Repository linode/manager, pull requests merged in 2018-05, with the labels that each got.

#3268 M3-392 & M3-393 - Volume actions tests
  e2e/config/custom-commands.js
  e2e/pageobjects/volume-detail.page.js
  e2e/specs/linodes/detail/detach-attach-volumes.spec.js
  e2e/specs/linodes/detail/edit-clone-resize-volumes.spec.js
  e2e/specs/search/search.spec.js
  src/features/linodes/LinodesDetail/LinodeVolumes/AttachVolumeDrawer.tsx
  src/features/linodes/LinodesDetail/LinodeVolumes/LinodeVolumes.tsx
Labels: QA

#3272 Expansion Panel - Fix component test
  src/components/ExpansionPanel/ExpansionPanel.spec.js
Labels: Testing

#3271 M3-404 - Linode Detail - Resize Tests
  e2e/pageobjects/create.js
  e2e/pageobjects/linode-detail-resize.page.js
  e2e/pageobjects/linode-detail.page.js
  e2e/pageobjects/page.js
  e2e/specs/linodes/detail/resize.spec.js
  src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
Labels: Testing

#3273 Add pre-commit bash script, add storybook tests to pre-commit
  .gitignore
  .travis.yml
  e2e/config/wdio.storybook.conf.js
  package.json
  scripts/pre-commit.sh
  src/components/IconTextLink/IconTextLink.spec.js
  yarn.lock
Labels: Testing

#3308 Add DomainDetail shell.
  src/App.tsx
  src/darkTheme.ts
  src/features/Domains/DomainActionMenu.tsx
  src/features/Domains/DomainCreateDrawer.tsx
  src/features/Domains/DomainDetail.tsx
  src/features/Domains/DomainRecordActionMenu.tsx
  src/features/Domains/DomainRecordDrawer.tsx
  src/features/Domains/DomainRecords.tsx
  src/features/Domains/DomainsLanding.tsx
  src/features/Domains/index.ts
  src/features/Domains/index.tsx
  src/services/domains.ts
  src/theme.ts
  src/types/Domain.ts
  src/utilities/defaultNumeric.tsx
Labels: Work in Progress

#3306 M3-414 - Networking E2E Tests
  e2e/pageobjects/linode-detail-networking.page.js
  e2e/pageobjects/list-linodes.js
  e2e/specs/linodes/detail/networking.spec.js
  src/features/linodes/LinodesDetail/LinodeNetworking/CreateIPv4Drawer.tsx
  src/features/linodes/LinodesDetail/LinodeNetworking/CreateIPv6Drawer.tsx
  src/features/linodes/LinodesDetail/LinodeNetworking/EditRDNSDrawer.tsx
  src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  src/features/linodes/LinodesDetail/LinodeNetworking/ViewIPDrawer.tsx
  src/features/linodes/LinodesDetail/LinodeNetworking/ViewRangeDrawer.tsx
Labels: QA, Testing

#3325 M3-382 - Select Component Tests
  src/components/Select/Select.spec.js
  src/components/Select/Select.stories.tsx
  src/components/Select/Select.tsx
Labels: QA, Testing

#3324 Add test setup/teardown script, testing documentation, misc fixes
  TESTING.md
  e2e/config/custom-commands.js
  e2e/config/wdio.conf.js
  e2e/config/wdio.storybook.conf.js
  e2e/constants.js
  e2e/pageobjects/linode-detail-volume.page.js
  e2e/pageobjects/volumes.page.js
  e2e/setup/setup.js
  e2e/setup/setup.spec.js
  e2e/specs/linodes/detail/backups.spec.js
  e2e/utils/config-utils.js
  package.json
  src/features/linodes/LinodesLanding/IPAddress.tsx
  yarn.lock
Labels: QA, Testing

#3300 Opacity change on drawer backdrop
  src/components/Drawer/Drawer.tsx
Labels: Add'tl Approval Required

#3344 M3-412 - Linode Settings Spec
  e2e/config/wdio.conf.js
  e2e/pageobjects/linode-detail-networking.page.js
  e2e/pageobjects/linode-detail-settings.page.js
  e2e/pageobjects/linode-detail-volume.page.js
  e2e/pageobjects/list-linodes.js
  e2e/pageobjects/page.js
  e2e/pageobjects/profile.js
  e2e/setup/setup.js
  e2e/specs/create/configure.linode.spec.js
  e2e/specs/create/create-volume.spec.js
  e2e/specs/linodes/detail/settings.spec.js
  e2e/specs/profile/clients.spec.js
  e2e/utils/common.js
  src/components/Notice/Notice.tsx
  src/features/Volumes/VolumeDrawer.tsx
  src/features/Volumes/VolumesLanding.tsx
  src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigsPanel.tsx
  src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
  src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx
  src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx
Labels: QA, Testing

#3358 M3-409 - Global Volume Create Drawer Tests
  e2e/pageobjects/linode-detail-volume.page.js
  e2e/specs/create/create-volume.spec.js
  src/features/Volumes/VolumeDrawer.tsx
Labels: QA, Testing

#3359 M3 573 - Log out Test
  e2e/pageobjects/page.js
  e2e/specs/usermenu/logout.spec.js
  src/features/TopMenu/UserMenu/UserMenu.tsx
Labels: QA

#3369 M3 562 - Clone from Existing Test
  e2e/pageobjects/configure-linode.js
  e2e/pageobjects/linode-detail-volume.page.js
  e2e/pageobjects/linode-detail.page.js
  e2e/pageobjects/list-linodes.js
  e2e/pageobjects/page.js
  e2e/setup/setup.spec.js
  e2e/specs/create/clone-from-existing-linode.spec.js
  src/features/linodes/LinodesCreate/LinodesCreate.tsx
  src/features/linodes/LinodesCreate/SelectLinodePanel.tsx
Labels: QA

#3393 M3-569 - Replace hardcoded timeouts, editDnsAction
  e2e/constants.js
  e2e/pageobjects/domain-detail/domain-details.page.js
  e2e/pageobjects/linode-detail/linode-detail-backups.page.js
  e2e/pageobjects/linode-detail/linode-detail-networking.page.js
  e2e/pageobjects/linode-detail/linode-detail-rebuild.page.js
  e2e/pageobjects/linode-detail/linode-detail-settings.page.js
  e2e/pageobjects/linode-detail/linode-detail-volume.page.js
  e2e/pageobjects/linode-detail/linode-detail.page.js
  e2e/pageobjects/list-domains.page.js
  e2e/pageobjects/list-linodes.js
  e2e/pageobjects/page.js
  e2e/pageobjects/profile.js
  e2e/pageobjects/search.page.js
  e2e/pageobjects/volumes.page.js
  e2e/setup/setup.spec.js
  e2e/specs/domains/list-domains.spec.js
  e2e/specs/linodes/detail/backups.spec.js
  e2e/specs/linodes/detail/create-volumes.spec.js
  e2e/specs/linodes/detail/detach-attach-volumes.spec.js
  e2e/specs/linodes/detail/edit-clone-resize-volumes.spec.js
  e2e/specs/linodes/detail/networking.spec.js
  e2e/specs/linodes/detail/rebuild.spec.js
  e2e/specs/linodes/linodes.spec.js
  e2e/specs/linodes/reboot-linodes.spec.js
  e2e/specs/profile/clients.spec.js
  e2e/specs/profile/tokens.spec.js
  e2e/specs/search/search-volumes.spec.js
  e2e/specs/search/search.spec.js
  src/features/Domains/DomainDetail.tsx
Labels: QA, Testing
