Repository linode/manager, pull requests merged in 2018-09, with the labels that each got.

#3783 M3-1261 - Support Landing and Tickets UI tests
  e2e/constants.js
  src/components/Tile/Tile.tsx
  src/features/Help/Panels/PopularPosts.tsx
  src/features/Help/Panels/SearchPanel.tsx
  src/features/Support/SupportTickets/SupportTicketsLanding.tsx
  src/features/Support/SupportTickets/TicketList.tsx
Labels: QA

#3779 M3-1049 - Refactor Volumes e2e tests
  e2e/pageobjects/linode-detail/linode-detail-volume.page.js
  e2e/specs/create/create-volume.spec.js
  e2e/specs/linodes/detail/detach-attach-volumes.spec.js
  e2e/specs/linodes/detail/edit-clone-resize-volumes.spec.js
  e2e/specs/search/search-volumes.spec.js
  src/features/Volumes/VolumesLanding.tsx
Labels: QA

#3786 update travis env variable
  .travis.yml
Labels: Build and Organization

#3788 Add support Landing/tickets e2e tests
  e2e/pageobjects/support/landing.page.js
  e2e/pageobjects/support/tickets.page.js
  e2e/specs/support/landing.spec.js
  e2e/specs/support/tickets.spec.js
Labels: QA

#3787 Add Lish SSH Keys E2E Tests
  e2e/constants.js
  e2e/pageobjects/profile/lish.page.js
  e2e/specs/profile/lish.spec.js
  src/features/Profile/LishSettings/LishSettings.tsx
Labels: QA

#3790 Ssh Key E2E Tests
  e2e/constants.js
  e2e/pageobjects/configure-linode.js
  e2e/pageobjects/profile/ssh-keys.page.js
  e2e/setup/setup.js
  e2e/specs/profile/ssh-keys.spec.js
  e2e/utils/common.js
  src/components/AccessPanel/AccessPanel.tsx
  src/features/Profile/SSHKeys/DeleteSSHKeyDialog.tsx
  src/features/Profile/SSHKeys/SSHKeys.tsx
Labels: QA

#3794 M3-1260 - Dashboard UI Tests
  e2e/pageobjects/dashboard.page.js
  e2e/specs/dashboard/dashboard.spec.js
  src/features/Dashboard/BlogDashboardCard/BlogDashboardCard.tsx
  src/features/Dashboard/Dashboard.tsx
  src/features/Dashboard/DashboardCard.tsx
  src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx
  src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx
  src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx
  src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx
  src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx
Labels: QA

#3781 M3-1315 apply new TableRow Component siteWide
  src/components/SelectionRow/SelectionRow.tsx
  src/components/TableRow/TableRow.tsx
  src/features/Account/AccountPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx
  src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx
  src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx
  src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx
  src/features/Domains/DomainsLanding.tsx
  src/features/NodeBalancers/NodeBalancersLanding.test.tsx
  src/features/NodeBalancers/NodeBalancersLanding.tsx
  src/features/StackScripts/SelectStackScriptPanel/PanelContent/StackScriptTableHead.tsx
  src/features/Users/UsersLanding.tsx
  src/features/linodes/LinodesLanding/LinodesListView.tsx
  src/index.css
  src/theme.ts
Labels: Work in Progress

#3815 Volume Configuration Test Fix
  e2e/pageobjects/linode-detail/linode-detail-volume.page.js
  e2e/specs/volumes/volume-configuration.spec.js
Labels: QA

#3812 Remove Joi for Yup.
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  package.json
  src/features/NodeBalancers/NodeBalancerCreate.tsx
  src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
  src/services/domains.ts
  src/services/index.test.ts
  src/services/index.ts
  src/services/linodes.ts
  src/services/nodebalancers.ts
  src/services/stackscripts.ts
  yarn.lock
Labels: Proof of Concept

#3849 Add smoke test flag, identify E2E smoke test specs
  e2e/config/wdio.conf.js
  e2e/pageobjects/dashboard.page.js
  e2e/specs/create/smoke-configure-linode.spec.js
  e2e/specs/create/smoke-create-volume.spec.js
  e2e/specs/dashboard/smoke-dashboard.spec.js
  e2e/specs/domains/smoke-list-domains.spec.js
  e2e/specs/images/smoke-create.spec.js
  e2e/specs/linodes/detail/smoke-settings.spec.js
  e2e/specs/linodes/smoke-linodes.spec.js
  e2e/specs/linodes/smoke-reboot-linodes.spec.js
  e2e/specs/nodebalancers/smoke-create.spec.js
  e2e/specs/search/smoke-search.spec.js
  e2e/specs/stackscripts/smoke-configure-stackscript.spec.js
  e2e/specs/support/smoke-tickets.spec.js
  e2e/specs/usermenu/smoke-logout.spec.js
Labels: QA

#3811 Cancel Request POC
  src/features/Domains/DomainCreateDrawer.tsx
  src/features/Domains/DomainZoneImportDrawer.tsx
  src/features/Domains/DomainsLanding.tsx
  src/services/domains.ts
  src/services/index.ts
  src/utilities/promiseToObservable.ts
Labels: Proof of Concept

#3850 M3-1356 - Firefox & MS Edge E2E Fixes
  e2e/config/browser-config.js
  e2e/config/wdio.conf.js
  e2e/pageobjects/page.js
  e2e/specs/account/restricted-users.spec.js
  e2e/specs/domains/smoke-list-domains.spec.js
  e2e/specs/linodes/detail/networking-allocate-ip.spec.js
  e2e/specs/usermenu/smoke-logout.spec.js
Labels: QA

#3853 Update PAT edit test
  e2e/specs/profile/tokens.spec.js
Labels: QA

#3844 Responsive Table Cells
  src/components/AccessPanel/AccessPanel.tsx
  src/components/Table/Table.tsx
  src/components/TableCell/TableCell.tsx
  src/components/TableRow/TableRow.tsx
  src/darkTheme.ts
  src/features/Account/AccountPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx
  src/features/Account/AccountPanels/RecentPaymentsPanel/RecentPaymentsPanel.tsx
  src/features/Account/InvoiceDetail/InvoiceDetail.tsx
  src/features/Domains/DomainRecords.tsx
  src/features/Domains/DomainsLanding.tsx
  src/features/Images/ImageRow.tsx
  src/features/Images/ImagesLanding.tsx
  src/features/NodeBalancers/NodeBalancersLanding.tsx
  src/features/Profile/APITokens/APITokenDrawer.tsx
  src/features/Profile/APITokens/APITokens.tsx
  src/features/Profile/OAuthClients/OAuthClients.tsx
  src/features/Profile/SSHKeys/SSHKeys.tsx
  src/features/StackScripts/SelectStackScriptPanel/PanelContent/StackScriptTableHead.tsx
  src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanelContent.tsx
  src/features/Support/SupportTickets/TicketList.tsx
  src/features/Users/UserPermissions.tsx
  src/features/Users/UsersLanding.tsx
  src/features/Volumes/VolumesLanding.tsx
  src/features/linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx
  src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
  src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigs.tsx
  src/features/linodes/LinodesDetail/LinodeSettings/LinodeDisks.tsx
  src/features/linodes/LinodesDetail/LinodeVolumes/LinodeVolumes.tsx
  src/features/linodes/LinodesLanding/LinodeRow.tsx
  src/theme.ts
Labels: Proof of Concept

#3862 M3-1354 - Automate Axe Accessibility Testing
  TESTING.md
  e2e/config/wdio.axe.conf.js
  e2e/specs/accessibility/axe.spec.js
  e2e/utils/accessibility.js
  package.json
  yarn.lock
Labels: QA

#3886 ActionMenu functional test - fix disabled with tooltip issue
  src/components/ActionMenu/ActionMenu.spec.js
Labels: QA
