Repository linode/manager, pull requests merged in 2019-06, with the labels that each got.

#5000 e2e: fix linode-no-image test
  e2e/specs/linodes/linode-no-image.spec.js
Labels: Testing

#5035 Maintenance Part 6: Copy Changes
  src/components/MaintenanceBanner/MaintenanceBanner.tsx
  src/features/linodes/LinodesLanding/SortableTableHead.tsx
Labels: Work in Progress

#4997 M3-1732 change: Performance metrics
  package.json
  patches/perfume.js+2.1.2.patch
  src/App.tsx
  src/components/withPerfMetrics/index.ts
  src/components/withPerfMetrics/withPerfMetrics.test.tsx
  src/components/withPerfMetrics/withPerfMetrics.tsx
  src/features/Events/EventsLanding.tsx
  src/perfMetrics.ts
  yarn.lock
Labels: Proof of Concept
