Repository linode/manager, pull requests merged in 2019-10, with the labels that each got.

#5507 OBJ-62: Drag-and-Drop file uploads
  packages/manager/package.json
  packages/manager/src/assets/icons/caution.svg
  packages/manager/src/assets/icons/cloudUpload.svg
  packages/manager/src/assets/icons/fileUpload.svg
  packages/manager/src/assets/icons/fileUploadComplete.svg
  packages/manager/src/assets/icons/uploadCaution.svg
  packages/manager/src/assets/icons/uploadPending.svg
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/index.ts
  packages/manager/src/features/ObjectStorage/requests.ts
  packages/manager/src/services/objectStorage/objects.ts
  packages/manager/src/types/ObjectStorage.ts
  packages/manager/yarn.lock
Labels: Do Not Merge

#5596 Change: Fix Longview Directory Structure
  packages/manager/src/features/Longview/LongviewLanding/AddClientDrawer.tsx
  packages/manager/src/features/Longview/LongviewLanding/LandingContent.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongivewLanding.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewActionMenu.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewDeleteDialog.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewTable.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewTableRows.tsx
  packages/manager/src/features/Longview/LongviewLanding/UpdateClientDrawer.tsx
  packages/manager/src/features/Longview/LongviewLanding/index.ts
Labels: Work in Progress

#5658 M3-3380 Updated syntax for linode details specs
  .travis.yml
  packages/manager/e2e/config/selenium-config.js
  packages/manager/e2e/pageobjects/linode-detail/linode-detail-backups.page.js
  packages/manager/e2e/pageobjects/linode-detail/linode-detail-networking.page.js
  packages/manager/e2e/pageobjects/linode-detail/linode-detail-rebuild.page.js
  packages/manager/e2e/pageobjects/linode-detail/linode-detail-volume.page.js
  packages/manager/e2e/pageobjects/linode-detail/linode-detail.page.js
  packages/manager/e2e/specs/linodes/detail/backups-create.spec.js
  packages/manager/e2e/specs/linodes/detail/backups.spec.js
  packages/manager/e2e/specs/linodes/detail/create-volumes.spec.js
  packages/manager/e2e/specs/linodes/detail/ip-transfer.spec.js
  packages/manager/e2e/specs/linodes/detail/networking-allocate-ip.spec.js
  packages/manager/e2e/specs/linodes/detail/networking-ip-sharing.spec.js
  packages/manager/e2e/specs/linodes/detail/networking.spec.js
  packages/manager/e2e/specs/linodes/detail/rebuild.spec.js
  packages/manager/e2e/specs/linodes/detail/rescue.spec.js
  packages/manager/e2e/specs/linodes/detail/resize.spec.js
  packages/manager/e2e/specs/linodes/linode-no-image.spec.js
  packages/manager/e2e/utils/common.js
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/components/Drawer/Drawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx
Labels: QA
