Repository linode/manager, pull requests merged in 2019-03, with the labels that each got.

#4571 [SPR-141] update NB nodes to support backup mode
  src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
  src/services/nodebalancers/configNodes.ts
  src/services/nodebalancers/nodebalancers.schema.ts
  src/types/NodeBalancer.ts
Labels: Do Not Merge

#4618 Integration Tests: Group By Tags Volumes/NodeBalancers, View all Links Dashboard, Booting Linode with No Image, Domains in Alphabetical Order, Ip Sharing
  e2e/config/custom-commands.js
  e2e/config/wdio.conf.js
  e2e/pageobjects/account/billing.page.js
  e2e/pageobjects/account/users.page.js
  e2e/pageobjects/configure-linode.js
  e2e/pageobjects/configure-stackscript.page.js
  e2e/pageobjects/dashboard.page.js
  e2e/pageobjects/linode-detail/linode-detail-networking.page.js
  e2e/pageobjects/linode-detail/linode-detail-rebuild.page.js
  e2e/pageobjects/linode-detail/linode-detail-volume.page.js
  e2e/pageobjects/linode-detail/linode-detail.page.js
  e2e/pageobjects/list-domains.page.js
  e2e/pageobjects/list-linodes.js
  e2e/pageobjects/list-nodebalancers.page.js
  e2e/pageobjects/list-stackscripts.page.js
  e2e/pageobjects/nodebalancers.page.js
  e2e/pageobjects/page.js
  e2e/pageobjects/profile.js
  e2e/pageobjects/profile/display.page.js
  e2e/pageobjects/volumes.page.js
  e2e/setup/setup.js
  e2e/specs/account/restricted-users.spec.js
  e2e/specs/create/create-from-stackscript-with-tags.spec.js
  e2e/specs/create/smoke-create-volume.spec.js
  e2e/specs/create/smoke-linode-with-tags.spec.js
  e2e/specs/dashboard/view-all-links.spec.js
  e2e/specs/domains/domains-listed-alphabetically.spec.js
  e2e/specs/domains/smoke-list-domains.spec.js
  e2e/specs/linodes/detail/backups-create.spec.js
  e2e/specs/linodes/detail/create-volumes.spec.js
  e2e/specs/linodes/detail/ip-transfer.spec.js
  e2e/specs/linodes/detail/networking-ip-sharing.spec.js
  e2e/specs/linodes/detail/rebuild.spec.js
  e2e/specs/linodes/detail/rescue.spec.js
  e2e/specs/linodes/linode-no-image.spec.js
  e2e/specs/linodes/smoke-linodes.spec.js
  e2e/specs/linodes/smoke-reboot-linodes.spec.js
  e2e/specs/nodebalancers/configurations.spec.js
  e2e/specs/profile/tokens.spec.js
  e2e/specs/profile/update-display.spec.js
  e2e/specs/search/search-tags.spec.js
  e2e/specs/stackscripts/stackscript-detail.spec.js
  e2e/specs/tagmanagement/group-by-tags-nodebalancer.spec.js
  e2e/specs/tagmanagement/group-by-tags-volumes.spec.js
  e2e/specs/tagmanagement/import-groups-and-group-by-tag-domains.spec.js
  e2e/utils/cleanup-account-data.js
  e2e/utils/common.js
  e2e/utils/config-utils.js
  src/components/TabLink/TabLink.tsx
  src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx
  src/features/Dashboard/ViewAllLink.tsx
  src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx
  src/features/NodeBalancers/NodeBalancersLanding/SortableTableHead.tsx
  src/features/Profile/Profile.tsx
  src/features/linodes/LinodesDetail/LinodeNetworking/IPSharingPanel.tsx
  storybook-test.yml
Labels: QA, Testing

#4647 M3-2507 Spike: fix timezone selection
  src/assets/timezones/timezones.ts
  src/features/Profile/DisplaySettings/TimezoneForm.tsx
Labels: Proof of Concept
