Repository linode/manager, pull requests merged in 2019-12, with the labels that each got.

#5605 Add: Longview Documentation
  packages/manager/src/features/Longview/LONGVIEW.md
Labels: Help Wanted, Work in Progress

#5863 [LV] Refactor overview gauges to separate files (with separate requests)
  package.json
  packages/manager/src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolRow.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/index.tsx
  packages/manager/src/features/Longview/shared/formatters.test.ts
  packages/manager/src/features/Longview/shared/formatters.ts
  packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
Labels: Proof of Concept

#5846 M3-3245 "Show All" on Linodes Landing
  packages/manager/src/components/Paginate.ts
  packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
  packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/utilities/storage.ts
Labels: Proof of Concept

#5945 clean yarn lock after merges in develop
  yarn.lock
Labels: Do Not Merge
