Repository linode/manager, pull requests merged in 2020-11, with the labels that each got.

#7062 M3-4603: Refinements for Create Database modal
  packages/manager/src/features/Databases/CreateDatabaseDialog/CreateDatabaseDialog.tsx
  packages/manager/src/features/Databases/CreateDatabaseDialog/SelectDBPlanPanel.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMaintenancePanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup_CMR.tsx
  packages/manager/src/utilities/initWindows.test.ts
  packages/manager/src/utilities/initWindows.ts
Labels: dbaas

#7079 DBaaS Details Settings tab feedback
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsLabelPanel.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMaintenancePanel.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsPasswordPanel.tsx
  packages/manager/src/store/databases/databases.actions.ts
Labels: dbaas

#7083 M3-4646: Implement Bucket Details Drawer
  packages/api-v4/src/object-storage/types.ts
  packages/manager/src/__data__/buckets.ts
  packages/manager/src/factories/objectStorage.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketActionMenu_CMR.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow_CMR.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable_CMR.tsx
Labels: CMR

#7093 Fix Database flag conditional in MainContent_CMR.tsx
  packages/manager/src/MainContent_CMR.tsx
Labels: dbaas

#7099 M3-4640: Remove "Delete" option from DBaaS backups table
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupActionMenu.tsx
Labels: dbaas

#7100 M3-4642: Maintenance window and day selection should be inline
  packages/manager/src/features/Databases/CreateDatabaseDialog/CreateDatabaseDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMaintenancePanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup_CMR.tsx
Labels: dbaas

#7067 Add copy explaining CC address restrictions
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/UpdateCreditCardDrawer/UpdateCreditCardDrawer.tsx
  packages/manager/src/features/GlobalNotifications/EmailBounce.tsx
Labels: Wait

#7111 Storybook cleanup
  packages/manager/src/components/Accordion/Accordion.stories.tsx
  packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.stories.tsx
  packages/manager/src/components/Breadcrumb/Breadcrumb.stories.tsx
  packages/manager/src/components/ColorPalette_CMR/ColorPalette_CMR.stories.tsx
  packages/manager/src/components/ColorPalette_CMR/ColorPalette_CMR.tsx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.stories.tsx
  packages/manager/src/components/Notice/Notice.stories.tsx
  packages/manager/src/components/TabbedPanel/TabbedPanel.stories.tsx
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/themeFactory.ts
Labels: Add'tl Approval Required, CMR

#7112 Reducing content width to 1100px
  packages/manager/src/MainContent_CMR.tsx
  packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
  packages/manager/src/components/DocumentationButton/DocumentationButton.tsx
  packages/manager/src/features/Domains/DomainRecords.tsx
  packages/manager/src/features/Domains/DomainRecordsWrapper.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ActiveConnections.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/Apache.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/ListeningServices.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINX.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/Network.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
  packages/manager/src/features/Profile/Profile.tsx
  packages/manager/src/features/Search/ResultGroup.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel_CMR.tsx
  packages/manager/src/features/Support/ExpandableTicketPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup_CMR.tsx
Labels: Work in Progress

#7137 CMR Documentation Button - Phase 1
  packages/manager/src/assets/icons/docs.svg
  packages/manager/src/components/CMR_DocumentationButton/DocumentationButton.stories.tsx
  packages/manager/src/components/CMR_DocumentationButton/DocumentationButton.tsx
  packages/manager/src/components/EntityHeader/EntityHeader.tsx
  packages/manager/src/components/LandingHeader/LandingHeader.tsx
  packages/manager/src/features/Footer/Footer_CMR.tsx
  packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
Labels: CMR

#7147 M3-4155: Fix Ada Chatbot overlapping buttons
  packages/manager/src/features/Footer/AdaLink.tsx
Labels: Bug

#7145 Linode List Landing Adjustments
  packages/manager/src/components/EntityHeader/EntityHeader.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/linodes/LinodesLanding/SortableTableHead_CMR.tsx
  packages/manager/src/themeFactory.ts
Labels: CMR

#7151 M3-4675 Change: Make time displays consistent
  packages/api-v4/src/images/types.ts
  packages/manager/src/components/BackupStatus/BackupStatus.tsx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.test.tsx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.tsx
  packages/manager/src/components/MaintenanceBanner/MaintenanceBanner.tsx
  packages/manager/src/components/StackScript/StackScript.test.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/constants.ts
  packages/manager/src/factories/images.ts
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel_CMR.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseEntityDetail.tsx
  packages/manager/src/features/Images/ImageRow.tsx
  packages/manager/src/features/Images/ImageRow_CMR.tsx
  packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.tsx
  packages/manager/src/features/Kubernetes/ClusterList/ClusterRow_CMR.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
  packages/manager/src/features/Managed/Monitors/IssueDay.test.tsx
  packages/manager/src/features/Managed/Monitors/IssueDay.tsx
  packages/manager/src/features/NotificationCenter/NotificationSection.tsx
  packages/manager/src/features/NotificationCenter/PastDue.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow_CMR.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow_CMR.tsx
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
  packages/manager/src/features/Profile/APITokens/APITokenTable_CMR.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevicesTable.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevicesTable_CMR.tsx
  packages/manager/src/features/Search/ResultRow.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel_CMR.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptsSection.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptsSection.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptsSection_CMR.tsx
  packages/manager/src/features/Support/ExpandableTicketPanel.tsx
  packages/manager/src/features/Support/SupportTickets/TicketRow.tsx
  packages/manager/src/features/Support/SupportTickets/TicketRow_CMR.tsx
  packages/manager/src/features/Vlans/VlanDetail/VlanEntityDetail.tsx
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
  packages/manager/src/utilities/format-date-iso8601.ts
  packages/manager/src/utilities/formatDate.ts
Labels: CMR
