Repository linode/manager, pull requests merged in 2021-12, with the labels that each got.

#8054 M3-5551: Refactor logic for displaying NVMe-related chips
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/features/Volumes/types.ts
Labels: Block Storage Migrations

#8060 M3-5609 PasswordInput component story
  packages/manager/src/components/PasswordInput/PasswordInput.stories.mdx
  packages/manager/src/components/PasswordInput/PasswordInput.stories.tsx
  packages/manager/src/components/PasswordInput/PasswordInput.tsx
Labels: Storybook

#8059 M3-5580: Update Storybook Entity Table
  packages/manager/src/components/EntityTable/EntityTable.stories.mdx
  packages/manager/src/components/EntityTable/EntityTable.stories.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
Labels: UI, Storybook

#8063 M3-5588 Drawer component story
  packages/manager/.storybook/preview.tsx
  packages/manager/package.json
  packages/manager/src/components/Drawer/Drawer.stories.mdx
  packages/manager/src/components/Drawer/Drawer.stories.tsx
  packages/manager/src/components/NotificationDrawer.stories.mdx
  packages/manager/src/components/NotificationDrawer/NotificationDrawer.stories.mdx
  packages/manager/src/components/NotificationDrawer/NotificationDrawer.tsx
  packages/manager/src/components/NotificationDrawer/index.ts
  packages/manager/src/eventMessageGenerator.test.ts
  packages/manager/src/factories/events.ts
  packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useNotificationData.tsx
  packages/manager/src/features/NotificationCenter/index.tsx
  packages/manager/src/store/events/event.selectors.test.ts
Labels: Storybook

#8071 M3-5610: Storybook for Radios
  packages/manager/src/components/Radio/Radio.stories.mdx
  packages/manager/src/components/Radio/Radio.stories.tsx
  packages/manager/src/components/Radio/Radio.tsx
  packages/manager/src/themeFactory.ts
Labels: Storybook

#8067 Cypress Stability Improvements
  packages/manager/cypress.json
  packages/manager/cypress/integration/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/integration/images/create-linode-from-image.spec.ts
  packages/manager/cypress/support/api/common.ts
  packages/manager/cypress/support/cypresshelpers.ts
Labels: e2e

#8074 M3-5600: Chips in Storybook
  packages/manager/src/components/Chip.stories.mdx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
Labels: Storybook

#8069 M3-5585: Add Story for Navigation
  packages/manager/.storybook/main.js
  packages/manager/.storybook/preview.tsx
  packages/manager/package.json
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/SideMenu.stories.mdx
  packages/manager/src/components/SideMenu.tsx
  packages/manager/src/components/TopMenu.stories.mdx
  packages/manager/src/components/UserMenu.stories.mdx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/queries/profile.ts
  yarn.lock
Labels: Storybook

#8080 DBAAS1-74: JS Client & Types scaffolding for DBaaS
  packages/api-v4/src/databases/databases.ts
  packages/api-v4/src/databases/types.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/validation/src/databases.schema.ts
Labels: DBaaS

#8068 M3-5591: Add Story for Paper
  packages/manager/src/components/Paper.stories.mdx
Labels: Storybook

#8085 DBaaS1-89: Add factories and mocks for DBaaS
  packages/manager/src/factories/databaseBackups.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/store/databases/databases.requests.ts
Labels: DBaaS

#8072 M3-5582: Update stories for Forms
  packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
  packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.tsx
  packages/manager/src/components/EnhancedSelect/Select.tsx
  packages/manager/src/components/TagCell/AddTag.tsx
  packages/manager/src/components/TagsInput/TagsInput.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.tsx
  packages/manager/src/components/TextField.stories.mdx
  packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
Labels: Storybook

#8076 M3-5636: Updates Object Storage cancellation copy
  packages/manager/src/features/Account/EnableObjectStorage.tsx
Labels: UI

#8081 DBAAS1-75: React Query for DBaaS
  packages/api-v4/.eslintrc.js
  packages/api-v4/src/databases/databases.ts
  packages/api-v4/src/databases/types.ts
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/queries/databases.ts
Labels: React Query, DBaaS

#8097 Small types & factories fixes/updates
  packages/api-v4/src/databases/databases.ts
  packages/api-v4/src/databases/types.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/databases.ts
Labels: DBaaS

#8095 DBAAS1-76: Add Databases icon to primary nav
  packages/manager/src/assets/icons/entityIcons/database.svg
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
Labels: DBaaS

#8096 DBAAS1-80: Database Detail Data Scaffolding
  packages/api-v4/src/databases/types.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseEntityDetail.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: DBaaS
