Repository linode/manager, pull requests merged in 2021-04, with the labels that each got.

#7553 M3-4956 bare metal create
  packages/api-v4/src/regions/types.ts
  packages/manager/src/constants.ts
  packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/store/linodeType/linodeType.requests.ts
  packages/manager/src/store/regions/regions.reducer.ts
  packages/manager/src/utilities/isProdApi.ts
Labels: Bare Metal

#7561 For Release: Schema and typing revisions to allow interface.label to be null
  packages/api-v4/src/linodes/linodes.schema.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/ConfigRow.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
Labels: VLAN

#7572 Fix for linodeInterfaceSchema test
  packages/api-v4/src/linodes/linodes.schema.ts
Labels: VLAN

#7569 M3-5044: Machine Images feature flag
  packages/api-v4/src/account/types.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
Labels: Machine Images

#7574 Update README.md
  README.md
Labels: Work in Progress

#7578 M3-5043 Change: ImagesLanding split into 2 tables
  packages/api-v4/src/images/types.ts
  packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.tsx
  packages/manager/src/components/EntityTable/APIPaginatedTable.tsx
  packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
  packages/manager/src/components/EntityTable/GroupedEntitiesByTag_CMR.tsx
  packages/manager/src/components/EntityTable/ListEntities_CMR.tsx
  packages/manager/src/components/EntityTable/types.ts
  packages/manager/src/factories/images.ts
  packages/manager/src/features/Images/ImageRow.tsx
  packages/manager/src/features/Images/ImagesActionMenu.tsx
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Machine Images

#7575 M3-5045: Images Create page
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageCreateContainer.tsx
  packages/manager/src/features/Images/ImagesCreate/index.ts
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/Images/index.tsx
Labels: Machine Images

#7591 Demo feedback: Remove copy re: disk MB limits
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
Labels: Machine Images

#7597 M3-5077: Rename Image deployment actions
  packages/manager/src/features/Images/ImagesActionMenu.tsx
Labels: Machine Images

#7600 Add beta notice for image uploads
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
Labels: UI

#7603 M3-5079: More precise helper text on Images Landing
  packages/manager/src/features/Images/ImagesLanding.tsx
Labels: Machine Images, UI

#7619 M3-5041: Make icon more vibrant on hover
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/themeFactory.ts
Labels: UI

#7621 M3-5013: Change OBJ drag and drop instructional text color
  packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx
Labels: UI

#7617 M3-4957: "Last Backup" cell for Bare Metal instances
  packages/manager/src/components/BackupStatus/BackupStatus.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowBackupCell.tsx
Labels: Bare Metal

#7605 M3-5062: VLAN Refinements in Linode Create flow
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallBanner.tsx
  packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/utilities/arrayToDelimiterSeparatedList/arrayToList.test.ts
  packages/manager/src/utilities/arrayToDelimiterSeparatedList/arrayToList.ts
  packages/manager/src/utilities/arrayToDelimiterSeparatedList/index.ts
  packages/manager/src/utilities/doesRegionSupportVLANs.ts
Labels: UI, VLAN
