Repository linode/manager, pull requests merged in 2021-07, with the labels that each got.

#7730 M3-5261: Successful payment UI updates
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCardPayment.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/Paypal.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/queries/accountBilling.ts
Labels: UI

#7745 Storybook can read .mdx files
  packages/manager/.storybook/main.js
  packages/manager/.storybook/preview.tsx
  packages/manager/package.json
  packages/manager/src/components/Button/button.stories.mdx
  packages/manager/src/components/Button/button.stories.tsx
  yarn.lock
Labels: Work in Progress

#7742 M3-5030: Fix Formatting Error when Showing rDNS Error
  packages/manager/src/components/TextField.tsx
Labels: UI

#7741 M3-5281: Add loading spinner while GPay loads
  packages/manager/src/components/HelpIcon/HelpIcon.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Billing/Providers/GooglePay.ts
Labels: UI

#7740 M3-5285: Update the Edit Credit Card drawer to use new API endpoint
  packages/api-v4/src/account/payments.ts
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/UpdateCreditCardDrawer/UpdateCreditCardDrawer.tsx
  packages/manager/src/queries/accountPayment.ts
Labels: JS Client

#7736 Table consistency tickets
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/components/EntityTable/EntityTableHeader.tsx
  packages/manager/src/components/EntityTable/GroupedEntitiesByTag.tsx
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/components/LineGraph/MetricsDisplay.tsx
  packages/manager/src/components/SelectableTableRow/SelectableTableRow.tsx
  packages/manager/src/components/Skeleton/Skeleton.stories.tsx
  packages/manager/src/components/Table/Table.stories.tsx
  packages/manager/src/components/TableRowEmptyState/TableRowEmptyState.tsx
  packages/manager/src/components/TableRowError/TableRowError.tsx
  packages/manager/src/components/TableRowLoading/TableRowLoading.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupTableRow.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseEntityDetail.tsx
  packages/manager/src/features/Domains/DomainRecords.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.tsx
  packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx
  packages/manager/src/features/EntityTransfers/TransfersTable.tsx
  packages/manager/src/features/Events/EventsLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDevicesTable.tsx
  packages/manager/src/features/Profile/APITokens/APITokenDrawer.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.test.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
  packages/manager/src/features/StackScripts/Partials/StackScriptTableHead.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptsSection.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Volumes/ListGroupedVolumes.tsx
  packages/manager/src/features/linodes/CloneLanding/Configs.tsx
  packages/manager/src/features/linodes/CloneLanding/Disks.tsx
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
  packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/linodes/LinodesLanding/TableWrapper.tsx
  packages/manager/src/themes.ts
Labels: UI

#7748 Google Pay refinements
  packages/api-v4/src/account/types.ts
  packages/manager/.env.example
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
  packages/manager/src/constants.ts
  packages/manager/src/features/Billing/BillingDetail.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.test.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCardPayment.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.test.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/Paypal.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/CreditCardInfo.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Billing/Providers/GooglePay.ts
  packages/manager/src/queries/accountPayment.ts
  packages/manager/src/utilities/creditCard.test.ts
  packages/manager/src/utilities/creditCard.ts
Labels: UI

#7744 M3-4721: Changes to how account balances are communicated in app
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.test.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
Labels: UI

#7763 M3-5226: LKE Detail page UI tweaks
  packages/manager/src/assets/icons/map-pin-icon.svg
  packages/manager/src/assets/icons/mini-kube.svg
  packages/manager/src/assets/icons/price-icon.svg
  packages/manager/src/components/StatusIndicator/StatusIndicator.tsx
  packages/manager/src/components/StatusIndicator/index.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeStatusIndicator.tsx
Labels: UI

#7768 M3-5314: Fix Kubernetes Create Active State and Refactor
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Kubernetes/index.tsx
  packages/manager/src/features/linodes/index.tsx
Labels: Bug

#7762 M3-5298: Change Default Payment Method
  packages/api-v4/src/account/payments.ts
  packages/api-v4/src/account/types.ts
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/factories/accountPayment.ts
Labels: Google Pay, JS Client

#7771 Allow dismissing of Google Pay available notice in Payment Methods paper
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
Labels: Google Pay, UI

#7767 Show card info for GPay in Payment Methods paper
  packages/api-v4/src/account/types.ts
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCardPayment.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
Labels: Google Pay, UI

#7769 Clean up Linode Settings
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx
  packages/manager/src/themeFactory.ts
Labels: UI

#7765 Remove remaining CMR flag dependency and clean up Accordion
  packages/manager/src/components/Accordion/Accordion.stories.tsx
  packages/manager/src/components/Accordion/Accordion.tsx
  packages/manager/src/components/Accordion/AccordionCMR.tsx
  packages/manager/src/components/ExtendedAccordion/ExtendedAccordion.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/Apache.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINX.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/Network.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesGraphs.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
  packages/manager/src/features/Profile/Settings/Settings.tsx
  packages/manager/src/features/Support/ExpandableTicketPanel.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
Labels: UI

#7718 M3-5254: Improve presentation of info & fix error-surfacing bug in LinodeConfigDialog
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.test.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
Labels: Bug

#7755 M3-5072: Google Pay
  packages/api-v4/src/account/payments.ts
  packages/api-v4/src/account/types.ts
  packages/manager/.env.example
  packages/manager/package.json
  packages/manager/src/assets/icons/payment/gPayButton.svg
  packages/manager/src/components/HelpIcon/HelpIcon.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
  packages/manager/src/constants.ts
  packages/manager/src/containers/SummaryPanels.styles.ts
  packages/manager/src/eventMessageGenerator.ts
  packages/manager/src/factories/accountPayment.ts
  packages/manager/src/factories/index.ts
  packages/manager/src/features/Billing/BillingDetail.test.tsx
  packages/manager/src/features/Billing/BillingDetail.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.test.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCardPayment.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.test.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/Paypal.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/index.ts
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/CreditCardInfo.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/UpdateCreditCardDrawer/UpdateCreditCardDrawer.tsx
  packages/manager/src/features/Billing/Providers/GooglePay.ts
  packages/manager/src/hooks/useScript.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/accountBilling.ts
  packages/manager/src/queries/accountPayment.ts
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
  packages/manager/src/utilities/creditCard.test.ts
  packages/manager/src/utilities/creditCard.ts
  packages/manager/src/utilities/formikErrorUtils.test.ts
  packages/manager/src/utilities/formikErrorUtils.ts
  packages/validation/src/account.schema.ts
  yarn.lock
Labels: Google Pay, UI

#7757 M3-5220 & 5213: Firewall Details table header and Longview Plan chip
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
  packages/manager/src/themeFactory.ts
Labels: UI

#7775 Log Google Pay Errors to Sentry
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Billing/Providers/GooglePay.ts
Labels: Google Pay

#7785 M3-5328: Change CVV to Security code and Fix Feature Flag Off Issue
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/UpdateCreditCardDrawer/UpdateCreditCardDrawer.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
  packages/manager/src/themeFactory.ts
Labels: Google Pay

#7777 M3-5319: Make sure Bare Metal plans appear for accounts w/ appropriate tag
  packages/manager/scripts/buildRequests.js
  packages/manager/src/cachedData/types.json
  packages/manager/src/components/Table/Table.stories.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/store/linodeType/linodeType.requests.ts
Labels: Bare Metal

#7793 Minor UI fixes
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/features/StackScripts/Partials/StackScriptTableHead.tsx
  packages/manager/src/features/StackScripts/StackScriptRowHelpers.tsx
Labels: UI

#7795 M3-5277: My Profile / Account dropdown changes
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
Labels: UI

#7791 Update Google Pay notice icon
  packages/manager/src/assets/icons/payment/googlePay.svg
  packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
Labels: Google Pay, UI

#7803 Fix GPay mark regression in Add Payment Method drawer
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
Labels: Google Pay, UI

#7796 M3-5244: Standardize secret token modals
  packages/manager/src/components/Dialog/Dialog.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDisplayDialog.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
  packages/manager/src/features/Profile/OAuthClients/Modals.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
  packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
  packages/manager/src/features/Profile/SecretTokenDialog/index.tsx
Labels: UI

#7788 Fixed styles for the Markdown Accordion of the Ticket modal
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/MarkdownReference.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
Labels: UI

#7798 M3-5332: Refine handling of payment_due notifications in Notifications drawer
  packages/manager/src/features/NotificationCenter/NotificationData/RenderNotification.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
Labels: UI

#7756 M3-5177: Use React Query for Account Settings
  packages/manager/src/App.test.tsx
  packages/manager/src/App.tsx
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
  packages/manager/src/containers/accountSettings.container.ts
  packages/manager/src/containers/withBackupCTA.container.ts
  packages/manager/src/features/Account/EnableManaged.tsx
  packages/manager/src/features/Account/EnableObjectStorage.tsx
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Backups/BackupsCTA.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesCreate/types.ts
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/hooks/useAccountManagement.ts
  packages/manager/src/hooks/useReduxLoad.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/accountSettings.ts
  packages/manager/src/store/accountSettings/accountSettings.actions.ts
  packages/manager/src/store/accountSettings/accountSettings.reducer.test.ts
  packages/manager/src/store/accountSettings/accountSettings.reducer.ts
  packages/manager/src/store/accountSettings/accountSettings.requests.ts
  packages/manager/src/store/backupDrawer/index.ts
  packages/manager/src/store/index.ts
  packages/manager/src/utilities/testHelpersStore.ts
Labels: React Query

#7802 M3-5248: Change look of Selectable Linode Plan to fix wrapping
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/features/Databases/CreateDatabaseDialog/SelectDBPlanPanel.tsx
  packages/manager/src/features/LinodeConfigSelectionDrawer/LinodeConfigSelectionDrawer.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectBackupPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectLinodePanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
Labels: UI
