Repository linode/manager, pull requests merged in 2021-05, with the labels that each got.

#7623 M3-4917: Firewalls Linodes tab refinements
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
Labels: UI

#7629 M3-5128: Add docs link in "Last Backup" Bare Metal column tooltips
  packages/manager/src/components/BackupStatus/BackupStatus.tsx
Labels: Bare Metal, UI

#7630 fix Add Disk button styling in RescueDialog
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx
Labels: UI

#7626 M3-5070: SideMenu scrollbar overlap
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/SideMenu.tsx
Labels: UI

#7628 M3-5035: Add box rule and adjust spacing in account billing
  packages/manager/src/components/core/Paper.tsx
  packages/manager/src/containers/SummaryPanels.styles.ts
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
Labels: UI

#7631 M3-4862: Styling for EventsLanding table column headers
  packages/manager/src/features/Events/EventsLanding.tsx
Labels: UI

#7651 Multiple UI updates
  packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevices.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevicesDialog.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevicesTable.tsx
  packages/manager/src/features/StackScripts/StackScriptRowHelpers.tsx
  packages/manager/src/features/TopMenu/iconStyles.ts
Labels: UI

#7646 M3-5121 payment method row component storybook
  packages/manager/.storybook/main.js
  packages/manager/.storybook/preview.tsx
  packages/manager/package.json
  packages/manager/src/assets/icons/payment/amex.svg
  packages/manager/src/assets/icons/payment/discover.svg
  packages/manager/src/assets/icons/payment/googlePay.svg
  packages/manager/src/assets/icons/payment/jcb.svg
  packages/manager/src/assets/icons/payment/mastercard.svg
  packages/manager/src/assets/icons/payment/payPal.svg
  packages/manager/src/assets/icons/payment/visa.svg
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/PaymentMethodRow/index.ts
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.tsx
  packages/manager/src/themeFactory.ts
  yarn.lock
Labels: UI

#7659 M3-5123: Update Credit Card Drawer
  packages/manager/src/assets/icons/accepted-cards.svg
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/UpdateCreditCardDrawer/UpdateCreditCardDrawer.tsx
Labels: UI

#7647 M3-5057: TextField error message positioning and width
  packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
  packages/manager/src/components/Breadcrumb/FinalCrumb.tsx
  packages/manager/src/components/EditableText/EditableText.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailsBreadcrumb.tsx
Labels: UI

#7660 M3-5129: Added connect with LISH copy to rescue modal for Bare Metal instances
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/BareMetalRescue.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
Labels: Bare Metal

#7655 M3-5083: Dismissible Images pricing banner
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/Images/ImagesPricingBanner.tsx
Labels: Machine Images
