Repository linode/manager, pull requests merged in 2021-10, with the labels that each got.

#7972 Autoscaler UI fixes
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
Labels: UI, LKE

#7968 M3-5483: Add "Upgrade to NVMe" chip for volumes pending migration
  packages/api-v4/src/account/types.ts
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: UI, Block Storage Migrations

#7967 M3-5486: Add Upgrade Volumes Dialog
  packages/api-v4/src/volumes/migrations.ts
  packages/api-v4/src/volumes/types.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/UpgradeVolumesDialog.tsx
  packages/manager/src/features/linodes/types.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/volumesMigrations.ts
Labels: @linode/api-v4, Block Storage Migrations

#7970 M3-5488: Add Notification in drawer when a user has Volumes scheduled for migration
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: e2e, UI, Block Storage Migrations

#8012 M3-5555: Re-request notifications after successful enqueueing of volumes
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/UpgradeVolumesDialog.tsx
Labels: Block Storage Migrations

#8014 M3-5556: Refresh Redux upon volume_migrate starting & finishing
  packages/manager/src/store/volume/volume.events.ts
Labels: Block Storage Migrations
