Repository linode/manager, pull requests merged in 2021-06, with the labels that each got.

#7677 M3-5061: Create Linode UI Refinements
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
Labels: UI

#7689 Fix paper padding regression in Create Cluster
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
Labels: UI

#7688 M3-5063: Linode Configs modal refinements
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
  packages/manager/src/themes.ts
Labels: UI

#7687 M3-5208: Fix Domains table header for large accounts
  packages/manager/src/components/EntityTable/APIPaginatedTable.tsx
  packages/manager/src/components/EntityTable/EntityTableHeader.tsx
  packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
  packages/manager/src/features/Domains/DomainTableRow.tsx
  packages/manager/src/features/Domains/DomainsLanding.test.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
Labels: UI

#7696 #7691: New Ticket Dialog: fixed clearing form state after submit
  packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
Labels: Bug

#7700 M3-5202: Fix IP Sharing for large accounts
  packages/manager/src/queries/linodes.ts
Labels: Bug

#7697 Cleanup Divider Component
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
  packages/manager/src/components/CheckoutBar/DisplaySection.tsx
  packages/manager/src/components/CheckoutBar/DisplaySectionList.tsx
  packages/manager/src/components/CheckoutBar/styles.ts
  packages/manager/src/components/ColorPalette_CMR/ColorPalette_CMR.tsx
  packages/manager/src/components/LongviewLineGraph/LongviewLineGraph.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/components/TabLinkList/TabLinkList.tsx
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/components/core/Divider.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Domains/DomainDrawer.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderNotification.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/EnableTwoFactorForm.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
  packages/manager/src/features/linodes/CloneLanding/Details.tsx
  packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingIPTransferPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
Labels: UI

#7692 M3-5203: Remove "beta" tag from Machine Images
  packages/manager/src/features/Images/ImageUpload.tsx
Labels: UI, Wait

#7615 M3-5071: Drag & Drop Image uploads
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
  packages/manager/src/components/FileUploader/FileUploader.tsx
  packages/manager/src/components/LinodeCLIModal/LinodeCLIModal.tsx
  packages/manager/src/components/LinodeCLIModal/index.tsx
  packages/manager/src/components/Prompt/Prompt.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImageUploadSuccessDialog.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageCreateContainer.tsx
  packages/manager/src/features/Images/ImagesCreate/ImagesPricingCopy.tsx
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/Images/requests.ts
  packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/reducer.ts
  packages/manager/src/hooks/useAuthentication.ts
  packages/manager/src/store/index.ts
  packages/manager/src/store/pendingUpload/index.ts
  packages/manager/src/themeFactory.ts
  packages/manager/src/utilities/stringUtils.ts
Labels: Machine Images

#7693 M3-5126: Update make payment drawer UI
  packages/api-v4/src/account/types.ts
  packages/manager/src/assets/icons/payment/gPayButton.svg
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCardPayment.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.test.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/Paypal.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/CreditCardInfo.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
Labels: UI

#7711 M3-5133: Fix bug that prevented /dev/sdh Block Device from showing up
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
Labels: Bug

#7715 Fix console warning for Divider custom props
  packages/manager/src/components/core/Divider.tsx
Labels: UI

#7712 Clean up EntityTables CMR
  packages/manager/src/components/EntityTable/EntityTable.stories.tsx
  packages/manager/src/components/EntityTable/EntityTable.tsx
  packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
  packages/manager/src/components/EntityTable/GroupedEntitiesByTag.tsx
  packages/manager/src/components/EntityTable/GroupedEntitiesByTag_CMR.tsx
  packages/manager/src/components/EntityTable/ListEntities.tsx
  packages/manager/src/components/EntityTable/ListEntities_CMR.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx
Labels: UI

#7721 M3-5259: Referral page changes
  packages/manager/src/assets/referrals/step-1.svg
  packages/manager/src/assets/referrals/step-2.svg
  packages/manager/src/assets/referrals/step-3.svg
  packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Profile/Referrals/Referrals.tsx
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
Labels: UI

#7723 M3-5269: Fix Object Storage landing table UI bugs
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketActionMenu.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
Labels: Bug
