Repository linode/manager, pull requests merged in 2021-09, with the labels that each got.

#7906 Fix Linode Maintenance Query
  CHANGELOG.md
  packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/accountMaintenance.ts
Labels: Bug, Urgent

#7900 M3-5402: Functionality for EU Contract on NodeBalancer Create
  packages/manager/src/factories/accountAgreements.ts
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/accountAgreements.ts
  packages/manager/src/queries/base.ts
Labels: GDPR Compliance

#7914 M3-5443: Update Linode logo used in MaintenanceScreen.tsx
  packages/manager/src/components/MaintenanceScreen.tsx
Labels: UI

#7901 M3-5400: EU contract functionality for Linode create
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
Labels: UI, GDPR Compliance

#7912 M3-5403: Functionality for EU Contract on Volumes Create
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/accountAgreements.ts
Labels: GDPR Compliance

#7886 M3-5427: Vertically center icons and texts in dropdown
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
  packages/manager/src/components/EnhancedSelect/components/SingleValue.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
Labels: UI

#7916 M3-5407: Remove EU Contract on Disk/Config clone
  packages/manager/src/features/linodes/CloneLanding/Details.tsx
Labels: GDPR Compliance

#7910 M3-5404: Functionality for EU Contract on Bucket Create
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx
Labels: GDPR Compliance

#7874 Add additional client-side Firewall rule label validation
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
Labels: UI

#7922 M3-5446: Simplify copy on API Maintenance screen
  packages/manager/src/components/MaintenanceScreen.tsx
Labels: UI

#7911 M3-5405: Functionality for EU Contract on Image Create
  packages/manager/src/components/FileUploader/FileUploader.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: GDPR Compliance

#7926 M3-5445: Change font size for Credentials and Contacts copy
  packages/manager/src/features/Managed/Contacts/Contacts.tsx
  packages/manager/src/features/Managed/Credentials/CredentialList.tsx
Labels: UI

#7899 M3-5436: Fix action buttons being disabled upon Firewall creation for restricted users
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
Labels: Bug, UI

#7904 M3-5430: Banner for upcoming API maintenance
  packages/manager/src/factories/statusPage.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/GlobalNotifications/APIMaintenanceBanner.tsx
  packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: UI

#7929 Undo label required for Firewall rules
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
Labels: UI

#7921 M3-5444: Add optional prop to Textfield and cleanup optional fields
  packages/manager/src/components/TextField.tsx
  packages/manager/src/features/Account/CloseAccountDialog.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
  packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
  packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
Labels: UI

#7928 M30-5401: EU Contract Cluster Create
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
Labels: GDPR Compliance

#7934 M3-5458: Adjustments for API Scheduled Maintenance feature flag and banner
  packages/manager/src/factories/statusPage.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/GlobalNotifications/APIMaintenanceBanner.tsx
  packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx
Labels: UI

#7897 M3-5434: Fix remaining Button position issues in Drawers and Modals
  packages/manager/src/features/Account/EnableManaged.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/Users/UserDetail.tsx
  packages/manager/src/features/Users/UserProfile.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/EditRDNSDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
  packages/manager/src/queries/accountUsers.ts
Labels: UI

#7947 M3-5438: Fix bug preventing Linode Configuration changes
  packages/validation/src/linodes.schema.ts
Labels: Bug

#7918 M3-5431 EU Model Contract agreement banner + notification
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/components/ConfirmationDialog/index.ts
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
  packages/manager/src/components/SupportLink/SupportLink.tsx
  packages/manager/src/context/complianceUpdateContext.ts
  packages/manager/src/factories/notification.ts
  packages/manager/src/features/Account/Agreements/EUAgreementCheckbox.tsx
  packages/manager/src/features/GlobalNotifications/ComplianceBanner.tsx
  packages/manager/src/features/GlobalNotifications/ComplianceUpdateModal.tsx
  packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.test.ts
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: GDPR Compliance

#7927 GDPR Clean Up and Error Handling
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
  packages/manager/src/queries/accountAgreements.ts
Labels: GDPR Compliance

#7956 GDPR Event Message
  packages/manager/src/eventMessageGenerator.ts
Labels: GDPR Compliance

#7955 E2e run workflow on staging and PRs with e2e label
  .github/workflows/e2e.yml
Labels: e2e

#7957 Merge Feature/gdpr compliance branch into Develop
  packages/api-v4/src/account/account.ts
  packages/api-v4/src/account/types.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/components/ConfirmationDialog/index.ts
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
  packages/manager/src/components/FileUploader/FileUploader.tsx
  packages/manager/src/components/SupportLink/SupportLink.tsx
  packages/manager/src/context/complianceUpdateContext.ts
  packages/manager/src/eventMessageGenerator.ts
  packages/manager/src/factories/accountAgreements.ts
  packages/manager/src/factories/notification.ts
  packages/manager/src/features/Account/Agreements/EUAgreementCheckbox.tsx
  packages/manager/src/features/Account/Agreements/withAgreements.ts
  packages/manager/src/features/GlobalNotifications/ComplianceBanner.tsx
  packages/manager/src/features/GlobalNotifications/ComplianceUpdateModal.tsx
  packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.test.ts
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
  packages/manager/src/hooks/useAccountManagement.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/accountAgreements.ts
  packages/manager/src/queries/base.ts
  packages/manager/src/store/authentication/authentication.helpers.ts
  packages/manager/src/utilities/formatRegion.ts
Labels: e2e

#7958 Find-and-replace GiB -> GB for Volumes
  packages/api-v4/src/volumes/volumes.ts
  packages/manager/src/documentation.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.ts
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CloneVolumeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/store/selectors/getSearchEntities.ts
Labels: e2e

#7931 M3-5456: Cleanup storybook entry for entity icons
  packages/manager/src/components/EntityIcon/EntityIcon.stories.mdx
  packages/manager/src/components/EntityIcon/EntityIcon.stories.tsx
  packages/manager/src/components/EntityIcon/EntityIcon.tsx
  packages/manager/src/components/EntityIcon/EntityIconStory.tsx
Labels: UI

#7932 M3-5441: Fix Create Access Key button order
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
Labels: UI

#7960 M3-5481: Remove "File System Path" column from Volumes landing table
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
Labels: UI, Block Storage Migrations

#7961 M3-5424: Improve experience when attaching a VLAN when creating a Linode from a Backup or Clone
  packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
Labels: Bug, e2e

#7935 M3-5448: Global changes to help icon
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/components/BackupStatus/BackupStatus.tsx
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/HelpIcon/HelpIcon.tsx
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx
  packages/manager/src/features/Images/ImageSelect.tsx
  packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
Labels: UI

#7964 M3-5482: Add NVMe chip for NVMe volumes
  packages/api-v4/src/volumes/types.ts
  packages/manager/src/__data__/volumes.ts
  packages/manager/src/factories/volume.ts
  packages/manager/src/features/Volumes/RenderVolumeData.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.test.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: UI, Block Storage Migrations

#7966 E2e test updates and workflow update
  .github/workflows/e2e.yml
  packages/manager/cypress/integration/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/cypress/integration/objectStorage/access-keys.spec.ts
  packages/manager/cypress/integration/objectStorage/buckets.spec.ts
Labels: e2e

#7965 M3-5322: Fix formatting of long strings in Domains TXT Record
  packages/manager/src/features/Domains/DomainRecords.tsx
Labels: Bug, UI

#7969 M3-5485: Upgrade volumes banner on Linode details
  packages/api-v4/src/account/types.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: e2e, UI, Block Storage Migrations

#7954 M3-5452: Add support for Autoscaling Node Pools
  packages/api-v4/src/kubernetes/nodePools.ts
  packages/api-v4/src/kubernetes/types.ts
  packages/manager/src/__data__/nodePools.ts
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.test.ts
  packages/manager/src/features/Kubernetes/types.ts
  packages/validation/src/kubernetes.schema.ts
Labels: UI, LKE
