Repository linode/manager, pull requests merged in 2021-08, with the labels that each got.

#7813 M3-5355: Fix users with active promotions unable unable to edit their account
  CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
Labels: Bug, Urgent

#7816 M3-5346: GooglePay display in Safari
  packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
Labels: UI

#7809 Improve Table Loading and Table Error Styles
  packages/manager/src/components/ErrorState/ErrorState.tsx
  packages/manager/src/components/Skeleton/Skeleton.tsx
Labels: UI

#7804 M3-5335: Reduce spacing for NodeBalancer Settings
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings/NodeBalancerSettings.tsx
Labels: UI

#7823 M3-5362: Update Linode logo on TPA
  packages/manager/src/assets/logo/logo-footer.svg
Labels: UI

#7814 M3-5331: Remove redundant headers
  packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.test.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.test.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
  packages/manager/src/features/Users/UsersLanding.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeActivity/LinodeActivity.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeActivity/LinodeActivity.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettings.tsx
Labels: UI

#7819 M3-5164: Fix delay in graph reporting when navigating to Linodes from search
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
Labels: Bug

#7824 Do not display the Google Pay notice when loading payment methods
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
Labels: UI, Google Pay

#7832 M3-5372: Add edit credit card notice to Add Payment Method drawer
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
Labels: Google Pay

#7792 M3-5297: Delete a Payment Method
  packages/api-v4/src/account/payments.ts
  packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
Labels: JS Client, Google Pay

#7826 M3 5339: Improve firewall error message for unsupported hosts
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
Labels: UI

#7828 M3-5118: Linode Create flow filtering for Bare Metal plans
  packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/utilities/doesRegionSupportBlockStorage.test.ts
  packages/manager/src/utilities/doesRegionSupportBlockStorage.ts
  packages/manager/src/utilities/doesRegionSupportFeature.test.ts
  packages/manager/src/utilities/doesRegionSupportFeature.ts
  packages/manager/src/utilities/doesRegionSupportVLANs.ts
Labels: Bare Metal

#7829 UI fixes for /account/billing
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
Labels: UI

#7817 M3-5353: Volume Create - remove checkout sidebar
  packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/features/Volumes/VolumeCreate/VolumeCreate.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
Labels: UI

#7850 M3-5360: Fix Root Device bugs in LinodeConfigDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
Labels: Bug

#7845 Update firewalls text
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
Labels: UI

#7840 M3-5381: Fix disabled action buttons in dark mode
  packages/manager/src/components/FileUploader/FileUploader.tsx
  packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx
Labels: UI

#7838 M3-5321: Add restricted user support for Firewalls
  packages/api-v4/src/account/types.ts
  packages/manager/src/factories/grants.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDevicesTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleActionMenu.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
Labels: UI

#7846 M3-5274 & M3-5275: Updated Button Placement and Styles
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/components/Drawer/Drawer.tsx
  packages/manager/src/features/Account/CloseAccountSetting.tsx
  packages/manager/src/features/Account/EnableObjectStorage.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
  packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
  packages/manager/src/features/Managed/MonitorDrawer.tsx
  packages/manager/src/features/Profile/APITokens/APITokenDrawer.tsx
  packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthFormDrawer.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeyCreationDrawer.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
  packages/manager/src/features/Users/CreateUserDrawer.tsx
  packages/manager/src/features/Users/UserProfile.tsx
  packages/manager/src/features/Volumes/VolumeAttachmentDrawer.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/VolumeConfigForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/VolumesActionsPanel.tsx
Labels: UI

#7855 M3-5392: Fix primary button loading state in dark mode
  packages/manager/src/themes.ts
Labels: Bug, UI

#7854 M3-5391: Fixed Object Storage warning message styles in dark mode
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
Labels: UI

#7863 M3-5395: Fix users unable to set a label and description when capturing an Image
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
Labels: Bug

#7862 M3-5394: Fix Kubernetes Debian images showing up in the Rebuild Dialog
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
Labels: Bug

#7859 Remove redundant headers for Managed
  packages/manager/src/features/Managed/Contacts/Contacts.tsx
  packages/manager/src/features/Managed/Credentials/CredentialList.tsx
Labels: UI

#7842 M3-5313: Fix @linode/api-v4 import issue
  packages/api-v4/src/support/types.ts
Labels: Bug, JS Client

#7856 M3-5273: Update Button Placements and Styles (includes Migration modal fixes)
  packages/manager/src/components/Dialog/Dialog.tsx
  packages/manager/src/features/Domains/DeleteDomain.tsx
  packages/manager/src/features/Domains/DomainDrawer.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/VolumesActionsPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/features/linodes/MigrateLanding/CautionNotice.tsx
  packages/manager/src/features/linodes/MigrateLanding/ConfigureForm.tsx
  packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
Labels: UI

#7852 M3-5390: Update Add a Payment drawer to support multiple payment methods of same type
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/constants.ts
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/UpdateCreditCardDrawer/UpdateCreditCardDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/UpdateCreditCardDrawer/index.ts
  packages/manager/src/features/Billing/Providers/GooglePay.ts
Labels: Google Pay

#7866 M3-5384: Add support for multiple payment methods in make payment drawer
  packages/manager/cypress/integration/account/google-pay.spec.ts
  packages/manager/src/assets/icons/payment/googlePay.svg
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
  packages/manager/src/components/SelectionCard/CardBase.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCardPayment.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Databases/CreateDatabaseDialog/SelectDBPlanPanel.tsx
  packages/manager/src/features/LinodeConfigSelectionDrawer/LinodeConfigSelectionDrawer.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectAppPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectBackupPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectLinodePanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
Labels: UI, Google Pay

#7865 M3-5368: Fix support ticket input with different font sizes
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TicketReply.tsx
Labels: Bug, UI

#7875 M3-5278: Update buttons for Domains
  packages/manager/src/features/Domains/DeleteDomain.tsx
  packages/manager/src/features/Domains/DomainDrawer.tsx
  packages/manager/src/features/Domains/DomainRecordDrawer.tsx
  packages/manager/src/features/Domains/DomainRecords.tsx
Labels: UI

#7867 M3-3874: Tighten spacing for Support Ticket Details
  packages/manager/src/components/Accordion/Accordion.tsx
  packages/manager/src/components/LinearProgress/LinearProgress.tsx
  packages/manager/src/features/Support/AttachFileForm.test.tsx
  packages/manager/src/features/Support/AttachFileForm.tsx
  packages/manager/src/features/Support/AttachFileListItem.test.tsx
  packages/manager/src/features/Support/AttachFileListItem.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.test.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyActions.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TabbedReply.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
  packages/manager/src/features/Support/TicketAttachmentList.tsx
Labels: UI

#7876 Make Payment Drawer UI fixes
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/SelectionCard/CardBase.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
Labels: UI

#7870 M3-5375: Handle API maintenance mode
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/MaintenanceScreen.tsx
  packages/manager/src/request.tsx
  packages/manager/src/store/globalErrors/types.ts
Labels: UI
