Repository linode/manager, pull requests merged in 2021-11, with the labels that each got.

#8013 M3-5515: Fix button placement and improved spacing in Add Node Pool Drawer
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/AddNodePoolDrawer/AddNodePoolDrawer.tsx
Labels: UI

#8003 M3-5451: Changes to Cluster Details for HA Clusters and Kubernetes Dashboard
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/kubernetes/kubernetes.ts
  packages/api-v4/src/kubernetes/types.ts
  packages/manager/src/assets/icons/reset.svg
  packages/manager/src/constants.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/HACheckbox.test.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/HACheckbox.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeClusterDialog.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.test.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/queries/kubernetesConfig.ts
  packages/manager/src/queries/kubernetesDashboard.ts
  yarn.lock
Labels: LKE

#8019 Fix HA Cluster chip in dark mode
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
Labels: LKE

#8011 M3-5553: Revisions to Account Maintenance Page for Volumes
  packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceLanding.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.test.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
Labels: UI, Block Storage Migrations

#8017 M3-5559: Button alignment in the Enable All Backups drawer
  packages/manager/src/features/Backups/BackupDrawer.tsx
Labels: UI

#8027 M3-5565: Fix button order in the Add Linode to Firewall drawer
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
Labels: e2e, UI

#8002 M3-5543: Add "Upgrade Pending" chip to Volumes
  packages/manager/src/eventMessageGenerator_CMR.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
Labels: Block Storage Migrations

#7984 Block Storage Migrations feature branch
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/volumes/migrations.ts
  packages/api-v4/src/volumes/types.ts
  packages/manager/src/__data__/volumes.ts
  packages/manager/src/components/MaintenanceBanner/MaintenanceBanner.tsx
  packages/manager/src/components/OrderBy.tsx
  packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
  packages/manager/src/eventMessageGenerator.ts
  packages/manager/src/eventMessageGenerator_CMR.tsx
  packages/manager/src/factories/accountMaintenance.ts
  packages/manager/src/factories/volume.ts
  packages/manager/src/features/Account/Maintenance/MaintenanceLanding.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.test.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
  packages/manager/src/features/Volumes/RenderVolumeData.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.test.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/UpgradeVolumesDialog.tsx
  packages/manager/src/features/linodes/types.ts
  packages/manager/src/hooks/useOrder.test.tsx
  packages/manager/src/hooks/useOrder.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/volumesMigrations.ts
  packages/manager/src/store/volume/volume.events.ts
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
Labels: UI, Block Storage Migrations

#7996 M3-5519: Add PayPal as recurring payment method
  packages/api-v4/src/account/payments.ts
  packages/api-v4/src/account/types.ts
  packages/manager/package.json
  packages/manager/src/assets/icons/payment/payPal.svg
  packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
  packages/manager/src/constants.ts
  packages/manager/src/factories/accountPayment.ts
  packages/manager/src/features/Billing/BillingDetail.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalErrorBoundary.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/mocks/serverHandlers.ts
  yarn.lock
Labels: PayPal

#8024 M3-5537: Table row height too high in Safari
  packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx
Labels: UI

#8030 M3-5575: Updates to Payment Method Logic and UI
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
  packages/manager/src/features/Billing/Providers/GooglePay.ts
Labels: UI, PayPal

#7986 Use react-paypal-js for one time PayPal payments
  packages/manager/.env.example
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalErrorBoundary.tsx
Labels: PayPal

#8032 Feature/paypal
  packages/api-v4/src/account/payments.ts
  packages/api-v4/src/account/types.ts
  packages/manager/.env.example
  packages/manager/package.json
  packages/manager/src/assets/icons/payment/payPal.svg
  packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
  packages/manager/src/constants.ts
  packages/manager/src/factories/accountPayment.ts
  packages/manager/src/features/Billing/BillingDetail.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalErrorBoundary.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Billing/Providers/GooglePay.ts
  packages/manager/src/mocks/serverHandlers.ts
  yarn.lock
Labels: e2e, PayPal

#8037 M3-5530: Add IPv6 ranges to IP Transfer modal
  packages/api-v4/src/networking/networking.ts
  packages/manager/src/factories/linodes.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.test.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/networking.ts
Labels: Elastic IPs

#8042 M3-5535: Handle IPv6 events language
  packages/manager/src/eventMessageGenerator.ts
Labels: Elastic IPs

#8010 M3-5529: Update "Add an IP Address" drawer and provide for ability to add IPv6 ranges in it
  packages/api-v4/src/networking/networking.ts
  packages/api-v4/src/networking/types.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Elastic IPs

#8039 M3-5531: Handle IPv6 Range Deletion
  packages/api-v4/src/linodes/ips.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPActions.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPConfirm.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
Labels: Elastic IPs

#8023 M3-5560: Add Delete Button to NodeBalancer Detail in Settings
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings/NodeBalancerSettings.tsx
Labels: e2e

#8043 Feature/Elastic IP
  packages/api-v4/src/linodes/ips.ts
  packages/api-v4/src/networking/networking.ts
  packages/api-v4/src/networking/types.ts
  packages/manager/src/eventMessageGenerator.ts
  packages/manager/src/factories/linodes.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPActions.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPConfirm.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.test.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/networking.ts
Labels: Elastic IPs

#8041 M3-5576: Fix row height and extra spacing around ActionMenu in Safari
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/TableCell/TableCell.tsx
  packages/manager/src/features/Domains/DomainTableRow.tsx
  packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx
  packages/manager/src/features/EntityTransfers/TransfersTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
  packages/manager/src/features/Images/ImageRow.tsx
  packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.tsx
  packages/manager/src/features/Managed/Contacts/ContactsRow.tsx
  packages/manager/src/features/Managed/Credentials/CredentialList.tsx
  packages/manager/src/features/Managed/Monitors/MonitorRow.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessRow.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
  packages/manager/src/features/Profile/APITokens/APITokens.test.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.test.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.test.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptActionMenu.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx
  packages/manager/src/features/Users/UsersLanding.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.style.ts
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/linodes/LinodesLanding/SortableTableHead.tsx
  packages/manager/src/themeFactory.ts
Labels: UI

#8050 M3-5492 & M3-5547: Axis label UI refinements
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/components/LineGraph/NewMetricDisplay.styles.ts
Labels: UI

#8053 M3-5579: Update Entity Detail in Storybook
  packages/manager/src/components/EntityDetail/EntityDetail.stories.mdx
  packages/manager/src/components/EntityDetail/EntityDetail.stories.tsx
Labels: UI, Storybook

#8047 M3-5567: Add warning when booting into Rescue Mode that Cloud Firewall will not be enabled
  packages/api-v4/src/linodes/linodes.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/BareMetalRescue.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx
  packages/manager/src/queries/linodeFirewalls.ts
Labels: Bare Metal, UI
