Repository linode/manager, pull requests merged in 2022-11, with the labels that each got.

#8596 M3-5968: Revised copy on Database Backups tab
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
Labels: DBaaS

#8597 M3-5977: Improve User Permissions Page for Large Accounts
  CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/Paginate.ts
  packages/manager/src/factories/grants.ts
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Enhancement, Urgent

#8554 M3-5935: Fix MUI v5 UI Issues
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/components/EnhancedSelect/components/SelectControl.tsx
  packages/manager/src/components/HighlightedMarkdown/__snapshots__/HighlightedMarkdown.test.tsx.snap
  packages/manager/src/components/TextField.tsx
  packages/manager/src/components/core/Divider.tsx
  packages/manager/src/components/core/Grid.ts
  packages/manager/src/components/core/Grid.tsx
  packages/manager/src/containers/SummaryPanels.styles.ts
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
  packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
  packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeyCreationDrawer.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/VolumeConfigForm.tsx
  packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
Labels: UI

#8569 M3-5501: [BUILD] Update the changelog generation script
  scripts/generate_changelog.py
Labels: Build and Organization

#8584 React Query for Volumes - Linode Storage
  packages/api-v4/src/volumes/types.ts
  packages/manager/src/features/Volumes/VolumeAttachmentDrawer.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeStorage/LinodeStorage.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/queries/base.ts
  packages/manager/src/queries/domains.ts
  packages/manager/src/queries/volumes.ts
Labels: React Query

#8603 M3-5101: Storybook beta stories
  packages/manager/src/components/BetaChip/BetaChip.stories.mdx
  packages/manager/src/components/BetaChip/BetaChip.tsx
  packages/manager/src/components/BetaChip/index.ts
  packages/manager/src/components/Chip.stories.mdx
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.stories.mdx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
Labels: Storybook

#8585 M3-5505: [DOCS] Automate developers site changlog PR
  scripts/generate_changelog.py
  scripts/publish_changelog.sh
Labels: Build and Organization

#8611 staging → master for v1.80.0
  CHANGELOG.md
  docs/development-guide/01-repository-structure.md
  docs/development-guide/04-component-library.md
  docs/development-guide/13-coding-standards.md
  package.json
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/api-v4/src/stackscripts/types.ts
  packages/manager/package.json
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/components/BetaChip/BetaChip.stories.mdx
  packages/manager/src/components/BetaChip/BetaChip.tsx
  packages/manager/src/components/BetaChip/index.ts
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/Button/button.stories.mdx
  packages/manager/src/components/Chip.stories.mdx
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.stories.mdx
  packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.tsx
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMenuItem.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeClusterSpecs.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Lish/Glish.tsx
  packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/StackScriptSelectionRow.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
  packages/manager/src/features/Support/AttachFileForm.tsx
  packages/manager/src/features/linodes/CloneLanding/Details.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/MutateDrawer/MutateDrawer.tsx
  scripts/generate_changelog.py
  scripts/publish_changelog.sh
Labels: Release

#8604 Update Webpack and Related Webpack Packages
  package.json
  packages/manager/.storybook/main.js
  packages/manager/.storybook/webpack.config.js
  packages/manager/config/webpack.config.dev.js
  packages/manager/config/webpack.config.prod.js
  packages/manager/package.json
  yarn.lock
Labels: dependencies

#8616 M3-5996: Cluster Pricing UI updates
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.test.tsx
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.test.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
  packages/manager/src/features/linodes/LinodesCreate/types.ts
  packages/manager/src/utilities/stringUtils.test.ts
  packages/manager/src/utilities/stringUtils.ts
Labels: One Click Clusters

#8624 M3-5997: Update OCA drawer to support clusters
  packages/manager/src/features/OneClickApps/AppDetailDrawer.test.tsx
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
Labels: One Click Clusters

#8623 M3-5995: UDF copy updates
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/HelpIcon/HelpIcon.tsx
  packages/manager/src/components/PasswordInput/HideShowText.tsx
  packages/manager/src/components/PasswordInput/PasswordInput.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/LabelField.tsx
Labels: Marketplace

#8610 M3-5197: React Query for Volumes - Misc Final Changes
  packages/manager/src/containers/volumes.container.ts
  packages/manager/src/containers/volumesRequests.container.ts
  packages/manager/src/features/Search/SearchLanding.test.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/withStoreSearch.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/ModeSelection.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/features/Volumes/WithEvents.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/ConfigRow.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.container.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesDetail/types.ts
  packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
  packages/manager/src/features/linodes/MigrateLanding/CautionNotice.tsx
  packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.tsx
  packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
  packages/manager/src/hooks/useEntities.ts
  packages/manager/src/hooks/useExtendedLinode.ts
  packages/manager/src/hooks/useReduxLoad.ts
  packages/manager/src/hooks/useVolumes.ts
  packages/manager/src/mocks/testBrowser.ts
  packages/manager/src/queries/volumes.ts
  packages/manager/src/store/index.ts
  packages/manager/src/store/selectors/getSearchEntities.ts
  packages/manager/src/store/volume/volume.actions.ts
  packages/manager/src/store/volume/volume.events.ts
  packages/manager/src/store/volume/volume.reducer.ts
  packages/manager/src/store/volume/volume.requests.ts
  packages/manager/src/store/volume/volume.selector.ts
  packages/manager/src/utilities/getEntityByIDFromStore.test.ts
  packages/manager/src/utilities/getEntityByIDFromStore.ts
Labels: React Query

#8615 M3-5958: [Changed] Landing page 2 column layout – adjust spacing
  packages/manager/src/components/Placeholder/Placeholder.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinksSection.tsx
Labels: UI

#8620 M3-5994: [Changed] One Click Cluster App Card
  packages/manager/src/components/SelectionCard/CardBase.test.tsx
  packages/manager/src/components/SelectionCard/CardBase.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/features/linodes/LinodesCreate/AppPanelSection.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx
Labels: UI, Marketplace
