Repository linode/manager, pull requests merged in 2022-08, with the labels that each got.

#8418 (Experimental) Detect excessive Linode APIv4 requests during Cypress tests
  packages/manager/cypress/support/index.js
  packages/manager/cypress/support/request-tracking.ts
Labels: Testing

#8468 M3-5869: Marketplace UI Refinement: Create form
  packages/manager/src/factories/stackscripts.ts
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/AppInfo.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
Labels: UI

#8472 M3-5143: Fix Linode Backups tab error
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
Labels: Bug

#8481 M3-4919: Fix browser Back button behavior on the User Permissions tab
  packages/manager/src/features/Users/UserDetail.tsx
Labels: Bug

#8494 Fix Cypress Testing with new `api-v4` and `validation` changes
  packages/manager/cypress/tsconfig.json
Labels: Urgent

#8499 M3-5880: "Any/All" option in StackScript Create flow
  packages/manager/src/features/Images/ImageSelect.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
Labels: StackScripts with Private Images

#8500 M3-5881: Add `Any/All` Option on StackScripts Landing
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx
Labels: StackScripts with Private Images

#8501 M3-5882: Show `Any/All` Chip on StackScripts Details
  packages/manager/src/components/StackScript/StackScript.tsx
Labels: StackScripts with Private Images

#8503 M3-5902: StackScript Create tooltips edits
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
Labels: StackScripts with Private Images

#8504 M3-5884: Linode Create - Deploy StackScripts with Private Image
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Labels: StackScripts with Private Images

#8497 M3-5919: Update Storybook and Add New Webpack 5 Loader
  packages/manager/.storybook/main.js
  packages/manager/.storybook/webpack.config.js
  packages/manager/package.json
  yarn.lock
Labels: Storybook

#8507 Hotfix StackScripts User Defined Field Input Bug
  CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Labels: Bug, Urgent

#8512 M3-5911: Marketplace UI Refinement: Searching and filtering analytics
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
  packages/manager/src/utilities/ga.ts
Labels: Marketplace

#8518 Fix Type-to-Confirm edge case bug
  packages/manager/src/components/TypeToConfirm/TypeToConfirm.tsx
Labels: Bug

#8492 M3-5839: Add More Insightful Credit Card Expiration Date Validation
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
  packages/manager/src/utilities/creditCard.test.ts
  packages/validation/src/account.schema.ts
Labels: Enhancement
