Repository linode/manager, pull requests merged in 2022-07, with the labels that each got.

#8429 M3-5180: Refactor Domains Landing to begin React Query integration
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Domains/DisableDomainDialog.tsx
  packages/manager/src/features/Domains/DomainTableRow.tsx
  packages/manager/src/features/Domains/DomainsLanding.test.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/queries/domains.ts
  packages/manager/src/queries/linodes.ts
Labels: React Query

#8450 M3-5180: React Query for Domains Drawer Refactors (Part 2)
  packages/api-v4/src/domains/domains.ts
  packages/api-v4/src/domains/types.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Domains/CloneDomainDrawer.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Domains/DeleteDomain.test.tsx
  packages/manager/src/features/Domains/DeleteDomain.tsx
  packages/manager/src/features/Domains/DisableDomainDialog.tsx
  packages/manager/src/features/Domains/DomainActionMenu.test.tsx
  packages/manager/src/features/Domains/DomainActionMenu.tsx
  packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
  packages/manager/src/features/Domains/DomainDetail/index.tsx
  packages/manager/src/features/Domains/DomainDrawer.tsx
  packages/manager/src/features/Domains/DomainTableRow.tsx
  packages/manager/src/features/Domains/DomainZoneImportDrawer.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
  packages/manager/src/features/Domains/EditDomainDrawer.test.tsx
  packages/manager/src/features/Domains/EditDomainDrawer.tsx
  packages/manager/src/features/Domains/domainUtils.ts
  packages/manager/src/features/Domains/index.tsx
  packages/manager/src/queries/domains.ts
  packages/manager/src/store/domainDrawer/index.test.ts
  packages/manager/src/store/domainDrawer/index.ts
  packages/manager/src/store/index.ts
  packages/manager/src/utilities/errorUtils.ts
Labels: React Query

#8427 M3-5722: Image upload max size bug on Linux
  packages/manager/src/components/FileUploader/FileUploader.tsx
Labels: Bug

#8425 M3-5462: Keys and secrets modals update UI
  packages/manager/cypress/integration/objectStorage/access-key.e2e.spec.ts
  packages/manager/cypress/integration/objectStorage/access-keys.smoke.spec.ts
  packages/manager/src/assets/icons/download.svg
  packages/manager/src/components/CopyableAndDownloadableTextField.tsx
  packages/manager/src/components/DownloadTooltip.tsx
  packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
Labels: UI

#8451 M3-5180: React Query for Domains Event Handler
  packages/manager/src/App.tsx
  packages/manager/src/queries/domains.ts
Labels: React Query

#8446 Button Placement in User Permissions and `ActionsPanel.tsx` Clean Up
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/components/RenderGuard.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
Labels: UI

#8448 M3-5771: Add Cypress tests for account security questions
  packages/manager/cypress/integration/account/security-questions.spec.ts
  packages/manager/cypress/support/intercepts/profile.ts
Labels: Alt Pay at Signup

#8462 M3-5180: React Query for Domains - Remove Redux, Allow Search, Attach to Ticket
  packages/manager/src/App.tsx
  packages/manager/src/containers/domains.container.ts
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Domains/DomainRecordDrawer.tsx
  packages/manager/src/features/Domains/DomainRecords.tsx
  packages/manager/src/features/Domains/DomainRecordsWrapper.tsx
  packages/manager/src/features/Search/SearchLanding.test.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/withStoreSearch.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
  packages/manager/src/features/TagImport/TagImportDrawer.test.tsx
  packages/manager/src/features/TagImport/TagImportDrawer.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/hooks/useDomains.ts
  packages/manager/src/hooks/useEntities.ts
  packages/manager/src/hooks/useReduxLoad.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/mocks/testBrowser.ts
  packages/manager/src/queries/domains.ts
  packages/manager/src/store/accountManagement/accountManagement.requests.ts
  packages/manager/src/store/domains/domains.actions.ts
  packages/manager/src/store/domains/domains.container.ts
  packages/manager/src/store/domains/domains.events.ts
  packages/manager/src/store/domains/domains.helpers.ts
  packages/manager/src/store/domains/domains.reducer.test.ts
  packages/manager/src/store/domains/domains.reducer.ts
  packages/manager/src/store/domains/domains.requests.ts
  packages/manager/src/store/index.ts
  packages/manager/src/store/selectors/entitiesErrors.ts
  packages/manager/src/store/selectors/entitiesLoading.ts
  packages/manager/src/store/selectors/getEntitiesWithGroupsToImport.test.tsx
  packages/manager/src/store/selectors/getEntitiesWithGroupsToImport.tsx
  packages/manager/src/store/selectors/getSearchEntities.ts
  packages/manager/src/store/tagImportDrawer/index.ts
  packages/manager/src/utilities/getEntityByIDFromStore.ts
  packages/manager/src/utilities/shouldDisplayGroupImportCTA.ts
Labels: React Query

#8444 M3-5092: `hosted-git-info` - CVE-2021-23362
  package.json
  yarn.lock
Labels: dependencies, security
