Repository linode/manager, pull requests merged in 2022-04, with the labels that each got.

#8298 M3-5719: Fixed StackScripts with deprecated Images not showing
  packages/manager/src/components/StackScript/StackScript.test.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
  packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/store/image/image.helpers.test.ts
  packages/manager/src/store/image/image.helpers.ts
Labels: Bug

#8303 M3-5412: Events page refinements
  packages/manager/src/features/Events/EventRow.test.tsx
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/Events/EventsLanding.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useEventInfo.ts
  packages/manager/src/features/Profile/DisplaySettings/GravatarIcon.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/queries/accountUsers.ts
  packages/manager/src/utilities/getEventsActionLink.ts
  packages/manager/src/utilities/getEventsActionLinkStrings.ts
Labels: UI

#8082 [M3-5534, M3-5692, M3-5709, M3-5760]: IPv6 sharing support
  packages/api-v4/src/networking/networking.ts
  packages/api-v4/src/networking/types.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.test.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
Labels: Elastic IPs

#8319 Revert #8298 - Community StackScript Issues
  packages/manager/src/components/StackScript/StackScript.test.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
  packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/store/image/image.helpers.test.ts
  packages/manager/src/store/image/image.helpers.ts
Labels: Bug, Urgent

#8325 replaced the word in with empty string
  packages/manager/src/features/linodes/MigrateLanding/CautionNotice.tsx
Labels: Bug, UI

#8323 M3-5776: Cloud Manager doesn't give feedback when resizing a Node Pool over the 100 node limit
  packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.tsx
Labels: UI, LKE

#8310 M3-5733: Support Ticket Refinements
  packages/manager/src/components/TabLinkList/TabLinkList.tsx
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/components/core/ReachTab.ts
  packages/manager/src/components/core/ReachTab.tsx
  packages/manager/src/components/core/ReachTabList.ts
  packages/manager/src/components/core/ReachTabList.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.test.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
  packages/manager/src/features/Support/SupportTickets/TicketRow.tsx
Labels: UI

#8326 M3-5282: Linode Detail - Networking - Improved stats empty state
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/DNSResolvers.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraph.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/StatsPanel.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/StatsPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/TotalTraffic.tsx
  packages/manager/src/hooks/useLinodeNetworkInfo.ts
  packages/manager/src/queries/linodes.ts
Labels: UI, React Query

#8306 M3-5775: Add support for DBaaS Maintenance Windows
  packages/api-v4/src/databases/types.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/validation/src/databases.schema.ts
Labels: DBaaS

#8333 Fix Events Table Loading State
  packages/manager/src/features/Events/EventsLanding.tsx
Labels: Bug, UI

#8340 M3-5773: Adjust spacing on DBaaS Settings page
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
Labels: DBaaS

#8346 M3-5790: Login & Authentication Scaffolding for Security Questions and Phone Verification
  packages/manager/src/components/ErrorState/ErrorState.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
Labels: UI

#8348 feature flagged the beta chips for DBaaS
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
Labels: UI, DBaaS

#8360 M3-5808: Adjustments to Database Create flow and types due to API changes
  packages/api-v4/src/databases/types.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: DBaaS
