Repository linode/manager, pull requests merged in 2022-06, with the labels that each got.

#8393 Remove notification menu content from DOM when not expanded
  packages/manager/src/components/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/features/TopMenu/NotificationButton.tsx
Labels: Testing

#8405 Fix Notification Menu bug
  CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/features/TopMenu/NotificationButton.tsx
Labels: Bug

#8396 Database Create Remove Duplicate State
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
Labels: DBaaS

#8403 M3-5835: Allow users to migrate unattached volumes
  packages/manager/src/features/Volumes/UpgradeVolumeDialog.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/Volumes/VolumesActionMenu.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/UpgradeVolumesDialog.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Block Storage Migrations

#8412 M3-5833: Make Notifications badge a true circle
  packages/manager/src/features/TopMenu/NotificationButton.tsx
  packages/manager/src/features/TopMenu/iconStyles.ts
Labels: UI

#8381 M3-5795: Phone Verification Component
  packages/api-v4/src/profile/profile.ts
  packages/api-v4/src/profile/types.ts
  packages/manager/config/webpack.config.prod.js
  packages/manager/package.json
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
  packages/manager/src/components/LinkButton.tsx
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/factories/profile.ts
  packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.test.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/countries.ts
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/helpers.ts
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/styles.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/profile.ts
  packages/validation/package.json
  packages/validation/src/profile.schema.ts
  packages/validation/webpack.config.js
  yarn.lock
Labels: Alt Pay at Signup

#8398 M3-5842: SMS Messaging Opt Out
  packages/api-v4/src/profile/profile.ts
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SMSMessaging.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/profile.ts
  yarn.lock
Labels: Alt Pay at Signup

#8370 M3-5794: Security Questions component
  packages/api-v4/src/profile/profile.ts
  packages/api-v4/src/profile/types.ts
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
  packages/manager/src/factories/profile.ts
  packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/Answer.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/Question.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/QuestionAndAnswerPair.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/SecurityQuestions.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/index.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/types.ts
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/utilities.ts
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/securityQuestions.ts
Labels: Alt Pay at Signup

#8416 Security Questions and SMS Verification Fixes and Updates
  packages/api-v4/src/profile/profile.ts
  packages/manager/src/components/LinkButton.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/Question.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/QuestionAndAnswerPair.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/SecurityQuestions.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/validation/src/profile.schema.ts
Labels: Alt Pay at Signup

#8415 Merge `feature/alt-payment-methods` ➡️ `develop`
  packages/api-v4/src/profile/profile.ts
  packages/api-v4/src/profile/types.ts
  packages/manager/config/webpack.config.prod.js
  packages/manager/package.json
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
  packages/manager/src/components/ErrorState/ErrorState.tsx
  packages/manager/src/components/LinkButton.tsx
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/factories/profile.ts
  packages/manager/src/features/OneClickApps/FakeSpec.ts
  packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.test.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/countries.ts
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/helpers.ts
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/SMSMessaging.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/Answer.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/Question.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/QuestionAndAnswerPair.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/SecurityQuestions.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/index.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/types.ts
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/utilities.ts
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/profile.ts
  packages/manager/src/queries/securityQuestions.ts
  packages/validation/package.json
  packages/validation/src/profile.schema.ts
  packages/validation/webpack.config.js
  yarn.lock
Labels: Alt Pay at Signup

#8419 Updated mock Security Questions
  packages/manager/src/factories/profile.ts
Labels: Alt Pay at Signup

#8413 Upgrade Sentry to `@sentry/browser@7.1.1`
  packages/manager/package.json
  packages/manager/src/initSentry.ts
  yarn.lock
Labels: dependencies

#8438 M3-5853: Make 2FA / Security Questions Errors Accurate
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
Labels: Enhancement, Alt Pay at Signup

#8436 M3-5860: Update 2FA Security Questions Notice Font Size
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
Labels: UI, Alt Pay at Signup
