Repository linode/manager, pull requests merged in 2022-01, with the labels that each got.

#8093 M3-5638: Fix Editing a Secondary Domain Freezing Cloud Manager
  packages/manager/src/features/Domains/DomainZoneImportDrawer.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
Labels: Bug

#8094 DBAAS1-106: Database Landing Table
  packages/api-v4/src/databases/types.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
Labels: DBaaS

#8091 M3-5632: Fixed Customer Unable to Edit Cloud Firewall Rules
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts
Labels: Bug

#8092 Update URL after redirecting from a URL that doesn't exist
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
Labels: DBaaS

#8083 DBAAS1-85: Database Details Backups Tab
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupActionMenu.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupTableRow.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/databases.ts
  yarn.lock
Labels: DBaaS

#8103 DBAAS1-82: Database Details - Cluster Configs
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
Labels: DBaaS

#8109 Upgrade immer to ^9.0.6
  package.json
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts
  yarn.lock
Labels: Bug, security

#8108 M3-5649: Add Engine to Database Details URL
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseEntityDetail.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/features/Databases/index.tsx
  packages/manager/src/queries/databases.ts
Labels: DBaaS

#8113 M3-5647: Fix Icon Alignment for Kubernetes Nodes
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
Labels: UI

#8112 M3-5651: Enable Mock Data in PR Builds
  packages/manager/src/constants.ts
  packages/manager/src/dev-tools/dev-tools.tsx
  packages/manager/src/dev-tools/load.ts
  packages/manager/src/mocks/testBrowser.ts
Labels: Build and Organization

#8101 DBAAS1-79: Database Create Page
  packages/api-v4/src/databases/types.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/src/assets/icons/mysql.svg
  packages/manager/src/components/TextField.tsx
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/utilities/ipUtils.ts
  packages/validation/src/databases.schema.ts
Labels: DBaaS

#8090 DBaaS1-78: Landing page empty state
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Labels: DBaaS

#8123 DBaaS Fixes and Updates
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
Labels: DBaaS

#8099 DBaaS1-84: Access Control in Database Details
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
  packages/manager/src/queries/databases.ts
Labels: DBaaS

#8119 Update Cypress Test for Editing Account Information
  packages/manager/cypress/integration/account/billing-contact.spec.ts
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
Labels: e2e

#8124 M3-5663: Changes to Upgrade to High Availability Dialog Copy
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeClusterDialog.tsx
Labels: UI, LKE

#8104 DBAAS1-107: Database Beta Chip
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
Labels: DBaaS

#8129 M3-5666 Update DBAAS icon
  packages/manager/src/assets/icons/entityIcons/database.svg
Labels: DBaaS

#8126 M3-5668: DBaaS Landing Page Refinements
  packages/api-v4/src/databases/types.ts
  packages/manager/src/components/TableSortCell/TableSortCell.tsx
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
Labels: DBaaS

#8130 M3-5671: Tweaks to Access Controls
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
Labels: DBaaS

#8127 DBAAS1-83: Database Connection Details
  packages/api-v4/src/databases/types.ts
  packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/databases.ts
Labels: DBaaS

#8132 M3 5665 - Create page refinement
  packages/api-v4/src/databases/types.ts
  packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/databases.ts
  packages/manager/src/utilities/formatStorageUnits.ts
  packages/validation/src/databases.schema.ts
Labels: DBaaS

#8133 M3-5630: Update NVMe Block Storage copy
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
Labels: UI

#8137 Making the DBaaS headers consistent
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Labels: DBaaS

#8142 Revise parameter type for getDatabaseType() method
  packages/api-v4/src/databases/databases.ts
Labels: DBaaS

#8144 M3-5680: Update DBaaS Connection Details ssl verbiage
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Labels: DBaaS

#8145 Do not mask DB username
  packages/manager/src/constants.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Labels: e2e, DBaaS

#8147 DBaaS1-205: Replace instances of 'semi-synch' with 'semi_synch'
  packages/api-v4/src/databases/types.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/validation/src/databases.schema.ts
Labels: DBaaS

#8150 M3-5689: Fix storage unit for DBaaS
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
Labels: DBaaS

#8148 M3-5683: Add Secondary Host and Tooltip
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Labels: DBaaS

#8151 M3-5681: DBaaS Create UI refinements
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
Labels: DBaaS

#8143 M3-5676: Database Backups Refinements
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupTableRow.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
Labels: DBaaS

#8122 M3-5661: Add Databases and Firewalls to Support Tickets
  packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
  packages/manager/src/queries/databases.ts
  packages/manager/src/queries/firewalls.ts
Labels: DBaaS

#8149 M3-5675: Post-demo Refinements to Access Controls
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
Labels: DBaaS
