Repository linode/manager, pull requests merged in 2022-02, with the labels that each got.

#8155 M3-5694: Changes to types, schema, and Database components to reflect cluster_size
  packages/api-v4/src/databases/types.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/validation/src/databases.schema.ts
Labels: DBaaS

#8154 Database Create Copy updates
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
Labels: DBaaS

#8131 M3-5672: Events and Polling for Databases
  packages/api-v4/src/account/types.ts
  packages/manager/src/App.tsx
  packages/manager/src/components/EntityIcon/EntityIcon.tsx
  packages/manager/src/eventMessageGenerator.ts
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/queries/databases.ts
  packages/manager/src/store/events/event.request.ts
  packages/manager/src/utilities/getEventsActionLink.ts
  packages/manager/src/utilities/getEventsActionLinkStrings.ts
Labels: React Query, DBaaS

#8161 Update SSLFields type and Download CA Certficate button
  packages/api-v4/src/databases/types.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Labels: DBaaS

#8163 Observe account.capabilities to enable DBaaS
  packages/api-v4/src/account/types.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Databases/index.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Labels: e2e, DBaaS

#8160 Fix Account Routing
  packages/manager/src/components/TaxBanner/TaxBanner.tsx
  packages/manager/src/features/Account/AccountLanding.tsx
Labels: e2e

#8152 M3-5679: Querify database credentials reset
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsResetPasswordDialog.tsx
  packages/manager/src/queries/databases.ts
Labels: DBaaS

#8165 M3-5701: Disable show button if database cluster is provisioning
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Labels: DBaaS

#8171 Add copy tooltip to password and hosts in Database Connection Details
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Labels: DBaaS

#8172 DBaaS UI fixes
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMenuItem.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsResetPasswordDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Labels: UI, DBaaS

#8159 Display country in the Billing Contact panel
  packages/manager/src/features/Billing/BillingDetail.test.tsx
  packages/manager/src/features/Billing/BillingDetail.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
Labels: UI

#8166 M3-5702: Changes resulting from GET /databases/versions --> GET /databases/engines
  packages/api-v4/src/databases/databases.ts
  packages/api-v4/src/databases/types.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/databases.ts
Labels: DBaaS

#8177 Database Landing Docs Link
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
Labels: DBaaS

#8169 DBaaS React Query Minor Change
  packages/manager/src/queries/databases.ts
Labels: React Query, DBaaS

#8162 Fix Storybook Dependency Issues
  package.json
  packages/manager/package.json
  yarn.lock
Labels: Storybook

#8181 Fix StackScript Broken Cypress Test
  packages/manager/cypress/integration/stackscripts/stackscripts.spec.ts
Labels: e2e

#8180 Fix icon showing after IP address
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx
  packages/manager/src/features/linodes/LinodesLanding/IPAddress.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/IPAddress.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/linodes/LinodesLanding/OverflowIPs.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/OverflowIPs.tsx
  packages/manager/src/index.css
Labels: UI

#8182 M3-5597: Storybook updates for Analytics & Graphs
  packages/manager/.storybook/preview.tsx
  packages/manager/src/components/GaugePercent/GaugePercent.stories.mdx
  packages/manager/src/components/GaugePercent/GaugePercent.stories.tsx
  packages/manager/src/components/LineGraph/LineGraph.stories.mdx
  packages/manager/src/components/LineGraph/LineGraph.stories.tsx
  packages/manager/src/components/LongviewLineGraph/LongviewLineGraph.stories.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Storybook

#8184 M3-5592: Update PaymentMethodRow story to mdx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.mdx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
Labels: Storybook

#8190 M3-5596: Convert ActionMenu story to MDX
  packages/manager/src/components/ActionMenu/ActionMenu.stories.mdx
  packages/manager/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
Labels: Storybook

#8191 M3-5593: Convert Search Story to MDX
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.stories.mdx
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.stories.tsx
  packages/manager/src/components/DebouncedSearchTextField/StoryComponents/SelectExample.tsx
Labels: Storybook

#8046 M3-5190: React Query for Object Storage
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/containers/bucket.container.ts
  packages/manager/src/containers/bucketRequests.container.ts
  packages/manager/src/containers/clusters.container.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMenuItem.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx
  packages/manager/src/features/Search/SearchLanding.test.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/withStoreSearch.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/hooks/useObjectStorageBuckets.ts
  packages/manager/src/hooks/useObjectStorageClusters.ts
  packages/manager/src/hooks/useReduxLoad.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/objectStorage.ts
  packages/manager/src/store/bucket/bucket.actions.ts
  packages/manager/src/store/bucket/bucket.reducer.ts
  packages/manager/src/store/bucket/bucket.requests.test.ts
  packages/manager/src/store/bucket/bucket.requests.ts
  packages/manager/src/store/bucket/types.ts
  packages/manager/src/store/clusters/clusters.actions.ts
  packages/manager/src/store/clusters/clusters.reducer.ts
  packages/manager/src/store/index.ts
  packages/manager/src/store/selectors/entitiesErrors.ts
  packages/manager/src/store/selectors/getSearchEntities.ts
Labels: e2e, React Query

#8188 Add copy tooltip to IP addresses on the Linode Networking tab
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
Labels: UI

#8204 M3-5616: Storybook for Toggles
  packages/manager/src/components/Toggle/Toggle.stories.mdx
  packages/manager/src/components/Toggle/Toggle.stories.tsx
  packages/manager/src/components/Toggle/Toggle.tsx
Labels: Storybook

#8192 M3-5589: Added Storybook Story for File Uploads
  packages/manager/src/components/FileUpload.stories.mdx
  packages/manager/src/components/FileUploader/FileUploader.stories.mdx
  packages/manager/src/components/FileUploader/FileUploader.tsx
Labels: Storybook

#8199 M3-5599: Update story for CheckBox
  packages/manager/src/components/CheckBox/CheckBox.stories.mdx
  packages/manager/src/components/CheckBox/CheckBox.stories.tsx
  packages/manager/src/components/CheckBox/CheckBox.tsx
Labels: Storybook

#8186 M3-5598: Update stories for Breadcrumb
  packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
  packages/manager/src/components/Breadcrumb/Breadcrumb.stories.tsx
Labels: Storybook

#8212 M3-5613: Update story for Tabs
  packages/manager/src/components/TabbedPanel/TabbedPanel.stories.tsx
  packages/manager/src/components/Tabs.stories.mdx
Labels: Storybook

#8217 React Query for Object Storage Bug Fixes
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx
  packages/manager/src/queries/objectStorage.ts
Labels: Bug, Urgent, React Query

#8215 M3-5617: Update Tooltip stories
  packages/manager/src/components/CopyTooltip/CopyTooltip.stories.mdx
  packages/manager/src/components/CopyTooltip/CopyTooltip.stories.tsx
  packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
  packages/manager/src/components/HelpIcon/HelpIcon.stories.mdx
  packages/manager/src/components/HelpIcon/HelpIcon.stories.tsx
  packages/manager/src/components/HelpIcon/HelpIcon.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/linodes/LinodesLanding/IPAddress.test.tsx
Labels: Storybook

#8040 M3-5473: Webpack 5
  package.json
  packages/api-v4/package.json
  packages/api-v4/tsconfig.json
  packages/manager/.storybook/webpack.config.js
  packages/manager/config/webpack.config.dev.js
  packages/manager/config/webpack.config.prod.js
  packages/manager/config/webpackDevServer.config.js
  packages/manager/package.json
  packages/manager/scripts/start.js
  packages/manager/src/cachedData/kernels.json
  packages/manager/src/cachedData/regions.json
  packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
  packages/manager/src/components/core/styles/index.ts
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts
  packages/manager/src/features/Help/SearchHOC.test.tsx
  packages/manager/src/features/Help/SearchHOC.tsx
  packages/manager/src/features/Managed/SSHAccess/LinodePubKey.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketBreadcrumb.tsx
  packages/manager/src/features/Search/refinedSearch.test.ts
  packages/manager/src/features/Search/refinedSearch.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
  packages/manager/src/features/linodes/LinodesLanding/IPAddress.tsx
  packages/manager/src/hooks/useDismissibleNotifications.ts
  packages/manager/src/hooks/usePageVisibility/index.ts
  packages/manager/src/hooks/usePageVisibility/use-page-visibility.d.ts
  packages/manager/src/hooks/usePageVisibility/usePageVisibility.ts
  packages/manager/src/hooks/usePolling.test.tsx
  packages/manager/src/hooks/usePolling.ts
  packages/manager/src/hooks/useReduxLoad.ts
  packages/manager/src/queries/regions.ts
  packages/manager/src/utilities/getEntityByIDFromStore.test.ts
  packages/manager/src/utilities/gravatar.ts
  packages/manager/src/utilities/markdown.ts
  packages/manager/src/utilities/queryParams.ts
  packages/manager/src/utilities/requestFilters.ts
  packages/manager/src/utilities/sanitize-html/sanitizeHTML.ts
  packages/manager/src/utilities/validatePassword/validatePassword.ts
  packages/manager/tsconfig.test.json
  packages/validation/package.json
  packages/validation/tsconfig.json
  yarn.lock
Labels: e2e

#8211 M3-5594: Storybook for Tables
  packages/manager/src/components/LineGraph/LineGraph.stories.mdx
  packages/manager/src/components/Skeleton/Skeleton.stories.tsx
  packages/manager/src/components/Table/Table.stories.mdx
  packages/manager/src/components/Table/Table.stories.tsx
  packages/manager/src/components/TableRowEmptyState/TableRowEmptyState.stories.mdx
  packages/manager/src/components/TableRowError/TableRowError.stories.mdx
  packages/manager/src/components/TableRowLoading/TableRowLoading.stories.mdx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Storybook

#8220 M3-5583: Fixed Linode Configurations Table Misalignment
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/ConfigRow.tsx
Labels: Bug

#8213 M3-5607: Update stories for loading states
  packages/manager/src/components/BarPercent/BarPercent.stories.mdx
  packages/manager/src/components/BarPercent/BarPercent.stories.tsx
  packages/manager/src/components/BarPercent/BarPercent.tsx
  packages/manager/src/components/CircleProgress/CircleProgress.stories.mdx
  packages/manager/src/components/CircleProgress/CircleProgress.stories.tsx
  packages/manager/src/components/CircleProgress/CircleProgress.tsx
  packages/manager/src/components/InlineTextLoader/InlineTextLoader.tsx
  packages/manager/src/components/InlineTextLoader/index.ts
  packages/manager/src/components/LinearProgress/LinearProgress.stories.mdx
  packages/manager/src/components/LinearProgress/LinearProgress.stories.tsx
  packages/manager/src/components/LinearProgress/LinearProgress.tsx
  packages/manager/src/components/LoadingText.tsx
  packages/manager/src/components/TableSortCell/TableSortCell.tsx
  packages/manager/src/features/Lish/Glish.tsx
  packages/manager/src/features/Lish/Lish.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/EnableTwoFactorForm.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptsSection.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptsSection.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransfer.tsx
Labels: Storybook

#8229 M3-5739: Apply branding to Storybook
  packages/manager/.storybook/YourTheme.js
  packages/manager/.storybook/main.js
  packages/manager/.storybook/manager-head.html
  packages/manager/.storybook/manager.js
  packages/manager/.storybook/preview-head.html
  packages/manager/.storybook/preview.tsx
  packages/manager/package.json
  packages/manager/src/components/intro.stories.mdx
  yarn.lock
Labels: Storybook
