Repository linode/manager, pull requests merged in 2022-09, with the labels that each got.

#8524 M3-5930: Fix Ant Media Server display in drawer
  packages/manager/src/features/OneClickApps/FakeSpec.ts
Labels: Marketplace

#8522 M3-5927: Allow Deletion of Private IPv4 Addresses
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
Labels: Enhancement

#8529 M3-5931: Fix database maintenance window mapping and database_update notification message
  packages/manager/src/eventMessageGenerator.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
Labels: DBaaS

#8537 M3-5891: Make Database Engine Icons More Visible on Focus
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
Labels: accessibility, UI

#8531 M3-5913: Replace `novnc-node` with `react-vnc`
  packages/manager/package.json
  packages/manager/src/features/Lish/Glish.tsx
  packages/manager/src/features/Lish/Lish.tsx
  packages/manager/src/features/Lish/VncDisplay.tsx
  packages/manager/src/features/Lish/Weblish.tsx
  packages/manager/src/features/Lish/novnc-node.d.ts
  packages/manager/src/index.tsx
  packages/manager/src/queries/linodes.ts
  yarn.lock
Labels: dependencies

#8546 M3-5937: Add Firewall Support for `IPENCAP` Protocol
  packages/api-v4/src/firewalls/types.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.test.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts
  packages/manager/src/features/Firewalls/shared.ts
  packages/validation/src/firewalls.schema.ts
Labels: Enhancement
