Repository linode/manager, pull requests merged in 2022-10, with the labels that each got.

#8559 M3-5941: Linode landing page – Empty state
  packages/manager/src/assets/icons/external-link.svg
  packages/manager/src/assets/icons/marketplace.svg
  packages/manager/src/assets/icons/pointer.svg
  packages/manager/src/assets/icons/youtube.svg
  packages/manager/src/components/Placeholder/Placeholder.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/AppsSection.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinksSection.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinksSubSection.tsx
  packages/manager/src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx
Labels: Enhancement, UI

#8564 M3-5900: Visual indicator when navigating Linode and Database plan selection tables
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Labels: accessibility, UI

#8216 React Query for Managed
  packages/api-v4/src/managed/managed.ts
  packages/api-v4/src/managed/types.ts
  packages/manager/src/__data__/managedIssues.ts
  packages/manager/src/containers/managedIssues.container.ts
  packages/manager/src/containers/managedServices.container.ts
  packages/manager/src/factories/managed.ts
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
  packages/manager/src/features/Managed/Contacts/Contacts.tsx
  packages/manager/src/features/Managed/Contacts/ContactsActionMenu.tsx
  packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
  packages/manager/src/features/Managed/Contacts/ContactsRow.tsx
  packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx
  packages/manager/src/features/Managed/Credentials/CredentialActionMenu.tsx
  packages/manager/src/features/Managed/Credentials/CredentialList.tsx
  packages/manager/src/features/Managed/Credentials/CredentialTableContent.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/DashboardCard.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedDashboardCard.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/MonitorTickets.tsx
  packages/manager/src/features/Managed/ManagedLanding.tsx
  packages/manager/src/features/Managed/ManagedLandingContent.tsx
  packages/manager/src/features/Managed/Monitors/HistoryDrawer.tsx
  packages/manager/src/features/Managed/Monitors/IssueCalendar.tsx
  packages/manager/src/features/Managed/Monitors/IssueDay.tsx
  packages/manager/src/features/Managed/Monitors/MonitorActionMenu.test.tsx
  packages/manager/src/features/Managed/Monitors/MonitorActionMenu.tsx
  packages/manager/src/features/Managed/Monitors/MonitorRow.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTable.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTableContent.tsx
  packages/manager/src/features/Managed/Monitors/Monitors.tsx
  packages/manager/src/features/Managed/Monitors/index.tsx
  packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx
  packages/manager/src/features/Managed/SSHAccess/LinodePubKey.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.test.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessRow.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessTable.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessTableContent.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/hooks/useReduxLoad.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/accountSettings.ts
  packages/manager/src/queries/base.ts
  packages/manager/src/queries/managed.ts
  packages/manager/src/queries/managed/helpers.ts
  packages/manager/src/queries/managed/managed.ts
  packages/manager/src/queries/managed/types.ts
  packages/manager/src/store/backupDrawer/index.ts
  packages/manager/src/store/index.ts
  packages/manager/src/store/managed/issues.actions.ts
  packages/manager/src/store/managed/issues.reducer.ts
  packages/manager/src/store/managed/managed.actions.ts
  packages/manager/src/store/managed/managed.reducer.test.ts
  packages/manager/src/store/managed/managed.reducer.ts
  packages/manager/src/store/managed/managed.requests.ts
Labels: React Query

#8452 M3-5889: Safari on iOS Accessibility and Zoom Fix
  packages/manager/public/index.html
  packages/manager/src/components/EnhancedSelect/EnhancedSelect.css
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
  packages/manager/src/components/EnhancedSelect/components/SelectPlaceholder.tsx
  packages/manager/src/components/EnhancedSelect/components/SingleValue.tsx
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/themeFactory.ts
Labels: accessibility

#8580 Remove unused `babel` dependencies
  packages/manager/package.json
  yarn.lock
Labels: Build and Organization, dependencies

#8588 M3-5963: Add pagination support for Marketplace
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/queries/stackscripts.ts
Labels: Marketplace

#8587 Update `launchdarkly-react-client-sdk` to `latest`
  package.json
  packages/manager/package.json
  packages/manager/patches/launchdarkly-react-client-sdk+2.11.0.patch
  packages/manager/src/utilities/testHelpers.tsx
  yarn.lock
Labels: dependencies

#8592 Fix IP Transfer Dialog
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
Labels: Bug

#8593 Re-add `nth-check` Yarn Resolution for CVE-2021-3803
  package.json
  yarn.lock
Labels: dependencies
