Repository linode/manager, pull requests merged in 2023-06, with the labels that each got.

#9185 refactor: [M3-6382] - MUI v5 - `Components > Radio`
  packages/manager/src/components/ModeSelect/ModeSelect.tsx
  packages/manager/src/components/Radio/Radio.mdx
  packages/manager/src/components/Radio/Radio.stories.mdx
  packages/manager/src/components/Radio/Radio.stories.tsx
  packages/manager/src/components/Radio/Radio.tsx
  packages/manager/src/components/Radio/index.ts
  packages/manager/src/components/core/Radio.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/manager/src/features/Domains/CloneDomainDrawer.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Domains/EditDomainDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleForm.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessCell.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/StackScriptSelectionRow.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedSelect.tsx
  packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/ModeSelection.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
  packages/manager/src/foundations/themes/light.ts
Labels: Storybook, Approved, Project: MUI v5 Migration

#9180 Refactor: [M3-6278]: MUI refactor - Object Storage
  packages/manager/.changeset/pr-9180-tech-stories-1685646103466.md
  packages/manager/src/components/Button/LinkStyledButton.ts
  packages/manager/src/components/FileUploader/FileUploader.stories.mdx
  packages/manager/src/components/FileUploader/FileUploader.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessCell.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyMenu.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessTable.styles.ts
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/RevokeAccessKeyDialog.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/ViewPermissionsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.data.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketAccess.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketBreadcrumb.styles.ts
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketBreadcrumb.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.styles.ts
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.styles.ts
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketActionMenu.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.styles.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/CancelNotice.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.styles.ts
  packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.styles.ts
  packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/index.ts
  packages/manager/src/features/ObjectStorage/index.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.tsx
Labels: Work in Progress

#9202 refactor: [M3-6372] - MUI v5 - `Components > PasswordInput`
  packages/manager/.changeset/pr-9202-tech-stories-1685725486015.md
  packages/manager/.changeset/pr-9202-tech-stories-1685980204155.md
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/PasswordInput/HideShowText.stories.tsx
  packages/manager/src/components/PasswordInput/HideShowText.tsx
  packages/manager/src/components/PasswordInput/PasswordInput.stories.mdx
  packages/manager/src/components/PasswordInput/PasswordInput.stories.tsx
  packages/manager/src/components/PasswordInput/PasswordInput.tsx
  packages/manager/src/components/PasswordInput/StrengthIndicator.stories.tsx
  packages/manager/src/components/PasswordInput/StrengthIndicator.test.tsx
  packages/manager/src/components/PasswordInput/StrengthIndicator.tsx
  packages/manager/src/components/PasswordInput/index.ts
  packages/manager/src/features/Linodes/LinodesCreate/PasswordPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx
  packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
  packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
Labels: Storybook, Approved, Project: MUI v5 Migration

#9204 chore: [M3-6363, M3-6371] - Remove unused `MonkeyWrench`, `PanelErrorBoundary` components
  packages/manager/src/components/MonkeyWrench/MonkeyWrench.tsx
  packages/manager/src/components/MonkeyWrench/index.ts
  packages/manager/src/components/PanelErrorBoundary/PanelErrorBoundary.tsx
  packages/manager/src/components/PanelErrorBoundary/index.ts
Labels: Ready for Review, Project: MUI v5 Migration, Clean Up

#9198 refactor: [M3-6491] - React Query Linodes - Configurations
  packages/api-v4/src/linodes/info.ts
  packages/manager/.changeset/pr-9198-tech-stories-1685632391390.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeAdvancedConfigurationsPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/index.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/BootConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/ConfigRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/DeleteConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/manager/src/queries/linodes/configs.ts
  packages/manager/src/queries/linodes/linodes.ts
Labels: React Query, Approved, Linodes

#9191 refactor: [M3-6399] - MUI v5 - `Components > TabbedPanel, ReachTab, ReachTabList`
  packages/manager/.changeset/pr-9191-tech-stories-1685642394277.md
  packages/manager/src/components/TabLinkList/TabLinkList.tsx
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/components/TabbedPanel/index.ts
  packages/manager/src/components/core/ReachTab.tsx
  packages/manager/src/components/core/ReachTabList.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TabbedReply.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
Labels: Add'tl Approval Needed, Project: MUI v5 Migration

#9212 Update to`vite@4.3.9` for `CVE-2023-34092`
  packages/manager/.changeset/pr-9212-tech-stories-1686072978202.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved

#9208 refactor: [M3-6402] - MUI v5 - `Components > TableContentWrapper`
  packages/manager/.changeset/pr-9208-tech-stories-1685734625059.md
  packages/manager/src/components/TableContentWrapper/TableContentWrapper.test.tsx
  packages/manager/src/components/TableContentWrapper/TableContentWrapper.tsx
  packages/manager/src/components/TableContentWrapper/index.tsx
  packages/manager/src/components/TableRowLoading/TableRowLoading.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
  packages/manager/src/features/EntityTransfers/TransfersTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDevicesTable.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
Labels: Approved, Project: MUI v5 Migration

#9211 refactor: [M3-6378] - MUI v5 - Components > ProductNotification
  packages/manager/.changeset/pr-9211-tech-stories-1686019152206.md
  packages/manager/src/components/ProductNotification/ProductNotification.test.tsx
  packages/manager/src/components/ProductNotification/ProductNotification.tsx
  packages/manager/src/components/ProductNotification/index.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx
Labels: Approved, Project: MUI v5 Migration

#9165 refactor: [M3-6561], [M3-6562] and [M3-6572] - Simplify SelectPlanPanel and SelectPlanQuantityPanel.
  packages/manager/.changeset/pr-9165-tech-stories-1685109845378.md
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/PremiumPlansAvailabilityNotice.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/PremiumPlansAvailabilityNotice.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/GPUNotice.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/KubernetesPlanContainer.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/MetalNotice.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlanContainer.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlanInformation.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlanInformation.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlanSelection.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlansPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/styles/kubernetesPlansPanelStyles.ts
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/styles/plansPanelStyles.ts
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/utils.test.ts
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/utils.ts
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/utilities/filterPlanSelectionsByType.ts
  packages/manager/src/utilities/filterPlanSelectionsByTypes.test.ts
Labels: Add'tl Approval Needed

#9214 fix: [M3-6555] - Don't conditionally render VLANs depending on Account Capabilities
  packages/manager/.changeset/pr-9214-fixed-1686072216523.md
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetail.container.tsx
  packages/manager/src/features/Linodes/MigrateLinode/CautionNotice.tsx
Labels: Bug, VLAN, Ready for Review

#9195 refactor: [M3-6494] - React Query for Linode Migrate Dialog
  packages/manager/.changeset/pr-9195-tech-stories-1685632202604.md
  packages/manager/src/features/Images/utils.test.tsx
  packages/manager/src/features/Images/utils.ts
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/useAPISearch.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/queries/images.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/store/selectors/getSearchEntities.ts
  packages/manager/src/utilities/getLinodeDescription.ts
Labels: React Query, Approved, Linodes

#9222 feat: [M3-6640] - Metadata beta updates
  packages/manager/.changeset/pr-9222-added-1686168792621.md
  packages/manager/src/cachedData/regions.json
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/utils.ts
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
Labels: Project: Metadata, Ready for Review

#9226 feat: [M3-6674] - Add kubernetes product information banner
  packages/manager/.changeset/pr-9226-added-1686168141780.md
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/GlobalNotifications/APIMaintenanceBanner.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
Labels: Ready for Review

#9205 fix: [M3-6653] - Encode `api-v4` Path Parameters
  packages/api-v4/CHANGELOG.md
  packages/api-v4/src/account/events.ts
  packages/api-v4/src/account/invoices.ts
  packages/api-v4/src/account/logins.ts
  packages/api-v4/src/account/oauth.ts
  packages/api-v4/src/account/payments.ts
  packages/api-v4/src/account/users.ts
  packages/api-v4/src/databases/databases.ts
  packages/api-v4/src/domains/domains.ts
  packages/api-v4/src/domains/records.ts
  packages/api-v4/src/entity-transfers/transfers.ts
  packages/api-v4/src/firewalls/firewalls.ts
  packages/api-v4/src/images/images.ts
  packages/api-v4/src/kubernetes/kubernetes.ts
  packages/api-v4/src/kubernetes/nodePools.ts
  packages/api-v4/src/linodes/actions.ts
  packages/api-v4/src/linodes/backups.ts
  packages/api-v4/src/linodes/configs.ts
  packages/api-v4/src/linodes/disks.ts
  packages/api-v4/src/linodes/info.ts
  packages/api-v4/src/linodes/ips.ts
  packages/api-v4/src/linodes/linodes.ts
  packages/api-v4/src/longview/longview.ts
  packages/api-v4/src/managed/managed.ts
  packages/api-v4/src/networking/networking.ts
  packages/api-v4/src/nodebalancers/nodebalancer-config-nodes.ts
  packages/api-v4/src/nodebalancers/nodebalancer-configs.ts
  packages/api-v4/src/nodebalancers/nodebalancers.ts
  packages/api-v4/src/nodebalancers/utils.ts
  packages/api-v4/src/object-storage/buckets.ts
  packages/api-v4/src/object-storage/objectStorageKeys.ts
  packages/api-v4/src/object-storage/objects.ts
  packages/api-v4/src/profile/accessTokens.ts
  packages/api-v4/src/profile/appTokens.ts
  packages/api-v4/src/profile/profile.ts
  packages/api-v4/src/profile/sshkeys.ts
  packages/api-v4/src/regions/regions.ts
  packages/api-v4/src/stackscripts/stackscripts.ts
  packages/api-v4/src/support/support.ts
  packages/api-v4/src/tags/tags.ts
  packages/api-v4/src/vlans/vlans.ts
  packages/api-v4/src/volumes/migrations.ts
  packages/api-v4/src/volumes/volumes.ts
  packages/manager/cypress/support/intercepts/images.ts
Labels: Security, Approved

#9229 feat: [M3-6535, M3-6537] - Add design tokens for `akamai`, `cloudmanager`, and dark/light themes
  packages/manager/package.json
  packages/manager/src/foundations/themes/light.ts
  yarn.lock
Labels: Design Tokens

#9197 Refactor: [M3-6280] MUI Migration: Profile
  packages/manager/.changeset/pr-9197-tech-stories-1685646179365.md
  packages/manager/src/components/GravatarByEmail.tsx
  packages/manager/src/components/TableSortCell/StyledTableSortCell.ts
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/Profile/APITokens/APITokenDrawer.styles.ts
  packages/manager/src/features/Profile/APITokens/APITokenTable.styles.ts
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
  packages/manager/src/features/Profile/APITokens/APITokens.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/ResetPassword.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SMSMessaging.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/QuestionAndAnswerPair.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/SecurityQuestions.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/index.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPADialog.test.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPADialog.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.test.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/ConfirmToken.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/EnableTwoFactorForm.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/QRCodeForm.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactorToggle.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/index.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/index.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
  packages/manager/src/features/Profile/DisplaySettings/index.ts
  packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
  packages/manager/src/features/Profile/LishSettings/index.ts
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
  packages/manager/src/features/Profile/Profile.tsx
  packages/manager/src/features/Profile/Referrals/Referrals.styles.ts
  packages/manager/src/features/Profile/Referrals/Referrals.tsx
  packages/manager/src/features/Profile/Referrals/index.ts
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.test.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
  packages/manager/src/features/Profile/SSHKeys/index.ts
  packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
  packages/manager/src/features/Profile/SecretTokenDialog/index.tsx
  packages/manager/src/features/Profile/Settings/Settings.tsx
  packages/manager/src/features/Profile/Settings/index.ts
Labels: Approved

#9224 refactor: [M3-6672] - Refactor `<AddNewMenu />` to use MUI rather than Reach UI
  packages/manager/.changeset/pr-9224-tech-stories-1686169209507.md
  packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/src/components/Dialog/Dialog.tsx
  packages/manager/src/components/Drawer/Drawer.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.test.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenuItem.test.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenuItem.tsx
  packages/manager/src/foundations/themes/dark.ts
  packages/manager/src/foundations/themes/light.ts
Labels: UI, Ready for Review

#9218 refactor: [M3-6490] - React Query - Linode Storage - Finish Volumes
  EntityIcon
  packages/manager/.changeset/pr-9218-tech-stories-1686268120191.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/Volumes/VolumesActionMenu.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
Labels: React Query, Ready for Review

#9220 refactor: [M3-6357] - Refactor LinodeCLIModal
  packages/manager/.changeset/pr-9220-changed-1686133289498.md
  packages/manager/src/components/LinodeCLIModal/LinodeCLIModal.tsx
  packages/manager/src/components/LinodeCLIModal/index.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
Labels: Ready for Review, Project: MUI v5 Migration

#9215 fix: [M3-5972] - Better/correct timestamps for finished event messages
  packages/manager/.changeset/pr-9215-fixed-1686154022321.md
  packages/manager/src/features/Events/EventRow.test.tsx
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
  packages/manager/src/utilities/eventUtils.test.ts
  packages/manager/src/utilities/eventUtils.ts
Labels: Approved, Ready for Review

#9234 Fix: [M3-6637] - Linode networking v6 resolvers overflow
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/DNSResolvers.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
Labels: Ready for Review, Missing Changeset

#9232 refactor: [M3-6405-6407] - MUI v5 - `Components > TableRowEmpty, TableRowError, TableRowLoading`
  packages/manager/.changeset/pr-9232-tech-stories-1686251566732.md
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/components/TableContentWrapper/TableContentWrapper.tsx
  packages/manager/src/components/TableRowEmpty/TableRowEmpty.stories.mdx
  packages/manager/src/components/TableRowEmpty/TableRowEmpty.tsx
  packages/manager/src/components/TableRowEmptyState/TableRowEmptyState.tsx
  packages/manager/src/components/TableRowEmptyState/index.ts
  packages/manager/src/components/TableRowError/TableRowError.stories.mdx
  packages/manager/src/components/TableRowError/TableRowError.tsx
  packages/manager/src/components/TableRowError/index.ts
  packages/manager/src/components/TableRowLoading/TableRowLoading.stories.mdx
  packages/manager/src/components/TableRowLoading/TableRowLoading.tsx
  packages/manager/src/features/Account/AccountLogins.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Domains/DomainRecords.tsx
  packages/manager/src/features/Events/EventsLanding.tsx
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/Linodes/CloneLanding/Configs.tsx
  packages/manager/src/features/Linodes/CloneLanding/Disks.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/ListView.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ActiveConnections.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/ListeningServices.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/TopProcesses.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
  packages/manager/src/features/Longview/LongviewPackageDrawer.tsx
  packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx
  packages/manager/src/features/Managed/Credentials/CredentialTableContent.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTableContent.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessTableContent.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevices.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
  packages/manager/src/features/Support/SupportTickets/TicketList.tsx
  packages/manager/src/features/Users/UsersLanding.tsx
Labels: Approved, Project: MUI v5 Migration

#9249 fix: [M3-6686] - Linode Details crashing for Linodes that don't have plans
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/queries/types.ts
Labels: Bug, React Query, Approved

#9240 feat, fix: [M3-6560, M3-6641] - Update Linode Power confirmation dialog layout and UX copy
  packages/manager/.changeset/pr-9240-changed-1686335599449.md
  packages/manager/src/components/DialogTitle/DialogTitle.tsx
  packages/manager/src/features/Linodes/PowerActionsDialogOrDrawer.tsx
Labels: UI, Approved

#9251 Remove duplicated entries in `packages/manager/CHANGELOG.md`
  packages/manager/CHANGELOG.md
Labels: Approved

#9241 refactor: [M3-6338, 6381, 6383] - `ExtendedAccordion, Prompt, SafeTabPanel`
  packages/manager/.changeset/pr-9241-tech-stories-1686337150607.md
  packages/manager/src/components/ExtendedAccordion/ExtendedAccordion.test.tsx
  packages/manager/src/components/ExtendedAccordion/ExtendedAccordion.tsx
  packages/manager/src/components/ExtendedAccordion/index.ts
  packages/manager/src/components/NavTabs/NavTabs.tsx
  packages/manager/src/components/Prompt/Prompt.tsx
  packages/manager/src/components/Prompt/index.ts
  packages/manager/src/components/SafeTabPanel/SafeTabPanel.tsx
  packages/manager/src/components/SafeTabPanel/index.ts
  packages/manager/src/components/Tabs.stories.mdx
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Linodes/CloneLanding/CloneLanding.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/index.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/manager/src/features/Lish/Lish.tsx
  packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/features/NotificationCenter/NotificationSection.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/Users/UserDetail.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
Labels: Approved, Clean Up

#9237 refactor: [M3-6369] - MUI v5 - `Components > PaginationControls, PaginationFooter`
  packages/manager/.changeset/pr-9237-tech-stories-1686326150154.md
  packages/manager/src/components/PaginationControls/PageButton.tsx
  packages/manager/src/components/PaginationControls/PageNumbers.styles.ts
  packages/manager/src/components/PaginationControls/PageNumbers.test.tsx
  packages/manager/src/components/PaginationControls/PageNumbers.tsx
  packages/manager/src/components/PaginationControls/PaginationControls.stories.mdx
  packages/manager/src/components/PaginationControls/PaginationControls.test.tsx
  packages/manager/src/components/PaginationControls/PaginationControls.tsx
  packages/manager/src/components/PaginationControls/index.tsx
  packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
  packages/manager/src/features/Support/SupportTickets/TicketList.tsx
  packages/manager/src/foundations/themes/dark.ts
  packages/manager/src/foundations/themes/light.ts
Labels: Approved, Project: MUI v5 Migration

#9243 refactor: [M3-6384] – MUI v5 Migration – `Components > ScriptCode`
  packages/manager/.changeset/pr-9243-changed-1686346732563.md
  packages/manager/src/components/ScriptCode/ScriptCode.tsx
  packages/manager/src/components/ScriptCode/index.ts
  packages/manager/src/components/StackScript/StackScript.tsx
Labels: Approved, Project: MUI v5 Migration

#9228 chore: Remove `url-parse` and clean up query param helpers
  packages/manager/.changeset/pr-9228-tech-stories-1686235871127.md
  packages/manager/package.json
  packages/manager/src/components/OrderBy.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.tsx
  packages/manager/src/features/Linodes/CloneLanding/CloneLanding.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectAppPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/utils.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/Profile/Settings/Settings.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
  packages/manager/src/hooks/useOrder.ts
  packages/manager/src/layouts/LoginAsCustomerCallback.tsx
  packages/manager/src/layouts/OAuth.test.tsx
  packages/manager/src/layouts/OAuth.tsx
  packages/manager/src/utilities/queryParams.test.ts
  packages/manager/src/utilities/queryParams.ts
  yarn.lock
Labels: Approved, Clean Up

#9257 feat: [M3-6703] - Update MSW and Database API-V4 types to support new plans
  packages/api-v4/.changeset/pr-9257-added-1686756493120.md
  packages/api-v4/src/databases/types.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved

#9213 refactor: [M3-6377] - MUI v5 - Components > ProductInformationBanner
  packages/manager/.changeset/pr-9213-tech-stories-1686062114543.md
  packages/manager/src/components/ProductInformationBanner/ProductInformationBanner.test.tsx
  packages/manager/src/components/ProductInformationBanner/ProductInformationBanner.tsx
  packages/manager/src/components/ProductInformationBanner/index.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
Labels: Approved, Requires Changes, Project: MUI v5 Migration

#9259 hotfix: June Marketplace apps
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesCreate/AppPanelSection.tsx
  packages/manager/src/features/OneClickApps/FakeSpec.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Bug, Marketplace, Approved, Hotfix

#9261 Release v1.95.1 – `staging` → `master`
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesCreate/AppPanelSection.tsx
  packages/manager/src/features/OneClickApps/FakeSpec.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Release, Approved, Missing Changeset

#9262 Release v1.95.1 – master → develop
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesCreate/AppPanelSection.tsx
  packages/manager/src/features/OneClickApps/FakeSpec.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Release, Approved

#9254 refactor: [M3-6340] - MUI v5 Migration - `Components > FileUploader`
  packages/manager/.changeset/pr-9254-tech-stories-1686608779585.md
  packages/manager/src/components/FileUploader/FileUploader.stories.mdx
  packages/manager/src/components/FileUploader/FileUploader.styles.ts
  packages/manager/src/components/FileUploader/FileUploader.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.styles.ts
  packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.tsx
Labels: Approved, Project: MUI v5 Migration

#9256 refactor: [M3-6694] - Convert <App /> to functional component
  packages/manager/.changeset/pr-9256-tech-stories-1686693372703.md
  packages/manager/src/App.test.tsx
  packages/manager/src/App.tsx
  packages/manager/src/components/ErrorBoundary.tsx
  packages/manager/src/index.tsx
Labels: Approved

#9258 refactor: [M3-6362,M3-6365] - Update `Components > ModeSelect, NavTabs`
  packages/manager/src/components/ModeSelect/ModeSelect.tsx
  packages/manager/src/components/ModeSelect/index.tsx
  packages/manager/src/components/NavTabs/NavTabs.tsx
  packages/manager/src/components/NavTabs/index.ts
  packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeDiskDrawer.tsx
  packages/manager/src/features/Managed/ManagedLanding.tsx
  packages/manager/src/features/Profile/Profile.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
Labels: Approved

#9267 refactor: [M3-6349] - MUI v5 Migration - `SRC > ImageSelect`
  packages/manager/.changeset/pr-9267-tech-stories-1686857766076.md
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
Labels: Approved, Project: MUI v5 Migration

#9260 fix: [M3-6706] - Fix Marketplace App typos
  packages/manager/.changeset/pr-9260-fixed-1686769842584.md
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
  packages/manager/src/features/OneClickApps/oneClickApps.ts
Labels: Approved

#9253 Feature: [M3-6665] Dynamic Premium Plans support for Linodes creation flows
  packages/api-v4/.changeset/pr-9253-added-1686860188779.md
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-9253-added-1686859236273.md
  packages/manager/src/components/TextTooltip/TextTooltip.stories.tsx
  packages/manager/src/components/TextTooltip/TextTooltip.test.tsx
  packages/manager/src/components/TextTooltip/TextTooltip.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/PremiumPlansAvailabilityNotice.styles.ts
  packages/manager/src/features/Linodes/LinodesCreate/PremiumPlansAvailabilityNotice.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/PremiumPlansAvailabilityNotice.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectBackupPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanInformation.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanInformation.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanSelection.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlansPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/styles/kubernetesPlansPanelStyles.ts
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanQuantityPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/hooks/usePremiumPlans.ts
Labels: Approved

#9193 refactor: [M3-6485, M3-6651] - RQ-ify + Refactor Linode Select
  packages/manager/.changeset/pr-9193-tech-stories-1685478443289.md
  packages/manager/cypress/e2e/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/images/smoke-create-image.spec.ts
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.stories.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.styles.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelectV2.tsx
  packages/manager/src/foundations/themes/dark.ts
  packages/manager/src/foundations/themes/light.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/utilities/mapIdsToLinodes.test.ts
  packages/manager/src/utilities/mapIdsToLinodes.ts
Labels: UI, React Query, Approved

#9263 refactor: [M3-6351] - Refactor `<IPSelect />`
  packages/manager/.changeset/pr-9263-tech-stories-1686839868932.md
  packages/manager/src/components/IPSelect/IPSelect.tsx
  packages/manager/src/components/IPSelect/index.ts
  packages/manager/src/factories/linodes.ts
  packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Add'tl Approval Needed, React Query

#9272 fix: [M3-6568] - Button alignment on Nodebalancer Create page
  packages/manager/.changeset/pr-9272-fixed-1686929413003.md
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
Labels: Approved

#9278 refactor: [M3-6360] - MUI v5 Migration - `Components > MaintenanceBanner`
  packages/manager/.changeset/pr-9278-tech-stories-1686942932396.md
  packages/manager/src/components/MaintenanceBanner/MaintenanceBanner.tsx
  packages/manager/src/components/MaintenanceBanner/index.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/Profile/APITokens/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/utilities/isPast.test.ts
  packages/manager/src/utilities/isPast.ts
Labels: Approved

#9271 refactor: Round dates on the filters for invoices and payments
  packages/manager/.changeset/pr-9271-tech-stories-1686927837582.md
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.test.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
Labels: Approved

#9239 refactor: [M3-6380] -MUI v5 - Components > PromotionalOfferCard
  packages/manager/.changeset/pr-9239-tech-stories-1686334794129.md
  packages/manager/.changeset/pr-9239-tech-stories-1686846441284.md
  packages/manager/src/components/PromotionalOfferCard/PromotionalOfferCard.tsx
  packages/manager/src/components/PromotionalOfferCard/index.ts
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
Labels: Approved, Project: MUI v5 Migration

#9274 fix: Github Actions CI `build-manager`
  .github/workflows/ci.yml
  packages/manager/.changeset/pr-9274-tech-stories-1686938963869.md
Labels: Approved

#9276 refactor: [M3-6356] - MUI v5 Migration - `Components > LineGraph`
  packages/manager/.changeset/pr-9276-tech-stories-1686940552048.md
  packages/manager/src/components/LineGraph/LineGraph.stories.mdx
  packages/manager/src/components/LineGraph/LineGraph.styles.ts
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/components/LineGraph/NewMetricDisplay.styles.ts
  packages/manager/src/components/LineGraph/index.tsx
  packages/manager/src/components/LongviewLineGraph/LongviewLineGraph.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/NetworkGraphs.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
Labels: Approved, Project: MUI v5 Migration

#9270 refactor: [M3-6352] - MUI v5 Migration - `Components > LabelAndTagsPanel`
  packages/manager/.changeset/pr-9270-tech-stories-1686927343871.md
  packages/manager/src/components/LabelAndTagsPanel/LabelAndTagsPanel.test.tsx
  packages/manager/src/components/LabelAndTagsPanel/LabelAndTagsPanel.tsx
  packages/manager/src/components/LabelAndTagsPanel/index.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Labels: Approved, Project: MUI v5 Migration

#9277 chore: [M3-6714] - Allow backticks in commits when using changeset
  scripts/changelog/changeset.mjs
Labels: Approved

#9238 style: [M3-6314] - Plan selection—reduce space
  packages/manager/.changeset/pr-9238-tech-stories-1686332206028.md
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/GPUNotice.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/MetalNotice.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanContainer.styles.ts
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanInformation.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanSelection.styles.ts
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanSelection.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlansPanel.styles.ts
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlansPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/styles/kubernetesPlansPanelStyles.ts
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/styles/plansPanelStyles.ts
Labels: Approved

#9273 Fix: [M3-6612] Grid/Tag views and toggle styling (Linodes Landing)
  packages/manager/.changeset/pr-9273-fixed-1686932547524.md
  packages/manager/src/components/EntityTable/EntityTableHeader.tsx
  packages/manager/src/features/Linodes/LinodesLanding/CardView.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.styles.ts
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx
Labels: Approved

#9255 refactor: [M3-6490] - React Query - Linode Disks
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-9255-tech-stories-1686759239474.md
  packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
  packages/manager/src/App.tsx
  packages/manager/src/components/TableRowLoading/TableRowLoading.tsx
  packages/manager/src/factories/disk.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeDiskDrawer.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeDiskDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeDiskSpace.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeDiskSpace.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateDiskDrawer.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateDiskDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateImageFromDiskDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/DeleteDiskDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDisks.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDisks.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeStorage.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/RenameDiskDrawer.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/RenameDiskDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/ResizeDiskDrawer.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/ResizeDiskDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/index.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/linodes/disks.ts
  packages/manager/src/queries/linodes/events.ts
  packages/manager/src/utilities/formikErrorUtils.ts
Labels: React Query, Approved, Linodes

#9281 fix: [M3-6687] - Show accurate Notification Threshold values when toggling in Linode Settings
  packages/manager/.changeset/pr-9281-fixed-1686955648087.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
Labels: Add'tl Approval Needed, Bug

#9287 chore: [M3-6557] - Improve Premium plans Tab copy
  packages/manager/.changeset/pr-9287-changed-1687360553653.md
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/utils.ts
Labels: Approved

#9280 fix: [M3-6664] - Fix crash due to unescaped RegEx
  packages/manager/.changeset/pr-9280-fixed-1686949826559.md
  packages/manager/src/eventMessageGenerator.test.ts
  packages/manager/src/eventMessageGenerator.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Bug, Approved

#9284 Feat: [M3-6713] Plan availability notices for GPU
  packages/manager/.changeset/pr-9284-added-1687297470464.md
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/PlansAvailabilityNotice.styles.ts
  packages/manager/src/features/Linodes/LinodesCreate/PlansAvailabilityNotice.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/PlansAvailabilityNotice.tsx
  packages/manager/src/features/Linodes/LinodesCreate/PremiumPlansAvailabilityNotice.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/PremiumPlansAvailabilityNotice.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/GPUNotice.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanContainer.styles.ts
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanInformation.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanInformation.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlansPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/hooks/usePremiumPlans.ts
  packages/manager/src/utilities/planNotices.ts
Labels: Approved

#9163 test: [M3-6549] - Add Cypress Integration tests for OAuth Apps
  packages/api-v4/src/account/types.ts
  packages/manager/cypress/e2e/profile/add-oauth-app.spec.ts
  packages/manager/cypress/e2e/profile/delete-oauth-app.spec.ts
  packages/manager/cypress/e2e/profile/edit-oauth-app.spec.ts
  packages/manager/cypress/e2e/profile/reset-oauth-app.spec.ts
  packages/manager/cypress/support/api/profile.ts
  packages/manager/cypress/support/intercepts/profile.ts
  packages/manager/cypress/support/ui/common.ts
  packages/manager/cypress/support/util/random.ts
  packages/manager/src/factories/accountOAuth.ts
  packages/manager/src/factories/index.ts
Labels: e2e, Approved

#9275 test: [M3-6506] - Add StackScript Landing Page Integration Tests
  packages/manager/cypress/e2e/core/stackscripts/smoke-stackscripts-landing-page.spec.ts
  packages/manager/cypress/support/intercepts/stackscripts.ts
  packages/manager/src/factories/stackscripts.ts
Labels: e2e, Approved

#9289 fix: [M3-6683]: Fix confirmation modal overflow on mobile
  packages/manager/.changeset/pr-9289-fixed-1687364211275.md
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/components/DialogTitle/DialogTitle.tsx
Labels: Approved

#9292 refactor: [M3-6391] - MUI v5 Migration - `Components > SingleTextFieldForm`
  packages/manager/.changeset/pr-9292-tech-stories-1687376650053.md
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.test.tsx
  packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.tsx
  packages/manager/src/components/SingleTextFieldForm/index.ts
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
Labels: Approved, Project: MUI v5 Migration

#9298 fix: Reduce Firewall create and update e2e test flakiness
  packages/manager/.changeset/pr-9298-fixed-1687455527847.md
  packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
  packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts
  packages/manager/cypress/support/intercepts/firewalls.ts
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelectV2.tsx
Labels: Approved

#9303 Fix: [M3-6716] Regression with placeholder opacity
  packages/manager/.changeset/pr-9303-fixed-1687530086967.md
  packages/manager/src/foundations/themes/light.ts
Labels: Approved

#9297 fix: Make `yarn up:expose` actually expose Cloud Manager
  docs/GETTING_STARTED.md
  package.json
  packages/manager/.changeset/pr-9297-tech-stories-1687467224725.md
  packages/manager/package.json
Labels: Approved

#9288 style: [M3-6639] - Add outline to country flags that contain white
  packages/manager/.changeset/pr-9288-added-1687360493313.md
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/utils.ts
  packages/manager/src/components/Flag.stories.tsx
  packages/manager/src/components/Flag.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx
  packages/manager/src/utilities/formatRegion.ts
Labels: UI, Approved

#9305 chore: Update `deleteChangesets.mjs` to track changeset deletions
  packages/manager/package.json
  scripts/changelog/utils/deleteChangesets.mjs
  scripts/changelog/utils/getPullRequestId.mjs
  yarn.lock
Labels: Add'tl Approval Needed

#9301 fix: [Marketplace] - Remove underscore in prometheus & grafana svg
  packages/manager/.changeset/pr-9301-fixed-1687543469745.md
  packages/manager/public/assets/prometheus_grafana.svg
  packages/manager/public/assets/prometheusgrafana.svg
  packages/manager/public/assets/white/prometheusgrafana.svg
  packages/manager/src/features/OneClickApps/oneClickApps.ts
Labels: Bug, Marketplace, Approved

#9307 chore: Move new OAuth e2e tests into 'core' directory
  packages/manager/cypress/e2e/core/account/add-oauth-app.spec.ts
  packages/manager/cypress/e2e/core/account/delete-oauth-app.spec.ts
  packages/manager/cypress/e2e/core/account/edit-oauth-app.spec.ts
  packages/manager/cypress/e2e/core/account/reset-oauth-app.spec.ts
  packages/manager/cypress/support/api/profile.ts
  packages/manager/src/factories/accountOAuth.ts
Labels: Approved, Missing Changeset

#9306 fix: [M3-6720] - Restore DBaaS engine icons
  packages/manager/.changeset/pr-9306-fixed-1687536357483.md
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
Labels: Approved

#9304 feat: Update metadata docs link
  packages/manager/.changeset/pr-9304-added-1687531307023.md
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
Labels: Approved

#9290 Feat: [M3-6473] - Add helper text to the Add SSHKey Drawer Form
  packages/manager/.changeset/pr-9290-added-1687466679796.md
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/components/Code/Code.tsx
  packages/manager/src/components/Code/index.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/ResizeDiskDrawer.tsx
  packages/manager/src/features/Profile/SSHKeys/CreateSSHKeyDrawer.test.tsx
  packages/manager/src/features/Profile/SSHKeys/CreateSSHKeyDrawer.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
Labels: Approved

#9291 refactor: [M3-6359] - MUI v5 Migration - `Components > LongviewLineGraph`
  packages/manager/.changeset/pr-9291-tech-stories-1687369699291.md
  packages/manager/src/components/LongviewLineGraph/LongviewLineGraph.tsx
  packages/manager/src/components/LongviewLineGraph/index.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/ApacheGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ProcessGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesGraphs.tsx
Labels: Approved, Project: MUI v5 Migration

#9302 chore: Delete old changesets from `develop` branch
  packages/api-v4/.changeset/pr-9253-added-1686860188779.md
  packages/api-v4/.changeset/pr-9257-added-1686756493120.md
  packages/api-v4/.changeset/pr-9266-removed-1686852804191.md
  packages/manager/.changeset/pr-9193-tech-stories-1685478443289.md
  packages/manager/.changeset/pr-9213-tech-stories-1686062114543.md
  packages/manager/.changeset/pr-9215-fixed-1686154022321.md
  packages/manager/.changeset/pr-9218-tech-stories-1686268120191.md
  packages/manager/.changeset/pr-9220-changed-1686133289498.md
  packages/manager/.changeset/pr-9224-tech-stories-1686169209507.md
  packages/manager/.changeset/pr-9228-tech-stories-1686235871127.md
  packages/manager/.changeset/pr-9230-tech-stories-1686242146063.md
  packages/manager/.changeset/pr-9232-tech-stories-1686251566732.md
  packages/manager/.changeset/pr-9237-tech-stories-1686326150154.md
  packages/manager/.changeset/pr-9238-tech-stories-1686332206028.md
  packages/manager/.changeset/pr-9239-tech-stories-1686334794129.md
  packages/manager/.changeset/pr-9239-tech-stories-1686846441284.md
  packages/manager/.changeset/pr-9240-changed-1686335599449.md
  packages/manager/.changeset/pr-9241-tech-stories-1686337150607.md
  packages/manager/.changeset/pr-9242-tech-stories-1686601876541.md
  packages/manager/.changeset/pr-9243-changed-1686346732563.md
  packages/manager/.changeset/pr-9244-tech-stories-1686579581871.md
  packages/manager/.changeset/pr-9248-changed-1686686631424.md
  packages/manager/.changeset/pr-9253-added-1686859236273.md
  packages/manager/.changeset/pr-9254-tech-stories-1686608779585.md
  packages/manager/.changeset/pr-9255-tech-stories-1686759239474.md
  packages/manager/.changeset/pr-9256-tech-stories-1686693372703.md
  packages/manager/.changeset/pr-9260-fixed-1686769842584.md
  packages/manager/.changeset/pr-9263-tech-stories-1686839868932.md
  packages/manager/.changeset/pr-9266-removed-1686852738775.md
  packages/manager/.changeset/pr-9267-tech-stories-1686857766076.md
  packages/manager/.changeset/pr-9270-tech-stories-1686927343871.md
  packages/manager/.changeset/pr-9271-tech-stories-1686927837582.md
  packages/manager/.changeset/pr-9272-fixed-1686929413003.md
  packages/manager/.changeset/pr-9273-fixed-1686932547524.md
  packages/manager/.changeset/pr-9274-tech-stories-1686938963869.md
  packages/manager/.changeset/pr-9276-tech-stories-1686940552048.md
  packages/manager/.changeset/pr-9278-tech-stories-1686942932396.md
  packages/manager/.changeset/pr-9280-fixed-1686949826559.md
  packages/manager/.changeset/pr-9281-fixed-1686955648087.md
  packages/manager/.changeset/pr-9283-tech-stories-1687277781133.md
  packages/manager/.changeset/pr-9284-added-1687297470464.md
  packages/manager/.changeset/pr-9287-changed-1687360553653.md
Labels: Approved, Missing Changeset

#9282 refactor: [M3-6354] - MUI v5 Migration - `Components > LandingLoading`
  packages/manager/.changeset/pr-9282-tech-stories-1687053909997.md
  packages/manager/src/components/LandingLoading/LandingLoading.stories.tsx
  packages/manager/src/components/LandingLoading/LandingLoading.test.tsx
  packages/manager/src/components/LandingLoading/LandingLoading.tsx
  packages/manager/src/components/LandingLoading/index.ts
  packages/manager/src/features/Linodes/LinodesCreate/SelectAppPanel.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
Labels: Approved, Project: MUI v5 Migration

#9319 refactor: [M3-6791] - MUI v5 Migration - `Components > Toolbar`
  packages/manager/.changeset/pr-9319-tech-stories-1687875908852.md
  packages/manager/src/components/Toolbar.ts
  packages/manager/src/components/core/Toolbar.ts
  packages/manager/src/features/TopMenu/TopMenu.tsx
Labels: Approved, Project: MUI v5 Migration

#9321 refactor: [M3-6793] - MUI v5 Migration - `Components > AppBar`
  packages/manager/.changeset/pr-9321-tech-stories-1687879529410.md
  packages/manager/src/components/AppBar.ts
  packages/manager/src/components/core/AppBar.ts
  packages/manager/src/features/TopMenu/TopMenu.tsx
Labels: Approved, Project: MUI v5 Migration

#9331 hotfix: Notification Menu crash due to null value
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/api-v4/src/account/types.ts
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/eventMessageGenerator.test.ts
  packages/manager/src/eventMessageGenerator.ts
Labels: Bug, @linode/api-v4, Approved, Release → Staging, Hotfix

#9296 fix: [M3-6638] - Object Storage > Create Access Key Drawer Layout Issue
  packages/manager/.changeset/pr-9296-fixed-1687442580014.md
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
Labels: UI, Approved

#9320 refactor: [M3-6290] - MUI v5 Migration - `Components > Accordion` (part 2)
  packages/manager/.changeset/pr-9320-tech-stories-1687878769530.md
  packages/manager/src/components/Accordion.stories.tsx
  packages/manager/src/components/Accordion.tsx
  packages/manager/src/components/Accordion/Accordion.stories.mdx
  packages/manager/src/components/Accordion/index.ts
  packages/manager/src/components/ExtendedAccordion/ExtendedAccordion.test.tsx
  packages/manager/src/components/ExtendedAccordion/ExtendedAccordion.tsx
  packages/manager/src/components/core/Accordion.ts
  packages/manager/src/components/core/AccordionDetails.ts
  packages/manager/src/components/core/AccordionSummary.ts
  packages/manager/src/features/Account/AutoBackups.tsx
  packages/manager/src/features/Account/CloseAccountSetting.tsx
  packages/manager/src/features/Account/EnableManaged.tsx
  packages/manager/src/features/Account/EnableObjectStorage.tsx
  packages/manager/src/features/Account/NetworkHelper.tsx
  packages/manager/src/features/EntityTransfers/TransfersTable.tsx
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings.tsx
  packages/manager/src/features/NotificationCenter/NotificationSection.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
Labels: Approved, Project: MUI v5 Migration

#9333 Release v1.96.1 - staging → master
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/api-v4/src/account/types.ts
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/eventMessageGenerator.test.ts
  packages/manager/src/eventMessageGenerator.ts
Labels: Release, Approved, Missing Changeset

#9334 fix: local dev server `AppBarProps` export
  packages/manager/src/components/AppBar.ts
Labels: Bug, Approved, Missing Changeset

#9294 refactor: [M3-6702] - React Query - Linodes - General clean up and refactors
  packages/manager/.changeset/pr-9294-tech-stories-1687468298891.md
  packages/manager/src/App.tsx
  packages/manager/src/containers/withLinodes.container.ts
  packages/manager/src/features/Account/EnableManaged.tsx
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Images/ImageSelect.test.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Linodes/CloneLanding/CloneLanding.tsx
  packages/manager/src/features/Linodes/CloneLanding/Details.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
  packages/manager/src/features/Linodes/LinodeSelect/index.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/types.ts
  packages/manager/src/features/Linodes/LinodesDetail/HostMaintenanceError.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeActivity/LinodeActivity.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeActivity/LinodeActivity.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeActivity/index.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeDetailErrorBoundary.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodePermissionsError.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/LinodeRebuildDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/StandardRescueDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettings.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateDiskDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetail.container.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetail.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx
  packages/manager/src/features/Linodes/LinodesDetail/README.md
  packages/manager/src/features/Linodes/LinodesDetail/index.tsx
  packages/manager/src/features/Linodes/LinodesDetail/linodeDetailContext.tsx
  packages/manager/src/features/Linodes/index.tsx
  packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
  packages/manager/src/features/Search/SearchLanding.test.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/Volumes/DestructiveVolumeDialog.tsx
  packages/manager/src/features/Volumes/VolumeAttachmentDrawer.tsx
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/hooks/useEntities.ts
  packages/manager/src/hooks/useExtendedLinode.ts
  packages/manager/src/hooks/useLinodeActions.ts
  packages/manager/src/hooks/useLinodes.ts
  packages/manager/src/hooks/useReduxLoad.test.ts
  packages/manager/src/hooks/useReduxLoad.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/store/linodes/linode.containers.ts
  packages/manager/src/utilities/testHelpersStore.ts
Labels: React Query, Approved, Clean Up

#9327 Refactor: [M3-6522-selection-card] Selection Card: named exports and v7 story
  packages/manager/.changeset/pr-9327-tech-stories-1687891798862.md
  packages/manager/src/components/SelectionCard/CardBase.styles.ts
  packages/manager/src/components/SelectionCard/CardBase.test.tsx
  packages/manager/src/components/SelectionCard/CardBase.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.stories.mdx
  packages/manager/src/components/SelectionCard/SelectionCard.stories.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/components/SelectionCard/index.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
  packages/manager/src/features/LinodeConfigSelectionDrawer/LinodeConfigSelectionDrawer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectBackupPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanSelection.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectionCardWrapper.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  yarn.lock
Labels: Approved, Project: MUI v5 Migration

#9286 feat: [M3-6707] – Light/dark mode shortcut copy on the "My Settings" page
  packages/manager/.changeset/pr-9286-added-1687296191023.md
  packages/manager/src/App.tsx
  packages/manager/src/features/Profile/Settings/Settings.tsx
Labels: Approved

#9295 refactor: [M3-6361] - MUI v5 Migration - `Components > MenuItem`
  packages/manager/.changeset/pr-9295-changed-1687441083123.md
  packages/manager/src/components/MenuItem/MenuItem.tsx
  packages/manager/src/components/MenuItem/index.ts
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedSelect.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
Labels: Approved, Project: MUI v5 Migration

#9313 Refactor: [M3-6522] - Update Link component export and improve Storybook story
  packages/manager/.changeset/pr-9313-tech-stories-1687805591350.md
  packages/manager/src/components/BackupStatus/BackupStatus.tsx
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.stories.mdx
  packages/manager/src/components/EmptyLandingPageResources/ResourcesLinks.tsx
  packages/manager/src/components/EmptyLandingPageResources/ResourcesMoreLink.tsx
  packages/manager/src/components/EntityHeader/EntityHeader.stories.tsx
  packages/manager/src/components/Link.stories.mdx
  packages/manager/src/components/Link.stories.tsx
  packages/manager/src/components/Link.tsx
  packages/manager/src/components/MaintenanceScreen.tsx
  packages/manager/src/components/Tile/Tile.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplay.tsx
  packages/manager/src/components/TypeToConfirm/TypeToConfirm.tsx
  packages/manager/src/eventMessageGenerator_CMR.tsx
  packages/manager/src/features/Account/AccountLoginsTableRow.tsx
  packages/manager/src/features/Account/Agreements/EUAgreementCheckbox.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Domains/DomainBanner.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
  packages/manager/src/features/GlobalNotifications/APIMaintenanceBanner.tsx
  packages/manager/src/features/GlobalNotifications/TaxCollectionBanner.tsx
  packages/manager/src/features/Help/StatusBanners.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/HACheckbox.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
  packages/manager/src/features/Linodes/LinodesLanding/AppsSection.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/Profile/Referrals/Referrals.tsx
  packages/manager/src/features/Profile/SSHKeys/CreateSSHKeyDrawer.tsx
  packages/manager/src/features/Profile/Settings/PreferenceEditor.tsx
  packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
  packages/manager/src/features/TopMenu/Community.tsx
  packages/manager/src/features/TopMenu/Help.tsx
  packages/manager/src/features/Volumes/UpgradeVolumeDialog.tsx
Labels: Add'tl Approval Needed

#9336 Fix: [M3-6800] Firewall custom port validation
  packages/manager/.changeset/pr-9336-fixed-1687982995866.md
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.utils.ts
  packages/validation/.changeset/pr-9336-fixed-1687983041491.md
  packages/validation/src/firewalls.schema.ts
Labels: Approved

#9340 refactor: [M3-6458] - Remove old changelog scripting
  packages/manager/.changeset/pr-9340-tech-stories-1688049933151.md
  packages/manager/config/env.js
  packages/manager/config/paths.js
  packages/manager/config/polyfills.js
  packages/manager/config/testSetup.js
  packages/manager/package.json
  packages/manager/scripts/jira-changelog.sh
  packages/manager/scripts/release_changelog.sh
  packages/manager/scripts/test.js
  packages/manager/src/testHelpers.ts
  packages/manager/src/testSetup.ts
  scripts/changelog/action.yml
  scripts/changelog/changeset-bot.mjs
  scripts/changelog/changeset.mjs
  scripts/changelog/compiled/README.md
  scripts/changelog/compiled/index.mjs
  scripts/generate_changelog.py
  scripts/package-versions/index.js
  scripts/publish_changelog.sh
  yarn.lock
Labels: Ready for Review, Clean Up

#9344 hotfix: [M3-6800] - Firewall Validation
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.utils.ts
  packages/validation/src/firewalls.schema.ts
Labels: Approved, Release → Staging, Hotfix

#9332 fix: [M3-5577] - Disable delete button for public IP addresses
  packages/manager/.changeset/pr-9332-fixed-1687902148264.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
Labels: Approved

#9346 Release v1.96.2 – `master` → `develop`
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-9294-tech-stories-1687468298891.md
  packages/manager/.changeset/pr-9336-fixed-1687982995866.md
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/eventMessageGenerator.test.ts
  packages/manager/src/eventMessageGenerator.ts
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Approved, Missing Changeset, Master → Develop

#9335 chore: [M3-6666] - Clean up for consistent spelling of "canceled"
  packages/api-v4/.changeset/pr-9335-changed-1687980892035.md
  packages/api-v4/src/entity-transfers/types.ts
  packages/manager/cypress/e2e/core/account/service-transfer.spec.ts
  packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx
  packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: @linode/api-v4, Approved

#9323 Refactor: [M3-6522-copy-tooltip] CopyTooltip: Styled component and v7 story
  packages/manager/.changeset/pr-9323-tech-stories-1687882441444.md
  packages/manager/src/components/Chip.stories.tsx
  packages/manager/src/components/CopyTooltip/CopyTooltip.stories.mdx
  packages/manager/src/components/CopyTooltip/CopyTooltip.stories.tsx
  packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
Labels: Approved

#9352 Fix: [M3-6786] ActionMenu tooltip icon color
  packages/manager/.changeset/pr-9352-fixed-1688140397688.md
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
Labels: Approved

#9318 refactor: Remove `withLoadingAndError` and clean up 2FA components
  packages/manager/.changeset/pr-9318-tech-stories-1687825157533.md
  packages/manager/src/components/withLoadingAndError/index.ts
  packages/manager/src/components/withLoadingAndError/withLoadingAndError.test.tsx
  packages/manager/src/components/withLoadingAndError/withLoadingAndError.ts
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/DisableTwoFactorDialog.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/ScratchCodeDialog.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
  packages/manager/src/queries/profile.ts
  packages/manager/src/requestableContext.tsx
Labels: Approved, Clean Up

#9330 Chore: [M3-6527] - Storybook update and maintenance fixes
  packages/manager/.storybook/preview.tsx
  packages/manager/package.json
  yarn.lock
Labels: Approved

#9339 refactor: [M3-6804] - MUI v5 Migration - `Components > Chip`
  packages/manager/.changeset/pr-9339-tech-stories-1688002163233.md
  packages/manager/src/components/BetaChip/BetaChip.tsx
  packages/manager/src/components/Chip.stories.tsx
  packages/manager/src/components/Chip.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.stories.tsx
  packages/manager/src/components/ShowMore/ShowMore.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/components/Tag/Tag.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AppPanelSection.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanSelection.styles.ts
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
Labels: Approved, Project: MUI v5 Migration

#9355 fix: [M3-6177] - Only request logo once for invoice pdf
  packages/manager/.changeset/pr-9355-fixed-1688147944694.md
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
Labels: Bug, Approved
