Repository linode/manager, pull requests merged in 2023-08, with the labels that each got.

#9459 fix: [M3-6658] - Cleared Firewall Drawer Inputs
  packages/manager/.changeset/pr-9459-fixed-1690565333481.md
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
Labels: Approved

#9473 fix: Add Gopaddle & re-add Wazuh Marketplace apps
  packages/manager/.changeset/pr-9473-fixed-1690900164385.md
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Marketplace, Approved

#9454 refactor: [M3-6943] - MUI v5 Migration - `SRC > Components > InputAdornment`
  packages/manager/.changeset/pr-9454-tech-stories-1690412371348.md
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx
  packages/manager/src/components/InputAdornment.stories.tsx
  packages/manager/src/components/InputAdornment.tsx
  packages/manager/src/components/TextField.stories.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/components/core/InputAdornment.ts
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateDiskDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/ResizeDiskDrawer.tsx
  packages/manager/src/features/Managed/MonitorDrawer.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerActiveCheck.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
  packages/manager/src/features/Support/AttachFileListItem.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
Labels: Storybook, Approved, Project: MUI v5 Migration

#9474 feat: [M3-6948] - Add basic routing for VPC
  packages/manager/.changeset/pr-9474-added-1690902058543.md
  packages/manager/src/GoTo.tsx
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/VPC/VPCCreate/VPCCreate.tsx
  packages/manager/src/features/VPC/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPC/index.tsx
Labels: Approved, VPC

#9475 chore: Fix broken changelog links
  CHANGELOG.md
Labels: Approved, Missing Changeset

#9455 chore: [M3-4317] - Remove Bluebird.js as a dependency
  packages/manager/.changeset/pr-9455-tech-stories-1690432975869.md
  packages/manager/package.json
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/manager/src/queries/managed/helpers.ts
  packages/manager/src/store/backupDrawer/index.ts
  packages/manager/src/utilities/reduceAsync.ts
  yarn.lock
Labels: Dependencies, Approved

#9464 fix: Fix `<LinodeSelect />` bugs
  packages/manager/.changeset/pr-9464-tech-stories-1690560314706.md
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
  packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/validation/src/nodebalancers.schema.ts
Labels: Bug, Approved

#9418 feat: [M3-6724]: Linode Config & Interface endpoints, validation, and React Query queries
  packages/api-v4/.changeset/pr-9418-added-1690303394895.md
  packages/api-v4/src/linodes/configs.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-9418-tech-stories-1690303249242.md
  packages/manager/src/App.tsx
  packages/manager/src/queries/linodes/configs.ts
  packages/validation/.changeset/pr-9418-added-1690303540547.md
  packages/validation/.changeset/pr-9418-changed-1690303623040.md
  packages/validation/src/linodes.schema.ts
  packages/validation/src/vpcs.schema.ts
Labels: @linode/api-v4, @linode/validation, Approved, VPC

#9476 refactor: [M3-6956] - MUI v5 Migration - `SRC > Components > FormControlLabel`
  packages/manager/.changeset/pr-9476-tech-stories-1690908160732.md
  packages/manager/src/components/Checkbox.tsx
  packages/manager/src/components/FormControlLabel.stories.tsx
  packages/manager/src/components/FormControlLabel.tsx
  packages/manager/src/components/ModeSelect/ModeSelect.tsx
  packages/manager/src/components/Radio/Radio.stories.tsx
  packages/manager/src/components/Toggle/Toggle.stories.mdx
  packages/manager/src/components/core/FormControlLabel.ts
  packages/manager/src/features/Account/AutoBackups.tsx
  packages/manager/src/features/Account/NetworkHelper.tsx
  packages/manager/src/features/Backups/AutoEnroll.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/manager/src/features/Domains/CloneDomainDrawer.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Domains/EditDomainDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleForm.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanSelection.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx
  packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerPassiveCheck.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactorToggle.tsx
  packages/manager/src/features/Profile/OAuthClients/CreateOAuthClientDrawer.tsx
  packages/manager/src/features/Profile/OAuthClients/EditOAuthClientDrawer.tsx
  packages/manager/src/features/Profile/Settings/Settings.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedSelect.tsx
  packages/manager/src/features/Users/CreateUserDrawer.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/ModeSelection.tsx
Labels: Approved, Project: MUI v5 Migration

#9478 chore: Add 'Upcoming Features' to the changeset types
  docs/CONTRIBUTING.md
  packages/api-v4/.changeset/README.md
  packages/manager/.changeset/README.md
  packages/manager/.changeset/pr-9419-tech-stories-1689716682370.md
  packages/validation/.changeset/README.md
  scripts/changelog/utils/constants.mjs
Labels: Approved, Missing Changeset

#9484 chore: [M3-6954] - Change `Premium` to `Premium CPU`
  packages/manager/.changeset/pr-9484-changed-1690998482707.md
  packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/utils.ts
Labels: Approved

#9483 chore: Upgrade Cypress to 12.17.3
  packages/manager/Dockerfile
  packages/manager/package.json
  yarn.lock
Labels: Approved, Missing Changeset

#9486 refactor: organize PlansPanel component
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/features/components/PlansPanel/MetalNotice.tsx
  packages/manager/src/features/components/PlansPanel/PlanContainer.styles.ts
  packages/manager/src/features/components/PlansPanel/PlanContainer.tsx
  packages/manager/src/features/components/PlansPanel/PlanInformation.test.tsx
  packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.styles.ts
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.styles.ts
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
  packages/manager/src/features/components/PlansPanel/utils.test.ts
  packages/manager/src/features/components/PlansPanel/utils.ts
Labels: Approved, Missing Changeset

#9491 fix: [M3-6688] - Alignment Issue on Service Transfers Page
  packages/manager/.changeset/pr-9491-fixed-1691152316740.md
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx
Labels: Approved

#9490 feat: [M3-6734] - VPC delete dialog
  packages/manager/.changeset/pr-9490-upcoming-features-1691091640290.md
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
  packages/manager/cypress/support/intercepts/vpc.ts
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCDeleteDialog.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCLanding.test.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCRow.test.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCRow.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, VPC

#9495 fix: IP Address copy icon regression
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
Labels: Bug, Approved

#9494 fix: [M3-6985] - User data input crash
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Labels: Add'tl Approval Needed, Bug, Project: Metadata

#9438 refactor: [M3-6260] - MUI v5 Migration - SRC > Features > Backups
  packages/manager/.changeset/pr-9438-tech-stories-1689965955259.md
  packages/manager/src/features/Backups/AutoEnroll.test.tsx
  packages/manager/src/features/Backups/AutoEnroll.tsx
  packages/manager/src/features/Backups/BackupDrawer.test.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Backups/BackupLinodes.test.tsx
  packages/manager/src/features/Backups/BackupLinodes.tsx
  packages/manager/src/features/Backups/BackupsCTA.styles.ts
  packages/manager/src/features/Backups/BackupsCTA.tsx
  packages/manager/src/features/Backups/BackupsTable.test.tsx
  packages/manager/src/features/Backups/BackupsTable.tsx
  packages/manager/src/features/Backups/index.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/queries/linodes/configs.ts
Labels: Project: MUI v5 Migration

#9441 refactor: [M3-6275] - MUI v5 Migration - SRC > Features > Managed
  packages/manager/.changeset/pr-9441-tech-stories-1690821997266.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Backups/BackupsTable.tsx
  packages/manager/src/features/Managed/Contacts/Contacts.styles.tsx
  packages/manager/src/features/Managed/Contacts/Contacts.tsx
  packages/manager/src/features/Managed/Contacts/ContactsActionMenu.tsx
  packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
  packages/manager/src/features/Managed/Contacts/ContactsRow.tsx
  packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx
  packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
  packages/manager/src/features/Managed/Credentials/CredentialActionMenu.tsx
  packages/manager/src/features/Managed/Credentials/CredentialList.tsx
  packages/manager/src/features/Managed/Credentials/CredentialRow.tsx
  packages/manager/src/features/Managed/Credentials/CredentialTableContent.tsx
  packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/DashboardCard.styles.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/DashboardCard.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.styles.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedDashboardCard.styles.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedDashboardCard.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/MonitorStatus.styles.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/MonitorStatus.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/MonitorTickets.styles.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/MonitorTickets.tsx
  packages/manager/src/features/Managed/MonitorDrawer.tsx
  packages/manager/src/features/Managed/Monitors/HistoryDrawer.tsx
  packages/manager/src/features/Managed/Monitors/IssueCalendar.tsx
  packages/manager/src/features/Managed/Monitors/IssueDay.styles.tsx
  packages/manager/src/features/Managed/Monitors/IssueDay.test.tsx
  packages/manager/src/features/Managed/Monitors/IssueDay.tsx
  packages/manager/src/features/Managed/Monitors/MonitorActionMenu.test.tsx
  packages/manager/src/features/Managed/Monitors/MonitorActionMenu.tsx
  packages/manager/src/features/Managed/Monitors/MonitorRow.styles.tsx
  packages/manager/src/features/Managed/Monitors/MonitorRow.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTable.styles.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTable.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTableContent.tsx
  packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.styles.tsx
  packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx
  packages/manager/src/features/Managed/SSHAccess/LinodePubKey.styles.tsx
  packages/manager/src/features/Managed/SSHAccess/LinodePubKey.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccess.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.test.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessRow.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessTable.styles.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessTable.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessTableContent.tsx
  packages/manager/src/features/Managed/SupportWidget.tsx
  packages/manager/src/features/Managed/index.tsx
Labels: Approved, Project: MUI v5 Migration

#9505 fix: [M3-6898] - Markup in Help landing
  packages/manager/src/features/Help/Panels/AlgoliaSearchBar.tsx
Labels: Bug

#9508 fix: linodes empty state - styles needed to be swapped
  packages/manager/src/features/Linodes/LinodesLanding/AppsSection.tsx
Labels: Bug

#9507 fix: Make drawer full width for app detail drawer on mobile viewport
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
Labels: Bug

#9503 fix: Allow auto-generated Linode `label` to be cleared
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
Labels: Bug

#9506 fix: Linode Select clear behavior by using `null` instead of `-1` in form state
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx
  packages/validation/src/volumes.schema.ts
Labels: Bug

#9499 fix: [M3-6498] - User Permissions table radio button misalignment on mobile
  packages/manager/.changeset/pr-9499-fixed-1691416274996.md
  packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
Labels: Bug

#9513 chore: Organize Storybook `LandingLoading` component
  packages/manager/src/components/LandingLoading/LandingLoading.stories.tsx
Labels: Storybook

#9482 chore: Clean up Profile Settings
  packages/manager/.changeset/pr-9482-tech-stories-1690991270035.md
  packages/manager/src/features/Profile/Settings/PreferenceEditor.tsx
  packages/manager/src/features/Profile/Settings/Settings.tsx
Labels: Approved, Clean Up

#9477 M3-6614 Add Cypress tests for Linode landing page 'Summary View'
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/src/features/Linodes/LinodesLanding/CardView.tsx
Labels: Approved, Missing Changeset

#9509 fix: [M3-6668] Broken K8 node pool infinite scrolling
  packages/manager/.changeset/pr-9509-fixed-1691434601314.md
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
Labels: Approved, Ready for Review

#9518 fix: [M3-6998] - Disabled Select tooltip hover
  packages/manager/.changeset/pr-9518-fixed-1691522243561.md
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
Labels: Bug, Approved

#9521 fix:[M3-6500] - Enhanced Select fields text cut off at bottom
  packages/manager/.changeset/pr-9521-fixed-1691588152719.md
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
Labels: Approved

#9515 fix: [M3-6763] - Cleared OAuth client inputs after canceling or submitting
  packages/manager/.changeset/pr-9515-fixed-1691506292062.md
  packages/manager/src/features/Profile/OAuthClients/CreateOAuthClientDrawer.tsx
Labels: Bug, Approved

#9527 refactor: [M3-6669] - Replaced deprecated keycodes
  packages/manager/.changeset/pr-9527-tech-stories-1691605134705.md
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
Labels: Approved

#9526 chore: [M3-6772] - Clean up one-off link styles
  packages/manager/src/components/IconTextLink/IconTextLink.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.styles.ts
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/ResetPassword.tsx
  packages/manager/src/features/Search/ResultRow.tsx
  packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
Labels: Approved

#9462 feat: [M3-6814] - Add AGLB empty state
  packages/manager/.changeset/pr-9462-upcoming-features-1691760025987.md
  packages/manager/src/components/EmptyLandingPageResources/ResourcesSection.tsx
  packages/manager/src/components/Placeholder/Placeholder.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerEmptyStateData.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerLandingEmptyState.tsx
Labels: Approved, AGLB

#9536 hotfix: Unescape encoding for user data
  packages/manager/.changeset/pr-9536-fixed-1691767427821.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/utilities.tsx
Labels: Bug, Project: Metadata, Approved, Hotfix

#9533 refactor: [M3-7006] - Make `UserMenu` use MUI instead of Reach UI
  packages/manager/.changeset/pr-9533-tech-stories-1691707780382.md
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/components/Link.tsx
  packages/manager/src/components/UserMenu.stories.mdx
  packages/manager/src/features/NotificationCenter/NotificationSection.tsx
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/TopMenu/UserMenu/index.ts
  packages/manager/src/foundations/themes/dark.ts
Labels: UI, Approved

#9538 Release v1.99.1 - staging → master
  packages/manager/.changeset/pr-9536-fixed-1691767427821.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/utilities.tsx
Labels: Release, Approved

#9489 feat: [M3-6787] - Update LKE HA implementation
  packages/api-v4/src/kubernetes/types.ts
  packages/manager/.changeset/pr-9489-tech-stories-1691180131190.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeClusterDialog.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.ts
Labels: Approved

#9528 feat: [M3-6735] - VPC Edit drawer
  packages/manager/.changeset/pr-9528-upcoming-features-1691607557491.md
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
  packages/manager/cypress/support/intercepts/vpc.ts
  packages/manager/src/features/VPC/VPCLanding/VPCDeleteDialog.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCEditDrawer.test.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCEditDrawer.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCRow.test.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCRow.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, VPC

#9542 Release v1.99.1 - `master` -> `develop`
  packages/manager/.changeset/pr-9536-fixed-1691767427821.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/utilities.tsx
Labels: Approved, Missing Changeset

#9463 feat: [M3-6646] - Strip whitespace on blur for username and email textfields
  packages/manager/.changeset/pr-9463-changed-1690912398697.md
  packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.tsx
  packages/manager/src/components/TextField.test.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Domains/DomainRecordDrawer.tsx
  packages/manager/src/features/Domains/EditDomainDrawer.tsx
  packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
  packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
  packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/Profile/SSHKeys/CreateSSHKeyDrawer.tsx
  packages/manager/src/features/Users/CreateUserDrawer.tsx
  packages/manager/src/features/Users/UserDetail.tsx
  packages/manager/src/features/Users/UserProfile.tsx
  packages/manager/src/utilities/formikTrimUtil.test.tsx
  packages/manager/src/utilities/formikTrimUtil.tsx
  packages/validation/src/domains.schema.ts
Labels: Approved

#9543 fix: Duplicate `key` error on Linodes Landing
  packages/manager/.changeset/pr-9543-tech-stories-1692026704155.md
  packages/manager/src/features/Linodes/LinodesLanding/IPAddress.tsx
Labels: Bug, Approved

#9534 fix: [M3-7002] Topbar Search fixes
  packages/manager/.changeset/pr-9534-fixed-1691788679611.md
  packages/manager/src/components/EnhancedSelect/components/SelectPlaceholder.tsx
  packages/manager/src/components/Tag/Tag.tsx
  packages/manager/src/features/Search/ResultRow.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.styles.ts
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
Labels: Approved

#9522 chore: Clean up `withRouter` usage
  packages/manager/.changeset/pr-9522-tech-stories-1691593109791.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Help/SupportSearchLanding/HelpResources.tsx
  packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.test.tsx
  packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.tsx
  packages/manager/src/features/Images/ImageRow.tsx
  packages/manager/src/features/Images/ImagesActionMenu.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
  packages/manager/src/features/Images/index.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx
  packages/manager/src/features/Profile/Profile.tsx
  packages/manager/src/features/Profile/index.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptActionMenu.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx
  packages/manager/src/features/StackScripts/StackScripts.tsx
  packages/manager/src/features/Users/UserProfile.tsx
  packages/manager/src/features/Volumes/Volumes.tsx
Labels: Approved, Clean Up

#9496 chore: [M3-6986] - Update AGLB endpoint, factories, and mocks
  packages/api-v4/src/aglb/certificates.ts
  packages/api-v4/src/aglb/configurations.ts
  packages/api-v4/src/aglb/entrypoints.ts
  packages/api-v4/src/aglb/index.ts
  packages/api-v4/src/aglb/loadbalancers.ts
  packages/api-v4/src/aglb/routes.ts
  packages/api-v4/src/aglb/service-targets.ts
  packages/api-v4/src/aglb/types.ts
  packages/manager/.changeset/pr-9496-upcoming-features-1691614623406.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-service-targets.spec.ts
  packages/manager/src/factories/aglb.ts
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetLanding.test.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetLanding.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/aglb/loadbalancers.ts
  packages/manager/src/queries/aglb/serviceTargets.ts
Labels: Approved, AGLB

#9498 refactor: [M3-6286] - SRC > Features > TopMenu
  package.json
  packages/manager/.changeset/pr-9498-tech-stories-1691768096558.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
  packages/manager/src/components/TopMenu.stories.mdx
  packages/manager/src/features/Help/Panels/AlgoliaSearchBar.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.test.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/index.ts
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.styles.ts
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.styles.ts
  packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.tsx
  packages/manager/src/features/TopMenu/SearchBar/index.tsx
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/TopMenu/index.ts
  yarn.lock
Labels: Approved, Project: MUI v5 Migration

#9525 chore: Clean up how dev tools are initialized
  packages/manager/.changeset/pr-9525-tech-stories-1691597467673.md
  packages/manager/src/constants.ts
  packages/manager/src/dev-tools/load.test.ts
  packages/manager/src/dev-tools/load.ts
  packages/manager/src/index.tsx
  packages/manager/src/utilities/env.ts
  packages/manager/src/utilities/storage.ts
Labels: Approved, Clean Up

#9535 chore: [M3-7012] - Add documentation for Typescript unions, const enums and objects
  docs/development-guide/13-coding-standards.md
Labels: Approved, Documentation

#9548 fix: [M3-7024] - Fix Hively visual regression
  packages/manager/.changeset/pr-9548-fixed-1692123558409.md
  packages/manager/src/components/Link.tsx
  packages/manager/src/features/Support/Hively.tsx
Labels: Bug, Approved

#9517 refactor: [M3-6953] - Refactor Backups Drawer
  packages/manager/.changeset/pr-9517-tech-stories-1691521279701.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Backups/AutoEnroll.test.tsx
  packages/manager/src/features/Backups/AutoEnroll.tsx
  packages/manager/src/features/Backups/BackupDrawer.test.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Backups/BackupLinodeRow.test.tsx
  packages/manager/src/features/Backups/BackupLinodeRow.tsx
  packages/manager/src/features/Backups/BackupLinodes.test.tsx
  packages/manager/src/features/Backups/BackupLinodes.tsx
  packages/manager/src/features/Backups/BackupsCTA.test.tsx
  packages/manager/src/features/Backups/BackupsCTA.tsx
  packages/manager/src/features/Backups/BackupsTable.test.tsx
  packages/manager/src/features/Backups/BackupsTable.tsx
  packages/manager/src/features/Backups/index.tsx
  packages/manager/src/features/Backups/types.ts
  packages/manager/src/features/Backups/utils.test.ts
  packages/manager/src/features/Backups/utils.ts
  packages/manager/src/store/backupDrawer/index.test.ts
  packages/manager/src/store/backupDrawer/index.ts
  packages/manager/src/store/index.ts
  packages/manager/tsconfig.json
Labels: Approved, Clean Up

#9540 refactor: [M3-7022] - Make `<ActionMenu />` use MUI instead of Reach UI
  packages/manager/.changeset/pr-9540-tech-stories-1691791833238.md
  packages/manager/cypress/e2e/core/account/default-payment-method.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/cypress/support/ui/action-menu.ts
  packages/manager/cypress/support/ui/buttons.ts
  packages/manager/package.json
  packages/manager/src/App.tsx
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.test.tsx
  packages/manager/src/components/TabLinkList/TabLinkList.tsx
  packages/manager/src/features/Kubernetes/ClusterList/ClusterActionMenu.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerDetail.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.test.tsx
  packages/manager/src/foundations/themes/light.ts
  packages/manager/src/utilities/testHelpers.tsx
  yarn.lock
Labels: UI, Approved

#9470 feat: [M3-6944]: Add Firewalls table to `Linode Details > Network` tab
  packages/manager/.changeset/pr-9470-added-1691528022524.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
  packages/manager/src/features/Firewalls/shared.ts
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/EditRangeRDNSDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls/LinodeFirewalls.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls/LinodeFirewalls.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls/LinodeFirewallsActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls/LinodeFirewallsRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.styles.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.test.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetwork.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/ViewRDNSDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/manager/src/queries/firewalls.ts
Labels: Approved, VPC

#9516 Feat: [M3-6925] Add Event story + playground
  packages/manager/.changeset/pr-9516-tech-stories-1691663475598.md
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/Events/Events.stories.tsx
  packages/manager/src/features/Events/constants.ts
  packages/manager/src/features/Events/eventMessageGenerator.test.ts
  packages/manager/src/features/Events/eventMessageGenerator.ts
  packages/manager/src/features/Events/eventMessageGenerator_CMR.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/ActivityRow.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useEventInfo.ts
Labels: Approved

#9553 fix: Failing `LinodeRow.test.tsx` unit test
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx
Labels: Approved, Unit tests, Missing Changeset

#9550 fix: [M3:-7009] - Resizing Under the Reputation Score Provides Incorrect Error
  packages/manager/.changeset/pr-9550-fixed-1692190165115.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
Labels: Approved

#9532 refactor: [M3-6281] - SRC > Features > Search CSS Migration
  packages/manager/.changeset/pr-9532-tech-stories-1691694231865.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Search/ResultGroup.styles.ts
  packages/manager/src/features/Search/ResultGroup.test.tsx
  packages/manager/src/features/Search/ResultGroup.tsx
  packages/manager/src/features/Search/ResultRow.styles.ts
  packages/manager/src/features/Search/ResultRow.tsx
  packages/manager/src/features/Search/SearchLanding.styles.ts
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/index.tsx
  packages/manager/src/features/Search/useAPISearch.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
Labels: Approved, Project: MUI v5 Migration

#9551 feat: [M3-6818] - Add AGLB Details - Summary Page
  packages/manager/.changeset/pr-9551-upcoming-features-1692204714914.md
  packages/manager/src/components/StatusIcon/StatusIcon.tsx
  packages/manager/src/factories/aglb.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerDetail.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerSummary.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerLanding.tsx
  packages/manager/src/features/LoadBalancers/index.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/aglb/configurations.ts
  packages/manager/src/queries/aglb/loadbalancers.ts
  packages/manager/src/queries/aglb/serviceTargets.ts
Labels: Approved, AGLB

#9554 fix: [M3-6836] - Fix Firewalls Breadcrumb
  packages/manager/.changeset/pr-9554-fixed-1692219454826.md
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Firewalls/index.tsx
Labels: Bug, Approved

#9546 feat: [M3-7027] - Remove customer tag check for Metadata
  packages/manager/.changeset/pr-9546-upcoming-features-1692199565994.md
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/utils.ts
Labels: Project: Metadata, Approved

#9557 chore: [M3-6691] - Add DC-specific pricing feature flag
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
Labels: Approved, DC-Specific Pricing

#9552 fix: Reduce Cypress test flake, August 2023
  packages/manager/cypress/e2e/core/account/default-payment-method.spec.ts
  packages/manager/cypress/e2e/core/databases/create-database.spec.ts
  packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts
  packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage-errors.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/clone-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/resize-volume.spec.ts
  packages/manager/cypress/support/api/lke.ts
  packages/manager/cypress/support/constants/lke.ts
  packages/manager/cypress/support/intercepts/databases.ts
  packages/manager/cypress/support/intercepts/events.ts
  packages/manager/cypress/support/util/polling.ts
  packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.tsx
Labels: Approved, Missing Changeset

#9564 feat: [M3-7037] Introduce dynamic pricing utils
  packages/manager/.changeset/pr-9564-added-1692350316540.md
  packages/manager/src/utilities/pricing/constants.ts
  packages/manager/src/utilities/pricing/dynamicPricing.test.tsx
  packages/manager/src/utilities/pricing/dynamicPricing.ts
  packages/manager/src/utilities/pricing/entityPricing.ts
Labels: Approved

#9566 feat: [M3-6974] - Add DC Specific Pricing to NodeBalancer Create
  packages/manager/.changeset/pr-9566-upcoming-features-1692376980714.md
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/utilities/pricing/dynamicPricing.ts
Labels: Approved, DC-Specific Pricing

#9567 fix: Make feature flag dev tools show reality
  packages/manager/.changeset/pr-9567-tech-stories-1692380986951.md
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
Labels: Approved

#9574 Release v1.100.0 - develop <- master
  packages/api-v4/.changeset/pr-9485-changed-1691764196950.md
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/manager/.changeset/pr-9462-upcoming-features-1691760025987.md
  packages/manager/.changeset/pr-9463-changed-1690912398697.md
  packages/manager/.changeset/pr-9465-upcoming-features-1691006815902.md
  packages/manager/.changeset/pr-9470-added-1691528022524.md
  packages/manager/.changeset/pr-9482-tech-stories-1690991270035.md
  packages/manager/.changeset/pr-9485-upcoming-features-1691086745329.md
  packages/manager/.changeset/pr-9488-tech-stories-1691077075702.md
  packages/manager/.changeset/pr-9489-tech-stories-1691180131190.md
  packages/manager/.changeset/pr-9490-upcoming-features-1691091640290.md
  packages/manager/.changeset/pr-9491-fixed-1691152316740.md
  packages/manager/.changeset/pr-9492-upcoming-features-1691161151116.md
  packages/manager/.changeset/pr-9496-upcoming-features-1691614623406.md
  packages/manager/.changeset/pr-9498-tech-stories-1691768096558.md
  packages/manager/.changeset/pr-9499-fixed-1691416274996.md
  packages/manager/.changeset/pr-9501-tech-stories-1691417405756.md
  packages/manager/.changeset/pr-9509-fixed-1691434601314.md
  packages/manager/.changeset/pr-9510-fixed-1691435597748.md
  packages/manager/.changeset/pr-9512-fixed-1691442376475.md
  packages/manager/.changeset/pr-9515-fixed-1691506292062.md
  packages/manager/.changeset/pr-9516-tech-stories-1691663475598.md
  packages/manager/.changeset/pr-9517-tech-stories-1691521279701.md
  packages/manager/.changeset/pr-9518-fixed-1691522243561.md
  packages/manager/.changeset/pr-9521-fixed-1691588152719.md
  packages/manager/.changeset/pr-9522-tech-stories-1691593109791.md
  packages/manager/.changeset/pr-9525-tech-stories-1691597467673.md
  packages/manager/.changeset/pr-9527-tech-stories-1691605134705.md
  packages/manager/.changeset/pr-9528-upcoming-features-1691607557491.md
  packages/manager/.changeset/pr-9532-tech-stories-1691694231865.md
  packages/manager/.changeset/pr-9533-tech-stories-1691707780382.md
  packages/manager/.changeset/pr-9534-fixed-1691788679611.md
  packages/manager/.changeset/pr-9536-fixed-1691767427821.md
  packages/manager/.changeset/pr-9540-tech-stories-1691791833238.md
  packages/manager/.changeset/pr-9543-tech-stories-1692026704155.md
  packages/manager/.changeset/pr-9546-upcoming-features-1692199565994.md
  packages/manager/.changeset/pr-9547-fixed-1692129984580.md
  packages/manager/.changeset/pr-9548-fixed-1692123558409.md
  packages/manager/.changeset/pr-9550-fixed-1692190165115.md
  packages/manager/.changeset/pr-9551-upcoming-features-1692204714914.md
  packages/manager/.changeset/pr-9554-fixed-1692219454826.md
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/validation/.changeset/pr-9485-changed-1691773014756.md
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Approved, Master → Develop

#9569 feat: [M3-6971] Add dynamic pricing model to Volume creation flows
  packages/manager/.changeset/pr-9569-changed-1692553123699.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.tsx
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CloneVolumeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/PricePanel.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/ResizeVolumeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/VolumeDrawer.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/Volumes/VolumesActionMenu.test.tsx
  packages/manager/src/features/Volumes/VolumesActionMenu.tsx
  packages/manager/src/store/volumeForm/index.ts
  packages/manager/src/utilities/pricing/dynamicPricing.test.tsx
  packages/manager/src/utilities/pricing/dynamicPricing.ts
  packages/manager/src/utilities/pricing/dynamicVolumePrice.test.tsx
  packages/manager/src/utilities/pricing/dynamicVolumePrice.ts
  packages/manager/src/utilities/pricing/entityPricing.ts
Labels: Approved, DC-Specific Pricing

#9568 feat: [M3-6969] - Add DC-specific pricing to Kubernetes HA
  packages/manager/.changeset/pr-9568-upcoming-features-1692399466892.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
  packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
  packages/manager/src/constants.ts
  packages/manager/src/env.d.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/HACheckbox.test.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/HACheckbox.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeClusterSpecs.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeClusterDialog.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.test.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/utilities/pricing/dynamicPricing.ts
Labels: UI, Approved, DC-Specific Pricing

#9573 hotfix: Timezone Form Styles and revert FromStrackScriptContent to a class component
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
Labels: Bug, UI, Approved, Hotfix

#9580 Release v1.100.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
Labels: Release, Approved

#9578 fix: `create-volume.spec.ts` and `dynamicPricing.test.ts`
  packages/manager/.changeset/pr-9578-upcoming-features-1692717836737.md
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/src/utilities/pricing/dynamicPricing.test.ts
  packages/manager/src/utilities/pricing/dynamicVolumePrice.test.ts
Labels: e2e, Approved, DC-Specific Pricing

#9587 fix: [M3-7050] re-instate copy tooltip hover state in Linode Summary
  packages/manager/.changeset/pr-9587-fixed-1692802396223.md
  packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
Labels: Approved

#9572 feat: [M3-6969] - Add DC Specific Pricing Notices and Docs Links
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-9572-upcoming-features-1692649682757.md
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/src/components/DynamicPriceNotice.tsx
  packages/manager/src/components/EntityHeader/EntityHeader.stories.tsx
  packages/manager/src/components/SelectRegionPanel/RegionHelperText.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/factories/linodes.ts
  packages/manager/src/factories/types.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/utilities/pricing/linodes.test.tsx
  packages/manager/src/utilities/pricing/linodes.ts
Labels: Approved, DC-Specific Pricing

#9537 feat: [M3-6757] - Create VPC page
  packages/api-v4/.changeset/pr-9537-upcoming-features-1692216355268.md
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-9537-upcoming-features-1692202603416.md
  packages/manager/src/factories/grants.ts
  packages/manager/src/features/VPC/VPCCreate/MultipleSubnetInput.test.tsx
  packages/manager/src/features/VPC/VPCCreate/MultipleSubnetInput.tsx
  packages/manager/src/features/VPC/VPCCreate/SubnetNode.test.tsx
  packages/manager/src/features/VPC/VPCCreate/SubnetNode.tsx
  packages/manager/src/features/VPC/VPCCreate/VPCCreate.styles.ts
  packages/manager/src/features/VPC/VPCCreate/VPCCreate.test.tsx
  packages/manager/src/features/VPC/VPCCreate/VPCCreate.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/utilities/subnets.test.ts
  packages/manager/src/utilities/subnets.ts
  packages/validation/.changeset/pr-9537-changed-1692640036055.md
  packages/validation/src/vpcs.schema.ts
Labels: VPC

#9563 fix: [M3-7040] - Longview crashing the app with a negative number of CPU cores
  packages/manager/.changeset/pr-9563-fixed-1692305293304.md
  packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx
Labels: Bug, Approved

#9576 feat: [M3-7025] - AGLB Details - Certificates Tab
  packages/api-v4/src/aglb/index.ts
  packages/api-v4/src/types.ts
  packages/manager/.changeset/pr-9576-upcoming-features-1692664450264.md
  packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerCertificates.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerDetail.tsx
  packages/manager/src/features/Support/SupportTickets/ticketUtils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/aglb/certificates.ts
Labels: Approved, AGLB

#9577 feat: [M3-7026] - AGLB Details - Service Targets Tab
  packages/manager/.changeset/pr-9577-upcoming-features-1692672144232.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerDetail.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerServiceTargets.tsx
  packages/manager/src/features/LoadBalancers/Routes/RouteCreate/RouteCreate.tsx
  packages/manager/src/features/LoadBalancers/Routes/RouteLanding/RouteLanding.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetCreate/ServiceTargetCreate.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetActionMenu.test.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetActionMenu.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetLanding.test.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetLanding.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetRow.tsx
  packages/manager/src/queries/aglb/serviceTargets.ts
Labels: Approved, AGLB

#9586 feat: [M3-6965] - Update api-v4 and mocks for DC-specific pricing
  packages/api-v4/.changeset/pr-9586-upcoming-features-1692798602248.md
  packages/api-v4/src/account/account.ts
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-9586-upcoming-features-1692798648869.md
  packages/manager/src/components/EntityHeader/EntityHeader.stories.tsx
  packages/manager/src/factories/account.ts
  packages/manager/src/factories/billing.ts
  packages/manager/src/factories/linodes.ts
  packages/manager/src/factories/types.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/accountTransfer.ts
Labels: @linode/api-v4, Approved, DC-Specific Pricing

#9555 refactor: [M3-6285] - SRC > Features > ToastNotifications
  packages/manager/.changeset/pr-9555-tech-stories-1692282778803.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
  packages/manager/src/features/ToastNotifications/index.ts
Labels: Approved, Project: MUI v5 Migration

#9453 feat: [M3-6727] – Include firewall field as part of Linode Create object
  packages/api-v4/.changeset/pr-9453-changed-1691514440186.md
  packages/api-v4/src/linodes/types.ts
  packages/manager/src/utilities/subnets.ts
  packages/validation/.changeset/pr-9453-changed-1691514405209.md
  packages/validation/src/linodes.schema.ts
  packages/validation/src/vpcs.schema.ts
Labels: @linode/api-v4, @linode/validation, Approved, VPC

#9565 refactor: [M3-6264] - MUI v5 Migration - SRC > Features > Events
  packages/manager/.changeset/pr-9565-tech-stories-1692368201746.md
  packages/manager/src/features/Events/EventRow.styles.ts
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/Events/EventsLanding.styles.ts
  packages/manager/src/features/Events/EventsLanding.tsx
Labels: Approved, Project: MUI v5 Migration

#9590 feat: [M3 7015] - Create nodebalancer tab in firewalls landing
  packages/api-v4/src/firewalls/types.ts
  packages/manager/.changeset/pr-9590-upcoming-features-1692899572064.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
Labels: Approved, Nodebalancer Firewall UX

#9544 feat: [M3-6690] - Beta details
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-9544-added-1692992268848.md
  packages/manager/cypress/e2e/core/account/betas.spec.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/factories/betas.ts
  packages/manager/src/features/Betas/BetaDetails.test.tsx
  packages/manager/src/features/Betas/BetaDetails.tsx
  packages/manager/src/features/Betas/BetaDetailsList.test.tsx
  packages/manager/src/features/Betas/BetaDetailsList.tsx
  packages/manager/src/features/Betas/BetaSignup.tsx
  packages/manager/src/features/Betas/BetasLanding.test.tsx
  packages/manager/src/features/Betas/BetasLanding.tsx
  packages/manager/src/features/Betas/index.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/accountBetas.ts
  packages/manager/src/utilities/betaUtils.ts
Labels: Approved

#9520 feat: [M3-7058] - Add AGLB Create Page - Stepper component
  packages/manager/.changeset/pr-9520-upcoming-features-1692378386106.md
  packages/manager/src/components/VerticalLinearStepper/VerticalLinearStepper.stories.tsx
  packages/manager/src/components/VerticalLinearStepper/VerticalLinearStepper.styles.ts
  packages/manager/src/components/VerticalLinearStepper/VerticalLinearStepper.test.tsx
  packages/manager/src/components/VerticalLinearStepper/VerticalLinearStepper.tsx
Labels: Approved, AGLB

#9570 feat: [M3-6968] Add DC specific pricing info to migration modal
  packages/manager/.changeset/pr-9570-changed-1692743440177.md
  packages/manager/src/components/DisplayPrice/DisplayPrice.tsx
  packages/manager/src/factories/linodes.ts
  packages/manager/src/factories/types.ts
  packages/manager/src/features/Linodes/MigrateLinode/CautionNotice.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.styles.ts
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.test.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrationPricing.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/utilities/pricing/linodes.ts
Labels: Approved, DC-Specific Pricing

#9596 feat: [OCA-1189] Sept marketplace release
  packages/manager/.changeset/pr-9596-added-1693253466611.md
  packages/manager/public/assets/nomadclientsocc.svg
  packages/manager/public/assets/nomadocc.svg
  packages/manager/public/assets/white/nomadclientsocc.svg
  packages/manager/public/assets/white/nomadocc.svg
  packages/manager/src/features/Linodes/LinodesCreate/SelectAppPanel.tsx
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Approved

#9530 feat: [M3-6945] – Support VPC and Subnet events
  packages/api-v4/.changeset/pr-9530-added-1692198648058.md
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-9530-added-1691618959800.md
  packages/manager/cypress/e2e/core/notificationsAndEvents/events.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-navigation.spec.ts
  packages/manager/src/GoTo.tsx
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/Events/constants.ts
  packages/manager/src/features/Events/eventMessageGenerator.ts
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
  packages/manager/src/features/VPC/VPCCreate/VPCCreate.tsx
  packages/manager/src/features/VPC/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCDeleteDialog.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCEmptyState.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPC/VPCLanding/VPCRow.tsx
  packages/manager/src/features/VPC/index.tsx
  packages/manager/src/utilities/getEventsActionLink.ts
Labels: Approved, VPC

#9588 feat: [M3-7035] - Add DC-specific pricing to Linode backups
  packages/manager/.changeset/pr-9588-upcoming-features-1693245885155.md
  packages/manager/src/cachedData/regions.json
  packages/manager/src/features/Backups/AutoEnroll.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Backups/BackupLinodeRow.test.tsx
  packages/manager/src/features/Backups/BackupLinodeRow.tsx
  packages/manager/src/features/Backups/utils.test.ts
  packages/manager/src/features/Backups/utils.ts
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/types.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/utilities/pricing/backups.ts
  packages/manager/src/utilities/pricing/linodes.test.tsx
Labels: Approved, DC-Specific Pricing

#9604 chore: Rename `src/features/VPC` to `src/features/VPCs`
  packages/manager/.changeset/pr-9604-changed-1693336292797.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/VPCs/VPCCreate/MultipleSubnetInput.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/MultipleSubnetInput.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.styles.ts
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.styles.ts
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCDeleteDialog.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEmptyState.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEmptyStateData.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCRow.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCRow.tsx
  packages/manager/src/features/VPCs/index.tsx
  packages/manager/src/features/VPCs/utils.test.ts
  packages/manager/src/features/VPCs/utils.ts
Labels: Approved, VPC

#9592 fix: [M3-7055] - Metadata Image select dropdown fixes
  packages/manager/.changeset/pr-9592-fixed-1692907566241.md
  packages/manager/src/assets/icons/cloud-init-incompatible.svg
  packages/manager/src/components/ImageSelect/ImageOption.tsx
Labels: Bug, Project: Metadata, Approved

#9605 fix: Fix VPC landing page test import
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
Labels: Approved, Missing Changeset

#9602 fix: [M3-7062] - Hide User Data accordion in Linode Rebuild dialog for unsupported regions
  packages/manager/.changeset/pr-9602-fixed-1693332727991.md
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/utilities.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/LinodeRebuildDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
Labels: Bug, Project: Metadata, Approved

#9524 fix: [M3-6999] - Remove Docker Compose hardcoded container names
  docker-compose.yml
Labels: Approved, Missing Changeset

#9603 chore: Update Material UI and Emotion
  packages/manager/.changeset/pr-9603-tech-stories-1693333265033.md
  packages/manager/package.json
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/components/Chip.tsx
  packages/manager/src/components/Tag/Tag.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/foundations/themes/light.ts
  yarn.lock
Labels: Dependencies, Approved

#9609 hotfix: Disable Configs API call when VPC is off
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
Labels: Approved, Hotfix

#9611 Release v1.100.2 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
Labels: Release, Approved

#9613 Release v1.100.2 - `develop` ⬅️ `master`
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
Labels: Approved, Master → Develop

#9615 fix: Kube checkout bar copy
  packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
  packages/manager/src/utilities/pricing/constants.ts
Labels: Approved
