Repository linode/manager, pull requests merged in 2023-05, with the labels that each got.

#9054 test: [M3-6052] - Add LKE cluster update and delete integration tests
  .gitignore
  CHANGELOG.md
  packages/manager/cypress/e2e/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/kubernetes/lke-delete.spec.ts
  packages/manager/cypress/e2e/kubernetes/lke-landing-page.spec.ts
  packages/manager/cypress/e2e/kubernetes/lke-update.spec.ts
  packages/manager/cypress/support/intercepts/lke.ts
  packages/manager/cypress/support/util/downloads.ts
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/RecycleNodeDialog.tsx
Labels: e2e, Approved

#9072 `develop` ⬅️ `master` for v1.92.0
  CHANGELOG.md
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/manager/package.json
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Release

#9069 fix: [M3-6022] - Add compression to logo when rendering in JPG format during invoice PDF generation
  CHANGELOG.md
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
Labels: Approved, Ready for Review

#9067 fix: [M3-6540] - Surface general errors in the Object Storage Bucket Create Drawer
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/objectStorage.ts
  packages/manager/src/utilities/testHelpers.tsx
Labels: Bug

#9065 feat: [M3-6464] – Add resource links to empty Volumes landing page
  CHANGELOG.md
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/features/Volumes/VolumesLandingEmptyState.styles.ts
  packages/manager/src/features/Volumes/VolumesLandingEmptyState.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinksSubSection.tsx
Labels: Approved, Update empty landing states

#9066 feat: [M3-6520] - Add new flag to deliver DC availability notice for premium plans
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/linodes/LinodesCreate/PremiumPlansAvailabilityNotice.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
Labels: Approved

#9081 fix: [M3-6558] - Remove 'MongoDB' from ClusterControl description in Marketplace
  CHANGELOG.md
  packages/manager/src/features/OneClickApps/FakeSpec.ts
Labels: Ready for Review

#9073 fix: [M3-5088] - Allow simple search for IPv6 addresses
  CHANGELOG.md
  packages/manager/src/features/Search/refinedSearch.test.ts
  packages/manager/src/features/Search/refinedSearch.ts
Labels: Add'tl Approval Needed

#9076 fix: [M3-6509] - Enable Cypress's experimental memory management config
  packages/manager/cypress.config.ts
Labels: Approved, Ready for Review

#9080 refactor: [M3-6222] - Refactor Images E2E Test Intercepts
  packages/manager/cypress/e2e/images/create-linode-from-image.spec.ts
  packages/manager/cypress/e2e/images/machine-image-upload.spec.ts
  packages/manager/cypress/e2e/images/smoke-create-image.spec.ts
  packages/manager/cypress/support/intercepts/images.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: e2e, Approved

#9061 chore: [POC] - Organize files under `src/foundations/`
  docs/development-guide/01-repository-structure.md
  docs/development-guide/13-coding-standards.md
  packages/manager/src/LinodeThemeWrapper.tsx
  packages/manager/src/components/ColorPalette/ColorPalette.stories.mdx
  packages/manager/src/components/LineGraph/MetricsDisplay.test.tsx
  packages/manager/src/components/core/Grid.tsx
  packages/manager/src/foundations/breakpoints/index.ts
  packages/manager/src/foundations/fonts/index.ts
  packages/manager/src/foundations/themes/dark.ts
  packages/manager/src/foundations/themes/index.ts
  packages/manager/src/foundations/themes/light.ts
  packages/manager/src/utilities/theme.ts
Labels: Proof of Concept, Design Tokens

#9038 chore: Upgrade Cypress to v12.11
  packages/manager/Dockerfile
  packages/manager/package.json
  packages/manager/src/cachedData/kernels.json
  packages/manager/src/cachedData/regions.json
  packages/manager/src/cachedData/typesLegacy.json
  yarn.lock
Labels: e2e, Approved

#9085 fix: Linode Details Access Table UI
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
Labels: Bug, UI, Approved

#9079 refactor: [M3-6492, M3-6315] - React Query - Linode Detail - Backups
  packages/api-v4/src/linodes/types.ts
  packages/manager/cypress/e2e/linodes/backup-linode.spec.ts
  packages/manager/src/App.tsx
  packages/manager/src/factories/linodes.ts
  packages/manager/src/features/linodes/LinodesCreate/SelectBackupPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/CancelBackupsDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/CaptureSnapshot.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/CaptureSnapshot.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/CaptureSnapshotConfirmationDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/DestructiveSnapshotDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackupActionMenu.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackups.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/ScheduleSettings.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/ScheduleSettings.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/index.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/manager/src/queries/linodes/backups.ts
  packages/manager/src/queries/linodes/linodes.ts
Labels: React Query, Approved

#9083 change: [M3-6483] – Update OCAs highlighted on empty state Linodes landing page
  CHANGELOG.md
  packages/manager/src/features/linodes/LinodesLanding/AppsSection.tsx
Labels: Approved, Update empty landing states

#9088 change: [M3-6465] - Move linodes, k8s & dbs empty landing pages resources to HOC
  packages/manager/src/components/EmptyLandingPageResources/ResourcesLinkIcon.tsx
  packages/manager/src/components/EmptyLandingPageResources/ResourcesLinks.tsx
  packages/manager/src/components/EmptyLandingPageResources/ResourcesLinksSection.tsx
  packages/manager/src/components/EmptyLandingPageResources/ResourcesLinksSubSection.tsx
  packages/manager/src/components/EmptyLandingPageResources/ResourcesSection.tsx
  packages/manager/src/components/Placeholder/Placeholder.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingEmptyStateData.ts
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLandingEmptyState.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLandingEmptyStateData.ts
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLandingEmptyState.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLandingEmptyStateData.ts
Labels: Approved, Update empty landing states

#9084 refactor: [M3-6326] - MUI v5 - Components > DownloadCSV
  CHANGELOG.md
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/DownloadCSV/DownloadCSV.tsx
  packages/manager/src/components/DownloadCSV/index.ts
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLandingCSVDownload.tsx
  packages/manager/src/hooks/useFormattedDate.ts
Labels: Approved, Project: MUI v5 Migration

#9096 refactor: [M3-6390] - MUI v5 - Components/ShowMoreExpansion
  packages/manager/src/components/ShowMoreExpansion/ShowMoreExpansion.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
Labels: Add'tl Approval Needed, Approved, Project: MUI v5 Migration

#9100 refactor: [M3-6301] – `MUI v5 - Components > CheckoutSummary`
  CHANGELOG.md
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
  packages/manager/src/components/CheckoutSummary/SummaryItem.tsx
Labels: Approved, Project: MUI v5 Migration

#9090 refactor: [M3-6376] – `MUI v5 - Components > PrimaryNav`
  CHANGELOG.md
  packages/manager/src/components/PrimaryNav/AdditionalMenuItems.tsx
  packages/manager/src/components/PrimaryNav/NavItem.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/PrimaryNav/index.ts
Labels: Approved, Project: MUI v5 Migration

#9091 feat: [M3-6470] - Add resource links to StackScripts empty state landing state
  CHANGELOG.md
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.styles.ts
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptsEmptyLandingPage.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptsEmptyResourcesData.ts
Labels: Approved, Update empty landing states

#9087 change: [M3-6057] - Avoid saving/uploading Cypress recordings for successful specs in CI
  packages/manager/cypress.config.ts
Labels: e2e, Approved, Ready for Review

#9097 refactor: M3-6489: React Query Linode Details - Network Tab
  CHANGELOG.md
  packages/api-v4/src/linodes/ips.ts
  packages/api-v4/src/networking/networking.ts
  packages/api-v4/src/types.ts
  packages/manager/src/__data__/ipResponse.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/CreateIPv4Drawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/CreateIPv6Drawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPActions.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPConfirm.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteRangeDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/EditIPRDNSDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/EditRDNSDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/EditRangeRDNSDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.test.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransfer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/ViewIPDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/ViewRDNSDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/ViewRangeDrawer.tsx
  packages/manager/src/queries/linodes/networking.ts
  packages/manager/src/queries/networking.ts
Labels: React Query, Approved

#9099 refactor: [M3-6488] - React Query for Linode Details - General Details
  CHANGELOG.md
  packages/manager/cypress/e2e/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/src/features/linodes/CloneLanding/CloneLanding.tsx
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.container.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/index.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/manager/src/features/linodes/LinodesDetail/MutateDrawer/MutateDrawer.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/queries/linodes/actions.ts
Labels: React Query, Approved

#9110 fix: [M3-6575] – Restore `<ProductInformationBanner />` in DatabaseEmptyState.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
Labels: Project: DBaaS

#9108 chore: [M3-6574] - Send Adobe Analytics Page Views
  CHANGELOG.md
  packages/manager/src/App.tsx
Labels: Add'tl Approval Needed, Ready for Review

#9109 refactor: [M3-6334] - MUI v5 - Components > EntityHeader
  CHANGELOG.md
  packages/manager/src/components/EntityHeader/EntityHeader.stories.tsx
  packages/manager/src/components/EntityHeader/EntityHeader.tsx
  packages/manager/src/components/EntityHeader/index.tsx
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
Labels: Ready for Review, Project: MUI v5 Migration

#9118 fix: Redirect to Linodes Landing when delete happens on the Linode details page
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesLanding/DeleteLinodeDialog.tsx
Labels: Bug

#9111 test: [M3-6550] - Add Domain delete, import a zone, and download zone file Cypress tests
  packages/manager/cypress/e2e/domains/smoke-delete-domain.spec.ts
  packages/manager/cypress/e2e/domains/smoke-domain-download-zone-file.spec.ts
  packages/manager/cypress/e2e/domains/smoke-domain-import-a-zone.spec.ts
  packages/manager/cypress/support/helpers.ts
  packages/manager/cypress/support/intercepts/domains.ts
  packages/manager/src/factories/domain.ts
Labels: e2e, Approved

#9107 refactor: [M3-6420] – `MUI v5 - Components > TransferDisplay`
  CHANGELOG.md
  packages/manager/src/components/TransferDisplay/TransferDisplay.tsx
  packages/manager/src/components/TransferDisplay/index.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
Labels: Approved, Project: MUI v5 Migration

#9133 hotfix: Linodes Details - Backups - Initialize linode before referencing
  CHANGELOG.md
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
Labels: Do Not Merge, Bug

#9113 refactor: [M3-6246] - SRC > Features > CancelLanding
  packages/manager/src/features/CancelLanding/CancelLanding.tsx
  packages/manager/src/features/CancelLanding/index.ts
  packages/manager/src/index.tsx
Labels: Ready for Review, Project: MUI v5 Migration

#9131 refactor: [M3-6374, M3-6344] - MUI v5 Migration - `Components > Placeholder & H1Header`
  packages/manager/.changeset/pr-9131-tech-stories-1684293772869.md
  packages/manager/.changeset/pr-9131-tech-stories-1684293796866.md
  packages/manager/src/components/Breadcrumb/FinalCrumb.tsx
  packages/manager/src/components/EditableText/EditableText.tsx
  packages/manager/src/components/EmptyLandingPageResources/ResourcesSection.tsx
  packages/manager/src/components/H1Header/H1Header.tsx
  packages/manager/src/components/H1Header/index.tsx
  packages/manager/src/components/NotFound.tsx
  packages/manager/src/components/Placeholder/.Placeholder.stories.mdx
  packages/manager/src/components/Placeholder/Placeholder.tsx
  packages/manager/src/components/Placeholder/index.ts
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/features/CancelLanding/CancelLanding.tsx
  packages/manager/src/features/Events/EventsLanding.tsx
  packages/manager/src/features/Help/Panels/SearchPanel.tsx
  packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.test.tsx
  packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx
  packages/manager/src/styles/keyframes.ts
Labels: Add'tl Approval Needed, Ready for Review, Project: MUI v5 Migration

#9130 fix: [M3-6581] - Fix Cloud Manager Maintenance Mode
  packages/manager/.changeset/pr-9130-fixed-1684419720777.md
  packages/manager/src/IdentifyUser.tsx
Labels: Bug, Approved

#9127 fix: [M3-5783] Firewall Rules - Improve form requirements and feedback
  packages/manager/.changeset/pr-9127-fixed-1684265961864.md
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.types.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.utils.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleForm.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
Labels: Approved

#9143 hotfix: [M3-6594] - Enable linode action menu "reboot" on mobile
  CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
Labels: Bug, Hotfix

#9144 Release v1.93.2 - staging → master
  CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
Labels: Release

#9146 `develop` ⬅️ `master` for v1.93.1 and v1.93.2 release
  CHANGELOG.md
  packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/package.json
  packages/manager/src/components/EntityTable/EntityTableHeader.tsx
  packages/manager/src/components/EntityTable/types.ts
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
  packages/manager/src/features/linodes/LinodesLanding/DeleteLinodeDialog.tsx
  packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/linodes/LinodesLanding/ListView.tsx
  packages/manager/src/features/linodes/LinodesLanding/SortableTableHead.tsx
  packages/manager/src/features/linodes/LinodesLanding/TableWrapper.tsx
  packages/manager/src/features/linodes/PowerActionsDialogOrDrawer.tsx
  packages/manager/src/features/linodes/index.tsx
  packages/manager/src/features/linodes/transitions.ts
Labels: Ready for Review

#9150 hotfix: [M3-6598] - Limited cannot create NodeBalancer
  CHANGELOG.md
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
Labels: Bug, Hotfix

#9151 hotfix: Linode Multi Select not working with large filters
  CHANGELOG.md
  packages/manager/src/components/LinodeMultiSelect/LinodeMultiSelect.tsx
Labels: Bug, Hotfix

#9140 fix: [M3-6576]: Fix Bucket Access Component Reloading API Data too often
  CHANGELOG.md
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketAccess.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
Labels: Bug, Approved, Hotfix

#9149 Release v1.93.3 - staging → master
  CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/LinodeMultiSelect/LinodeMultiSelect.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketAccess.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
Labels: Release

#9129 refactor: [M3-6329] - MUI v5 Migration - `Components > EditableEntityLabel`
  packages/manager/.changeset/pr-9129-tech-stories-1684288822656.md
  packages/manager/src/components/EditableEntityLabel/EditableEntityLabel.tsx
  packages/manager/src/components/EditableEntityLabel/index.tsx
  packages/manager/src/components/EntityIcon/EntityIcon.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientInstructions.tsx
Labels: Approved, Project: MUI v5 Migration

#9145 change: [OCA-1137] - deprecate unifi marketplace app
  packages/manager/.changeset/pr-9145-removed-1684770464653.md
  packages/manager/public/assets/unifi.svg
  packages/manager/public/assets/white/unifi.svg
  packages/manager/src/features/OneClickApps/FakeSpec.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Marketplace, Approved

#9101 refactor: [M3-6563] - Create util function to filter plan selecting t…
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
  packages/manager/src/utilities/filterPlanSelectionsByType.ts
  packages/manager/src/utilities/filterPlanSelectionsByTypes.test.ts
Labels: Approved, Refactor SelectPlanPanel

#9089 ci: [M3-6566] - Update container environment variables for Cypress 12.3 changes
  docker-compose.yml
Labels: e2e, Approved

#9155 chore: Remove unused Linode components
  packages/manager/src/features/linodes/CloneLanding/CloneLanding.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodePowerControl/index.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailsBreadcrumb.tsx
  packages/manager/src/features/linodes/LinodesDetail/initLinode.ts
  packages/manager/src/features/linodes/LinodesDetail/initLinodeConfigs.ts
  packages/manager/src/features/linodes/LinodesDetail/initLinodeDisks.ts
Labels: Approved, Clean Up

#9124 refactor: [M3-6421 & M3-6422] – MUI v5 Migration - `Components > TypeToConfirm` & `Components > TypeToConfirmDialog`
  packages/manager/.changeset/pr-9124-tech-stories-1684339298469.md
  packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
  packages/manager/src/components/TypeToConfirm/TypeToConfirm.test.tsx
  packages/manager/src/components/TypeToConfirm/TypeToConfirm.tsx
  packages/manager/src/components/TypeToConfirm/index.ts
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.test.tsx
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
  packages/manager/src/components/TypeToConfirmDialog/index.ts
  packages/manager/src/features/Account/CloseAccountDialog.tsx
  packages/manager/src/features/Account/EnableObjectStorage.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDeleteDialog.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/Volumes/DestructiveVolumeDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx
  packages/manager/src/features/linodes/LinodesLanding/DeleteLinodeDialog.tsx
Labels: Project: MUI v5 Migration

#9154 refactor: [M3-6423] - Remove unused ViewAllLink and ActivitySummary
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummary.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummary.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummaryContent.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummaryContent.tsx
Labels: Ready for Review

#9141 change: [M3-5963] - Update Marketplace analytics search event
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
  packages/manager/src/utilities/ga.ts
Labels: Add'tl Approval Needed

#9125 refactor: [M3-6335] - MUI v5 Migration - `Components > EntityIcon`
  EntityIcon
  packages/manager/.changeset/pr-9125-tech-stories-1684260472991.md
  packages/manager/src/components/EditableEntityLabel/EditableEntityLabel.tsx
  packages/manager/src/components/EntityIcon/EntityIcon.stories.mdx
  packages/manager/src/components/EntityIcon/EntityIcon.stories.tsx
  packages/manager/src/components/EntityIcon/EntityIcon.tsx
  packages/manager/src/components/EntityIcon/EntityIconStory.tsx
  packages/manager/src/components/EntityIcon/index.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useEventInfo.ts
  packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.tsx
Labels: Approved, Project: MUI v5 Migration

#9137 Chore: [M3-6511] Changeset BOT
  .github/workflows/changeset-bot.yml
  packages/manager/.changeset/pr-9137-added-1684448927783.md
  packages/manager/package.json
  packages/manager/scripts/changelog/action.yml
  packages/manager/scripts/changelog/changeset-bot.mjs
  packages/manager/scripts/changelog/compiled/README.md
  packages/manager/scripts/changelog/compiled/index.mjs
  packages/manager/scripts/changelog/utils/constants.mjs
  packages/manager/scripts/changelog/utils/getPullRequestId.mjs
  yarn.lock
Labels: Add'tl Approval Needed

#9121 refactor: [M3-6493] - React Query - Linode Detail - Settings Tab
  packages/manager/.changeset/pr-9121-tech-stories-1684873551953.md
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettings.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/manager/src/queries/linodes/disks.ts
  packages/manager/src/queries/linodes/linodes.ts
Labels: React Query, Approved

#9120 fix: [M3-5768] - Fix broken Jest tests for PaymentInformation
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.test.tsx
Labels: Needs More Approvals

#9162 Refactor: [M3-6277] Notification center MUI Migration
  packages/manager/src/components/Button/LinkStyledButton.ts
  packages/manager/src/components/GravatarByUsername.tsx
  packages/manager/src/features/NotificationCenter/Events.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.styles.ts
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
  packages/manager/src/features/NotificationCenter/NotificationSection.tsx
  packages/manager/src/features/NotificationCenter/Notifications.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
Labels: Project: MUI v5 Migration

#9142 refactor: [M3-6073] - Move dismissibleButton to DismissibleBanner component
  packages/manager/.changeset/pr-9142-tech-stories-1685027048549.md
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/features/GlobalNotifications/ComplianceBanner.tsx
  packages/manager/src/features/GlobalNotifications/TaxCollectionBanner.tsx
  packages/manager/src/features/Help/StatusBanners.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeKubernetesVersionBanner.tsx
Labels: Ready for Review

#9173 refactor: [M3-6388] - MUI v5 - `Components > SelectRegionPanel`
  packages/manager/.changeset/pr-9173-tech-stories-1684963143824.md
  packages/manager/src/components/SelectRegionPanel/RegionHelperText.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/components/SelectRegionPanel/index.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
Labels: Approved, Ready for Review, Project: MUI v5 Migration

#9172 refactor: [M3-6375] - MUI v5 - `Components > PreferenceToggle`
  packages/manager/.changeset/pr-9172-tech-stories-1684955729823.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PreferenceToggle/PreferenceToggle.tsx
  packages/manager/src/components/PreferenceToggle/index.ts
  packages/manager/src/features/Backups/BackupsCTA.tsx
  packages/manager/src/features/Profile/Settings/Settings.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
Labels: Approved, Ready for Review, Project: MUI v5 Migration

#9156 chore: Resolve `yaml` dependabot alert `CVE-2023-2251`
  package.json
  packages/api-v4/package.json
  packages/manager/.changeset/pr-9156-tech-stories-1684852664331.md
  packages/manager/package.json
  packages/validation/package.json
  yarn.lock
Labels: Dependencies, Approved

#9086 test: Increase machine image upload timeout from 2 minutes to 4 minutes
  packages/manager/cypress/e2e/images/create-linode-from-image.spec.ts
  packages/manager/cypress/e2e/images/machine-image-upload.spec.ts
  packages/manager/cypress/e2e/images/smoke-create-image.spec.ts
  packages/manager/cypress/support/intercepts/images.ts
Labels: e2e, Approved

#9177 refactor: [M3-6355] - MUI v5 -`Components > LinearProgress`
  packages/manager/.changeset/pr-9177-tech-stories-1685109915585.md
  packages/manager/.storybook/main.ts
  packages/manager/src/components/BarPercent/BarPercent.tsx
  packages/manager/src/components/LinearProgress.stories.tsx
  packages/manager/src/components/LinearProgress.tsx
  packages/manager/src/components/LinearProgress/LinearProgress.stories.mdx
  packages/manager/src/components/LinearProgress/LinearProgress.tsx
  packages/manager/src/components/LinearProgress/index.ts
  packages/manager/src/components/core/LinearProgress.ts
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.tsx
  packages/manager/src/features/Support/AttachFileListItem.tsx
Labels: Storybook, Approved, Project: MUI v5 Migration

#9159 refactor: [M3-6409 & 6410] – MUI v5 - `Components > TabLink` & `Components > TabLinkList`
  packages/manager/.changeset/pr-9159-changed-1684947497930.md
  packages/manager/src/components/Dialog/Dialog.tsx
  packages/manager/src/components/Drawer/Drawer.tsx
  packages/manager/src/components/NavTabs/NavTabs.tsx
  packages/manager/src/components/TabLink/TabLink.tsx
  packages/manager/src/components/TabLink/index.ts
  packages/manager/src/components/TabLinkList/TabLinkList.tsx
  packages/manager/src/components/TabLinkList/index.ts
  packages/manager/src/components/Tabs.stories.mdx
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Lish/Lish.tsx
  packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/Users/UserDetail.tsx
  packages/manager/src/features/linodes/CloneLanding/CloneLanding.tsx
  packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/manager/src/utilities/stringUtils.ts
Labels: Approved, Project: MUI v5 Migration

#9171 feat: [M3-6077] - Add Maintenance Mode Environment Variable and Clean Up `<MaintenanceScreen />`
  packages/manager/.changeset/pr-9171-tech-stories-1684951964927.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/MaintenanceScreen.tsx
  packages/manager/src/constants.ts
  packages/manager/src/env.d.ts
Labels: Approved

#9178 chore: update component structure docs
  docs/development-guide/02-component-structure.md
Labels: Approved, Documentation

#9147 refactor: [M3-6585] - Allow Cypress region selection to be overridden
  docs/development-guide/08-testing.md
  packages/manager/cypress.config.ts
  packages/manager/cypress/e2e/account/service-transfer.spec.ts
  packages/manager/cypress/e2e/databases/create-database.spec.ts
  packages/manager/cypress/e2e/databases/delete-database.spec.ts
  packages/manager/cypress/e2e/databases/update-database.spec.ts
  packages/manager/cypress/e2e/firewalls/create-firewall.spec.ts
  packages/manager/cypress/e2e/firewalls/delete-firewall.spec.ts
  packages/manager/cypress/e2e/firewalls/update-firewall.spec.ts
  packages/manager/cypress/e2e/images/create-linode-from-image.spec.ts
  packages/manager/cypress/e2e/images/machine-image-upload.spec.ts
  packages/manager/cypress/e2e/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/kubernetes/lke-landing-page.spec.ts
  packages/manager/cypress/e2e/kubernetes/smoke-lke-create.spec.ts
  packages/manager/cypress/e2e/linodes/create-linode.spec.ts
  packages/manager/cypress/e2e/linodes/rescue-linode.spec.ts
  packages/manager/cypress/e2e/linodes/smoke-delete-linode.spec.ts
  packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/cypress/e2e/nodebalancers/smoke-create-nodebal.spec.ts
  packages/manager/cypress/e2e/stackscripts/create-stackscripts.spec.ts
  packages/manager/cypress/e2e/volumes/attach-volume.spec.ts
  packages/manager/cypress/e2e/volumes/clone-volume.spec.ts
  packages/manager/cypress/e2e/volumes/create-volume.spec.ts
  packages/manager/cypress/e2e/volumes/delete-volume.spec.ts
  packages/manager/cypress/e2e/volumes/resize-volume.spec.ts
  packages/manager/cypress/e2e/volumes/update-volume.spec.ts
  packages/manager/cypress/support/api/linodes.ts
  packages/manager/cypress/support/api/nodebalancers.ts
  packages/manager/cypress/support/constants/databases.ts
  packages/manager/cypress/support/constants/regions.ts
  packages/manager/cypress/support/ui/select.ts
  packages/manager/cypress/support/util/regions.ts
Labels: Approved, Ready for Review

#9188 fix: IP Sharing Query Invalidation
  packages/manager/src/queries/linodes/networking.ts
Labels: Bug

#9167 refactor: [M3-6623] - React Query - Object Storage - Bucket SSL/TLS
  packages/api-v4/src/object-storage/buckets.ts
  packages/manager/.changeset/pr-9167-tech-stories-1684946718170.md
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/objectStorage.ts
Labels: React Query, Object Storage

#9114 feat: [OCA-1135] - June 2023 Marketplace Release
  packages/manager/.changeset/pr-9114-added-1684262923966.md
  packages/manager/public/assets/appwrite.svg
  packages/manager/public/assets/illabuilder.svg
  packages/manager/public/assets/owncloud.svg
  packages/manager/public/assets/seatable.svg
  packages/manager/public/assets/white/appwrite.svg
  packages/manager/public/assets/white/illabuilder.svg
  packages/manager/public/assets/white/owncloud.svg
  packages/manager/public/assets/white/seatable.svg
  packages/manager/src/features/OneClickApps/FakeSpec.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
  packages/manager/src/features/linodes/LinodesCreate/SelectAppPanel.tsx
Labels: Marketplace

#9182 chore: Fix Storybook build and add build storybook in CI
  .github/workflows/ci.yml
  packages/manager/.storybook/preview.tsx
  packages/manager/src/components/EditableText/EditableText.stories.mdx
  packages/manager/src/components/Notice/Notice.stories.mdx
  packages/manager/src/components/PaginationControls/PaginationControls.stories.mdx
  packages/manager/src/components/PasswordInput/PasswordInput.stories.mdx
  packages/manager/src/components/Table/Table.stories.mdx
  packages/manager/src/components/TableRowEmptyState/TableRowEmptyState.stories.mdx
  packages/manager/src/components/TableRowError/TableRowError.stories.mdx
  packages/manager/src/components/TableRowLoading/TableRowLoading.stories.mdx
  packages/manager/src/components/TopMenu.stories.mdx
  packages/manager/src/components/UserMenu.stories.mdx
Labels: Storybook, Approved

#9181 chore: Storybook Upgrade and Enhancements
  packages/manager/.changeset/pr-9181-tech-stories-1685559954671.md
  packages/manager/.storybook/main.ts
  packages/manager/package.json
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  yarn.lock
Labels: Storybook, Approved
