Repository linode/manager, pull requests merged in 2023-10, with the labels that each got.

#9737 fix: CSV Download on Account Maintenance
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
Labels: Bug

#9703 feat: [M3-6755] - Unassign Linodes from Subnet
  packages/manager/.changeset/pr-9703-upcoming-features-1695751361212.md
  packages/manager/src/components/DownloadCSV/DownloadCSV.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/features/VPCs/constants.ts
  packages/manager/src/hooks/useUnassignLinode.ts
  packages/manager/src/utilities/subnets.ts
Labels: Ready for Review, VPC

#9735 feat: [M3-7109] - Add AGLB Delete Route Dialog
  packages/manager/.changeset/pr-9735-upcoming-features-1696265642529.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRoutes.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/DeleteRouteDialog.tsx
  packages/manager/src/queries/aglb/routes.ts
Labels: Approved, AGLB

#9739 fix: [M3-7208] Prevent forwarding the title prop to the markup
  packages/manager/.changeset/pr-9739-fixed-1696019997998.md
  packages/manager/src/components/Dialog/Dialog.tsx
Labels: Approved

#9743 fix: [M3-7226] - Make Reboot Linodes dismissible banner on VPC Details page unique
  packages/manager/.changeset/pr-9743-upcoming-features-1696347149626.md
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
Labels: Approved, VPC

#9732 feat: Statically Cache Marketplace Apps
  packages/manager/.changeset/pr-9732-added-1696340382725.md
  packages/manager/scripts/prebuild.mjs
  packages/manager/src/cachedData/kernels.json
  packages/manager/src/cachedData/marketplace.json
  packages/manager/src/containers/withMarketplaceApps.ts
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/queries/stackscripts.ts
Labels: Proof of Concept

#9719 refactor: Remove Cypress `cy.visitWithLogin()` account mocking, improve DBaaS mocks
  packages/manager/cypress/e2e/core/billing/billing-contact.spec.ts
  packages/manager/cypress/e2e/core/databases/create-database.spec.ts
  packages/manager/cypress/e2e/core/databases/delete-database.spec.ts
  packages/manager/cypress/e2e/core/databases/update-database.spec.ts
  packages/manager/cypress/support/constants/databases.ts
  packages/manager/cypress/support/intercepts/common.ts
  packages/manager/cypress/support/intercepts/databases.ts
  packages/manager/cypress/support/login.ts
  packages/manager/src/factories/account.ts
Labels: Wait to Merge

#9727 fix: [M3-7079] - Resolve "Incomplete string escape or encoding" alert in changeset.mjs
  scripts/changelog/changeset.mjs
Labels: Approved

#9752 chore: [M3-7231] - Migrate Filesystem TextField Select to Autocomplete
  packages/manager/.changeset/pr-9752-tech-stories-1696367849962.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateDiskDrawer.tsx
Labels: Approved

#9731 fix: [M3-7072] - Long drawer titles overlapping close icon
  packages/manager/.changeset/pr-9731-fixed-1695931370886.md
  packages/manager/src/components/Drawer.tsx
Labels: Bug

#9759 hotfix: DC-specific pricing -- monthly price decimals and invoice region column
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/billing/billing-invoices.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/src/factories/types.ts
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.test.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.test.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.test.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/manager/src/utilities/pricing/constants.ts
  packages/manager/src/utilities/pricing/dynamicPricing.test.ts
  packages/manager/src/utilities/pricing/dynamicPricing.ts
Labels: DC-Specific Pricing

#9729 feat: [M3-7152] - Add AGLB Route Add Rule Drawer
  packages/api-v4/src/aglb/routes.ts
  packages/api-v4/src/aglb/types.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts
  packages/manager/cypress/support/intercepts/load-balancers.ts
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/components/LinkButton.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/factories/aglb.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRoutes.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/AddRuleDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/MatchTypeInfo.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetSelect.tsx
  packages/manager/src/queries/aglb/routes.ts
  packages/manager/src/queries/aglb/serviceTargets.ts
  packages/manager/src/utilities/formikErrorUtils.test.ts
  packages/manager/src/utilities/formikErrorUtils.ts
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, AGLB

#9750 fix: [M3-7170] - Create VPC Region and Label Validation
  packages/manager/.changeset/pr-9750-fixed-1696365803471.md
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
Labels: Add'tl Approval Needed, VPC

#9761 Release v1.401.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/billing/billing-invoices.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/package.json
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.test.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/disabledRegions.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/factories/types.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.test.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.test.tsx
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.test.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/manager/src/utilities/pricing/constants.ts
  packages/manager/src/utilities/pricing/dynamicPricing.test.ts
  packages/manager/src/utilities/pricing/dynamicPricing.ts
Labels: Release

#9766 chore: [M3-7243] - Add 'Tests' to Changeset types
  docs/CONTRIBUTING.md
  packages/api-v4/.changeset/README.md
  packages/manager/.changeset/README.md
  packages/validation/.changeset/README.md
  scripts/changelog/utils/constants.mjs
Labels: Approved

#9723 feat: [M3-7160] - Add AGLB "Edit Certificate" drawer
  packages/api-v4/src/aglb/certificates.ts
  packages/api-v4/src/aglb/types.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-certificates.spec.ts
  packages/manager/src/factories/aglb.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/Certificates.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CreateCertificateDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/EditCertificateDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/EditCertificateDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/aglb/certificates.ts
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, AGLB

#9728 test: [M3-7123] - Cypress integration test for edit subnet flow
  packages/manager/.changeset/pr-9728-tests-1696600050126.md
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/cypress/support/intercepts/vpc.ts
Labels: Testing, Approved, VPC

#9755 fix: [M3-7204] - Notice fix & improvements
  packages/manager/.changeset/pr-9755-fixed-1696437359700.md
  packages/manager/src/components/Notice/Notice.stories.mdx
  packages/manager/src/components/Notice/Notice.stories.tsx
  packages/manager/src/components/Notice/Notice.styles.ts
  packages/manager/src/components/Notice/Notice.test.tsx
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/features/Linodes/LinodesCreate/PlansAvailabilityNotice.tsx
Labels: Approved

#9751 feat: [M3-7119] - Showcase VPC feedback
  packages/manager/.changeset/pr-9751-upcoming-features-1696367790874.md
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
  packages/manager/src/features/VPCs/VPCCreate/MultipleSubnetInput.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/MultipleSubnetInput.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.styles.ts
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
Labels: Approved, VPC

#9767 chore: Update `vite` and `sanitize-html` to update `postcss` for dependabot
  packages/manager/package.json
  yarn.lock
Labels: Dependencies

#9769 change: PR Template Updates
  docs/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#9736 feat: [M3-7185] - Add Drag and Drop support to the Rules Table
  packages/api-v4/src/aglb/types.ts
  packages/manager/.changeset/pr-9736-upcoming-features-1696008733328.md
  packages/manager/cypress/support/intercepts/load-balancers.ts
  packages/manager/src/factories/aglb.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRoutes.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.styles.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/aglb/routes.ts
  packages/manager/src/queries/aglb/serviceTargets.ts
Labels: Ready for Review, AGLB

#9780 fix: [M3-7259] - Fix inconsistent display of % in Linode Details MNTP legend
  packages/manager/.changeset/pr-9780-fixed-1696969213915.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferContent.tsx
Labels: Bug, Approved, DC-Specific Pricing

#9677 feat: [M3-7114] - Allow user to choose resize migration type when resizing Linode
  packages/api-v4/.changeset/pr-9677-added-1695693363239.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/linodes/actions.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-9677-added-1695693479114.md
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/src/components/ProductNotification/ProductNotification.tsx
  packages/manager/src/components/Tooltip.tsx
  packages/manager/src/components/TooltipIcon.stories.tsx
  packages/manager/src/components/TooltipIcon.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Events/constants.ts
  packages/manager/src/features/Events/eventMessageGenerator.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.utils.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResizeUnifiedMigrationPanel.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/Linodes/transitions.ts
  packages/manager/src/foundations/themes/dark.ts
  packages/manager/src/foundations/themes/light.ts
  packages/manager/src/queries/linodes/events.ts
  packages/manager/src/styles/keyframes.ts
  packages/manager/src/utilities/eventUtils.ts
Labels: Do Not Merge, @linode/api-v4, Ready for Review

#9774 refactor: [M3-6273] - MUI v5 Migration - SRC > Features > Lish
  packages/manager/.changeset/pr-9774-tech-stories-1696952177563.md
  packages/manager/src/assets/weblish/weblish.css
  packages/manager/src/components/CircleProgress/CircleProgress.tsx
  packages/manager/src/components/ReachTab.tsx
  packages/manager/src/features/Lish/Glish.tsx
  packages/manager/src/features/Lish/Lish.tsx
  packages/manager/src/features/Lish/Weblish.tsx
Labels: Ready for Review, Project: MUI v5 Migration

#9753 change: [OCA-1218] - Comment out CS:GO app pending update
  packages/manager/.changeset/pr-9753-changed-1696626338930.md
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Marketplace

#9725 fix: [M3-7038] - Add Firewall and Linode Configuration success toast notifications
  packages/manager/.changeset/pr-9725-fixed-1695824674392.md
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/DeleteConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
Labels: Ready for Review

#9776 fix: [M3-7256] - Added spacing for Hively external link
  packages/manager/.changeset/pr-9776-fixed-1696956017237.md
  packages/manager/src/features/Support/Hively.stories.tsx
  packages/manager/src/features/Support/Hively.tsx
Labels: Bug, Storybook, Approved

#9748 refactor: [M3-6287] - MUI v5 `Features > Users`
  packages/manager/.changeset/pr-9748-tech-stories-1696350216805.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/index.tsx
  packages/manager/src/features/Users/CreateUserDrawer.tsx
  packages/manager/src/features/Users/UserDeleteConfirmationDialog.tsx
  packages/manager/src/features/Users/UserDetail.tsx
  packages/manager/src/features/Users/UserPermissions.styles.ts
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Users/UserPermissionsEntitySection.styles.ts
  packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
  packages/manager/src/features/Users/UserProfile.styles.ts
  packages/manager/src/features/Users/UserProfile.tsx
  packages/manager/src/features/Users/UsersActionMenu.tsx
  packages/manager/src/features/Users/UsersLanding.tsx
  packages/manager/src/features/Users/index.tsx
Labels: Project: MUI v5 Migration

#9773 refactor: [M3-6282] MUI v5 Migration - `SRC > Features > StackScripts` pt1
  packages/manager/.changeset/pr-9773-tech-stories-1696952796931.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
  packages/manager/src/features/StackScripts/Partials/StackScriptTableHead.styles.ts
  packages/manager/src/features/StackScripts/Partials/StackScriptTableHead.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.styles.ts
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanelContent.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptsSection.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/StackScriptSelectionRow.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/index.ts
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.styles.ts
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.test.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/index.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.styles.ts
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/index.tsx
  packages/manager/src/features/StackScripts/StackScriptRowHelpers.tsx
  packages/manager/src/features/StackScripts/StackScripts.tsx
Labels: Approved, Project: MUI v5 Migration

#9756 refactor: [M3-7229] - Migrate UserDefinedSelect from a TextField Select to an Autocomplete
  packages/manager/.changeset/pr-9756-tech-stories-1696441475265.md
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedSelect.tsx
Labels: Approved

#9754 refactor: [M3-7230] - Migrate NodeBalancer Node Mode Select TextField to Autocomplete
  packages/manager/.changeset/pr-9754-tech-stories-1696437177982.md
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
Labels: Approved

#9788 change: [M3-7266] - Improve Linode Create Error Placement
  packages/manager/.changeset/pr-9788-changed-1697134985443.md
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/LabelAndTagsPanel/LabelAndTagsPanel.tsx
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx
Labels: Enhancement, UI, Approved

#9733 feat: [M3-7021] - Added Firewall panel to create NodeBalancer flow
  packages/api-v4/src/nodebalancers/types.ts
  packages/manager/.changeset/pr-9733-upcoming-features-1697041470658.md
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
Labels: Approved, Nodebalancer Firewall UX

#9790 change: [M3-7232] Rename isPropValid and update codebase & documentation
  docs/development-guide/02-component-structure.md
  packages/manager/.changeset/pr-9790-changed-1697132255387.md
  packages/manager/src/components/Autocomplete/Autocomplete.styles.tsx
  packages/manager/src/components/BarPercent/BarPercent.tsx
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/Chip.tsx
  packages/manager/src/components/CircleProgress/CircleProgress.tsx
  packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
  packages/manager/src/components/Dialog/Dialog.tsx
  packages/manager/src/components/Divider.tsx
  packages/manager/src/components/EntityDetail/EntityDetail.tsx
  packages/manager/src/components/FileUploader/FileUploader.styles.ts
  packages/manager/src/components/GaugePercent/GaugePercent.styles.ts
  packages/manager/src/components/LineGraph/LineGraph.styles.ts
  packages/manager/src/components/Paper.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
  packages/manager/src/components/StatusIcon/StatusIcon.tsx
  packages/manager/src/components/Table/Table.styles.ts
  packages/manager/src/components/TableRow/TableRow.styles.ts
  packages/manager/src/components/TagCell/AddTag.tsx
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/components/TooltipIcon.tsx
  packages/manager/src/components/VerticalLinearStepper/VerticalLinearStepper.styles.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.styles.ts
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.styles.ts
  packages/manager/src/features/Linodes/LinodesCreate/SelectBackupPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.styles.ts
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.styles.ts
  packages/manager/src/features/Linodes/LinodesLanding/IPAddress.styles.ts
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.styles.ts
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.styles.ts
  packages/manager/src/features/StackScripts/Partials/StackScriptTableHead.styles.ts
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.styles.ts
  packages/manager/src/features/components/PlansPanel/PlanContainer.styles.ts
  packages/manager/src/features/components/PlansPanel/PlansPanel.styles.ts
  packages/manager/src/utilities/isPropValid/index.ts
  packages/manager/src/utilities/omittedProps/index.ts
  packages/manager/src/utilities/omittedProps/omittedProps.test.tsx
  packages/manager/src/utilities/omittedProps/omittedProps.ts
Labels: Approved

#9709 feat: [M3-7121 & M3-7122] - Support VPC in Linode Add/Edit Config dialog
  packages/manager/.changeset/pr-9709-upcoming-features-1697141846298.md
  packages/manager/src/features/Linodes/LinodesCreate/AttachVLAN.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VLANAccordion.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/ConfigRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/InterfaceListItem.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/InterfaceListItem.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/queries/vpcs.ts
  packages/manager/src/utilities/formikErrorUtils.ts
  packages/validation/.changeset/pr-9709-changed-1697141933133.md
  packages/validation/src/linodes.schema.ts
Labels: Ready for Review, VPC

#9782 test: Fix Cypress LKE create test failures stemming from reset mocks
  packages/manager/.changeset/pr-9782-tests-1697147463647.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
Labels: Approved

#9777 test: Improve Cypress error messages when Linode API errors occur
  packages/manager/.changeset/pr-9777-tests-1696958372039.md
  packages/manager/cypress/support/setup/defer-command.ts
Labels: Approved

#9795 Release v1.105.0 - Update API, Manager, and Validation changelogs
  packages/api-v4/CHANGELOG.md
  packages/manager/CHANGELOG.md
  packages/validation/CHANGELOG.md
Labels: Release

#9791 fix: [M3-7081] - Quote variable in changeset shell command
  packages/manager/.changeset/pr-9791-fixed-1697461463011.md
  scripts/changelog/changeset.mjs
Labels: Approved

#9803 Release 1.105.0 - `master -> develop`
  packages/api-v4/.changeset/pr-9677-added-1695693363239.md
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/manager/.changeset/pr-9677-added-1695693479114.md
  packages/manager/.changeset/pr-9703-upcoming-features-1695751361212.md
  packages/manager/.changeset/pr-9725-fixed-1695824674392.md
  packages/manager/.changeset/pr-9728-tests-1696600050126.md
  packages/manager/.changeset/pr-9730-tests-1696881818677.md
  packages/manager/.changeset/pr-9731-fixed-1695931370886.md
  packages/manager/.changeset/pr-9732-added-1696340382725.md
  packages/manager/.changeset/pr-9735-upcoming-features-1696265642529.md
  packages/manager/.changeset/pr-9736-upcoming-features-1696008733328.md
  packages/manager/.changeset/pr-9739-fixed-1696019997998.md
  packages/manager/.changeset/pr-9743-upcoming-features-1696347149626.md
  packages/manager/.changeset/pr-9745-tech-stories-1696272112150.md
  packages/manager/.changeset/pr-9746-fixed-1696274683693.md
  packages/manager/.changeset/pr-9750-fixed-1696365803471.md
  packages/manager/.changeset/pr-9751-upcoming-features-1696367790874.md
  packages/manager/.changeset/pr-9752-tech-stories-1696367849962.md
  packages/manager/.changeset/pr-9753-changed-1696626338930.md
  packages/manager/.changeset/pr-9755-fixed-1696437359700.md
  packages/manager/.changeset/pr-9762-fixed-1696961275313.md
  packages/manager/.changeset/pr-9770-changed-1696954786545.md
  packages/manager/.changeset/pr-9774-tech-stories-1696952177563.md
  packages/manager/.changeset/pr-9776-fixed-1696956017237.md
  packages/manager/.changeset/pr-9780-fixed-1696969213915.md
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Approved, Master → Develop

#9801 test: Fix DBaaS tests after API update
  packages/manager/.changeset/pr-9801-tests-1697547109194.md
  packages/manager/cypress/e2e/core/databases/create-database.spec.ts
  packages/manager/cypress/e2e/core/databases/delete-database.spec.ts
  packages/manager/cypress/e2e/core/databases/update-database.spec.ts
  packages/manager/cypress/support/constants/databases.ts
  packages/manager/cypress/support/intercepts/databases.ts
Labels: Approved

#9775 fix: [M3-7245] - Replaced 'Devices' with 'Services' in Firewall Page
  packages/manager/.changeset/pr-9775-fixed-1696955612922.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
Labels: Approved, Nodebalancer Firewall UX

#9787 feat: [M3-7252] - Only show regions that support VPCs in VPC Create page
  packages/manager/.changeset/pr-9787-upcoming-features-1697145963212.md
  packages/manager/cypress/e2e/core/vpc/vpc-create.spec.ts
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/disabledRegions.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
Labels: Approved, VPC

#9799 docs: Add MigrationNotification Storybook
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.stories.tsx
Labels: Storybook, Approved

#9798 fix: [M3-7270] - Edit Linode VLAN config interface
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
Labels: Approved, VPC

#9786 refactor: [M3-6282] MUI v5 Migration - `SRC > Features > StackScripts` pt2
  packages/manager/.changeset/pr-9786-tech-stories-1697120258125.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
  packages/manager/src/features/StackScripts/CommonStackScript.styles.ts
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptsSection.tsx
  packages/manager/src/features/StackScripts/SelectStackScriptPanel/StackScriptSelectionRow.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.styles.ts
  packages/manager/src/features/StackScripts/StackScriptDialog.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.styles.ts
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanelContent.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptsSection.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/index.ts
  packages/manager/src/features/StackScripts/StackScriptRowHelpers.tsx
  packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedMultiSelect.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedSelect.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.styles.ts
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/index.tsx
  packages/manager/src/features/StackScripts/index.tsx
Labels: Approved, Project: MUI v5 Migration

#9815 fix: [UIE-6961]: Only show regions that support Databases on the Database Create page
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-9815-fixed-1697665414544.md
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
Labels: Project: DBaaS

#9808 fix: [UIE-6952] - DBaaS menu flickers on page load
  packages/manager/.changeset/pr-9808-fixed-1697722511987.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Labels: Project: DBaaS

#9816 test: [M3-7283] - Make `ConfigureForm.test.tsx` Vitest compatible
  packages/manager/.changeset/pr-9816-tests-1697660159676.md
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.test.tsx
Labels: Approved, Unit tests

#9765 test: [M3-7071] - Add Cypress integration tests for NodeBalancer Create DC-specific pricing
  packages/manager/cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts
Labels: Approved, DC-Specific Pricing

#9806 feat: [M3-6816] - Add AGLB Create Route Drawer
  packages/api-v4/.changeset/pr-9806-upcoming-features-1697723638782.md
  packages/api-v4/src/aglb/routes.ts
  packages/manager/.changeset/pr-9806-upcoming-features-1697563902060.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts
  packages/manager/cypress/support/intercepts/load-balancers.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRoutes.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/CreateRouteDrawer.tsx
  packages/manager/src/queries/aglb/routes.ts
  packages/validation/.changeset/pr-9806-upcoming-features-1697723572839.md
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, AGLB

#9819 test: Fix Database Create e2e test region selection
  packages/manager/cypress/support/constants/databases.ts
  packages/manager/cypress/support/util/regions.ts
Labels: Add'tl Approval Needed, e2e

#9814 feat: [M3-7257] - Invalidate VPC-related queries after deleting a linode
  packages/manager/.changeset/pr-9814-upcoming-features-1697651400469.md
  packages/manager/src/features/Linodes/LinodesLanding/DeleteLinodeDialog.tsx
  packages/manager/src/features/Linodes/LinodesLanding/utils.test.ts
  packages/manager/src/features/Linodes/LinodesLanding/utils.ts
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetCreateDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
Labels: Approved, VPC

#9804 feat: [M3-7267] - Add AGLB Rule Delete Dialog
  packages/manager/.changeset/pr-9804-upcoming-features-1697563268544.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRoutes.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/DeleteRuleDialog.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.tsx
Labels: Approved, AGLB

#9812 fix: [M3-7104] - Images create > upload image > reduce space above and below Linode CLI help text
  packages/manager/.changeset/pr-9812-fixed-1697639234272.md
  packages/manager/src/features/Images/ImageUpload.tsx
Labels: Approved

#9813 feat: [M3-6973] - Add DC-specific pricing Object Storage overages
  packages/manager/.changeset/pr-9813-added-1697655032681.md
  packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.tsx
  packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.test.tsx
  packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.tsx
  packages/manager/src/utilities/pricing/dynamicPricing.ts
Labels: Approved, DC-Specific Pricing

#9823 fix: [M3-7298] - Improve Footer Styles
  packages/manager/.changeset/pr-9823-fixed-1697820563300.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/SideMenu.tsx
  packages/manager/src/constants.ts
  packages/manager/src/features/Footer.tsx
  packages/manager/src/features/Footer/Footer.tsx
Labels: Bug, UI, Approved

#9824 change: [M3-7227] - Update VPC-related API types in accordance with new API changes
  packages/api-v4/.changeset/pr-9824-upcoming-features-1697827003419.md
  packages/api-v4/src/linodes/types.ts
  packages/api-v4/src/vpcs/types.ts
  packages/manager/.changeset/pr-9824-upcoming-features-1697827056392.md
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/src/factories/linodeConfigInterfaceFactory.ts
  packages/manager/src/factories/subnets.ts
  packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/features/VPCs/utils.test.ts
  packages/manager/src/features/VPCs/utils.ts
Labels: @linode/api-v4, Approved, VPC

#9811 feat: [M3-7253] - Add AGLB details - Configurations - Routes Table
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationAccordion.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerDetail.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RoutesTable.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, AGLB

#9822 feat: [M3-7028] - Add AGLB Edit Route Drawer
  packages/manager/.changeset/pr-9822-upcoming-features-1697770750840.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/EditRouteDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RoutesTable.tsx
  packages/manager/src/queries/aglb/routes.ts
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, AGLB

#9807 tests: [M3-6219] - Clean up Cypress Firewall tests
  packages/manager/.changeset/pr-9807-tests-1697570775779.md
  packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
  packages/manager/cypress/support/intercepts/firewalls.ts
  packages/manager/cypress/support/intercepts/linodes.ts
  packages/manager/cypress/support/util/regions.ts
Labels: Approved

#9830 refactor: [M3-7098] - Create `Stack` component
  packages/manager/.changeset/pr-9830-tech-stories-1698094153367.md
  packages/manager/src/components/MaintenanceScreen.tsx
  packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
  packages/manager/src/components/Stack.stories.tsx
  packages/manager/src/components/Stack.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Betas/BetaDetails.tsx
  packages/manager/src/features/Betas/BetaDetailsList.tsx
  packages/manager/src/features/Betas/BetasLanding.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/GlobalNotifications/APIMaintenanceBanner.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/Certificates.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/index.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationAccordion.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerServiceTargets.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerSettings.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerSummary.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RoutesTable.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/CreateServiceTargetDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/LinodeOrIPSelect.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Settings/Delete.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Settings/Label.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Settings/Region.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerRow.tsx
  packages/manager/src/features/Profile/Settings/Settings.tsx
  packages/manager/src/features/Support/Hively.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/Users/UserRow.tsx
  packages/manager/src/features/Volumes/VolumeDetailsDrawer.tsx
Labels: Project: MUI v5 Migration

#9771 feat: 10/30/23 Marketplace apps
  packages/manager/.changeset/pr-9771-added-1698247004747.md
  packages/manager/public/assets/mainconcept.svg
  packages/manager/public/assets/simplexchat.svg
  packages/manager/public/assets/white/mainconcept.svg
  packages/manager/public/assets/white/simplexchat.svg
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Marketplace, Approved

#9800 feat: [M3-6888] - Add AGLB "Edit Service Target" drawer
  packages/api-v4/.changeset/pr-9800-upcoming-features-1698173062924.md
  packages/api-v4/src/aglb/service-targets.ts
  packages/manager/.changeset/pr-9800-upcoming-features-1698173161683.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-service-targets.spec.ts
  packages/manager/cypress/support/intercepts/load-balancers.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerServiceTargets.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/aglb/serviceTargets.ts
  packages/validation/.changeset/pr-9800-upcoming-features-1698172955122.md
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, AGLB

#9836 fix: [M3-7249] - Linode Landing flickering
  packages/manager/.changeset/pr-9836-fixed-1698158641264.md
  packages/manager/cypress/e2e/core/general/account-activation.spec.ts
  packages/manager/src/IdentifyUser.tsx
  packages/manager/src/MainContent.test.ts
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
  packages/manager/src/components/PreferenceToggle/PreferenceToggle.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.test.tsx
Labels: Bug, Approved

#9825 feat: [M3-7288] - AGLB create page with Actions buttons.
  packages/manager/.changeset/pr-9825-upcoming-features-1698093221284.md
  packages/manager/src/components/VerticalLinearStepper/VerticalLinearStepper.styles.ts
  packages/manager/src/components/VerticalLinearStepper/VerticalLinearStepper.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerConfiguration.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerConfiguration.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerCreate.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerLabel.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerLabel.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerRegions.tsx
Labels: Approved, AGLB

#9827 change: [M3-7182] - Update RemovableSelectionsList default maximum height to cut off the last list item
  packages/manager/.changeset/pr-9827-upcoming-features-1698091273479.md
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.style.ts
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.test.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectAppPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
Labels: Approved, VPC

#9820 fix: [M3-7268] - Unassign multiple Linodes from Subnet
  packages/manager/.changeset/pr-9820-upcoming-features-1698170376454.md
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
Labels: Approved, VPC

#9833 test: [DBASS1-574] - Adding test coverage for disk metrics added to UI.
  packages/manager/.changeset/pr-9833-tests-1698335199212.md
  packages/manager/cypress/e2e/core/databases/update-database.spec.ts
  packages/manager/cypress/e2e/core/notificationsAndEvents/events.spec.ts
Labels: Ready for Review, Missing Changeset

#9834 fix: [M3-7285] – Tweak when and where `public` interfaces are included in Linode Create payload
  packages/manager/.changeset/pr-9834-changed-1698111109868.md
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Labels: Approved, VPC

#9841 refactor: [M3-7329] - MUI Migration - `SRC > Components > Crumbs`
  packages/manager/.changeset/pr-9841-tech-stories-1698261567678.md
  packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
  packages/manager/src/components/Breadcrumb/Breadcrumb.stories.tsx
  packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
  packages/manager/src/components/Breadcrumb/Crumbs.tsx
  packages/manager/src/components/Breadcrumb/README.md
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
  packages/manager/src/features/Domains/DomainActionMenu.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu.tsx
  packages/manager/src/features/Kubernetes/ClusterList/ClusterActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrationPricing.tsx
  packages/manager/src/features/Managed/Credentials/CredentialActionMenu.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/FolderActionMenu.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.tsx
  packages/manager/src/features/Profile/APITokens/APITokenMenu.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClientActionMenu.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptActionMenu.tsx
  packages/manager/src/features/Users/UsersActionMenu.tsx
  packages/manager/src/features/Volumes/VolumesActionMenu.tsx
Labels: Approved, Project: MUI v5 Migration

#9832 feat: [M3-7169, M3-7193, M3-7211, M3-7255, M3-7258] - VPC UX feedback
  packages/manager/.changeset/pr-9832-upcoming-features-1698162070035.md
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
  packages/manager/src/assets/icons/entityIcons/vpc.svg
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEmptyState.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEmptyStateData.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPCs/constants.ts
Labels: Approved, VPC

#9837 fix: [M3-7313] - Migrated Linode dropdown to Autocomplete in Firewall Landing > Create Firewall drawer
  packages/manager/.changeset/pr-9785-fixed-1697059201989.md
  packages/manager/.changeset/pr-9837-fixed-1698172001079.md
  packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
Labels: Nodebalancer Firewall UX

#9851 fix: [M3-7348] - Only unassign linodes in the 'Linodes to be Unassigned from Subnet' list for Subnet Unassign Drawer
  packages/manager/.changeset/pr-9851-upcoming-features-1698695391804.md
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
Labels: Approved, VPC

#9852 Release 1.106.0 - master -> develop
  packages/api-v4/.changeset/pr-9800-upcoming-features-1698173062924.md
  packages/api-v4/.changeset/pr-9806-upcoming-features-1697723638782.md
  packages/api-v4/.changeset/pr-9824-upcoming-features-1697827003419.md
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/manager/.changeset/pr-9660-added-1697473425862.md
  packages/manager/.changeset/pr-9709-upcoming-features-1697141846298.md
  packages/manager/.changeset/pr-9748-tech-stories-1696350216805.md
  packages/manager/.changeset/pr-9754-tech-stories-1696437177982.md
  packages/manager/.changeset/pr-9756-tech-stories-1696441475265.md
  packages/manager/.changeset/pr-9771-added-1698247004747.md
  packages/manager/.changeset/pr-9773-tech-stories-1696952796931.md
  packages/manager/.changeset/pr-9777-tests-1696958372039.md
  packages/manager/.changeset/pr-9778-upcoming-features-1696961231870.md
  packages/manager/.changeset/pr-9781-tests-1697144294347.md
  packages/manager/.changeset/pr-9782-tests-1697147463647.md
  packages/manager/.changeset/pr-9783-tech-stories-1697046190232.md
  packages/manager/.changeset/pr-9784-tests-1697487553929.md
  packages/manager/.changeset/pr-9785-fixed-1697059201989.md
  packages/manager/.changeset/pr-9786-tech-stories-1697120258125.md
  packages/manager/.changeset/pr-9787-upcoming-features-1697145963212.md
  packages/manager/.changeset/pr-9788-changed-1697134985443.md
  packages/manager/.changeset/pr-9790-changed-1697132255387.md
  packages/manager/.changeset/pr-9791-fixed-1697461463011.md
  packages/manager/.changeset/pr-9800-upcoming-features-1698173161683.md
  packages/manager/.changeset/pr-9801-tests-1697547109194.md
  packages/manager/.changeset/pr-9804-upcoming-features-1697563268544.md
  packages/manager/.changeset/pr-9806-upcoming-features-1697563902060.md
  packages/manager/.changeset/pr-9807-tests-1697570775779.md
  packages/manager/.changeset/pr-9808-fixed-1697722511987.md
  packages/manager/.changeset/pr-9809-tests-1697572246108.md
  packages/manager/.changeset/pr-9810-added-1697595269902.md
  packages/manager/.changeset/pr-9812-fixed-1697639234272.md
  packages/manager/.changeset/pr-9813-added-1697655032681.md
  packages/manager/.changeset/pr-9814-upcoming-features-1697651400469.md
  packages/manager/.changeset/pr-9815-fixed-1697665414544.md
  packages/manager/.changeset/pr-9816-tests-1697660159676.md
  packages/manager/.changeset/pr-9822-upcoming-features-1697770750840.md
  packages/manager/.changeset/pr-9823-fixed-1697820563300.md
  packages/manager/.changeset/pr-9824-upcoming-features-1697827056392.md
  packages/manager/.changeset/pr-9826-fixed-1698115883663.md
  packages/manager/.changeset/pr-9830-tech-stories-1698094153367.md
  packages/manager/.changeset/pr-9835-fixed-1698158982152.md
  packages/manager/.changeset/pr-9838-upcoming-features-1698178631355.md
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/validation/.changeset/pr-9709-changed-1697141933133.md
  packages/validation/.changeset/pr-9800-upcoming-features-1698172955122.md
  packages/validation/.changeset/pr-9806-upcoming-features-1697723572839.md
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Master → Develop

#9845 change: [M3-7289] – Payload refinements in "Assign Linodes" flow
  packages/manager/.changeset/pr-9845-upcoming-features-1698349552302.md
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
Labels: Approved, VPC

#9854 fix: [OCA-1229] - Correct links to Main Concept and Simplex docs
  packages/manager/.changeset/pr-9854-fixed-1698764756434.md
  packages/manager/src/features/OneClickApps/oneClickApps.ts
Labels: Marketplace, Approved
