Repository linode/manager, pull requests merged in 2023-02, with the labels that each got.

#8749 M3-6067: Update Copy and Spacing - Part 2
  packages/manager/src/components/TabLinkList/TabLinkList.tsx
  packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
Labels: UI, API/CLI Project

#8742 M3-6065: API Tokens Refactors and Fixes
  packages/api-v4/src/account/types.ts
  packages/manager/src/App.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessCell.tsx
  packages/manager/src/features/Profile/APITokens/APITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/APITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/APITokenMenu.tsx
  packages/manager/src/features/Profile/APITokens/APITokenTable.test.ts
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
  packages/manager/src/features/Profile/APITokens/APITokens.test.tsx
  packages/manager/src/features/Profile/APITokens/APITokens.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/EditAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/EditAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/RevokeTokenDialog.test.tsx
  packages/manager/src/features/Profile/APITokens/RevokeTokenDialog.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/index.tsx
  packages/manager/src/features/Profile/APITokens/utils.test.ts
  packages/manager/src/features/Profile/APITokens/utils.ts
  packages/manager/src/features/Profile/Profile.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/base.ts
  packages/manager/src/queries/profile.ts
  packages/manager/src/queries/tokens.ts
Labels: Bug, React Query

#8735 M3-6039: Update FirewallRuleTable to support screen readers
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
Labels: accessibility

#8753 Manually pin `ua-parser-js` to `0.7.33` for CVE-2022-25927
  package.json
  yarn.lock
Labels: dependencies

#8747 Fix strings in cli commands
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/utilities/escapeStringForCLI.ts
  packages/manager/src/utilities/generate-cURL.test.ts
  packages/manager/src/utilities/generate-cURL.ts
  packages/manager/src/utilities/generate-cli.test.ts
  packages/manager/src/utilities/generate-cli.ts
Labels: API/CLI Project

#8779 M3-6094: Add role attribute to top menu icons
  packages/manager/src/features/TopMenu/TopMenuIcon.tsx
Labels: accessibility

#8762 Fix Uneven Breakpoints in Kubernetes Landing Table
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
Labels: Bug, UI

#8770 Account Agreements Query Small Optimization
  packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
  packages/manager/src/queries/accountAgreements.ts
Labels: React Query

#8785 Fix Cypress failure involving top menu icon changes
  packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
Labels: e2e

#8782 Release v1.85.0 -> develop
  CHANGELOG.md
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/manager/package.json
  packages/manager/src/assets/logo/akamai-logo.svg
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Release

#8745 Migrate to MUI v5 Theme format and make our theme more typesafe
  packages/manager/src/LinodeThemeWrapper.tsx
  packages/manager/src/components/AccountActivation/AccountActivationLanding.tsx
  packages/manager/src/components/IconButton/IconButton.tsx
  packages/manager/src/components/LineGraph/MetricsDisplay.test.tsx
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/components/SnackBar/SnackBar.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.tsx
  packages/manager/src/components/core/styles/createMuiTheme.ts
  packages/manager/src/components/core/styles/index.ts
  packages/manager/src/features/GlobalNotifications/EmailBounce.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderNotification.tsx
  packages/manager/src/features/TopMenu/UserNotificationsMenu/UserNotificationListItem.tsx
  packages/manager/src/features/TopMenu/UserNotificationsMenu/UserNotificationsButton.tsx
  packages/manager/src/features/TopMenu/UserNotificationsMenu/UserNotificationsMenu.tsx
  packages/manager/src/features/linodes/MigrateLanding/CautionNotice.tsx
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
Labels: Enhancement

#8768 M3-6079: Creating a Linode via a StackScript - Require `image` Field
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/validation/src/linodes.schema.ts
Labels: @linode/validation

#8793 `staging` --> `master` for Cloud v1.86.0 release
  CHANGELOG.md
  packages/manager/cypress/e2e/account/service-transfer.spec.ts
  packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/package.json
  packages/manager/src/LinodeThemeWrapper.tsx
  packages/manager/src/assets/logo/akamai-logo.svg
  packages/manager/src/assets/logo/logo-animated.svg
  packages/manager/src/components/AccountActivation/AccountActivationLanding.tsx
  packages/manager/src/components/IconButton/IconButton.tsx
  packages/manager/src/components/LineGraph/MetricsDisplay.test.tsx
  packages/manager/src/components/MainContentBanner.tsx
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/SnackBar/SnackBar.tsx
  packages/manager/src/components/SplashScreen/SplashScreen.tsx
  packages/manager/src/components/SplashScreen/keyframes.css
  packages/manager/src/components/TagsPanel/TagsPanel.tsx
  packages/manager/src/components/core/styles/createMuiTheme.ts
  packages/manager/src/components/core/styles/index.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
  packages/manager/src/features/Billing/PdfGenerator/akamai-logo.png
  packages/manager/src/features/CancelLanding/CancelLanding.test.tsx
  packages/manager/src/features/CancelLanding/CancelLanding.tsx
  packages/manager/src/features/GlobalNotifications/EmailBounce.tsx
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderNotification.tsx
  packages/manager/src/features/TopMenu/TopMenuIcon.tsx
  packages/manager/src/features/TopMenu/UserNotificationsMenu/UserNotificationListItem.tsx
  packages/manager/src/features/TopMenu/UserNotificationsMenu/UserNotificationsButton.tsx
  packages/manager/src/features/TopMenu/UserNotificationsMenu/UserNotificationsMenu.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
  packages/manager/src/features/linodes/MigrateLanding/CautionNotice.tsx
  packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
  packages/manager/src/index.tsx
  packages/manager/src/queries/accountAgreements.ts
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
  packages/manager/src/utilities/getEventsActionLink.ts
  packages/validation/CHANGELOG.md
  packages/validation/package.json
  packages/validation/src/linodes.schema.ts
Labels: Release

#8794 `master` --> `develop` following release of Cloud v1.86.0
  CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/assets/logo/akamai-logo.svg
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
  packages/manager/src/utilities/generate-cli.ts
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Release

#8769 M3-6009: Add Cypress integration tests for Personal Access Token CRUD
  packages/manager/cypress/e2e/account/personal-access-tokens.spec.ts
  packages/manager/cypress/support/intercepts/profile.ts
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
  packages/manager/src/features/Profile/APITokens/RevokeTokenDialog.tsx
Labels: e2e

#8757 M3-4090: Object Storage Add Ability to Create "Folders"
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/CreateFolderDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/FolderActionMenu.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx
  packages/manager/src/features/ObjectStorage/utilities.ts
  packages/manager/src/queries/objectStorage.ts
Labels: Object Storage

#8752 M3-5193: RQ-ify tags + enhancements
  packages/manager/src/components/Tag/Tag.tsx
  packages/manager/src/components/TagCell/AddTag.tsx
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/components/TagCell/TagDrawer.tsx
  packages/manager/src/components/TagsInput/TagsInput.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.tsx
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
  packages/manager/src/queries/tags.ts
Labels: React Query

#8808 staging → master for v1.87.0
  CHANGELOG.md
  packages/manager/cypress/e2e/account/personal-access-tokens.spec.ts
  packages/manager/cypress/support/intercepts/profile.ts
  packages/manager/package.json
  packages/manager/src/components/TextTooltip/TextTooltip.tsx
  packages/manager/src/components/TextTooltip/index.ts
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/CreateFolderDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/FolderActionMenu.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx
  packages/manager/src/features/ObjectStorage/utilities.ts
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
  packages/manager/src/features/Profile/APITokens/RevokeTokenDialog.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/queries/objectStorage.ts
Labels: Release

#8691 M3-5896: Enable Cypress recording and parallelization via Jenkins
  docker-compose.yml
  packages/manager/Dockerfile
Labels: e2e

#8806 fix(PrimaryNav): M3-6162 - Improve new branded logo animation and transition
  packages/manager/src/assets/logo/akamai-logo.svg
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
Labels: accessibility, UI

#8814 Remove `wait-on` package for CVE-2023-25166
  packages/manager/package.json
  yarn.lock
Labels: dependencies

#8815 fix(PrimaryNav): M3-6162 - Update E2E tests for this previous change
  packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
Labels: e2e

#8812 Fetch all tags when cleaning Cypress test tags
  packages/manager/cypress/support/api/tags.ts
  packages/manager/cypress/support/ui/common.ts
Labels: e2e

#8798 M3-6078: Account Logins Show `Successful` or `Failed` Access
  packages/api-v4/src/account/types.ts
  packages/manager/src/components/StatusIcon/StatusIcon.tsx
  packages/manager/src/features/Account/AccountLogins.tsx
  packages/manager/src/features/Account/AccountLoginsTableRow.tsx
  packages/manager/src/index.css
Labels: UI

#8756 M3-5182: RQ-ify Images Pt. 3
  packages/manager/src/App.tsx
  packages/manager/src/components/EntityTable/EntityTable.stories.mdx
  packages/manager/src/components/FileUploader/FileUploader.tsx
  packages/manager/src/containers/images.container.tsx
  packages/manager/src/containers/withImage.container.ts
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/Search/SearchLanding.test.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/withStoreSearch.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx
  packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.tsx
  packages/manager/src/queries/images.ts
  packages/manager/src/store/image/image.actions.ts
  packages/manager/src/store/image/image.reducer.test.ts
  packages/manager/src/store/image/image.reducer.ts
  packages/manager/src/store/image/image.requests.ts
  packages/manager/src/store/index.ts
  packages/manager/src/store/middleware/imageEvents.ts
  packages/manager/src/store/selectors/entitiesErrors.ts
  packages/manager/src/store/selectors/entitiesLoading.ts
  packages/manager/src/store/selectors/getSearchEntities.test.ts
  packages/manager/src/store/selectors/getSearchEntities.ts
  packages/manager/src/utilities/getEntityByIDFromStore.ts
Labels: React Query, Approved

#8677 Validate api-v4 package before publishing to NPM
  .github/workflows/ci.yml
  scripts/validatePackages/sdk-commonjs.cjs
  scripts/validatePackages/sdk-esm.js
Labels: Testing, Approved

#8821 refactor: M3-6195 - Add tss-react and refactor Button to styled API
  packages/manager/package.json
  packages/manager/src/assets/icons/reload.svg
  packages/manager/src/components/Button/Button.test.tsx
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/HelpIcon/HelpIcon.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/CreateFolderDrawer.tsx
  packages/manager/src/features/Profile/APITokens/RevokeTokenDialog.tsx
  packages/manager/src/styles/index.ts
  packages/manager/src/styles/keyframes.ts
  packages/manager/src/themeFactory.ts
  packages/manager/src/utilities/isPropValid/index.ts
  packages/manager/src/utilities/isPropValid/isPropValid.ts
  yarn.lock
Labels: Testing, Enhancement

#8829 fix: Allow DBaaS e2e tests to pass regardless of engine minor version
  packages/manager/cypress/e2e/databases/create-database.spec.ts
Labels: e2e

#8805 M3-6173: Improve Cypress support for alternative environments
  packages/api-v4/src/index.ts
  packages/manager/cypress/e2e/account/billing-contact.spec.ts
  packages/manager/cypress/e2e/account/default-payment-method.spec.ts
  packages/manager/cypress/e2e/account/google-pay.spec.ts
  packages/manager/cypress/e2e/account/smoke-billing-activity.spec.ts
  packages/manager/cypress/e2e/databases/create-database.spec.ts
  packages/manager/cypress/e2e/domains/smoke-create-domain-records.spec.ts
  packages/manager/cypress/e2e/domains/smoke-create-domain.spec.ts
  packages/manager/cypress/e2e/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/general/smoke-deep-link.spec.ts
  packages/manager/cypress/e2e/helpAndSupport/open-support-ticket.spec.ts
  packages/manager/cypress/e2e/helpAndSupport/support.spec.ts
  packages/manager/cypress/e2e/images/create-linode-from-image.spec.ts
  packages/manager/cypress/e2e/images/machine-image-upload.spec.ts
  packages/manager/cypress/e2e/images/smoke-create-image.spec.ts
  packages/manager/cypress/e2e/kubernetes/smoke-lke-create.spec.ts
  packages/manager/cypress/e2e/linodes/backup-linode.spec.ts
  packages/manager/cypress/e2e/linodes/clone-linode.spec.ts
  packages/manager/cypress/e2e/linodes/create-linode.spec.ts
  packages/manager/cypress/e2e/linodes/linode-storage.spec.ts
  packages/manager/cypress/e2e/linodes/rescue-linode.spec.ts
  packages/manager/cypress/e2e/linodes/resize-linode.spec.ts
  packages/manager/cypress/e2e/linodes/smoke-delete-linode.spec.ts
  packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/cypress/e2e/longview/longview.spec.ts
  packages/manager/cypress/e2e/nodebalancers/smoke-create-nodebal.spec.ts
  packages/manager/cypress/e2e/notificationsAndEvents/events.spec.ts
  packages/manager/cypress/e2e/notificationsAndEvents/notifications.spec.ts
  packages/manager/cypress/e2e/objectStorage/object-storage-errors.spec.ts
  packages/manager/cypress/e2e/volumes/attach-volume.spec.ts
  packages/manager/cypress/e2e/volumes/clone-volume.spec.ts
  packages/manager/cypress/e2e/volumes/create-volume.smoke.spec.ts
  packages/manager/cypress/e2e/volumes/create-volume.spec.ts
  packages/manager/cypress/e2e/volumes/delete-volume.spec.ts
  packages/manager/cypress/e2e/volumes/resize-volume.spec.ts
  packages/manager/cypress/e2e/volumes/update-volume.spec.ts
  packages/manager/cypress/support/api/objectStorage.ts
  packages/manager/cypress/support/api/routes.ts
  packages/manager/cypress/support/api/volumes.ts
  packages/manager/cypress/support/intercepts/account.ts
  packages/manager/cypress/support/intercepts/common.ts
  packages/manager/cypress/support/intercepts/databases.ts
  packages/manager/cypress/support/intercepts/linodes.ts
  packages/manager/cypress/support/intercepts/managed.ts
  packages/manager/cypress/support/intercepts/object-storage.ts
  packages/manager/cypress/support/intercepts/profile.ts
  packages/manager/cypress/support/intercepts/stackscripts.ts
  packages/manager/cypress/support/login.ts
  packages/manager/cypress/support/ui/common.ts
  packages/manager/cypress/support/ui/constants.ts
  packages/manager/cypress/support/util/intercepts.ts
  packages/manager/cypress/support/util/paginate.ts
Labels: Approved

#8807 feat: [M3-6149] - Add Cloud Init checkbox to Image Capture/Create flow
  packages/api-v4/src/images/images.ts
  packages/api-v4/src/images/types.ts
  packages/manager/src/components/CheckBox/CheckBox.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
  packages/manager/src/store/image/image.requests.ts
  packages/validation/src/images.schema.ts
Labels: Metadata

#8795 M3-5195: RQ-ify user preferences
  packages/manager/src/App.test.tsx
  packages/manager/src/App.tsx
  packages/manager/src/LinodeThemeWrapper.tsx
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
  packages/manager/src/components/HighlightedMarkdown/__snapshots__/HighlightedMarkdown.test.tsx.snap
  packages/manager/src/components/MainContentBanner.tsx
  packages/manager/src/components/OrderBy.tsx
  packages/manager/src/components/PreferenceToggle/PreferenceToggle.tsx
  packages/manager/src/components/SplashScreen/SplashScreen.tsx
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
  packages/manager/src/containers/preferences.container.ts
  packages/manager/src/factories/preferences.ts
  packages/manager/src/features/Account/EnableObjectStorage.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx
  packages/manager/src/features/Domains/DeleteDomain.test.tsx
  packages/manager/src/features/Help/StatusBanners.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
  packages/manager/src/features/Longview/shared/TimeRangeSelect.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.test.tsx
  packages/manager/src/features/Profile/Profile.tsx
  packages/manager/src/features/Profile/Settings/PreferenceEditor.tsx
  packages/manager/src/features/Profile/Settings/Settings.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.test.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenuItem.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/hooks/useDismissibleNotifications.ts
  packages/manager/src/hooks/useOrder.test.tsx
  packages/manager/src/hooks/useOrder.ts
  packages/manager/src/hooks/usePagination.ts
  packages/manager/src/hooks/usePreferences.ts
  packages/manager/src/index.tsx
  packages/manager/src/queries/preferences.ts
  packages/manager/src/store/index.ts
  packages/manager/src/store/preferences/preferences.reducer.ts
  packages/manager/src/store/preferences/preferences.requests.ts
  packages/manager/src/types/ManagerPreferences.ts
  packages/manager/src/utilities/testHelpers.tsx
Labels: React Query, Approved

#8811 feat: [M3 6143] - Add User Data Accordion to Linode Create page
  packages/api-v4/src/images/types.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/src/components/Accordion/Accordion.tsx
  packages/manager/src/factories/images.ts
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/UserDataAccordion.tsx
  packages/validation/src/linodes.schema.ts
Labels: Metadata

#8830 Re-enable RQ DevTools
  packages/manager/src/index.tsx
Labels: Bug, React Query
