Repository linode/manager, pull requests merged in 2023-12, with the labels that each got.

#9940 test: [M3-7321] - Combine billing cypress tests
  packages/manager/.changeset/pr-9940-tests-1701368286376.md
  packages/manager/cypress/e2e/core/billing/billing-contact.spec.ts
Labels: Approved

#9849 feat: [M3-7292] - Stepper component - Details content
  packages/api-v4/src/aglb/types.ts
  packages/manager/.changeset/pr-9849-upcoming-features-1698676302215.md
  packages/manager/src/factories/aglb.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ConfigurationDetails.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerActionPanel.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerConfiguration.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerConfiguration.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerConfigurations.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerCreate.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerLabel.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerLabel.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/constants.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/constants.tsx
  packages/manager/src/features/LoadBalancers/constants.ts
  packages/manager/src/utilities/testHelpers.tsx
  packages/validation/src/loadbalancers.schema.ts
Labels: Add'tl Approval Needed, Ready for Review, AGLB

#9933 change: [M3-7485] - Revert Disable Public IP for Linodes Landing
  packages/manager/.changeset/pr-9899-upcoming-features-1699911388781.md
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
Labels: Approved, VPC

#9945 upcoming: [M3-7220, M3-7355] - Add DC Get Well logic to various user flows pt2 and cleanup
  packages/manager/.changeset/pr-9945-upcoming-features-1701375629844.md
  packages/manager/src/components/RegionSelect/RegionSelect.stories.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.test.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.styles.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCCreateDrawer.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.tsx
  packages/manager/src/hooks/useCreateVPC.ts
Labels: Add'tl Approval Needed, DC Get Well

#9941 upcoming: [M3-7131] - Add AGLB Configuration Edit Tests & General Bug Fixes
  packages/api-v4/src/aglb/types.ts
  packages/manager/.changeset/pr-9941-upcoming-features-1701203325929.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-configurations.spec.ts
  packages/manager/cypress/support/intercepts/load-balancers.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/EditCertificateDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/EditCertificateDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ApplyCertificatesDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/CertificateTable.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerServiceTargets.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx
  packages/manager/src/queries/aglb/serviceTargets.ts
  packages/validation/src/loadbalancers.schema.ts
Labels: Add'tl Approval Needed, Ready for Review, AGLB

#9938 upcoming: [M3-7301] - Replace Linode Network Transfer History chart with Recharts
  packages/manager/.changeset/pr-9938-upcoming-features-1701201054946.md
  packages/manager/package.json
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransferHistoryChart.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
  yarn.lock
Labels: Approved, Recharts

#9944 feat: [M3-7412] - Add new Parent/Child api-v4 endpoints
  packages/api-v4/.changeset/pr-9944-upcoming-features-1701281121547.md
  packages/api-v4/src/account/account.ts
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/types.ts
  packages/manager/.changeset/pr-9944-upcoming-features-1701281085057.md
  packages/manager/src/queries/account.ts
  packages/manager/src/request.test.tsx
  packages/manager/src/request.tsx
Labels: @linode/api-v4, Approved, Parent / Child Account

#9952 test: [M3-6169] - Account cancellation integration tests
  packages/manager/.changeset/pr-9952-tests-1701457740855.md
  packages/manager/cypress/e2e/core/account/account-cancellation.spec.ts
  packages/manager/cypress/support/intercepts/account.ts
  packages/manager/cypress/support/intercepts/general.ts
  packages/manager/cypress/support/ui/accordion.ts
Labels: Ready for Review, Parent / Child Account

#9957 fix: Update types for DC get well endpoint
  packages/api-v4/src/account/types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.ts
  packages/manager/src/factories/accountAvailability.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: DC Get Well

#9954 upcoming: [M3-7520] - AGLB Fixes and Improvements
  packages/api-v4/src/aglb/types.ts
  packages/manager/.changeset/pr-9954-fixed-1701698397297.md
  packages/manager/.changeset/pr-9954-upcoming-features-1701698414248.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-landing-page.spec.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts
  packages/manager/src/components/TableCell/TableCell.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ConfigurationDetails.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerRegions.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CreateCertificateDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/constants.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/index.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerSummary.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/CreateRouteDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/DeleteRuleDialog.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/constants.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.test.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RuleRow.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/utils.test.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/utils.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Settings/Region.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerRow.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/Ports.tsx
  packages/validation/src/loadbalancers.schema.ts
Labels: Ready for Review, AGLB

#9956 refactor: [M3-7531] - SideMenu & UserMenu Storybook v7 Story
  packages/manager/.changeset/pr-9956-tech-stories-1701724808593.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/PrimaryNav/SideMenu.stories.tsx
  packages/manager/src/components/PrimaryNav/SideMenu.test.tsx
  packages/manager/src/components/PrimaryNav/SideMenu.tsx
  packages/manager/src/components/SideMenu.stories.mdx
  packages/manager/src/components/UserMenu.stories.mdx
  packages/manager/src/features/Footer.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.stories.tsx
Labels: Storybook, Approved

#9958 refactor: [M3-7532] - Payment Method Row Storybook v7 Story
  packages/manager/.changeset/pr-9958-tech-stories-1701721635562.md
  packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.test.tsx
  packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.mdx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.test.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.test.tsx
  packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
  packages/manager/src/components/PaymentMethodRow/index.ts
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentMethods.tsx
Labels: Storybook, Approved

#9946 feat: [M3-7086] - Add pricing Docs Link to create/clone flows and remove DC-specific pricing warning notice
  packages/manager/.changeset/pr-9946-changed-1701467724778.md
  packages/manager/.changeset/pr-9946-tests-1701467652746.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/src/components/DynamicPriceNotice.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.test.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.styles.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/utilities/pricing/constants.ts
  packages/manager/src/utilities/pricing/linodes.test.ts
  packages/manager/src/utilities/pricing/linodes.ts
Labels: Approved, DC-Specific Pricing

#9962 change: [M3-7493] – Update UX copy on VPC Create page
  packages/manager/.changeset/pr-9962-upcoming-features-1701804783926.md
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/SubnetContent.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.tsx
  packages/manager/src/features/VPCs/constants.ts
Labels: Approved, VPC

#9951 change: [M3-7492] – VPC Landing page empty state resource links & copy updates
  packages/manager/.changeset/pr-9951-upcoming-features-1701454182728.md
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
  packages/manager/src/features/VPCs/VPCLanding/VPCEmptyState.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEmptyStateData.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLandingEmptyStateData.tsx
Labels: Add'tl Approval Needed, VPC

#9966 change: [M3-7494] – Update copy for Linode "Reboot Needed" tooltip
  packages/manager/.changeset/pr-9966-upcoming-features-1701878955797.md
  packages/manager/src/features/VPCs/constants.ts
Labels: Approved, VPC

#9967 change: Remove VPC Banner on Linodes Landing
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
Labels: Approved, VPC

#9971 fix: [M3-7533] - RegionSelect sorting in Firefox
  packages/manager/.changeset/pr-9971-fixed-1701887926900.md
  packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.ts
Labels: Approved

#9950 change: [OCA-1240] - Update Main Concept app names to include demo
  packages/manager/.changeset/pr-9950-changed-1701876302104.md
  packages/manager/src/cachedData/marketplace.json
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Marketplace, Approved

#9974 change: [M3-7546] - Revert FW table row changes
  packages/manager/.changeset/pr-9974-changed-1701965338643.md
  packages/manager/package.json
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
Labels: Nodebalancer Firewall UX

#9959 refactor: [M3-7537] - PaginationControls Storybook v7 Story
  packages/manager/.changeset/pr-9959-tech-stories-1701811015350.md
  packages/manager/src/components/PaginationControls/PaginationControls.stories.mdx
  packages/manager/src/components/PaginationControls/PaginationControls.stories.tsx
  packages/manager/src/components/PaginationControls/PaginationControls.test.tsx
  packages/manager/src/components/PaginationControls/PaginationControls.tsx
Labels: Storybook, Approved

#9975 upcoming: [M3-7553] - AGLB Refinements and Improvements - Selects and Forms
  packages/manager/.changeset/pr-9975-upcoming-features-1702056998142.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-configurations.spec.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts
  packages/manager/cypress/support/ui/autocomplete.ts
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RouteSelect.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetSelect.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Settings/Label.tsx
Labels: Approved, AGLB

#9985 fix: FW NodeBalancer Release Fixes
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings.tsx
  packages/manager/src/queries/nodebalancers.ts
Labels: Nodebalancer Firewall UX

#9968 change: [M3-7499, M3-7502, M3-7507] – UX copy updates for VPC Panel in Linode Create & Linode Add/Edit Config Dialog
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/constants.ts
  packages/manager/src/features/VPCs/constants.ts
Labels: Approved, VPC

#9977 upcoming: [M3-7414] - Add mocks and update queries for new Parent/Child endpoints
  packages/manager/.changeset/pr-9977-upcoming-features-1701987666651.md
  packages/manager/src/env.d.ts
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/account.ts
Labels: Approved, Parent / Child Account

#9961 chore: [M3-7551] - Update Vite and Vitest
  packages/api-v4/package.json
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/support/plugins/configure-api.ts
  packages/manager/cypress/support/plugins/discard-passed-test-recordings.ts
  packages/manager/cypress/support/plugins/load-env-config.ts
  packages/manager/cypress/support/plugins/vite-preprocessor.ts
  packages/manager/cypress/tsconfig.json
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved

#9969 fix: [M3-7543] - AGLB Rule Drawer - Session Stickiness TTL - Use Seconds instead of Milliseconds
  packages/manager/.changeset/pr-9969-upcoming-features-1701885967965.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetDrawer.test.tsx
Labels: Approved, AGLB

#9973 ci: [M3-7550] - Add Lint To Github Actions
  .github/workflows/ci.yml
  packages/api-v4/.changeset/pr-9973-tech-stories-1701959506143.md
  packages/manager/.changeset/pr-9973-tech-stories-1701959520658.md
  packages/manager/.eslintrc.cjs
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/validation/.changeset/pr-9973-tech-stories-1701959541076.md
Labels: Approved, Ready for Review

#9988 ci: Speed Up Code Coverage Github Actions Jobs
  .github/workflows/coverage.yml
  .github/workflows/coverage_badge.yml
  packages/manager/.changeset/pr-9988-tech-stories-1702336644030.md
Labels: Approved, Performance

#9990 change: [M3-7505] – Update copy for Private IP add-on in Linode Create flow
  packages/manager/.changeset/pr-9990-upcoming-features-1702400746535.md
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
Labels: Approved, VPC

#9955 test: [M3-7135] - Add integration test for AGLB Load Balancer delete flows
  packages/manager/.changeset/pr-9955-tests-1701693591911.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-landing-page.spec.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-summary.spec.ts
  packages/manager/cypress/support/intercepts/load-balancers.ts
Labels: e2e, Approved, AGLB

#9963 refactor: [M3-7542] - TagsInput & TagsPanel Storybook v7 Stories
  packages/manager/.changeset/pr-9963-tech-stories-1701881397641.md
  packages/manager/.storybook/preview.tsx
  packages/manager/src/components/Tag/Tag.stories.tsx
  packages/manager/src/components/TagsInput/TagsInput.stories.mdx
  packages/manager/src/components/TagsInput/TagsInput.stories.tsx
  packages/manager/src/components/TagsInput/TagsInput.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.stories.mdx
  packages/manager/src/components/TagsPanel/TagsPanel.stories.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.styles.ts
  packages/manager/src/components/TagsPanel/TagsPanel.test.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.tsx
Labels: Storybook, Approved

#9984 chore: Rewrite some Enzyme Unit Tests
  packages/manager/src/App.test.tsx
  packages/manager/src/components/ModeSelect/ModeSelect.test.tsx
  packages/manager/src/factories/accountUsers.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx
Labels: Approved, Unit tests, Clean Up

#9995 test: [M3-7470] - Cypress test for Volumes landing page empty state
  packages/manager/.changeset/pr-9995-tests-1702420300908.md
  packages/manager/cypress/e2e/core/volumes/landing-page-empty-state.spec.ts
Labels: Testing

#9983 upcoming: [M3-7302] - Replace NodeBalancer detail charts with Recharts
  packages/manager/.changeset/pr-9983-upcoming-features-1702070124570.md
  packages/manager/src/components/AreaChart.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransferHistoryChart.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
Labels: Add'tl Approval Needed, Recharts

#9989 change: [M3-7446] - VLAN availability text on Linode Create
  packages/manager/.changeset/pr-9989-changed-1702494798508.md
  packages/manager/src/features/Linodes/LinodesCreate/AttachVLAN.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VLANAccordion.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VLANAccordion.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VLANAvailabilityNotice.tsx
Labels: Approved

#9994 refactor: [M3-7562] - Remove Radio.mdx and Textfield.mdx files
  packages/manager/.changeset/pr-9994-tech-stories-1702486520396.md
  packages/manager/src/components/Radio/Radio.mdx
  packages/manager/src/components/Radio/Radio.test.tsx
  packages/manager/src/components/Radio/Radio.tsx
  packages/manager/src/components/TextField.mdx
  packages/manager/src/components/TextField.test.tsx
  packages/manager/src/components/TextField.tsx
Labels: Storybook, Approved

#9978 refactor: Finish Remaining MUI Style Migration with codemod
  packages/manager/.changeset/pr-9978-tech-stories-1702564889256.md
  packages/manager/package.json
  packages/manager/src/GoTo.tsx
  packages/manager/src/LinodeThemeWrapper.tsx
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
  packages/manager/src/components/CheckoutSummary/SummaryItem.tsx
  packages/manager/src/components/CopyableAndDownloadableTextField.tsx
  packages/manager/src/components/DownloadTooltip.tsx
  packages/manager/src/components/EntityTable/EntityTableHeader.tsx
  packages/manager/src/components/EntityTable/types.ts
  packages/manager/src/components/Grid.tsx
  packages/manager/src/components/Grid/Grid.stories.tsx
  packages/manager/src/components/Grid/Grid.tsx
  packages/manager/src/components/Grid/index.ts
  packages/manager/src/components/GroupByTagToggle.tsx
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/LineGraph/MetricDisplay.styles.ts
  packages/manager/src/components/LineGraph/MetricsDisplay.test.tsx
  packages/manager/src/components/LineGraph/MetricsDisplay.tsx
  packages/manager/src/components/LinkButton.tsx
  packages/manager/src/components/MainContentBanner.tsx
  packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx
  packages/manager/src/components/RenderGuard.tsx
  packages/manager/src/components/VerticalLinearStepper/VerticalLinearStepper.tsx
  packages/manager/src/containers/SummaryPanels.styles.ts
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Help/Panels/PopularPosts.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeClusterSpecs.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeActionMenu.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeClusterDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/UpgradeVolumesDialog.tsx
  packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx
  packages/manager/src/features/Lish/Glish.tsx
  packages/manager/src/features/Lish/Weblish.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientInstructions.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.styles.ts
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
  packages/manager/src/features/TheApplicationIsOnFire.tsx
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  yarn.lock
Labels: Approved, Project: MUI v5 Migration, Needs extra approvals

#9987 feat: [M3-7526] - Add setHeader to GET /profile endpoint
  packages/api-v4/.changeset/pr-9987-added-1702566330400.md
  packages/api-v4/src/profile/profile.ts
  packages/manager/.changeset/pr-9987-upcoming-features-1702333742297.md
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/GlobalNotifications/EmailBounce.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/manager/src/hooks/useInitialRequests.ts
  packages/manager/src/queries/profile.ts
Labels: Parent / Child Account

#9982 refactor: [M3-7544, M3-7552] - ErrorState and FileUploader v7 stories
  packages/manager/.changeset/pr-9981-tech-stories-1702058586434.md
  packages/manager/src/cachedData/marketplace.json
  packages/manager/src/cachedData/regions.json
  packages/manager/src/cachedData/typesLegacy.json
  packages/manager/src/components/ErrorState/ErrorState.stories.mdx
  packages/manager/src/components/ErrorState/ErrorState.stories.tsx
  packages/manager/src/components/ErrorState/ErrorState.test.tsx
  packages/manager/src/components/ErrorState/ErrorState.tsx
  packages/manager/src/components/FileUploader/FileUploader.stories.mdx
  packages/manager/src/components/Uploaders/FileUpload.styles.ts
  packages/manager/src/components/Uploaders/FileUpload.tsx
  packages/manager/src/components/Uploaders/ImageUploader/ImageUploader.stories.tsx
  packages/manager/src/components/Uploaders/ImageUploader/ImageUploader.styles.ts
  packages/manager/src/components/Uploaders/ImageUploader/ImageUploader.test.tsx
  packages/manager/src/components/Uploaders/ImageUploader/ImageUploader.tsx
  packages/manager/src/components/Uploaders/ObjectUploader/ObjectUploader.stories.tsx
  packages/manager/src/components/Uploaders/ObjectUploader/ObjectUploader.styles.ts
  packages/manager/src/components/Uploaders/ObjectUploader/ObjectUploader.test.tsx
  packages/manager/src/components/Uploaders/ObjectUploader/ObjectUploader.tsx
  packages/manager/src/components/Uploaders/reducer.test.ts
  packages/manager/src/components/Uploaders/reducer.ts
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Managed/SSHAccess/LinodePubKey.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
Labels: Storybook, Approved

#10000 test: [M3-7464] - Add Cypress test FW landing page empty state
  packages/manager/.changeset/pr-10000-tests-1702591069388.md
  packages/manager/cypress/e2e/core/firewalls/landing-page-empty-state.spec.ts
Labels: Testing, Approved

#10007 refactor: [M3-7569] - Currency and DateTimeDisplay v7 Storybook migration
  packages/manager/.changeset/pr-10007-tech-stories-1702922152291.md
  packages/manager/src/components/Currency/Currency.stories.mdx
  packages/manager/src/components/Currency/Currency.stories.tsx
  packages/manager/src/components/Currency/Currency.test.tsx
  packages/manager/src/components/Currency/Currency.tsx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.stories.mdx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.stories.tsx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.test.tsx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.tsx
Labels: Storybook, Approved

#10004 test: [M3-7466] - Add integration test for Domains empty landing page
  packages/manager/.changeset/pr-10004-tests-1702676791962.md
  packages/manager/cypress/e2e/core/domains/domains-empty-landing-page.spec.ts
Labels: Testing, Approved

#9999 refactor: [M3-7547] - Graphs stories v7 migration
  packages/manager/.changeset/pr-9999-tech-stories-1702588492903.md
  packages/manager/.storybook/main.ts
  packages/manager/package.json
  packages/manager/src/components/GaugePercent/GaugePercent.stories.mdx
  packages/manager/src/components/GaugePercent/GaugePercent.stories.tsx
  packages/manager/src/components/GaugePercent/GaugePercent.test.tsx
  packages/manager/src/components/GaugePercent/GaugePercent.tsx
  packages/manager/src/components/LineGraph/LineGraph.stories.mdx
  packages/manager/src/components/LineGraph/LineGraph.stories.tsx
  packages/manager/src/components/LineGraph/LineGraph.test.tsx
  packages/manager/src/components/LineGraph/LineGraph.tsx
  yarn.lock
Labels: Storybook, Approved

#9992 upcoming, change: [M3-7524] - Add child_account OAuth scope to Create and View PAT drawers
  packages/manager/.changeset/pr-9992-changed-1703028128822.md
  packages/manager/.changeset/pr-9992-upcoming-features-1702939785550.md
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/utils.test.ts
  packages/manager/src/features/Profile/APITokens/utils.ts
Labels: Approved, Parent / Child Account

#10015 refactor: [M3-7575] CircleProgress and ColorPalette storybook v7 migrations
  packages/manager/.changeset/pr-10015-tech-stories-1703101491856.md
  packages/manager/src/components/CircleProgress/CircleProgress.stories.mdx
  packages/manager/src/components/CircleProgress/CircleProgress.stories.tsx
  packages/manager/src/components/CircleProgress/CircleProgress.test.tsx
  packages/manager/src/components/CircleProgress/CircleProgress.tsx
  packages/manager/src/components/ColorPalette/ColorPalette.stories.mdx
  packages/manager/src/components/ColorPalette/ColorPalette.stories.tsx
  packages/manager/src/components/ColorPalette/ColorPalette.test.tsx
  packages/manager/src/components/ColorPalette/ColorPalette.tsx
Labels: Storybook, Approved

#10011 change: [M3-7461] - Update toast notifications for UserPermissions
  packages/manager/.changeset/pr-10011-changed-1703028750129.md
  packages/manager/src/features/Users/UserPermissions.tsx
Labels: Approved, Parent / Child Account

#10009 test: [M3-7484] - Add Cypress integration tests for User Permissions page
  packages/manager/.changeset/pr-10009-fixed-1703009466518.md
  packages/manager/.changeset/pr-10009-tests-1703009412715.md
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/cypress/support/constants/user-permissions.ts
  packages/manager/cypress/support/intercepts/account.ts
  packages/manager/cypress/support/util/arrays.ts
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
Labels: Testing, Approved, Parent / Child Account

#10017 refactor: [M3-7576] - DebouncedSearchTextfield and EditableText v7 storybook migrations
  packages/manager/.changeset/pr-10017-tech-stories-1703176302247.md
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.stories.mdx
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.stories.tsx
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextfield.test.tsx
  packages/manager/src/components/DebouncedSearchTextField/StoryComponents/TextFieldExample.tsx
  packages/manager/src/components/EditableText/EditableText.stories.mdx
  packages/manager/src/components/EditableText/EditableText.stories.tsx
  packages/manager/src/components/EditableText/EditableText.test.tsx
  packages/manager/src/components/EditableText/EditableText.tsx
Labels: Storybook, Approved

#10005 change: [M3-7454] - Add child access user permissions for parent accounts
  packages/manager/.changeset/pr-10005-changed-1702679066439.md
  packages/manager/.changeset/pr-10005-upcoming-features-1703273545929.md
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/src/features/Users/UserDetail.tsx
  packages/manager/src/features/Users/UserPermissions.styles.ts
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Parent / Child Account

#9993 change: [M3-7225] - Filter out already assigned services in firewall drawers
  packages/api-v4/src/firewalls/types.ts
  packages/manager/.changeset/pr-9993-changed-1702418666735.md
  packages/manager/src/__data__/firewalls.ts
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/factories/firewalls.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddLinodeDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallDialog.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.test.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerSelect.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerSelect.tsx
Labels: Add'tl Approval Needed, Nodebalancer Firewall UX
