Repository linode/manager, pull requests merged in 2023-01, with the labels that each got.

#8683 Gravatar Clean Up
  packages/api-v4/src/account/types.ts
  packages/manager/src/components/GravatarByEmail.tsx
  packages/manager/src/components/GravatarByUsername.tsx
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/Profile/DisplaySettings/GravatarIcon.tsx
  packages/manager/src/features/Support/ExpandableTicketPanel.test.tsx
  packages/manager/src/features/Support/ExpandableTicketPanel.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
  packages/manager/src/features/Support/types.ts
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/Users/UsersLanding.tsx
  packages/manager/src/queries/account.ts
  packages/manager/src/queries/accountUsers.ts
  packages/manager/src/themeFactory.ts
  packages/manager/src/utilities/gravatar.ts
Labels: Enhancement

#8708 `staging` → `master` for v1.83.1
  CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/linodes/index.tsx
Labels: Release

#8716 M3-6066: Fix `api-v4` and `validation` Node Errors
  packages/validation/src/firewalls.schema.ts
  packages/validation/src/linodes.schema.ts
Labels: Bug

#8717 M3-6068: Incorrect tab selection on Linode Create
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
Labels: Bug

#8719 M3-6064: Deploying a Linode Backup to a new Linode forces a different plan size to be chosen
  packages/manager/src/features/linodes/LinodesCreate/SelectLinodePanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
Labels: Bug

#8720 Fix Linodes Detail Showing Past Maintenance Events
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx
  packages/manager/src/queries/accountMaintenance.ts
Labels: Bug

#8721 M3-6069: Fix NodeBalanacer Mode Change Select
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
Labels: Bug

#8727 Fix Linodes Landing Extra Padding
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
Labels: UI

#8731 Switch `require`s to `import`s for `highlight.js` Languages
  packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.tsx
Labels: Build and Organization

#8729 M3-6067: Linode Create - API/CLI Copy Changes
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
Labels: API/CLI Project

#8730 Use `@types/react-csv` for `react-csv`
  packages/manager/package.json
  packages/manager/src/types/index.ts
  yarn.lock
Labels: dependencies

#8739 M3-6135: Fix `api-v4` and `validation` CommonJS not accepted by Node.js
  packages/api-v4/README.md
  packages/api-v4/package.json
  packages/api-v4/tsup.config.ts
  packages/manager/package.json
  packages/validation/package.json
  packages/validation/tsup.config.ts
Labels: Build and Organization, Bug

#8725 M3 6047: Code block component Part 1 & 2
  packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.test.tsx
  packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.tsx
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
  packages/manager/src/features/linodes/LinodesCreate/CodeBlock/index.tsx
  packages/manager/src/features/linodes/LinodesCreate/CodeBlock/styles.ts
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
Labels: API/CLI Project

#8710 M3-6046: dynamically generate cURL and CLI commands
  packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
  packages/manager/src/features/linodes/LinodesCreate/CodeBlock/styles.ts
  packages/manager/src/utilities/generate-cURL.test.ts
  packages/manager/src/utilities/generate-cURL.ts
  packages/manager/src/utilities/generate-cli.test.ts
  packages/manager/src/utilities/generate-cli.ts
Labels: API/CLI Project

#8673 M3-5182: RQ-ify Images, Pt. 2
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/containers/images.container.tsx
  packages/manager/src/containers/withImages.container.ts
  packages/manager/src/features/Images/ImageSelect.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Images/utils.ts
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/useAPISearch.tsx
  packages/manager/src/features/Search/withStoreSearch.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.test.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/features/StackScripts/StackScriptsLanding.test.tsx
  packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.container.tsx
  packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/linodes/LinodesLanding/index.tsx
  packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
  packages/manager/src/hooks/useEntities.ts
  packages/manager/src/hooks/useImages.test.tsx
  packages/manager/src/hooks/useImages.ts
  packages/manager/src/hooks/useReduxLoad.ts
  packages/manager/src/queries/images.ts
Labels: React Query

#8695 M3-5717: Storybook patterns
  docs/development-guide/04-component-library.md
  packages/manager/src/components/Accordion/Accordion.stories.mdx
  packages/manager/src/components/ActionMenu/ActionMenu.stories.mdx
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/components/BarPercent/BarPercent.stories.mdx
  packages/manager/src/components/BetaChip/BetaChip.stories.mdx
  packages/manager/src/components/BetaChip/BetaChip.tsx
  packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
  packages/manager/src/components/Button/Button.stories.mdx
  packages/manager/src/components/CheckBox/CheckBox.stories.mdx
  packages/manager/src/components/Chip.stories.mdx
  packages/manager/src/components/CircleProgress/CircleProgress.stories.mdx
  packages/manager/src/components/CopyTooltip/CopyTooltip.stories.mdx
  packages/manager/src/components/Currency/Currency.stories.mdx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.stories.mdx
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.stories.mdx
  packages/manager/src/components/Dialog/Dialog.stories.mdx
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.stories.mdx
  packages/manager/src/components/DocsLink/DocsLink.stories.mdx
  packages/manager/src/components/Drawer/Drawer.stories.mdx
  packages/manager/src/components/EditableText/EditableText.stories.mdx
  packages/manager/src/components/EditableText/EditableText.stories.tsx
  packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.stories.mdx
  packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
  packages/manager/src/components/ErrorState/ErrorState.stories.mdx
  packages/manager/src/components/ExternalLink/ExternalLink.stories.mdx
  packages/manager/src/components/FileUploader/FileUploader.stories.mdx
  packages/manager/src/components/GaugePercent/GaugePercent.stories.mdx
  packages/manager/src/components/HelpIcon/HelpIcon.stories.mdx
  packages/manager/src/components/LineGraph/LineGraph.stories.mdx
  packages/manager/src/components/LinearProgress/LinearProgress.stories.mdx
  packages/manager/src/components/Link.stories.mdx
  packages/manager/src/components/PaginationControls/PaginationControls.stories.mdx
  packages/manager/src/components/PaginationControls/PaginationControls.stories.tsx
  packages/manager/src/components/Paper.stories.mdx
  packages/manager/src/components/PasswordInput/PasswordInput.stories.mdx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.mdx
  packages/manager/src/components/Radio/Radio.stories.mdx
  packages/manager/src/components/SelectionCard/SelectionCard.stories.mdx
  packages/manager/src/components/ShowMoreExpansion/ShowMoreExpansion.stories.mdx
  packages/manager/src/components/SideMenu.stories.mdx
  packages/manager/src/components/StatusIcon/StatusIcon.stories.mdx
  packages/manager/src/components/TableRowEmptyState/TableRowEmptyState.stories.mdx
  packages/manager/src/components/TableRowError/TableRowError.stories.mdx
  packages/manager/src/components/TableRowLoading/TableRowLoading.stories.mdx
  packages/manager/src/components/Tag/Tag.stories.mdx
  packages/manager/src/components/Tags/Tags.stories.mdx
  packages/manager/src/components/TagsPanel/TagsPanel.stories.mdx
  packages/manager/src/components/TextField.stories.mdx
  packages/manager/src/components/Toggle/Toggle.stories.mdx
  packages/manager/src/components/TopMenu.stories.mdx
  packages/manager/src/components/Typography.stories.mdx
  packages/manager/src/components/UserMenu.stories.mdx
  packages/manager/src/features/ToastNotifications/ToastNotifications.stories.mdx
Labels: Storybook
