Repository linode/manager, pull requests merged in 2023-03, with the labels that each got.

#8822 refactor: [M3-5182] –`feature/react-query-images` --> `develop`
  packages/manager/src/App.tsx
  packages/manager/src/components/EntityTable/EntityTable.stories.mdx
  packages/manager/src/components/FileUploader/FileUploader.tsx
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/containers/images.container.tsx
  packages/manager/src/containers/withImage.container.ts
  packages/manager/src/containers/withImages.container.ts
  packages/manager/src/features/Images/ImageSelect.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/Images/utils.ts
  packages/manager/src/features/Search/SearchLanding.test.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/useAPISearch.tsx
  packages/manager/src/features/Search/withStoreSearch.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.test.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/features/StackScripts/StackScriptsLanding.test.tsx
  packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.container.tsx
  packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/linodes/LinodesLanding/index.tsx
  packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.tsx
  packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
  packages/manager/src/hooks/useEntities.ts
  packages/manager/src/hooks/useImages.test.tsx
  packages/manager/src/hooks/useImages.ts
  packages/manager/src/hooks/useReduxLoad.ts
  packages/manager/src/queries/base.ts
  packages/manager/src/queries/images.ts
  packages/manager/src/store/image/image.actions.ts
  packages/manager/src/store/image/image.reducer.test.ts
  packages/manager/src/store/image/image.reducer.ts
  packages/manager/src/store/image/image.requests.ts
  packages/manager/src/store/index.ts
  packages/manager/src/store/middleware/imageEvents.ts
  packages/manager/src/store/selectors/entitiesErrors.ts
  packages/manager/src/store/selectors/entitiesLoading.ts
  packages/manager/src/store/selectors/getSearchEntities.test.ts
  packages/manager/src/store/selectors/getSearchEntities.ts
  packages/manager/src/utilities/getEntityByIDFromStore.ts
Labels: React Query

#8833 fix: Cypress React Query Images improvements
  packages/manager/cypress/e2e/images/smoke-create-image.spec.ts
Labels: e2e

#8835 fix: Improve Cypress Managed SSH Test Flake
  packages/manager/cypress/e2e/managed/managed-ssh.spec.ts
  packages/manager/cypress/support/api/managed.ts
Labels: e2e, Approved

#8827 feat: [M3-6160] - Add resource links to Kubernetes empty state landing page
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLandingEmptyState.tsx
  packages/manager/src/features/linodes/LinodesLanding/AppsSection.tsx
  packages/manager/src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx
  packages/manager/src/utilities/emptyStateLandingUtils.ts
Labels: Approved, Question

#8819 feat: [M3-6147] - Add warning for invalid user data
  packages/manager/src/features/linodes/UserDataAccordion.tsx
Labels: Project: Metadata, Approved

#8837 fix: [M3-6166] - Revert select changes to logo brand update
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
Labels: Bug, Ready for Review

#8836 test: [M3-6168] - Added Service Transfer E2E test for Managed users
  packages/manager/cypress/e2e/account/service-transfer.spec.ts
  packages/manager/cypress/support/intercepts/account.ts
Labels: e2e, Ready for Review

#8841 docs: Add event handler naming convention section
  docs/development-guide/13-coding-standards.md
Labels: Documentation

#8845 fix: Removed development branch and reverted to master
  .github/workflows/ci.yml
Labels: Bug

#8839 fix: [M3-6216] - Cluster search regression
  packages/manager/src/features/OneClickApps/FakeSpec.ts
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
Labels: Bug, Project: One Click Clusters

#8847 change: [M3-6218] - Temporarily change Remit To invoice address
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
Labels: Approved

#8852 refactor: [M3-6228] - Use Mock Linode Data for Managed Service Transfer Test
  packages/manager/cypress/e2e/account/service-transfer.spec.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: e2e, Approved

#8849 test: [M3-5952] - Object Storage object upload, access, delete tests
  packages/manager/cypress/e2e/objectStorage/object-storage.e2e.spec.ts
  packages/manager/cypress/support/intercepts/object-storage.ts
Labels: e2e, Approved

#8828 refactor: [M3-5800] - Improve notification event links
  packages/manager/src/eventMessageGenerator.ts
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useEventInfo.ts
  packages/manager/src/utilities/getEventsActionLink.ts
Labels: Approved

#8854 refactor: Use `yarn start:manager:ci` for GitHub Actions E2E workflows
  .github/workflows/e2e_schedule_and_push.yml
Labels: e2e

#8826 fix: [M3-6178] - Disable/hide showAll for PaginationFooter
  packages/manager/src/components/EntityTable/GroupedEntitiesByTag.tsx
  packages/manager/src/features/Domains/DomainRecords.tsx
  packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/hooks/useInfinitePageSize.ts
Labels: Approved, Ready for Review

#8860 deps: [M3-6230] - Remove unused packages + update lint-staged
  package.json
  packages/api-v4/package.json
  packages/manager/package.json
  packages/manager/src/assets/weblish/weblish.css
  packages/validation/package.json
  yarn.lock
Labels: Dependencies, Approved

#8850 feat: [M3-6146] - Add User Data to Linode Rebuild flow
  packages/api-v4/src/linodes/types.ts
  packages/manager/src/components/CheckBox/CheckBox.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.styles.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/linodes/UserDataAccordion.styles.ts
  packages/manager/src/features/linodes/UserDataAccordion.test.tsx
  packages/manager/src/features/linodes/UserDataAccordion.tsx
  packages/validation/src/linodes.schema.ts
Labels: Project: Metadata, Requires Changes

#8863 build(dep): M3-6231: Update Typescript to latest (`4.9.5`)
  package.json
  packages/api-v4/src/request.ts
  packages/manager/src/components/AddNewLink/AddNewLink.tsx
  packages/manager/src/features/Longview/shared/utilities.ts
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/reducer.test.ts
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedMultiSelect.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueContainer.test.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/reloadableWithRouter.tsx
  packages/manager/src/store/longviewStats/longviewStats.actions.ts
  packages/manager/src/store/longviewStats/longviewStats.reducer.ts
  packages/manager/src/store/selectors/entitiesErrors.ts
  packages/manager/src/store/selectors/entitiesLoading.ts
  packages/manager/src/store/selectors/getSearchEntities.ts
  packages/manager/src/store/selectors/imageEvents.ts
  packages/manager/src/store/selectors/inProgressEventForLinode.ts
  packages/manager/src/store/selectors/inProgressEvents.ts
  packages/manager/src/store/selectors/recentEventForLinode.ts
  packages/manager/src/utilities/createDevicesFromStrings/createDevicesFromStrings.ts
  packages/manager/src/utilities/downloadFile.ts
  yarn.lock
Labels: Dependencies, Ready for Review

#8866 chore: [M3-6210] - Update Cypress recommended Node version message
  packages/manager/cypress.config.ts
Labels: e2e

#8871 fix: [M3-6235] - Fix Radio Styles after Vite Upgrade
  packages/manager/src/components/Radio/Radio.tsx
Labels: Bug, UI, Ready for Review

#8869 feat: Allow users to select `system` as a theme option
  packages/manager/src/App.tsx
  packages/manager/src/LinodeThemeWrapper.tsx
  packages/manager/src/components/ColorPalette/ColorPalette.stories.mdx
  packages/manager/src/components/CopyableAndDownloadableTextField.tsx
  packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
  packages/manager/src/components/ExternalLink/ExternalLink.tsx
  packages/manager/src/components/Placeholder/Placeholder.tsx
  packages/manager/src/components/Tag/Tag.tsx
  packages/manager/src/components/core/Divider.tsx
  packages/manager/src/components/core/ReachTabList.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
  packages/manager/src/features/Profile/Referrals/Referrals.tsx
  packages/manager/src/features/Profile/Settings/Settings.tsx
  packages/manager/src/features/Profile/Settings/ThemeToggle.test.tsx
  packages/manager/src/features/Profile/Settings/ThemeToggle.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/MarkdownReference.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/TopMenu/UserNotificationsMenu/UserNotificationsMenu.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx
  packages/manager/src/features/linodes/LinodesLanding/AppsSection.tsx
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
  packages/manager/src/types/ManagerPreferences.ts
  packages/manager/src/utilities/theme.test.ts
  packages/manager/src/utilities/theme.ts
Labels: Enhancement, Ready for Review

#8870 chore: [M3-6227] - Clean up Cypress Volumes test intercepts
  packages/manager/cypress/e2e/account/security-questions.spec.ts
  packages/manager/cypress/e2e/account/sms-verification.spec.ts
  packages/manager/cypress/e2e/databases/delete-database.spec.ts
  packages/manager/cypress/e2e/databases/update-database.spec.ts
  packages/manager/cypress/e2e/linodes/backup-linode.spec.ts
  packages/manager/cypress/e2e/linodes/clone-linode.spec.ts
  packages/manager/cypress/e2e/linodes/create-linode.spec.ts
  packages/manager/cypress/e2e/volumes/attach-volume.spec.ts
  packages/manager/cypress/e2e/volumes/clone-volume.spec.ts
  packages/manager/cypress/e2e/volumes/create-volume.smoke.spec.ts
  packages/manager/cypress/e2e/volumes/create-volume.spec.ts
  packages/manager/cypress/e2e/volumes/delete-volume.spec.ts
  packages/manager/cypress/e2e/volumes/resize-volume.spec.ts
  packages/manager/cypress/support/intercepts/linodes.ts
  packages/manager/cypress/support/intercepts/volumes.ts
  packages/manager/cypress/support/ui/events.ts
Labels: e2e

#8868 docs: Update styles coding standards to reflect FE Cafe consensus
  docs/development-guide/02-component-structure.md
  docs/development-guide/13-coding-standards.md
Labels: Approved, Documentation

#8874 fix: [M3-6141] - Use our custom dialog instead of MUI's
  packages/manager/src/components/TransferDisplay/TransferDisplay.tsx
Labels: Bug, Approved, Ready for Review

#8881 fix: Use Jenkins build number for Cypress unique build ID
  docker-compose.yml
Labels: e2e, Approved

#8856 refactor: [M3-4876] - LandingHeader & EntityHeader Refactor
  packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
  packages/manager/src/components/DocsLink/DocsLink.tsx
  packages/manager/src/components/EditableText/EditableText.tsx
  packages/manager/src/components/EntityHeader/EntityHeader.stories.tsx
  packages/manager/src/components/EntityHeader/EntityHeader.tsx
  packages/manager/src/components/EntityHeader/HeaderBreadCrumb.tsx
  packages/manager/src/components/IconTextLink/IconTextLink.tsx
  packages/manager/src/components/LandingHeader/LandingHeader.stories.tsx
  packages/manager/src/components/LandingHeader/LandingHeader.test.tsx
  packages/manager/src/components/LandingHeader/LandingHeader.tsx
  packages/manager/src/constants.ts
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/EntityTransfersCreate.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageCreateContainer.tsx
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.test.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
  packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.test.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
  packages/manager/src/features/Users/UserDetail.tsx
  packages/manager/src/features/Volumes/VolumeCreate/VolumeCreate.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailsBreadcrumb.tsx
  packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/themeFactory.ts
Labels: Enhancement, Approved, Under Review

#8872 refactor: [M3-5196] - Remove vlans from redux
  packages/manager/src/containers/vlans.container.ts
  packages/manager/src/features/linodes/LinodesCreate/SelectVLAN.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/hooks/useReduxLoad.ts
  packages/manager/src/hooks/useVlans.ts
  packages/manager/src/queries/vlans.ts
  packages/manager/src/store/index.ts
  packages/manager/src/store/vlans/vlans.actions.ts
  packages/manager/src/store/vlans/vlans.reducer.ts
  packages/manager/src/store/vlans/vlans.requests.ts
Labels: React Query, Approved

#8876 refactor: Infinitely Loaded Entity Select
  packages/manager/src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/VolumeSelect.tsx
  packages/manager/src/queries/volumes.ts
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
Labels: React Query, Approved, Under Review

#8842 docs: [M3-6206] - Add commit standards to docs
  docs/CONTRIBUTING.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: Approved, Documentation

#8887 fix: Region in e2e tests for region `Tokyo, JP`
  packages/manager/cypress/support/constants/regions.ts
Labels: e2e, Approved

#8886 style: Final One Click Clusters Updates
  packages/manager/public/assets/galera.svg
  packages/manager/public/assets/white/galera.svg
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
  packages/manager/src/features/OneClickApps/FakeSpec.ts
  packages/manager/src/features/linodes/LinodesCreate/AppPanelSection.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectAppPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx
  packages/manager/src/features/linodes/LinodesCreate/utilities.test.ts
  packages/manager/src/features/linodes/LinodesCreate/utilities.tsx
Labels: Project: One Click Clusters

#8861 feat: [M3-6159] - Improve Linode disk downsize error messaging
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/Code/Code.tsx
  packages/manager/src/components/Code/index.ts
  packages/manager/src/components/FormHelperText/FormHelperText.tsx
  packages/manager/src/components/FormHelperText/index.ts
  packages/manager/src/components/HelpIcon/HelpIcon.tsx
  packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx
  packages/manager/src/components/TextTooltip/TextTooltip.tsx
  packages/manager/src/eventMessageGenerator.ts
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Events/Event.helpers.test.ts
  packages/manager/src/features/Events/Event.helpers.ts
  packages/manager/src/features/Events/EventRow.test.tsx
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useEventInfo.ts
  packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskActionMenu.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivityRow.tsx
Labels: Approved, Under Review

#8878 feat: [M3-5982] - One Click Clusters
  packages/manager/public/assets/galera.svg
  packages/manager/public/assets/white/galera.svg
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
  packages/manager/src/components/HelpIcon/HelpIcon.tsx
  packages/manager/src/components/PasswordInput/HideShowText.tsx
  packages/manager/src/components/PasswordInput/PasswordInput.tsx
  packages/manager/src/components/SelectionCard/CardBase.test.tsx
  packages/manager/src/components/SelectionCard/CardBase.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/documentation.ts
  packages/manager/src/features/OneClickApps/AppDetailDrawer.test.tsx
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
  packages/manager/src/features/OneClickApps/FakeSpec.ts
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.test.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/LabelField.tsx
  packages/manager/src/features/linodes/LinodesCreate/AppPanelSection.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectAppPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
  packages/manager/src/features/linodes/LinodesCreate/types.ts
  packages/manager/src/features/linodes/LinodesCreate/utilities.test.ts
  packages/manager/src/features/linodes/LinodesCreate/utilities.tsx
Labels: Project: One Click Clusters, Under Review

#8893 refactor: [M3-6241] - MUI v5 Migration - Features > Account
  packages/manager/package.json
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/AccountLogins.tsx
  packages/manager/src/features/Account/Agreements/EUAgreementCheckbox.tsx
  packages/manager/src/features/Account/Agreements/withAgreements.ts
  packages/manager/src/features/Account/AutoBackups.tsx
  packages/manager/src/features/Account/CloseAccountDialog.tsx
  packages/manager/src/features/Account/CloseAccountSetting.tsx
  packages/manager/src/features/Account/EnableManaged.tsx
  packages/manager/src/features/Account/EnableObjectStorage.tsx
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Account/ImportGroupsAsTags.test.tsx
  packages/manager/src/features/Account/ImportGroupsAsTags.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
  packages/manager/src/features/Account/NetworkHelper.tsx
  yarn.lock
Labels: Ready for Review, Project: MUI v5 Migration

#8884 fix: [M3-6204] - Add Cypress clean-up for service transfer requests
  packages/manager/cypress/support/api/entityTransfer.ts
  packages/manager/cypress/support/ui/common.ts
Labels: e2e, Approved

#8895 refactor: [M3-6245] - MUI v5 Migration - Features > Billing
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/components/SupportError.tsx
  packages/manager/src/components/core/Paper.tsx
  packages/manager/src/features/Billing/BillingDetail.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/Paypal.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PromoDialog.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/EditBillingContactDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentMethods.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
Labels: Add'tl Approval Needed, Ready for Review, Project: MUI v5 Migration

#8890 feat: [M3-5746] - Disable Download CA Certificate when DB is provisioning
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Labels: Project: DBaaS, Approved

#8888 fix: [M3-6254] - Show warning message for only Linode clone and backups
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/AccordionHeading.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
Labels: Project: Metadata, Approved, Ready for Review

#8896 refactor: [M3-6261] - MUI v5 Migration - `Features > Databases`
  packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupActionMenu.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMenuItem.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/features/Databases/index.tsx
Labels: Ready for Review, Project: MUI v5 Migration

#8904 fix: [M3-6426] - Fix NodeBalancer Configurations not saving
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
Labels: Bug

#8905 refactor: [M3-6290] - MUI v5 Migration - `Components > Accordion`
  packages/manager/src/components/Accordion/Accordion.tsx
Labels: Ready for Review, Project: MUI v5 Migration

#8911 feat: [M3-6142] - Metadata
  packages/api-v4/src/images/images.ts
  packages/api-v4/src/images/types.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/src/components/CheckBox/CheckBox.tsx
  packages/manager/src/components/FileUploader/FileUploader.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/factories/images.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/AcceptedFormats.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.styles.ts
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataExplanatory.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.styles.ts
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/images.ts
  packages/manager/vite.config.js
  packages/manager/vite.config.js.map
  packages/validation/src/images.schema.ts
  packages/validation/src/linodes.schema.ts
  yarn.lock
Labels: Project: Metadata, Ready for Review

#8918 fix: `service-transfer.spec.ts` test failures
  packages/manager/cypress/e2e/account/service-transfer.spec.ts
  packages/manager/src/components/Accordion/Accordion.tsx
Labels: e2e, Approved

#8908 refactor: [M3-6327, M3-6328] - MUI v5 Migration - Components > Drawer, DrawerContent
  packages/manager/src/components/Drawer/Drawer.tsx
  packages/manager/src/components/DrawerContent/DrawerContent.test.tsx
  packages/manager/src/components/DrawerContent/DrawerContent.tsx
Labels: Approved, Project: MUI v5 Migration

#8925 fix: [M3-4876] - Update incorrect headline
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
Labels: Bug, Approved, Ready for Review

#8906 feat: [M3-6072] - New tab for plans table
  packages/api-v4/src/linodes/types.ts
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Labels: Approved, Ready for Review

#8907 chore: Repo Clean Up - Remove Old Redux Docs
  packages/manager/src/components/DocsSidebar/DocComponent.tsx
  packages/manager/src/components/DocsSidebar/DocsSidebar.tsx
  packages/manager/src/components/DocsSidebar/index.ts
  packages/manager/src/components/DocsSidebar/setDocs.tsx
  packages/manager/src/documentation.ts
  packages/manager/src/features/Billing/BillingDetail.test.tsx
  packages/manager/src/features/Billing/BillingDetail.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
  packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.test.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.test.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.test.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Ready for Review

#8931 staging → master for v1.89.1
  CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
Labels: Release

#8928 feat: [M3-6072] - New tab for plans table (#8906)
  packages/api-v4/src/linodes/types.ts
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Labels: Approved

#8926 refactor: [M3-6387] - MUI v5 Migration - Components > SelectionCard
  packages/manager/src/components/SelectionCard/CardBase.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx
  packages/manager/src/styles/keyframes.ts
Labels: Approved, Ready for Review, Project: MUI v5 Migration

#8912 fix: [M3-6433] - Fix crash for Events with a `null` community post `entity`
  packages/manager/src/eventMessageGenerator.ts
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/utilities/getEventsActionLink.ts
Labels: Bug, Approved, Ready for Review

#8930 refactor: [M3-6291, M3-6292] – MUI v5 Migration - `Components > AccountActivation`, `Components > ActionMenu`
  packages/manager/src/components/AccountActivation/AccountActivationError.tsx
  packages/manager/src/components/AccountActivation/AccountActivationLanding.tsx
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
Labels: Project: MUI v5 Migration

#8915 refactor: [M3-6436] - React Query for Notifications
  packages/manager/src/App.tsx
  packages/manager/src/components/AbuseTicketBanner/AbuseTicketBanner.test.tsx
  packages/manager/src/components/AbuseTicketBanner/AbuseTicketBanner.tsx
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
  packages/manager/src/components/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/EditBillingContactDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/GlobalNotifications/ComplianceBanner.tsx
  packages/manager/src/features/GlobalNotifications/ComplianceUpdateModal.tsx
  packages/manager/src/features/GlobalNotifications/EmailBounce.test.tsx
  packages/manager/src/features/GlobalNotifications/EmailBounce.tsx
  packages/manager/src/features/NotificationCenter/Events.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/index.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useNotificationData.tsx
  packages/manager/src/features/NotificationCenter/Notifications.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/TopMenu/NotificationButton.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/UpgradeVolumesDialog.tsx
  packages/manager/src/features/linodes/LinodesDetail/types.ts
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/linodes/LinodesLanding/withNotifications.ts
  packages/manager/src/features/linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/hooks/useExtendedLinode.ts
  packages/manager/src/hooks/useNotifications.ts
  packages/manager/src/hooks/useReduxLoad.ts
  packages/manager/src/queries/account.ts
  packages/manager/src/queries/accountNotifications.ts
  packages/manager/src/store/index.ts
  packages/manager/src/store/linodes/linode.events.test.ts
  packages/manager/src/store/linodes/linodes.events.ts
  packages/manager/src/store/notification/notification.actions.ts
  packages/manager/src/store/notification/notification.containers.ts
  packages/manager/src/store/notification/notification.reducer.ts
  packages/manager/src/store/notification/notification.requests.ts
  packages/manager/src/store/notification/notification.selector.ts
  packages/manager/src/store/selectors/getAbuseTicket.ts
  packages/manager/src/store/selectors/index.ts
Labels: Add'tl Approval Needed, React Query, Ready for Review

#8897 perf: Decrease bundle size for largest assets > 100kb
  packages/manager/package.json
  packages/manager/src/components/CopyableAndDownloadableTextField.tsx
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
Labels: Proof of Concept, Ready for Review, Performance

#8919 refactor: [M3-6323, M3-6339, M3-6348] - MUI v5 Migration - Components > DocsLink, ExternalLink, IconTextLink
  packages/manager/src/components/DocsLink/DocsLink.tsx
  packages/manager/src/components/ExternalLink/ExternalLink.tsx
  packages/manager/src/components/IconTextLink/IconTextLink.tsx
Labels: Approved, Project: MUI v5 Migration

#8934 fix: Linode Details Notifications showing all notifications
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx
Labels: Bug

#8927 style: Update OCC logos to include naming convention
  packages/manager/public/assets/galeramarketplaceocc.svg
  packages/manager/public/assets/mongodbmarketplaceocc.svg
  packages/manager/public/assets/postgresqlmarketplaceocc.svg
  packages/manager/public/assets/redissentinelmarketplaceocc.svg
  packages/manager/public/assets/white/galeramarketplaceocc.svg
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
  packages/manager/src/features/OneClickApps/FakeSpec.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
Labels: Project: One Click Clusters

#8913 refactor: [M3-6288, M3-6289] - MUI v5 Migration - `Components > AbuseTicketBanner`, `Components > AccessPanel`
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
Labels: Add'tl Approval Needed, Project: MUI v5 Migration

#8909 fix: [M3-6429] - Fix Tag drawer in LinodesLanding summary view
  packages/manager/src/components/EntityTable/EntityTable.tsx
  packages/manager/src/components/EntityTable/EntityTableHeader.tsx
  packages/manager/src/components/EntityTable/types.ts
  packages/manager/src/components/OrderBy.tsx
  packages/manager/src/features/Domains/DomainsTableWrapper.tsx
  packages/manager/src/features/Domains/SortableTableHead.tsx
  packages/manager/src/features/Volumes/SortableVolumesTableHeader.tsx
  packages/manager/src/features/Volumes/VolumeTableWrapper.tsx
  packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
  packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/linodes/LinodesLanding/ListView.tsx
  packages/manager/src/features/linodes/LinodesLanding/SortableTableHead.tsx
  packages/manager/src/features/linodes/LinodesLanding/TableWrapper.tsx
  packages/manager/src/features/linodes/index.tsx
  packages/manager/src/hooks/useExtendedLinode.ts
  packages/manager/src/store/linodes/types.ts
Labels: Add'tl Approval Needed, Bug

#8923 feat: [M3-6431] - Adjust Accordion arrow to be in line with title
  packages/manager/src/components/Accordion/Accordion.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.styles.ts
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
Labels: Project: Metadata, Ready for Review

#8939 fix: [M3-6387] - MUI v5 Migration - Components > SelectionCard & ActionsPanel
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/components/SelectionCard/CardBase.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
  packages/manager/src/features/LinodeConfigSelectionDrawer/LinodeConfigSelectionDrawer.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/linodes/LinodesCreate/AppPanelSection.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectLinodePanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx
Labels: Ready for Review

#8945 docs: [M3-6451] - Add change as a commit type and update refactor definition
  docs/CONTRIBUTING.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: Ready for Review, Documentation

#8947 fix: [M3-6453] - Filtering by `Status` on Linode Details Volumes Table
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx
Labels: Bug, Urgent

#8940 chore: Repo Clean Up
  packages/manager/src/App.test.tsx
  packages/manager/src/App.tsx
  packages/manager/src/constants.ts
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.test.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/Paypal.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
  packages/manager/src/store/documentation/index.ts
  packages/manager/src/store/index.ts
  packages/manager/src/types/Documentation.ts
  packages/manager/src/types/Paypal.ts
  packages/manager/vite.config.js
  packages/manager/vite.config.js.map
Labels: Approved, Ready for Review

#8941 perf: Only fetch `/v4/profile/grants` if a user is `restricted`
  packages/manager/src/queries/profile.ts
Labels: Enhancement, React Query, Approved

#8943 chore:[M3-6313] - Add column head to Plan Name
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Labels: Ready for Review
