Repository linode/manager, pull requests merged in 2023-04, with the labels that each got.

#8946 docs: [M3-6452] - Update Docs for JSX element naming convention
  docs/development-guide/02-component-structure.md
Labels: Approved, Documentation

#8954 master -> develop following release of Cloud v1.90.0
  CHANGELOG.md
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/manager/package.json
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Release

#8900 refactor: [M3-5945] - Parameterize DBaaS tests for multiple engines
  packages/manager/cypress/e2e/databases/create-database.spec.ts
  packages/manager/cypress/e2e/databases/delete-database.spec.ts
  packages/manager/cypress/e2e/databases/update-database.spec.ts
  packages/manager/cypress/support/constants/databases.ts
Labels: e2e, Approved

#8933 refactor: [M3-6437] - MUI v5 Migration - Features > Billing
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
  packages/manager/src/components/Grid/Grid.stories.mdx
  packages/manager/src/components/Grid/Grid.stories.tsx
  packages/manager/src/components/HelpIcon/HelpIcon.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/features/Billing/BillingDetail.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PromoDisplay.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentMethods.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
Labels: Add'tl Approval Needed, Ready for Review, Project: MUI v5 Migration

#8921 feat: Add Metadata region capability
  packages/api-v4/src/regions/types.ts
  packages/manager/src/cachedData/regions.json
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Project: Metadata, Ready for Review

#8902 fix: [M3-6001] - Fix notification menu displaying empty menu on secondary status click
  packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/NotificationMenu/.NotificationMenu.stories.mdx
  packages/manager/src/components/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/components/NotificationMenu/index.ts
  packages/manager/src/components/core/Paper.tsx
  packages/manager/src/features/NotificationCenter/NotificationContext.ts
  packages/manager/src/features/NotificationCenter/NotificationSection.tsx
  packages/manager/src/features/NotificationCenter/index.tsx
  packages/manager/src/features/TopMenu/Community.tsx
  packages/manager/src/features/TopMenu/Help.tsx
  packages/manager/src/features/TopMenu/NotificationButton.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/index.ts
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/features/TopMenu/TopMenuIcon.tsx
  packages/manager/src/features/TopMenu/iconStyles.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Bug

#8960 refactor: [M3-6295] - MUI v5 Migration - `Components > BackupStatus`
  packages/manager/src/components/BackupStatus/BackupStatus.tsx
  packages/manager/src/components/BackupStatus/index.ts
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowBackupCell.tsx
Labels: Approved, Project: MUI v5 Migration

#8957 fix: [M3-6251] - Domain Records not updating when navigating
  packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
  packages/manager/src/features/Domains/DomainRecordsWrapper.tsx
  packages/manager/src/features/Domains/EditDomainDrawer.tsx
  packages/manager/src/queries/domains.ts
Labels: Bug, React Query, Approved, Ready for Review

#8961 docs: Enable MSW in storybook
  packages/manager/.storybook/preview.tsx
  packages/manager/src/components/EntityTable/EntityTable.stories.mdx
  packages/manager/src/components/TooltipIcon/TooltipIcon.stories.mdx
Labels: Storybook, Approved, Ready for Review

#8956 chore: resolves pseudo class console errors
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/components/EntityTable/GroupedEntitiesByTag.tsx
  packages/manager/src/components/LineGraph/MetricDisplay.styles.ts
  packages/manager/src/components/LineGraph/NewMetricDisplay.styles.ts
  packages/manager/src/components/TableRow/TableRow.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Domains/DomainBanner.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectAppPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
  packages/manager/src/formatted-text.css
  packages/manager/src/themeFactory.ts
  packages/manager/src/themes.ts
Labels: Approved, Ready for Review

#8963 chore: [M3-5939] - Remove deprecated `linode_tax_id` property
  packages/manager/src/featureFlags.ts
Labels: Approved

#8958 chore: Repo Clean Up
  packages/manager/src/App.tsx
  packages/manager/src/__data__/groupImports.ts
  packages/manager/src/__data__/index.ts
  packages/manager/src/__data__/volumes.ts
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
  packages/manager/src/components/LineGraph/SimpleLegend.tsx
  packages/manager/src/context/dbaasContext.ts
  packages/manager/src/context/index.ts
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Account/ImportGroupsAsTags.test.tsx
  packages/manager/src/features/Account/ImportGroupsAsTags.tsx
  packages/manager/src/features/TagImport/DisplayGroupList.test.tsx
  packages/manager/src/features/TagImport/DisplayGroupList.tsx
  packages/manager/src/features/TagImport/TagImportDrawer.test.tsx
  packages/manager/src/features/TagImport/TagImportDrawer.tsx
  packages/manager/src/features/TagImport/index.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.test.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenuItem.test.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenuItem.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/index.ts
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/features/Users/UserDeleteConfirmationDialog.tsx
  packages/manager/src/features/Users/UserProfile.tsx
  packages/manager/src/features/Users/UsersLanding.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeBusyStatus.tsx
  packages/manager/src/store/index.ts
  packages/manager/src/store/regions/regions.actions.ts
  packages/manager/src/store/regions/regions.reducer.test.ts
  packages/manager/src/store/regions/regions.reducer.ts
  packages/manager/src/store/selectors/getEntitiesWithGroupsToImport.test.tsx
  packages/manager/src/store/selectors/getEntitiesWithGroupsToImport.tsx
  packages/manager/src/store/selectors/index.ts
  packages/manager/src/store/tagImportDrawer/index.test.ts
  packages/manager/src/store/tagImportDrawer/index.ts
  packages/manager/src/utilities/isProdApi.ts
  packages/manager/src/utilities/shouldDisplayGroupImportCTA.ts
Labels: Approved, Ready for Review

#8938 refactor: [M3-6439] - React Query for OAuth Apps
  packages/api-v4/src/account/types.ts
  packages/manager/src/App.tsx
  packages/manager/src/factories/accountOAuth.ts
  packages/manager/src/features/Profile/OAuthClients/CreateOAuthClientDrawer.test.tsx
  packages/manager/src/features/Profile/OAuthClients/CreateOAuthClientDrawer.tsx
  packages/manager/src/features/Profile/OAuthClients/DeleteOAuthClientDialog.tsx
  packages/manager/src/features/Profile/OAuthClients/EditOAuthClientDrawer.tsx
  packages/manager/src/features/Profile/OAuthClients/Modals.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClientActionMenu.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.test.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthFormDrawer.tsx
  packages/manager/src/features/Profile/OAuthClients/ResetOAuthClientDialog.tsx
  packages/manager/src/features/Profile/OAuthClients/index.tsx
  packages/manager/src/features/Profile/Profile.tsx
  packages/manager/src/queries/accountOAuth.ts
Labels: Add'tl Approval Needed, React Query, Approved

#8942 refactor: [M3-6449] - React Query for Profile - Trusted Devices
  packages/manager/src/components/ToggleState/ToggleState.ts
  packages/manager/src/components/ToggleState/index.ts
  packages/manager/src/features/Profile/AuthenticationSettings/RevokeTrustedDevicesDialog.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevices.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevicesDialog.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevicesTable.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
  packages/manager/src/queries/profile.ts
Labels: Add'tl Approval Needed, React Query, Ready for Review

#8968 refactor: [M3-6297, M3-6298] - MUI v5 Migration - Components > BetaChip & Breadcrumb
  packages/manager/src/components/BetaChip/BetaChip.tsx
  packages/manager/src/components/BetaChip/index.ts
  packages/manager/src/components/Breadcrumb/Breadcrumb.test.tsx
  packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
  packages/manager/src/components/Breadcrumb/index.tsx
  packages/manager/src/components/LandingHeader/LandingHeader.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailsBreadcrumb.tsx
Labels: Approved, Ready for Review, Project: MUI v5 Migration

#8962 refactor: [M3-6296] - MUI v5 Migration - `Components > BarPercent`
  packages/manager/src/components/BarPercent/BarPercent.tsx
Labels: Approved, Project: MUI v5 Migration

#8966 fix: Fix Clone Linode e2e test flake when Newark resources exist
  packages/manager/cypress/e2e/linodes/clone-linode.spec.ts
Labels: e2e

#8965 refactor: Un-Redux-ify Object Storage Drawer
  packages/manager/src/containers/bucketDrawer.container.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx
  packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/ObjectStorage/index.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/objectStorage.ts
  packages/manager/src/store/bucketDrawer/bucketDrawer.actions.ts
  packages/manager/src/store/bucketDrawer/bucketDrawer.reducer.ts
  packages/manager/src/store/index.ts
Labels: Ready for Review

#8959 refactor: [M3-6437] - MUI v5 Migration - Update src/components grid references
  packages/manager/src/components/AbuseTicketBanner/AbuseTicketBanner.tsx
  packages/manager/src/components/Accordion/Accordion.tsx
  packages/manager/src/components/ColorPalette/ColorPalette.tsx
  packages/manager/src/components/Dialog/Dialog.tsx
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.stories.mdx
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
  packages/manager/src/components/Drawer/Drawer.stories.mdx
  packages/manager/src/components/Drawer/Drawer.tsx
  packages/manager/src/components/EditableEntityLabel/EditableEntityLabel.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionOption.tsx
  packages/manager/src/components/EntityDetail/EntityDetail.tsx
  packages/manager/src/components/EntityIcon/EntityIconStory.tsx
  packages/manager/src/components/ErrorState/ErrorState.tsx
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/components/ImageSelect/imageIcons.stories.mdx
  packages/manager/src/components/LineGraph/MetricDisplay.styles.ts
  packages/manager/src/components/LineGraph/MetricsDisplay.test.tsx
  packages/manager/src/components/LineGraph/NewMetricDisplay.styles.ts
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
  packages/manager/src/components/PasswordInput/PasswordInput.tsx
  packages/manager/src/components/PasswordInput/StrengthIndicator.tsx
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
  packages/manager/src/components/Skeleton/Skeleton.test.tsx
  packages/manager/src/components/Skeleton/Skeleton.tsx
  packages/manager/src/components/Skeleton/index.ts
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/components/TableHeader/TableHeader.tsx
  packages/manager/src/components/TableHeader/index.ts
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplay.tsx
  packages/manager/src/components/UIIcons.stories.mdx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
  packages/manager/src/queries/profile.ts
Labels: Add'tl Approval Needed, Ready for Review, Project: MUI v5 Migration

#8972 fix: NodeBalancer Create e2e tests and associated bug
  packages/manager/cypress/e2e/nodebalancers/smoke-create-nodebal.spec.ts
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
Labels: e2e, Ready for Review

#8974 fix: skeleton import path
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
Labels: Bug, Ready for Review

#8970 ci: Add more context to the Cypress docker environment
  docker-compose.yml
Labels: Add'tl Approval Needed, e2e, Ready for Review

#8975 chore: [M3-5751] - Improve the `README.md`
  README.md
Labels: Enhancement, Approved, Documentation

#8973 chore: [M3-5351] - OCAs - improve usability of UDF forms
  packages/manager/src/components/Radio/Radio.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedSelect.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
Labels: Project: One Click Clusters, Approved

#8969 docs: Update component structure and storybook documentation
  docs/development-guide/02-component-structure.md
  docs/development-guide/04-component-library.md
Labels: Approved, Ready for Review, Documentation

#8971 fix: [M3-6214] - Reattempt failed HTTP requests in Cypress before hooks
  packages/manager/cypress/e2e/domains/smoke-create-domain-records.spec.ts
  packages/manager/cypress/e2e/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/nodebalancers/smoke-create-nodebal.spec.ts
  packages/manager/cypress/support/api/authentication.ts
  packages/manager/cypress/support/api/common.ts
  packages/manager/cypress/support/api/domains.ts
  packages/manager/cypress/support/api/entityTransfer.ts
  packages/manager/cypress/support/api/firewalls.ts
  packages/manager/cypress/support/api/helpAndSupport.ts
  packages/manager/cypress/support/api/images.ts
  packages/manager/cypress/support/api/linodes.ts
  packages/manager/cypress/support/api/longview.ts
  packages/manager/cypress/support/api/nodebalancers.ts
  packages/manager/cypress/support/api/stackscripts.ts
  packages/manager/cypress/support/api/tags.ts
  packages/manager/cypress/support/api/volumes.ts
  packages/manager/cypress/support/constants/api.ts
  packages/manager/cypress/support/constants/cypress.ts
  packages/manager/cypress/support/e2e.js
  packages/manager/cypress/support/login.ts
  packages/manager/cypress/support/ui/common.ts
  packages/manager/cypress/support/util/backoff.ts
  packages/manager/cypress/support/util/polling.ts
  packages/manager/cypress/tsconfig.json
Labels: e2e, Ready for Review

#8980 refactor: [M3-6299] – MUI v5 Migration - `Components > CheckBox`
  packages/manager/src/components/CheckBox/CheckBox.tsx
Labels: Project: MUI v5 Migration

#8979 chore: Clean Up Repo Root
  .eslintignore
  .eslintrc.js
  .gitchangelog.rc
  .gitchangelog.tpl
  .npmignore
Labels: Build and Organization

#8976 feat: [M3-6450] - Add icon to images not cloud-init compatible
  packages/manager/src/assets/icons/cloud-init-incompatible.svg
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/ImageSelect/ImageSelect.test.tsx
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/components/TooltipIcon/TooltipIcon.tsx
Labels: Project: Metadata, Ready for Review

#8901 test: [M3-6234] - Add Cypress LKE creation end-to-end tests
  packages/manager/cypress/e2e/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/kubernetes/smoke-lke-create.spec.ts
  packages/manager/cypress/support/api/lke.ts
  packages/manager/cypress/support/constants/lke.ts
  packages/manager/cypress/support/intercepts/kubernetes.ts
  packages/manager/cypress/support/intercepts/lke.ts
  packages/manager/cypress/support/ui/breadcrumb.ts
  packages/manager/cypress/support/ui/common.ts
  packages/manager/cypress/support/ui/index.ts
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.tsx
Labels: e2e, Approved

#8981 fix: [M3-6425] - Linode Details Add Configurations Modal Header
  packages/manager/src/components/Dialog/Dialog.tsx
Labels: Ready for Review

#8977 style: [M3-6215] - Metadata final copy
  packages/manager/src/components/TooltipIcon/TooltipIcon.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/AcceptedFormats.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.styles.ts
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataExplanatory.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
Labels: Project: Metadata, Ready for Review

#8984 fix: Unit Tests for Metadata and Improvements to Typesafety
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
  packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
Labels: Project: Metadata

#8983 fix: async await console erros in unit test
  packages/manager/src/hooks/useAPIRequest.test.ts
Labels: Unit tests

#8982 chore: [M3-6186] - Update logo in TPA Providers screen
  packages/manager/src/assets/icons/providers/akamai-logo-rgb-waveOnly.svg
  packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/SecurityQuestions.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.test.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
Labels: Approved

#8987 fix: [M3-6298] - Fix breadcrumb story import and missing react import
  packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
Labels: Storybook

#8991 fix: `smoke-deep-link.spec.ts` after copy changes
  packages/manager/cypress/support/ui/constants.ts
Labels: e2e

#8992 refactor: [M3-6395] – MUI v5 Migration - `Components > StackScript`
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/components/StackScript/index.ts
Labels: Project: MUI v5 Migration

#8994 refactor: [M3-6394] – MUI v5 Migration - `Components > SplashScreen`
  packages/manager/src/components/SplashScreen/SplashScreen.tsx
Labels: Project: MUI v5 Migration

#8944 test: [M3-6247] - Add Cypress Firewall e2e Create/Delete tests
  packages/manager/cypress/e2e/firewalls/create-firewall.spec.ts
  packages/manager/cypress/e2e/firewalls/delete-firewall.spec.ts
  packages/manager/cypress/support/intercepts/firewalls.ts
  packages/manager/cypress/support/ui/autocomplete-popper.ts
  packages/manager/cypress/support/ui/index.ts
Labels: e2e

#8995 refactor: [M3-6414, M3-6415] - MUIv5 Migration - Components > TagsInput, TagsPanel
  CHANGELOG.md
  packages/manager/src/components/BetaChip/BetaChip.stories.mdx
  packages/manager/src/components/LabelAndTagsPanel/LabelAndTagsPanel.tsx
  packages/manager/src/components/TagCell/TagDrawer.tsx
  packages/manager/src/components/TagsInput/TagsInput.stories.mdx
  packages/manager/src/components/TagsInput/TagsInput.test.tsx
  packages/manager/src/components/TagsInput/TagsInput.tsx
  packages/manager/src/components/TagsInput/index.ts
  packages/manager/src/components/TagsPanel/TagsPanel.stories.mdx
  packages/manager/src/components/TagsPanel/TagsPanel.tsx
  packages/manager/src/components/TagsPanel/index.ts
  packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
  packages/manager/src/features/Domains/EditDomainDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/EditVolumeForm.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/linodes/LinodesCreate/types.ts
Labels: Ready for Review, Project: MUI v5 Migration

#9000 fix: [M3-6312] - Clear Kubernetes Delete Dialog when it is reopened
  CHANGELOG.md
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
Labels: Bug, Approved

#8996 refactor: Made `<RegionSelect />` more dynamic
  CHANGELOG.md
  packages/manager/src/components/EnhancedSelect/components/SingleValue.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionOption.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.test.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/index.ts
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/utils.ts
  packages/manager/src/components/Flag.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/features/linodes/MigrateLinode/ConfigureForm.tsx
Labels: Enhancement, Approved

#8986 refactor: [M3-6478] - Make `<Select />` type safe
  CHANGELOG.md
  packages/manager/src/GoTo.tsx
  packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
  packages/manager/src/components/EnhancedSelect/Select.tsx
  packages/manager/src/components/EnhancedSelect/index.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
  packages/manager/src/components/TagsInput/TagsInput.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/manager/src/features/Domains/DomainRecordDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
  packages/manager/src/features/Help/Panels/AlgoliaSearchBar.tsx
  packages/manager/src/features/Images/ImageSelect.tsx
  packages/manager/src/features/Longview/shared/TimeRangeSelect.tsx
  packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/Question.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedMultiSelect.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/KernelSelect.tsx
Labels: Enhancement, Approved, Ready for Review

#9002 refactor: [M3-6304] - MUI v5 Migration - `ConditionalWrapper`
  packages/manager/src/components/ConditionalWrapper/ConditionalWrapper.tsx
  packages/manager/src/components/ConditionalWrapper/index.ts
  packages/manager/src/components/DocsLink/DocsLink.tsx
  packages/manager/src/components/IconTextLink/IconTextLink.tsx
  packages/manager/src/components/IconTextLink/index.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx
Labels: Ready for Review, Project: MUI v5 Migration

#9001 refactor: [M3-6417] - SRC > Components > Tile
  packages/manager/src/components/Tile/Tile.stories.mdx
  packages/manager/src/components/Tile/Tile.tsx
  packages/manager/src/components/Tile/index.ts
  packages/manager/src/features/Help/Panels/OtherWays.tsx
  packages/manager/src/features/Help/SupportSearchLanding/HelpResources.tsx
Labels: Approved, Project: MUI v5 Migration

#9012 master -> develop following release of Cloud v1.91.0
  CHANGELOG.md
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/manager/package.json
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Release

#9003 fix: [M3-6430] - Event entities should only be linked for true labels
  CHANGELOG.md
  packages/manager/src/eventMessageGenerator.test.ts
  packages/manager/src/eventMessageGenerator.ts
Labels: Approved

#9014 refactor: [M3-6396] - MUIv5 Migration - Components > StatusIcon
  packages/manager/src/components/StatusIcon/StatusIcon.stories.mdx
  packages/manager/src/components/StatusIcon/StatusIcon.tsx
  packages/manager/src/components/StatusIcon/index.tsx
  packages/manager/src/features/Account/AccountLoginsTableRow.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/features/Domains/DomainTableRow.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
Labels: Ready for Review, Project: MUI v5 Migration

#9011 fix: `README.md` Validation Version Badge Label
  CHANGELOG.md
  README.md
Labels: Approved, Documentation

#9013 refactor: [M3-6303] - SRC > Components > ColorPalette
  packages/manager/src/components/ColorPalette/ColorPalette.stories.mdx
  packages/manager/src/components/ColorPalette/ColorPalette.tsx
Labels: Approved, Ready for Review, Project: MUI v5 Migration

#9024 staging → master for v1.91.1
  CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
Labels: Release

#9022 refactor: [M3-6322] - SRC > Components > DisplayPrice
  packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
  packages/manager/src/components/DisplayPrice/DisplayPrice.tsx
  packages/manager/src/components/DisplayPrice/index.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/HACheckbox.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CloneVolumeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/PricePanel.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/ResizeVolumeForm.tsx
Labels: Add'tl Approval Needed, Project: MUI v5 Migration

#9015 refactor: [M3-6308] - MUI v5 Migration - `Components > CreateLinodeDisabled`
  packages/manager/src/components/CreateLinodeDisabled/CreateLinodeDisabled.tsx
  packages/manager/src/components/CreateLinodeDisabled/index.ts
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
Labels: Add'tl Approval Needed, Project: MUI v5 Migration

#8999 feat: [M3-6427] - Add No Results section for Marketplace Search
  CHANGELOG.md
  packages/manager/src/features/linodes/LinodesCreate/AppPanelSection.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectAppPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
Labels: Marketplace, Approved

#9029 chore: slightly improve PR template
  docs/PULL_REQUEST_TEMPLATE.md
Labels: Approved, Documentation

#9027 refactor: Clean up Linode rescue tests, work around flake caused by action menu interactions
  packages/manager/cypress/e2e/linodes/rescue-linode.spec.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: e2e, Approved

#9009 fix: [M3-6480] - Fix blank Node Pool plan selection
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/VolumeDrawer.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
  packages/manager/src/index.tsx
Labels: Bug, Approved, Ready for Review

#9031 fix: Increase radio button padding to fix hover effect shape
  CHANGELOG.md
  packages/manager/src/components/Radio/Radio.tsx
Labels: Ready for Review

#9005 chore: [M3-6024] – Upgrade NR to v1230
  packages/manager/public/new-relic.js
Labels: Approved

#9035 fix: Improve stability of `ObjectDetailsDrawer.test.tsx`
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
Labels: Approved, Ready for Review, Unit tests

#9037 chore: Update Vite, Storybook, tsup, and related dependencies
  packages/api-v4/package.json
  packages/manager/package.json
  packages/validation/package.json
  yarn.lock
Labels: Dependencies, Ready for Review

#9007 refactor: [M3-6316, M3-6317] MUI v5 Migration - Components > DateTimeDisplay, DebouncedSearchTextField
  CHANGELOG.md
  packages/manager/src/components/BackupStatus/BackupStatus.tsx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.test.tsx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.tsx
  packages/manager/src/components/DateTimeDisplay/index.ts
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx
  packages/manager/src/components/DebouncedSearchTextField/StoryComponents/TextFieldExample.tsx
  packages/manager/src/components/DebouncedSearchTextField/index.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PromoDisplay.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
  packages/manager/src/features/Domains/DomainTableRow.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.tsx
  packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
  packages/manager/src/features/Managed/Credentials/CredentialRow.tsx
  packages/manager/src/features/Managed/Monitors/IssueDay.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevices.tsx
  packages/manager/src/features/Search/ResultRow.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
  packages/manager/src/features/Support/ExpandableTicketPanel.tsx
  packages/manager/src/features/Support/SupportTickets/TicketRow.tsx
  packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskRow.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivityRow.tsx
Labels: Add'tl Approval Needed, Ready for Review, Project: MUI v5 Migration

#9032 fix: [M3-6446] - Fix code scanning alert that DOM text is reinterpreted as HTML
  packages/manager/src/components/ExternalLink/ExternalLink.tsx
Labels: Security, Ready for Review

#9030 refactor: [M3-6309] - SRC > Components > Currency
  CHANGELOG.md
  packages/manager/src/components/Currency/Currency.stories.mdx
  packages/manager/src/components/Currency/Currency.test.tsx
  packages/manager/src/components/Currency/Currency.tsx
  packages/manager/src/components/Currency/index.ts
  packages/manager/src/components/DisplayPrice/DisplayPrice.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PromoDisplay.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
  packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
Labels: Approved, Project: MUI v5 Migration

#9034 refactor: Improve Object Storage E2E flake related to ACL select
  packages/manager/cypress/e2e/objectStorage/object-storage.e2e.spec.ts
  packages/manager/src/components/EnhancedSelect/components/MenuList.tsx
Labels: e2e, Approved

#9017 test: [M3-6248] - Add Cypress Firewall e2e Update tests
  packages/manager/cypress/e2e/firewalls/update-firewall.spec.ts
  packages/manager/src/factories/firewalls.ts
Labels: Approved

#9048 fix: `firewallRuleEditor.test.ts` failure
  packages/api-v4/src/firewalls/types.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts
Labels: Unit tests

#9047 refactor: [M3-6318] - MUI v5 - Components > DeletionDialog
  CHANGELOG.md
  packages/manager/src/components/DeletionDialog/DeletionDialog.stories.tsx
  packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
  packages/manager/src/components/DeletionDialog/index.tsx
  packages/manager/src/features/Domains/DeleteDomain.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
  packages/manager/src/features/Managed/Contacts/Contacts.tsx
  packages/manager/src/features/Managed/Credentials/CredentialList.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTable.tsx
Labels: Approved, Project: MUI v5 Migration

#9041 chore: assets and utilities clean up
  packages/manager/config/environments/beta
  packages/manager/cypress/e2e/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/src/__data__/withLinodeActions.ts
  packages/manager/src/assets/default/cube.png
  packages/manager/src/assets/distros/Alpine.png
  packages/manager/src/assets/distros/Arch.png
  packages/manager/src/assets/distros/CentOS.png
  packages/manager/src/assets/distros/ContainerLinux.png
  packages/manager/src/assets/distros/Debian.png
  packages/manager/src/assets/distros/Fedora.png
  packages/manager/src/assets/distros/Gentoo.png
  packages/manager/src/assets/distros/OpenSUSE.png
  packages/manager/src/assets/distros/Slackware.png
  packages/manager/src/assets/distros/Ubuntu.png
  packages/manager/src/assets/noscript/styles.css
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
  packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx
  packages/manager/src/features/EntityTransfers/TransfersTable.tsx
  packages/manager/src/features/EntityTransfers/utilities.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
  packages/manager/src/features/NodeBalancers/utils.ts
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/Search/ResultGroup.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
  packages/manager/src/features/linodes/MigrateLinode/ConfigureForm.tsx
  packages/manager/src/hooks/useForm.ts
  packages/manager/src/requestableContext.tsx
  packages/manager/src/utilities/allocateIPAddress.ts
  packages/manager/src/utilities/capitalize.test.ts
  packages/manager/src/utilities/capitalize.ts
  packages/manager/src/utilities/defaultNumeric.ts
  packages/manager/src/utilities/escapeStringForCLI.ts
  packages/manager/src/utilities/formatRegion.ts
  packages/manager/src/utilities/formikErrorUtils.ts
  packages/manager/src/utilities/generate-cURL.ts
  packages/manager/src/utilities/getItemByID.ts
  packages/manager/src/utilities/getLinodeInfo.test.ts
  packages/manager/src/utilities/getLinodeInfo.ts
  packages/manager/src/utilities/haveAnyBeenModified.ts
  packages/manager/src/utilities/imageToItem.test.ts
  packages/manager/src/utilities/imageToItem.ts
  packages/manager/src/utilities/images.ts
  packages/manager/src/utilities/index.ts
  packages/manager/src/utilities/initAll.test.ts
  packages/manager/src/utilities/initAll.ts
  packages/manager/src/utilities/isNilOrEmpty.ts
  packages/manager/src/utilities/maybeCastToNumber.ts
  packages/manager/src/utilities/sort-by.ts
  packages/manager/src/utilities/sortAlphabetically.test.ts
  packages/manager/src/utilities/sortAlphabetically.ts
  scripts/start_manager.sh
Labels: Approved, Clean Up

#9033 feat: [M3-6501] - Add Metadata migrate warning
  CHANGELOG.md
  packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/linodes/MigrateLinode/CautionNotice.tsx
  packages/manager/src/features/linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/linodes/MigrateLinode/index.ts
Labels: Project: Metadata, Approved

#9039 feat: [M3-5561] - Add Private IP checkbox when cloning a Linode
  packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.test.tsx
  packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
Labels: Approved

#9040 refactor: [M3-6307] - MUIv5 Migration - SRC > Components > CopyTooltip
  CHANGELOG.md
  packages/manager/src/components/CopyTooltip/CopyTooltip.stories.mdx
  packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
  packages/manager/src/components/CopyTooltip/index.ts
  packages/manager/src/components/CopyableAndDownloadableTextField.tsx
  packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
  packages/manager/src/components/LinodeCLIModal/LinodeCLIModal.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
  packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Longview/shared/InstallationInstructions.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/linodes/LinodesCreate/CodeBlock/index.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/features/linodes/LinodesLanding/IPAddress.tsx
Labels: Approved, Project: MUI v5 Migration

#9053 fix: [M3-6510] - Modifying Configuration Profile in Cloud breaks with VLANs
  CHANGELOG.md
  packages/api-v4/src/linodes/types.ts
  packages/manager/src/factories/linodeConfigInterfaceFactory.ts
  packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
Labels: Ready for Review

#9052 chore: Update PayPal and Braintree dependencies
  package.json
  packages/manager/package.json
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  yarn.lock
Labels: Dependencies, Approved

#9051 refactor: [M3-6300] - MUI v5 Migration - `Components > CheckoutBar`
  CHANGELOG.md
  packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
  packages/manager/src/components/CheckoutBar/DisplaySection.tsx
  packages/manager/src/components/CheckoutBar/DisplaySectionList.tsx
  packages/manager/src/components/CheckoutBar/index.ts
  packages/manager/src/components/CheckoutBar/styles.ts
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
Labels: Approved, Project: MUI v5 Migration

#9045 feat: [M3-5915] Accessible graph data
  CHANGELOG.md
  packages/manager/src/components/LineGraph/AccessibleGraphData.test.tsx
  packages/manager/src/components/LineGraph/AccessibleGraphData.tsx
  packages/manager/src/components/LineGraph/LineGraph.stories.mdx
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/components/LineGraph/NewMetricDisplay.styles.ts
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraphs.tsx
Labels: Add'tl Approval Needed, Accessibility

#9055 feat: [M3-6525] - Storybook config cleanup
  packages/manager/.storybook/main.ts
  packages/manager/.storybook/manager-head.html
  packages/manager/.storybook/preview-head.html
  packages/manager/.storybook/preview.tsx
  packages/manager/package.json
  packages/manager/src/components/EntityDetail/.EntityDetail.stories.mdx
  packages/manager/src/components/Notice/Notice.stories.mdx
  packages/manager/src/components/Table/Table.stories.mdx
  yarn.lock
Labels: Approved

#9004 chore: [M3-6496] - Add Adobe Analytics custom event tracking
  packages/manager/src/utilities/ga.ts
Labels: Approved

#9050 refactor: [M3-6320] - MUI v5 Migration - Components > DialogTitle
  CHANGELOG.md
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/components/Dialog/Dialog.tsx
  packages/manager/src/components/DialogTitle/DialogTitle.tsx
  packages/manager/src/components/DialogTitle/index.tsx
  packages/manager/src/components/IconButton/IconButton.tsx
  packages/manager/src/features/TheApplicationIsOnFire.tsx
  packages/manager/src/themes.ts
Labels: Ready for Review, Project: MUI v5 Migration

#9058 fix: [M3-6454] - Show error for PayPal payments
  packages/api-v4/src/account/payments.ts
  packages/api-v4/src/account/types.ts
  packages/manager/src/factories/billing.ts
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentBits/PaypalDialog.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentBits/PaypalDialogActionButtons.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
  packages/validation/src/account.schema.ts
Labels: Approved

#9049 refactor: Prepare for React Query for Linodes
  packages/manager/src/App.tsx
  packages/manager/src/components/LinodeMultiSelect/LinodeMultiSelect.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
  packages/manager/src/features/Lish/Lish.tsx
  packages/manager/src/features/Volumes/VolumeAttachmentDrawer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
  packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
  packages/manager/src/queries/linodes.ts
  packages/manager/src/queries/linodes/events.ts
  packages/manager/src/queries/linodes/firewalls.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/queries/linodes/stats.ts
  packages/manager/src/queries/volumes.ts
  packages/manager/src/store/linodes/linode.requests.ts
Labels: Add'tl Approval Needed, React Query, Ready for Review

#9060 feat: [M3-6525] - Storybook story POC
  packages/manager/src/components/BarPercent/BarPercent.stories.mdx
  packages/manager/src/components/BarPercent/BarPercent.stories.tsx
  packages/manager/src/components/BarPercent/BarPercent.tsx
Labels: Approved

#9057 refactor: [M3-6217]: Refactor Domains E2E Test Intercepts
  packages/manager/cypress/e2e/domains/smoke-create-domain-records.spec.ts
  packages/manager/cypress/e2e/domains/smoke-create-domain.spec.ts
  packages/manager/cypress/support/intercepts/domains.ts
Labels: e2e, Approved
