Repository linode/manager, pull requests merged in 2023-09, with the labels that each got.

#9598 feat: [M3-6966] - Add DC-specific pricing to Linode Create flows
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-9598-upcoming-features-1693322571328.md
  packages/manager/package.json
  packages/manager/src/components/SelectionCard/CardBase.tsx
  packages/manager/src/factories/types.ts
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Backups/utils.test.ts
  packages/manager/src/features/Backups/utils.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx
  packages/manager/src/features/components/PlansPanel/PlanContainer.test.tsx
  packages/manager/src/features/components/PlansPanel/PlanContainer.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.test.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
  packages/manager/src/features/components/PlansPanel/types.ts
  packages/manager/src/features/components/PlansPanel/utils.ts
  packages/manager/src/utilities/pricing/backups.test.tsx
  packages/manager/src/utilities/pricing/backups.ts
  packages/manager/src/utilities/pricing/constants.ts
  packages/manager/src/utilities/pricing/dynamicPricing.ts
  packages/manager/src/utilities/pricing/linodes.test.tsx
  packages/manager/src/utilities/pricing/linodes.ts
  packages/manager/src/utilities/testHelpers.tsx
  yarn.lock
Labels: Approved, DC-Specific Pricing

#9619 fix: Restore Longview styling to what it used to be
  packages/manager/.changeset/pr-9619-fixed-1693518126299.md
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/Apache.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/GaugesSection.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINX.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/Network.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ProcessGraphs.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientInstructions.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
  packages/manager/src/features/Longview/shared/InstallationInstructions.tsx
Labels: Bug, Approved

#9621 chore: Update yarn lock
  yarn.lock
Labels: Approved, Missing Changeset

#9614 fix: Fix E2E failures caused by inadequate resource clean-up
  packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
  packages/manager/cypress/e2e/core/longview/longview.spec.ts
Labels: Approved, Missing Changeset

#9625 change: [M3-7077] - Remove VPC column from Linodes landing page table
  packages/manager/.changeset/pr-9625-removed-1693588382719.md
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx
Labels: Ready for Review, VPC

#9606 feat: [M3-7048] - Add DC-specific pricing for Kubernetes node pools
  packages/manager/.changeset/pr-9606-upcoming-features-1693548349929.md
  packages/manager/src/factories/types.ts
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeClusterSpecs.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.test.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/utilities/pricing/constants.ts
  packages/manager/src/utilities/pricing/kubernetes.test.tsx
  packages/manager/src/utilities/pricing/kubernetes.ts
Labels: Approved, DC-Specific Pricing

#9585 feat: [M3-6759] - Handle VPC Account Grants / Permissions / Capabilities
  packages/api-v4/.changeset/pr-9585-changed-1692736077405.md
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-9585-upcoming-features-1692736112038.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/factories/grants.ts
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEmptyState.tsx
  packages/manager/src/features/VPCs/index.tsx
Labels: @linode/api-v4, Ready for Review, VPC

#9623 fix: Payment Drawer Style Regression from MUI Update
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
Labels: Bug, UI, Ready for Review

#9622 fix: Billing Summary UI Regression from MUI Update
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
Labels: Bug, UI, Ready for Review

#9632 fix: Linode Crate - Attach VLAN - Grid Conatiner
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
Labels: UI

#9634 Release v1.101.0 - master → develop
  packages/api-v4/.changeset/pr-9453-changed-1691514440186.md
  packages/api-v4/.changeset/pr-9530-added-1692198648058.md
  packages/api-v4/.changeset/pr-9537-upcoming-features-1692216355268.md
  packages/api-v4/.changeset/pr-9586-upcoming-features-1692798602248.md
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/manager/.changeset/pr-9520-upcoming-features-1692378386106.md
  packages/manager/.changeset/pr-9523-tech-stories-1691607836644.md
  packages/manager/.changeset/pr-9530-added-1691618959800.md
  packages/manager/.changeset/pr-9537-upcoming-features-1692202603416.md
  packages/manager/.changeset/pr-9544-added-1692992268848.md
  packages/manager/.changeset/pr-9549-upcoming-features-1692196983630.md
  packages/manager/.changeset/pr-9555-tech-stories-1692282778803.md
  packages/manager/.changeset/pr-9556-upcoming-features-1692288655388.md
  packages/manager/.changeset/pr-9561-tech-stories-1692300253731.md
  packages/manager/.changeset/pr-9563-fixed-1692305293304.md
  packages/manager/.changeset/pr-9564-added-1692350316540.md
  packages/manager/.changeset/pr-9565-tech-stories-1692368201746.md
  packages/manager/.changeset/pr-9566-upcoming-features-1692376980714.md
  packages/manager/.changeset/pr-9567-tech-stories-1692380986951.md
  packages/manager/.changeset/pr-9568-upcoming-features-1692399466892.md
  packages/manager/.changeset/pr-9569-changed-1692553123699.md
  packages/manager/.changeset/pr-9570-changed-1692743440177.md
  packages/manager/.changeset/pr-9572-upcoming-features-1692649682757.md
  packages/manager/.changeset/pr-9576-upcoming-features-1692664450264.md
  packages/manager/.changeset/pr-9577-upcoming-features-1692672144232.md
  packages/manager/.changeset/pr-9578-upcoming-features-1692717836737.md
  packages/manager/.changeset/pr-9583-upcoming-features-1692727583271.md
  packages/manager/.changeset/pr-9584-upcoming-features-1692729650610.md
  packages/manager/.changeset/pr-9586-upcoming-features-1692798648869.md
  packages/manager/.changeset/pr-9587-fixed-1692802396223.md
  packages/manager/.changeset/pr-9588-upcoming-features-1693245885155.md
  packages/manager/.changeset/pr-9592-fixed-1692907566241.md
  packages/manager/.changeset/pr-9596-added-1693253466611.md
  packages/manager/.changeset/pr-9602-fixed-1693332727991.md
  packages/manager/.changeset/pr-9603-tech-stories-1693333265033.md
  packages/manager/.changeset/pr-9604-changed-1693336292797.md
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/validation/.changeset/pr-9453-changed-1691514405209.md
  packages/validation/.changeset/pr-9537-changed-1692640036055.md
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Master → Develop

#9597 feat: [M3-6980] - Add DC Specific Pricing Invoice Support
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-9597-upcoming-features-1693255450332.md
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, DC-Specific Pricing

#9582 refactor: [M3-6263] - MUI v5 Migration - SRC > Features > EntityTransfers
  packages/manager/.changeset/pr-9582-tech-stories-1692726989780.md
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/index.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/EntityTransferCreate.styles.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/EntityTransfersCreate.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferCheckoutBar.styles.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferCheckoutBar.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferHeader.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.styles.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/index.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/transferReducer.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferCancelDialog.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.styles.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.test.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.styles.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.styles.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferDetailsDialog.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/index.ts
  packages/manager/src/features/EntityTransfers/RenderTransferRow.styles.ts
  packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx
  packages/manager/src/features/EntityTransfers/TransfersPendingActionMenu.tsx
  packages/manager/src/features/EntityTransfers/TransfersTable.styles.ts
  packages/manager/src/features/EntityTransfers/TransfersTable.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
Labels: Approved, Project: MUI v5 Migration

#9545 test: [M3-6553] - Add e2e tests for Linode Rebuild
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
Labels: e2e, Approved

#9591 feat: [M3-6819] - AGLB Details - Configurations Tab
  packages/api-v4/src/aglb/configurations.ts
  packages/api-v4/src/aglb/types.ts
  packages/manager/.changeset/pr-9591-upcoming-features-1692984602898.md
  packages/manager/src/factories/aglb.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CertificateSelect.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ApplyCertificatesDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/CertificateTable.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationAccordion.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerConfigurations.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerDetail.tsx
  packages/manager/src/queries/aglb/certificates.ts
  packages/manager/src/queries/aglb/configurations.ts
  packages/validation/src/index.ts
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, AGLB

#9639 fix: [M3-7088] - Fix typo in `CloseTicketLink.tsx`
  packages/manager/.changeset/pr-9639-fixed-1694031609043.md
  packages/manager/src/features/Support/SupportTicketDetail/CloseTicketLink.tsx
Labels: Approved

#9644 hotfix: [M3-7085] Edit VLAN config validation bug
  packages/validation/.changeset/pr-9641-fixed-1694095072428.md
  packages/validation/src/linodes.schema.ts
Labels: Hotfix

#9624 chore: [M3-7067] - Update Empty state landing page according to the n…
  packages/manager/src/components/EmptyLandingPageResources/ResourcesLinksSubSection.tsx
  packages/manager/src/components/EmptyLandingPageResources/ResourcesSection.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerEmptyStateData.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerLanding.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerLandingEmptyState.tsx
Labels: Approved, AGLB

#9643 fix: [M3-6950] - Restored longview active table rows and arrow
  packages/manager/.changeset/pr-9643-fixed-1694103276021.md
  packages/manager/src/components/TableRow/TableRow.styles.ts
  packages/manager/src/components/TableRow/TableRow.tsx
Labels: Bug, Approved

#9637 hotfix: [M3-7084] - Fix Restricted User Permissions after entity creation
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/queries/databases.ts
  packages/manager/src/queries/domains.ts
  packages/manager/src/queries/firewalls.ts
  packages/manager/src/queries/images.ts
  packages/manager/src/queries/kubernetes.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/queries/nodebalancers.ts
  packages/manager/src/queries/volumes.ts
  packages/validation/.changeset/pr-9641-fixed-1694095072428.md
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Urgent, Ready for Review, Hotfix

#9646 Release v1.101.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/queries/databases.ts
  packages/manager/src/queries/domains.ts
  packages/manager/src/queries/firewalls.ts
  packages/manager/src/queries/images.ts
  packages/manager/src/queries/kubernetes.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/queries/nodebalancers.ts
  packages/manager/src/queries/volumes.ts
  packages/validation/CHANGELOG.md
  packages/validation/package.json
  packages/validation/src/linodes.schema.ts
Labels: Release, Hotfix

#9651 Release v1.101.1 - master → develop
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/queries/databases.ts
  packages/manager/src/queries/domains.ts
  packages/manager/src/queries/firewalls.ts
  packages/manager/src/queries/images.ts
  packages/manager/src/queries/kubernetes.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/queries/nodebalancers.ts
  packages/manager/src/queries/volumes.ts
  packages/validation/CHANGELOG.md
  packages/validation/package.json
  packages/validation/src/linodes.schema.ts
Labels: Master → Develop

#9616 feat: [M3-7029] - Add AGLB Certificate Create Drawer
  packages/api-v4/src/aglb/certificates.ts
  packages/manager/.changeset/pr-9616-upcoming-features-1693507025003.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-details-page.spec.ts
  packages/manager/cypress/support/intercepts/load-balancers.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CreateCertificateDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CreateCertificateDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerCertificates.tsx
  packages/manager/src/queries/aglb/certificates.ts
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, AGLB

#9647 feat: [M3-6747] - Add filter subnets field
  packages/manager/.changeset/pr-9647-upcoming-features-1694186188307.md
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
Labels: Approved, VPC

#9642 test: [M3-7070] - Add DC pricing tests for Linode Clone flow
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: Approved, DC-Specific Pricing

#9497 refactor: [M3-6922] - Add Autocomplete Component
  packages/manager/.changeset/pr-9497-tech-stories-1691208190450.md
  packages/manager/src/components/Autocomplete/Autocomplete.stories.tsx
  packages/manager/src/components/Autocomplete/Autocomplete.styles.tsx
  packages/manager/src/components/Autocomplete/Autocomplete.test.tsx
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.styles.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
  packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
  packages/manager/src/foundations/themes/light.ts
Labels: Storybook, Approved

#9608 feat: [M3-7019] - Create add Nodebalancer to Firewall drawer
  packages/manager/.changeset/pr-9608-upcoming-features-1693406491148.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddLinodeDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
  packages/manager/src/utilities/mapIdsToDevices.test.ts
  packages/manager/src/utilities/mapIdsToDevices.ts
  packages/manager/src/utilities/mapIdsToLinodes.ts
Labels: Add'tl Approval Needed, Nodebalancer Firewall UX

#9600 refactor: [M3-6274] - MUI v5 Migration - `SRC > Features > Longview` Pt1: Longview Detail
  packages/manager/.changeset/pr-9600-tech-stories-1693257951344.md
  packages/manager/src/components/TableRow/TableRow.styles.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ActiveConnections.test.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ActiveConnections.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ConnectionRow.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/index.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/Apache.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/ApacheGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/index.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/CommonStyles.styles.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/DiskGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.styles.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.styles.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.test.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/index.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/GaugesSection.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.styles.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Installation.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/ListeningServices.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/LongviewServiceRow.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/index.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/index.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINX.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/index.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/index.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/index.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ProcessGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.styles.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.styles.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.test.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/TopProcesses.styles.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/TopProcesses.tsx
  packages/manager/src/features/Longview/LongviewDetail/GraphCard.tsx
  packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.styles.ts
  packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
  packages/manager/src/features/Longview/LongviewDetail/index.ts
  packages/manager/src/features/Longview/index.tsx
Labels: Approved, Project: MUI v5 Migration

#9664 feat: [M3-7052] - Add NodeBalancer table under Firewall / Devices
  packages/manager/.changeset/pr-9664-upcoming-features-1694530488404.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceTable.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDevicesTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
Labels: Add'tl Approval Needed, Nodebalancer Firewall UX

#9662 fix: Resolve test account Machine Image resource accumulation by authenticating clean up requests
  packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
Labels: Approved

#9640 feat: [M3-6749] - Subnet delete dialog
  packages/manager/.changeset/pr-9640-upcoming-features-1694033247968.md
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/cypress/support/intercepts/vpc.ts
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetDeleteDialog.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetDeleteDialog.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, VPC

#9626 feat: [M3-7016] - Add Basic Filtering for Firewall Devices
  packages/manager/.changeset/pr-9626-upcoming-features-1693604222356.md
  packages/manager/src/components/ActionsPanel/ActionsPanel.stories.tsx
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/ListeningServices.tsx
Labels: Add'tl Approval Needed, Nodebalancer Firewall UX

#9620 feat: [M3-7036] DC specific transfer pool displays
  packages/api-v4/src/linodes/info.ts
  packages/manager/.changeset/pr-9620-upcoming-features-1694457457440.md
  packages/manager/src/components/BarPercent/BarPercent.tsx
  packages/manager/src/components/TransferDisplay/LegacyTransferDisplay.test.tsx
  packages/manager/src/components/TransferDisplay/LegacyTransferDisplay.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplay.styles.ts
  packages/manager/src/components/TransferDisplay/TransferDisplay.test.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplay.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayDialog.test.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayDialog.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayUsage.test.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayUsage.tsx
  packages/manager/src/components/TransferDisplay/constants.ts
  packages/manager/src/components/TransferDisplay/utils.test.tsx
  packages/manager/src/components/TransferDisplay/utils.ts
  packages/manager/src/factories/account.ts
  packages/manager/src/factories/linodes.ts
  packages/manager/src/factories/regions.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetwork.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransfer.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransfer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferContent.styles.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/utils.test.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/utils.ts
  packages/manager/src/utilities/pricing/linodes.test.tsx
  packages/manager/src/utilities/pricing/linodes.ts
Labels: DC-Specific Pricing

#9663 feat: [M3-7096] - Show Region `label` in addition to `id` on Invoices
  packages/manager/.changeset/pr-9663-upcoming-features-1694534723160.md
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.test.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, DC-Specific Pricing

#9665 fix: [M3-7099] - Metadata CLI command
  packages/manager/.changeset/pr-9665-fixed-1694552506393.md
  packages/manager/src/utilities/generate-cli.test.ts
  packages/manager/src/utilities/generate-cli.ts
Labels: Bug, Project: Metadata, Approved

#9652 feat: [M3-6743] - Create Subnet Drawer
  packages/manager/.changeset/pr-9652-upcoming-features-1694185012011.md
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/cypress/support/intercepts/vpc.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/ListeningServices.tsx
  packages/manager/src/features/VPCs/VPCCreate/MultipleSubnetInput.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetCreateDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetCreateDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/utilities/subnets.ts
  packages/validation/src/vpcs.schema.ts
Labels: Approved, VPC

#9666 feat: [M3-7107] - Add AGLB Certificate Delete Dialog
  packages/manager/.changeset/pr-9666-upcoming-features-1694557714134.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/DeleteCertificateDialog.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerCertificates.tsx
  packages/manager/src/queries/aglb/certificates.ts
Labels: AGLB

#9661 feat: [M3-6751] - Edit Subnet drawer
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetEditDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetEditDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
Labels: Approved, VPC

#9595 test: [M3-6551] - Add Community Stackscripts integration tests
  packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/smoke-stackscripts-landing-page.spec.ts
Labels: Add'tl Approval Needed, Missing Changeset

#9669 chore: Remove `React.FC` from docs examples
  docs/development-guide/05-fetching-data.md
  docs/development-guide/06-performance.md
  docs/development-guide/11-feature-flags.md
  packages/api-v4/REACT.md
Labels: Add'tl Approval Needed, Documentation

#9667 fix: Billing Contact UI Regression from by MUI Update
  packages/manager/.changeset/pr-9667-fixed-1694576063628.md
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
Labels: UI

#9672 Fix: [M3-7116] Fix visual regression with Image Select option
  packages/manager/src/components/EnhancedSelect/Select.tsx
  packages/manager/src/components/EnhancedSelect/components/Option.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionOption.tsx
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/components/ImageSelect/index.tsx
  packages/manager/src/features/Help/Panels/SearchItem.tsx
  packages/manager/src/features/Images/ImageOption.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
Labels: Approved

#9638 feat: [UIE-6576] - Dbaas total disk size and used disk size
  packages/api-v4/.changeset/pr-9638-upcoming-features-1694022154737.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-9638-upcoming-features-1694022186629.md
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
  packages/manager/src/features/Events/eventMessageGenerator.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Project: DBaaS

#9658 feat: [M3-7060] - Add configuration docs for upcoming UUID update
  packages/manager/.changeset/pr-9658-added-1694206862050.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
  packages/manager/src/utilities/analytics.ts
Labels: Approved

#9659 change: [poc] - Better subnet validation behavior on VPCCreate page
  packages/manager/.changeset/pr-9659-changed-1694440105022.md
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
  packages/manager/src/utilities/formikErrorUtils.test.ts
  packages/manager/src/utilities/formikErrorUtils.ts
  packages/manager/src/utilities/subnets.test.ts
  packages/manager/src/utilities/subnets.ts
Labels: Approved, VPC

#9668 feat: [M3-7033] - Update Firewall Landing Device Column
  packages/manager/.changeset/pr-9668-upcoming-features-1694613000549.md
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.styles.ts
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls/LinodeFirewallsRow.tsx
Labels: Ready for Review, Nodebalancer Firewall UX

#9670 chore: [M3-7042] - DC-Specific Pricing Copy and Link Cleanup
  packages/manager/.changeset/pr-9670-upcoming-features-1694618602374.md
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/src/components/DynamicPriceNotice.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayDialog.tsx
  packages/manager/src/constants.ts
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
  packages/manager/src/features/Linodes/CloneLanding/Details.tsx
  packages/manager/src/features/Linodes/LinodesCreate/utilities.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
  packages/manager/src/utilities/pricing/constants.ts
  packages/manager/src/utilities/pricing/dynamicPricing.ts
Labels: UI, Approved, DC-Specific Pricing

#9671 fix: VPC Detail page document title
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPCs/index.tsx
  packages/manager/src/utilities/subnets.ts
Labels: Approved, VPC

#9675 feat: [M3-7108] - Add AGLB Configuration Delete Dialog
  packages/manager/.changeset/pr-9675-upcoming-features-1694635724766.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationAccordion.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/DeleteConfigurationDialog.tsx
  packages/manager/src/queries/aglb/configurations.ts
Labels: AGLB

#9645 feat: [M3-6993] – Add VPC data to Linode Detail header
  packages/manager/.changeset/pr-9645-upcoming-features-1694541839832.md
  packages/manager/src/components/EntityDetail/EntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/queries/vpcs.ts
Labels: VPC

#9683 fix: [M3-7138] - Fix Create Volume Drawer static pricing copy and misplaced helper text
  packages/manager/.changeset/pr-9683-fixed-1694731625764.md
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
Labels: Bug, Approved, DC-Specific Pricing

#9673 fix: [M3-7117] - Fix style consistency issues with NodeBalancer create flow panels
  packages/manager/.changeset/pr-9673-fixed-1694628742725.md
  packages/manager/src/features/NodeBalancers/NodeBalancerActiveCheck.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerPassiveCheck.tsx
Labels: Approved

#9674 test: [M3-7091] - Add integration tests for Cloud Manager invoices, DC-specific pricing
  packages/manager/cypress/e2e/core/account/smoke-billing-activity.spec.ts
  packages/manager/cypress/e2e/core/billing/billing-contact.spec.ts
  packages/manager/cypress/e2e/core/billing/billing-invoices.spec.ts
  packages/manager/cypress/e2e/core/billing/default-payment-method.spec.ts
  packages/manager/cypress/e2e/core/billing/google-pay.spec.ts
  packages/manager/cypress/e2e/core/billing/smoke-billing-activity.spec.ts
  packages/manager/cypress/support/intercepts/account.ts
  packages/manager/cypress/support/intercepts/profile.ts
  packages/manager/cypress/support/ui/index.ts
  packages/manager/cypress/support/ui/pagination.ts
  packages/manager/cypress/support/ui/user-menu.ts
  packages/manager/cypress/support/util/arrays.ts
  packages/manager/cypress/support/util/currency.ts
  packages/manager/src/components/PaginationControls/PaginationControls.tsx
  packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
Labels: Approved, DC-Specific Pricing

#9694 fix: [M3-7151] - Redis trademark changes
  packages/manager/CHANGELOG.md
  packages/manager/public/assets/redis.svg
  packages/manager/public/assets/redissentinelmarketplaceocc.svg
  packages/manager/public/assets/white/redis.svg
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
  packages/manager/src/features/OneClickApps/oneClickApps.ts
Labels: Marketplace, Ready for Review

#9696 Release v1.102.0 - master → develop
  packages/api-v4/.changeset/pr-9585-changed-1692736077405.md
  packages/api-v4/.changeset/pr-9638-upcoming-features-1694022154737.md
  packages/api-v4/.changeset/pr-9656-fixed-1694441991292.md
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/manager/.changeset/pr-9497-tech-stories-1691208190450.md
  packages/manager/.changeset/pr-9558-fixed-1692292498419.md
  packages/manager/.changeset/pr-9582-tech-stories-1692726989780.md
  packages/manager/.changeset/pr-9585-upcoming-features-1692736112038.md
  packages/manager/.changeset/pr-9591-upcoming-features-1692984602898.md
  packages/manager/.changeset/pr-9597-upcoming-features-1693255450332.md
  packages/manager/.changeset/pr-9598-upcoming-features-1693322571328.md
  packages/manager/.changeset/pr-9599-upcoming-features-1693256682508.md
  packages/manager/.changeset/pr-9600-tech-stories-1693257951344.md
  packages/manager/.changeset/pr-9606-upcoming-features-1693548349929.md
  packages/manager/.changeset/pr-9616-upcoming-features-1693507025003.md
  packages/manager/.changeset/pr-9619-fixed-1693518126299.md
  packages/manager/.changeset/pr-9620-upcoming-features-1694457457440.md
  packages/manager/.changeset/pr-9625-removed-1693588382719.md
  packages/manager/.changeset/pr-9638-upcoming-features-1694022186629.md
  packages/manager/.changeset/pr-9639-fixed-1694031609043.md
  packages/manager/.changeset/pr-9640-upcoming-features-1694033247968.md
  packages/manager/.changeset/pr-9643-fixed-1694103276021.md
  packages/manager/.changeset/pr-9645-upcoming-features-1694541839832.md
  packages/manager/.changeset/pr-9647-upcoming-features-1694186188307.md
  packages/manager/.changeset/pr-9648-fixed-1694120022815.md
  packages/manager/.changeset/pr-9652-upcoming-features-1694185012011.md
  packages/manager/.changeset/pr-9658-added-1694206862050.md
  packages/manager/.changeset/pr-9659-changed-1694440105022.md
  packages/manager/.changeset/pr-9663-upcoming-features-1694534723160.md
  packages/manager/.changeset/pr-9665-fixed-1694552506393.md
  packages/manager/.changeset/pr-9666-upcoming-features-1694557714134.md
  packages/manager/.changeset/pr-9667-fixed-1694576063628.md
  packages/manager/.changeset/pr-9670-upcoming-features-1694618602374.md
  packages/manager/.changeset/pr-9673-fixed-1694628742725.md
  packages/manager/.changeset/pr-9675-upcoming-features-1694635724766.md
  packages/manager/.changeset/pr-9683-fixed-1694731625764.md
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/public/assets/redis.svg
  packages/manager/public/assets/redissentinelmarketplaceocc.svg
  packages/manager/public/assets/white/redis.svg
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Master → Develop

#9690 change: [M3-7145] - Update DC Specific Pricing Notices
  packages/manager/.changeset/pr-9690-upcoming-features-1695050611174.md
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/src/components/DynamicPriceNotice.tsx
  packages/manager/src/components/SelectRegionPanel/RegionHelperText.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.test.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/utilities/pricing/dynamicPricing.ts
  packages/manager/src/utilities/pricing/linodes.test.ts
  packages/manager/src/utilities/pricing/linodes.ts
Labels: Approved, DC-Specific Pricing

#9649 fix: [M3-7085] e2e coverage for Linode Config Flows
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/linodes/rescue-linode.spec.ts
  packages/manager/cypress/support/intercepts/configs.ts
  packages/manager/cypress/support/intercepts/linodes.ts
  packages/manager/cypress/support/ui/select.ts
  packages/manager/cypress/support/util/linode-utils.ts
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx
  packages/manager/src/features/Linodes/CloneLanding/CloneLanding.tsx
  packages/manager/src/features/Linodes/CloneLanding/Details.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
Labels: e2e, Approved

#9692 feat: [M3-7144] - MNTP Dialog Updates for DC-specific pricing
  packages/manager/.changeset/pr-9692-upcoming-features-1695054097678.md
  packages/manager/src/components/Dialog/Dialog.tsx
  packages/manager/src/components/TooltipIcon.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayDialog.test.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayDialog.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayDialogHeader.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayUsage.test.tsx
  packages/manager/src/components/TransferDisplay/utils.test.tsx
  packages/manager/src/components/TransferDisplay/utils.ts
Labels: Approved, DC-Specific Pricing

#9682 feat: [M3-6984] Test coverage for SelectRegionPanel
  packages/manager/src/components/DynamicPriceNotice.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/SelectRegionPanel/RegionHelperText.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.test.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/constants.ts
  packages/manager/src/features/Linodes/LinodesCreate/utilities.tsx
  packages/manager/src/utilities/pricing/constants.ts
Labels: Approved, DC-Specific Pricing

#9676 test: [M3-7100] - Add DC-specific pricing to LKE update integration test
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
Labels: Approved, DC-Specific Pricing

#9681 test: [M3-7068] - Add integration tests for Linode migration dialog DC-specific pricing
  packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: DC-Specific Pricing

#9693 feat: [M3-7017] - Update firewall events
  packages/manager/.changeset/pr-9693-upcoming-features-1695157943571.md
  packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
  packages/manager/src/features/Events/eventMessageGenerator.ts
Labels: Approved, Nodebalancer Firewall UX

#9697 fix: [M3-7155] - Link Accessibility & Markup on Billing Detail page
  packages/manager/.changeset/pr-9697-fixed-1695133545193.md
  packages/manager/cypress/e2e/core/billing/billing-invoices.spec.ts
  packages/manager/src/components/DownloadCSV/DownloadCSV.tsx
  packages/manager/src/components/Link.tsx
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
  packages/manager/src/features/Account/index.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Billing/InvoiceDetail/index.ts
  packages/manager/src/features/Billing/index.tsx
Labels: Approved

#9657 feat: [M3-7031] - Add AGLB Create Service Target Drawer
  packages/api-v4/src/aglb/service-targets.ts
  packages/api-v4/src/aglb/types.ts
  packages/manager/.changeset/pr-9657-upcoming-features-1694451006203.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-service-targets.spec.ts
  packages/manager/cypress/support/intercepts/load-balancers.ts
  packages/manager/src/components/Autocomplete/Autocomplete.styles.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/factories/aglb.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CertificateSelect.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerServiceTargets.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/AddEndpointForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/CreateServiceTargetDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/DeleteServiceTargetDialog.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/EndpointTable.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/EndpointTable.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/LinodeOrIPSelect.tsx
  packages/manager/src/foundations/themes/dark.ts
  packages/manager/src/foundations/themes/light.ts
  packages/manager/src/queries/aglb/serviceTargets.ts
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, AGLB

#9654 feat: [M3-7159] - Update Enable Object Storage modal for beta DC-specific pricing
  packages/manager/.changeset/pr-9654-upcoming-features-1694534244928.md
  packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.smoke.spec.ts
  packages/manager/cypress/support/intercepts/object-storage.ts
  packages/manager/cypress/support/intercepts/regions.ts
  packages/manager/cypress/support/ui/accordion.ts
  packages/manager/cypress/support/ui/index.ts
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.test.tsx
  packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/utilities/pricing/constants.ts
  packages/manager/src/utilities/pricing/dynamicPricing.ts
Labels: Approved, DC-Specific Pricing

#9630 feat: [M3-7020] - Update Create Firewall drawer
  packages/manager/.changeset/pr-9630-upcoming-features-1694699100182.md
  packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
  packages/manager/cypress/support/ui/tab-list.ts
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
Labels: Approved, Nodebalancer Firewall UX

#9705 fix: [M3-7105] - Highlight.js Theme Switching
  packages/manager/.changeset/pr-9705-fixed-1695242987904.md
  packages/manager/package.json
  packages/manager/src/App.test.tsx
  packages/manager/src/App.tsx
  packages/manager/src/LinodeThemeWrapper.tsx
  packages/manager/src/components/Button/Button.test.tsx
  packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.tsx
  packages/manager/src/components/LandingHeader/LandingHeader.test.tsx
  packages/manager/src/env.d.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromImageContent.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromLinodeContent.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx
  packages/manager/src/index.tsx
  packages/manager/src/utilities/testHelpers.tsx
  packages/manager/src/utilities/theme.ts
Labels: Bug

#9702 fix: [M3-7008] - Invoice and Payment `id` wrapping in generated PDFs
  packages/manager/.changeset/pr-9702-fixed-1695158299608.md
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Bug, Approved

#9612 refactor: [M3-6274] - MUI v5 Migration - `SRC > Features > Longview` Pt2: Longview Landing and Root folder
  packages/manager/.changeset/pr-9612-tech-stories-1693429144649.md
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/CommonStyles.styles.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.styles.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/GaugesSection.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Installation.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.styles.ts
  packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/RAM.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/RAM.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/Storage.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/Swap.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewActionMenu.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.styles.ts
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientInstructions.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.styles.ts
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClients.styles.ts
  packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewDeleteDialog.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewList.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewListRows.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.styles.ts
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
  packages/manager/src/features/Longview/LongviewLanding/RestrictedUserLabel.tsx
  packages/manager/src/features/Longview/LongviewLanding/SubscriptionDialog.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/SubscriptionDialog.tsx
  packages/manager/src/features/Longview/LongviewLanding/index.ts
  packages/manager/src/features/Longview/LongviewPackageDrawer.tsx
  packages/manager/src/features/Longview/LongviewPackageRow.tsx
  packages/manager/src/features/Longview/index.tsx
  packages/manager/src/features/Longview/request.ts
  packages/manager/src/features/Longview/shared/InstallationInstructions.styles.ts
  packages/manager/src/features/Longview/shared/InstallationInstructions.tsx
  packages/manager/src/features/Longview/shared/TimeRangeSelect.tsx
  packages/manager/src/features/Longview/shared/USAGE.md
Labels: Approved, Ready for Review, Project: MUI v5 Migration

#9700 fix: [M3-7078] codeQL warning with analytics.ts
  packages/manager/.changeset/pr-9700-fixed-1695156150613.md
  packages/manager/src/utilities/analytics.ts
Labels: Approved

#9712 Release v1.103.0 - release → staging
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
Labels: Out of Band Release

#9713 Release v1.103.0 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
Labels: Out of Band Release

#9715 test: Mock DBaaS feature flag in Cypress tests
  packages/manager/cypress/e2e/core/databases/create-database.spec.ts
  packages/manager/cypress/e2e/core/databases/delete-database.spec.ts
  packages/manager/cypress/e2e/core/databases/update-database.spec.ts
Labels: Ready for Review

#9687 feat: [M3-6752] - Assign Linodes to Subnet drawer
  packages/api-v4/.changeset/pr-9687-changed-1695235363178.md
  packages/api-v4/src/linodes/configs.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-9687-upcoming-features-1695074900291.md
  packages/manager/src/components/CollapsibleTable/CollapsibleRow.tsx
  packages/manager/src/components/DownloadCSV/DownloadCSV.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.stories.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.test.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.styles.ts
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/features/VPCs/constants.ts
  packages/manager/src/hooks/useUnassignLinode.ts
  packages/manager/src/queries/linodes/configs.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/validation/.changeset/pr-9687-upcoming-features-1695235474879.md
  packages/validation/src/linodes.schema.ts
Labels: @linode/api-v4, @linode/validation, Approved, Ready for Review, VPC

#9710 feat: [M3-7157] - Only show IPv4s specific to a linode-subnet relationship on VPC details page
  packages/manager/.changeset/pr-9710-upcoming-features-1695410168923.md
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/features/VPCs/utils.test.ts
  packages/manager/src/features/VPCs/utils.ts
Labels: Approved, VPC

#9707 test: [M3-7101] - Add integration tests for Kubernetes Create DC-specific pricing
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
Labels: Approved, DC-Specific Pricing

#9720 chore: [M3-7187] - Improvements to Volumes Create
  packages/manager/.changeset/pr-9720-added-1695748436771.md
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
  packages/manager/src/features/Volumes/Volumes.tsx
  packages/manager/src/features/Volumes/VolumesLandingEmptyState.tsx
Labels: Enhancement, Approved

#9718 feat: [M3-7120] - Create VPC Feedback
  packages/manager/.changeset/pr-9718-upcoming-features-1695736606321.md
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
  packages/manager/src/utilities/subnets.test.ts
  packages/manager/src/utilities/subnets.ts
Labels: Approved, VPC

#9593 feat: [M3-6809] - Add AGLB details - Routes Tab
  packages/api-v4/src/aglb/types.ts
  packages/manager/.changeset/pr-9593-upcoming-features-1692935903332.md
  packages/manager/src/factories/aglb.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerDetail.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRoutes.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.tsx
  packages/manager/src/queries/aglb/routes.ts
Labels: Approved, AGLB

#9726 fix: [M3-7191] - Missing primary and secondary action button labels in Delete SSH Key dialog and Clone Domain drawer
  packages/manager/.changeset/pr-9726-fixed-1695827222025.md
  packages/manager/src/components/ActionsPanel/ActionsPanel.test.tsx
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/features/Domains/CloneDomainDrawer.tsx
  packages/manager/src/features/Profile/SSHKeys/DeleteSSHKeyDialog.test.tsx
  packages/manager/src/features/Profile/SSHKeys/DeleteSSHKeyDialog.tsx
Labels: Bug

#9721 fix: [M3-7192] - Account Users `Add A User` Button Alignment
  packages/manager/.changeset/pr-9721-fixed-1695755881914.md
  packages/manager/src/features/Users/UsersLanding.tsx
Labels: Bug, UI

#9722 fix: [M3-7196] - Database Access Drawer Incorrect Loading State
  packages/manager/.changeset/pr-9722-fixed-1695762935283.md
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
Labels: Bug, UI

#9635 feat: [M3-6731] – Add VPC and Firewall sections in Linode Create flow
  packages/api-v4/.changeset/pr-9635-upcoming-features-1695321404295.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-9635-upcoming-features-1695321565271.md
  packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.test.tsx
  packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
  packages/manager/src/containers/account.container.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AttachVLAN.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.styles.ts
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VLANAccordion.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/constants.ts
  packages/manager/src/queries/vpcs.ts
  packages/validation/src/linodes.schema.ts
Labels: @linode/api-v4, @linode/validation, Approved, VPC

#9701 test: [M3-7069] - Add Cypress integration tests for Linode Create DC-specific pricing
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: Approved, DC-Specific Pricing
