Repository linode/manager, pull requests merged in 2023-07, with the labels that each got.

#9342 fix: Fix miscellaneous Cypress test flake
  packages/manager/cypress/e2e/core/account/default-payment-method.spec.ts
  packages/manager/cypress/e2e/core/account/google-pay.spec.ts
  packages/manager/cypress/e2e/core/images/create-linode-from-image.spec.ts
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
Labels: e2e, Approved, Missing Changeset

#9348 fix: Fix Linode landing page delete smoke test flake
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
Labels: e2e, Approved, Missing Changeset

#9268 refactor: [M3-6350] - MUI v5 Migration - `Components > InlineMenuAction`
  packages/manager/.changeset/pr-9268-tech-stories-1686863251318.md
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/components/Button/Button.test.tsx
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/Button/StyledActionButton.ts
  packages/manager/src/components/Drawer/Drawer.tsx
  packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.tsx
  packages/manager/src/components/InlineMenuAction/InlineMenuAction.stories.tsx
  packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx
  packages/manager/src/components/InlineMenuAction/index.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupActionMenu.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMenuItem.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
  packages/manager/src/features/Domains/DomainActionMenu.tsx
  packages/manager/src/features/EntityTransfers/TransfersPendingActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu.tsx
  packages/manager/src/features/Images/ImagesActionMenu.tsx
  packages/manager/src/features/Kubernetes/ClusterList/ClusterActionMenu.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/MutateDrawer/MutateDrawer.tsx
  packages/manager/src/features/Managed/Contacts/ContactsActionMenu.tsx
  packages/manager/src/features/Managed/Credentials/CredentialActionMenu.tsx
  packages/manager/src/features/Managed/Monitors/MonitorActionMenu.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyMenu.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/FolderActionMenu.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketActionMenu.tsx
  packages/manager/src/features/Profile/APITokens/APITokenMenu.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevices.tsx
  packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClientActionMenu.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeyActionMenu.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptActionMenu.tsx
  packages/manager/src/features/Users/UsersActionMenu.tsx
  packages/manager/src/features/Volumes/VolumesActionMenu.tsx
Labels: Add'tl Approval Needed, Project: MUI v5 Migration

#9349 fix: [M3-6627] - Fix `cy.defer()` TypeScript errors
  packages/manager/cypress/e2e/core/account/service-transfer.spec.ts
  packages/manager/cypress/e2e/core/account/smoke-billing-activity.spec.ts
  packages/manager/cypress/e2e/core/domains/smoke-create-domain-records.spec.ts
  packages/manager/cypress/e2e/core/domains/smoke-delete-domain.spec.ts
  packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/delete-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
  packages/manager/cypress/e2e/core/linodes/rescue-linode.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/clone-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/delete-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/resize-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/update-volume.spec.ts
  packages/manager/cypress/support/commands.ts
  packages/manager/cypress/support/e2e.ts
  packages/manager/cypress/support/index.d.ts
  packages/manager/cypress/support/util/backoff.ts
Labels: e2e, Approved, Missing Changeset

#9350 chore: [M3-6777] - Rename Cypress functions and variables related to secrets
  packages/manager/cypress/e2e/core/account/add-oauth-app.spec.ts
  packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts
  packages/manager/cypress/e2e/core/account/reset-oauth-app.spec.ts
  packages/manager/cypress/e2e/core/account/third-party-access-tokens.spec.ts
  packages/manager/cypress/e2e/core/account/two-factor-auth.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/access-keys.smoke.spec.ts
  packages/manager/cypress/support/intercepts/object-storage.ts
  packages/manager/cypress/support/util/random.ts
  packages/manager/scripts/prebuild.mjs
Labels: Approved, Missing Changeset

#9175 refactor: [M3-6063] - Refactor components to use TypeToConfirmDialog component
  packages/manager/.changeset/pr-9175-changed-1685739474444.md
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.stories.tsx
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.test.tsx
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
  packages/manager/src/features/Account/CloseAccountDialog.tsx
  packages/manager/src/features/Account/EnableObjectStorage.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DeleteLinodeDialog.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDeleteDialog.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/Volumes/DestructiveVolumeDialog.tsx
Labels: Approved, Project: MUI v5 Migration

#9351 test: [M3-6054] - Add Cypress test coverage for Linode Create via CLI dialog
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
Labels: Add'tl Approval Needed, e2e, Missing Changeset

#9366 fix: NVM should be NVMe
  packages/manager/.changeset/pr-9366-fixed-1688578241873.md
  packages/manager/src/features/Volumes/VolumesLandingEmptyStateData.ts
Labels: Bug, Approved

#9359 refactor: [M3-6393] - MUI v5 - `Components > Snackbar`
  packages/manager/.changeset/pr-9359-tech-stories-1688401214973.md
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.stories.mdx
  packages/manager/src/components/Notice/Notice.stories.mdx
  packages/manager/src/components/Notice/Notice.tsx
  packages/manager/src/components/SnackBar/index.ts
  packages/manager/src/components/Snackbar/CloseSnackbar.tsx
  packages/manager/src/components/Snackbar/Snackbar.tsx
  packages/manager/src/features/Account/AutoBackups.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Events/EventsLanding.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Kubernetes/ClusterList/ClusterActionMenu.tsx
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeKubernetesVersionBanner.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.tsx
  packages/manager/src/features/ToastNotifications/ToastNotifications.stories.mdx
  packages/manager/src/features/ToastNotifications/ToastNotifications.stories.tsx
  packages/manager/src/foundations/themes/light.ts
  packages/manager/src/index.tsx
Labels: Storybook, Approved, Project: MUI v5 Migration

#9363 feat: [M3-6779] - AGLB api-v4 endpoints
  packages/api-v4/.changeset/pr-9363-added-1688564871453.md
  packages/api-v4/src/aglb/entrypoints.ts
  packages/api-v4/src/aglb/loadbalancers.ts
  packages/api-v4/src/aglb/routes.ts
  packages/api-v4/src/aglb/service-targets.ts
  packages/api-v4/src/aglb/types.ts
Labels: @linode/api-v4, Approved, AGLB

#9368 feat: [M3-6840] - Add VPC feature flag
  packages/manager/.changeset/pr-9368-added-1688662246154.md
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
Labels: Approved, VPC

#9361 feat: [M3-6722] – VPC endpoints, validation, & React Query queries
  packages/api-v4/.changeset/pr-9361-added-1688422080839.md
  packages/api-v4/src/index.ts
  packages/api-v4/src/vpcs/index.ts
  packages/api-v4/src/vpcs/types.ts
  packages/api-v4/src/vpcs/vpcs.ts
  packages/manager/.changeset/pr-9361-added-1688421871670.md
  packages/manager/src/queries/vpcs.ts
  packages/validation/.changeset/pr-9361-added-1688422154757.md
  packages/validation/src/index.ts
  packages/validation/src/vpcs.schema.ts
Labels: @linode/api-v4, @linode/validation, Approved, VPC

#9364 feat: [M3-6789] - Improve failed backup error messaging
  packages/manager/.changeset/pr-9364-added-1688576551150.md
  packages/manager/src/eventMessageGenerator.ts
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/CaptureSnapshot.tsx
  packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
Labels: UI, Approved

#9358 fix: wording in "My Profile" -> "Login and Authentication"
  packages/manager/.changeset/pr-9358-fixed-1688405470106.md
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/QRCodeForm.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
Labels: Approved

#9315 test: [M3-6505] - Add StackScript Update/Delete E2E Tests
  packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/delete-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/smoke-stackscripts-landing-page.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/update-stackscripts.spec.ts
  packages/manager/cypress/support/intercepts/stackscripts.ts
Labels: Approved, Missing Changeset

#9285 refactor: Upgrade LaunchDarkly SDK and use anonymous users
  packages/manager/.changeset/pr-9285-tech-stories-1687517120223.md
  packages/manager/package.json
  packages/manager/src/IdentifyUser.tsx
  packages/manager/src/__data__/ldClient.ts
  packages/manager/src/containers/withFeatureFlagProvider.container.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/dev-tools/MockDataTool.tsx
  yarn.lock
Labels: Approved

#9329 refactor: [M3-6385] – MUI v5 Migration - `SRC > Components > SectionErrorBoundary`
  packages/manager/.changeset/pr-9329-tech-stories-1687892455096.md
  packages/manager/src/components/AccountActivation/AccountActivationLanding.tsx
  packages/manager/src/components/ErrorBoundary.tsx
  packages/manager/src/components/SectionErrorBoundary/SectionErrorBoundary.tsx
  packages/manager/src/components/SectionErrorBoundary/index.ts
  packages/manager/src/components/SupportLink/SupportLink.tsx
  packages/manager/src/features/Help/SupportSearchLanding/HelpResources.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/Managed/SupportWidget.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.test.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
Labels: Approved, Project: MUI v5 Migration

#9374 feat: [M3-6842] - Update Metadata copy
  packages/manager/.changeset/pr-9374-changed-1688763763302.md
  packages/manager/cypress/e2e/core/account/change-username.spec.ts
  packages/manager/cypress/e2e/core/account/security-questions.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
  packages/manager/src/components/TextField.tsx
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
Labels: Project: Metadata, Approved

#9378 Update Changelog for v1.97.0 release
  packages/manager/.changeset/pr-9374-changed-1688763763302.md
  packages/manager/CHANGELOG.md
Labels: Approved

#9379 fix: minor css regression account > billing history dropdowns
  packages/manager/src/components/EnhancedSelect/Select.tsx
Labels: Approved, Missing Changeset

#9384 Master to develop v1.97.0
  packages/api-v4/CHANGELOG.md
  packages/api-v4/package.json
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/account/change-username.spec.ts
  packages/manager/cypress/e2e/core/account/security-questions.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
  packages/manager/package.json
  packages/manager/src/components/EnhancedSelect/Select.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
  packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/validation/CHANGELOG.md
  packages/validation/package.json
Labels: Approved

#9372 test: [M3-6627] - Add region tests for Linodes
  packages/manager/cypress.config.ts
  packages/manager/cypress/e2e/region/hello-world.spec.ts
  packages/manager/cypress/e2e/region/linodes/create-linode.spec.ts
  packages/manager/cypress/e2e/region/linodes/delete-linode.spec.ts
  packages/manager/cypress/e2e/region/linodes/update-linode.spec.ts
  packages/manager/cypress/support/constants/timeouts.ts
  packages/manager/cypress/support/intercepts/linodes.ts
  packages/manager/cypress/support/util/backoff.ts
  packages/manager/cypress/support/util/promises.ts
  packages/manager/cypress/support/util/regions.ts
Labels: Approved

#9381 Chore: Release v.1.97.0: Delete changesets
  packages/api-v4/.changeset/pr-9335-changed-1687980892035.md
  packages/api-v4/.changeset/pr-9361-added-1688422080839.md
  packages/api-v4/.changeset/pr-9363-added-1688564871453.md
  packages/manager/.changeset/pr-9175-changed-1685739474444.md
  packages/manager/.changeset/pr-9268-tech-stories-1686863251318.md
  packages/manager/.changeset/pr-9282-tech-stories-1687053909997.md
  packages/manager/.changeset/pr-9285-tech-stories-1687517120223.md
  packages/manager/.changeset/pr-9286-added-1687296191023.md
  packages/manager/.changeset/pr-9288-added-1687360493313.md
  packages/manager/.changeset/pr-9289-fixed-1687364211275.md
  packages/manager/.changeset/pr-9290-added-1687466679796.md
  packages/manager/.changeset/pr-9291-tech-stories-1687369699291.md
  packages/manager/.changeset/pr-9292-tech-stories-1687376650053.md
  packages/manager/.changeset/pr-9295-changed-1687441083123.md
  packages/manager/.changeset/pr-9296-fixed-1687442580014.md
  packages/manager/.changeset/pr-9297-tech-stories-1687467224725.md
  packages/manager/.changeset/pr-9298-fixed-1687455527847.md
  packages/manager/.changeset/pr-9299-tech-stories-1687458748557.md
  packages/manager/.changeset/pr-9301-fixed-1687543469745.md
  packages/manager/.changeset/pr-9306-fixed-1687536357483.md
  packages/manager/.changeset/pr-9310-tech-stories-1687550766529.md
  packages/manager/.changeset/pr-9313-tech-stories-1687805591350.md
  packages/manager/.changeset/pr-9318-tech-stories-1687825157533.md
  packages/manager/.changeset/pr-9319-tech-stories-1687875908852.md
  packages/manager/.changeset/pr-9320-tech-stories-1687878769530.md
  packages/manager/.changeset/pr-9321-tech-stories-1687879529410.md
  packages/manager/.changeset/pr-9322-tech-stories-1687882091838.md
  packages/manager/.changeset/pr-9323-tech-stories-1687882441444.md
  packages/manager/.changeset/pr-9325-tech-stories-1687887654571.md
  packages/manager/.changeset/pr-9326-tech-stories-1687889013916.md
  packages/manager/.changeset/pr-9327-tech-stories-1687891798862.md
  packages/manager/.changeset/pr-9328-tech-stories-1687891912950.md
  packages/manager/.changeset/pr-9332-fixed-1687902148264.md
  packages/manager/.changeset/pr-9338-tech-stories-1687997394786.md
  packages/manager/.changeset/pr-9339-tech-stories-1688002163233.md
  packages/manager/.changeset/pr-9340-tech-stories-1688049933151.md
  packages/manager/.changeset/pr-9352-fixed-1688140397688.md
  packages/manager/.changeset/pr-9353-changed-1688145967385.md
  packages/manager/.changeset/pr-9355-fixed-1688147944694.md
  packages/manager/.changeset/pr-9358-fixed-1688405470106.md
  packages/manager/.changeset/pr-9359-tech-stories-1688401214973.md
  packages/manager/.changeset/pr-9360-fixed-1688405874821.md
  packages/manager/.changeset/pr-9361-added-1688421871670.md
  packages/manager/.changeset/pr-9364-added-1688576551150.md
  packages/manager/.changeset/pr-9366-fixed-1688578241873.md
  packages/manager/.changeset/pr-9368-added-1688662246154.md
  packages/manager/.changeset/pr-9369-tech-stories-1688664760672.md
  packages/manager/.changeset/pr-9370-added-1688666315054.md
  packages/validation/.changeset/pr-9336-fixed-1687983041491.md
  packages/validation/.changeset/pr-9361-added-1688422154757.md
Labels: Approved

#9376 feat: [M3-6822] - Add initial routes, folders, pages, and tabs for AGLB
  packages/manager/.changeset/pr-9376-tech-stories-1689016335781.md
  packages/manager/src/GoTo.tsx
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/LoadBalancers/EntryPoints/EntryPointCreate/EntryPointCreate.tsx
  packages/manager/src/features/LoadBalancers/EntryPoints/EntryPointLanding/EntryPointLanding.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerCreate.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerDetail.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerLanding.tsx
  packages/manager/src/features/LoadBalancers/Routes/RouteCreate/RouteCreate.tsx
  packages/manager/src/features/LoadBalancers/Routes/RouteLanding/RouteLanding.tsx
  packages/manager/src/features/LoadBalancers/index.tsx
Labels: Approved, AGLB

#9367 Feat: [M3-5540] Table rows hover state + Table v7 stories
  packages/manager/.changeset/pr-9367-added-1688668684455.md
  packages/manager/.storybook/preview.tsx
  packages/manager/src/components/Table/Table.stories.mdx
  packages/manager/src/components/Table/Table.stories.tsx
  packages/manager/src/components/Table/Table.styles.ts
  packages/manager/src/components/Table/Table.tsx
  packages/manager/src/components/TableRow/TableRow.styles.ts
  packages/manager/src/components/TableRow/TableRow.tsx
  packages/manager/src/components/TableRowEmpty/TableRowEmpty.stories.mdx
  packages/manager/src/components/TableRowEmpty/TableRowEmpty.stories.tsx
  packages/manager/src/components/TableRowEmpty/TableRowEmpty.tsx
  packages/manager/src/components/TableRowError/TableRowError.stories.mdx
  packages/manager/src/components/TableRowError/TableRowError.stories.tsx
  packages/manager/src/components/TableRowError/TableRowError.tsx
  packages/manager/src/components/TableRowLoading/TableRowLoading.stories.mdx
  packages/manager/src/components/TableRowLoading/TableRowLoading.stories.tsx
  packages/manager/src/components/TableRowLoading/TableRowLoading.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.style.ts
Labels: Approved

#9375 feat: [M3-6781] Add MSW endpoints with factories for AGLB
  packages/api-v4/src/aglb/types.ts
  packages/manager/src/factories/aglb.ts
  packages/manager/src/factories/index.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: @linode/api-v4, Approved, AGLB

#9362 fix: [M3-6834]: Misleading MNTP percentage for accounts with no active services
  packages/manager/.changeset/pr-9362-fixed-1688576649790.md
  packages/manager/src/components/BarPercent/BarPercent.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplay.test.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplay.tsx
Labels: UI, Approved

#9371 fix: [M3-6188] - Fix TopMenuIcon tooltips
  packages/manager/.changeset/pr-9371-fixed-1688749077631.md
  packages/manager/src/constants.ts
  packages/manager/src/features/TopMenu/Community.tsx
  packages/manager/src/features/TopMenu/Help.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/features/TopMenu/TopMenuIcon.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
Labels: Accessibility, Approved

#9395 chore: Fix broken Linode landing table top bar navigation test
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
Labels: Approved

#9365 ci: [M3-6837] - Allow Cypress runs to be parallelized without reliance on third party services
  docker-compose.yml
  docs/development-guide/08-testing.md
  packages/manager/Dockerfile
  packages/manager/cypress.config.ts
  packages/manager/cypress/support/plugins/junit-report.ts
  packages/manager/cypress/support/plugins/split-run.ts
  packages/manager/package.json
  yarn.lock
Labels: Proof of Concept, e2e, Approved

#9400 Chore: Enable local storage for MSW feature flags
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
Labels: Approved

#9404 Feat: [M3-6805] AGLB Primary Nav Entry
  packages/manager/.changeset/pr-9404-added-1689282822245.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-navigation.spec.ts
  packages/manager/cypress/support/intercepts/feature-flags.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
Labels: Approved, AGLB

#9405 Feat: [M3-6806] AGLB - Add LoadBalancer create menu entry
  packages/manager/.changeset/pr-9405-added-1689345233361.md
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.test.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Labels: Approved, AGLB

#9390 feat: [M3-6723] – VPC Subnet endpoints, validation, & React Query queries
  packages/api-v4/.changeset/pr-9390-added-1689111404354.md
  packages/api-v4/src/vpcs/types.ts
  packages/api-v4/src/vpcs/vpcs.ts
  packages/manager/.changeset/pr-9390-tech-stories-1689111377085.md
  packages/manager/src/queries/vpcs.ts
  packages/validation/.changeset/pr-9390-added-1689111447323.md
  packages/validation/src/vpcs.schema.ts
Labels: @linode/api-v4, @linode/validation, Approved, VPC

#9397 feat: [M3-6811] - Add AGLB Service Target landing page
  packages/api-v4/src/aglb/service-targets.ts
  packages/manager/.changeset/pr-9397-tech-stories-1689273448414.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-service-targets.spec.ts
  packages/manager/cypress/support/intercepts/feature-flags.ts
  packages/manager/cypress/support/intercepts/load-balancers.ts
  packages/manager/src/factories/aglb.ts
  packages/manager/src/features/LoadBalancers/EntryPoints/EntryPointCreate/EntryPointCreate.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerDetail.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerLanding.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetCreate/ServiceTargetCreate.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetActionMenu.test.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetActionMenu.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetLanding.test.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetLanding.tsx
  packages/manager/src/features/LoadBalancers/ServiceTargets/ServiceTargetLanding/ServiceTargetRow.tsx
  packages/manager/src/features/LoadBalancers/index.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/aglb/serviceTargets.ts
Labels: @linode/api-v4, Approved, AGLB

#9337 chore: [M3-6803] - Use latest `@sentry/react` package and enable performance monitoring
  packages/manager/.changeset/pr-9337-tech-stories-1687990748857.md
  packages/manager/package.json
  packages/manager/src/App.tsx
  packages/manager/src/components/ErrorBoundary.tsx
  packages/manager/src/exceptionReporting.ts
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalErrorBoundary.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/manager/src/initSentry.ts
  yarn.lock
Labels: Dependencies, Approved

#9409 M3-6577: Add Cypress coverage for Linode deletion from details page
  packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: Approved, Missing Changeset

#9406 refactor: [M3-6325] – MUI v5 Migration - `SRC > Components > DocumentTitle`
  packages/manager/.changeset/pr-9406-tech-stories-1689347139957.md
  packages/manager/src/App.tsx
  packages/manager/src/components/DocumentTitle/DocumentTitle.tsx
Labels: Approved, Project: MUI v5 Migration

#9420 refactor: [M3-6342] - MUI v5 Migration - SRC > Component > GaugePercent
  packages/manager/.changeset/pr-9420-tech-stories-1689780372828.md
  packages/manager/src/components/GaugePercent/GaugePercent.stories.mdx
  packages/manager/src/components/GaugePercent/GaugePercent.styles.ts
  packages/manager/src/components/GaugePercent/GaugePercent.tsx
  packages/manager/src/components/GaugePercent/index.ts
  packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/RAM.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/Storage.tsx
  packages/manager/src/features/Longview/LongviewLanding/Gauges/Swap.tsx
Labels: Approved, Project: MUI v5 Migration

#9347 refactor: [M3-6625] - Make changes to facilitate Cloud Manager region test pipeline
  Jenkinsfile-region-tests.groovy
  docker-compose.yml
  docs/development-guide/08-testing.md
  packages/manager/cypress.config.ts
  packages/manager/cypress/support/plugins/authenticate-api.ts
  packages/manager/cypress/support/plugins/fetch-linode-regions.ts
  packages/manager/cypress/support/plugins/oauth-token-check.ts
Labels: Wait to Merge, e2e, Approved, Missing Changeset

#9414 feat: [M3-6732] - Make VLAN section in Linode Create an Accordion
  packages/manager/.changeset/pr-9414-changed-1689694769486.md
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AttachVLAN.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VLANAccordion.tsx
Labels: Approved, Ready for Review, VPC

#9426 fix: `withDocumentTitleProvider` type-checking error
  packages/manager/src/components/DocumentTitle/DocumentTitle.tsx
Labels: Approved, Missing Changeset

#9417 fix: [M3-6799] - Linode Select Dropdown Z-index
  packages/manager/.changeset/pr-9417-fixed-1689705981191.md
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.styles.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelectV2.tsx
Labels: Bug, Approved

#9423 refactor: [M3-6900] - MUI v5 Migration - `SRC > Components > Drawer`
  packages/manager/.changeset/pr-9423-tech-stories-1689738958743.md
  packages/manager/src/components/Drawer.stories.tsx
  packages/manager/src/components/Drawer.tsx
  packages/manager/src/components/Drawer/Drawer.stories.mdx
  packages/manager/src/components/Drawer/index.ts
  packages/manager/src/components/SideMenu.tsx
  packages/manager/src/components/TagCell/TagDrawer.tsx
  packages/manager/src/components/core/Drawer.ts
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/EditBillingContactDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
  packages/manager/src/features/Domains/CloneDomainDrawer.tsx
  packages/manager/src/features/Domains/DomainRecordDrawer.tsx
  packages/manager/src/features/Domains/DomainZoneImportDrawer.tsx
  packages/manager/src/features/Domains/EditDomainDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx
  packages/manager/src/features/LinodeConfigSelectionDrawer/LinodeConfigSelectionDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/EditIPRDNSDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/EditRangeRDNSDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/ViewIPDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/ViewRDNSDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/ViewRangeDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateDiskDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/RenameDiskDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/ResizeDiskDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/MutateDrawer/MutateDrawer.tsx
  packages/manager/src/features/Longview/LongviewPackageDrawer.tsx
  packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
  packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
  packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
  packages/manager/src/features/Managed/MonitorDrawer.tsx
  packages/manager/src/features/Managed/Monitors/HistoryDrawer.tsx
  packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/ViewPermissionsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/CreateFolderDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/EditAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.tsx
  packages/manager/src/features/Profile/OAuthClients/CreateOAuthClientDrawer.tsx
  packages/manager/src/features/Profile/OAuthClients/EditOAuthClientDrawer.tsx
  packages/manager/src/features/Profile/SSHKeys/CreateSSHKeyDrawer.tsx
  packages/manager/src/features/Profile/SSHKeys/EditSSHKeyDrawer.tsx
  packages/manager/src/features/Users/CreateUserDrawer.tsx
  packages/manager/src/features/Volumes/VolumeAttachmentDrawer.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/VolumeDrawer.tsx
Labels: Storybook, Approved, Project: MUI v5 Migration

#9429 fix: Fix automated Cypress tests
  docker-compose.yml
Labels: Approved, Missing Changeset

#9428 chore: Improve Sentry's environment identification
  packages/manager/.changeset/pr-9428-tech-stories-1689796437483.md
  packages/manager/src/constants.ts
  packages/manager/src/initSentry.ts
Labels: Enhancement, Approved

#9415 refactor: [M3-6266] - `SRC > Features > Footer`
  packages/manager/.changeset/pr-9415-tech-stories-1689870607291.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Footer/Footer.tsx
  packages/manager/src/features/Footer/index.ts
Labels: Approved

#9431 Fix: [M3-6923] - Regressions with sidebar menu
  packages/manager/.changeset/pr-9431-fixed-1689868222225.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/assets/logo/akamai-logo.svg
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/SideMenu.stories.mdx
  packages/manager/src/components/SideMenu.tsx
Labels: Approved

#9424 fix: [M3-6006] - Make images landing page "Edit" buttons consistent
  packages/manager/.changeset/pr-9424-fixed-1689773023166.md
  packages/manager/src/features/Images/ImagesActionMenu.tsx
Labels: Bug, Approved

#9402 refactor: [M3-6827] - Use RQ for `isLargeAccount`
  packages/manager/.changeset/pr-9402-tech-stories-1689276550300.md
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx
  packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/hooks/useAccountManagement.ts
  packages/manager/src/hooks/useIsLargeAccount.ts
  packages/manager/src/store/accountManagement/accountManagement.actions.ts
  packages/manager/src/store/accountManagement/accountManagement.reducer.ts
  packages/manager/src/store/accountManagement/accountManagement.requests.ts
  packages/manager/src/store/index.ts
Labels: React Query, Approved

#9386 feat: Add support for self serve betas endpoints
  packages/api-v4/.changeset/pr-9386-added-1689191794116.md
  packages/api-v4/src/account/betas.ts
  packages/api-v4/src/account/index.ts
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/betas/betas.ts
  packages/api-v4/src/betas/index.ts
  packages/api-v4/src/betas/types.ts
  packages/api-v4/src/index.ts
  packages/manager/.changeset/pr-9386-added-1689191860871.md
  packages/manager/src/factories/betas.ts
  packages/manager/src/factories/index.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/accountBetas.ts
  packages/manager/src/queries/betas.ts
Labels: @linode/api-v4, Approved

#9435 chore: Only enable `useIsLargeAccount` when it's absolutely needed
  packages/manager/.changeset/pr-9435-tech-stories-1689887826129.md
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/hooks/useIsLargeAccount.ts
Labels: React Query, Approved

#9432 fix: Fix StackScript test by using latest images available
  packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
Labels: Approved, Missing Changeset

#9403 refactor [M3-6262]: MUI v5 Migration - `SRC > Features > Domains`
  packages/manager/.changeset/pr-9403-tech-stories-1689601832985.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Domains/CloneDomainDrawer.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Domains/CreateDomain/index.tsx
  packages/manager/src/features/Domains/DeleteDomain.test.tsx
  packages/manager/src/features/Domains/DeleteDomain.tsx
  packages/manager/src/features/Domains/DisableDomainDialog.tsx
  packages/manager/src/features/Domains/DomainActionMenu.tsx
  packages/manager/src/features/Domains/DomainBanner.tsx
  packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
  packages/manager/src/features/Domains/DomainDetail/index.tsx
  packages/manager/src/features/Domains/DomainRecordActionMenu.tsx
  packages/manager/src/features/Domains/DomainRecordDrawer.tsx
  packages/manager/src/features/Domains/DomainRecords.styles.ts
  packages/manager/src/features/Domains/DomainRecords.tsx
  packages/manager/src/features/Domains/DomainTableRow.tsx
  packages/manager/src/features/Domains/DomainZoneImportDrawer.tsx
  packages/manager/src/features/Domains/DomainsEmptyLandingPage.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
  packages/manager/src/features/Domains/DownloadDNSZoneFileButton.tsx
  packages/manager/src/features/Domains/EditDomainDrawer.tsx
  packages/manager/src/features/Domains/index.tsx
Labels: Approved, Project: MUI v5 Migration

#9439 fix: Storybook build failing due to duplicate `ToastNotifications` stories
  packages/manager/src/components/Snackbar/ToastNotifications.stories.tsx
  packages/manager/src/features/ToastNotifications/ToastNotifications.stories.tsx
Labels: Storybook, Approved, Missing Changeset

#9425 chore: Resolve open dependabot alerts and clean up packages
  package.json
  packages/manager/.changeset/pr-9425-tech-stories-1689783955027.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved

#9396 refactor: [M3-6875, M3-6719] - Upgrade remaining `LinodeSelect`s
  packages/manager/.changeset/pr-9396-tech-stories-1689779632023.md
  packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts
  packages/manager/cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts
  packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/src/components/LinodeMultiSelect/LinodeMultiSelect.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Linodes/CloneLanding/Details.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.md
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.stories.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.styles.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.test.ts
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.test.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelectV2.tsx
  packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
  packages/manager/src/features/Volumes/VolumeAttachmentDrawer.tsx
  packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
  packages/manager/src/foundations/themes/light.ts
Labels: Approved, Clean Up

#9419 refactor: [M3-6899] - MUI v5 Migration - `SRC > Components > Dialog`
  packages/manager/.changeset/pr-9419-tech-stories-1689716682370.md
  packages/manager/src/GoTo.tsx
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
  packages/manager/src/components/Dialog/Dialog.mdx
  packages/manager/src/components/Dialog/Dialog.stories.tsx
  packages/manager/src/components/Dialog/Dialog.tsx
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.stories.tsx
  packages/manager/src/components/core/CssBaseline.ts
  packages/manager/src/components/core/Dialog.ts
  packages/manager/src/components/core/DialogActions.ts
  packages/manager/src/components/core/DialogContent.ts
  packages/manager/src/components/core/DialogContentText.ts
  packages/manager/src/components/core/DialogTitle.ts
  packages/manager/src/components/core/Fade.ts
  packages/manager/src/features/TheApplicationIsOnFire.tsx
Labels: Storybook, Approved, Project: MUI v5 Migration

#9412 refactor: [M3-6897] - MUI v5 Migration - `SRC > Components > TableFooter`
  packages/manager/.changeset/pr-9412-tech-stories-1689649966860.md
  packages/manager/src/components/TableFooter.stories.tsx
  packages/manager/src/components/TableFooter.tsx
  packages/manager/src/components/core/TableFooter.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
Labels: Storybook, Approved, Project: MUI v5 Migration

#9430 fix, style: [M3-6644] - Standardize styling of copy icon on OBJ bucket details page
  packages/manager/.changeset/pr-9430-fixed-1689805558132.md
  packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketBreadcrumb.styles.ts
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketBreadcrumb.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.styles.ts
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
Labels: UI, Approved

#9433 feat: [M3-6924] - Allow users to filter Databases by `Region` and `Engine`
  packages/manager/.changeset/pr-9433-added-1689877090742.md
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
Labels: Enhancement, Project: DBaaS, Approved

#9427 fix: [M3-6728] - Make drawers full width on mobile viewports
  packages/manager/.changeset/pr-9427-fixed-1689792880711.md
  packages/manager/src/components/Drawer.tsx
Labels: Bug, Approved

#9434 refactor: [M3-6265] - MUI v5 Migration - `SRC > Features > Firewalls`
  packages/manager/.changeset/pr-9434-tech-stories-1689886686469.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDevicesTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/index.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleActionMenu.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleForm.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.styles.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.test.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/index.ts
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallDialog.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/index.ts
  packages/manager/src/features/Firewalls/index.tsx
Labels: Approved, Project: MUI v5 Migration

#9451 refactor: [M3-6693] - Optimize Linode event handlers and query invalidation
  packages/manager/.changeset/pr-9451-tech-stories-1690343906802.md
  packages/manager/cypress/e2e/core/images/create-linode-from-image.spec.ts
  packages/manager/src/containers/withLinodes.container.ts
  packages/manager/src/features/Backups/BackupDrawer.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/StandardRescueDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/queries/linodes/actions.ts
  packages/manager/src/queries/linodes/backups.ts
  packages/manager/src/queries/linodes/configs.ts
  packages/manager/src/queries/linodes/events.ts
  packages/manager/src/queries/linodes/firewalls.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/queries/linodes/networking.ts
  packages/manager/src/queries/linodes/requests.ts
Labels: React Query, Approved

#9450 test: [M3-6618] - Add Linode resize decrease size end-to-end tests
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
Labels: Approved, Missing Changeset

#9458 chore: [M3-6947] - Update Storybook Categories
  packages/manager/.changeset/pr-9458-tech-stories-1690481194169.md
  packages/manager/.storybook/preview.tsx
  packages/manager/src/components/BetaChip/BetaChip.stories.mdx
  packages/manager/src/components/Currency/Currency.stories.mdx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.stories.mdx
  packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
  packages/manager/src/components/ErrorState/ErrorState.stories.mdx
  packages/manager/src/components/FileUploader/FileUploader.stories.mdx
  packages/manager/src/components/StatusIcon/StatusIcon.stories.mdx
  packages/manager/src/components/Tabs.stories.mdx
  packages/manager/src/components/Tag/Tag.stories.mdx
  packages/manager/src/components/Tags/Tags.stories.mdx
  packages/manager/src/components/TagsInput/TagsInput.stories.mdx
  packages/manager/src/components/TagsPanel/TagsPanel.stories.mdx
  packages/manager/src/components/Toggle/Toggle.stories.mdx
Labels: Storybook, Approved

#9460 fix: Resize e2e test
  packages/manager/src/features/Linodes/PowerActionsDialogOrDrawer.tsx
Labels: e2e, Approved, Missing Changeset

#9466 hotfix: Fix Backups Drawer, Region Select Order, Cloud Manager `v1.98.1`
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.test.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
  packages/manager/src/containers/withLinodes.container.ts
  packages/manager/src/features/Backups/BackupDrawer.test.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/store/backupDrawer/index.ts
Labels: Approved, Release → Staging, Hotfix

#9452 refactor: [M3 6730] - LinodeSelect - Allow fully custom noOptionsText
  packages/manager/.changeset/pr-9452-tech-stories-1690342391207.md
  packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts
  packages/manager/cypress/support/intercepts/linodes.ts
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.stories.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
Labels: Storybook, Approved

#9468 Release v1.98.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.test.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
  packages/manager/src/containers/withLinodes.container.ts
  packages/manager/src/features/Backups/BackupDrawer.test.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/store/backupDrawer/index.ts
Labels: Release, Approved

#9471 Release v1.98.1 - master → develop
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.test.tsx
  packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
Labels: Approved, Missing Changeset

#9461 fix: ActionsPanel regression
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/ScheduleSettings.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
Labels: Approved, Missing Changeset
