Repository linode/manager, pull requests merged in 2024-12, with the labels that each got.

#11337 feat: [M3-8947] - Improve linter rules for naming convention
  packages/api-v4/.changeset/pr-11337-added-1732714186488.md
  packages/api-v4/.eslintrc.json
  packages/manager/.changeset/pr-11337-added-1732714227095.md
  packages/manager/.eslintrc.cjs
Labels: Approved

#11324 refactor: [M3-8945] - Update `yup` from `0.32.9` to `1.4.0`
  packages/api-v4/.changeset/pr-11324-tech-stories-1732641088654.md
  packages/api-v4/package.json
  packages/manager/.changeset/pr-11324-tech-stories-1732641114172.md
  packages/manager/cypress/support/plugins/generate-weights.ts
  packages/manager/package.json
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/schemas.ts
  packages/validation/.changeset/pr-11324-tech-stories-1732641099442.md
  packages/validation/package.json
  packages/validation/src/account.schema.ts
  packages/validation/src/buckets.schema.ts
  packages/validation/src/cloudpulse.schema.ts
  packages/validation/src/databases.schema.ts
  packages/validation/src/domains.schema.ts
  packages/validation/src/firewalls.schema.ts
  packages/validation/src/kubernetes.schema.ts
  packages/validation/src/linodes.schema.ts
  packages/validation/src/managed.schema.ts
  packages/validation/src/networking.schema.ts
  packages/validation/src/nodebalancers.schema.ts
  packages/validation/src/records.schema.ts
  packages/validation/src/volumes.schema.ts
  packages/validation/src/vpcs.schema.ts
  yarn.lock
Labels: Dependencies, @linode/validation, Approved

#11311 change: [UIE-8228] - DBaaS Resize GA: Enable Downsizing, update node presentation
  packages/manager/.changeset/pr-11311-changed-1732288180106.md
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseNodeSelector.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryClusterConfigurationLegacy.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
Labels: Add'tl Approval Needed, DBaaS

#11322 upcoming: [M3-8840] - Add Cluster Type selection to LKE Create Cluster flow
  packages/manager/.changeset/pr-11322-upcoming-features-1732570083227.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/ClusterTypePanel.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.styles.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.test.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/queries/kubernetes.ts
Labels: Approved, LKE-Enterprise

#11338 tech-story: [M3-8939] - Get rid of `DrawerContent`
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/components/Drawer.tsx
  packages/manager/src/components/DrawerContent/DrawerContent.test.tsx
  packages/manager/src/components/DrawerContent/DrawerContent.tsx
  packages/manager/src/components/DrawerContent/index.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/Managed/Monitors/HistoryDrawer.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTable.tsx
  packages/manager/src/queries/kubernetes.ts
Labels: Approved, Tech Debt

#11340 test: [M3-8546] - Add unit tests for `DialogTitle` component
  packages/manager/.changeset/pr-11340-tests-1732789911285.md
  packages/manager/src/components/DialogTitle/DialogTitle.test.tsx
  packages/manager/src/components/DialogTitle/DialogTitle.tsx
Labels: Approved, Unit tests

#11310 feat: [UIE-8131] - IAM RBAC: Routes, Menu, Feature Flag
  packages/manager/.changeset/pr-11310-added-1732287073605.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/assets/icons/entityIcons/iam.svg
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/IAM/IAMLanding.tsx
  packages/manager/src/features/IAM/Roles/Roles.tsx
  packages/manager/src/features/IAM/Shared/constants.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
  packages/manager/src/features/IAM/Users/Users.tsx
  packages/manager/src/features/IAM/index.tsx
Labels: IAM (Identity & Access Management)

#11326 test: [M3-6611] - Add new assertions for linode backup tests
  packages/manager/.changeset/pr-11326-tests-1732566960471.md
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: Approved

#11356 fix: [M3-8958] - LinodeCreate OS Panel fetches region with -1 on page load
  packages/manager/.changeset/pr-11356-fixed-1733237715392.md
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/OperatingSystems.tsx
Labels: Bug, Approved

#11353 refactor: [M3-8899] - Migrate `FormControlLabel` to `ui` package
  packages/manager/.changeset/pr-11353-removed-1733229097582.md
  packages/manager/src/components/FormGroup.stories.tsx
  packages/manager/src/components/FormLabel.stories.tsx
  packages/manager/src/components/ModeSelect/ModeSelect.tsx
  packages/manager/src/features/Account/AutoBackups.tsx
  packages/manager/src/features/Account/NetworkHelper.tsx
  packages/manager/src/features/Backups/AutoEnroll.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreateAccessControls.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseNodeSelector.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/manager/src/features/Domains/CloneDomainDrawer.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Domains/EditDomainDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleForm.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Addons/Backups.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Addons/PrivateIP.tsx
  packages/manager/src/features/Linodes/LinodeCreate/FirewallAuthorization.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/UserDefinedFields/UserDefinedFieldInput.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
  packages/manager/src/features/Linodes/LinodeCreate/shared/LinodeSelectTableRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.styles.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResizeUnifiedMigrationPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/VPCPanel.tsx
  packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerPassiveCheck.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupPolicyRadioGroup.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactorToggle.tsx
  packages/manager/src/features/Profile/OAuthClients/CreateOAuthClientDrawer.tsx
  packages/manager/src/features/Profile/OAuthClients/EditOAuthClientDrawer.tsx
  packages/manager/src/features/Profile/Settings/Settings.tsx
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedSelect.tsx
  packages/manager/src/features/Users/CreateUserDrawer.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/ModeSelection.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/ui/.changeset/pr-11353-added-1733229144769.md
  packages/ui/src/components/FormControlLabel/FormControlLabel.stories.tsx
  packages/ui/src/components/FormControlLabel/FormControlLabel.tsx
  packages/ui/src/components/FormControlLabel/index.ts
  packages/ui/src/components/index.ts
Labels: Approved, Modularization

#11358 tech-story: [M3-8959] - Bump recharts to ^2.14.1
  packages/manager/.changeset/pr-11358-tech-stories-1733240852206.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved

#11361 change: [M3-8961] - Change Pendo sanitized url path string to match UXR request
  packages/manager/.changeset/pr-11361-tech-stories-1733330515390.md
  packages/manager/src/hooks/usePendo.test.ts
  packages/manager/src/hooks/usePendo.ts
Labels: Approved, Analytics

#11370 fix: [M3-8966] - Regression with AppBar
  packages/manager/src/features/TopMenu/CreateMenu/CreateMenu.tsx
Labels: Bug, Approved

#11348 upcoming: [M3-8847] - Update Region Select for LKE-Enterprise
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-11348-upcoming-features-1733174894693.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Linodes/LinodeCreate/resolvers.ts
  packages/ui/src/components/TextField/TextField.tsx
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, LKE-Enterprise

#11355 feat: [M3-8953] - Object Storage Gen2 Updates and Improvements
  packages/api-v4/src/object-storage/buckets.ts
  packages/manager/.changeset/pr-11355-fixed-1733342647044.md
  packages/manager/.changeset/pr-11355-upcoming-features-1733237339445.md
  packages/manager/.changeset/pr-11355-upcoming-features-1733342861906.md
  packages/manager/cypress/e2e/core/objectStorage/bucket-details.spec.ts
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-access-keys-gen2.spec.ts
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-object-gen2.spec.ts
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
  packages/manager/src/queries/object-storage/requests.ts
Labels: Approved, Ready for Review, Object Storage Gen2

#11293 fix: [M3-8740] - Convert Object Storage size from `GiB` to `GB` in frontend
  packages/manager/.changeset/pr-11293-fixed-1732102749040.md
  packages/manager/src/components/Uploaders/FileUpload.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_BucketLanding.tsx
Labels: Add'tl Approval Needed, Object Storage, Ready for Review

#11374 fix: [M3-8847] RegionSelect width
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
Labels: Bug

#11371 feat: [UIE-8269], [UIE-8290] - DBaaS: Access Controls text update, fix defaultDB for legacy instances
  packages/manager/.changeset/pr-11371-changed-1733409504298.md
  packages/manager/cypress/e2e/core/databases/update-database.spec.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreateAccessControls.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreateAccessControls.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
  packages/manager/src/features/Databases/constants.ts
  packages/manager/src/utilities/ipUtils.ts
Labels: Add'tl Approval Needed, DBaaS

#11349 refactor: [M3-8954] - Update `@hookform/resolvers` to latest
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/package.json
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.utils.ts
  packages/manager/src/features/Linodes/LinodeCreate/resolvers.ts
  packages/validation/src/buckets.schema.ts
  packages/validation/src/cloudpulse.schema.ts
  packages/validation/src/images.schema.ts
  packages/validation/src/kubernetes.schema.ts
  yarn.lock
Labels: Dependencies, Approved, Ready for Review

#11300 fix: [M3-8912] - Create support ticket for buckets created through legacy flow
  packages/manager/.changeset/pr-11300-fixed-1732196456888.md
  packages/manager/src/features/Support/SupportTickets/SupportTicketProductSelectionFields.tsx
Labels: Approved

#11365 test: [M3-8758]- Fixed `delete-volume.spec.ts` flaky test
  packages/manager/.changeset/pr-11365-tests-1733305182663.md
  packages/manager/cypress/e2e/core/volumes/delete-volume.spec.ts
Labels: e2e, Approved

#11351 added: [M3-6989] - `aria-describedby` to TextField with helper text
  packages/manager/.changeset/pr-11351-added-1733194164261.md
  packages/ui/src/components/TextField/TextField.test.tsx
  packages/ui/src/components/TextField/TextField.tsx
Labels: Accessibility

#11328 tech-story: [M3-8940] - Dev Tools fixes and improvements
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-11328-tech-stories-1732650627657.md
  packages/manager/src/dev-tools/DevTools.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/dev-tools/ServiceWorkerTool.tsx
  packages/manager/src/dev-tools/components/Draggable.tsx
  packages/manager/src/dev-tools/components/ExtraPresetAccount.tsx
  packages/manager/src/dev-tools/components/ExtraPresetOptionCheckbox.tsx
  packages/manager/src/dev-tools/components/ExtraPresetOptionSelect.tsx
  packages/manager/src/dev-tools/components/ExtraPresetOptions.tsx
  packages/manager/src/dev-tools/components/ExtraPresetProfile.tsx
  packages/manager/src/dev-tools/components/JsonTextArea.tsx
  packages/manager/src/dev-tools/components/SeedOptions.tsx
  packages/manager/src/dev-tools/constants.ts
  packages/manager/src/dev-tools/dev-tools.css
  packages/manager/src/dev-tools/load.ts
  packages/manager/src/dev-tools/utils.ts
  packages/manager/src/factories/account.ts
  packages/manager/src/factories/profile.ts
  packages/manager/src/features/Betas/BetaDetails.test.tsx
  packages/manager/src/mocks/presets/baseline/noMocks.ts
  packages/manager/src/mocks/presets/extra/account/childAccount.ts
  packages/manager/src/mocks/presets/extra/account/customAccount.ts
  packages/manager/src/mocks/presets/extra/account/customProfile.ts
  packages/manager/src/mocks/presets/extra/account/lkeEnterpriseEnabled.ts
  packages/manager/src/mocks/presets/extra/account/parentAccount.ts
  packages/manager/src/mocks/presets/index.ts
  packages/manager/src/mocks/types.ts
Labels: Add'tl Approval Needed, Ready for Review

#11364 refactor: [M3-8964] - Remove `reselect` dependency
  packages/manager/.changeset/pr-11364-tech-stories-1733273269749.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved, Clean Up

#11354 upcoming: [DI-20929] - Added applied filters view in CloudPulse
  packages/manager/.changeset/pr-11354-upcoming-features-1733237771685.md
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.test.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseAppliedFilter.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseAppliedFilter.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseAppliedFilterRenderer.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelectUtils.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
Labels: Ready for Review, CloudPulse

#11321 upcoming: [M3-8869] - Update types for NodeBalancer UDP support
  packages/api-v4/.changeset/pr-11321-added-1733240671518.md
  packages/api-v4/src/nodebalancers/types.ts
  packages/manager/.changeset/pr-11321-tech-stories-1733243149867.md
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
  packages/manager/src/features/NodeBalancers/types.ts
  packages/manager/src/features/NodeBalancers/utils.ts
  packages/validation/.changeset/pr-11321-added-1733240871159.md
  packages/validation/src/nodebalancers.schema.ts
Labels: Approved, NodeBalancers

#11347 tests: [M3-8656] - Mock LKE creation flow + APL coverage
  packages/api-v4/.changeset/pr-11347-fixed-1733327446988.md
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-11347-tests-1733170030162.md
  packages/manager/cypress/e2e/core/billing/smoke-billing-activity.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/support/api/lke.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/cypress/support/constants/lke.ts
  packages/manager/cypress/support/intercepts/betas.ts
  packages/manager/cypress/support/intercepts/lke.ts
  packages/manager/src/factories/betas.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
Labels: Testing, e2e, LKE, Approved, APL

#11379 fix: [M3-8796] - Disallow word-break in billing contact info
  packages/manager/.changeset/pr-11379-fixed-1733476117431.md
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
Labels: Bug, Approved

#11346 upcoming: [DI-22217] - Added the Alert Listing page with Alerting Table and added relevant api endpoints
  packages/api-v4/.changeset/pr-11346-changed-1733145182722.md
  packages/api-v4/src/cloudpulse/alerts.ts
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-11346-added-1733145106911.md
  packages/manager/src/factories/cloudpulse/alerts.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertActionMenu.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/constants.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/alerts.ts
  packages/manager/src/queries/cloudpulse/queries.ts
  packages/manager/src/queries/cloudpulse/requests.ts
Labels: Approved, CloudPulse

#11380 fix: [M3-8972] - Overflow issue in Kubernetes Summary section on smaller screens (→ `staging`)
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
Labels: Bug, Approved

#11154 refactor: [M3-8783] - Migrate /volumes to Tanstack Router
  packages/manager/.changeset/pr-11154-tech-stories-1730404184309.md
  packages/manager/.eslintrc.cjs
  packages/manager/.storybook/preview.tsx
  packages/manager/cypress/e2e/core/volumes/create-volume.smoke.spec.ts
  packages/manager/cypress/e2e/core/volumes/upgrade-volume.spec.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/Router.tsx
  packages/manager/src/components/TanstackLink.stories.tsx
  packages/manager/src/components/TanstackLinks.tsx
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
  packages/manager/src/features/Volumes/AttachVolumeDrawer.test.tsx
  packages/manager/src/features/Volumes/AttachVolumeDrawer.tsx
  packages/manager/src/features/Volumes/CloneVolumeDrawer.test.tsx
  packages/manager/src/features/Volumes/CloneVolumeDrawer.tsx
  packages/manager/src/features/Volumes/DeleteVolumeDialog.tsx
  packages/manager/src/features/Volumes/DetachVolumeDialog.tsx
  packages/manager/src/features/Volumes/EditVolumeDrawer.test.tsx
  packages/manager/src/features/Volumes/EditVolumeDrawer.tsx
  packages/manager/src/features/Volumes/ResizeVolumeDrawer.tsx
  packages/manager/src/features/Volumes/UpgradeVolumeDialog.tsx
  packages/manager/src/features/Volumes/VolumeCreate.test.tsx
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/manager/src/features/Volumes/VolumeDetailsDrawer.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeAddDrawer.test.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.test.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/Volumes/Volumes.tsx
  packages/manager/src/features/Volumes/VolumesActionMenu.test.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/features/Volumes/VolumesLandingEmptyState.test.tsx
  packages/manager/src/features/Volumes/VolumesLandingEmptyState.tsx
  packages/manager/src/features/Volumes/VolumesLandingEmptyStateData.ts
  packages/manager/src/features/Volumes/constants.ts
  packages/manager/src/features/Volumes/index.tsx
  packages/manager/src/hooks/useDialogData.ts
  packages/manager/src/hooks/useOrder.ts
  packages/manager/src/hooks/useOrderV2.test.tsx
  packages/manager/src/hooks/useOrderV2.ts
  packages/manager/src/hooks/usePaginationV2.test.ts
  packages/manager/src/hooks/usePaginationV2.ts
  packages/manager/src/mocks/utilities/response.ts
  packages/manager/src/routes/index.tsx
  packages/manager/src/routes/types.ts
  packages/manager/src/routes/volumes/VolumesRoot.tsx
  packages/manager/src/routes/volumes/constants.ts
  packages/manager/src/routes/volumes/index.ts
  packages/manager/src/routes/volumes/volumesLazyRoutes.ts
  packages/manager/src/types/ManagerPreferences.ts
Labels: Approved, Routing Refactor

#11303 fix: [M3-8538] - Incorrect Commands in Linode CLI Modal
  packages/manager/.changeset/pr-11303-fixed-1733422977888.md
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/ApiAwarenessModal.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/CurlTabPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/LinodeCLIPanel.tsx
  packages/manager/src/utilities/codesnippets/generate-cli.ts
Labels: Approved

#11367 feat: [UIE-8136] - IAM RBAC: add new users table component (part 1)
  packages/manager/.changeset/pr-11367-upcoming-features-1733488193445.md
  packages/manager/src/features/IAM/IAMLanding.tsx
  packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
  packages/manager/src/features/IAM/Users/Users.tsx
  packages/manager/src/features/IAM/Users/UsersTable/UserRow.test.tsx
  packages/manager/src/features/IAM/Users/UsersTable/UserRow.tsx
  packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
  packages/manager/src/features/IAM/Users/UsersTable/UsersActionMenu.test.tsx
  packages/manager/src/features/IAM/Users/UsersTable/UsersActionMenu.tsx
  packages/manager/src/features/IAM/Users/UsersTable/UsersLandingTableBody.test.tsx
  packages/manager/src/features/IAM/Users/UsersTable/UsersLandingTableBody.tsx
  packages/manager/src/features/IAM/Users/UsersTable/UsersLandingTableHead.tsx
Labels: Approved, IAM (Identity & Access Management)

#11383 test: [M3-8693] - Cypress tests for Credit Card Expired banner
  packages/manager/.changeset/pr-11383-tests-1733523460107.md
  packages/manager/cypress/e2e/core/billing/credit-card-expired-banner.spec.ts
Labels: e2e, Approved

#11394 test: Fix and clean up `smoke-billing-activity.spec.ts` and `DatabaseBackups.test.tsx`
  packages/manager/.changeset/pr-11394-tests-1733856095533.md
  packages/manager/.changeset/pr-11394-tests-1733856145159.md
  packages/manager/cypress/e2e/core/billing/smoke-billing-activity.spec.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx
Labels: Testing

#11382 upcoming: [DI-20595] - ACLP Supported regions per service type
  packages/manager/.changeset/pr-11382-upcoming-features-1733485035913.md
  packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-dashboard-errors.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/Utils/models.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
Labels: Approved, CloudPulse

#11253 feat: [M3-8676] - Provide Customer Notice for OS Distro Nearing EOL/EOS
  packages/manager/.changeset/pr-11253-added-1731495888267.md
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
Labels: Approved, Ready for Review

#11359 upcoming: [M3-8848] - Update Kubernetes version Autocomplete to filter on LKE-E versions
  packages/manager/.changeset/pr-11359-upcoming-features-1733244908637.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/support/constants/lke.ts
  packages/manager/cypress/support/intercepts/lke.ts
  packages/manager/cypress/support/util/lke.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/queries/kubernetes.ts
Labels: Approved, Ready for Review, LKE-Enterprise

#11357 refactor: [M3-8877] - Refactor VPC Create to use `react-hook-form`
  packages/manager/.changeset/pr-11357-tech-stories-1733778960338.md
  packages/manager/cypress/e2e/core/vpc/vpc-create.spec.ts
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/SubnetContent.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/SubnetContent.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.tsx
  packages/manager/src/features/VPCs/VPCCreate/MultipleSubnetInput.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/MultipleSubnetInput.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.test.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
  packages/manager/src/features/VPCs/VPCCreateDrawer/VPCCreateDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCCreateDrawer/VPCCreateDrawer.tsx
  packages/manager/src/hooks/useCreateVPC.ts
  packages/manager/src/utilities/formikErrorUtils.test.ts
  packages/manager/src/utilities/formikErrorUtils.ts
  packages/manager/src/utilities/subnets.ts
  packages/validation/.changeset/pr-11357-changed-1733929595429.md
  packages/validation/src/vpcs.schema.ts
Labels: Approved, VPC

#11384 fix: [M3-8975] - Object Storage object uploader spinner spinning backwards
  packages/manager/.changeset/pr-11384-fixed-1733733978349.md
  packages/manager/src/assets/icons/uploadPending.svg
  packages/manager/src/components/Uploaders/FileUpload.styles.ts
  packages/manager/src/components/Uploaders/FileUpload.tsx
Labels: Bug, Approved

#11398 fix: [M3-8506] - Misplaced `errorGroup` prop causing console error
  packages/manager/.changeset/pr-11398-fixed-1733917277527.md
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
Labels: Bug, Approved

#11386 refactor: [M3-8981] - User Preferences optimization with selector pattern (Part 1)
  packages/manager/src/MainContent.tsx
  packages/manager/src/Root.tsx
  packages/manager/src/components/PreferenceToggle/PreferenceToggle.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/queries/profile/preferences.ts
  packages/manager/src/types/ManagerPreferences.ts
  packages/manager/src/utilities/theme.ts
Labels: React Query, Approved

#11393 refactor: [M3-8986] - Refactor VPCEditDrawer and SubnetEditDrawer to use `react-hook-form`
  packages/manager/.changeset/pr-11393-tech-stories-1733855306252.md
  packages/manager/src/features/VPCs/VPCDetail/SubnetEditDrawer.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.tsx
  packages/validation/.changeset/pr-11393-changed-1733855352751.md
  packages/validation/src/vpcs.schema.ts
Labels: Approved, VPC

#11413 change: [M3-8928] - Switch from v4beta to v4 `account` endpoint for LKE-E
  packages/api-v4/.changeset/pr-11413-removed-1734030444142.md
  packages/api-v4/src/account/account.ts
  packages/manager/.changeset/pr-11413-upcoming-features-1734030483336.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/features/Kubernetes/CreateCluster/ClusterTypePanel.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.test.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/queries/account/account.ts
  packages/manager/src/queries/account/queries.ts
Labels: Approved, Clean Up, LKE-Enterprise

#11151 feat: [M3-8611]- New DatePicker Component
  packages/manager/.changeset/pr-11151-added-1731944151381.md
  packages/manager/src/components/DatePicker/DatePicker.stories.tsx
  packages/manager/src/components/DatePicker/DatePicker.test.tsx
  packages/manager/src/components/DatePicker/DatePicker.tsx
  packages/manager/src/components/DatePicker/DateTimePicker.stories.tsx
  packages/manager/src/components/DatePicker/DateTimePicker.test.tsx
  packages/manager/src/components/DatePicker/DateTimePicker.tsx
  packages/manager/src/components/DatePicker/DateTimeRangePicker.stories.tsx
  packages/manager/src/components/DatePicker/DateTimeRangePicker.test.tsx
  packages/manager/src/components/DatePicker/DateTimeRangePicker.tsx
  packages/manager/src/components/DatePicker/TimeZoneSelect.tsx
  packages/ui/package.json
Labels: Approved, Date Range Picker

#11344 test: [M3-8948] Added cypress component test for firewall inbound and outbound rules for mouse drag and drop
  packages/manager/.changeset/pr-11344-tests-1733127883345.md
  packages/manager/cypress/component/features/firewalls/firewall-rule-table.spec.tsx
  packages/manager/cypress/tsconfig.json
  packages/manager/package.json
  yarn.lock
Labels: Testing, e2e, Approved

#11350 test: [M3-8760] - Improve stability of Linode end-to-end tests
  packages/manager/.changeset/pr-11350-tests-1733842479277.md
  packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/rescue-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/search-linodes.spec.ts
  packages/manager/cypress/e2e/core/linodes/switch-linode-state.spec.ts
  packages/manager/cypress/e2e/core/linodes/update-linode-labels.spec.ts
  packages/manager/cypress/support/constants/linodes.ts
  packages/manager/cypress/support/setup/defer-command.ts
  packages/manager/cypress/support/util/linodes.ts
  packages/manager/cypress/support/util/polling.ts
Labels: Approved, Ready for Review

#11407 M3-8974: Fix account login tests when using non-Prod login environment
  packages/manager/.changeset/pr-11407-tests-1734013914322.md
  packages/manager/cypress/e2e/core/account/account-logout.spec.ts
  packages/manager/cypress/e2e/core/general/account-login-redirect.spec.ts
  packages/manager/cypress/support/constants/login.ts
Labels: Approved

#11414 fix: [UIE-8338] dbaas IP validation should display updated error message that includes IPV6
  packages/manager/.changeset/pr-11414-fixed-1734041664478.md
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
  packages/manager/src/features/Databases/constants.ts
Labels: DBaaS

#11406 fix: [UIE-8228] - Database Resize: text update
  packages/manager/.changeset/pr-11406-changed-1734097478149.md
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseSummarySection.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseSummarySection.tsx
  packages/manager/src/features/Databases/DatabaseCreate/utilities.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
  packages/manager/src/features/Databases/DatabaseEngineVersion.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
  packages/manager/src/features/components/PlansPanel/constants.ts
  packages/manager/src/features/components/PlansPanel/types.ts
  packages/manager/src/features/components/PlansPanel/utils.test.ts
  packages/manager/src/features/components/PlansPanel/utils.ts
Labels: DBaaS

#11399 upcoming: [DI-22130] - Alert listing action menu and Alert Detail landing
  packages/api-v4/.changeset/pr-11399-upcoming-features-1733923542682.md
  packages/api-v4/src/cloudpulse/alerts.ts
  packages/manager/.changeset/pr-11399-upcoming-features-1733923517331.md
  packages/manager/src/factories/index.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertActionMenu.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertsActionMenu.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/alerts.ts
  packages/manager/src/queries/cloudpulse/queries.ts
Labels: Approved, CloudPulse, Cloud Pulse - Alerting

#11417 change: [UIE-8194] DBaaS Settings maintenance pending updates tooltip should have accurate tooltip text
  packages/manager/.changeset/pr-11417-changed-1734111263221.md
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMaintenance.tsx
Labels: DBaaS, Approved

#11341 test: [M3-8951] - Cypress component tests for firewall rules drag and drop `keyboard` interaction
  packages/manager/.changeset/pr-11341-tests-1732886601848.md
  packages/manager/cypress/component/features/firewalls/firewall-rule-table.spec.tsx
  packages/manager/src/utilities/CustomKeyboardSensor.ts
Labels: Testing, Approved

#11401 feat: [UIE-8138] - IAM RBAC: add new no assigned roles component
  packages/manager/.changeset/pr-11401-upcoming-features-1733923108694.md
  packages/manager/src/assets/icons/emptynotification.svg
  packages/manager/src/features/IAM/Shared/NoAssignedRoles/NoAssignedRoles.test.tsx
  packages/manager/src/features/IAM/Shared/NoAssignedRoles/NoAssignedRoles.tsx
  packages/manager/src/features/IAM/Shared/constants.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
  packages/manager/src/features/IAM/Users/UserResources/UserResources.tsx
  packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: IAM (Identity & Access Management)

#11410 docs: [M3-9010] - `useEffect` Best Practices
  docs/development-guide/13-coding-standards.md
  packages/manager/.changeset/pr-11410-tech-stories-1734037217982.md
Labels: Approved, Documentation

#11345 refactor: [M3-8917] - Replace one-off hardcoded color values with color tokens pt4
  packages/manager/.changeset/pr-11345-tech-stories-1733225462381.md
  packages/manager/src/components/BarPercent/BarPercent.tsx
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
  packages/manager/src/components/CodeBlock/CodeBlock.styles.ts
  packages/manager/src/components/ColorPalette/ColorPalette.tsx
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
  packages/manager/src/components/IconTextLink/IconTextLink.tsx
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PromotionalOfferCard/PromotionalOfferCard.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.styles.ts
  packages/manager/src/components/SelectionCard/CardBase.styles.ts
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/components/ShowMore/ShowMore.tsx
  packages/manager/src/components/Uploaders/FileUpload.styles.ts
  packages/manager/src/components/Uploaders/ImageUploader/ImageUploader.styles.ts
  packages/manager/src/components/VerticalLinearStepper/VerticalLinearStepper.styles.ts
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/CancelLanding/CancelLanding.tsx
  packages/manager/src/features/Help/SupportSearchLanding/DocumentationResults.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferContent.styles.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.styles.ts
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
  packages/manager/src/features/Profile/Referrals/Referrals.styles.ts
  packages/manager/src/features/TopMenu/CreateMenu/CreateMenu.styles.ts
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.styles.ts
  packages/manager/src/features/components/PlansPanel/PlansPanel.styles.ts
  packages/ui/src/components/Accordion/Accordion.tsx
  packages/ui/src/components/Button/StyledTagButton.ts
Labels: Approved, Design Tokens

#11424 fix: [M3-8196] - Fix Linode Edit Config warning message when initially selecting a VPC as the primary interface
  packages/manager/.changeset/pr-11424-fixed-1734375315983.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
Labels: Bug, Approved, VPC

#11391 [M3-8991 + M3-6911] - New Select Component + Managed Replacement
  packages/manager/.changeset/pr-11391-tech-stories-1733949258449.md
  packages/manager/cypress/component/poc/select.spec.tsx
  packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
  packages/manager/src/features/Managed/MonitorDrawer.tsx
  packages/ui/.changeset/pr-11391-added-1733949199859.md
  packages/ui/src/components/Autocomplete/Autocomplete.tsx
  packages/ui/src/components/Select/Select.stories.tsx
  packages/ui/src/components/Select/Select.test.tsx
  packages/ui/src/components/Select/Select.tsx
  packages/ui/src/components/index.ts
Labels: Approved, Tech Debt

#11392 upcoming: [DI-22184] - Added Metric Criteria, Metric components
  packages/api-v4/.changeset/pr-11392-changed-1733853811812.md
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-11392-added-1733853776123.md
  packages/manager/src/factories/cloudpulse/alerts.ts
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/ClearIconButton.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/ClearIconButton.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/MetricCriteria.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/MetricCriteria.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/AlertSeveritySelect.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/ResourceMultiSelect.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/types.ts
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/utilities.ts
  packages/manager/src/features/CloudPulse/Alerts/constants.ts
  packages/validation/src/cloudpulse.schema.ts
Labels: Cloud Pulse, Cloud Pulse - Alerting

#11415 upcoming: [M3-8960] - Update Kubernetes version upgrade components for LKE-E
  packages/manager/.changeset/pr-11415-upcoming-features-1734109279111.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeKubernetesVersionBanner.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/Kubernetes/UpgradeVersionModal.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.test.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/queries/kubernetes.ts
Labels: Approved, LKE-Enterprise

#11368 feat: [M3-8855] - Surface Node Pool Tags
  packages/api-v4/.changeset/pr-11368-added-1733420616390.md
  packages/api-v4/src/kubernetes/types.ts
  packages/manager/.changeset/pr-11368-added-1733415278919.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.styles.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
Labels: LKE, Approved

#11420 refactor: Treat `scripts` as a yarn workspace
  package.json
  packages/manager/package.json
  scripts/changelog/generate-changelogs.mjs
  scripts/junit-summary/index.ts
  scripts/package-versions/index.js
  scripts/package.json
  scripts/tod-payload/index.ts
  yarn.lock
Labels: Modularization

#11412 fix: [M3-7528] - Account Cancellation Survey Button Color Issues
  packages/manager/.changeset/pr-11412-fixed-1734107098320.md
  packages/manager/src/features/CancelLanding/CancelLanding.tsx
  packages/manager/src/index.tsx
Labels: Approved

#11427 change: [M3-8742] - Update Pendo URL with CNAME
  docs/tooling/analytics.md
  packages/manager/.changeset/pr-11427-tech-stories-1734383515695.md
  packages/manager/src/hooks/usePendo.ts
Labels: Approved, Documentation, Analytics

#11333 refactor: [M3-8637] - Make `EditableText` UI component pure
  packages/manager/src/components/Breadcrumb/FinalCrumb.styles.tsx
  packages/manager/src/components/Breadcrumb/FinalCrumb.tsx
  packages/manager/src/components/Link.tsx
  packages/ui/.changeset/pr-11333-changed-1733176201231.md
  packages/ui/src/components/EditableText/EditableText.stories.tsx
  packages/ui/src/components/EditableText/EditableText.tsx
Labels: Approved, Modularization

#11388 change: [DI-22390] - Enhanced monitor page for contextual view
  packages/manager/.changeset/pr-11388-changed-1733815118971.md
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.test.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Ready for Review, Cloud Pulse

#11385 fix: [M3-8905] - Change document title from address to appropriate keyword
  packages/manager/.changeset/pr-11385-fixed-1733735480951.md
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
  packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
Labels: Bug, Approved

#11335 test: [M3-8608] - Cypress test for restricted user Image non-empty landing page
  packages/manager/.changeset/pr-11335-added-1732792310960.md
  packages/manager/cypress/e2e/core/images/images-non-empty-landing-page.spec.ts
Labels: e2e, Approved

#11389 feat: [M3-8177] - Add `MultipleIPInput` Story
  packages/manager/.changeset/pr-11389-added-1733834884159.md
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.stories.tsx
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
Labels: Storybook, Approved

#11426 fix: [UIE-8342] DBaaS resize used field should show N/A when property is null
  packages/api-v4/.changeset/pr-11426-changed-1734381690407.md
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-11426-fixed-1734381380797.md
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.tsx
Labels: DBaaS, Approved

#11418 tech-story: [M3-8784] - Tanstack routing for Domains
  packages/manager/.changeset/pr-11418-tech-stories-1734276290091.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/e2e/core/domains/smoke-clone-domain.spec.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Betas/BetaSignup.tsx
  packages/manager/src/features/Domains/CloneDomainDrawer.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Domains/DisableDomainDialog.tsx
  packages/manager/src/features/Domains/DomainActionMenu.test.tsx
  packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
  packages/manager/src/features/Domains/DomainDetail/index.tsx
  packages/manager/src/features/Domains/DomainZoneImportDrawer.tsx
  packages/manager/src/features/Domains/DomainsLanding.test.tsx
  packages/manager/src/features/Domains/DomainsLanding.tsx
  packages/manager/src/features/Domains/DownloadDNSZoneFileButton.test.tsx
  packages/manager/src/features/Domains/EditDomainDrawer.tsx
  packages/manager/src/features/Domains/constants.ts
  packages/manager/src/features/Domains/index.tsx
  packages/manager/src/hooks/useDialogData.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/domains.ts
  packages/manager/src/routes/domains/domainsLazyRoutes.ts
  packages/manager/src/routes/domains/index.ts
  packages/manager/src/routes/index.tsx
  packages/manager/src/routes/routes.test.tsx
Labels: Approved, Routing Refactor

#11409 fix: [M3-8970] - Duplicate VPCs fetch on Linode Create
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/src/components/VPCSelect.test.tsx
  packages/manager/src/components/VPCSelect.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/VPCPanel.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DeleteLinodeDialog.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketProductSelectionFields.tsx
  packages/manager/src/hooks/useUnassignLinode.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/queries/regions/regions.ts
  packages/manager/src/queries/vpcs/requests.ts
  packages/manager/src/queries/vpcs/vpcs.ts
Labels: Bug, Approved

#11430 tech-story: [M3-6904] - Replace react-select instances in /Users with new Select
  packages/manager/.changeset/pr-11430-tech-stories-1734463578200.md
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/ui/src/components/Select/Select.tsx
Labels: Approved, Tech Debt

#11433 fix: CloudPulse metric definition types
  packages/api-v4/.changeset/pr-11433-changed-1734483970019.md
  packages/api-v4/.changeset/pr-11433-removed-1734484000708.md
  packages/api-v4/src/cloudpulse/services.ts
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-11433-tech-stories-1734484023886.md
  packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-dashboard-errors.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/cypress/support/intercepts/cloudpulse.ts
  packages/manager/src/factories/dashboards.ts
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/MetricCriteria.test.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidgetRenderer.tsx
  packages/manager/src/queries/cloudpulse/services.ts
Labels: Approved, Cloud Pulse

#11437 fix: [M3-9032] - ARIA label of action menu in Domains Landing table row
  packages/manager/.changeset/pr-11437-fixed-1734527875368.md
  packages/manager/cypress/e2e/core/domains/smoke-clone-domain.spec.ts
  packages/manager/cypress/e2e/core/domains/smoke-delete-domain.spec.ts
  packages/manager/src/features/Domains/DomainActionMenu.tsx
Labels: Bug, Approved

#11422 test: [M3-8864] - Cypress tests to validate errors in Linode Create Backups tab
  packages/manager/.changeset/pr-11422-tests-1734356272451.md
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
Labels: e2e, Approved

#11339 fix: [M3-8451] - List events in event landing page in chronological order
  packages/manager/.changeset/pr-11339-fixed-1732776925827.md
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/Events/EventsLanding.tsx
  packages/manager/src/features/Events/utils.test.tsx
  packages/manager/src/features/Events/utils.tsx
  packages/manager/src/features/NotificationCenter/Events/NotificationCenterEvent.tsx
  packages/manager/src/utilities/eventUtils.test.ts
  packages/manager/src/utilities/eventUtils.ts
Labels: Approved

#11432 fix: [M3-9022, M3-9027] - Filter regions by endpoints and fix unavailable regions
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/BucketPermissionsTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/hooks/useIsObjectStorageGen2Enabled.tsx
  packages/manager/src/features/ObjectStorage/hooks/useObjectStorageRegions.tsx
  packages/manager/src/features/ObjectStorage/utilities.ts
Labels: Add'tl Approval Needed, Release → Staging, Hotfix

#11390 test: [M3-8768] - Cypress test flake: Rebuild Linode
  packages/manager/.changeset/pr-11390-tests-1733844253656.md
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
Labels: Approved

#11411 test: [M3-8979] - Fix lke-create test by using a different mock region
  packages/manager/.changeset/pr-11411-tests-1734023093705.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
Labels: Approved

#11441 Release v1.133.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/AccessKeyRegions.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/BucketPermissionsTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/hooks/useIsObjectStorageGen2Enabled.tsx
  packages/manager/src/features/ObjectStorage/hooks/useObjectStorageRegions.tsx
  packages/manager/src/features/ObjectStorage/utilities.ts
Labels: Release

#11431 fix: [M3-9021] - Various bugs in Managed tables
  packages/manager/.changeset/pr-11431-fixed-1734558226981.md
  packages/manager/src/features/Managed/Contacts/Contacts.tsx
  packages/manager/src/features/Managed/Contacts/ContactsActionMenu.tsx
  packages/manager/src/features/Managed/Contacts/ContactsRow.tsx
  packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx
  packages/manager/src/features/Managed/Credentials/CredentialActionMenu.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTable.styles.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTable.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTableContent.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessTableContent.tsx
Labels: Bug, Approved

#11397 feat: [UIE-8137] - IAM RBAC: add new user details component
  packages/api-v4/.changeset/pr-11397-upcoming-features-1734001143561.md
  packages/api-v4/src/iam/types.ts
  packages/manager/.changeset/pr-11397-upcoming-features-1733916688951.md
  packages/manager/src/factories/accountPermissions.ts
  packages/manager/src/features/IAM/Users/UserDetails/DeleteUserPanel.test.tsx
  packages/manager/src/features/IAM/Users/UserDetails/DeleteUserPanel.tsx
  packages/manager/src/features/IAM/Users/UserDetails/UserDeleteConfirmation.tsx
  packages/manager/src/features/IAM/Users/UserDetails/UserDetailsPanel.test.tsx
  packages/manager/src/features/IAM/Users/UserDetails/UserDetailsPanel.tsx
  packages/manager/src/features/IAM/Users/UserDetails/UserEmailPanel.test.tsx
  packages/manager/src/features/IAM/Users/UserDetails/UserEmailPanel.tsx
  packages/manager/src/features/IAM/Users/UserDetails/UserProfile.tsx
  packages/manager/src/features/IAM/Users/UserDetails/UsernamePanel.test.tsx
  packages/manager/src/features/IAM/Users/UserDetails/UsernamePanel.tsx
  packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
Labels: Approved, IAM (Identity & Access Management)

#11435 test: [M3-8863, M3-9040] - Cypress test to validate aria label of Linode IP Addresses/Ranges action menu
  packages/manager/.changeset/pr-11435-tests-1734516339389.md
  packages/manager/cypress/e2e/core/linodes/linode-network.spec.ts
Labels: e2e, Approved

#11449 hotfix: Incorrect Region Options
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/AccessKeyRegions.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.tsx
  packages/manager/src/features/ObjectStorage/utilities.ts
Labels: Hotfix

#11451 Release v1.133.2 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/AccessKeyRegions.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.tsx
  packages/manager/src/features/ObjectStorage/utilities.ts
Labels: Release, Hotfix

#11443 change: [M3-9041] - Remove `Images are not encrypted` warning
  packages/manager/.changeset/pr-11443-removed-1734624899643.md
  packages/manager/cypress/e2e/core/images/create-image.spec.ts
  packages/manager/src/components/Encryption/constants.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.test.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
Labels: Approved, Images

#11460 fix: [M3-9049] - Resolve bucket size discrepancy in CM
  packages/manager/.changeset/pr-11460-fixed-1735030571347.md
  packages/manager/src/store/selectors/getSearchEntities.ts
Labels: Object Storage, Approved

#11446 upcoming: [M3-9001] - Footer Update
  packages/manager/src/MainContent.tsx
  packages/manager/src/Root.tsx
  packages/manager/src/dev-tools/dev-tools.css
  packages/manager/src/features/Footer.tsx
  packages/ui/src/foundations/themes/index.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Design Tokens

#11463 upcoming: [M3-8982] - Update Left Navigation
  packages/manager/src/MainContent.tsx
  packages/manager/src/Root.tsx
  packages/manager/src/assets/icons/entityIcons/bucket.svg
  packages/manager/src/assets/icons/entityIcons/database.svg
  packages/manager/src/assets/icons/entityIcons/linode.svg
  packages/manager/src/assets/icons/entityIcons/monitor.svg
  packages/manager/src/assets/icons/entityIcons/networking.svg
  packages/manager/src/assets/icons/more.svg
  packages/manager/src/assets/icons/pin-filled.svg
  packages/manager/src/assets/icons/pin-outline.svg
  packages/manager/src/components/PrimaryNav/PrimaryLink.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/PrimaryNav/SideMenu.test.tsx
  packages/manager/src/components/PrimaryNav/SideMenu.tsx
  packages/manager/src/dev-tools/dev-tools.css
  packages/manager/src/features/Footer.tsx
  packages/manager/src/features/TopMenu/TopMenu.stories.tsx
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/index.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Ready for Review, Design Tokens

#11462 upcoming: [M3-9002] - Replace hamburger icon in left navigation
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/index.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Add'tl Approval Needed, Design Tokens
