Repository linode/manager, pull requests merged in 2024-08, with the labels that each got.

#10733 test: [M3-8319] - Add CM Logout test
  packages/manager/.changeset/pr-10733-tests-1722436583624.md
  packages/manager/cypress/e2e/core/account/account-logout.spec.ts
  packages/manager/cypress/support/intercepts/account.ts
Labels: Testing, Approved

#10719 test: [M3-8197,M3-8150] - Cypress test for refactored events and placement group
  packages/manager/.changeset/pr-10719-tests-1722001957079.md
  packages/manager/cypress/e2e/core/notificationsAndEvents/events.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/create-linode-with-placement-groups.spec.ts
Labels: Testing, Approved

#10735 refactor: [M3-8366] – `DiskEncryption` slight refactor & renaming
  packages/manager/.changeset/pr-10735-tech-stories-1722524181846.md
  packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/Encryption/Encryption.test.tsx
  packages/manager/src/components/Encryption/Encryption.tsx
  packages/manager/src/components/Encryption/constants.tsx
  packages/manager/src/components/Encryption/utils.ts
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Backups.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Security.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx
Labels: Approved, Block Storage Encryption (BSE)

#10727 change: [M3-8362] – Update placement group policy text copy
  packages/manager/.changeset/pr-10727-changed-1722358178386.md
  packages/manager/src/features/PlacementGroups/PlacementGroupPolicyRadioGroup.tsx
  packages/manager/src/features/PlacementGroups/constants.ts
Labels: Approved, Placement Groups

#10715 refactor: [M3-6906] Replace Select with Autocomplete in: stackscripts and Images
  packages/manager/.changeset/pr-10715-tech-stories-1722374365063.md
  packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/update-stackscripts.spec.ts
  packages/manager/src/features/Images/ImageSelect.test.tsx
  packages/manager/src/features/Images/ImageSelect.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.test.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/utils.test.ts
  packages/manager/src/features/StackScripts/StackScriptForm/utils.ts
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedMultiSelect.tsx
  packages/manager/src/utilities/imageToItem.ts
Labels: Add'tl Approval Needed, Ready for Review

#10739 upcoming: [M3-8411] - Data Visualization Tokens
  packages/manager/.changeset/pr-10739-upcoming-features-1722528251084.md
  packages/manager/src/foundations/themes/dark.ts
  packages/manager/src/foundations/themes/index.ts
  packages/manager/src/foundations/themes/light.ts
Labels: Add'tl Approval Needed, Design Tokens

#10726 refactor: [M3-7438] - Query Key Factory for Object Storage
  packages/manager/.changeset/pr-10726-tech-stories-1722355169168.md
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/Uploaders/ObjectUploader/ObjectUploader.tsx
  packages/manager/src/features/Account/EnableObjectStorage.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/CreateFolderDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.tsx
  packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.test.tsx
  packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/queries/object-storage/queries.ts
  packages/manager/src/queries/object-storage/requests.ts
  packages/manager/src/queries/object-storage/utilities.ts
  packages/manager/src/queries/objectStorage.ts
Labels: React Query, Object Storage, Approved

#10736 upcoming: [M3-8301] - Added `/object-storage/endpoints` query and request
  packages/api-v4/src/object-storage/buckets.ts
  packages/api-v4/src/object-storage/objects.ts
  packages/manager/.changeset/pr-10736-upcoming-features-1722454894455.md
  packages/manager/src/queries/object-storage/queries.ts
  packages/manager/src/queries/object-storage/requests.ts
Labels: Approved, Object Storage Gen2

#10710 upcoming: [DI-19818] - Added line graph to CloudPulse widgets for different metrics
  packages/api-v4/.changeset/pr-10710-upcoming-features-1721901283228.md
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-10710-upcoming-features-1721901189629.md
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetColorPalette.ts
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Utils/utils.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/dashboards.ts
  packages/manager/src/queries/cloudpulse/metrics.ts
  packages/manager/src/queries/cloudpulse/queries.ts
  packages/manager/src/queries/cloudpulse/resources.ts
  packages/manager/src/queries/cloudpulse/services.ts
Labels: Approved, CloudPulse

#10743 fix: Region filter for Core tab in Linode Create v2
  packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.tsx
Labels: Approved, Linode Create Refactor, Gecko GA

#10757 test: [M3-8419] - Fix failing stackscript deploy test
  packages/manager/.changeset/pr-10757-tests-1722971426093.md
  packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts
Labels: Approved

#10758 change: [M3-8418] - Add documentation on changeset best practices
  docs/CONTRIBUTING.md
  docs/PULL_REQUEST_TEMPLATE.md
  packages/api-v4/.changeset/README.md
  packages/manager/.changeset/README.md
  packages/manager/.changeset/pr-10758-added-1722975143465.md
  packages/validation/.changeset/README.md
Labels: Approved, Documentation

#10697 test: [M3-8136] - Add Cypress integration test for closing support tickets
  packages/manager/.changeset/pr-10697-tests-1721417045353.md
  packages/manager/cypress/e2e/core/helpAndSupport/close-support-ticket.spec.ts
  packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts
  packages/manager/cypress/support/constants/help-and-support.ts
  packages/manager/cypress/support/intercepts/support.ts
Labels: Testing, Approved

#10759 test: Fix `EditImageDrawer.test.tsx` Unit Test Flake
  packages/manager/.changeset/pr-10759-tests-1723040352780.md
  packages/manager/src/features/Images/ImagesLanding/EditImageDrawer.test.tsx
Labels: Unit tests

#10747 upcoming: [DI-20050] - Added Data Rollup logic for graph data
  packages/api-v4/.changeset/pr-10747-upcoming-features-1723026166451.md
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-10747-upcoming-features-1723026263446.md
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Utils/unitConversion.test.ts
  packages/manager/src/features/CloudPulse/Utils/unitConversion.ts
  packages/manager/src/features/CloudPulse/Utils/utils.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx
  packages/manager/src/queries/cloudpulse/metrics.ts
Labels: Approved, CloudPulse

#10744 upcoming: [M3-8301] - Object Storage Gen2 Create Bucket Additions
  packages/api-v4/.changeset/pr-10744-changed-1722619037605.md
  packages/api-v4/src/object-storage/types.ts
  packages/manager/.changeset/pr-10744-upcoming-features-1722618984741.md
  packages/manager/src/factories/account.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Object Storage Gen2

#10730 test: M3-8148: Cypress tests for refactored Linode Create flow with add ons
  packages/manager/.changeset/pr-10730-tests-1722367873620.md
  packages/manager/cypress/e2e/core/linodes/create-linode-with-add-ons.spec.ts
  packages/manager/cypress/support/ui/pages/linode-create-page.ts
Labels: Testing, Approved

#10754 feat: [M3-7666] - Remove Animation from Search Results and Animate Icon Instead
  packages/manager/.changeset/pr-10754-added-1723039007976.md
  packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
  packages/manager/src/features/Search/SearchLanding.styles.ts
  packages/manager/src/features/Search/SearchLanding.test.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/searchLanding.css
Labels: Approved, Search

#10742 fix: [M3-8409] - Community Notifications in Event Messages v2 Refactor
  packages/manager/.changeset/pr-10742-fixed-1722601990368.md
  packages/manager/src/features/Events/Event.helpers.ts
  packages/manager/src/features/Events/EventRowV2.tsx
  packages/manager/src/features/Events/eventMessageGenerator.ts
  packages/manager/src/features/Events/factories/community.tsx
  packages/manager/src/features/Events/utils.test.tsx
  packages/manager/src/features/Events/utils.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEventV2.tsx
Labels: Approved

#10764 change: [M3-8429] - Add a "Sizing a pull request" section to `CONTRIBUTING.md`
  docs/CONTRIBUTING.md
  packages/manager/.changeset/pr-10764-added-1723149902254.md
Labels: Documentation

#10725 refactor: [M3-6913] Replace Select with Autocomplete in: linodes
  packages/manager/.changeset/pr-10725-tech-stories-1722343555187.md
  packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VLANAccordion.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VLANAccordion.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/ScheduleSettings.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/ScheduleSettings.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/DeviceSelection.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/KernelSelect.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/KernelSelect.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateDiskDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/utilities.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/utilities.ts
  packages/manager/src/features/Linodes/PowerActionsDialogOrDrawer.tsx
  packages/manager/src/utilities/analytics/utils.ts
Labels: Approved, Linodes

#10718 upcoming: [DI-19819] - Added a filter builder component for ACLP that builds the filters per service type
  packages/manager/.changeset/pr-10718-upcoming-features-1721988074945.md
  packages/manager/src/assets/icons/entityIcons/monitor.svg
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/factories/dashboards.ts
  packages/manager/src/factories/index.ts
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.test.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/Utils/constants.ts
  packages/manager/src/features/CloudPulse/Utils/models.ts
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
Labels: Add'tl Approval Needed, Requires Changes, CloudPulse

#10763 upcoming: [M3-8426] - Add Sentry Tag for Linode Create v2
  packages/manager/.changeset/pr-10763-upcoming-features-1723138942196.md
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
Labels: Linode Create Refactor

#10760 refactor: [M3-8421] - Update Linode Types to use a Query Key Factory
  packages/manager/.changeset/pr-10760-tech-stories-1723236539851.md
  packages/manager/src/containers/types.container.ts
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenuUtils.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/queries/linodes/requests.ts
  packages/manager/src/queries/types.ts
Labels: React Query, Approved

#10772 fix: [M3-7324] - LKE Cluster Create Tab Selection Reset Upon Adding Pool
  packages/manager/.changeset/pr-10772-fixed-1723476789978.md
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
Labels: LKE, Approved

#10750 upcoming: [M3-8367] – Add "Volume Encryption" section to Volume Create page
  packages/manager/.changeset/pr-10750-upcoming-features-1723139035892.md
  packages/manager/src/components/Encryption/Encryption.tsx
  packages/manager/src/components/Encryption/constants.tsx
  packages/manager/src/components/Encryption/utils.ts
  packages/manager/src/features/Volumes/VolumeCreate.test.tsx
  packages/manager/src/features/Volumes/VolumeCreate.tsx
Labels: Approved, Block Storage Encryption (BSE)

#10768 upcoming: [DI-16642] - Enable ACLP to be shown based on account capabilities
  packages/api-v4/.changeset/pr-10768-upcoming-features-1723463731514.md
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-10768-upcoming-features-1723464477834.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/factories/account.ts
  packages/manager/src/features/CloudPulse/Utils/utils.ts
Labels: Approved, CloudPulse

#10749 refactor: [M3-8240] - Allow URL path to open OBJ create access key drawer
  packages/manager/.changeset/pr-10749-tech-stories-1722885758140.md
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/ObjectStorage/index.tsx
Labels: Object Storage, Approved, Ready for Review

#10777 fix: [M3-8213] - Use correct spelling of Ukrainian capital
  packages/manager/.changeset/pr-10777-fixed-1723516402764.md
  packages/manager/cypress/e2e/core/billing/smoke-billing-activity.spec.ts
  packages/manager/src/assets/timezones/timezones.ts
Labels: Approved

#10751 upcoming: [M3-8399] - Secure VMs banners
  packages/manager/.changeset/pr-10751-upcoming-features-1722963124052.md
  packages/manager/cypress/support/e2e.ts
  packages/manager/cypress/support/setup/delete-internal-header.ts
  packages/manager/src/assets/logo/akamai-logo.svg
  packages/manager/src/components/AkamaiBanner/AkamaiBanner.styles.ts
  packages/manager/src/components/AkamaiBanner/AkamaiBanner.test.tsx
  packages/manager/src/components/AkamaiBanner/AkamaiBanner.tsx
  packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
  packages/manager/src/containers/withSecureVMNoticesEnabled.container.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Firewall.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/FirewallAuthorization.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/resolvers.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/hooks/useIsAkamaiAccount.test.ts
  packages/manager/src/hooks/useIsAkamaiAccount.ts
  packages/manager/src/hooks/useSecureVMNoticesEnabled.test.ts
  packages/manager/src/hooks/useSecureVMNoticesEnabled.ts
  packages/manager/src/request.test.tsx
  packages/manager/src/request.tsx
  packages/manager/src/types/ManagerPreferences.ts
  packages/manager/src/utilities/analytics/types.ts
Labels: Approved, Ready for Review, Secure VMs

#10722 fix: [M3-8126] - Fix and enable Linode Create flow v1 form events
  docs/tooling/analytics.md
  packages/manager/.changeset/pr-10722-tech-stories-1723478781442.md
  packages/manager/src/components/DetailsPanel/DetailsPanel.tsx
  packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCCreateDrawer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/SubnetContent.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.tsx
  packages/manager/src/hooks/useCreateVPC.ts
  packages/manager/src/utilities/analytics/formEventAnalytics.ts
  packages/manager/src/utilities/analytics/types.ts
  packages/manager/src/utilities/analytics/utils.test.ts
  packages/manager/src/utilities/analytics/utils.ts
Labels: Approved, Analytics

#10767 refractor: [M3-8437] - Prepare for React Query v5
  docs/tooling/react-query.md
  packages/manager/.changeset/pr-10767-tech-stories-1723554692779.md
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PromoDialog.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Billing/GooglePayProvider.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/EntityTransfersCreate.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferCancelDialog.tsx
  packages/manager/src/features/GlobalNotifications/ComplianceUpdateModal.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DeleteLinodeDialog.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/features/Users/UserDetail.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/hooks/useUnassignLinode.ts
  packages/manager/src/queries/account/betas.ts
  packages/manager/src/queries/account/oauth.ts
  packages/manager/src/queries/account/users.ts
  packages/manager/src/queries/cloudpulse/metrics.ts
  packages/manager/src/queries/databases/databases.ts
  packages/manager/src/queries/events/events.ts
  packages/manager/src/queries/images.ts
  packages/manager/src/queries/linodes/backups.ts
  packages/manager/src/queries/linodes/configs.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/queries/placementGroups.ts
  packages/manager/src/queries/profile/profile.ts
  packages/manager/src/queries/profile/tokens.ts
  packages/manager/src/queries/stackscripts.ts
  packages/manager/src/queries/vpcs/vpcs.ts
Labels: React Query, Approved, Ready for Review

#10775 upcoming: [M3-8368] – Add "Encryption" column to Volumes landing page
  packages/manager/.changeset/pr-10775-upcoming-features-1723502865486.md
  packages/manager/src/factories/volume.ts
  packages/manager/src/features/Volumes/VolumeTableRow.test.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
Labels: Approved, Block Storage Encryption (BSE)

#10782 fix: [M3-7558] - Update guide link for Secure Your Server Marketplace app
  packages/manager/.changeset/pr-10782-fixed-1723574317048.md
  packages/manager/src/features/OneClickApps/oneClickAppsv2.ts
Labels: Bug, Marketplace, Approved

#10778 change: [OCA-1411] - Use Passbolt CE full name
  packages/manager/.changeset/pr-10778-changed-1723563275697.md
  packages/manager/src/features/OneClickApps/oneClickAppsv2.ts
Labels: Marketplace

#10783 fix: 'Oh snap' error when creating VPC from Linode Create
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
Labels: Bug, Approved, Ready for Review

#10740 change: [M3-8209] - Update Region label globally
  packages/manager/.changeset/pr-10740-changed-1723488918061.md
  packages/manager/cypress/e2e/core/billing/billing-invoices.spec.ts
  packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/images/manage-image-regions.spec.ts
  packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/access-keys.smoke.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.smoke.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/create-linode-with-placement-groups.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.smoke.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-create.spec.ts
  packages/manager/cypress/support/intercepts/regions.ts
  packages/manager/cypress/support/plugins/fetch-linode-regions.ts
  packages/manager/cypress/support/util/regions.ts
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Backups/BackupLinodeRow.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ImageRegionRow.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.test.tsx
  packages/manager/src/features/Images/ImagesLanding/RegionsList.test.tsx
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Details/PlacementGroupPanel.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Summary/Summary.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Summary/Summary.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/shared/LinodeSelectTableRow.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeRow.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransfer.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesList.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.test.tsx
  packages/manager/src/queries/regions/regions.ts
Labels: UX/UI, Approved

#10779 fix: [M3-8443] - Enabled login history for unrestricted child accounts
  packages/manager/.changeset/pr-10779-fixed-1723593549058.md
  packages/manager/cypress/e2e/core/account/account-login-history.spec.ts
  packages/manager/src/features/Account/AccountLogins.tsx
Labels: Approved, Parent / Child Account

#10771 upcoming: [M3-8304] - Add Endpoint Type Column & Disable CORS for Gen2 Buckets
  packages/manager/.changeset/pr-10771-upcoming-features-1723731588900.md
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
Labels: Approved, Object Storage Gen2

#10766 refactor: Clean up Account Settings Object Storage
  packages/manager/.changeset/pr-10766-tech-stories-1723171237019.md
  packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts
  packages/manager/src/features/Account/EnableObjectStorage.test.tsx
  packages/manager/src/features/Account/EnableObjectStorage.tsx
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Account/ObjectStorageSettings.test.tsx
  packages/manager/src/features/Account/ObjectStorageSettings.tsx
  packages/manager/src/queries/object-storage/queries.ts
Labels: Object Storage, Approved

#10770 upcoming: [M3-8398] - Generate firewall dialog
  packages/api-v4/.changeset/pr-10770-added-1723479930096.md
  packages/api-v4/src/firewalls/firewalls.ts
  packages/api-v4/src/firewalls/types.ts
  packages/manager/.changeset/pr-10770-upcoming-features-1723479438379.md
  packages/manager/src/components/AkamaiBanner/AkamaiBanner.styles.ts
  packages/manager/src/components/AkamaiBanner/AkamaiBanner.tsx
  packages/manager/src/components/GenerateFirewallDialog/GenerateFirewallDialog.test.tsx
  packages/manager/src/components/GenerateFirewallDialog/GenerateFirewallDialog.tsx
  packages/manager/src/components/GenerateFirewallDialog/useCreateFirewallFromTemplate.ts
  packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
  packages/manager/src/factories/firewalls.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Firewalls/index.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Firewall.tsx
  packages/manager/src/hooks/useSecureVMNoticesEnabled.test.ts
  packages/manager/src/queries/firewalls.ts
  packages/manager/src/utilities/replaceNewlinesWithLineBreaks.test.tsx
  packages/manager/src/utilities/replaceNewlinesWithLineBreaks.tsx
Labels: Approved, Secure VMs

#10776 upcoming: [M3-8306] - Hide CORS and SSL for OBJ Gen2
  packages/manager/.changeset/pr-10776-upcoming-features-1723515799181.md
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketAccess.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
  packages/manager/src/queries/object-storage/queries.ts
Labels: Approved, Object Storage Gen2

#10791 change: [M3-6843] - Move manual snapshot error message to snapshot confirmation dialog
  packages/manager/.changeset/pr-10791-changed-1723820950904.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/CaptureSnapshot.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/CaptureSnapshotConfirmationDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/CaptureSnapshotConfirmationDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
Labels: Approved

#10787 upcoming: [M3-8369] – Add "Encrypt Volume" checkbox in Edit Volume drawer
  packages/manager/.changeset/pr-10787-upcoming-features-1723672538179.md
  packages/manager/src/components/Encryption/constants.tsx
  packages/manager/src/features/Volumes/EditVolumeDrawer.test.tsx
  packages/manager/src/features/Volumes/EditVolumeDrawer.tsx
Labels: Approved, Block Storage Encryption (BSE)

#10790 upcoming: [M3-8301] - Updated Bucket Rate Limits
  packages/manager/.changeset/pr-10790-upcoming-features-1724031092075.md
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
Labels: Add'tl Approval Needed, Ready for Review, Object Storage Gen2

#10761 test: [M3-8149] - Add test for Linode create error flows
  packages/manager/.changeset/pr-10761-tests-1723056815829.md
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: Approved

#10769 upcoming: [DI-20204] - Added Interface type setup, query updates and enhanced preferences type for upcoming Cloudpulsecustomselect component
  packages/api-v4/.changeset/pr-10769-upcoming-features-1723465718778.md
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-10769-upcoming-features-1723465772614.md
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/Utils/models.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/queries/cloudpulse/customfilters.ts
  packages/manager/src/queries/cloudpulse/queries.ts
  packages/manager/src/queries/databases/databases.ts
  packages/manager/src/queries/databases/requests.ts
Labels: Approved, CloudPulse

#10789 change: [M3-8456] - Update LISH experience based on feedback
  packages/manager/.changeset/pr-10789-changed-1724075831126.md
  packages/manager/.changeset/pr-10789-changed-1724075913480.md
  packages/manager/package.json
  packages/manager/src/features/Lish/Weblish.tsx
  packages/manager/src/features/Lish/lishUtils.ts
  yarn.lock
Labels: Ready for Review

#10745 feat: [M3-8336] - Improve support ticket form pre-population and field labels
  packages/manager/.changeset/pr-10745-changed-1723666784731.md
  packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts
  packages/manager/src/components/ErrorMessage.tsx
  packages/manager/src/components/SupportLink/SupportLink.tsx
  packages/manager/src/components/SupportTicketGeneralError.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Error.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketAccountLimitFields.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketProductSelectionFields.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
  packages/manager/src/features/Support/SupportTickets/constants.tsx
  packages/manager/src/features/Support/SupportTickets/ticketUtils.test.ts
  packages/manager/src/features/Support/SupportTickets/ticketUtils.ts
Labels: Approved

#10800 refactor: [M3-8459] - Remove `patch-package` package
  docs/development-guide/01-repository-structure.md
  package.json
  packages/manager/.changeset/pr-10800-tech-stories-1724094117438.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved, Clean Up

#10801 upcoming: [M3-8187] - Add useRegionQuery and cleanup bucket landing page
  packages/api-v4/.changeset/pr-10801-changed-1724274276545.md
  packages/api-v4/src/object-storage/clusters.ts
  packages/manager/.changeset/pr-10801-upcoming-features-1724274214381.md
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_BucketLanding.tsx
  packages/manager/src/queries/object-storage/queries.ts
  packages/manager/src/queries/object-storage/requests.ts
  packages/manager/src/queries/regions/regions.ts
Labels: Ready for Review, Object Storage Gen2

#10811 test: [M3-8458] - Fix StackScripts pagination test failure
  packages/manager/.changeset/pr-10811-tests-1724336950451.md
  packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscripts.spec.ts
Labels: Approved

#10812 fix: Re-enable CORS for Legacy/Gen1 Endpoints
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Ready for Review, Hotfix

#10816 fix: Re-enable CORS for Legacy/Gen1 Endpoints
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Release → Staging, Hotfix

#10817 Release v1.126.1 - `staging` → `master`
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Release, Approved

#10793 upcoming: [M3-8370] – Add "Encryption" column to Linode Volumes table
  packages/manager/.changeset/pr-10793-upcoming-features-1723845275155.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
Labels: Approved, Block Storage Encryption (BSE)

#10803 upcoming: [M3-8455] – Add "Encrypt Volume" checkbox in Clone Volume drawer
  packages/manager/.changeset/pr-10803-upcoming-features-1724100276144.md
  packages/manager/src/components/Encryption/constants.tsx
  packages/manager/src/features/Volumes/CloneVolumeDrawer.test.tsx
  packages/manager/src/features/Volumes/CloneVolumeDrawer.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/PricePanel.tsx
Labels: Approved, Block Storage Encryption (BSE)

#10805 upcoming: [DI-20284] - Added support for multiple services in the dashboards list
  packages/api-v4/.changeset/pr-10805-upcoming-features-1724163902024.md
  packages/api-v4/src/cloudpulse/dashboards.ts
  packages/api-v4/src/cloudpulse/services.ts
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-10805-upcoming-features-1724163948287.md
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.test.tsx
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
  packages/manager/src/features/CloudPulse/Utils/utils.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/dashboards.ts
  packages/manager/src/queries/cloudpulse/metrics.ts
  packages/manager/src/queries/cloudpulse/queries.ts
  packages/manager/src/queries/cloudpulse/services.ts
Labels: Approved, CloudPulse

#10784 feat: [M3-8170] - Add CheckoutBar Story
  packages/manager/.changeset/pr-10784-added-1723651941893.md
  packages/manager/src/components/CheckoutBar/CheckoutBar.stories.tsx
  packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
Labels: Storybook, Approved

#10796 upcoming: [M3-8305] - Display Endpoint Type alongside each endpoint hostname in Regions Column & Hostnames Drawers
  packages/manager/.changeset/pr-10796-upcoming-features-1724152512210.md
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTable.styles.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTableRow.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesDrawer.tsx
Labels: Add'tl Approval Needed, Object Storage Gen2

#10786 feat: [UIE-8054] - DBaaS enhancements 1
  packages/api-v4/.changeset/pr-10786-added-1723662117687.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/databases/types.ts
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-10786-upcoming-features-1723662207016.md
  packages/manager/src/__data__/regionsData.ts
  packages/manager/src/assets/icons/db-logo.svg
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/factories/account.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.test.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: DBaaS, Approved

#10824 fix: [M3-8477] - Event handlers making a proportional number of GET requests to the number of incoming events
  packages/manager/.changeset/pr-10824-fixed-1724428840947.md
  packages/manager/cypress/e2e/core/notificationsAndEvents/events-fetching.spec.ts
  packages/manager/src/hooks/EventHandlerData.ts
  packages/manager/src/hooks/useEventHandlers.ts
  packages/manager/src/queries/account/billing.ts
  packages/manager/src/queries/account/oauth.ts
  packages/manager/src/queries/databases/events.ts
  packages/manager/src/queries/domains.ts
  packages/manager/src/queries/firewalls.ts
  packages/manager/src/queries/images.ts
  packages/manager/src/queries/linodes/events.ts
  packages/manager/src/queries/nodebalancers.ts
  packages/manager/src/queries/profile/profile.ts
  packages/manager/src/queries/profile/tokens.ts
  packages/manager/src/queries/stackscripts.ts
  packages/manager/src/queries/support.ts
  packages/manager/src/queries/volumes/events.ts
Labels: Bug, React Query, Approved

#10809 change: [M3-8210] - Storybook nav organization POC
  packages/manager/.changeset/pr-10809-changed-1724354812801.md
  packages/manager/.storybook/preview.tsx
  packages/manager/src/assets/logo/akamai-logo-color.svg
  packages/manager/src/components/Accordion.stories.tsx
  packages/manager/src/components/BetaChip/BetaChip.stories.tsx
  packages/manager/src/components/Box.stories.tsx
  packages/manager/src/components/Breadcrumb/Breadcrumb.stories.tsx
  packages/manager/src/components/Button/Button.stories.tsx
  packages/manager/src/components/Button/StyledTagButton.stories.tsx
  packages/manager/src/components/Checkbox.stories.tsx
  packages/manager/src/components/Chip.stories.tsx
  packages/manager/src/components/Currency/Currency.stories.tsx
  packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.stories.tsx
  packages/manager/src/components/Divider.stories.tsx
  packages/manager/src/components/DocsLink/DocsLink.stories.tsx
  packages/manager/src/components/EditableText/EditableText.stories.tsx
  packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.stories.tsx
  packages/manager/src/components/EntityIcon/EntityIcon.stories.tsx
  packages/manager/src/components/Flag.stories.tsx
  packages/manager/src/components/InlineMenuAction/InlineMenuAction.stories.tsx
  packages/manager/src/components/Link.stories.tsx
  packages/manager/src/components/OSIcon.stories.tsx
  packages/manager/src/components/Paper.stories.tsx
  packages/manager/src/components/PasswordInput/HideShowText.stories.tsx
  packages/manager/src/components/PasswordInput/PasswordInput.stories.tsx
  packages/manager/src/components/Radio/Radio.stories.tsx
  packages/manager/src/components/ShowMoreExpansion/ShowMoreExpansion.stories.tsx
  packages/manager/src/components/Stack.stories.tsx
  packages/manager/src/components/StatusIcon/StatusIcon.stories.tsx
  packages/manager/src/components/Tabs/Tabs.stories.tsx
  packages/manager/src/components/TextField.stories.tsx
  packages/manager/src/components/Toggle/Toggle.stories.tsx
  packages/manager/src/components/Typography.stories.tsx
Labels: Build and Organization, Proof of Concept, Storybook, Approved

#10827 change: [M3-8384] - Update storybook to fix dependency vulnerabilities
  packages/manager/.changeset/pr-10827-tech-stories-1724432793341.md
  packages/manager/package.json
  yarn.lock
Labels: Storybook, Approved

#10818 test: [M3-8463] - Add unit tests for CheckoutBar component
  packages/manager/.changeset/pr-10818-tests-1724394944251.md
  packages/manager/src/components/CheckoutBar/CheckoutBar.test.tsx
  packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
Labels: Approved, Unit tests

#10830 change: [M3-8383] - Packages updates and resolution for braces vulnerability
  package.json
  packages/api-v4/package.json
  packages/manager/.changeset/pr-10830-tech-stories-1724469419694.md
  packages/manager/package.json
  packages/validation/package.json
  yarn.lock
Labels: Dependencies

#10829 change: [M3-8382] - Update jsdom to remove WS package vulnerability
  packages/manager/.changeset/pr-10829-tech-stories-1724462593074.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Tech Debt

#10310 test: [M3-7852] Use test weights for Jenkins/Cypress parallelization
  docs/development-guide/08-testing.md
  packages/manager/cypress.config.ts
  packages/manager/cypress/support/plugins/generate-weights.ts
  packages/manager/cypress/support/plugins/split-run.ts
Labels: Proof of Concept, Ready for Review

#10833 fix: [M3-7760] - Create SSH key drawer hidden by Rebuild Linode dialog
  packages/manager/.changeset/pr-10833-fixed-1724689652747.md
  packages/manager/src/features/Profile/SSHKeys/CreateSSHKeyDrawer.tsx
Labels: Bug, Ready for Review

#10826 test: [M3-8478] - Fix Cypress StackScript Linode deploy test flake
  packages/manager/.changeset/pr-10826-tests-1724431261722.md
  packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
  packages/manager/cypress/support/intercepts/account.ts
  packages/manager/cypress/support/ui/autocomplete.ts
Labels: Approved, Ready for Review

#10807 upcoming: [DI-20348] - Changes for Adding CloudPulseCustomSelect component and Integration
  packages/manager/.changeset/pr-10807-upcoming-features-1724226251911.md
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelectUtils.test.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelectUtils.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/customfilters.ts
Labels: CloudPulse

#10840 change: [M3-8439] - Tag form events in Linode Create v2
  packages/manager/.changeset/pr-10840-tech-stories-1724713234913.md
  packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Details/PlacementGroupPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Firewall.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Plan.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts
Labels: Approved, Analytics

#10821 upcoming: [M3-8308] - Add bucket rate limit info to Object Storage Bucket Details drawer
  packages/manager/.changeset/pr-10821-upcoming-features-1724414057285.md
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
Labels: Approved, Object Storage Gen2

#10762 refactor: [M3-8184] - Improve local Storybook performance
  packages/manager/.changeset/pr-10762-tech-stories-1723134446106.md
  packages/manager/.storybook/main.ts
  packages/manager/.storybook/utils.test.ts
  packages/manager/.storybook/utils.ts
Labels: Storybook, Performance

#10828 fix: [M3-8453] - Update error text color in confirmation dialogs to use theme, refactor styling
  packages/manager/.changeset/pr-10828-fixed-1724688319150.md
  packages/manager/.changeset/pr-10828-tests-1724688351092.md
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.test.tsx
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/components/Dialog/Dialog.tsx
Labels: Approved

#10832 test: [M3-8486] - Allow using Cypress region selection helpers with mock regions
  packages/manager/.changeset/pr-10832-tests-1724681646686.md
  packages/manager/cypress/support/ui/autocomplete.ts
Labels: Approved, Ready for Review

#10797 upcoming: [M3-8378] - Add Bucket Management `Properties` Tab for Object Storage Gen2
  packages/manager/.changeset/pr-10795-upcoming-features-1724084768188.md
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketProperties.styles.ts
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketProperties.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
Labels: Approved, Object Storage Gen2

#10808 change: [M3-8075] - "Create Volume" button text changed to "Add Volume".
  packages/manager/.changeset/pr-10808-changed-1724315097131.md
  packages/manager/cypress/e2e/core/volumes/create-volume.smoke.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.tsx
Labels: Approved

#10842 fix: [M3-8466] - Improve validation rules for create bucket schema
  packages/validation/.changeset/pr-10842-fixed-1724786185430.md
  packages/validation/src/buckets.schema.ts
Labels: Bug, Object Storage, Approved

#10774 test: [M3-8432] - Cypress integration test for Object Storage Gen2: E0 endpoint, some additional unit tests
  packages/manager/.changeset/pr-10774-tests-1723501645286.md
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
  packages/manager/cypress/support/intercepts/object-storage.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.test.tsx
Labels: Testing, Approved, Object Storage Gen2

#10846 fix: [M3-8500] - Restricted users without account access unable to create Linodes on Linode Create v2
  packages/manager/.changeset/pr-10846-fixed-1724859567426.md
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/resolvers.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts
Labels: Bug, Approved

#10847 fix: [M3-8467] - Improve validation rules for create bucket schema
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/validation/.changeset/pr-10842-fixed-1724786185430.md
  packages/validation/src/buckets.schema.ts
Labels: Bug, Approved

#10838 fix: [M3-8492] - Create Linode Firewall warning not appearing
  packages/manager/.changeset/pr-10838-fixed-1724705410961.md
  packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Firewall.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/FirewallAuthorization.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/resolvers.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
Labels: Ready for Review, Secure VMs

#10822 fix: [M3-7305] - Correct Object Storage folder links containing special characters
  .gitignore
  packages/manager/.changeset/pr-10819-fixed-1724404332335.md
  packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx
Labels: Bug, Object Storage, Approved

#10848 change: [M3-8379] - Disable Region in OS tab for unsupported distributed images
  packages/manager/.changeset/pr-10848-changed-1724869290917.md
  packages/manager/src/components/RegionSelect/RegionSelect.styles.ts
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.utils.test.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.utils.ts
Labels: Approved, Gecko Beta

#10814 tech story: [M3-8385] - Replace lodash set utility function to handle prototype pollution security threat
  packages/manager/.changeset/pr-10814-tech-stories-1724434847753.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts
  packages/manager/src/utilities/formikErrorUtils.test.ts
  packages/manager/src/utilities/formikErrorUtils.ts
  yarn.lock
Labels: Approved, Ready for Review

#10855 fix: [M3-7142] - Update helper text copy in NodeBalancer Create form 'Algorithm' field
  packages/manager/.changeset/pr-10855-fixed-1724944515841.md
  packages/manager/.changeset/pr-10855-tests-1724944533420.md
  packages/manager/src/features/NodeBalancers/NodeBalancerActiveCheck.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
  packages/manager/src/features/NodeBalancers/types.ts
Labels: Bug, Approved, Ready for Review
