Repository linode/manager, pull requests merged in 2024-03, with the labels that each got.

#10237 upcoming: [M3-7816] - Hide "Switch Account" buttons if child_account_access is false
  packages/manager/.changeset/pr-10237-upcoming-features-1709143756413.md
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
Labels: Bug, Approved, Parent / Child Account

#10238 upcoming: [M3-7727] - Only support Edge to Edge Migrations
  packages/manager/.changeset/pr-10238-upcoming-features-1709143092179.md
  packages/manager/src/__data__/regionsData.ts
  packages/manager/src/components/RegionSelect/RegionSelect.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.ts
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Gecko Beta

#10204 test: [M3-7497] - Add tests for child user verification banner
  packages/manager/.changeset/pr-10204-tests-1708976001328.md
  packages/manager/cypress/e2e/core/account/user-verification-banner.spec.ts
  packages/manager/cypress/support/constants/user.ts
Labels: Approved, Parent / Child Account

#10249 fix: React Query `updateInPaginatedStore` helper function not working as expected
  packages/manager/src/queries/base.ts
Labels: Bug, React Query, Approved

#10241 refactor: [M3-7437] - Use `@lukemorales/query-key-factory` for Profile Queries
  docs/development-guide/05-fetching-data.md
  docs/tooling/react-query.md
  packages/manager/.changeset/pr-10241-tech-stories-1709241014115.md
  packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts
  packages/manager/package.json
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/hooks/useInitialRequests.ts
  packages/manager/src/queries/base.ts
  packages/manager/src/queries/databases.ts
  packages/manager/src/queries/domains.ts
  packages/manager/src/queries/firewalls.ts
  packages/manager/src/queries/images.ts
  packages/manager/src/queries/kubernetes.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/queries/nodebalancers.ts
  packages/manager/src/queries/placementGroups.ts
  packages/manager/src/queries/profile.ts
  packages/manager/src/queries/tokens.ts
  packages/manager/src/queries/volumes.ts
  yarn.lock
Labels: Enhancement, React Query

#10205 upcoming: [M3 7738] - Update Placement Group Create & Edit Drawers
  packages/api-v4/src/placement-groups/placement-groups.ts
  packages/manager/.changeset/pr-10205-changed-1709570324014.md
  packages/manager/.changeset/pr-10205-upcoming-features-1709303410944.md
  packages/manager/src/__data__/regionsData.ts
  packages/manager/src/components/TextField.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsAffinityEnforcementRadioGroup.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsAffinityTypeSelect.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDrawerContent.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDrawerContent.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsRenameDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsRenameDrawer.tsx
  packages/manager/src/features/PlacementGroups/index.tsx
  packages/manager/src/features/PlacementGroups/types.ts
  packages/manager/src/features/PlacementGroups/utils.test.ts
  packages/manager/src/features/PlacementGroups/utils.ts
  packages/manager/src/queries/placementGroups.ts
  packages/validation/src/placement-groups.schema.ts
Labels: Approved, Placement Groups

#10252 upcoming: [M3-7835] - Adjust user table column count
  packages/manager/.changeset/pr-10252-upcoming-features-1709581147040.md
  packages/manager/src/features/Users/UsersLanding.tsx
  packages/manager/src/features/Users/UsersLandingProxyTableHead.tsx
  packages/manager/src/features/Users/UsersLandingTableBody.tsx
  packages/manager/src/features/Users/UsersLandingTableHead.tsx
Labels: Add'tl Approval Needed, Ready for Review, Parent / Child Account

#10259 upcoming: [M3-7839] - Change Business Partner to Parent User
  packages/manager/.changeset/pr-10259-upcoming-features-1709654629410.md
  packages/manager/cypress/e2e/core/account/account-login-history.spec.ts
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/cypress/e2e/core/account/user-profile.spec.ts
  packages/manager/cypress/e2e/core/account/user-verification-banner.spec.ts
  packages/manager/src/features/Account/constants.ts
  packages/manager/src/features/Account/utils.ts
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Users/UserProfile.tsx
  packages/manager/src/features/Users/UsersLanding.tsx
Labels: Approved, Parent / Child Account

#10256 upcoming: [M3-7723] - Placement Group feature flag as object
  docs/development-guide/11-feature-flags.md
  packages/manager/.changeset/pr-10256-upcoming-features-1709671609446.md
  packages/manager/src/components/DetailsPanel/DetailsPanel.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
Labels: Approved, Placement Groups

#10245 test: Resolve OBJ create and delete E2E test flake
  packages/manager/.changeset/pr-10245-tests-1709311899662.md
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
  packages/manager/cypress/support/intercepts/account.ts
Labels: Approved

#10227 refactor: [M3-7687] - Linodes Restricted User Experience 2/2
  packages/manager/.changeset/pr-10227-tech-stories-1708986866364.md
  packages/manager/src/components/EmptyLandingPageResources/ResourcesSection.tsx
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/components/TagCell/TagDrawer.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.test.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.tsx
  packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailFooter.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeCard.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodePanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeRow.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeTable.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodePermissionsError.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettings.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLandingEmptyState.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
  packages/manager/src/utilities/linodes.ts
Labels: Approved, Restricted User Access

#10264 fix: [M3-7824] - ACLB TCP Rule Creation and other fixes
  packages/api-v4/.changeset/pr-10264-changed-1709750042330.md
  packages/api-v4/src/aclb/types.ts
  packages/manager/.changeset/pr-10264-fixed-1709749998087.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RuleRow.tsx
  packages/validation/.changeset/pr-10264-changed-1709750194085.md
  packages/validation/src/loadbalancers.schema.ts
Labels: Bug, Approved, ACLB

#10267 test: Fix test flake for Images landing page test
  packages/manager/.changeset/pr-10267-tests-1709834235631.md
  packages/manager/cypress/e2e/core/images/images-empty-landing-page.spec.ts
Labels: Approved

#10222 upcoming: [M3-7704] - Disable Cloning, Private IP, Backups for edge regions
  packages/manager/.changeset/pr-10222-upcoming-features-1708978137113.md
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.ts
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenu.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenu.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Wait to Merge, Approved, Gecko Beta

#10263 upcoming: [M3-7842] - Update Assign Linode Drawer and improve query skipping
  packages/manager/.changeset/pr-10263-upcoming-features-1709749179406.md
  packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsUnassignModal.tsx
  packages/manager/src/features/PlacementGroups/constants.ts
  packages/manager/src/hooks/usePlacementGroupsData.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Placement Groups

#10254 fix: [M3-7831] - Persisting error messages in ACLB delete dialogs
  packages/manager/.changeset/pr-10254-fixed-1709590335168.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/DeleteCertificateDialog.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/DeleteConfigurationDialog.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/DeleteRouteDialog.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/DeleteRuleDialog.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/DeleteServiceTargetDialog.tsx
Labels: Bug, Approved, ACLB

#10266 upcoming: [M3-7816-v2] - Adjust logic for when to show Switch Account button
  packages/manager/cypress/e2e/core/parentChild/account-switching.spec.ts
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
Labels: Ready for Review, Parent / Child Account

#10233 fix: [M3-7817] - Show correct status of Child Account Enabled column for parent users
  packages/manager/.changeset/pr-10233-upcoming-features-1709140962559.md
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Users/UserRow.tsx
  packages/manager/src/features/Users/UsersLandingTableBody.tsx
Labels: Bug, Approved, Parent / Child Account

#10218 upcoming: [M3-7697] - Add scrolling for S3 hostnames in the Access Keys modal
  packages/manager/.changeset/pr-10218-upcoming-features-1708616641655.md
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesList.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesList.tsx
  packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
Labels: Approved, OBJ Multi-Cluster

#10255 upcoming: [M3-7724] - Linode plan table updates for Edge regions
  packages/manager/.changeset/pr-10255-upcoming-features-1709738933221.md
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/components/PlansPanel/EdgePlanTable.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
Labels: Add'tl Approval Needed, Gecko Beta

#10261 refactor: [M3-6708] – Implement new React 18 hooks
  docs/development-guide/13-coding-standards.md
  packages/manager/.changeset/pr-10261-tech-stories-1709842863706.md
  packages/manager/src/components/GroupByTagToggle.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx
Labels: Approved

#10271 change: [M3-7856] - Update ACLB Match Condition Tooltips and Placeholders
  packages/manager/.changeset/pr-10271-changed-1710174159065.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/constants.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts
Labels: Approved, ACLB

#10270 upcoming: [M3-7857] - Account Management Copy Updates & Improvements
  packages/manager/.changeset/pr-10270-upcoming-features-1710171371281.md
  packages/manager/cypress/e2e/core/account/display-settings.spec.ts
  packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts
  packages/manager/cypress/e2e/core/account/user-profile.spec.ts
  packages/manager/src/features/Account/CloseAccountSetting.test.tsx
  packages/manager/src/features/Account/CloseAccountSetting.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.tsx
  packages/manager/src/features/Account/constants.ts
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/Profile/APITokens/APITokenMenu.tsx
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
Labels: Bug, Parent / Child Account

#10268 feat: [M3-7806] - Linode Create Refactor - Part 1
  packages/api-v4/.changeset/pr-10268-changed-1710182395545.md
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-10268-tech-stories-1709929859267.md
  packages/manager/cypress/support/api/linodes.ts
  packages/manager/package.json
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Error.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Plan.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Summary.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/index.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
  yarn.lock
Labels: Approved, Linode Create Refactor

#10272 feat: Add March 2024 apps to Marketplace
  packages/manager/.changeset/pr-10272-added-1710176373422.md
  packages/manager/public/assets/linuxgsm.svg
  packages/manager/public/assets/passbolt.svg
  packages/manager/public/assets/white/linuxgsm.svg
  packages/manager/public/assets/white/passbolt.svg
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Marketplace

#10244 upcoming: [M3-7798] - Update Buckets landing page to use regions instead of clusters.
  packages/api-v4/.changeset/pr-10244-upcoming-features-1709582607964.md
  packages/api-v4/src/object-storage/buckets.ts
  packages/manager/.changeset/pr-10244-upcoming-features-1709333927883.md
  packages/manager/cypress/e2e/core/objectStorage/object-storage.smoke.spec.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/objectStorage.ts
Labels: Approved, Ready for Review, OBJ Multi-Cluster

#10274 change: [M3-7860] - Source ACLB region info from API data and use Jakarta instead of Sydney
  packages/manager/.changeset/pr-10274-changed-1710189301907.md
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerRegions.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRegions.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerSummary.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Settings/Region.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerRow.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/RegionItem.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/RegionItem.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/RegionsCell.tsx
  packages/manager/src/features/LoadBalancers/constants.ts
Labels: Ready for Review, ACLB

#10276 fix: [M3-7826-v2] - Fix email displaying in top menu for all users without a company name
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/TopMenu/UserMenu/utils.test.ts
  packages/manager/src/features/TopMenu/UserMenu/utils.ts
Labels: Bug, Approved, Parent / Child Account

#10279 fix: [M3-7867] -Ensure IP / Mask for firewall rules drawer correctly populates
  packages/manager/.changeset/pr-10279-fixed-1710360079232.md
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleForm.tsx
Labels: Bug, Approved

#10277 upcoming: [M3-7866] - Improve Proxy Account Visibility with Distinct Visual Indicators
  packages/manager/.changeset/pr-10277-upcoming-features-1710340806902.md
  packages/manager/src/assets/icons/parent-child.svg
  packages/manager/src/components/GravatarForProxy.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
Labels: Approved, Parent / Child Account

#10269 upcoming: [M3-7855] - Updates to PATs for Restricted Parent Users
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerSummary.tsx
  packages/manager/src/features/Profile/APITokens/APITokenMenu.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/utils.test.ts
Labels: Bug, Parent / Child Account

#10280 feat: [M3-7829] - Linode Clone UI refinements
  packages/manager/.changeset/pr-10280-added-1710363273220.md
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeCards.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeRow.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeRow.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeTable.tsx
Labels: Approved, Linode Clone UI Updates

#10284 upcoming: [M3-7868] - Gecko Beta Demo feedback
  packages/manager/.changeset/pr-10284-upcoming-features-1710432233464.md
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/Linodes/MigrateLinode/CautionNotice.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
Labels: Approved, Gecko Beta

#10291 chore: Update `axios` to resolve `follow-redirects` CVE-2024-28849
  packages/api-v4/.changeset/pr-10291-tech-stories-1710770920874.md
  packages/api-v4/package.json
  packages/manager/.changeset/pr-10291-tech-stories-1710770854595.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved

#10295 fix: `SMTPRestrictionText.test.tsx` MSW Change
  packages/manager/src/features/Linodes/SMTPRestrictionText.test.tsx
Labels: Approved

#10298 fix: [M3-7894] - Hide bullet for single notice
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodePanel.tsx
Labels: Linode Clone UI Updates

#10273 upcoming: [M3-7691] - Create PG in Linode Create Flow
  packages/manager/.changeset/pr-10273-upcoming-features-1710350268383.md
  packages/manager/src/__data__/regionsData.ts
  packages/manager/src/components/DetailsPanel/DetailsPanel.test.tsx
  packages/manager/src/components/DetailsPanel/DetailsPanel.tsx
  packages/manager/src/components/PlacementGroupsSelect/PlacementGroupSelectOption.tsx
  packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.test.tsx
  packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroups.styles.ts
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx
  packages/manager/src/features/PlacementGroups/constants.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Placement Groups

#10288 test: [M3-7517 & M3-7519] - Cypress integration tests for Child -> Parent and Child -> Child account switching
  packages/manager/.changeset/pr-10288-tests-1710450875663.md
  packages/manager/cypress/e2e/core/parentChild/account-switching.spec.ts
  packages/manager/cypress/support/intercepts/account.ts
Labels: Approved, Parent / Child Account

#10281 upcoming: [M3-7869] - Linode Create Refactor - Part 2 - Images and Distributions
  packages/api-v4/.changeset/pr-10281-changed-1710871902134.md
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-10281-tech-stories-1710376996913.md
  packages/manager/src/components/DistributionIcon.stories.tsx
  packages/manager/src/components/DistributionIcon.test.tsx
  packages/manager/src/components/DistributionIcon.tsx
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/components/ImageSelect/icons.ts
  packages/manager/src/components/ImageSelectv2/ImageOptionv2.test.tsx
  packages/manager/src/components/ImageSelectv2/ImageOptionv2.tsx
  packages/manager/src/components/ImageSelectv2/ImageSelectv2.stories.tsx
  packages/manager/src/components/ImageSelectv2/ImageSelectv2.test.tsx
  packages/manager/src/components/ImageSelectv2/ImageSelectv2.tsx
  packages/manager/src/components/ImageSelectv2/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Plan.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Summary.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/tabs/Distributions.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/tabs/Distributions.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/tabs/Images.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/tabs/Images.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/utilities.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts
  packages/manager/src/foundations/themes/light.ts
  packages/manager/src/index.tsx
  packages/manager/src/utilities/testHelpers.tsx
  packages/validation/.changeset/pr-10281-changed-1710865045363.md
  packages/validation/src/linodes.schema.ts
Labels: Add'tl Approval Needed, Linode Create Refactor

#10262 change: [UIE-7308] - Notifications for database resize events
  packages/api-v4/.changeset/pr-10262-added-1709742032135.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-10262-changed-1709742412767.md
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.style.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseStatusDisplay.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseStatusDisplay.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/features/Events/constants.ts
  packages/manager/src/features/Events/eventMessageGenerator.ts
  packages/manager/src/features/Events/eventMessageGenerator_CMR.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
  packages/manager/src/features/components/PlansPanel/PlanContainer.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
Labels: DBaaS, Approved

#10300 upcoming: [M3-7871] - Placement Groups in alpha - type updates
  packages/api-v4/src/placement-groups/types.ts
  packages/manager/.changeset/pr-10300-upcoming-features-1711040772223.md
  packages/manager/src/__data__/linodes.ts
  packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.test.tsx
  packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx
  packages/manager/src/factories/linodes.ts
  packages/manager/src/factories/placementGroups.ts
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsAffinityTypeSelect.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.test.tsx
  packages/manager/src/features/PlacementGroups/utils.test.ts
  packages/manager/src/features/PlacementGroups/utils.ts
  packages/manager/src/hooks/usePlacementGroupsData.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/placementGroups.ts
Labels: Approved, Placement Groups

#10299 refactor: [M3-7893] – Post-GA VPC cleanup
  packages/manager/.changeset/pr-10299-tech-stories-1710882340931.md
  packages/manager/src/GoTo.tsx
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AttachVLAN.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodePanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DeleteLinodeDialog.tsx
  packages/manager/src/features/Linodes/PowerActionsDialogOrDrawer.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/features/VPCs/index.tsx
  packages/manager/src/hooks/useVPCConfigInterface.ts
  packages/manager/src/queries/vpcs.ts
Labels: Approved, VPC

#10304 upcoming: [M3-7431] - Add placement group to checkout summary
  packages/manager/.changeset/pr-10304-upcoming-features-1711050408019.md
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Labels: Approved, Placement Groups

#10303 fix: [M3-7881] - Restore loading state to Users & Grants table
  packages/manager/.changeset/pr-10303-fixed-1710976860713.md
  packages/manager/src/features/Users/UsersLanding.tsx
  packages/manager/src/features/Users/UsersLandingTableBody.tsx
Labels: Bug, Approved, Parent / Child Account

#10305 fix: [M3-7909] - Hide the Child Account Access table header for parent users without `child_account_access` grant
  packages/manager/.changeset/pr-10305-upcoming-features-1711059101461.md
  packages/manager/src/features/Users/UsersLanding.tsx
Labels: Approved, Parent / Child Account

#10297 upcoming: [M3-7878] - Linode Create UI Refactor - Part 3 - Details Section
  packages/manager/.changeset/pr-10297-upcoming-features-1711046598676.md
  packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Details/PlacementGroupPanel.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Details/PlacementGroupPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Plan.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Distributions.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Distributions.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
  packages/manager/src/utilities/testHelpers.tsx
Labels: Approved, Linode Create Refactor

#10257 upcoming: [M3-7613] - Grants and Permissions for Placement Groups
  packages/manager/.changeset/pr-10257-upcoming-features-1710177497998.md
  packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
  packages/manager/src/components/Breadcrumb/Crumbs.tsx
  packages/manager/src/components/Breadcrumb/FinalCrumb.tsx
  packages/manager/src/components/Drawer.tsx
  packages/manager/src/components/EditableText/EditableText.tsx
  packages/manager/src/components/LandingHeader/LandingHeader.tsx
  packages/manager/src/features/Account/constants.ts
  packages/manager/src/features/PlacementGroups/PlacementGroupsAffinityEnforcementRadioGroup.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsAffinityTypeSelect.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodesTableRow.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLandingEmptyState.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsUnassignModal.tsx
  packages/manager/src/features/PlacementGroups/types.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Placement Groups

#10306 refactor: [M3-7895] – Remove VPC feature flag
  packages/manager/.changeset/pr-10306-tech-stories-1711123927073.md
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.test.tsx
Labels: Approved, VPC

#10275 fix: [M3-7862] - Fix display of TagsPanel in read-only entities
  packages/manager/src/components/TagCell/AddTag.tsx
  packages/manager/src/components/TagCell/TagDrawer.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.tsx
  packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/Linodes/LinodesLanding/CardView.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
Labels: Approved

#10308 upcoming: [M3-7879] - Linode Create Refactor - Part 4 - Access
  packages/manager/.changeset/pr-10308-upcoming-features-1711132212593.md
  packages/manager/src/features/Linodes/LinodeCreatev2/Access.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Access.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
  packages/manager/src/foundations/themes/light.ts
Labels: Add'tl Approval Needed, Linode Create Refactor

#10283 fix: [M3-6606] - Add spacing between copy and Linode Rebuild button.
  packages/manager/.changeset/pr-10283-fixed-1710431540230.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.styles.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
Labels: Bug, Approved

#10311 change: [M3-7922] - Clear ACLB configuration certificates if `http` or `tcp` protocol is selected
  packages/manager/.changeset/pr-10311-changed-1711378782884.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-configurations.spec.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationForm.tsx
  packages/validation/.changeset/pr-10311-changed-1711379618292.md
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, ACLB

#10296 test: [M3-7508] - Add tests to check Parent and Child Close Account flows
  packages/manager/cypress/e2e/core/account/account-cancellation.spec.ts
Labels: Approved, Missing Changeset, Parent / Child Account

#10312 upcoming: [M3-7903] - Placement Groups: Edit Drawer & Delete Modal UI Updates
  packages/manager/.changeset/pr-10312-upcoming-features-1711384895230.md
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/components/Drawer.tsx
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
  packages/manager/src/features/PlacementGroups/types.ts
Labels: Approved, Placement Groups

#10315 upcoming: [M3-7925] - Linode Create Refactor - Add Firewall - Part 5
  packages/manager/.changeset/pr-10315-upcoming-features-1711410039390.md
  packages/manager/src/features/Linodes/LinodeCreatev2/Firewall.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Firewall.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
Labels: Approved, Linode Create Refactor

#10314 upcoming: [M3-7840] - Placement Groups Query Key Factory
  packages/manager/.changeset/pr-10314-upcoming-features-1711460549811.md
  packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.test.tsx
  packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx
  packages/manager/src/queries/placementGroups.ts
Labels: Placement Groups

#10313 feat: [M3-7888] - Revoke proxy PAT when switching accounts
  packages/manager/.changeset/pr-10313-upcoming-features-1711398916591.md
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.tsx
  packages/manager/src/features/Account/utils.ts
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/hooks/usePendingRevocationToken.test.ts
  packages/manager/src/hooks/usePendingRevocationToken.ts
Labels: Approved, Parent / Child Account

#10319 upcoming: [M3-7927] - Linode Create Refactor - Part 6 - Add-ons
  packages/api-v4/.changeset/pr-10319-changed-1711487054721.md
  packages/api-v4/.changeset/pr-10319-changed-1711487087221.md
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-10319-upcoming-features-1711487110394.md
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Addons.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Addons.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Backups.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Backups.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/PrivateIP.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/PrivateIP.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/utilities.test.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Summary.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Distributions.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
  packages/validation/.changeset/pr-10319-changed-1711487139814.md
  packages/validation/src/linodes.schema.ts
Labels: Approved, Linode Create Refactor

#10137 feat: [M3-7366] - Improved Primary Navigation UX
  packages/manager/.changeset/pr-10137-tech-stories-1707328190628.md
  packages/manager/.storybook/manager.ts
  packages/manager/public/fonts/fonts.css
  packages/manager/src/MainContent.tsx
  packages/manager/src/assets/logo/akamai-logo-color.svg
  packages/manager/src/assets/logo/akamai-logo.svg
  packages/manager/src/components/BetaChip/BetaChip.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/PrimaryNav/SideMenu.tsx
Labels: UX/UI, Ready for Review, Needs extra approvals

#10324 fix: [UIE-7491] - Hide DBaaS resize tab behind feature flag
  packages/manager/.changeset/pr-10324-fixed-1711637470278.md
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
Labels: DBaaS, Approved

#10320 fix: [M3-7605] - Wrong status indicator when provisioning a LKE
  packages/manager/.changeset/pr-10320-fixed-1711553963315.md
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.styles.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
Labels: Bug, LKE

#10282 upcoming: [M3-7536] - Disable fetching buckets with clusters when ObjMultiClusterEnabled flag is enabled.
  packages/manager/.changeset/pr-10282-upcoming-features-1710422378958.md
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/TransferDisplay/utils.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransfer.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/queries/objectStorage.ts
  packages/manager/src/utilities/types/typesHelpers.test.ts
  packages/manager/src/utilities/types/typesHelpers.ts
  packages/manager/src/utilities/typesHelpers.ts
Labels: Approved, OBJ Multi-Cluster

#10332 fix: `README.md` Logo
  README.md
Labels: Approved, Documentation

#10333 change: [M3-7873] - Use Chip for notification badge
  packages/manager/.changeset/pr-10333-changed-1711728610850.md
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
Labels: Approved

#10317 upcoming: [M3-7898] - Support ticket severity
  packages/api-v4/.changeset/pr-10317-added-1711481937702.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/support/types.ts
  packages/manager/.changeset/pr-10317-upcoming-features-1711481971547.md
  packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts
  packages/manager/cypress/support/intercepts/support.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/factories/support.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Support/ExpandableTicketPanel.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SeverityChip.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.test.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TicketStatus.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
  packages/manager/src/features/Support/SupportTickets/TicketList.tsx
  packages/manager/src/features/Support/SupportTickets/TicketRow.tsx
  packages/manager/src/features/Support/SupportTickets/constants.tsx
  packages/manager/src/features/Support/SupportTickets/ticketUtils.ts
  packages/manager/src/features/Support/TicketDetailText.tsx
  packages/manager/src/foundations/themes/dark.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: UX/UI, @linode/api-v4, Approved
