Repository linode/manager, pull requests merged in 2024-06, with the labels that each got.

#10500 feat: [OCA-1345] - June 10 2024 Marketplace Release
  packages/manager/.changeset/pr-10500-added-1716322924328.md
  packages/manager/public/assets/apachekafka.svg
  packages/manager/public/assets/couchbase.svg
  packages/manager/public/assets/white/apachekafka.svg
  packages/manager/public/assets/white/couchbase.svg
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/manager/src/features/OneClickApps/oneClickAppsv2.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Marketplace, Approved

#10529 test: [M3-7784] - Cypress integration tests for Placement Group update label flow
  packages/manager/.changeset/pr-10529-tests-1717072137790.md
  packages/manager/cypress/e2e/core/placementGroups/update-placement-group-label.spec.ts
  packages/manager/cypress/support/intercepts/placement-groups.ts
Labels: Testing, Approved, Placement Groups

#10520 upcoming: [M3-7874] - Linode Create Refactor - Marketplace App Sections
  packages/manager/.changeset/pr-10520-upcoming-features-1717077696131.md
  packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/containers/withMarketplaceApps.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppSection.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppSection.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppSelect.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppsList.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/Marketplace.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/UserDefinedFields/UserDefinedFields.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/UserDefinedFields/UserDefinedFields.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
  packages/manager/src/features/Linodes/LinodesCreate/utilities.test.ts
  packages/manager/src/features/Linodes/LinodesCreate/utilities.tsx
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/manager/src/features/OneClickApps/oneClickAppsv2.ts
  packages/manager/src/features/OneClickApps/types.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
  packages/manager/src/queries/stackscripts.ts
Labels: Marketplace, Approved, Linode Create Refactor

#10535 upcoming: [M3-8083] - Linode Create v2 - Disk Encryption
  packages/manager/.changeset/pr-10535-upcoming-features-1717175664387.md
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/DiskEncryption/DiskEncryption.test.tsx
  packages/manager/src/components/DiskEncryption/DiskEncryption.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Access.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Access.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Backups.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Backups.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Summary.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Summary.tsx
Labels: Linode Create Refactor, Linode Disk Encryption (LDE)

#10521 upcoming: [M3-8139, M3-8140, M3-8141] – Add warning notices re: non-encryption when creating Images & enabling Backups
  packages/manager/.changeset/pr-10521-tests-1717099871186.md
  packages/manager/.changeset/pr-10521-upcoming-features-1717099430648.md
  packages/manager/cypress/e2e/core/images/create-image.spec.ts
  packages/manager/src/components/DiskEncryption/constants.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateImageFromDiskDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateImageFromDiskDialog.tsx
Labels: Linode Disk Encryption (LDE)

#10534 fix: [M3-7718] - Stale assigned Firewall data displaying on Linode and NodeBalancer details pages
  packages/manager/.changeset/pr-10534-fixed-1717169773875.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallDialog.tsx
Labels: Approved

#10541 upcoming: [M3-8014] - Update APIv4 and Validation packages based on Image Service spec
  packages/api-v4/.changeset/pr-10541-upcoming-features-1717446459710.md
  packages/api-v4/src/images/images.ts
  packages/api-v4/src/images/types.ts
  packages/manager/.changeset/pr-10541-changed-1717446372854.md
  packages/manager/src/factories/images.ts
  packages/validation/.changeset/pr-10541-added-1717446497849.md
  packages/validation/src/images.schema.ts
Labels: @linode/api-v4, @linode/validation, Images

#10452 refactor: [M3-8071] - Rename Edge Regions to Distributed Regions
  packages/api-v4/src/regions/types.ts
  packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
  packages/manager/src/__data__/regionsData.ts
  packages/manager/src/assets/icons/entityIcons/distributed-region.svg
  packages/manager/src/components/RegionSelect/RegionOption.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.styles.ts
  packages/manager/src/components/RegionSelect/RegionSelect.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Events/factories/backup.tsx
  packages/manager/src/features/Events/factories/lke.tsx
  packages/manager/src/features/Events/factories/reserved.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Addons.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Addons.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Backups.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Backups.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/PrivateIP.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/PrivateIP.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/utilities.test.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/utilities.ts
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenu.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenu.tsx
  packages/manager/src/features/Linodes/MigrateLinode/CautionNotice.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/components/PlansPanel/DistributedRegionPlanTable.tsx
  packages/manager/src/features/components/PlansPanel/EdgePlanTable.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Gecko Beta

#10537 upcoming: [M3-8019] – Add Encrypted/Not Encrypted status to Linode Detail summary header
  packages/api-v4/.changeset/pr-10537-changed-1717182754934.md
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-10537-upcoming-features-1717182633416.md
  packages/manager/src/__data__/linodes.ts
  packages/manager/src/assets/icons/lock.svg
  packages/manager/src/assets/icons/unlock.svg
  packages/manager/src/components/DiskEncryption/constants.tsx
  packages/manager/src/factories/linodes.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/ListView.tsx
Labels: Approved, Linode Disk Encryption (LDE)

#10538 test: [M3-8108, M3-8113] - Improve security of Linodes created by tests
  packages/manager/.changeset/pr-10538-tests-1717187190983.md
  packages/manager/cypress/e2e/core/account/service-transfer.spec.ts
  packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/rescue-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/switch-linode-state.spec.ts
  packages/manager/cypress/e2e/core/linodes/update-linode-labels.spec.ts
  packages/manager/cypress/e2e/core/longview/longview.spec.ts
  packages/manager/cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts
  packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/cypress/e2e/region/images/create-machine-image-from-linode.spec.ts
  packages/manager/cypress/e2e/region/linodes/delete-linode.spec.ts
  packages/manager/cypress/e2e/region/linodes/update-linode.spec.ts
  packages/manager/cypress/support/api/firewalls.ts
  packages/manager/cypress/support/api/linodes.ts
  packages/manager/cypress/support/constants/cypress.ts
  packages/manager/cypress/support/util/linodes.ts
Labels: Approved

#10536 change: [M3-8159] - Modify limited availability banner display logic
  packages/manager/.changeset/pr-10536-changed-1717183226858.md
  packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/components/PlansPanel/PlanInformation.test.tsx
  packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
  packages/manager/src/features/components/PlansPanel/utils.ts
Labels: Approved, DC Get Well

#10540 change: [M3-6541] - eslint: consistent-type-imports
  packages/manager/.changeset/pr-10540-tech-stories-1717433580405.md
  packages/manager/.eslintrc.cjs
Labels: Approved

#10524 refactor: [M3-8183] - Clean up loading components
  packages/manager/.changeset/pr-10524-tech-stories-1716999765184.md
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/components/CircleProgress/CircleProgress.test.tsx
  packages/manager/src/components/CircleProgress/CircleProgress.tsx
  packages/manager/src/components/CircularProgress.stories.tsx
  packages/manager/src/components/CircularProgress.tsx
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx
  packages/manager/src/components/EnhancedSelect/components/LoadingIndicator.tsx
  packages/manager/src/components/LandingLoading/LandingLoading.stories.tsx
  packages/manager/src/components/LandingLoading/LandingLoading.test.tsx
  packages/manager/src/components/LandingLoading/LandingLoading.tsx
  packages/manager/src/components/LinkButton.tsx
  packages/manager/src/components/MenuItem/MenuItem.tsx
  packages/manager/src/components/TableSortCell/TableSortCell.tsx
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplay.tsx
  packages/manager/src/features/Account/SwitchAccounts/ChildAccountList.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentMethods.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Backups/BackupSelect.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppsList.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectAppPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/StatsPanel.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerConfigurations.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
  packages/manager/src/features/Managed/SSHAccess/LinodePubKey.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
  packages/manager/src/features/NotificationCenter/NotificationSection.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
  packages/manager/src/features/Profile/Referrals/Referrals.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/PricePanel.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/foundations/themes/light.ts
Labels: Clean Up

#10278 test: Improve unit test stability when running locally
  packages/api-v4/package.json
  packages/manager/.changeset/pr-10278-tests-1710347078555.md
  packages/manager/package.json
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CreateCertificateDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/EditCertificateDrawer.test.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/EditAPITokenDrawer.test.tsx
  packages/manager/src/utilities/storage.test.ts
  yarn.lock
Labels: Approved, Ready for Review

#10548 test: [M3-8013] - Upgrade to Cypress v13.11.0
  packages/manager/.changeset/pr-10548-tech-stories-1717618206213.md
  packages/manager/Dockerfile
  packages/manager/package.json
  yarn.lock
Labels: Approved

#10512 feat: [M3-7919] Add Fonoa tax id event notification on invalidation
  packages/api-v4/.changeset/pr-10512-added-1717103206247.md
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-10512-added-1716563502479.md
  packages/manager/cypress/e2e/core/billing/billing-contact.spec.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Account/utils.ts
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/Billing/constants.ts
  packages/manager/src/features/Events/constants.ts
  packages/manager/src/features/Events/eventMessageGenerator.ts
  packages/manager/src/features/Events/factories/index.ts
  packages/manager/src/features/Events/factories/tax.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
  packages/manager/src/features/PlacementGroups/utils.ts
  packages/manager/src/queries/account/account.ts
Labels: Approved

#10555 upcoming: [M3-8218] - Obj fix for crashing accesskey page when relevant customer tags are not added.
  packages/manager/.changeset/pr-10555-upcoming-features-1717778847157.md
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
Labels: Approved

#10560 fix: [M3-8162] - Inability to create access keys due to incorrectly running `/types` query
  packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.tsx
Labels: Bug, Approved

#10551 refactor: [M3-8203] - Refactor Region Select
  packages/api-v4/src/regions/types.ts
  packages/manager/src/components/RegionSelect/RegionMultiSelect.stories.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.test.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
  packages/manager/src/components/RegionSelect/RegionOption.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.stories.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/CloudPulse/shared/RegionSelect.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Images/ImageUpload.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/AccessKeyRegions.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/SelectedRegionsList.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.tsx
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/manager/src/utilities/formatRegion.ts
Labels: Ready for Review

#10559 refactor: [M3-8127] - Query Key Factory for Domains
  packages/manager/.changeset/pr-10559-tech-stories-1718119071574.md
  packages/manager/src/queries/domains.ts
Labels: React Query

#10487 refactor: [M3-8157] - Clean up images drawer
  packages/api-v4/.changeset/pr-10514-added-1716499303668.md
  packages/api-v4/src/images/images.ts
  packages/api-v4/src/images/types.ts
  packages/manager/.changeset/pr-10514-tech-stories-1716499244555.md
  packages/manager/src/features/Images/EditImageDrawer.test.tsx
  packages/manager/src/features/Images/EditImageDrawer.tsx
  packages/manager/src/features/Images/ImageRow.tsx
  packages/manager/src/features/Images/ImagesActionMenu.tsx
  packages/manager/src/features/Images/ImagesDrawer.test.tsx
  packages/manager/src/features/Images/ImagesDrawer.tsx
  packages/manager/src/features/Images/ImagesLanding.tsx
  packages/manager/src/features/Images/RebuildImageDrawer.test.tsx
  packages/manager/src/features/Images/RebuildImageDrawer.tsx
  packages/manager/src/features/Images/utils.test.tsx
  packages/manager/src/features/Images/utils.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetail.tsx
  packages/manager/src/queries/images.ts
Labels: Approved, Images

#10561 test: Upgrade Vitest and related dependencies to v1.6.0
  packages/api-v4/package.json
  packages/manager/.changeset/pr-10561-tech-stories-1718047853944.md
  packages/manager/package.json
  yarn.lock
Labels: Approved

#10546 upcoming: [M3-8031] – Add Disk Encryption info banner to Kubernetes landing page
  packages/manager/.changeset/pr-10546-tests-1717604850412.md
  packages/manager/.changeset/pr-10546-upcoming-features-1717603180090.md
  packages/manager/cypress/e2e/core/kubernetes/lke-landing-page.spec.ts
  packages/manager/src/components/DiskEncryption/constants.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
Labels: Approved, Linode Disk Encryption (LDE)

#10552 test: [M3-7769] - Add Placement Groups Navigation Integration Tests
  packages/manager/.changeset/pr-10552-tests-1717702940797.md
  packages/manager/cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts
Labels: Testing, Approved, Placement Groups

#10567 hotfix: Fix Core Plan table display
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.test.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
Labels: Hotfix

#10475 test: [M3-7667] - (Proof of Concept) Add tagging capability for Cypress tests
  docs/development-guide/08-testing.md
  packages/manager/cypress.config.ts
  packages/manager/cypress/e2e/core/account/service-transfer.spec.ts
  packages/manager/cypress/e2e/core/account/third-party-access-tokens.spec.ts
  packages/manager/cypress/e2e/core/billing/smoke-billing-activity.spec.ts
  packages/manager/cypress/e2e/core/domains/smoke-clone-domain.spec.ts
  packages/manager/cypress/e2e/core/domains/smoke-delete-domain.spec.ts
  packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/delete-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
  packages/manager/cypress/e2e/core/images/create-image.spec.ts
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/rescue-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/switch-linode-state.spec.ts
  packages/manager/cypress/e2e/core/linodes/update-linode-labels.spec.ts
  packages/manager/cypress/e2e/core/longview/longview.spec.ts
  packages/manager/cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts
  packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/clone-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/delete-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/resize-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/update-volume.spec.ts
  packages/manager/cypress/e2e/region/images/create-machine-image-from-linode.spec.ts
  packages/manager/cypress/e2e/region/images/update-delete-machine-image.spec.ts
  packages/manager/cypress/e2e/region/linodes/delete-linode.spec.ts
  packages/manager/cypress/e2e/region/linodes/update-linode.spec.ts
  packages/manager/cypress/support/e2e.ts
  packages/manager/cypress/support/index.d.ts
  packages/manager/cypress/support/plugins/test-tagging-info.ts
  packages/manager/cypress/support/setup/defer-command.ts
  packages/manager/cypress/support/setup/test-tagging.ts
  packages/manager/cypress/support/util/arrays.ts
  packages/manager/cypress/support/util/cleanup.ts
  packages/manager/cypress/support/util/tag.ts
Labels: Proof of Concept, Approved

#10544 feat: [M3-8017] - Support Linodes in Distributed Compute Regions on Image Create
  packages/manager/.changeset/pr-10544-added-1717530161965.md
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.test.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
Labels: Approved, Images

#10571 Release v1.121.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.test.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
Labels: Hotfix

#10556 refactor: [M3-8216] - NodeBalancer Query Key Factory
  packages/manager/.changeset/pr-10556-tech-stories-1717782967942.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallDialog.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
  packages/manager/src/hooks/useEventHandlers.ts
  packages/manager/src/queries/nodebalancers.ts
Labels: React Query, Approved, NodeBalancers

#10477 test: [M3-7954] - Cypress integration test to add SSH key via Profile page
  packages/manager/.changeset/pr-10477-tests-1717448262964.md
  packages/manager/cypress/e2e/core/account/ssh-keys.spec.ts
  packages/manager/cypress/support/constants/account.ts
  packages/manager/cypress/support/intercepts/profile.ts
Labels: Approved

#10572 test: Improve disk encryption banner test in CI
  packages/manager/cypress/e2e/core/kubernetes/lke-landing-page.spec.ts
Labels: Approved, Ready for Review

#10574 test: Improve stability of StackScript pagination test
  packages/manager/.changeset/pr-10574-tests-1718222529272.md
  packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts
Labels: Approved

#10568 refactor: [M3-8232] - Query Key Factory for Firewalls
  packages/manager/.changeset/pr-10568-tech-stories-1718139515455.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallDialog.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
  packages/manager/src/queries/firewalls.ts
  packages/manager/src/queries/linodes/events.ts
  packages/manager/src/queries/linodes/firewalls.ts
  packages/manager/src/queries/nodebalancers.ts
Labels: React Query, Approved

#10564 upcoming: [M3-8081] - Linode Create v2 - Handle side-effects when changing the Region
  packages/manager/.changeset/pr-10564-upcoming-features-1718118654107.md
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/components/VLANSelect.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Security.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Security.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts
Labels: Linode Create Refactor

#10566 refactor: [M3-8101] - Use `network-transfer/prices` endpoint for transfer overage pricing
  packages/api-v4/.changeset/pr-10566-added-1718123757956.md
  packages/api-v4/src/index.ts
  packages/api-v4/src/network-transfer/index.ts
  packages/api-v4/src/network-transfer/prices.ts
  packages/manager/.changeset/pr-10566-changed-1718123674587.md
  packages/manager/src/factories/types.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.tsx
  packages/manager/src/queries/networkTransfer.ts
  packages/manager/src/utilities/pricing/constants.ts
  packages/manager/src/utilities/pricing/dynamicPricing.ts
Labels: @linode/api-v4, Approved, DC-Specific Pricing

#10554 change: [M3-8153] - Rename to Choose an OS in Linode Create flow
  packages/manager/.changeset/pr-10554-changed-1718122854647.md
  packages/manager/cypress/support/ui/constants.ts
  packages/manager/cypress/support/ui/pages/linode-create-page.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Distributions.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Distributions.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Labels: Wait to Merge, Approved

#10573 change: [M3-8242] - Update TypeScript to latest
  package.json
  packages/manager/.changeset/pr-10573-tech-stories-1718213403351.md
  packages/manager/package.json
  packages/manager/src/components/OrderBy.tsx
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
  packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx
  packages/manager/src/features/Linodes/LinodesLanding/TableWrapper.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/EditRoutes/RouteAccordion.tsx
  packages/manager/src/store/store.helpers.test.ts
  packages/manager/src/store/store.helpers.tmp.ts
  packages/manager/src/store/store.helpers.ts
  packages/manager/src/store/types.ts
  packages/manager/tsconfig.json
  yarn.lock
Labels: Dependencies, Ready for Review

#10549 upcoming: [M3-8020] – Add "Disk Encryption" section to Linode Rebuild modal
  packages/manager/.changeset/pr-10549-upcoming-features-1718120005131.md
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/DiskEncryption/constants.tsx
  packages/manager/src/features/Events/factories/tax.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/LinodeRebuildDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Linode Disk Encryption (LDE)

#10576 upcoming: [M3-8145] – Update LDE copy in Linode Create flow when Distributed region is selected
  packages/manager/.changeset/pr-10576-upcoming-features-1718227220058.md
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/DiskEncryption/constants.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Security.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Security.tsx
Labels: Approved, Linode Disk Encryption (LDE)

#10585 test: Mock profile to fix GHA test failure
  packages/manager/.changeset/pr-10585-tests-1718380830458.md
  packages/manager/cypress/e2e/core/account/security-questions.spec.ts
Labels: Approved

#10578 upcoming: [M3-8245] – Update "Add Node Pools" description in LKE Create flow
  packages/manager/.changeset/pr-10578-upcoming-features-1718295945732.md
  packages/manager/src/features/Kubernetes/ClusterList/constants.ts
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
Labels: Approved, Linode Disk Encryption (LDE)

#10582 change: [M3-7646] - Link Cloud Manager README to new documentation pages
  README.md
  packages/manager/.changeset/pr-10582-changed-1718310753730.md
Labels: Approved, Documentation

#10581 test: Resolve Linode/Firewall E2E flake by using alternative security method
  packages/manager/.changeset/pr-10581-tests-1718308219716.md
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/linodes/rescue-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
Labels: Ready for Review

#10586 upcoming: [M3-8265] - Linode Create v2 - Add Marketplace Searching / Filtering
  packages/manager/.changeset/pr-10586-upcoming-features-1718384912084.md
  packages/manager/src/factories/stackscripts.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppSelect.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppsList.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/utilities.test.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/utilities.ts
Labels: Marketplace, Linode Create Refactor

#10587 fix: [M3-7646] CONTRIBUTING commit type list markup
  docs/CONTRIBUTING.md
  packages/manager/.changeset/pr-10587-fixed-1718643059797.md
Labels: Approved, Documentation

#10588 fix: React Query Events `seen` and other optimizations
  packages/manager/.changeset/pr-10588-fixed-1718731923572.md
  packages/manager/src/features/Events/EventsLanding.tsx
  packages/manager/src/features/Events/constants.ts
  packages/manager/src/features/NotificationCenter/EventsV2.test.tsx
  packages/manager/src/features/NotificationCenter/EventsV2.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEventV2.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useEventNotificationsV2.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenuV2.tsx
  packages/manager/src/queries/events/event.helpers.test.ts
  packages/manager/src/queries/events/event.helpers.ts
  packages/manager/src/queries/events/events.ts
Labels: React Query

#10590 fix: [M3-8269] - Accessibility: Add tabindex to TextTooltip
  packages/manager/.changeset/pr-10590-fixed-1718722141069.md
  packages/manager/src/components/TextTooltip/TextTooltip.tsx
Labels: Accessibility, Approved

#10505 change: [M3-7383] - Replace hardcoded prices for LKE HA with data from `lke/types` API endpoint
  packages/api-v4/.changeset/pr-10505-added-1716400052332.md
  packages/api-v4/src/kubernetes/kubernetes.ts
  packages/manager/.changeset/pr-10505-changed-1716400104404.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/factories/types.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.test.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeClusterSpecs.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeClusterDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/index.tsx
  packages/manager/src/features/Kubernetes/index.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/kubernetes.ts
  packages/manager/src/utilities/formatRegion.ts
  packages/manager/src/utilities/pricing/constants.ts
  packages/manager/src/utilities/pricing/dynamicPricing.test.ts
  packages/manager/src/utilities/pricing/kubernetes.test.tsx
  packages/manager/src/utilities/pricing/kubernetes.ts
Labels: @linode/api-v4, Approved, DC-Specific Pricing

#10591 test: [M3-7330] - Attempt to fix hanging unit tests
  packages/manager/.changeset/pr-10591-tests-1718746383365.md
  packages/manager/src/features/Events/utils.test.tsx
  packages/manager/src/hooks/useOrder.test.tsx
  packages/manager/src/index.tsx
  packages/manager/src/queries/base.ts
  packages/manager/vite.config.ts
Labels: Ready for Review

#10596 test: Unit test coverage - HostNameTableCell
  packages/manager/.changeset/pr-10596-tests-1718806691101.md
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx
Labels: OBJ Multi-Cluster

#10583 fix: [M3-8193] - Check account access for disabling add tags button
  packages/manager/.changeset/pr-10583-fixed-1718375225734.md
  packages/manager/src/components/TagCell/TagCell.test.tsx
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailFooter.tsx
Labels: Bug, Approved

#10592 upcoming: [M3-8270] - Add Distributed Icon to ImageSelects for distributed compatible images
  packages/manager/.changeset/pr-10592-upcoming-features-1718725835055.md
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/ImageSelect/ImageSelect.test.tsx
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/components/ImageSelectv2/ImageOptionv2.test.tsx
  packages/manager/src/components/ImageSelectv2/ImageOptionv2.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Ready for Review, Image Service Gen2

#10545 upcoming: [M3-8015] - Update Images Landing table
  packages/api-v4/src/images/types.ts
  packages/manager/.changeset/pr-10545-upcoming-features-1718402597165.md
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.utils.ts
  packages/manager/src/features/Images/ImagesCreate/ImageUploadCLIDialog.test.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUploadCLIDialog.tsx
  packages/manager/src/features/Images/ImagesLanding/EditImageDrawer.test.tsx
  packages/manager/src/features/Images/ImagesLanding/EditImageDrawer.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRow.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRow.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesActionMenu.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLandingEmptyState.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLandingEmptyStateData.ts
  packages/manager/src/features/Images/ImagesLanding/RebuildImageDrawer.test.tsx
  packages/manager/src/features/Images/ImagesLanding/RebuildImageDrawer.tsx
  packages/manager/src/features/Images/ImagesLanding/RegionsList.test.tsx
  packages/manager/src/features/Images/ImagesLanding/RegionsList.tsx
  packages/manager/src/features/Images/index.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Ready for Review, Images, Image Service Gen2

#10597 fix: [M3-8274] - Fix parsing issue causing in Kubernetes Version field
  packages/manager/.changeset/pr-10597-fixed-1718893685492.md
  packages/manager/src/features/Kubernetes/kubeUtils.test.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/utilities/sort-by.test.ts
  packages/manager/src/utilities/sort-by.ts
Labels: Add'tl Approval Needed

#10602 test: Update Object Storage tests to mock account `capabilities` as needed
  packages/manager/.changeset/pr-10602-tests-1718985699307.md
  packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/access-keys.smoke.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.smoke.spec.ts
Labels: e2e

#10603 fix: Object Storage Object URLs
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/utilities.ts
Labels: Hotfix, OBJ Multi-Cluster

#10605 Release v1.121.2 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/utilities.ts
Labels: Release, Hotfix

#10606 added: [M3-8008, M3-8277] - Update invoices for JP and EU
  packages/manager/CHANGELOG.md
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
Labels: Add'tl Approval Needed, Ready for Review

#10584 fix: [M3-8264] - Conditional invocation of useEventInfiniteQuery hook
  packages/manager/.changeset/pr-10584-fixed-1718376872460.md
  packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
Labels: Bug

#10594 change: [M3-8022] - Update Rebuild Linode drawer
  packages/manager/.changeset/pr-10594-changed-1718748465150.md
  packages/manager/src/features/Images/ImagesLanding/ImageRow.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRow.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Images/ImagesLanding/RebuildImageDrawer.test.tsx
  packages/manager/src/features/Images/ImagesLanding/RebuildImageDrawer.tsx
Labels: Approved, Image Service Gen2

#10589 upcoming: [DI-19062] - Dashboard Select component in cloudpulse global filters view
  packages/api-v4/.changeset/pr-10589-upcoming-features-1718971604339.md
  packages/api-v4/src/cloudpulse/dashboards.ts
  packages/api-v4/src/cloudpulse/index.ts
  packages/api-v4/src/cloudpulse/types.ts
  packages/api-v4/src/index.ts
  packages/manager/.changeset/pr-10589-upcoming-features-1718716331830.md
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/dashboards.ts
Labels: CloudPulse

#10609 test: Fix Cypress failure by accounting for OBJ Multicluster in upload test
  packages/manager/.changeset/pr-10609-tests-1719255666019.md
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
Labels: Testing, Approved, Ready for Review

#10607 upcoming: [M3-8279] - Conditionally disable regions based on the selected image
  packages/manager/.changeset/pr-10607-upcoming-features-1719247291579.md
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.test.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.utils.test.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.utils.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Image Service Gen2

#10557 refactor: [M3-8228] - Refactor `SupportTicketDialog` to use React Hook Form
  packages/manager/.changeset/pr-10557-tech-stories-1718728411161.md
  packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts
  packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.tsx
  packages/manager/src/components/HighlightedMarkdown/highlight.d.ts
  packages/manager/src/features/Support/SupportTicketDetail/SeverityChip.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketProductSelectionFields.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketSMTPFields.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
  packages/manager/src/features/Support/SupportTickets/TicketList.tsx
  packages/manager/src/features/Support/SupportTickets/TicketRow.tsx
  packages/manager/src/features/Support/SupportTickets/constants.tsx
  packages/manager/src/features/Support/SupportTickets/ticketUtils.test.ts
  packages/manager/src/features/Support/SupportTickets/ticketUtils.ts
  packages/validation/.changeset/pr-10557-added-1718728514265.md
  packages/validation/src/support.schema.ts
Labels: Ready for Review, Tech Debt

#10598 refactor: [M3-8275] - Query Key Factory for ACLB
  packages/manager/.changeset/pr-10598-tech-stories-1718897422896.md
  packages/manager/src/queries/aclb/certificates.ts
  packages/manager/src/queries/aclb/configurations.ts
  packages/manager/src/queries/aclb/loadbalancers.ts
  packages/manager/src/queries/aclb/queries.ts
  packages/manager/src/queries/aclb/routes.ts
  packages/manager/src/queries/aclb/serviceTargets.ts
Labels: React Query, Approved, ACLB

#10479 upcoming: [M3-7949] - Gecko GA Region Select
  packages/api-v4/src/cloudpulse/dashboards.ts
  packages/api-v4/src/cloudpulse/index.ts
  packages/api-v4/src/cloudpulse/types.ts
  packages/api-v4/src/index.ts
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-10479-upcoming-features-1718906242285.md
  packages/manager/src/components/RegionSelect/RegionOption.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/components/RegionSelect/TwoStepRegionSelect.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx
  packages/manager/src/hooks/useFlags.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/dashboards.ts
  packages/manager/src/queries/regions/regions.ts
  packages/manager/src/utilities/sort-by.test.ts
Labels: Approved, Gecko GA

#10621 test: Fix CI support ticket test failure by mocking clusters
  packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts
Labels: Add'tl Approval Needed

#10604 change: [M3-8199] - Auto-populate Image Label based on linode and disk names
  packages/manager/.changeset/pr-10604-changed-1719003322690.md
  packages/manager/cypress/e2e/core/images/create-image.spec.ts
  packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.test.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
Labels: Approved, Image Service Gen2

#10615 test: [M3-7320] - De-Parameterize Cypress Domain Record Create Tests
  packages/manager/.changeset/pr-10615-tests-1719412831217.md
  packages/manager/cypress/e2e/core/domains/smoke-create-domain-records.spec.ts
  packages/manager/cypress/support/api/domains.ts
  packages/manager/cypress/support/constants/domains.ts
Labels: e2e, Approved

#10614 change: [M3-8024] - Update Linode disk action menu
  packages/manager/.changeset/pr-10614-changed-1719356418613.md
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.test.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateImageFromDiskDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateImageFromDiskDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskActionMenu.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDisks.tsx
Labels: Approved, Image Service Gen2

#10622 test: [M3-7319] - De-Parameterize Cypress Deep Link Smoke Tests
  packages/manager/.changeset/pr-10622-tests-1719519067716.md
  packages/manager/cypress/e2e/core/general/smoke-deep-link.spec.ts
  packages/manager/cypress/support/ui/constants.ts
Labels: e2e
