Repository linode/manager, pull requests merged in 2024-10, with the labels that each got.

#10964 change: [M3-8468] - Improve action menu styling
  packages/manager/.changeset/pr-10964-changed-1726673831823.md
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/foundations/themes/dark.ts
Labels: Accessibility, Approved

#11030 fix: [UIE-8163] - DBaaS V2 Landing Page platform fix
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/queries/databases/databases.ts
Labels: DBaaS, Ready for Review, Hotfix

#10967 change: [M3-8607] - Change notification `tax_id_invalid` to `tax_id_verifying`
  packages/api-v4/.changeset/pr-10967-changed-1727612967612.md
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-10967-changed-1726862920341.md
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
Labels: Approved, Ready for Review

#11032 fix: Add Volume button on Cloud Manager Linode page causing browser to freeze
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx
Labels: Hotfix

#11034 fix: [M3-8685] - Users unable to update timezone
  packages/manager/CHANGELOG.md
  packages/manager/src/assets/timezones/timezones.ts
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
Labels: Bug

#11037 Release v1.129.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/assets/timezones/timezones.ts
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx
  packages/manager/src/queries/databases/databases.ts
Labels: Release, Hotfix

#11033 chore: [M3-8677] – Upgrade `upload-artifact` and `download-artifact` actions to `v4`
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  packages/manager/.changeset/pr-11033-tech-stories-1727816117048.md
Labels: Dependencies, Approved

#10950 feat: [M3-8180] - Notification Menu story
  packages/manager/.changeset/pr-10950-added-1727092343272.md
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.stories.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Storybook, Approved

#11016 test: [M3-8541, M3-8621] - Unit tests for CollapsibleTable and CollapsibleRow components
  packages/manager/.changeset/pr-11016-tests-1727686556299.md
  packages/manager/src/components/CollapsibleTable/CollapsibleRow.test.tsx
  packages/manager/src/components/CollapsibleTable/CollapsibleTable.stories.tsx
  packages/manager/src/components/CollapsibleTable/CollapsibleTable.test.tsx
Labels: Approved, Unit tests

#10994 test: [M3-8440] - Cypress tests for OBJ Gen 2 bucket access tab changes
  packages/manager/.changeset/pr-10994-tests-1727202548403.md
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-details-gen2.spec.ts
  packages/manager/cypress/support/intercepts/object-storage.ts
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
Labels: Testing, Approved, Object Storage Gen2

#11022 add: [M3-8630] - Add default root hostname for TXT records
  packages/manager/.changeset/pr-11022-added-1727879935382.md
  packages/manager/src/features/Domains/DomainRecordDrawer.test.tsx
  packages/manager/src/features/Domains/DomainRecordDrawer.tsx
  packages/manager/src/features/Domains/DomainRecords.tsx
Labels: Approved, Ready for Review

#11041 fix: [M3-8696] - Explicitly define 'key' prop for Autocomplete instead of spreading
  packages/manager/.changeset/pr-11041-fixed-1727966039153.md
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
Labels: Approved, Ready for Review

#10979 fix: [M3-8523] - Fix styling on Support Ticket Details page
  packages/manager/.changeset/pr-10979-fixed-1726843710952.md
  packages/manager/src/features/Support/ExpandableTicketPanel.tsx
Labels: Approved

#11046 change: [M3-6994] - Spell out "Configuration" on Linodes Configurations table
  packages/manager/.changeset/pr-11046-changed-1727990528328.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
Labels: Approved

#11036 fix: [UIE-8165] - DBaaS remove 512 GB plan selection
  packages/manager/.changeset/pr-11036-changed-1727881220211.md
  packages/manager/src/features/components/PlansPanel/constants.ts
  packages/manager/src/features/components/PlansPanel/utils.test.ts
  packages/manager/src/features/components/PlansPanel/utils.ts
Labels: DBaaS, Approved

#11019 change: [M3-8175] - Refactor KubeConfigDrawer to use CodeBlock and add Codeblock story
  packages/manager/.changeset/pr-11019-changed-1727727502564.md
  packages/manager/.changeset/pr-11019-tech-stories-1727727527842.md
  packages/manager/src/components/CodeBlock/CodeBlock.stories.tsx
  packages/manager/src/components/CodeBlock/CodeBlock.styles.ts
  packages/manager/src/components/CodeBlock/CodeBlock.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/CurlTabPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/IntegrationsTabPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/LinodeCLIPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/SDKTabPanel.tsx
Labels: Storybook

#11023 feat: [M3-7011] - Add firewalls to search result queries
  packages/api-v4/.changeset/pr-11023-changed-1727944517923.md
  packages/api-v4/src/firewalls/types.ts
  packages/manager/.changeset/pr-11023-added-1727785979860.md
  packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/src/__data__/firewalls.ts
  packages/manager/src/factories/firewalls.ts
  packages/manager/src/features/Firewalls/shared.ts
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/search.interfaces.ts
  packages/manager/src/features/Search/utils.test.ts
  packages/manager/src/features/Search/utils.ts
  packages/manager/src/features/Search/withStoreSearch.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/store/selectors/getSearchEntities.ts
Labels: Approved, Search

#10941 feat: [M3-6715] - Allow sorting by amount on billing activity table
  packages/manager/.changeset/pr-10941-added-1726492437722.md
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
Labels: Add'tl Approval Needed, Ready for Review

#11047 upcoming: [M3-8452, M3-8603] - Add Resource Links & Fix Test Flake
  packages/manager/.changeset/pr-11047-upcoming-features-1728307120334.md
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
Labels: Approved, Object Storage Gen2

#10891 test: [DI-20585] - Add ACLP Cypress Test Coverage for Linode Dashboard Widgets
  packages/manager/.changeset/pr-10891-tests-1726565438335.md
  packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-navigation.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/cypress/support/constants/widgets.ts
  packages/manager/cypress/support/intercepts/cloudpulse.ts
  packages/manager/cypress/support/ui/autocomplete.ts
  packages/manager/cypress/support/util/cloudpulse.ts
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/factories/dashboards.ts
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.test.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
  packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
Labels: Add'tl Approval Needed, e2e, CloudPulse

#10639 feat: [M3-7948] - Add Region filtering to Linodes landing table
  packages/api-v4/.changeset/pr-10639-removed-1727977150621.md
  packages/api-v4/src/linodes/types.ts
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-10639-upcoming-features-1721164284962.md
  packages/manager/cypress/e2e/core/images/create-image.spec.ts
  packages/manager/src/__data__/distributedRegionsData.ts
  packages/manager/src/__data__/regionsData.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Addons/Addons.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Addons/Backups.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Addons/PrivateIP.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.styles.ts
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/Linodes/LinodesLanding/RegionTypeFilter.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx
  packages/manager/src/features/Linodes/index.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/queries/linodes/stats.ts
  packages/manager/src/utilities/storage.ts
Labels: Approved, Gecko LA

#10982 change: [M3-8390] - Initialize Pendo on Cloud Manager
  packages/manager/.changeset/pr-10982-tech-stories-1726865548976.md
  packages/manager/.env.example
  packages/manager/package.json
  packages/manager/src/App.tsx
  packages/manager/src/constants.ts
  packages/manager/src/env.d.ts
  packages/manager/src/hooks/usePendo.ts
  packages/manager/src/hooks/useScript.ts
  yarn.lock
Labels: Approved, Analytics

#11050 change: [M3-7676] - Remove VPC Details dismissible warning banner
  packages/manager/.changeset/pr-11050-removed-1728374181106.md
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
Labels: Approved, VPC

#11053 upcoming: [DI-21351] - Fixed metrics api call issue
  packages/manager/.changeset/pr-11053-upcoming-features-1728319517379.md
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidgetRenderer.tsx
Labels: Approved, CloudPulse

#11002 test: [M3-8447] - Add cypress integration test for OBJ gen 2 Bucket Details Properties tab
  packages/manager/.changeset/pr-11002-tests-1727812216912.md
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-details-gen2.spec.ts
  packages/manager/cypress/support/util/object-storage-gen2.ts
  packages/validation/src/vpcs.schema.ts
Labels: Testing, Object Storage Gen2

#10937 change: [M3-8583] - Add support ticket mocks to MSW 2.0
  packages/manager/.changeset/pr-10937-tech-stories-1728079160083.md
  packages/manager/src/dev-tools/load.ts
  packages/manager/src/mocks/mockState.ts
  packages/manager/src/mocks/presets/baseline/crud.ts
  packages/manager/src/mocks/presets/crud/handlers/supportTickets.ts
  packages/manager/src/mocks/presets/crud/seeds/index.ts
  packages/manager/src/mocks/presets/crud/seeds/supportTickets.ts
  packages/manager/src/mocks/presets/crud/supportTickets.ts
  packages/manager/src/mocks/types.ts
Labels: Approved

#11048 feat: [UIE-8166] - DBaaS backup GA toggle and beta fixes
  packages/api-v4/.changeset/pr-11048-changed-1728076842800.md
  packages/api-v4/src/databases/databases.ts
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-11048-upcoming-features-1728076876251.md
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.style.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupsDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/index.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/legacy/DatabaseBackupActionMenu.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/legacy/DatabaseBackupTableBody.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/legacy/DatabaseBackupTableRow.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/legacy/DatabaseBackupsLegacy.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/legacy/RestoreLegacyFromBackupDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/queries/databases/databases.ts
Labels: DBaaS, Approved

#10753 upcoming: [APL-55] - Application platform for Linode Kubernetes
  packages/api-v4/src/kubernetes/kubernetes.ts
  packages/api-v4/src/kubernetes/types.ts
  packages/manager/src/components/Breadcrumb/Breadcrumb.test.tsx
  packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
  packages/manager/src/components/LandingHeader/LandingHeader.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.styles.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/APLSummaryPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/components/PlansPanel/constants.ts
  packages/manager/src/features/components/PlansPanel/types.ts
  packages/manager/src/features/components/PlansPanel/utils.ts
  packages/manager/src/queries/kubernetes.ts
  packages/manager/src/utilities/pricing/constants.ts
Labels: LKE

#11038 upcoming: [M3-8613] - Restrict Image Upload to regions with Object Storage
  packages/manager/.changeset/pr-11038-upcoming-features-1727969322447.md
  packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
Labels: Approved, Image Service Gen2

#10991 change: [M3-8415] - Hide SMTP warning for Linodes and accounts that have SMTP enabled
  packages/api-v4/.changeset/pr-10991-added-1727125536609.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-10991-changed-1727125505081.md
  packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts
  packages/manager/src/constants.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/manager/src/features/Linodes/SMTPRestrictionText.test.tsx
  packages/manager/src/features/Linodes/SMTPRestrictionText.tsx
Labels: Approved, Ready for Review

#11056 fix: [M3-8726] - Users unable to upgrade Kubernetes version from landing page
  packages/manager/.changeset/pr-11056-fixed-1728428139880.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
Labels: Bug, LKE, Approved

#11065 chore: [M3-7014] - Remove `isVLAN` code
  packages/manager/.changeset/pr-11065-tech-stories-1728392959296.md
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx
  packages/manager/src/features/Linodes/LinodesLanding/TableWrapper.tsx
Labels: Clean Up

#11061 test: Unit tests for CheckoutSummary component
  packages/manager/.changeset/pr-11061-tests-1728374977579.md
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.test.tsx
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
Labels: Approved, Unit tests

#11059 feat: [M3-7011] - Add databases to search result queries
  packages/manager/.changeset/pr-11059-added-1728379220045.md
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/refinedSearch.ts
  packages/manager/src/features/Search/search.interfaces.ts
  packages/manager/src/features/Search/utils.test.ts
  packages/manager/src/features/Search/utils.ts
  packages/manager/src/features/Search/withStoreSearch.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/store/selectors/getSearchEntities.ts
Labels: Approved, Search

#11055 test: [M3-8718] - Fix conflicting shorthand flags for TOD script
  scripts/tod-payload/index.ts
Labels: Approved

#11076 fix: TypeScript performance of `BarPercent.tsx`
  packages/manager/.changeset/pr-11076-tech-stories-1728498604542.md
  packages/manager/src/components/BarPercent/BarPercent.tsx
Labels: Performance

#11072 feat: [M3-8703] - Disable VPC Action Buttons for Restricted Users
  packages/manager/.changeset/pr-11072-changed-1728479835625.md
  packages/manager/src/features/VPCs/VPCLanding/VPCRow.tsx
Labels: Restricted User Access

#11079 fix: Better sanitize Pendo URLs
  packages/manager/.changeset/pr-11079-tech-stories-1728504676937.md
  packages/manager/src/hooks/usePendo.ts
Labels: Approved, Analytics

#11073 fix: [M3-8052] - Toasts are not consistently dismissible with the 'X' button
  packages/manager/.changeset/pr-11073-fixed-1728472748252.md
  packages/manager/src/components/Snackbar/Snackbar.tsx
Labels: Bug, Approved

#11057 upcoming: [M3-8638] - Introduce the new `(at)linode/ui` package
  .github/workflows/ci.yml
  README.md
  package.json
  packages/manager/package.json
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
  packages/ui/.changeset/README.md
  packages/ui/.changeset/pr-11057-added-1728496448213.md
  packages/ui/.eslintrc.json
  packages/ui/.prettierrc
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/components/BetaChip/BetaChip.test.tsx
  packages/ui/src/components/BetaChip/BetaChip.tsx
  packages/ui/src/components/BetaChip/index.ts
  packages/ui/src/components/Chip.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
  packages/ui/testSetup.ts
  packages/ui/tsconfig.json
  packages/ui/vitest.config.ts
  scripts/changelog/utils/constants.mjs
  scripts/package-versions/index.js
Labels: Approved, Modularization

#11040 feat: [UIE-8089] - DBaaS Resize GA
  packages/api-v4/.changeset/pr-11040-changed-1727911382574.md
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-11040-added-1727911099315.md
  packages/manager/cypress/e2e/core/databases/resize-database.spec.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/features/components/PlansPanel/types.ts
Labels: DBaaS

#11066 test: [M3-8436] - Add cypress test for create validation & API errors for OBJ Gen 2
  packages/manager/.changeset/pr-11066-tests-1728400382103.md
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
Labels: Testing, Object Storage Gen2

#11039 feat: [UIE-8098] - DBaaS 2.0 Landing Page GA
  packages/api-v4/.changeset/pr-11039-added-1727885059968.md
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-11039-upcoming-features-1727885138241.md
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/features/GlobalNotifications/DatabaseClusterInfoBanner.tsx
Labels: DBaaS, Approved

#11045 test: [M3-8445] Add new test to confirm changes to the Object details drawer for OBJ Gen 2
  packages/manager/.changeset/pr-11045-tests-1727985809023.md
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-object-gen2.spec.ts
  packages/manager/cypress/support/intercepts/object-storage.ts
Labels: Approved, Object Storage Gen2

#11069 feat: [M3-8560] - NodeBalancer Configurations - Support Linodes with Multiple Private IPs
  packages/manager/.changeset/pr-11069-fixed-1728443895478.md
  packages/manager/src/features/Linodes/LinodeCreate/shared/LinodeSelectTable.tsx
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.test.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
  packages/manager/src/features/Linodes/LinodesLanding/IPAddress.tsx
  packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx
  packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
  packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.utils.test.ts
  packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.utils.ts
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
  packages/manager/src/utilities/ipUtils.test.ts
  packages/manager/src/utilities/ipUtils.ts
  packages/validation/.changeset/pr-11069-added-1728444089255.md
  packages/validation/.changeset/pr-11069-changed-1728444173048.md
  packages/validation/src/nodebalancers.schema.ts
Labels: Approved, NodeBalancers

#11078 upcoming: [M3-6538] - Add Interaction Tokens, Minimally Cleanup Theme Files
  packages/manager/.changeset/pr-11078-upcoming-features-1728503718215.md
  packages/manager/src/components/ColorPalette/ColorPalette.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/foundations/themes/dark.ts
  packages/manager/src/foundations/themes/index.ts
  packages/manager/src/foundations/themes/light.ts
Labels: Add'tl Approval Needed, Design Tokens

#11089 fix: Conditionally check for `PENDO_API_KEY` before Pendo set up
  packages/manager/src/hooks/usePendo.ts
Labels: Ready for Review, Analytics

#10971 test: [M3-8444] - Add assertions for bucket details drawer tests
  packages/manager/.changeset/pr-10971-tests-1726764686101.md
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
Labels: Approved, Object Storage Gen2

#11081 fix: [M3-8730] - Remove `@mui/system` imports
  packages/manager/.eslintrc.cjs
  packages/manager/src/components/Avatar/Avatar.tsx
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/Checkbox.tsx
  packages/manager/src/components/CheckoutBar/styles.ts
  packages/manager/src/components/CircleProgress/CircleProgress.tsx
  packages/manager/src/components/DescriptionList/DescriptionList.tsx
  packages/manager/src/components/DialogTitle/DialogTitle.tsx
  packages/manager/src/components/DownloadCSV/DownloadCSV.tsx
  packages/manager/src/components/H1Header/H1Header.tsx
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx
  packages/manager/src/components/SelectionCard/CardBase.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/components/TextTooltip/TextTooltip.tsx
  packages/manager/src/components/TooltipIcon.tsx
  packages/manager/src/features/Betas/BetaSignup.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
  packages/manager/src/features/GlobalNotifications/ComplianceBanner.tsx
  packages/manager/src/features/Linodes/AccessTable.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/ImageEmptyState.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerSelect.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/CopyAllHostnames.tsx
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.tsx
  packages/manager/src/features/components/PlansPanel/DistributedRegionPlanTable.tsx
  packages/manager/src/foundations/breakpoints.ts
  packages/manager/src/foundations/themes/dark.ts
  packages/manager/src/foundations/themes/index.ts
  packages/manager/src/foundations/themes/light.ts
  packages/manager/src/utilities/deepMerge.test.ts
  packages/manager/src/utilities/deepMerge.ts
Labels: Approved, Performance

#11085 test: [M3-7863] - Use `happy-dom` instead of `jsdom` in unit tests
  packages/manager/.changeset/pr-11085-tests-1728657019139.md
  packages/manager/package.json
  packages/manager/src/components/Avatar/Avatar.test.tsx
  packages/manager/src/components/BetaChip/BetaChip.test.tsx
  packages/manager/src/components/DescriptionList/DescriptionList.test.tsx
  packages/manager/src/components/HighlightedMarkdown/__snapshots__/HighlightedMarkdown.test.tsx.snap
  packages/manager/src/components/Notice/Notice.test.tsx
  packages/manager/src/components/Tabs/Tab.test.tsx
  packages/manager/src/components/TextTooltip/TextTooltip.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.test.tsx
  packages/manager/src/features/Linodes/CloneLanding/Disks.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/index.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/VPCPanel.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.test.tsx
  packages/manager/src/features/Profile/OAuthClients/CreateOAuthClientDrawer.test.tsx
  packages/manager/src/features/Volumes/VolumeCreate.test.tsx
  packages/manager/src/utilities/omittedProps.test.tsx
  packages/manager/vite.config.ts
  packages/ui/.changeset/pr-11085-tests-1728657169966.md
  packages/ui/src/components/BetaChip/BetaChip.test.tsx
  packages/ui/vitest.config.ts
  yarn.lock
Labels: Dependencies, Unit tests

#11052 feat: [M3-8703] - Disable Create VPC button with tooltip text on empty state Landing Page for restricted users
  packages/manager/.changeset/pr-11052-changed-1728305995058.md
  packages/manager/src/features/VPCs/VPCLanding/VPCEmptyState.tsx
Labels: Approved, Restricted User Access

#11063 feat: [M3-8703] - Disable Create VPC button with tooltip text on Landing Page for restricted users
  packages/manager/.changeset/pr-11063-added-1728386681970.md
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
Labels: Approved, VPC, Restricted User Access

#11094 feat: [M3-8704] - Disable Create Firewall button with tooltip text on Landing Page for restricted users
  packages/manager/.changeset/pr-11094-fixed-1728923124356.md
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
Labels: Approved, Restricted User Access

#11098 change: [M3-7887] - VPC Not Recommended Configuration Tooltip Text Revision
  packages/manager/.changeset/pr-11098-changed-1728938497573.md
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/constants.ts
Labels: Approved

#11068 upcoming: [DI-21322] - Retain Resource selections during expand / collapse of filter button
  packages/manager/.changeset/pr-11068-upcoming-features-1728916409850.md
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
Labels: Approved, CloudPulse

#11092 refactor: [M3-8640] – Move Theme layer from `manager` package to `ui` package
  docker-compose.yml
  packages/manager/.changeset/pr-11092-tech-stories-1728680192850.md
  packages/manager/cypress/support/component/setup.tsx
  packages/manager/cypress/support/util/components.ts
  packages/manager/src/LinodeThemeWrapper.tsx
  packages/manager/src/components/Button/StyledActionButton.ts
  packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.tsx
  packages/manager/src/components/PrimaryNav/SideMenu.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Security.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.test.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.test.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.test.tsx
  packages/manager/src/utilities/theme.ts
  packages/ui/.changeset/pr-11092-added-1728931799888.md
  packages/ui/src/foundations/breakpoints.ts
  packages/ui/src/foundations/fonts.ts
  packages/ui/src/foundations/index.ts
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/index.ts
  packages/ui/src/foundations/themes/light.ts
  packages/ui/src/index.ts
Labels: Approved, Modularization

#11106 test: [M3-8756] - Fix Cypress SMTP support ticket test failure
  packages/manager/.changeset/pr-11106-tests-1729028269027.md
  packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts
Labels: Approved

#11060 test: [M3-8609] - Cypress test for non-empty Linode landing page with restricted user
  packages/manager/.changeset/pr-11060-tests-1728375821627.md
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
Labels: Approved

#11104 fix: `AppSelect.test.tsx` test flake
  packages/manager/.changeset/pr-11104-tests-1729020207783.md
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppSelect.test.tsx
Labels: Approved, Unit tests

#11062 Upcoming: [DI-20844] - Tooltip for widget level filters and icons, beta feedbacks and CSS changes for CloudPulse
  packages/manager/.changeset/pr-11062-upcoming-features-1728390800736.md
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.test.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidgetRenderer.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.test.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.test.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx
  packages/manager/src/features/CloudPulse/Widget/components/Zoomer.test.tsx
  packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTooltip.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTooltip.tsx
  packages/manager/src/queries/cloudpulse/metrics.ts
Labels: Approved, Ready for Review, CloudPulse

#11100 change: [M3-8749] - Add and use new cloud-init icon
  packages/manager/.changeset/pr-11100-changed-1729010084175.md
  packages/manager/src/assets/icons/cloud-init.svg
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/ImageSelectv2/ImageOptionv2.tsx
Labels: UX/UI, Approved

#11049 refactor: [M3-8712] - Tanstack Reat Router rollout setup + betas routes migration
  packages/manager/.changeset/pr-11049-tech-stories-1728329839703.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/e2e/core/account/betas.spec.ts
  packages/manager/cypress/e2e/core/account/smoke-enroll-beta.spec.ts
  packages/manager/cypress/support/intercepts/betas.ts
  packages/manager/src/App.tsx
  packages/manager/src/MainContent.tsx
  packages/manager/src/Router.tsx
  packages/manager/src/components/Link.tsx
  packages/manager/src/features/Betas/BetaDetails.test.tsx
  packages/manager/src/features/Betas/BetaDetails.tsx
  packages/manager/src/features/Betas/BetaDetailsList.test.tsx
  packages/manager/src/features/Betas/BetaDetailsList.tsx
  packages/manager/src/features/Betas/BetaSignup.tsx
  packages/manager/src/features/Betas/BetasLanding.test.tsx
  packages/manager/src/features/Betas/BetasLanding.tsx
  packages/manager/src/features/Betas/index.tsx
  packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/betas.ts
  packages/manager/src/routes/betas.tsx
  packages/manager/src/routes/index.tsx
  packages/manager/src/routes/longview.tsx
  packages/manager/src/routes/root.ts
  packages/manager/src/routes/routes.test.tsx
  packages/manager/src/routes/search.tsx
  packages/manager/src/routes/types.ts
  packages/manager/src/routes/utils/allPaths.ts
  packages/manager/src/utilities/testHelpers.test.tsx
  packages/manager/src/utilities/testHelpers.tsx
Labels: Approved, Routing Refactor

#11113 test: Fix LKE update test failure following feature flag update
  packages/manager/.changeset/pr-11113-tests-1729099850186.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
Labels: Approved

#11082 DI-20837 - Handle new label property for services while selecting dashboard and Node-type filter update in DbasS
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/src/factories/cloudpulse/services.ts
  packages/manager/src/factories/index.ts
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.test.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Add'tl Approval Needed, CloudPulse

#11101 fix: [M3-8748] - Markdown cheatsheet link in Support ticket interface has an expired domain
  packages/manager/.changeset/pr-11101-fixed-1729011064940.md
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/MarkdownReference.tsx
Labels: Approved

#11107 test: [M3-8744] - Reduce Cypress flakiness in Placement Group deletion tests
  packages/manager/.changeset/pr-11107-tests-1729033939339.md
  packages/manager/cypress/e2e/core/placementGroups/delete-placement-groups.spec.ts
Labels: e2e, Approved

#11070 feat: [M3-7445] - Public IP Addresses Tooltip and LISH Display
  packages/manager/.changeset/pr-11070-changed-1728495168369.md
  packages/manager/cypress/support/intercepts/object-storage.ts
  packages/manager/src/features/Linodes/AccessTable.test.tsx
  packages/manager/src/features/Linodes/AccessTable.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesLanding/IPAddress.tsx
  packages/manager/src/features/Linodes/PublicIPAddressesTooltip.tsx
  packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
Labels: Approved, VPC

#11086 feat: [M3-7158] - Update NodeJS naming to Node.js for Marketplace
  packages/manager/.changeset/pr-11086-tech-stories-1729012343535.md
  packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts
  packages/manager/src/factories/stackscripts.ts
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppDetailDrawer.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppDetailDrawer.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppSection.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/utilities.ts
  packages/manager/src/features/OneClickApps/oneClickAppsv2.ts
  packages/manager/src/features/OneClickApps/types.ts
Labels: Marketplace

#11103 fix: [M3-8752] - Region Multi Select spacing issues
  packages/manager/.changeset/pr-11103-fixed-1729099711508.md
  packages/manager/src/components/Flag.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
  packages/manager/src/components/RegionSelect/RegionOption.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.styles.ts
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/SelectedRegionsList.tsx
Labels: Bug, Approved, Clean Up

#11074 fix: [M3-7197] - "Support Ticket" button in network tab not working properly
  packages/manager/.changeset/pr-11074-fixed-1728476792585.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/ExplainerCopy.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/ExplainerCopy.tsx
Labels: Bug, Approved, Ready for Review

#11114 fix: [UIE-8181] - DBaaS enable restricted beta users
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingEmptyStateData.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/queries/databases/databases.ts
Labels: DBaaS, Approved

#11105 feat: [UIE-7995] DBaaS Monitor GA
  packages/manager/.changeset/pr-11105-added-1729023730319.md
  packages/manager/src/components/Tabs/TabLinkList.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseMonitor/DatabaseMonitor.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseMonitor/DatabaseMonitor.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
Labels: Add'tl Approval Needed, DBaaS, Ready for Review

#11112 feat: [M3-7841] - Add the capability to search for a Linode by ID using the main search tool.
  packages/manager/.changeset/pr-11112-added-1729086990373.md
  packages/manager/cypress/e2e/core/linodes/search-linodes.spec.ts
  packages/manager/src/features/Search/refinedSearch.ts
  packages/manager/src/features/Search/search.interfaces.ts
  packages/manager/src/store/selectors/getSearchEntities.ts
Labels: Approved

#11090 fix: [M3-8739] - Fix MSW 2.0 initial mock store and support ticket seeder bugs
  packages/manager/.changeset/pr-11090-tech-stories-1728605016946.md
  packages/manager/src/mocks/mockState.ts
  packages/manager/src/mocks/presets/crud/seeds/utils.ts
Labels: Bug, Approved

#11119 test: [M3-8734] - Reduce Linode rebuild test flakiness
  packages/manager/.changeset/pr-11119-tests-1729169604255.md
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
Labels: Approved, Ready for Review

#11093 feat: [M3-8704] - Disable Create Firewalls button with tooltip text on empty state Landing Page for restricted users.
  packages/manager/.changeset/pr-11093-fixed-1728898767762.md
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLandingEmptyState.tsx
Labels: Approved, Restricted User Access

#11123 fix: Dark Mode style regressions
  packages/manager/package.json
  packages/ui/src/foundations/themes/index.ts
  yarn.lock
Labels: Bug, UX/UI

#11129 docs: Change `pageSize` to `page_size` in `api-v4` documentation
  packages/api-v4/.changeset/pr-11129-fixed-1729536266478.md
  packages/api-v4/README.md
Labels: Documentation

#11116 refactor: [M3-8746] – Move `inputMaxWidth` into `Theme`
  packages/manager/src/features/Linodes/LinodeCreate/Security.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
  packages/ui/.changeset/pr-11116-changed-1729114321677.md
  packages/ui/src/foundations/themes/index.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Modularization

#11122 change: [M3-8509] - Add Pendo documentation to our development guide
  docs/tooling/analytics.md
  packages/manager/.changeset/pr-11122-added-1729183156879.md
  packages/manager/src/hooks/usePendo.ts
Labels: Approved, Documentation, Analytics

#11115 upcoming: [M3-8751& M3-8610] - Image Service Gen 2 final GA tweaks
  packages/manager/.changeset/pr-11115-upcoming-features-1729115799261.md
  packages/manager/cypress/e2e/core/images/manage-image-regions.spec.ts
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/ImageSelectv2/ImageOptionv2.test.tsx
  packages/manager/src/components/ImageSelectv2/ImageOptionv2.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.test.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRow.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRow.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
Labels: Image Service Gen2

#11118 upcoming: [DI-20928] - Introduce label for all global filters
  packages/manager/.changeset/pr-11118-upcoming-features-1729486113842.md
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/cypress/support/util/cloudpulse.ts
  packages/manager/src/components/Autocomplete/Autocomplete.styles.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.test.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
Labels: Approved, CloudPulse

#11136 feat: [DI-21463] - Added capability to transform area chart into line chart
  packages/manager/.changeset/pr-11136-added-1729581444483.md
  packages/manager/src/components/AreaChart/AreaChart.tsx
Labels: CloudPulse

#11088 test: [M3-8072] - Cloud changes for ad-hoc test pipeline
  docker-compose.yml
  docs/development-guide/08-testing.md
  packages/manager/.changeset/pr-11088-tech-stories-1729535071709.md
  packages/manager/.changeset/pr-11088-tests-1729535093463.md
  packages/manager/.changeset/pr-11088-tests-1729535165205.md
  packages/manager/.changeset/pr-11088-tests-1729535197632.md
  packages/manager/Dockerfile
  packages/manager/cypress.config.ts
  packages/manager/cypress/support/constants/feature-flags.ts
  packages/manager/cypress/support/e2e.ts
  packages/manager/cypress/support/intercepts/feature-flags.ts
  packages/manager/cypress/support/plugins/feature-flag-override.ts
  packages/manager/cypress/support/setup/mock-feature-flags-request.ts
  scripts/junit-summary/formatters/github-formatter.ts
  scripts/junit-summary/formatters/slack-formatter.ts
  scripts/junit-summary/index.ts
  scripts/junit-summary/metadata/metadata.ts
Labels: Ready for Review

#11124 feat: [UIE-8196] - DBaaS create encourage users to add IP allow_list
  packages/manager/.changeset/pr-11124-upcoming-features-1729198459249.md
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.test.tsx
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreateAccessControls.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreateAccessControls.tsx
Labels: Add'tl Approval Needed, DBaaS

#10968 feat: [LKEAPIFW-428] LKE clusters should have IP ACL integration on CM (part 1)
  packages/api-v4/.changeset/pr-10968-added-1727966811522.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/kubernetes/kubernetes.ts
  packages/api-v4/src/kubernetes/types.ts
  packages/manager/.changeset/pr-10968-added-1727901904107.md
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/components/MultipleIPInput/MultipleNonExtendedIPInput.tsx
  packages/manager/src/factories/dashboards.ts
  packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeEntityDetailFooter.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.styles.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/queries/kubernetes.ts
  packages/validation/.changeset/pr-10968-added-1729020457987.md
  packages/validation/src/firewalls.schema.ts
  packages/validation/src/kubernetes.schema.ts
Labels: LKE, Approved

#11133 refactor: [M3-8765] - Remove unused Marketplace feature flags
  packages/manager/.changeset/pr-11133-tech-stories-1729550913039.md
  packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppSelect.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/utilities.test.ts
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/UserDefinedFields/UserDefinedFields.tsx
  packages/manager/src/features/OneClickApps/oneClickApps.ts
Labels: Approved, Clean Up

#10952 refactor: [M3-8501] - AccessSelect Optimization: Use React Hook Form
  packages/manager/.changeset/pr-10952-tech-stories-1726576261944.md
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketAccess.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/queries/object-storage/queries.ts
Labels: Approved, Ready for Review

#11120 upcoming: [M3-8755, M3-6700] - Add global colorTokens to theme and replace one-off hardcoded white colors
  packages/manager/.changeset/pr-11120-upcoming-features-1729173753438.md
  packages/manager/src/components/Accordion.tsx
  packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
  packages/manager/src/components/Placeholder/Placeholder.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/RegionSelect/RegionSelect.styles.ts
  packages/manager/src/components/Tag/Tag.styles.ts
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/dev-tools/Preferences.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/CancelLanding/CancelLanding.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppDetailDrawer.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/QRCodeForm.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.styles.ts
  packages/manager/src/features/components/PlansPanel/PlanSelection.styles.ts
  packages/ui/src/foundations/themes/index.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Design Tokens

#11148 fix: [M3-8773] - Duplicate punctuation on `image_upload` event message
  packages/manager/.changeset/pr-11148-fixed-1729687116230.md
  packages/manager/src/features/Events/factories/image.tsx
Labels: Approved

#11110 fix: [APL-272] - Make `useAPLAvailability` check for beta enrollment
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-11110-added-1729516190960.md
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.test.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/queries/account/betas.ts
  packages/manager/src/queries/kubernetes.ts
Labels: LKE

#11067 feat: [M3-8722] - Improve weblish retry behavior
  packages/manager/.changeset/pr-11067-added-1729705480335.md
  packages/manager/src/components/ErrorState/ErrorState.tsx
  packages/manager/src/features/Lish/Lish.tsx
  packages/manager/src/features/Lish/Weblish.tsx
Labels: Approved

#11139 change: [M3-8759] - Hide distributed regions in Linode Create StackScripts
  packages/api-v4/.changeset/pr-11139-added-1729701623137.md
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-11139-changed-1729698979911.md
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
Labels: Approved, Gecko LA

#11131 test: [M3-8725] - Add cypress tests for updating ACL in LKE clusters (LKE ACL integration part 2)
  packages/manager/.changeset/pr-11131-tests-1729627189739.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/cypress/support/intercepts/kubernetes.ts
  packages/manager/cypress/support/intercepts/lke.ts
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx
Labels: Testing, LKE, Approved

#11135 refactor: [M3-8766] - Cleanup feature flag - Create Using Command Line (DX Tools Additions)
  packages/manager/.changeset/pr-11135-tech-stories-1729565746630.md
  packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
Labels: Approved, Clean Up, DX Tools Additions

#11099 change: [M3-8373] - Fix unexpected heading spacing on Account Maintenance page
  packages/manager/.changeset/pr-11099-fixed-1728996803052.md
  packages/manager/src/features/Account/Maintenance/MaintenanceLanding.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
Labels: Approved

#11132 test: [M3-8725] - Add cypress tests for creating LKE clusters with ACL (LKE ACL integration part 3)
  packages/manager/.changeset/pr-11132-tests-1729628045654.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.styles.tsx
Labels: Testing, Add'tl Approval Needed, LKE

#11144 refactor: [M3-8775] - Make the Support Ticket UI look slightly less broken
  packages/manager/.changeset/pr-11144-changed-1729684811107.md
  packages/manager/src/components/Paper.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/MarkdownReference.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/PreviewReply.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TabbedReply.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
Labels: UX/UI, Approved, Ready for Review

#11125 refactor: [M3-8707] - Move `Tooltip` component to UI package
  packages/manager/.storybook/main.ts
  packages/manager/.storybook/utils.test.ts
  packages/manager/.storybook/utils.ts
  packages/manager/src/components/BackupStatus/BackupStatus.tsx
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
  packages/manager/src/components/DownloadTooltip.tsx
  packages/manager/src/components/GroupByTagToggle.tsx
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/ImageSelectv2/ImageOptionv2.tsx
  packages/manager/src/components/PlacementGroupsSelect/PlacementGroupSelectOption.tsx
  packages/manager/src/components/PrimaryNav/NavItem.tsx
  packages/manager/src/components/RegionSelect/RegionOption.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/components/TextTooltip/TextTooltip.tsx
  packages/manager/src/components/TooltipIcon.tsx
  packages/manager/src/components/Uploaders/FileUpload.tsx
  packages/manager/src/dev-tools/ServiceWorkerTool.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTooltip.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ImageRegionRow.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx
  packages/manager/src/features/Managed/Monitors/IssueDay.tsx
  packages/manager/src/features/Managed/Monitors/MonitorRow.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessCell.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/CopyAllHostnames.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupTypeSelect.tsx
  packages/manager/src/features/TopMenu/TopMenuTooltip.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/components/PlansPanel/DisabledPlanSelectionTooltip.tsx
  packages/manager/src/utilities/noneSingleOrMultipleWithChip.tsx
  packages/ui/src/components/Tooltip.stories.tsx
  packages/ui/src/components/Tooltip.tsx
  packages/ui/src/components/index.ts
Labels: Approved, Modularization

#11161 fix: [M3-8788] - Only run coverage comment job on non-drafts
  .github/workflows/coverage_comment.yml
  packages/manager/.changeset/pr-11161-fixed-1729827835443.md
Labels: Approved

#11158 refactor: [M3-8707] - Move `IconButton` component to UI package
  packages/manager/src/components/Autocomplete/Autocomplete.stories.tsx
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx
  packages/manager/src/components/DialogTitle/DialogTitle.tsx
  packages/manager/src/components/Drawer.tsx
  packages/manager/src/components/EditableEntityLabel/EditableInput.tsx
  packages/manager/src/components/MenuItem/MenuItem.tsx
  packages/manager/src/components/PrimaryNav/SideMenu.stories.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsListTable.tsx
  packages/manager/src/components/Snackbar/CloseSnackbar.tsx
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/components/TooltipIcon.tsx
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ImageRegionRow.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionList.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/UserDefinedFields/UserDefinedFields.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPCRanges.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.styles.ts
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/AppInfo.tsx
  packages/manager/src/features/Support/TicketDetailText.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.styles.ts
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/features/components/PlansPanel/DisabledPlanSelectionTooltip.tsx
  packages/ui/.changeset/pr-11125-added-1729871688954.md
  packages/ui/.changeset/pr-11158-added-1729864026236.md
  packages/ui/src/components/IconButton.tsx
  packages/ui/src/components/index.ts
Labels: Add'tl Approval Needed, Modularization

#11137 fix: [M3-8590] - Restrict access to Database Create page for restricted users
  packages/manager/.changeset/pr-11137-fixed-1729745562099.md
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreateAccessControls.tsx
Labels: Approved, Restricted User Access

#11147 change: [M3-8461] - Improve validation error when a backup is not selected.
  packages/manager/.changeset/pr-11147-changed-1729684531663.md
  packages/manager/src/features/Linodes/LinodeCreate/schemas.ts
Labels: Approved, Linodes

#11111 change: [M3-8442] - Remove Double border on "Billing & Payment History" table with dark theme.
  packages/manager/.changeset/pr-11111-changed-1729082750525.md
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
Labels: Approved, Design Tokens

#11173 change: LKE ACL copy and placeholder updates
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx
Labels: LKE, Approved

#11141 refactor: [M3-8770] - Clean up Profile Display Settings page
  packages/manager/.changeset/pr-11141-added-1730133012318.md
  packages/manager/.changeset/pr-11141-tech-stories-1729629238072.md
  packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.test.tsx
  packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.tsx
  packages/manager/src/features/Profile/DisplaySettings/AvatarForm.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/AvatarForm.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/Profile/DisplaySettings/EmailForm.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/EmailForm.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
  packages/manager/src/features/Profile/DisplaySettings/UsernameForm.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/UsernameForm.tsx
  packages/manager/src/queries/profile/profile.ts
Labels: Approved, Clean Up

#11157 chore: [M3-8786] - Update and clean up `@types/node` package
  packages/api-v4/.changeset/pr-11157-tech-stories-1729787265807.md
  packages/api-v4/package.json
  packages/manager/.changeset/pr-11157-tech-stories-1729787405590.md
  packages/manager/cypress/support/plugins/discard-passed-test-recordings.ts
  packages/manager/package.json
  packages/manager/src/hooks/useInterval.tsx
  packages/ui/.changeset/pr-11157-tech-stories-1729787461166.md
  packages/ui/package.json
  packages/validation/.changeset/pr-11157-tech-stories-1729787428923.md
  packages/validation/package.json
  yarn.lock
Labels: Dependencies, Approved

#11176 test: [M3-8776] - Fix lke-create tests and create unit tests for LKE ACL
  packages/manager/.changeset/pr-11176-tests-1730144406169.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx
Labels: Testing, LKE, Approved, Unit tests

#11165 upcoming: [M3-6700] - Replace one-off hardcoded black and white color values with colorTokens
  packages/manager/.changeset/pr-11165-upcoming-features-1729872623442.md
  packages/manager/src/GoTo.tsx
  packages/manager/src/components/AkamaiBanner/AkamaiBanner.styles.ts
  packages/manager/src/components/ColorPalette/ColorPalette.tsx
  packages/manager/src/components/Drawer.tsx
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/MainContentBanner.tsx
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/components/Notice/Notice.styles.ts
  packages/manager/src/components/Placeholder/Placeholder.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PromotionalOfferCard/PromotionalOfferCard.tsx
  packages/manager/src/components/ShowMore/ShowMore.tsx
  packages/manager/src/components/Tag/Tag.styles.ts
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Databases/DatabaseCreate/EngineOption.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppDetailDrawer.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.styles.ts
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Design Tokens

#11171 upcoming: [M3-8755] - Add global `font` and `spacing` tokens to theme and refactor design tokens
  packages/manager/.changeset/pr-11171-upcoming-features-1730182630692.md
  packages/manager/src/GoTo.tsx
  packages/manager/src/components/Accordion.tsx
  packages/manager/src/components/AkamaiBanner/AkamaiBanner.styles.ts
  packages/manager/src/components/ColorPalette/ColorPalette.tsx
  packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
  packages/manager/src/components/Drawer.tsx
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/MainContentBanner.tsx
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/components/Notice/Notice.styles.ts
  packages/manager/src/components/Placeholder/Placeholder.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PromotionalOfferCard/PromotionalOfferCard.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.styles.ts
  packages/manager/src/components/ShowMore/ShowMore.tsx
  packages/manager/src/components/Tag/Tag.styles.ts
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/dev-tools/Preferences.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/CancelLanding/CancelLanding.tsx
  packages/manager/src/features/Databases/DatabaseCreate/EngineOption.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.style.ts
  packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppDetailDrawer.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/QRCodeForm.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.styles.ts
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.styles.ts
  packages/manager/src/features/components/PlansPanel/PlanSelection.styles.ts
  packages/ui/src/foundations/breakpoints.ts
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/index.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Design Tokens

#11182 fix: [UIE-8007] - DBaaS display host in summary details
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
Labels: DBaaS, Hotfix

#11185 Release v1.131.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
Labels: Release, Hotfix

#11188 change: [M3-8807] - Improve Linode Create VPC user experience
  packages/manager/.changeset/pr-11188-added-1730298408749.md
  packages/manager/cypress/e2e/core/linodes/create-linode-with-vpc.spec.ts
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/VPCPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/VPCPanel.tsx
  packages/manager/src/features/VPCs/VPCCreateDrawer/VPCCreateDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCCreateDrawer/VPCCreateDrawer.tsx
  packages/manager/src/hooks/useCreateVPC.ts
Labels: Approved, VPC

#11080 change: [M3-8659] - Incorporate Product Family Groups in Side Nav
  packages/manager/.changeset/pr-11080-changed-1730138781683.md
  packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-navigation.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.smoke.spec.ts
  packages/manager/src/assets/icons/more.svg
  packages/manager/src/components/PrimaryNav/PrimaryLink.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/PrimaryNav/SideMenu.stories.tsx
  packages/manager/src/components/PrimaryNav/SideMenu.tsx
  packages/manager/src/features/Domains/DomainsEmptyLandingPage.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLandingEmptyState.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLandingEmptyState.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLandingEmptyState.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLandingEmptyState.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptsEmptyLandingPage.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEmptyState.tsx
  packages/manager/src/features/Volumes/VolumesLandingEmptyState.styles.ts
  packages/manager/src/features/Volumes/VolumesLandingEmptyState.tsx
  packages/manager/src/hooks/usePreFetch.ts
  packages/ui/src/foundations/themes/light.ts
Labels: UX/UI

#11190 test: [M3-8810] - Fix DBaaS failures when v2 feature flag is enabled
  packages/manager/.changeset/pr-11190-tests-1730312266172.md
  packages/manager/cypress/e2e/core/databases/resize-database.spec.ts
Labels: Approved, Ready for Review

#11134 refactor: [M3-8652] - TextField Component Cleanup - Part 1
  packages/manager/.changeset/pr-11134-tech-stories-1729561221251.md
  packages/manager/src/components/TextField.stories.tsx
  packages/manager/src/components/TextField.tsx
Labels: Approved, Modularization

#11184 test: [M3-8809] - Add vitest workspace configuration
  docs/development-guide/08-testing.md
  package.json
  packages/api-v4/package.json
  packages/manager/.changeset/pr-11184-tests-1730217933343.md
  packages/manager/.storybook/utils.test.ts
  packages/manager/.storybook/utils.ts
  packages/manager/package.json
  packages/search/package.json
  packages/ui/package.json
  vitest.workspace.ts
Labels: Approved, Modularization
