Repository linode/manager, pull requests merged in 2024-09, with the labels that each got.

#10865 change: increased block storage max volume size to 16TB
  packages/api-v4/CHANGELOG.md
  packages/api-v4/src/constants.ts
  packages/manager/CHANGELOG.md
  packages/manager/src/constants.ts
  packages/validation/CHANGELOG.md
  packages/validation/src/constants.ts
Labels: Approved, Ready for Review, Volumes

#10802 test: [M3-8454] - Cypress test for Secure VMs firewall generation
  packages/manager/.changeset/pr-10802-tests-1724271249856.md
  packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
  packages/manager/cypress/support/intercepts/firewalls.ts
Labels: e2e, Approved, Secure VMs

#10134 test: [M3-5858] - Cypress component tests
  package.json
  packages/manager/cypress.config.ts
  packages/manager/cypress/component/poc/beta-chip.spec.tsx
  packages/manager/cypress/component/poc/region-select.spec.tsx
  packages/manager/cypress/support/component/index.html
  packages/manager/cypress/support/component/setup.tsx
  packages/manager/cypress/support/index.d.ts
  packages/manager/cypress/support/intercepts/account.ts
  packages/manager/cypress/support/util/accessibility.ts
  packages/manager/cypress/support/util/components.ts
  packages/manager/package.json
  packages/manager/src/components/RegionSelect/RegionOption.tsx
Labels: Proof of Concept, Approved

#10857 upcoming: [M3-8378] - OBJ Cleanup
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketProperties.styles.ts
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketProperties.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
Labels: Add'tl Approval Needed, Object Storage Gen2

#10876 fix: cherry-picked our changes to feature flag rate limit text
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
Labels: Hotfix

#10850 refactor: [M3-6852] - Remove global error interceptors
  packages/manager/.changeset/pr-10850-tech-stories-1724879639152.md
  packages/manager/src/components/ErrorMessage.tsx
  packages/manager/src/components/GenerateFirewallDialog/GenerateFirewallDialog.tsx
  packages/manager/src/components/MigrateError.tsx
  packages/manager/src/components/SupportLink/SupportLink.tsx
  packages/manager/src/components/SupportTicketGeneralError.tsx
  packages/manager/src/components/VerificationError.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Error.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/manager/src/request.tsx
  packages/manager/src/utilities/formikErrorUtils.ts
  packages/manager/src/utilities/interceptAPIError.tsx
Labels: Approved

#10839 chore: [M3-8262] - Cleanup eventMessages flag and legacy code
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-10839-tech-stories-1724962338813.md
  packages/manager/cypress/e2e/core/notificationsAndEvents/events.spec.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Events/Event.helpers.test.ts
  packages/manager/src/features/Events/Event.helpers.ts
  packages/manager/src/features/Events/EventRow.test.tsx
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/Events/EventRowV2.test.tsx
  packages/manager/src/features/Events/EventRowV2.tsx
  packages/manager/src/features/Events/EventsLanding.styles.ts
  packages/manager/src/features/Events/EventsLanding.test.tsx
  packages/manager/src/features/Events/EventsLanding.tsx
  packages/manager/src/features/Events/constants.ts
  packages/manager/src/features/Events/eventMessageGenerator.test.ts
  packages/manager/src/features/Events/eventMessageGenerator.ts
  packages/manager/src/features/Events/eventMessageGenerator_CMR.tsx
  packages/manager/src/features/Events/factories/linode.tsx
  packages/manager/src/features/Events/utils.test.tsx
  packages/manager/src/features/Events/utils.tsx
  packages/manager/src/features/GlobalNotifications/ComplianceBanner.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/NotificationCenter/Events.tsx
  packages/manager/src/features/NotificationCenter/Events/NotificationCenterEvent.test.tsx
  packages/manager/src/features/NotificationCenter/Events/NotificationCenterEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationCenter.styles.ts
  packages/manager/src/features/NotificationCenter/NotificationCenterContext.ts
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.styles.ts
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.test.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEventV2.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/notificationUtils.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/useEventInfo.ts
  packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
  packages/manager/src/features/NotificationCenter/NotificationSection.tsx
  packages/manager/src/features/NotificationCenter/Notifications.tsx
  packages/manager/src/features/NotificationCenter/Notifications/NotificationCenterNotificationMessage.tsx
  packages/manager/src/features/NotificationCenter/Notifications/NotificationCenterNotifications.tsx
  packages/manager/src/features/NotificationCenter/Notifications/NotificationCenterNotificationsContainer.tsx
  packages/manager/src/features/NotificationCenter/index.tsx
  packages/manager/src/features/NotificationCenter/types.ts
  packages/manager/src/features/NotificationCenter/useFormattedNotifications.test.ts
  packages/manager/src/features/NotificationCenter/useFormattedNotifications.tsx
  packages/manager/src/features/NotificationCenter/utils.ts
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.test.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenuV2.tsx
  packages/manager/src/features/TopMenu/TopMenu.tsx
Labels: Approved, Clean Up

#10861 change: [M3-8511] - Refactor and Improve the User Details Page
  packages/manager/.changeset/pr-10861-changed-1725028189510.md
  packages/manager/cypress/e2e/core/account/user-profile.spec.ts
  packages/manager/cypress/e2e/core/account/users-landing-page.spec.ts
  packages/manager/src/features/Users/UserDetail.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Users/UserProfile.styles.ts
  packages/manager/src/features/Users/UserProfile.tsx
  packages/manager/src/features/Users/UserProfile/DeleteUserPanel.tsx
  packages/manager/src/features/Users/UserProfile/UserDetailsPanel.test.tsx
  packages/manager/src/features/Users/UserProfile/UserDetailsPanel.tsx
  packages/manager/src/features/Users/UserProfile/UserEmailPanel.test.tsx
  packages/manager/src/features/Users/UserProfile/UserEmailPanel.tsx
  packages/manager/src/features/Users/UserProfile/UserProfile.tsx
  packages/manager/src/features/Users/UserProfile/UsernamePanel.test.tsx
  packages/manager/src/features/Users/UserProfile/UsernamePanel.tsx
  packages/manager/src/queries/account/users.ts
  packages/manager/src/queries/profile/profile.ts
Labels: Enhancement, Approved, Clean Up

#10851 upcoming: [DI-20501] - Fix Demo feedbacks and missed changes across ACLP
  packages/api-v4/.changeset/pr-10851-upcoming-features-1725332570350.md
  packages/api-v4/src/cloudpulse/dashboards.ts
  packages/api-v4/src/cloudpulse/services.ts
  packages/manager/.changeset/pr-10851-upcoming-features-1724918306619.md
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/features/CloudPulse/CloudPulseLanding.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.test.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, CloudPulse

#10866 refactor: [M3-8513] - Update Node.js from `18.14` to `20.17`
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/coverage_badge.yml
  .github/workflows/coverage_comment.yml
  .github/workflows/e2e_schedule_and_push.yml
  .nvmrc
  docs/GETTING_STARTED.md
  package.json
  packages/manager/.changeset/pr-10866-tech-stories-1725038374615.md
  packages/manager/Dockerfile
  packages/manager/cypress/support/plugins/node-version-check.ts
  packages/manager/src/components/AreaChart/utils.test.ts
  scripts/getting_started.sh
Labels: Approved

#10874 feat: [OCA-1418] - Adds September 2024 Marketplace apps
  packages/manager/.changeset/pr-10874-added-1725380346411.md
  packages/manager/public/assets/apachespark.svg
  packages/manager/public/assets/white/apachespark.svg
  packages/manager/src/features/OneClickApps/oneClickAppsv2.ts
Labels: Marketplace, Approved

#10871 fix: [M3-8502] - Allow regions to be searched by ID when Gecko is enabled
  packages/manager/.changeset/pr-10871-fixed-1725373117220.md
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
Labels: Approved

#10845 upcoming: [DI-20357] - Changes for ACLP Dashboard with Filters component
  packages/manager/.changeset/pr-10845-upcoming-features-1724828070812.md
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.test.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.test.ts
  packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, CloudPulse

#10886 change: [M3-8520] - Revert the "View Code Snippets"button copy to the original text
  packages/manager/.changeset/pr-10886-upcoming-features-1725465397032.md
  packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Labels: Add'tl Approval Needed

#10870 feat: [M3-8178] - Add SelectableTableRow Story
  packages/manager/.changeset/pr-10870-added-1725366701050.md
  packages/manager/src/components/SelectableTableRow/SelectableTableRow.stories.tsx
  packages/manager/src/components/SelectableTableRow/SelectableTableRow.tsx
Labels: Storybook, Approved

#10794 feat: [M3-7686] - Restricted access UX for Databases
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-10794-added-1724066782757.md
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupActionMenu.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupTableRow.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMenuItem.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
Labels: Approved, Restricted User Access

#10888 test: [M3-8471] - Allow Cypress region selection to work with Gecko options improvements
  packages/manager/.changeset/pr-10888-tests-1725482771826.md
  packages/manager/cypress/support/ui/autocomplete.ts
Labels: Approved

#10872 feat: [UIE-8006] - DBaaS 2.0 Create
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-10872-upcoming-features-1725396256315.md
  packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/factories/account.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
Labels: DBaaS, Approved

#10877 refactor: [M3-8496] - Remove Placement Group flag and underlying logic
  packages/manager/.changeset/pr-10877-tech-stories-1725397280235.md
  packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/create-linode-with-placement-groups.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/create-placement-groups.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/delete-placement-groups.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/placement-groups-landing-page.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/placement-groups-linode-assignment.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/update-placement-group-label.spec.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.test.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.test.tsx
  packages/manager/src/features/PlacementGroups/utils.test.ts
  packages/manager/src/features/PlacementGroups/utils.ts
Labels: Approved, Placement Groups

#10893 fix: [M3-8529] - Weblish line wrapping
  packages/manager/.changeset/pr-10893-fixed-1725548041320.md
  packages/manager/src/features/Lish/Weblish.tsx
Labels: Bug, Approved

#10890 test: [M3-8518] - Add unit tests for SelectableTableRow component
  packages/manager/.changeset/pr-10890-tests-1725525454848.md
  packages/manager/src/components/SelectableTableRow/SelectableTableRow.test.tsx
Labels: Approved, Unit tests

#10841 refactor: [M3-8331] - useToastNotification async toasts
  packages/manager/.changeset/pr-10841-tech-stories-1724763185078.md
  packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
  packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/delete-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/upgrade-volume.spec.ts
  packages/manager/src/features/Events/asyncToasts.test.tsx
  packages/manager/src/features/Events/asyncToasts.tsx
  packages/manager/src/features/Events/factories/backup.tsx
  packages/manager/src/features/Events/factories/disk.tsx
  packages/manager/src/features/Events/factories/image.tsx
  packages/manager/src/hooks/useToastNotifications.tsx
Labels: Approved, Ready for Review

#10813 refactor: [M3-8186] - Clean up DebouncedSearchTextField and fix instances where debouncing is not happening
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextfield.test.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/shared/LinodeSelectTable.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodePanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodePanel.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
Labels: Approved

#10902 change: [M3-8548] - Update security policy
  SECURITY.md
  packages/manager/.changeset/pr-10902-changed-1725634282672.md
  packages/manager/public/.well-known/security.txt
  security.txt
Labels: Approved

#10896 change: [M3-8531] - Hide Beta price notice for Gecko LA
  packages/manager/.changeset/pr-10896-changed-1725558246039.md
  packages/manager/src/components/RegionSelect/RegionOption.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayDialog.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
Labels: Approved, Gecko LA

#10901 fix: [M3-7915] - Update Linode Migrate Datacenter Started message to be generic
  packages/manager/.changeset/pr-10901-fixed-1725632415734.md
  packages/manager/src/features/Events/factories/linode.tsx
Labels: Bug, Approved, Ready for Review

#10882 test: [M3-6615, M3-8507] - Cypress test for empty Linode landing page and restricted user Linode landing page
  packages/manager/.changeset/pr-10882-tests-1725437459486.md
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
Labels: e2e, Approved

#10879 test: [M3-8434] - Cypress integration test for Object Storage Gen2: E2 Endpoint
  packages/manager/.changeset/pr-10879-tests-1725646369852.md
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
Labels: e2e, Approved, Object Storage Gen2

#10880 test: [M3-8435] - Cypress integration test for Object Storage Gen2: E3 Endpoint
  packages/manager/.changeset/pr-10880-tests-1725646735341.md
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: e2e, Approved, Object Storage Gen2

#10894 change: [M3-8530] - Allow quoted strings in Search v2 and improve StackScript searching on Linode Create v2
  packages/manager/.changeset/pr-10894-added-1725553004847.md
  packages/manager/.changeset/pr-10894-fixed-1725552964331.md
  packages/manager/src/components/Code/Code.tsx
  packages/manager/src/components/TextField.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/StackScriptSelectionList.tsx
  packages/search/src/search.peggy
  packages/search/src/search.test.ts
Labels: Search

#10837 upcoming: [M3-8465] – Add "Volume Encryption" section to "Create and Attach Volume" drawer
  docs/tooling/react-query.md
  packages/api-v4/.changeset/pr-10837-upcoming-features-1725037074546.md
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-10837-tests-1725037321098.md
  packages/manager/.changeset/pr-10837-upcoming-features-1725037508758.md
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/cypress/support/intercepts/volumes.ts
  packages/manager/cypress/support/util/linodes.ts
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/components/Encryption/constants.tsx
  packages/manager/src/factories/linodes.ts
  packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeAddDrawer.test.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeAddDrawer.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeAttachForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeCreateForm.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/VolumeSelect.tsx
  packages/manager/src/queries/volumes/events.ts
  packages/manager/src/queries/volumes/volumes.ts
Labels: Approved, Block Storage Encryption (BSE)

#10835 change: [M3-8491] - Image Service Gen2 GA tweaks
  packages/manager/.changeset/pr-10835-changed-1724705534485.md
  packages/manager/cypress/e2e/core/images/manage-image-regions.spec.ts
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.test.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRow.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRow.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesActionMenu.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Images/ImagesLanding/RegionsList.test.tsx
  packages/manager/src/features/Images/ImagesLanding/RegionsList.tsx
Labels: Ready for Review, Image Service Gen2

#10867 test: [M3-8474] - Allow cached account data to be used for Cypress tests when available
  docker-compose.yml
  docs/development-guide/08-testing.md
  packages/manager/.changeset/pr-10867-tests-1725460656929.md
  packages/manager/.changeset/pr-10867-tests-1725482924721.md
  packages/manager/cypress/support/plugins/fetch-account.ts
Labels: Approved

#10889 test: [M3-8526] - Update remaining Linode Create Cypress tests run against Linode Create v2
  packages/manager/.changeset/pr-10889-tests-1725485099504.md
  packages/manager/cypress/e2e/core/general/gdpr-agreement.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-mobile.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-region-select.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-add-ons.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-dc-specific-pricing.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-disk-encryption.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-ssh-key.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-user-data.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-vlan.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-vpc.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
  packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/create-linode-with-placement-groups.spec.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Addons.tsx
  packages/manager/src/features/OneClickApps/oneClickAppsv2.ts
Labels: e2e, Approved

#10904 feat: [M3-8173] - Add DisplayPrice Story
  packages/manager/.changeset/pr-10904-added-1725873382370.md
  packages/manager/src/components/DisplayPrice/DisplayPrice.stories.tsx
  packages/manager/src/components/DisplayPrice/DisplayPrice.tsx
Labels: Storybook, Approved

#10887 tech story: [M3-8423] - Resolve "Incomplete string escape or encoding" in generate-ansibleConfig.test.ts
  packages/manager/.changeset/pr-10887-tech-stories-1725467686328.md
  packages/manager/src/utilities/codesnippets/generate-ansibleConfig.test.ts
  packages/manager/src/utilities/codesnippets/generate-ansibleConfig.ts
Labels: Approved, Ready for Review

#10852 test: [M3-7971] - Add new tests for for selecting "All" Scopes
  packages/manager/.changeset/pr-10852-tests-1724937535185.md
  packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts
  packages/manager/cypress/e2e/core/parentChild/token-scopes.spec.ts
Labels: Approved

#10910 change: [M3-8198] - "contact support" as links in event.message
  packages/manager/.changeset/pr-10910-changed-1725910840891.md
  packages/manager/src/features/Events/EventMessage.tsx
  packages/manager/src/features/Events/EventsMessages.stories.tsx
  packages/manager/src/features/Events/FormattedEventMessage.test.tsx
  packages/manager/src/features/Events/FormattedEventMessage.tsx
  packages/manager/src/features/Events/factories/domain.tsx
  packages/manager/src/features/Events/factories/image.tsx
Labels: Approved

#10892 test: [M3-8321] - Clean up feature flag mocks
  packages/manager/.changeset/pr-10892-tests-1725546783401.md
  packages/manager/cypress/e2e/core/billing/billing-contact.spec.ts
  packages/manager/cypress/e2e/core/general/gdpr-agreement.spec.ts
  packages/manager/cypress/e2e/core/helpAndSupport/close-support-ticket.spec.ts
  packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts
  packages/manager/cypress/e2e/core/helpAndSupport/support-tickets-landing-page.spec.ts
  packages/manager/cypress/e2e/core/images/create-image.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-landing-page.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-region-select.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-dc-specific-pricing.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-disk-encryption.spec.ts
  packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/access-keys.smoke.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.smoke.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/create-placement-groups.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/placement-groups-linode-assignment.spec.ts
Labels: Approved

#10825 test: [M3-7287] - Add new test for the NodeBalancer Create flow for multiple nodes and multiple configs
  packages/manager/.changeset/pr-10825-tests-1724428903440.md
  packages/manager/cypress/e2e/core/nodebalancers/nodebalancers-create-in-complex-form.spec.ts
Labels: Approved

#10868 upcoming: [M3-8420] – Add conditionally-displayed reboot notice on Volume Create page
  packages/manager/.changeset/pr-10868-upcoming-features-1725546685590.md
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/src/features/Volumes/VolumeCreate.tsx
Labels: Approved, Block Storage Encryption (BSE)

#10909 upcoming: [M3-8549] – BSE tooltip copy update & add "Encrypt Volume" checkbox in Attach Volume drawer
  packages/manager/.changeset/pr-10909-tests-1725903174019.md
  packages/manager/.changeset/pr-10909-upcoming-features-1725903122030.md
  packages/manager/src/components/Encryption/constants.tsx
  packages/manager/src/features/Volumes/AttachVolumeDrawer.test.tsx
  packages/manager/src/features/Volumes/AttachVolumeDrawer.tsx
Labels: Approved, Block Storage Encryption (BSE)

#10913 fix: [M3-8553] - DisplayPrice story crash when Currency component's `minimumFractionDigits` is negative
  packages/manager/.changeset/pr-10913-fixed-1725955539025.md
  packages/manager/src/components/Currency/Currency.test.tsx
  packages/manager/src/components/Currency/Currency.tsx
Labels: Bug, Approved

#10905 feat: [M3-8171] - Add CheckoutSummary Story
  packages/manager/.changeset/pr-10905-added-1725893781288.md
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.stories.tsx
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
Labels: Storybook

#10859 feat: [M3-8158] - Begin to sunset Gravatar
  packages/manager/.changeset/pr-10859-added-1725550540714.md
  packages/manager/.changeset/pr-10859-changed-1725550568902.md
  packages/manager/src/assets/logo/akamai-wave.svg
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/components/Avatar/Avatar.stories.tsx
  packages/manager/src/components/Avatar/Avatar.test.tsx
  packages/manager/src/components/Avatar/Avatar.tsx
  packages/manager/src/components/AvatarForProxy.tsx
  packages/manager/src/components/ColorPicker/ColorPicker.stories.tsx
  packages/manager/src/components/ColorPicker/ColorPicker.tsx
  packages/manager/src/components/GravatarByEmail.tsx
  packages/manager/src/components/GravatarByUsername.tsx
  packages/manager/src/components/GravatarOrAvatar.tsx
  packages/manager/src/features/Events/EventRow.styles.ts
  packages/manager/src/features/Events/EventRow.test.tsx
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx
  packages/manager/src/features/GlobalNotifications/GravatarSunsetBanner.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Security.test.tsx
  packages/manager/src/features/NotificationCenter/Events/NotificationCenterEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationCenter.styles.ts
  packages/manager/src/features/Profile/DisplaySettings/AvatarColorPickerDialog.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/AvatarColorPickerDialog.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/Support/ExpandableTicketPanel.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/Users/UserRow.tsx
  packages/manager/src/hooks/useGravatar.ts
  packages/manager/src/types/ManagerPreferences.ts
  packages/manager/src/utilities/gravatar.ts
Labels: Approved

#10911 test: [M3-8555] - Add unit tests for NodeBalancersLanding package
  packages/manager/.changeset/pr-10911-tests-1725912717549.md
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.test.tsx
Labels: Approved, Ready for Review, Unit tests

#10919 fix: [M3-8158] - Fix inaccurate Gravatar sunset banner date and rendering for users without Gravatar
  packages/manager/src/features/GlobalNotifications/GravatarSunsetBanner.tsx
Labels: Approved

#10912 feat: [M3-8172] - Add CopyableTextField story and clean up components
  packages/manager/.changeset/pr-10912-added-1725913446437.md
  packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
  packages/manager/src/components/CopyableAndDownloadableTextField.tsx
  packages/manager/src/components/CopyableTextField/CopyableTextField.stories.tsx
  packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
  packages/manager/src/components/DownloadTooltip.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx
  packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
Labels: Storybook, Approved

#10920 fix: [M3-8563 & M3-8566] – Fix BSE capability for linodes & prevent unnecessary API request on Volume Create page
  packages/api-v4/.changeset/pr-10920-added-1726070878408.md
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-10920-upcoming-features-1726068029277.md
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeAddDrawer.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeAttachForm.tsx
Labels: Approved, Block Storage Encryption (BSE)

#10923 fix: [M3-8158] - Render the correct Avatar icon for `ACTIONS_WITHOUT_USERNAMES`
  packages/manager/.changeset/pr-10923-fixed-1726086511137.md
  packages/manager/src/features/NotificationCenter/Events/NotificationCenterEvent.tsx
Labels: Bug, Approved

#10921 refactor: [M3-8571] - Use Linode Create v2 at all times (remove `linodeCreateRefactor` feature flag)
  packages/manager/.changeset/pr-10921-tech-stories-1726073448179.md
  packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/index.tsx
Labels: Approved

#10918 fix: API Tokens Table Style Regression
  packages/manager/.changeset/pr-10918-fixed-1726068911721.md
  packages/manager/src/features/Profile/APITokens/APITokenTable.styles.ts
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
Labels: Bug, UX/UI, Approved

#10926 test: [M3-8517] - Cloud changes for component test CI
  Jenkinsfile-component-tests.groovy
  docker-compose.yml
  package.json
  packages/manager/.changeset/pr-10926-tests-1726156342482.md
  packages/manager/cypress.config.ts
  packages/manager/cypress/component/poc/region-select.spec.tsx
  packages/manager/cypress/support/component/index.html
  packages/manager/cypress/support/component/setup.tsx
  packages/manager/cypress/support/plugins/junit-report.ts
  packages/manager/package.json
Labels: Approved

#10928 change: Use loading icon to indicate tax id is being verified
  packages/manager/.changeset/pr-10928-removed-1726148104546.md
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/queries/account/account.ts
Labels: Approved

#10915 test: [M3-8316,M3-8317] - Tag cypress tests by adding the "method:e2e" and "purpose:dcTesting"
  packages/manager/.changeset/pr-10915-tests-1725992312603.md
  packages/manager/cypress/e2e/core/account/account-logout.spec.ts
  packages/manager/cypress/e2e/core/account/service-transfer.spec.ts
  packages/manager/cypress/e2e/core/domains/smoke-clone-domain.spec.ts
  packages/manager/cypress/e2e/core/domains/smoke-create-domain-records.spec.ts
  packages/manager/cypress/e2e/core/domains/smoke-create-domain.spec.ts
  packages/manager/cypress/e2e/core/domains/smoke-delete-domain.spec.ts
  packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/delete-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
  packages/manager/cypress/e2e/core/general/account-activation.spec.ts
  packages/manager/cypress/e2e/core/general/smoke-deep-link.spec.ts
  packages/manager/cypress/e2e/core/images/create-image.spec.ts
  packages/manager/cypress/e2e/core/images/search-images.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/rescue-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/switch-linode-state.spec.ts
  packages/manager/cypress/e2e/core/linodes/update-linode-labels.spec.ts
  packages/manager/cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
  packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/clone-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/delete-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/resize-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/search-volumes.spec.ts
  packages/manager/cypress/e2e/core/volumes/update-volume.spec.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: Approved

#10932 test: Remove committed Cypress screenshots, simplify .gitignore rules
  .gitignore
  packages/manager/cypress/screenshots/smoke-visual-icons.spec.ts/record-Docs-View-1440-900.png
  packages/manager/cypress/screenshots/smoke-visual-icons.spec.ts/record-Running-Total-1440-900.png
  packages/manager/cypress/screenshots/smoke-visual-icons.spec.ts/record-linode-offline-1440-900.png
  packages/manager/cypress/screenshots/smoke-visual-icons.spec.ts/record-linode-running-1440-900.png
Labels: Ready for Review, Clean Up, Missing Changeset

#10934 tech story: [M3-8386] - Update storybook to take care of tar vulnerability
  packages/manager/.changeset/pr-10934-tech-stories-1726237837582.md
  packages/manager/package.json
  yarn.lock
Labels: Storybook, Approved

#10780 refactor: [M3-6908] - Replace react-select in Profile
  packages/manager/.changeset/pr-10780-tech-stories-1724255560445.md
  packages/manager/cypress/e2e/core/account/security-questions.spec.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/Autocomplete/Autocomplete.styles.tsx
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/Question.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/QuestionAndAnswerPair.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
  packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
  packages/manager/src/features/Profile/Profile.tsx
Labels: Add'tl Approval Needed, Ready for Review

#10906 feat: [M3-8326], [M3-8055] - Create Linode - Create Using Command Line A/B Test
  packages/manager/.changeset/pr-10906-added-1726196972242.md
  packages/manager/src/components/EmptyLandingPageResources/ResourcesLinks.tsx
  packages/manager/src/components/EmptyLandingPageResources/ResourcesLinksTypes.ts
  packages/manager/src/constants.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Actions.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/AnsibleIntegrationResources.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/CurlTabPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/GoSDKResources.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/IntegrationsTabPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/LinodeCLIPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/PythonSDKResources.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/SDKTabPanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/TerraformIntegrationResources.tsx
  packages/manager/src/features/Linodes/LinodesCreate/CodeBlock/CodeBlock.styles.ts
  packages/manager/src/features/Linodes/LinodesCreate/CodeBlock/CodeBlock.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Labels: Add'tl Approval Needed

#10908 fix: [M3-7574] - Fix missing labels for User Permission radio buttons
  packages/manager/.changeset/pr-10908-fixed-1726091771498.md
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
Labels: Accessibility, Approved

#10823 feat: [UIE-8002] - DBaaS 2.0 Landing Page
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/databases/types.ts
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-10823-upcoming-features-1724867496417.md
  packages/manager/src/__data__/regionsData.ts
  packages/manager/src/assets/icons/db-logo-white.svg
  packages/manager/src/components/EmptyLandingPageResources/ResourcesLinksTypes.ts
  packages/manager/src/components/EmptyLandingPageResources/ResourcesSection.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
  packages/manager/src/factories/account.ts
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseStatusDisplay.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingEmptyStateData.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/features/GlobalNotifications/DatabaseClusterInfoBanner.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: DBaaS, Approved

#10922 fix: [M3-8572] - Scrollbar showing briefly on Splash Screen
  packages/manager/.changeset/pr-10922-fixed-1726078413547.md
  packages/manager/src/components/SplashScreen.tsx
  packages/manager/src/index.css
  packages/manager/src/utilities/accessibility.ts
Labels: Bug, Approved

#10924 fix: [M3-8161] - Fix misaligned DNS banner text
  packages/manager/.changeset/pr-10924-fixed-1726085139068.md
  packages/manager/src/features/Domains/DomainBanner.tsx
Labels: Approved

#10917 test: [M3-8544, M3-8545] - Add unit tests for Dialog and DeletionDialog components
  packages/manager/.changeset/pr-10917-tests-1726061618551.md
  packages/manager/src/components/DeletionDialog/DeletionDialog.test.tsx
  packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
  packages/manager/src/components/Dialog/Dialog.test.tsx
Labels: Approved, Unit tests

#10938 fix: [M3-7149] - Fix textfield tooltip icon focus area
  packages/manager/.changeset/pr-10938-fixed-1726262803311.md
  packages/manager/src/components/TextField.tsx
Labels: Approved

#10903 upcoming: [DI-20709] - CSS updates for widget level filters for ACLP
  packages/manager/.changeset/pr-10903-upcoming-features-1725857694589.md
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.test.tsx
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.test.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
  packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
Labels: Approved, CloudPulse

#10947 fix: [M3-8589] - Flickering on the user profile page when updating the currently signed in user's username
  packages/manager/.changeset/pr-10947-fixed-1726507951785.md
  packages/manager/src/queries/account/users.ts
Labels: Bug, Approved

#10930 feat: [M3-8570] - Finish sunsetting Gravatar
  packages/manager/.changeset/pr-10930-removed-1726159393499.md
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/components/Avatar/Avatar.test.tsx
  packages/manager/src/components/Avatar/Avatar.tsx
  packages/manager/src/components/GravatarByEmail.tsx
  packages/manager/src/components/GravatarByUsername.tsx
  packages/manager/src/components/GravatarOrAvatar.tsx
  packages/manager/src/features/Events/EventRow.styles.ts
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/Events/utils.test.tsx
  packages/manager/src/features/Events/utils.tsx
  packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx
  packages/manager/src/features/GlobalNotifications/GravatarSunsetBanner.tsx
  packages/manager/src/features/NotificationCenter/Events/NotificationCenterEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationCenter.styles.ts
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/Support/ExpandableTicketPanel.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/Users/UserRow.tsx
  packages/manager/src/hooks/useGravatar.ts
  packages/manager/src/utilities/gravatar.ts
Labels: Approved

#10944 change: [M3-8552] - eslint - mark formik as deprecated
  docs/development-guide/05-fetching-data.md
  docs/development-guide/15-composition.md
  packages/manager/.changeset/pr-10944-changed-1726505494539.md
  packages/manager/.eslintrc.cjs
  packages/manager/package.json
  yarn.lock
Labels: Approved

#10945 test: [M3-8565] - Add unit tests for rest of NodeBalancers package
  packages/manager/.changeset/pr-10945-tests-1726507532580.md
  packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDeleteDialog.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerPassiveCheck.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerSelect.test.tsx
Labels: Approved, Unit tests

#10955 tech story: Update dompurify and jsPDF to fix dependabot alert
  packages/manager/.changeset/pr-10955-tech-stories-1726591613226.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved

#10948 fix: [M3-8422] - Linode IPv6 rDNS typo
  packages/manager/.changeset/pr-10948-fixed-1726517375013.md
  packages/manager/src/components/LinkButton.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.tsx
Labels: Bug, Approved

#10939 feat: [UIE-8007] - DBaaS enhancements summary and settings
  packages/api-v4/.changeset/pr-10939-upcoming-features-1726263534115.md
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-10939-upcoming-features-1726263444178.md
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/validation/src/databases.schema.ts
Labels: DBaaS, Approved

#10965 fix: Marketplace Apache Spark Cluster URL Slug
  packages/manager/.changeset/pr-10965-fixed-1726675687897.md
  packages/manager/src/features/OneClickApps/oneClickAppsv2.ts
Labels: Marketplace, Approved

#10960 chore: bump vite to 5.4.6
  packages/api-v4/package.json
  packages/manager/.changeset/pr-10960-tech-stories-1726671382649.md
  packages/manager/package.json
  packages/search/package.json
  yarn.lock
Labels: Dependencies, Approved

#10963 change: [M3-8599] - Disable 'Save' button in Change Avatar Color dialog until color is changed
  packages/manager/.changeset/pr-10963-changed-1726672295505.md
  packages/manager/src/features/Profile/DisplaySettings/AvatarColorPickerDialog.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/AvatarColorPickerDialog.tsx
Labels: Approved

#10954 change: [M3-8593] - Copy updates in Create with CLI modal
  packages/manager/.changeset/pr-10954-changed-1726591307327.md
  packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/AnsibleIntegrationResources.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/TerraformIntegrationResources.tsx
Labels: Approved

#10942 feat: [M3-8185] - Add Accessibility tab to Storybook Stories
  packages/manager/.changeset/pr-10942-added-1726774387695.md
  packages/manager/.storybook/main.ts
  packages/manager/package.json
  yarn.lock
Labels: Accessibility, Storybook

#10951 upcoming: [DI-20800] - CSS for widget size control and feedbacks
  packages/manager/.changeset/pr-10951-upcoming-features-1726561825358.md
  packages/manager/src/assets/icons/arrow_down.svg
  packages/manager/src/assets/icons/arrow_right.svg
  packages/manager/src/assets/icons/refresh.svg
  packages/manager/src/assets/icons/zoomin.svg
  packages/manager/src/assets/icons/zoomout.svg
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.test.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.test.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx
  packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, CloudPulse

#10966 test: [M3-8591, M3-8594] - Add unit tests for AccountActivationLanding component, remove AddNewLink component
  packages/manager/.changeset/pr-10966-removed-1726765827523.md
  packages/manager/.changeset/pr-10966-tests-1726678346834.md
  packages/manager/src/components/AccountActivation/AccountActivationLanding.test.tsx
  packages/manager/src/components/AccountActivation/AccountActivationLanding.tsx
  packages/manager/src/components/AddNewLink/AddNewLink.tsx
  packages/manager/src/components/AddNewLink/index.ts
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
  packages/manager/src/features/Managed/Contacts/Contacts.tsx
  packages/manager/src/features/Managed/Credentials/CredentialList.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTable.tsx
  packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
  packages/manager/src/features/Users/UsersLanding.tsx
Labels: Approved, Unit tests

#10978 fix: [M3-8617] - Autocomplete Popper re-rendering causing test failures
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
Labels: Testing, Bug

#10973 upcoming: [M3-8604] – Update URL for Volume Encryption guide
  packages/manager/.changeset/pr-10973-upcoming-features-1726768912614.md
  packages/manager/src/components/Encryption/constants.tsx
Labels: Approved, Block Storage Encryption (BSE)

#10975 test: [M3-8616] - Fix failures in DBaaS update tests
  docs/development-guide/09-mocking-data.md
  packages/manager/cypress/e2e/core/databases/update-database.spec.ts
Labels: DBaaS, Approved, Ready for Review

#10858 change: [M3-8377, M3-8579] - Move Region section above Images in Linode Create and update default OS to Ubuntu 24.04 LTS
  packages/manager/.changeset/pr-10858-changed-1725914163062.md
  packages/manager/cypress/e2e/core/linodes/create-linode-mobile.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscripts.spec.ts
  packages/manager/cypress/support/util/linodes.ts
  packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Clone/Clone.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/Marketplace.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/OperatingSystems.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/StackScripts.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/IntegrationsTabPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/SDKTabPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/store/image/image.helpers.test.ts
  packages/manager/src/store/image/image.helpers.ts
Labels: UX/UI, Approved

#10976 fix: [M3-8602] - Fix `plan-selection.spec.ts` test failures on retries
  packages/manager/.changeset/pr-10976-tests-1726778238574.md
  packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts
Labels: Ready for Review

#10959 change: [M3-6838] - Better "Backups Enabled" default when cloning Linode
  packages/manager/.changeset/pr-10959-changed-1726660002249.md
  packages/manager/src/features/Linodes/LinodeCreatev2/shared/LinodeSelectTable.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts
Labels: Approved, Linodes

#10940 change: [M3-7679] - Update VPC Assigned Linodes table header
  packages/manager/.changeset/pr-10940-changed-1726472458540.md
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
Labels: Approved

#10931 fix: [M3-7571] - Missing label for Full Account Access Toggle
  packages/manager/.changeset/pr-10931-fixed-1726172174760.md
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/src/features/Users/UserPermissions.styles.ts
  packages/manager/src/features/Users/UserPermissions.tsx
Labels: Accessibility, Approved

#10983 test: [M3-8619] - Fix Cypress test flake in `create-linode-from-image.spec.ts`
  packages/manager/.changeset/pr-10983-tests-1726865807776.md
  packages/manager/cypress/support/ui/autocomplete.ts
Labels: Ready for Review

#10981 test: [M3-8601] - Fix NodeBalancer `nodebalancers-create-in-complex-form.spec.ts` Cypress test flake
  packages/manager/.changeset/pr-10981-tests-1726863454562.md
  packages/manager/cypress/e2e/core/nodebalancers/nodebalancers-create-in-complex-form.spec.ts
Labels: Approved

#10916 test: [M3-8556] - Add unit tests for NodeBalancer details package
  packages/manager/.changeset/pr-10916-tests-1726065357292.md
  packages/manager/src/factories/nodebalancer.ts
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDeleteDialog.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerFirewalls.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerFirewalls.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerFirewallsActionMenu.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerFirewallsRow.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerFirewallsRow.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/NodeBalancerSummary.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerPassiveCheck.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.test.tsx
  packages/manager/src/utilities/testHelpers.tsx
Labels: Approved, Unit tests

#10962 fix: [M3-8508] - Cancel Button Not Functioning in Delete Node Balancer Configuration Dialog
  packages/manager/.changeset/pr-10962-fixed-1726688754577.md
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
Labels: Approved

#10990 chore: Update `husky` to latest
  .husky/pre-commit
  package.json
  packages/manager/.changeset/pr-10990-tech-stories-1727187564566.md
  yarn.lock
Labels: Dependencies

#10985 change: [M3-8622] - Update Images empty state as part of Image Service Gen2
  packages/manager/.changeset/pr-10985-changed-1727105394355.md
  packages/manager/cypress/e2e/core/images/images-empty-landing-page.spec.ts
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLandingEmptyStateData.ts
Labels: Image Service Gen2

#10987 upcoming: [M3-8624] - Update Region description helper text
  packages/manager/.changeset/pr-10987-upcoming-features-1727113889522.md
  packages/manager/src/components/SelectRegionPanel/RegionHelperText.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.tsx
Labels: Gecko LA

#10999 test: [M3-8395] - Fix Linode delete test flake by fixing deletion assertion
  packages/manager/.changeset/pr-10999-tests-1727196449912.md
  packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
Labels: Ready for Review

#10927 fix: [M3-8519] - Objects Table Refreshing Logic
  packages/manager/.changeset/pr-10927-fixed-1726139552414.md
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/queries/object-storage/queries.ts
Labels: Object Storage, Approved

#10970 fix: [M3-8578] - Fix console error on Volume Create - Linode Config selection
  packages/manager/.changeset/pr-10970-fixed-1726762187663.md
  packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx
Labels: Approved

#10998 fix: [M3-8657] - Set full height to DX Tools Modal and add Linode API link
  packages/manager/.changeset/pr-10998-fixed-1727195767338.md
  packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
Labels: Approved

#10993 fix: [UIE-8150] - DBaaS empty landing page show logo for V2
  packages/manager/.changeset/pr-10993-fixed-1727189409908.md
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
Labels: DBaaS, Approved

#10989 fix: [UIE-8007] - DBaaS Summary tab display correct user and readonly host
  packages/api-v4/.changeset/pr-10989-fixed-1727118907870.md
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-10989-fixed-1727118993352.md
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Labels: DBaaS

#10986 change: [M3-8614] - Update Image Upload dropzone copy as part of Image Service Gen2
  packages/manager/.changeset/pr-10986-changed-1727108550951.md
  packages/manager/src/components/Uploaders/ImageUploader/ImageUploader.test.tsx
  packages/manager/src/components/Uploaders/ImageUploader/ImageUploader.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.tsx
Labels: Approved, Image Service Gen2

#10980 fix: [UIE-8146] - DBaaS V2 bug fix
  packages/api-v4/.changeset/pr-10980-changed-1726868220865.md
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-10980-fixed-1726845381695.md
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseStatusDisplay.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseStatusDisplay.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/validation/.changeset/pr-10980-changed-1726868115893.md
  packages/validation/src/databases.schema.ts
Labels: DBaaS, Approved

#10988 fix: [UIE-8009] - DBaaS backups disable invalid dates
  packages/api-v4/.changeset/pr-10988-changed-1727197910740.md
  packages/api-v4/src/databases/databases.ts
  packages/manager/.changeset/pr-10988-fixed-1727119069361.md
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreLegacyFromBackupDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreNewFromBackupDialog.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/queries/databases/databases.ts
Labels: DBaaS, Approved

#11001 fix: [M3-8661] - Fix crash in Volume Create page caused by misconfigured Autocomplete
  packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx
Labels: Bug

#10995 fix: [UIE-8152] - DBaaS V2 Resize: disable Shared plans tab
  packages/manager/.changeset/pr-10995-fixed-1727190775726.md
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
Labels: DBaaS

#10956 feat: [M3-8581] - GPUv2 Plan Selection Egress Banner
  packages/manager/.changeset/pr-10956-added-1727103260742.md
  packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
Labels: Approved

#11010 fix: [UIE-8157] - DBaaS type call requires X-Filter
  packages/manager/.changeset/pr-11010-fixed-1727359551617.md
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/queries/databases/databases.ts
  packages/manager/src/queries/databases/requests.ts
Labels: DBaaS, Approved

#11009 chore: [M3-8662] - Update Github Actions actions
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/coverage_badge.yml
  .github/workflows/coverage_comment.yml
  .github/workflows/docs.yml
  .github/workflows/e2e_schedule_and_push.yml
  .github/workflows/security_scan.yml
  packages/manager/.changeset/pr-11009-tech-stories-1727310949305.md
Labels: Dependencies

#11008 fix: [M3-8424] - Fix CodeQL alerts for `DOM text reinterpreted as HTML`
  packages/manager/.changeset/pr-11008-fixed-1727297819528.md
  packages/manager/src/session.ts
  packages/manager/src/store/authentication/authentication.requests.ts
Labels: Security

#11007 fix: [M3-8588] - Fix `value` selection issue in `ImageSelect`
  packages/manager/.changeset/pr-11007-fixed-1727295720802.md
  packages/manager/src/features/Images/ImageSelect.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateDiskDrawer.tsx
  packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
  packages/validation/.changeset/pr-11007-changed-1727366867981.md
  packages/validation/src/linodes.schema.ts
Labels: Bug, Approved

#11012 feat: [M3-8174] - Add Linode Empty Landing story
  packages/manager/.changeset/pr-11012-added-1727369897345.md
  packages/manager/src/components/EmptyLandingPageResources/ResourcesSection.stories.tsx
Labels: Storybook, Approved

#11005 chore: [M3-8524] - Attempt to get dependencies in a more healthy state
  package.json
  packages/api-v4/package.json
  packages/manager/.changeset/pr-11005-tech-stories-1727294313614.md
  packages/manager/cypress/vite.config.ts
  packages/manager/package.json
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Firewall.test.tsx
  packages/manager/src/features/Linodes/LinodeCreatev2/Security.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResizeUnifiedMigrationPanel.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsUnassignModal.tsx
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/manager/src/foundations/themes/light.ts
  packages/manager/src/mocks/utilities/response.ts
  packages/manager/src/store/selectors/reselect-tools.d.ts
  packages/manager/vite.config.ts
  packages/validation/package.json
  packages/validation/src/vpcs.schema.ts
  yarn.lock
Labels: Dependencies, Approved

#11011 chore: Clean up unused assets & icons
  packages/manager/.changeset/pr-11011-tech-stories-1727369421760.md
  packages/manager/src/assets/community.svg
  packages/manager/src/assets/icons/accepted-cards.svg
  packages/manager/src/assets/icons/activeRowCaret.svg
  packages/manager/src/assets/icons/bell.svg
  packages/manager/src/assets/icons/bell_new.svg
  packages/manager/src/assets/icons/book.svg
  packages/manager/src/assets/icons/bucketBreadcrumb.svg
  packages/manager/src/assets/icons/circle.svg
  packages/manager/src/assets/icons/clock.svg
  packages/manager/src/assets/icons/cloudUpload.svg
  packages/manager/src/assets/icons/cloudpulse.svg
  packages/manager/src/assets/icons/collapse.svg
  packages/manager/src/assets/icons/console.svg
  packages/manager/src/assets/icons/cpu-icon.svg
  packages/manager/src/assets/icons/delete.svg
  packages/manager/src/assets/icons/details.svg
  packages/manager/src/assets/icons/disk.svg
  packages/manager/src/assets/icons/edit.svg
  packages/manager/src/assets/icons/entityIcons/cv_overview.svg
  packages/manager/src/assets/icons/entityIcons/kubernetes_2.svg
  packages/manager/src/assets/icons/entityIcons/loading.svg
  packages/manager/src/assets/icons/entityIcons/vlan.svg
  packages/manager/src/assets/icons/expand.svg
  packages/manager/src/assets/icons/gear.svg
  packages/manager/src/assets/icons/gift-box.svg
  packages/manager/src/assets/icons/info2.svg
  packages/manager/src/assets/icons/invoice.svg
  packages/manager/src/assets/icons/line-chart.svg
  packages/manager/src/assets/icons/managed.svg
  packages/manager/src/assets/icons/managednav.svg
  packages/manager/src/assets/icons/menu-indicator.svg
  packages/manager/src/assets/icons/minusSign.svg
  packages/manager/src/assets/icons/mobile.svg
  packages/manager/src/assets/icons/moreInfo.svg
  packages/manager/src/assets/icons/power-button.svg
  packages/manager/src/assets/icons/powerOn.svg
  packages/manager/src/assets/icons/promotion.svg
  packages/manager/src/assets/icons/ram-sticks.svg
  packages/manager/src/assets/icons/reboot.svg
  packages/manager/src/assets/icons/recycle.svg
  packages/manager/src/assets/icons/resize.svg
  packages/manager/src/assets/icons/resource.svg
  packages/manager/src/assets/icons/sort.svg
  packages/manager/src/assets/icons/sortUp.svg
  packages/manager/src/assets/icons/streamline.svg
  packages/manager/src/assets/icons/table-view.svg
  packages/manager/src/assets/icons/trash.svg
  packages/manager/src/assets/icons/user.svg
  packages/manager/src/assets/icons/viewDetails.svg
  packages/manager/src/assets/icons/volume.svg
  packages/manager/src/assets/logo/logo-footer.svg
  packages/manager/src/assets/logo/logo.svg
  packages/manager/src/assets/primary-nav-help.svg
Labels: Approved, Clean Up

#11015 chore: Fix last `path-to-regexp` depenabot alert by using `vite preview` instead of `serve`
  packages/manager/.changeset/pr-11015-tech-stories-1727465775221.md
  packages/manager/package.json
  packages/manager/src/features/Linodes/LinodeCreatev2/Security.test.tsx
  yarn.lock
Labels: Dependencies

#10853 upcoming: [DI-20360] - Updated preferences logic to remove flickering issue
  packages/api-v4/.changeset/pr-10853-upcoming-features-1725371578425.md
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-10853-upcoming-features-1725371660855.md
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardRenderer.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.test.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.test.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
  packages/manager/src/features/CloudPulse/Utils/constants.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidgetRenderer.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelectUtils.test.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelectUtils.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseErrorPlaceholder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
  packages/manager/src/queries/cloudpulse/metrics.ts
Labels: Approved, CloudPulse
