Repository linode/manager, pull requests merged in 2024-01, with the labels that each got.

#10019 refactor: [M3-7578] - Placeholder and EntityDetails v7 storybook migrations
  packages/manager/.changeset/pr-10019-tech-stories-1703256618481.md
  packages/manager/src/components/EntityDetail/.EntityDetail.stories.mdx
  packages/manager/src/components/EntityDetail/EntityDetail.stories.tsx
  packages/manager/src/components/EntityDetail/EntityDetail.test.tsx
  packages/manager/src/components/EntityDetail/EntityDetail.tsx
  packages/manager/src/components/EntityDetail/index.tsx
  packages/manager/src/components/ErrorState/ErrorState.test.tsx
  packages/manager/src/components/Placeholder/.Placeholder.stories.mdx
  packages/manager/src/components/Placeholder/Placeholder.stories.tsx
  packages/manager/src/components/Placeholder/Placeholder.test.tsx
  packages/manager/src/components/Placeholder/Placeholder.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
Labels: Storybook, Approved

#9980 test: [M3-6608] - Add Linode power off, power on and reboot tests
  packages/manager/.changeset/pr-9980-added-1701986820847.md
  packages/manager/cypress/e2e/core/linodes/switch-linode-state.spec.ts
Labels: Testing, Approved

#10023 fix: Failing `CreditCard.test.tsx` Unit Test
  packages/manager/.changeset/pr-10023-tests-1704213295558.md
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.test.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
  packages/manager/src/utilities/creditCard.test.ts
  packages/manager/src/utilities/creditCard.ts
Labels: Approved, Unit tests

#10014 upcoming: [M3-7424] - Update top menu for parent, child, and proxy accounts
  packages/manager/.changeset/pr-10014-upcoming-features-1703710696662.md
  packages/manager/src/env.d.ts
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Parent / Child Account

#9976 upcoming: [M3-7423] - Create Bucket - Able to choose a single Compute Region ID eg ('us-east')
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/object-storage/types.ts
  packages/manager/.changeset/pr-9976-upcoming-features-1702579922373.md
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/factories/objectStorage.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.styles.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/validation/src/buckets.schema.ts
Labels: Approved, OBJ Multi-Cluster

#10029 refactor: [M3-7588] - Remove `classnames` and `@types/classnames`
  packages/manager/.changeset/pr-10029-tech-stories-1704318402385.md
  packages/manager/package.json
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/components/EnhancedSelect/Select.tsx
  packages/manager/src/components/GravatarByEmail.tsx
  packages/manager/src/components/GravatarByUsername.tsx
  packages/manager/src/components/PrimaryNav/NavItem.tsx
  packages/manager/src/features/Help/Panels/SearchItem.tsx
  packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
  packages/manager/src/features/NotificationCenter/NotificationSection.tsx
  yarn.lock
Labels: Dependencies, Approved, Clean Up

#10001 upcoming: [M3-7303] - Replace Managed summary charts with Recharts
  packages/manager/.changeset/pr-10001-upcoming-features-1702680383371.md
  packages/manager/src/components/AreaChart.tsx
  packages/manager/src/components/AreaChart/AccessibleAreaChart.test.tsx
  packages/manager/src/components/AreaChart/AccessibleAreaChart.tsx
  packages/manager/src/components/AreaChart/AreaChart.stories.tsx
  packages/manager/src/components/AreaChart/AreaChart.test.tsx
  packages/manager/src/components/AreaChart/AreaChart.tsx
  packages/manager/src/components/AreaChart/utils.test.ts
  packages/manager/src/components/AreaChart/utils.ts
  packages/manager/src/components/LineGraph/AccessibleGraphData.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.styles.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedDashboardCard.styles.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedDashboardCard.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
Labels: Approved, Recharts

#9996 feat: [M3-7535] – Update OBJ types to support Multicluster changes
  packages/api-v4/.changeset/pr-9996-changed-1702508393416.md
  packages/api-v4/src/object-storage/types.ts
  packages/manager/.changeset/pr-9996-changed-1702508487859.md
  packages/manager/src/__data__/buckets.ts
  packages/manager/src/__data__/objectStorageKeys.ts
  packages/manager/src/factories/objectStorage.ts
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx
Labels: Approved, OBJ Multi-Cluster

#10025 upcoming: [M3-7455] - Add child account access column and disable button when account has child accounts
  packages/manager/.changeset/pr-10012-upcoming-features-1703090453195.md
  packages/manager/src/features/Account/CloseAccountSetting.test.tsx
  packages/manager/src/features/Account/CloseAccountSetting.tsx
  packages/manager/src/features/Users/UserRow.test.tsx
  packages/manager/src/features/Users/UserRow.tsx
  packages/manager/src/features/Users/UsersLanding.tsx
  packages/manager/src/queries/accountUsers.ts
Labels: Approved, Parent / Child Account

#10027 feat: [M3-7538] - Cloud Manager Docs with Vitepress
  .github/workflows/docs.yml
  .gitignore
  docs/.vitepress/config.ts
  docs/.vitepress/plugins/sidebar.ts
  docs/CONTRIBUTING.md
  docs/GETTING_STARTED.md
  docs/development-guide/08-testing.md
  docs/index.md
  docs/public/akamai-wave.svg
  docs/public/favicon.ico
  package.json
  packages/manager/.changeset/pr-10027-added-1704309699899.md
Labels: Approved, Documentation

#10013 feat: [M3-7373] - Sold Out Chips
  packages/manager/.changeset/pr-10013-added-1703179399644.md
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/src/components/SelectionCard/CardBase.tsx
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/constants.ts
  packages/manager/src/factories/regions.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/components/PlansPanel/PlanContainer.styles.ts
  packages/manager/src/features/components/PlansPanel/PlanContainer.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.test.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.styles.ts
  packages/manager/src/features/components/PlansPanel/utils.test.ts
  packages/manager/src/features/components/PlansPanel/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/regions.ts
Labels: Approved, Sold Out Plans

#10020 change: [M3-7205] - Dark theme Radio & Toggle improvements
  packages/manager/.changeset/pr-10020-changed-1704231120228.md
  packages/manager/src/components/Radio/Radio.stories.tsx
  packages/manager/src/components/Radio/Radio.tsx
  packages/manager/src/components/Toggle/Toggle.stories.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResizeUnifiedMigrationPanel.tsx
  packages/manager/src/foundations/themes/dark.ts
Labels: Approved

#10028 feat: [M3-7589] - Improve Accessibility of Button Component
  packages/manager/.changeset/pr-10028-tech-stories-1704319234636.md
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/cypress/support/e2e.ts
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/components/Button/Button.stories.tsx
  packages/manager/src/components/Button/Button.test.tsx
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/components/Button/StyledActionButton.ts
  packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.test.tsx
  packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx
  packages/manager/src/components/LandingHeader/LandingHeader.test.tsx
  packages/manager/src/components/Uploaders/ImageUploader/ImageUploader.test.tsx
  packages/manager/src/features/Account/CloseAccountSetting.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/EditRouteDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/EditAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetCreateDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetEditDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.test.tsx
  packages/manager/src/foundations/themes/dark.ts
  packages/manager/src/foundations/themes/light.ts
Labels: Ready for Review

#10016 fix: [M3-7521 & M3-7556 & M3-7581] - Update AGLB Service Target Validation & Fix Route Rules being cleared
  packages/api-v4/src/aglb/types.ts
  packages/manager/.changeset/pr-10016-fixed-1703172060704.md
  packages/manager/.changeset/pr-10016-fixed-1703172108441.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-service-targets.spec.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ServiceTargetForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerServiceTargets.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/EditRouteDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/MatchTypeInfo.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/constants.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/utils.test.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/utils.ts
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, AGLB

#10038 feat: [M3-7563] – Add proper support for OBJ Access Key events
  packages/manager/.changeset/pr-10038-added-1704495369939.md
  packages/manager/src/features/Events/eventMessageGenerator.ts
Labels: OBJ Multi-Cluster

#10040 fix: Profile Query Keys, User Permissions loading state, and read_only PAT creation
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/utils.test.ts
  packages/manager/src/features/Profile/APITokens/utils.ts
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/queries/profile.ts
Labels: Bug, Approved

#10031 upcoming: [M3-7429] - Add Parent/Proxy 'Switch Account' button and drawer to user profile dropdown menu
  packages/manager/.changeset/pr-10031-upcoming-features-1704467384095.md
  packages/manager/src/assets/icons/swapSmall.svg
  packages/manager/src/features/Account/SwitchAccountButton.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.test.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Parent / Child Account

#10042 fix: [M3-7260] - Managed Summary layout
  packages/manager/.changeset/pr-10042-fixed-1704748141170.md
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.styles.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/ManagedDashboardCard.styles.tsx
Labels: Bug, Approved

#10045 upcoming: [M3-7463] - Disable Billing access user permission for child users
  packages/manager/.changeset/pr-10045-tests-1704834823931.md
  packages/manager/.changeset/pr-10045-upcoming-features-1704814925607.md
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/src/features/Users/UserPermissions.tsx
Labels: Approved, Parent / Child Account

#10050 fix: [M3-7625] – Update VPC docs links with published docs
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPCs/constants.ts
Labels: Approved, Hotfix, VPC

#10047 fix: [M3-7623] - Fix VPC subnet Linode assignment text input
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-linodes-update.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-navigation.spec.ts
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
Labels: Approved, Ready for Review

#10051 `staging` → `master` for Cloud v1.109.1 release
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-linodes-update.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-navigation.spec.ts
  packages/manager/package.json
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPCs/constants.ts
Labels: Release

#10048 fix: [M3-7624] - AGLB Configuration - Save button disabled when trying to remove a route
  packages/manager/.changeset/pr-10048-upcoming-features-1704822100414.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-configurations.spec.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationForm.tsx
Labels: Bug, Approved, AGLB

#9869 feat: [UIE-6937] - Add the ability to scale up DBaaS
  packages/api-v4/.changeset/pr-9869-added-1703002185530.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/databases/databases.ts
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-9869-added-1699013625860.md
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseScaleUp/DatabaseScaleUp.style.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseScaleUp/DatabaseScaleUp.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseScaleUp/DatabaseScaleUp.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseScaleUp/DatabaseScaleUpCurrentConfiguration.style.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseScaleUp/DatabaseScaleUpCurrentConfiguration.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseScaleUp/DatabaseScaleUpCurrentConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Events/constants.ts
  packages/manager/src/features/Events/eventMessageGenerator.ts
  packages/manager/src/features/components/PlansPanel/PlanContainer.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
  packages/validation/.changeset/pr-9869-changed-1703002209433.md
  packages/validation/src/databases.schema.ts
Labels: Project: DBaaS, Approved, Ready for Review

#10057 fix: [M3-7630] - Fix Kubernetes Upgrade Flow
  packages/manager/.changeset/pr-10057-fixed-1704983627685.md
  packages/manager/.changeset/pr-10057-tests-1704983693919.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/features/Kubernetes/UpgradeVersionModal.tsx
Labels: Bug, LKE, Approved

#10060 upcoming: [M3-7606] VM Placement feature flag
  packages/manager/.changeset/pr-10060-upcoming-features-1704989096198.md
  packages/manager/src/dev-tools/EnvironmentToggleTool.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/dev-tools/dev-tools.css
  packages/manager/src/featureFlags.ts
Labels: Approved, VM Placement

#10059 chore: [M3-7634] - Update `axios` to resolve `follow-redirects` dependabot alert
  packages/api-v4/package.json
  packages/manager/.changeset/pr-10059-tech-stories-1704987208139.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved

#10026 change: [M3-7583] - Update `react-waypoint` for React 18
  packages/manager/.changeset/pr-10026-tech-stories-1704298288134.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved

#9998 test: [M3-6855, M3-6876] - Add script to generate JUnit test summaries
  package.json
  packages/manager/cypress/support/plugins/configure-test-suite.ts
  packages/manager/cypress/support/plugins/junit-report.ts
  packages/manager/package.json
  scripts/junit-summary/formatters/formatter.ts
  scripts/junit-summary/formatters/github-formatter.ts
  scripts/junit-summary/formatters/json-formatter.ts
  scripts/junit-summary/formatters/slack-formatter.ts
  scripts/junit-summary/formatters/status-formatter.ts
  scripts/junit-summary/index.ts
  scripts/junit-summary/metadata/metadata.ts
  scripts/junit-summary/results/run-info.ts
  scripts/junit-summary/results/test-result.ts
  scripts/junit-summary/util/cypress.ts
  scripts/junit-summary/util/escape.ts
  scripts/junit-summary/util/index.ts
  scripts/junit-summary/util/pluralize.ts
  yarn.lock
Labels: Proof of Concept, Ready for Review

#10046 changed: [Marketplace] Deprecate 7 Marketplace apps
  packages/manager/.changeset/pr-10046-changed-1704923289933.md
  packages/manager/src/cachedData/marketplace.json
  packages/manager/src/features/OneClickApps/AppDetailDrawer.test.tsx
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Marketplace, Approved

#10054 change: SD-598 - Ticket page small refresh
  packages/manager/.changeset/pr-10054-changed-1704991179381.md
  packages/manager/src/features/Support/ExpandableTicketPanel.test.tsx
  packages/manager/src/features/Support/ExpandableTicketPanel.tsx
  packages/manager/src/features/Support/Hively.tsx
Labels: Approved

#10055 fix: [M3-7604] - Linode Detail Summary styles and cleanup
  packages/manager/src/features/Linodes/AccessTable.test.tsx
  packages/manager/src/features/Linodes/AccessTable.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailFooter.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
Labels: Bug, Approved, Ready for Review

#10032 `test`: [M3-6616] - Add tests to update/rename linode label
  packages/manager/.changeset/pr-10032-tests-1704400629879.md
  packages/manager/cypress/e2e/core/linodes/update-linode-labels.spec.ts
Labels: Approved, Missing Changeset

#10036 upcoming: [M3-7459] - Disable Contact / Billing Info for Restricted Users
  packages/manager/.changeset/pr-10036-upcoming-features-1704936534931.md
  packages/manager/src/components/Button/Button.tsx
  packages/manager/src/features/Account/constants.ts
  packages/manager/src/features/Billing/BillingDetail.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.test.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.test.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Billing/billingUtils.ts
  packages/manager/src/features/Billing/constants.ts
Labels: Approved, Ready for Review, Parent / Child Account

#10062 upcoming: [M3-7607] Placement Groups - Queries, Types, Validation, Factories and Mock Data
  packages/api-v4/src/index.ts
  packages/api-v4/src/linodes/types.ts
  packages/api-v4/src/placement-groups/index.ts
  packages/api-v4/src/placement-groups/placement-groups.ts
  packages/api-v4/src/placement-groups/types.ts
  packages/manager/.changeset/pr-10062-upcoming-features-1705355996434.md
  packages/manager/src/__data__/linodes.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/factories/index.ts
  packages/manager/src/factories/linodes.ts
  packages/manager/src/factories/placementGroups.ts
  packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/ListView.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/placementGroups.ts
  packages/validation/src/index.ts
  packages/validation/src/placement-groups.schema.ts
Labels: Placement Groups

#10008 feat: [M3-7487] - Add AGLB Endpoint Health
  packages/api-v4/.changeset/pr-10008-added-1704919102710.md
  packages/api-v4/src/aglb/configurations.ts
  packages/api-v4/src/aglb/loadbalancers.ts
  packages/api-v4/src/aglb/service-targets.ts
  packages/api-v4/src/aglb/types.ts
  packages/manager/.changeset/pr-10008-upcoming-features-1704919046550.md
  packages/manager/src/factories/aglb.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationAccordion.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationAccordionHeader.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationAccordionHeader.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationEndpointHealth.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationEndpointHealth.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/EndpointHealth.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/EndpointHealth.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerEndpointHealth.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerEndpointHealth.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerServiceTargets.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerSummary.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetEndpointHealth.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetEndpointHealth.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetRow.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerLanding.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerRow.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/aglb/configurations.ts
  packages/manager/src/queries/aglb/loadbalancers.ts
  packages/manager/src/queries/aglb/serviceTargets.ts
Labels: Approved, Ready for Review, AGLB

#10052 upcoming: [M3-7475] - Add Switch Account button to Account Landing page
  packages/manager/.changeset/pr-10052-upcoming-features-1704993330964.md
  packages/manager/src/components/LandingHeader/LandingHeader.tsx
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.test.tsx
Labels: Approved, Parent / Child Account

#10066 upcoming: [M3-7602] - Improve AGLB Configuration - Add Certificate Drawer (revision 2)
  packages/manager/.changeset/pr-10066-upcoming-features-1705422066984.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-configurations.spec.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CreateCertificateDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/AddCertificateDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/AddExistingCertificateForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/AddNewCertificateForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ApplyCertificatesDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/AddRouteDrawer.tsx
  packages/manager/src/queries/aglb/certificates.ts
  packages/validation/src/loadbalancers.schema.ts
Labels: Enhancement, AGLB

#10073 fix: [M3-7638] - Standardize Copy Icon Color Variations in CopyableTextField
  packages/manager/.changeset/pr-10073-fixed-1705544271675.md
  packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
Labels: Approved

#10069 upcoming: [M3-7462] - User Permissions: Configure Billing Account Access
  packages/manager/.changeset/pr-10069-upcoming-features-1705512789450.md
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/src/features/Users/UserDetail.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Parent / Child Account

#10071 fix: [M3-7638] - VPC arguments in Linode Create flow CLI
  packages/manager/.changeset/pr-10071-fixed-1705522697458.md
  packages/manager/src/utilities/generate-cli.test.ts
  packages/manager/src/utilities/generate-cli.ts
Labels: Bug, VPC

#10077 fix: [M3-7664] - Linode Action Buttons Incorrect Color in Dark Mode
  packages/manager/.changeset/pr-10077-fixed-1705594578246.md
  packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
Labels: Bug, Approved, Linodes

#10063 feat: [M3-7564] – Update OBJ validation
  packages/validation/.changeset/pr-10063-changed-1705088599651.md
  packages/validation/src/objectStorageKeys.schema.ts
Labels: Approved, OBJ Multi-Cluster

#10072 change: [M3-7651] - Add Clone Linode power-off notice
  packages/manager/.changeset/pr-10072-changed-1705529283172.md
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
Labels: Approved, Linodes, Linode Clone UI Updates

#10074 changed: [M3-7663] - Remove unified migrations feature flag
  packages/manager/.changeset/pr-10074-changed-1705590614132.md
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
Labels: Approved

#10065 test: [M3-7482] - Add cypress tests to add users on "Users & Grants" page
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/cypress/support/intercepts/account.ts
Labels: Testing, Approved

#10078 change: [M3-7668] - Right align chart tooltip data points
  packages/manager/.changeset/pr-10078-changed-1705616003861.md
  packages/manager/src/components/AreaChart/AreaChart.tsx
Labels: Approved, Recharts

#10068 upcoming: [M3-7609] - Placement Groups Landing Page
  packages/api-v4/src/placement-groups/types.ts
  packages/manager/.changeset/pr-10068-upcoming-features-1705596672088.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/assets/icons/entityIcons/placement-groups.svg
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/factories/placementGroups.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.styles.ts
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.tsx
  packages/manager/src/features/PlacementGroups/constants.ts
  packages/manager/src/features/PlacementGroups/index.tsx
Labels: Placement Groups

#10070 test: [M3-7498] - Add Cypress tests for Parent/Child billing page UX enhancements
  packages/manager/.changeset/pr-10070-tests-1705515017364.md
  packages/manager/.changeset/pr-10070-tests-1705515031938.md
  packages/manager/cypress/e2e/core/billing/restricted-user-billing.spec.ts
  packages/manager/cypress/support/intercepts/profile.ts
  packages/manager/cypress/support/ui/index.ts
  packages/manager/cypress/support/ui/tooltip.ts
  packages/manager/package.json
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
  packages/manager/src/components/Tooltip.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.test.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentMethods.tsx
  packages/manager/src/features/Billing/billingUtils.ts
  packages/manager/src/features/Billing/constants.ts
  yarn.lock
Labels: Approved, Parent / Child Account

#10080 upcoming: [M3-7659] - Add `user_type` to `/profile` endpoint
  packages/api-v4/.changeset/pr-10080-upcoming-features-1705618109652.md
  packages/api-v4/src/profile/types.ts
  packages/manager/.changeset/pr-10080-upcoming-features-1705618128252.md
  packages/manager/cypress/e2e/core/billing/restricted-user-billing.spec.ts
  packages/manager/src/factories/profile.ts
  packages/manager/src/features/Billing/BillingDetail.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.test.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.test.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Ready for Review, Parent / Child Account

#10079 upcoming: [M3-7599] - Update AGLB Configuration Ports Copy
  packages/manager/.changeset/pr-10079-upcoming-features-1705615366001.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/constants.tsx
Labels: Approved, Ready for Review, AGLB

#10090 refactor: [M3-7672] – Use feature flag to govern display of beta chip for VPC in PrimaryNav
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
Labels: Add'tl Approval Needed, VPC

#10091 test - Fix StackScript Test Failure due to Ubuntu 23.04 Image Deprecation
  packages/manager/.changeset/pr-10091-tests-1705938529204.md
  packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
Labels: Approved, Ready for Review

#10075 upcoming: [M3-7608]: Placement Groups Landing page empty state
  packages/manager/.changeset/pr-10075-upcoming-features-1705615244383.md
  packages/manager/src/assets/icons/entityIcons/placement-groups.svg
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLandingEmptyState.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLandingEmptyStateData.ts
  packages/manager/src/features/PlacementGroups/constants.ts
Labels: Approved, Placement Groups

#10094 test: Fix Domains landing page empty state test flake
  packages/manager/.changeset/pr-10094-tests-1705959873279.md
  packages/manager/cypress/e2e/core/domains/domains-empty-landing-page.spec.ts
Labels: Testing, Approved

#10064 upcoming: [M3-7430] - Implement Account Switching Functionality
  packages/manager/.changeset/pr-10064-upcoming-features-1705092306140.md
  packages/manager/src/assets/icons/error-state-cloud.svg
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/SwitchAccountButton.test.tsx
  packages/manager/src/features/Account/SwitchAccountButton.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.test.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.tsx
  packages/manager/src/features/Account/SwitchAccounts/ChildAccountList.test.tsx
  packages/manager/src/features/Account/SwitchAccounts/ChildAccountList.tsx
  packages/manager/src/features/Account/utils.ts
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
Labels: Approved, Parent / Child Account

#10084 feat: [M3-7665] - RegionMultiSelect Component
  packages/manager/.changeset/pr-10084-added-1705676104397.md
  packages/manager/src/components/RegionSelect/RegionMultiSelect.stories.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.test.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
  packages/manager/src/components/RegionSelect/RegionOption.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.ts
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
Labels: Add'tl Approval Needed

#10088 upcoming: [M3-7580] - Add search field to Create Linode UIs
  packages/manager/.changeset/pr-10088-upcoming-features-1705707697666.md
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel.tsx
Labels: Approved, Linodes, Linode Clone UI Updates

#10034 upcoming: [M3-7425] - OBJ MultiCluster - Add regions field in Create Access Key Flow
  packages/api-v4/src/object-storage/buckets.ts
  packages/manager/.changeset/pr-10034-upcoming-features-1704431063670.md
  packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/access-keys.smoke.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts
  packages/manager/src/components/RegionSelect/RegionMultiSelect.stories.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.test.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyMenu.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/AccessKeyRegions.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/SelectedRegionsList.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/BucketPermissionsTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/CopyAll.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/objectStorage.ts
  packages/manager/src/utilities/regions.test.ts
  packages/manager/src/utilities/regions.ts
Labels: Ready for Review, OBJ Multi-Cluster

#10101 fix: [M3-7692] - VPC Action Buttons Incorrect Color in Dark Mode
  packages/manager/.changeset/pr-10101-fixed-1706061984923.md
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.styles.ts
Labels: Bug, Approved, VPC

#10105 upcoming: [M3-7701] - Add new ACLB Logo
  packages/manager/.changeset/pr-10105-upcoming-features-1706135685745.md
  packages/manager/src/assets/icons/entityIcons/loadbalancer.svg
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Labels: Approved, ACLB

#10093 test: [M3-7483] - Add test to delete users on "Users & Grants" page
  packages/manager/.changeset/pr-10093-tests-1706031852395.md
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/cypress/support/intercepts/account.ts
Labels: Approved, Parent / Child Account

#10099 chore: Clean up some dependencies
  packages/manager/.changeset/pr-10099-tech-stories-1706059564066.md
  packages/manager/.changeset/pr-10099-tech-stories-1706059664589.md
  packages/manager/.changeset/pr-10099-tech-stories-1706059705766.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved, Clean Up

#10109 upcoming: [M3-7481] - Disable creating and editing API tokens for proxy users
  packages/manager/.changeset/pr-10109-upcoming-features-1706136926455.md
  packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts
  packages/manager/src/features/Profile/APITokens/APITokenMenu.tsx
  packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
Labels: Approved, Parent / Child Account

#10108 feat: [M3-7644] - Add VPC IPv4 address and range to Linode IP Address Table
  packages/manager/.changeset/pr-10108-added-1706218083195.md
  packages/manager/src/factories/linodeConfigInterfaceFactory.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/types.ts
Labels: VPC

#10089 feat: [M3-7641] – Support IPv4 ranges in VPC "Assign Linodes" drawer
  packages/manager/.changeset/pr-10089-added-1706135120889.md
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.style.ts
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsListTable.tsx
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
  packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPCs/constants.ts
  packages/manager/src/utilities/noneSingleOrMultipleWithChip.test.tsx
  packages/manager/src/utilities/noneSingleOrMultipleWithChip.tsx
  packages/validation/.changeset/pr-10089-changed-1706135447361.md
  packages/validation/src/linodes.schema.ts
Labels: @linode/validation, Approved, VPC

#10103 upcoming: [M3-7530] - Restrict proxy users from updating username/email
  packages/manager/.changeset/pr-10103-upcoming-features-1706069199851.md
  packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
  packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Parent / Child Account

#10116 feat: [M3-7643] – Support VPC IPv4 Ranges in Linode Create flow
  packages/manager/.changeset/pr-10116-added-1706293067938.md
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
Labels: Approved, VPC

#10018 upcoming: [M3-7296] - Create Load Balancer Summary page
  packages/manager/.changeset/pr-10018-upcoming-features-1703185915854.md
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/AddRouteDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/AddRouteDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ConfigurationDetails.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/EditRouteDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/EditRouteDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerActionPanel.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerConfiguration.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerConfiguration.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerCreate.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerCreateFormWrapper.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerLabel.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerLabel.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerRegions.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/EditConfigurationDetails/ConfigurationAccordion.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/EditConfigurationDetails/ConfigurationAccordion.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/EditConfigurationDetails/ConfigurationAccordionHeader.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/EditConfigurationDetails/ConfigurationAccordionHeader.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/EditConfigurationDetails/ConfigurationDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/EditRoutes/EditRouteDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/EditRoutes/EditRouteDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/EditRoutes/RouteAccordion.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/EditRoutes/RouteAccordionHeader.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/EditRoutes/RouteAccordionHeader.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerConfigurations/index.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerLabel/EditLoadBalancerLabelDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerLabel/index.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerLabel/index.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerRegions/EditLoadBalancerRegionsDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerRegions/index.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/EditLoadBalancerRegions/index.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/LoadBalancerSummary.styles.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerSummary/LoadBalancerSummary.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/Routes.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/Routes.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ServiceTargetDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ServiceTargetDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ServiceTargetForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ServiceTargets.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ServiceTargets.tsx
  packages/manager/src/features/LoadBalancers/index.tsx
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, ACLB

#10076 upcoming: [M3-7460] - Child View: Users & Grants page
  packages/manager/.changeset/pr-10076-upcoming-features-1705592122151.md
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/src/components/Button/Button.test.tsx
  packages/manager/src/features/Account/CloseAccountSetting.test.tsx
  packages/manager/src/features/Account/CloseAccountSetting.tsx
  packages/manager/src/features/Account/constants.ts
  packages/manager/src/features/Users/UserDetail.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Users/UserRow.test.tsx
  packages/manager/src/features/Users/UserRow.tsx
  packages/manager/src/features/Users/UsersActionMenu.tsx
  packages/manager/src/features/Users/UsersLanding.tsx
  packages/manager/src/features/Users/UsersLandingProxyTableHead.tsx
  packages/manager/src/features/Users/UsersLandingTableBody.tsx
  packages/manager/src/features/Users/UsersLandingTableHead.tsx
Labels: Approved, Parent / Child Account

#10107 upcoming: [M3-7699] - Put newly created ACLB Rules at the top of the table upon creation
  packages/manager/.changeset/pr-10107-upcoming-features-1706135635175.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx
Labels: Approved, ACLB

#10112 upcoming: [M3-7707] - Change AGLB Rule Execution Order Column Header and Values
  packages/manager/.changeset/pr-10112-upcoming-features-1706218217394.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RuleRow.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.tsx
Labels: Approved, ACLB

#10098 upcoming: [M3-7670] - Add and handle ACLB Account Capability
  packages/api-v4/.changeset/pr-10098-upcoming-features-1706043741908.md
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-10098-upcoming-features-1706043816494.md
  packages/manager/src/GoTo.tsx
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/LoadBalancers/utils.ts
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
  packages/manager/src/queries/images.ts
  packages/manager/src/utilities/accountCapabilities.test.ts
  packages/manager/src/utilities/accountCapabilities.ts
Labels: Approved, ACLB

#10121 change: [M3-7715] - Remove `kubernetesDashboardAvailability` feature flag
  packages/manager/.changeset/pr-10121-tech-stories-1706560897746.md
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/queries/kubernetes.ts
Labels: LKE, Approved, Clean Up

#10115 upcoming: [M3-7693] - Rename `Akamai Global Load Balancer` to `Akamai Cloud Load Balancer`
  packages/api-v4/src/aglb/certificates.ts
  packages/api-v4/src/aglb/configurations.ts
  packages/api-v4/src/aglb/loadbalancers.ts
  packages/api-v4/src/aglb/routes.ts
  packages/api-v4/src/aglb/service-targets.ts
  packages/api-v4/src/aglb/types.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-certificates.spec.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-configurations.spec.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-landing-page.spec.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-navigation.spec.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-service-targets.spec.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-summary.spec.ts
  packages/manager/cypress/support/intercepts/load-balancers.ts
  packages/manager/src/GoTo.tsx
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/AddRouteDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ConfigurationDetails.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/EditRouteDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerBasicCreate.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerCreate.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerCreateFormWrapper.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/Routes.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ServiceTargetForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/constants.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/AddCertificateDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/constants.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerDetail.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/constants.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/constants.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerEmptyStateData.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerLanding.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerLandingEmptyState.tsx
  packages/manager/src/features/LoadBalancers/constants.ts
  packages/manager/src/features/LoadBalancers/index.tsx
  packages/manager/src/features/LoadBalancers/utils.ts
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.test.tsx
  packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/aglb/configurations.ts
  packages/manager/src/queries/aglb/loadbalancers.ts
  packages/manager/src/queries/aglb/serviceTargets.ts
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, ACLB

#10035 upcoming: [M3-7294] - AGLB Full Create Flow - Add Rule Support to Routes
  packages/manager/.changeset/pr-10035-upcoming-features-1705441915646.md
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerConfiguration.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerConfigurations.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/Routes.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/RuleDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/RulesTable.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RuleRow.tsx
  packages/manager/src/queries/aglb/loadbalancers.ts
  packages/validation/src/loadbalancers.schema.ts
Labels: Add'tl Approval Needed, ACLB

#10085 upcoming: [M3-7476] - Add Verification Banner for Child Accounts
  packages/manager/.changeset/pr-10085-upcoming-features-1706069396819.md
  packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx
  packages/manager/src/features/GlobalNotifications/VerificationDetailsBanner.test.tsx
  packages/manager/src/features/GlobalNotifications/VerificationDetailsBanner.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/Answer.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/QuestionAndAnswerPair.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/SecurityQuestions.tsx
  packages/manager/src/queries/securityQuestions.ts
Labels: Approved, Parent / Child Account

#10119 change: [M3-7710] - Table Collapsible row icon orientation
  packages/manager/.changeset/pr-10119-changed-1706549896002.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts
  packages/manager/src/components/CollapsibleTable/CollapsibleRow.tsx
Labels: Approved

#10106 upcoming: [M3-7614] - Placement Groups Create/Rename Drawers
  packages/api-v4/src/placement-groups/placement-groups.ts
  packages/api-v4/src/placement-groups/types.ts
  packages/manager/.changeset/pr-10106-upcoming-features-1706544198124.md
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/factories/placementGroups.ts
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDrawerContent.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDrawerContent.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsRenameDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsRenameDrawer.tsx
  packages/manager/src/features/PlacementGroups/index.tsx
  packages/manager/src/features/PlacementGroups/types.ts
  packages/manager/src/features/PlacementGroups/utils.test.ts
  packages/manager/src/features/PlacementGroups/utils.ts
  packages/manager/src/hooks/useFormValidateOnChange.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/placementGroups.ts
  packages/validation/src/placement-groups.schema.ts
Labels: Approved, Placement Groups

#10095 feat: [M3-7490] - Improve NodeBalancer Restricted User Experience
  packages/manager/.changeset/pr-10095-tech-stories-1706069306820.md
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/components/Button/StyledTagButton.stories.tsx
  packages/manager/src/components/Button/StyledTagButton.ts
  packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.styles.ts
  packages/manager/src/components/TagsPanel/TagsPanel.tsx
  packages/manager/src/features/Account/constants.ts
  packages/manager/src/features/Account/types.ts
  packages/manager/src/features/Account/utils.ts
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
  packages/manager/src/hooks/useIsResourceRestricted.ts
Labels: Ready for Review, Restricted User Access

#10129 Release v1.110.1 - `staging` → `master`
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
Labels: Release

#10131 Release v1.110.2 - `staging` → `master`
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
Labels: Release

#10127 fix: Custom breadcrumb for NodeBalancers details page
  packages/manager/.changeset/pr-10127-fixed-1706638177404.md
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
Labels: Approved

#10124 refactor: [M3-7720] - Refactor AccessKeyTable - Eliminate react anti patterns
  packages/manager/.changeset/pr-10124-tech-stories-1706629455055.md
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyActionMenu.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTable.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTableBody.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTableRows.tsx
Labels: Approved

#10133 Release v1.110.3 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Users/UserPermissions.tsx
Labels: Bug, Release

#10126 upcoming: [M3-7695] - Add new `path_regex` match type to ACLB
  packages/api-v4/src/aglb/types.ts
  packages/manager/.changeset/pr-10126-upcoming-features-1706637215176.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/MatchTypeInfo.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/constants.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts
  packages/validation/.changeset/pr-10126-upcoming-features-1706637249025.md
  packages/validation/src/loadbalancers.schema.ts
Labels: Approved, ACLB

#10128 upcoming: [M3-7700] - Make ACLB Copy Changes Requested by UX
  packages/manager/.changeset/pr-10128-upcoming-features-1706647613582.md
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-configurations.spec.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts
  packages/manager/cypress/e2e/core/loadBalancers/load-balancer-service-targets.spec.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/AddRouteDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ConfigurationDetails.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/RuleDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ServiceTargetDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ServiceTargetForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/Certificates.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/constants.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/index.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/AddExistingCertificateForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/AddNewCertificateForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/constants.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerConfigurations.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRoutes.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerServiceTargets.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/AddRouteDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.test.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/constants.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/AddEndpointForm.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/LinodeOrIPSelect.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetDrawer.tsx
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/constants.tsx
  packages/manager/src/features/LoadBalancers/constants.ts
Labels: Approved, ACLB

#10132 fix: [M3-7722] - Adjust EditableText styling to prevent pixel shift
  packages/manager/.changeset/pr-10132-fixed-1706715510568.md
  packages/manager/src/components/EditableText/EditableText.tsx
Labels: Approved
