Repository linode/manager, pull requests merged in 2024-02, with the labels that each got.

#10102 upcoming: [M3-7660] - Cleanup files to use `profile` to get `user_type`
  packages/manager/.changeset/pr-10102-upcoming-features-1706069240239.md
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.test.tsx
  packages/manager/src/features/Account/SwitchAccounts/ChildAccountList.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/queries/account.ts
Labels: Approved, Parent / Child Account

#10138 fix: [M3-7728] - Token issues when account switching
  packages/manager/src/features/Account/SwitchAccountDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Parent / Child Account

#10150 test: [M3-7737] - Resolve Billing Contact Cypress failure
  packages/manager/.changeset/pr-10150-tests-1707236804326.md
  packages/manager/cypress/e2e/core/billing/billing-contact.spec.ts
Labels: Approved, Parent / Child Account

#10148 refactor: [M3-7736] - Clean up `regionDropdown` feature flag
  packages/manager/.changeset/pr-10148-tech-stories-1707231054836.md
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
Labels: Approved, Clean Up

#10154 change: [M3-7584] - Update `react-router-dom` in preparation for React 18
  packages/manager/.changeset/pr-10154-tech-stories-1707251127609.md
  packages/manager/package.json
  packages/manager/src/components/EmptyLandingPageResources/ResourcesMoreLink.tsx
  packages/manager/src/components/Link.tsx
  yarn.lock
Labels: Dependencies, Approved

#10118 upcoming: [M3-7696] - Edit Access key Drawer - Fix Save button is disabled
  packages/api-v4/src/object-storage/objectStorageKeys.ts
  packages/manager/.changeset/pr-10118-upcoming-features-1706544516803.md
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyActionMenu.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/utils.test.ts
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/validation/src/objectStorageKeys.schema.ts
Labels: Approved, OBJ Multi-Cluster

#10139 test: [M3-7698] - Add test to check proxy user disabled username/email field
  packages/manager/.changeset/pr-10139-tests-1707331596288.md
  packages/manager/cypress/e2e/core/account/change-username.spec.ts
Labels: Approved, Parent / Child Account

#10157 fix: [M3-7741] - Hide error notices for $0 regions in Resize Pool and Add a Node Pool drawers
  packages/manager/.changeset/pr-10157-fixed-1707328749030.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/utils.test.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/utils.ts
Labels: Approved

#10161 fix: [M3-7746] - Fix $0 region price error in "Enable All Backups" drawer
  packages/manager/.changeset/pr-10161-fixed-1707341493849.md
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/src/factories/index.ts
  packages/manager/src/features/Backups/BackupDrawer.test.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Backups/BackupLinodeRow.test.tsx
  packages/manager/src/features/Backups/BackupLinodeRow.tsx
  packages/manager/src/utilities/pricing/backups.test.tsx
  packages/manager/src/utilities/pricing/backups.ts
Labels: Approved

#10156 fix: [M3-7004] - Allow IPv6 ranges transfers
  packages/manager/.changeset/pr-10156-fixed-1707363343774.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/queries/linodes/networking.ts
Labels: Approved, Linodes

#10166 fix: [M3-7747] - Fix Linode Migration dialog hidden $0 price
  packages/manager/.changeset/pr-10166-fixed-1707414781493.md
  packages/manager/src/features/Linodes/MigrateLinode/MigrationPricing.test.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrationPricing.tsx
Labels: Approved

#10153 fix: [M3-7739] - Fix error when enabling backups for Linodes in regions with $0 price
  packages/manager/.changeset/pr-10153-fixed-1707249479775.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
Labels: Approved, Ready for Review

#10165 refactor: [M3-7750] - Update `launchdarkly-react-client-sdk` to latest
  packages/manager/.changeset/pr-10165-tech-stories-1707412665889.md
  packages/manager/package.json
  packages/manager/src/App.tsx
  packages/manager/src/containers/flags.container.ts
  packages/manager/src/containers/withFeatureFlagConsumer.container.ts
  packages/manager/src/features/Domains/DomainRecords.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/utilities/testHelpers.tsx
  yarn.lock
Labels: Dependencies, Approved

#10144 test: [M3-7435, M3-7637] - Cypress tests for OBJ Multicluster access key management
  packages/manager/.changeset/pr-10144-tests-1707158192794.md
  packages/manager/cypress/e2e/core/objectStorage/access-keys.smoke.spec.ts
  packages/manager/cypress/support/intercepts/object-storage.ts
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
Labels: Approved, OBJ Multi-Cluster

#10140 upcoming: [M3-7726] - Assign Linodes to Placement Group Drawer
  packages/api-v4/src/placement-groups/placement-groups.ts
  packages/api-v4/src/placement-groups/types.ts
  packages/manager/.changeset/pr-10140-upcoming-features-1707331683987.md
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
  packages/manager/src/factories/linodes.ts
  packages/manager/src/factories/placementGroups.ts
  packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodesTable.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodesTableRow.test.tsx
  packages/manager/src/features/PlacementGroups/index.tsx
  packages/manager/src/features/PlacementGroups/types.ts
  packages/manager/src/features/PlacementGroups/utils.test.ts
  packages/manager/src/features/PlacementGroups/utils.ts
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/placementGroups.ts
  packages/validation/src/placement-groups.schema.ts
Labels: Approved, Placement Groups

#10164 upcoming: [M3-7611] - Placement Groups Detail Summary
  packages/manager/.changeset/pr-10164-upcoming-features-1707487417041.md
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.tsx
  packages/manager/src/features/PlacementGroups/constants.ts
Labels: Approved, Placement Groups

#10163 refactor: [M3-7749] - Update `luxon` to latest
  packages/manager/.changeset/pr-10163-tech-stories-1707409590058.md
  packages/manager/package.json
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.test.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Linodes/CloneLanding/utilities.ts
  packages/manager/src/features/Managed/Monitors/IssueCalendar.tsx
  packages/manager/src/features/Managed/Monitors/IssueDay.test.tsx
  packages/manager/src/utilities/isRecent.test.ts
  yarn.lock
Labels: Dependencies, Approved, Ready for Review

#10170 feat: [M3-7645] – Support VPC IPv4 Ranges in Add/Edit Linode Config dialog
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.tsx
  packages/manager/src/features/VPCs/constants.ts
Labels: VPC

#10175 chore: [M3-7754] - fix bundle analyse script
  package.json
  packages/manager/.changeset/pr-10175-fixed-1707751671549.md
  packages/manager/package.json
Labels: Approved

#10179 upcoming: [M3-7632] - Use infinite query for child accounts
  packages/manager/.changeset/pr-10179-upcoming-features-1707763060976.md
  packages/manager/src/factories/account.ts
  packages/manager/src/features/Account/SwitchAccounts/ChildAccountList.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/account.ts
  packages/manager/src/queries/events/events.ts
Labels: Approved, Parent / Child Account

#10178 Release v1.112.0 - release → staging
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-linodes-update.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/package.json
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.style.ts
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsListTable.tsx
  packages/manager/src/factories/index.ts
  packages/manager/src/factories/linodeConfigInterfaceFactory.ts
  packages/manager/src/features/Backups/BackupDrawer.test.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Backups/BackupLinodeRow.test.tsx
  packages/manager/src/features/Backups/BackupLinodeRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/utils.test.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/utils.ts
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/types.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrationPricing.test.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrationPricing.tsx
  packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/constants.ts
  packages/manager/src/utilities/noneSingleOrMultipleWithChip.test.tsx
  packages/manager/src/utilities/noneSingleOrMultipleWithChip.tsx
  packages/manager/src/utilities/pricing/backups.test.tsx
  packages/manager/src/utilities/pricing/backups.ts
  packages/manager/src/utilities/subnets.ts
  packages/validation/CHANGELOG.md
  packages/validation/package.json
  packages/validation/src/linodes.schema.ts
Labels: Add'tl Approval Needed, Release → Staging

#10181 change: [M3-7755] – Update IPv4 range "Learn more" docs link
  packages/manager/CHANGELOG.md
  packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.tsx
  packages/manager/src/features/VPCs/constants.ts
Labels: VPC

#10180 Release v1.112.0 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-linodes-update.spec.ts
  packages/manager/cypress/support/constants/dc-specific-pricing.ts
  packages/manager/package.json
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.style.ts
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsListTable.tsx
  packages/manager/src/factories/index.ts
  packages/manager/src/factories/linodeConfigInterfaceFactory.ts
  packages/manager/src/features/Backups/BackupDrawer.test.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Backups/BackupLinodeRow.test.tsx
  packages/manager/src/features/Backups/BackupLinodeRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/utils.test.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/utils.ts
  packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/types.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrationPricing.test.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrationPricing.tsx
  packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/constants.ts
  packages/manager/src/utilities/noneSingleOrMultipleWithChip.test.tsx
  packages/manager/src/utilities/noneSingleOrMultipleWithChip.tsx
  packages/manager/src/utilities/pricing/backups.test.tsx
  packages/manager/src/utilities/pricing/backups.ts
  packages/manager/src/utilities/subnets.ts
  packages/validation/CHANGELOG.md
  packages/validation/package.json
  packages/validation/src/linodes.schema.ts
Labels: Release

#10176 change: [M3-7740] - Use "default" for non-parent/proxy/child `user_type` instead of null
  packages/api-v4/.changeset/pr-10176-upcoming-features-1707761577767.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/profile/types.ts
  packages/manager/.changeset/pr-10176-tests-1707761742808.md
  packages/manager/.changeset/pr-10176-upcoming-features-1707761677226.md
  packages/manager/cypress/e2e/core/account/account-login-history.spec.ts
  packages/manager/cypress/e2e/core/account/change-username.spec.ts
  packages/manager/cypress/e2e/core/billing/restricted-user-billing.spec.ts
  packages/manager/src/factories/accountUsers.ts
  packages/manager/src/factories/profile.ts
  packages/manager/src/features/Account/AccountLogins.tsx
  packages/manager/src/features/Account/CloseAccountSetting.tsx
  packages/manager/src/features/Account/utils.ts
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.test.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/Users/UserRow.test.tsx
Labels: Approved, Parent / Child Account

#10172 upcoming: [M3-7619] - Unassign Linode from PG Modal
  packages/manager/.changeset/pr-10172-upcoming-features-1707758747606.md
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodesTableRow.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsUnassignModal.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsUnassignModal.tsx
  packages/manager/src/features/PlacementGroups/index.tsx
Labels: Add'tl Approval Needed, Placement Groups

#10149 feat: [OCA-1273] - Add February 2024 Marketplace apps: NATS + Jupyter
  packages/manager/.changeset/pr-10149-added-1707494965603.md
  packages/manager/public/assets/jupyter.svg
  packages/manager/public/assets/nats.svg
  packages/manager/public/assets/white/jupyter.svg
  packages/manager/public/assets/white/nats.svg
  packages/manager/src/features/OneClickApps/oneClickApps.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
Labels: Marketplace, Approved

#10186 change: [M3-7735] - Improve Linode Graph X Axis Labels when viewing historic data
  packages/manager/.changeset/pr-10186-changed-1707835872709.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/NetworkGraphs.tsx
Labels: Approved, Recharts

#10183 change: [M3-7731] - Tag breadcrumb label edit icon on Linode Details page for analytics
  packages/manager/.changeset/pr-10183-tech-stories-1707777141390.md
  packages/manager/src/components/Breadcrumb/FinalCrumb.tsx
  packages/manager/src/components/Breadcrumb/types.ts
  packages/manager/src/components/EditableText/EditableText.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/utilities/analytics.ts
Labels: Approved, Analytics

#10191 upcoming: [M3-7756] - Placement Groups limits updates
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/placement-groups/types.ts
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-10191-upcoming-features-1707862432850.md
  packages/manager/src/__data__/regionsData.ts
  packages/manager/src/factories/linodes.ts
  packages/manager/src/factories/placementGroups.ts
  packages/manager/src/factories/regions.ts
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsRenameDrawer.tsx
  packages/manager/src/features/PlacementGroups/utils.test.ts
  packages/manager/src/features/PlacementGroups/utils.ts
  packages/manager/src/hooks/usePlacementGroupsData.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/utilities/regions.test.ts
Labels: Approved, Placement Groups

#10192 upcoming: [M3-7714] - Use API filtering on `user_type` to populate the two Users & Grants tables
  packages/manager/.changeset/pr-10192-upcoming-features-1707921063742.md
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/features/Users/UsersLanding.tsx
  packages/manager/src/features/Users/UsersLandingTableBody.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/accountUsers.ts
Labels: Approved, Parent / Child Account

#10190 upcoming: [M3-7753] - Tag custom analytics events for account switching
  packages/manager/.changeset/pr-10190-upcoming-features-1707847452121.md
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.tsx
  packages/manager/src/features/Account/SwitchAccounts/SwitchAccountSessionDialog.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/utilities/analytics.ts
Labels: Approved, Analytics, Parent / Child Account

#10197 fix: [M3-7758] - Linode Network Graph Tooltip - Incorrect Units
  packages/manager/.changeset/pr-10197-fixed-1708020473057.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/NetworkGraphs.tsx
Labels: Bug, Recharts

#10162 upcoming: [M3-7618] - Delete Placement Group Modal
  packages/manager/.changeset/pr-10162-upcoming-features-1708036002117.md
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.stories.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.test.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsUnassignModal.tsx
  packages/manager/src/features/PlacementGroups/index.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/placementGroups.ts
Labels: Placement Groups

#10188 upcoming: [M3-7694] - OBJ Multi Cluster Copy updates
  packages/manager/.changeset/pr-10188-upcoming-features-1707837776464.md
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/BucketPermissionsTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/CopyAllHostnames.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
  packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
  packages/validation/src/objectStorageKeys.schema.ts
Labels: Ready for Review, OBJ Multi-Cluster

#10202 upcoming: [M3-7775] - Disable ability to edit or delete a proxy user via User Profile page
  packages/manager/.changeset/pr-10202-tests-1708119481596.md
  packages/manager/.changeset/pr-10202-upcoming-features-1708119409383.md
  packages/manager/cypress/e2e/core/account/display-settings.spec.ts
  packages/manager/cypress/e2e/core/account/user-profile.spec.ts
  packages/manager/src/features/Account/constants.ts
  packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
  packages/manager/src/features/Users/UserProfile.tsx
Labels: Approved, Parent / Child Account

#10203 refactor: [M3-7786] - Convert `isRestrictedGlobalGrantType` to Hook
  packages/manager/.changeset/pr-10203-tech-stories-1708119742778.md
  packages/manager/src/features/Account/utils.ts
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.tsx
  packages/manager/src/hooks/useRestrictedGlobalGrantCheck.test.ts
  packages/manager/src/hooks/useRestrictedGlobalGrantCheck.ts
Labels: Ready for Review, Restricted User Access

#10199 feat: [M3-7687] - Refactor & Improve `LinodeActionMenu` Restricted User Experience
  packages/manager/.changeset/pr-10199-tech-stories-1708028973425.md
  packages/manager/src/components/EntityHeader/EntityHeader.stories.tsx
  packages/manager/src/features/Account/utils.ts
  packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenu.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenuUtils.ts
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
Labels: Approved, Restricted User Access

#10195 upcoming: [M3-7615] - Add placement group to payload
  packages/api-v4/.changeset/pr-10195-upcoming-features-1708464732978.md
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-10195-upcoming-features-1708099058499.md
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/components/DetailsPanel/DetailsPanel.test.tsx
  packages/manager/src/components/DetailsPanel/DetailsPanel.tsx
  packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/validation/src/linodes.schema.ts
Labels: Approved, Placement Groups

#10189 upcoming: [M3-7743] - Handle errors gracefully when FF enabled without MSW
  packages/manager/.changeset/pr-10189-upcoming-features-1707838240012.md
  packages/manager/src/components/AccountActivation/AccountActivationError.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTableBody.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTableRow.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTableRows.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.test.tsx
  packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
Labels: Approved, OBJ Multi-Cluster

#10212 chore: Update Storybook to latest to resolve `CVE-2023-42282`
  packages/manager/.changeset/pr-10212-tech-stories-1708530535485.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Storybook

#10211 test: [M3-7434]: Add a Cypress test for OBJ Multicluster Bucket create flow
  packages/manager/.changeset/pr-10211-tests-1708466647763.md
  packages/manager/cypress/e2e/core/objectStorage/object-storage.smoke.spec.ts
  packages/manager/cypress/support/intercepts/object-storage.ts
  packages/manager/cypress/support/ui/autocomplete.ts
Labels: Ready for Review, OBJ Multi-Cluster

#10213 upcoming: [M3-7733] - Access key "Permissions" drawer ARIA label needs to be updated for OBJ Multicluster
  packages/manager/.changeset/pr-10213-upcoming-features-1708540968499.md
  packages/manager/cypress/e2e/core/objectStorage/access-keys.smoke.spec.ts
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/ViewPermissionsDrawer.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, OBJ Multi-Cluster

#10215 fix: [M3-7059] - Stop resetting count and disabling Add button when adding node pool to Kubernetes cluster
  packages/manager/.changeset/pr-10215-fixed-1708555044784.md
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
Labels: Bug, Approved

#10214 poc: [M3-7799] - Improve Docs Site Sidebar
  docs/.vitepress/config.ts
  docs/.vitepress/plugins/sidebar.ts
  docs/.vitepress/tsconfig.json
  package.json
  packages/manager/.changeset/pr-10214-tech-stories-1708552464325.md
  packages/manager/tsconfig.json
Labels: Approved, Documentation

#10219 change: [M3-7802] - Remove API caching
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-10219-tech-stories-1708637715379.md
  packages/manager/package.json
  packages/manager/scripts/prebuild.mjs
  packages/manager/src/cachedData/kernels.json
  packages/manager/src/cachedData/marketplace.json
  packages/manager/src/cachedData/regions.json
  packages/manager/src/cachedData/typesLegacy.json
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/factories/kernels.ts
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/KernelSelect.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.test.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsRenameDrawer.test.tsx
  packages/manager/src/queries/regions.ts
  packages/manager/src/queries/stackscripts.ts
Labels: Approved, Clean Up

#10223 chore: [M3-7803] - Clean up `Chip` component
  packages/manager/.changeset/pr-10223-tech-stories-1708637625570.md
  packages/manager/src/components/Chip.stories.tsx
  packages/manager/src/components/Chip.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
  packages/manager/src/utilities/noneSingleOrMultipleWithChip.tsx
Labels: UX/UI, Approved, Clean Up

#10220 change: [M3-7785] - Improve Dev Tools
  docs/development-guide/10-local-dev-tools.md
  packages/manager/.changeset/pr-10220-changed-1708622627827.md
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/dev-tools/Preferences.tsx
  packages/manager/src/dev-tools/ServiceWorkerTool.tsx
  packages/manager/src/dev-tools/ThemeSelector.tsx
  packages/manager/src/dev-tools/dev-tools.css
  packages/manager/src/dev-tools/dev-tools.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Enhancement, Approved

#10194 upcoming: [M3-7702] - Update Region Select for edge sites
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-10194-upcoming-features-1708456171781.md
  packages/manager/src/__data__/regionsData.ts
  packages/manager/src/assets/icons/entityIcons/edge-server.svg
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
  packages/manager/src/components/RegionSelect/RegionOption.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.styles.ts
  packages/manager/src/components/RegionSelect/RegionSelect.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.utils.ts
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.test.tsx
  packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/factories/regions.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
  packages/manager/src/features/Linodes/LinodesCreate/types.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/utilities/regions.test.ts
Labels: Approved, Gecko MVP

#10217 refactor: [M3-7800] - Clean up `new QueryClient()` pattern in unit tests
  packages/manager/.changeset/pr-10217-tech-stories-1708960982000.md
  packages/manager/src/components/AbuseTicketBanner/AbuseTicketBanner.test.tsx
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.test.tsx
  packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.test.tsx
  packages/manager/src/components/TagsPanel/TagsPanel.test.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTable.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AccessControls.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.test.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
  packages/manager/src/features/GlobalNotifications/RegionStatusBanner.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls/LinodeFirewalls.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/RescueDialog.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.test.tsx
  packages/manager/src/features/Search/SearchLanding.test.tsx
  packages/manager/src/features/Support/SupportTickets/TicketList.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.test.tsx
Labels: Approved, Unit tests, Clean Up

#10182 upcoming: [M3-7580] - Add list view for Linode Clone/Backup
  packages/manager/.changeset/pr-10182-upcoming-features-1707859324148.md
  packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx
  packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeCard.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeCards.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodePanel.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodePanel.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeRow.test.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeRow.tsx
  packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeTable.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
  packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
  packages/manager/src/features/Linodes/LinodesCreate/types.ts
  packages/manager/src/features/Linodes/LinodesCreate/utilities.test.ts
  packages/manager/src/features/Linodes/LinodesCreate/utilities.tsx
  packages/manager/src/queries/types.ts
Labels: Approved, Linodes, Linode Clone UI Updates

#10230 fix: [M3-7811] - Fix Users & Grants query filtering on user_type
  packages/manager/.changeset/pr-10230-upcoming-features-1708982538087.md
  packages/manager/src/features/Users/UsersLanding.tsx
Labels: Bug, Approved, Parent / Child Account

#10231 fix: [M3-7812] Textfield input disabled styles
  packages/manager/.changeset/pr-10231-fixed-1708986686253.md
  packages/manager/src/foundations/themes/light.ts
Labels: Bug, Approved

#10229 feat: [M3-7801] - Reintroduce NVMe Volume Upgrades
  packages/manager/.changeset/pr-10229-added-1708735909784.md
  packages/manager/cypress/e2e/core/volumes/upgrade-volume.spec.ts
  packages/manager/cypress/support/intercepts/volumes.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/UpgradeVolumesDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/VolumesUpgradeBanner.tsx
  packages/manager/src/features/Linodes/LinodesDetail/VolumesUpgradeBenner.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/types.ts
  packages/manager/src/features/Volumes/UpgradeVolumeDialog.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.test.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/features/Volumes/VolumesActionMenu.test.tsx
  packages/manager/src/features/Volumes/VolumesActionMenu.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/features/Volumes/utils.test.ts
  packages/manager/src/features/Volumes/utils.ts
  packages/manager/src/hooks/useToastNotifications.tsx
  packages/manager/src/queries/volumes.ts
  packages/manager/src/queries/volumesMigrations.ts
Labels: Approved, Volumes

#10234 upcoming: [M3-7814, M3-7819] - Fix Account Switching
  packages/manager/.changeset/pr-10234-upcoming-features-1709068609413.md
  packages/manager/.changeset/pr-10234-upcoming-features-1709068764309.md
  packages/manager/cypress/e2e/core/parentChild/account-switching.spec.ts
  packages/manager/src/features/Account/SwitchAccountDrawer.tsx
Labels: Approved, Parent / Child Account

#10225 fix: [M3-7804] - Volume Create Drawer Crash (Linode detail)
  packages/manager/.changeset/pr-10225-fixed-1708720961774.md
  packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeCreateForm.tsx
Labels: Bug

#10235 fix: [M3-7804] - LinodeVolumeCreateForm crash (for real this time)
  packages/manager/.changeset/pr-10225-fixed-1708720961774.md
  packages/manager/.changeset/pr-10235-fixed-1709135736984.md
  packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx
  packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeCreateForm.tsx
Labels: Bug, 🚨 Urgent, Approved

#10232 change: [M3-7815] - Change ACLB Beta Regions
  packages/manager/.changeset/pr-10232-changed-1709130492234.md
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRegions.tsx
Labels: Approved, ACLB

#10239 test: [M3-7820] - Suppress Cypress "MODULE_LEVEL_DIRECTIVE" and "SOURCEMAP_ERROR" warnings
  packages/manager/.changeset/pr-10239-tests-1709145080838.md
  packages/manager/cypress/vite.config.ts
Labels: Approved

#10226 fix: [M3-7796] - Correct Default VPC Scope and Adjust PAT Creation Behavior
  packages/manager/.changeset/pr-10226-fixed-1708710525397.md
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/utils.test.ts
  packages/manager/src/features/Profile/APITokens/utils.ts
Labels: Bug, Approved, VPC

#10208 feat: [M3-7577] - Add invoice byline for powered down instances
  packages/manager/.changeset/pr-10208-added-1708450451347.md
  packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
  packages/manager/src/features/Billing/PdfGenerator/utils.ts
Labels: Approved, Ready for Review

#10167 test: [M3-7452] - Add Cypress test to check empty state in Images landing page
  packages/manager/.changeset/pr-10167-tests-1709236661581.md
  packages/manager/cypress/e2e/core/images/images-empty-landing-page.spec.ts
Labels: Approved, Missing Changeset
