Repository linode/manager, pull requests merged in 2025-04, with the labels that each got.

#11918 refactor: [M3-9645] - Remove `flags` as a prop and move `useIsGeckoEnabled` out of `RegionSelect`
  packages/manager/.changeset/pr-11918-removed-1743089155053.md
  packages/manager/cypress/component/components/region-select.spec.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.stories.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.test.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.stories.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.test.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayDialog.tsx
  packages/manager/src/features/Account/Quotas/Quotas.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsRegionFilter.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/RegionSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseClusterData.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreate/TwoStepRegion.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx
  packages/manager/src/features/Linodes/index.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/AccessKeyRegions.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.tsx
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
  packages/shared/.changeset/pr-11918-added-1743089184822.md
  packages/shared/README.md
  packages/shared/src/components/LinodeSelect/LinodeSelect.stories.tsx
  packages/shared/src/components/LinodeSelect/LinodeSelect.test.tsx
  packages/shared/src/components/LinodeSelect/LinodeSelect.tsx
  packages/shared/src/components/LinodeSelect/index.ts
  packages/shared/src/components/index.ts
  packages/shared/src/hooks/index.ts
  packages/shared/src/hooks/useIsGeckoEnabled.ts
  packages/shared/src/index.ts
Labels: Approved, Modularization

#11885 upcoming: [UIE-8516] - DBaaS: Advanced Configuration (Part 2) - add/remove configs
  packages/api-v4/.changeset/pr-11885-changed-1742400890057.md
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-11885-upcoming-features-1742401242206.md
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfiguration.style.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfigurationDrawer.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.style.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationSelect.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.style.ts
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
  packages/validation/src/databases.schema.ts
Labels: DBaaS, Approved

#11909 refactor: [UIE-8626] - DBaaS cleanup: Deprecated Types, DatabaseCreate, DatabaseSummary
  packages/api-v4/.changeset/pr-11909-removed-1742830690604.md
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-11909-removed-1742830913597.md
  packages/manager/cypress/e2e/core/databases/update-database.spec.ts
  packages/manager/cypress/support/constants/databases.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseClusterData.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreateAccessControls.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseEngineSelect.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseNodeSelector.tsx
  packages/manager/src/features/Databases/DatabaseCreate/utilities.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryClusterConfigurationLegacy.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
Labels: Add'tl Approval Needed, DBaaS

#11939 test: [M3-9488] - Allow Cypress Volume tests to pass against other environments
  packages/api-v4/.changeset/pr-11939-fixed-1743535108177.md
  packages/api-v4/src/linodes/linodes.ts
  packages/manager/.changeset/pr-11939-tests-1743444706872.md
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume-encryption.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.smoke.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/search-volumes.spec.ts
  packages/manager/cypress/e2e/core/volumes/upgrade-volume.spec.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: Ready for Review

#11915 upcoming: [M3-9637] - Support more VPC features and default Firewalls on the Linode Create flow
  packages/manager/.changeset/pr-11915-upcoming-features-1742915363501.md
  packages/manager/.changeset/pr-11915-upcoming-features-1742915406867.md
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceFirewall.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceType.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/Networking.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPC.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPCRanges.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.test.ts
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
  packages/validation/src/linodes.schema.ts
Labels: Linode Interfaces

#11933 fix: [M3-9685] Console errors from create menu & flow
  packages/manager/.changeset/pr-11933-fixed-1743104278261.md
  packages/manager/src/components/Tabs/Tabs.tsx
  packages/manager/src/components/Tabs/__snapshots__/TabList.test.tsx.snap
  packages/manager/src/features/TopMenu/CreateMenu/CreateMenu.styles.ts
Labels: Approved

#11951 test: [M3-9703] - Improve stability of Linode config Cypress tests
  packages/manager/.changeset/pr-11951-tests-1743535607155.md
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/support/setup/defer-command.ts
  packages/manager/cypress/support/util/linodes.ts
Labels: Ready for Review

#11954 change: [M3-9598] - Form fields on Firewall Create page are enabled for restricted user
  packages/manager/.changeset/pr-11954-changed-1743543232723.md
  packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx
Labels: Approved

#11950 change: [M3-9702] - Remove hashing from Pendo
  docs/tooling/analytics.md
  packages/manager/.changeset/pr-11950-tech-stories-1743528301761.md
  packages/manager/package.json
  packages/manager/src/hooks/usePendo.ts
  pnpm-lock.yaml
Labels: Approved, Analytics

#11949 refactor: [M3-9387] - Move Stackscripts queries
  packages/manager/.changeset/pr-11949-removed-1743525729687.md
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppSelect.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptDetailsDialog.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptImages.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionList.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/UserDefinedFields/UserDefinedFields.tsx
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/Image.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/UserDefinedFields.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/utils.ts
  packages/manager/src/features/Search/useAPISearch.ts
  packages/manager/src/features/Search/useClientSideSearch.ts
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/features/StackScripts/StackScriptEdit.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptDeleteDialog.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptLandingTable.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptMakePublicDialog.tsx
  packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
  packages/manager/src/queries/stackscripts.ts
  packages/queries/.changeset/pr-11949-added-1743525787297.md
  packages/queries/src/index.ts
  packages/queries/src/stackscripts/index.ts
  packages/queries/src/stackscripts/keys.ts
  packages/queries/src/stackscripts/requests.ts
  packages/queries/src/stackscripts/stackscripts.ts
  packages/validation/src/linodes.schema.ts
Labels: Approved, Ready for Review, Modularization

#11946 fix: [M3-9700] - Profile Menu Icon Size Inconsistency
  packages/manager/.changeset/pr-11946-fixed-1743519262429.md
  packages/manager/src/assets/icons/chevron-down.svg
  packages/manager/src/assets/icons/chevron-up.svg
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/ui/.changeset/pr-11946-added-1743519284653.md
  packages/ui/src/assets/icons/chevron-up.svg
  packages/ui/src/assets/icons/index.ts
Labels: Bug, Approved

#11919 feat: [UIE-8628, UIE-8631, UIE-8632] - IAM RBAC: update iam apis
  packages/api-v4/.changeset/pr-11919-upcoming-features-1742907313076.md
  packages/api-v4/src/entities/entities.ts
  packages/api-v4/src/entities/index.ts
  packages/api-v4/src/entities/types.ts
  packages/api-v4/src/iam/iam.ts
  packages/api-v4/src/iam/types.ts
  packages/api-v4/src/index.ts
  packages/api-v4/src/resources/index.ts
  packages/api-v4/src/resources/resources.ts
  packages/api-v4/src/resources/types.ts
  packages/manager/.changeset/pr-11919-upcoming-features-1742907356639.md
  packages/manager/src/factories/accountEntities.ts
  packages/manager/src/factories/accountPermissions.ts
  packages/manager/src/factories/accountResources.ts
  packages/manager/src/factories/userPermissions.ts
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesActionMenu.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UnassignRoleConfirmationDialog.test.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.test.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
  packages/manager/src/features/IAM/Shared/utilities.test.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserDetails/UserDetailsPanel.test.tsx
  packages/manager/src/features/IAM/Users/UserDetails/UserDetailsPanel.tsx
  packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.test.tsx
  packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
  packages/manager/src/features/IAM/Users/UserRoles/UserRoles.test.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/entities/entities.ts
  packages/manager/src/queries/entities/queries.ts
  packages/manager/src/queries/resources/queries.ts
Labels: IAM (Identity & Access Management)

#11906 refactor: [M3-9080] - Tanstack routing for VPCs
  packages/manager/.changeset/pr-11906-fixed-1742567649683.md
  packages/manager/.changeset/pr-11906-fixed-1742567667084.md
  packages/manager/.changeset/pr-11906-tech-stories-1742567613345.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-linodes-update.spec.ts
  packages/manager/cypress/support/intercepts/vpc.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Linodes/PowerActionsDialogOrDrawer.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/SubnetContent.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetCreateDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetDeleteDialog.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetDeleteDialog.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetEditDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetEditDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCDeleteDialog.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCDeleteDialog.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEmptyState.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCRow.tsx
  packages/manager/src/features/VPCs/constants.ts
  packages/manager/src/features/VPCs/index.tsx
  packages/manager/src/hooks/useDialogData.ts
  packages/manager/src/routes/index.tsx
  packages/manager/src/routes/vpcs/index.ts
  packages/manager/src/routes/vpcs/vpcsLazyRoutes.ts
  packages/queries/src/vpcs/vpcs.ts
Labels: Approved, Routing Refactor

#11935 fix: [M3-9070] - Exclude `child_account` grant from PAT token calculations when it is hidden
  packages/manager/.changeset/pr-11935-fixed-1743110166866.md
  packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
  packages/manager/src/features/Profile/APITokens/utils.ts
Labels: Bug, Approved, Ready for Review

#11947 fix: [M3-9689] - Fix unclearable ACL IP addresses for LKE clusters
  packages/manager/.changeset/pr-11947-fixed-1743523539798.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx
Labels: Bug, UX/UI, LKE, Approved

#11938 upcoming: [M3-9515] - Update types for VPC IPs
  packages/api-v4/.changeset/pr-11938-upcoming-features-1743446020892.md
  packages/api-v4/src/vpcs/types.ts
  packages/manager/.changeset/pr-11938-upcoming-features-1743446079043.md
  packages/manager/src/factories/vpcs.ts
Labels: VPC IPv6

#11943 upcoming:[DI-23542] - Resource selection limitation phase 2 in cloudpulse alerting resources section
  packages/manager/.changeset/pr-11943-upcoming-features-1743494415175.md
  packages/manager/cypress/e2e/core/cloudpulse/edit-user-alert.spec.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertMaxSelectionText.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertMaxSelectionText.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResourcesNotice.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/DisplayAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Resources/CloudPulseModifyAlertResources.test.tsx
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#11961 test: [M3-9716] - Disallow some regions from being used for Image upload tests
  packages/manager/.changeset/pr-11961-tests-1743634308900.md
  packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
  packages/manager/cypress/support/util/regions.ts
Labels: Add'tl Approval Needed, Ready for Review

#11958 test: [M3-9481 & more] - Apply environment-specific tags to tests
  packages/manager/.changeset/pr-11958-tests-1743610427083.md
  packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
  packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscripts.spec.ts
  packages/manager/cypress/support/setup/test-tagging.ts
  packages/manager/cypress/support/util/tag.ts
Labels: Ready for Review

#11970 change: Update docs link for Accelerated Linode Plans GA Launch
  packages/manager/src/features/components/PlansPanel/constants.ts
Labels: Approved, Ready for Review, For Release

#11969 refactor: [DI-24450] - Added logic to update the alert in cache when it is created
  packages/manager/.changeset/pr-11969-added-1743779981445.md
  packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/edit-user-alert.spec.ts
  packages/manager/cypress/support/intercepts/cloudpulse.ts
  packages/manager/src/queries/cloudpulse/alerts.ts
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#11979 fix: [UIE-8447] - refresh drawer after config add/update
  packages/api-v4/CHANGELOG.md
  packages/api-v4/src/databases/types.ts
  packages/manager/CHANGELOG.md
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfigurationDrawer.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
Labels: Add'tl Approval Needed, DBaaS, For Release

#11983 fix: Update `pnpm clean` command to include all new packages
  package.json
Labels: Add'tl Approval Needed, Ready for Review

#11934 upcoming: [M3-9682] - Disable Upgrade Interfaces functionality for LKE Linodes and other conditions
  packages/manager/.changeset/pr-11934-upcoming-features-1743443080180.md
  packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/constants.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/utils.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetail.tsx
  packages/manager/src/hooks/useCanUpgradeInterfaces.ts
  packages/ui/src/components/Button/Button.tsx
Labels: Approved, Linode Interfaces

#11963 upcoming: [DI-24238] - UI changes to Create/Edit form
  packages/manager/.changeset/pr-11963-upcoming-features-1743680039001.md
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/TriggerConditions.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/ServiceTypeSelect.tsx
  packages/validation/.changeset/pr-11963-changed-1743680086813.md
  packages/validation/src/cloudpulse.schema.ts
Labels: Cloud Pulse, Cloud Pulse - Alerting

#11967 upcoming:[DI-24445] - Remove or condition when empty
  packages/manager/.changeset/pr-11967-upcoming-features-1743747392300.md
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
Labels: Cloud Pulse - Dashboards

#11953 upcoming: [M3-9706] - Fix Subnets Table for Linodes using new interfaces
  packages/manager/.changeset/pr-11953-upcoming-features-1743614906461.md
  packages/manager/cypress/e2e/core/linodes/create-linode-with-vpc.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/cypress/support/intercepts/configs.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceDetailsDrawer/VPCInterfaceDetailsContent.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/features/VPCs/utils.test.ts
  packages/manager/src/features/VPCs/utils.ts
  packages/manager/src/hooks/useInterfaceAndFirewallDataForLinode.ts
  packages/queries/.changeset/pr-11953-added-1743614960791.md
  packages/queries/src/linodes/configs.ts
  packages/queries/src/linodes/interfaces.ts
  packages/queries/src/linodes/linodes.ts
  packages/utilities/src/factories/linodeInterface.ts
Labels: Approved, Linode Interfaces

#11987 fix: [UIE-8674] - advanced config fix
  packages/manager/.changeset/pr-11987-changed-1744123144788.md
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfigurationDrawer.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
  packages/validation/src/cloudpulse.schema.ts
Labels: Add'tl Approval Needed, DBaaS

#11974 upcoming: [M3-9646] - Create VM Host Maintenance flag
  packages/manager/.changeset/pr-11974-upcoming-features-1743784910488.md
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
Labels: Approved

#11962 change: [M3-9655] - [Akamai Design System] Toast Component
  packages/manager/.changeset/pr-11962-changed-1743652792312.md
  packages/manager/src/components/Snackbar/CloseSnackbar.tsx
  packages/manager/src/components/Snackbar/Snackbar.tsx
  packages/manager/src/components/Snackbar/ToastNotifications.stories.tsx
  packages/manager/src/index.tsx
  packages/ui/.changeset/pr-11962-added-1743652880587.md
  packages/ui/src/assets/icons/error-outlined.svg
  packages/ui/src/assets/icons/index.ts
  packages/ui/src/assets/icons/info-outlined.svg
  packages/ui/src/assets/icons/success-outlined.svg
  packages/ui/src/assets/icons/tip-outlined.svg
  packages/ui/src/assets/icons/warning-outlined.svg
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Ready for Review, Design Tokens

#11991 revert: [M3-9080] - Tanstack routing for VPCs
  packages/manager/.changeset/pr-11906-fixed-1742567649683.md
  packages/manager/.changeset/pr-11906-fixed-1742567667084.md
  packages/manager/.changeset/pr-11906-tech-stories-1742567613345.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-linodes-update.spec.ts
  packages/manager/cypress/support/intercepts/vpc.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Linodes/PowerActionsDialogOrDrawer.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/SubnetContent.tsx
  packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetCreateDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetDeleteDialog.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetDeleteDialog.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetEditDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetEditDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCDeleteDialog.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCDeleteDialog.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCEmptyState.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCRow.tsx
  packages/manager/src/features/VPCs/constants.ts
  packages/manager/src/features/VPCs/index.tsx
  packages/manager/src/hooks/useDialogData.ts
  packages/manager/src/routes/index.tsx
  packages/manager/src/routes/vpcs/index.ts
  packages/manager/src/routes/vpcs/vpcsLazyRoutes.ts
  packages/queries/src/vpcs/vpcs.ts
Labels: Approved, Ready for Review

#11944 change: [M3-9408] - Remove min length validation for tag
  packages/manager/.changeset/pr-11944-changed-1743506054914.md
  packages/manager/src/components/TagCell/AddTag.tsx
  packages/manager/src/components/TagsInput/TagsInput.test.tsx
  packages/manager/src/components/TagsInput/TagsInput.tsx
Labels: Approved, Ready for Review

#11968 fix: [DI-24413] - Bug fixes on the dashboard UI
  packages/manager/.changeset/pr-11968-fixed-1743780227804.md
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseAppliedFilter.tsx
Labels: Cloud Pulse, Cloud Pulse - Alerting

#11981 upcoming: [DI-24451] - Added confirmation dialog on enabling/disabling of alert
  packages/manager/.changeset/pr-11981-upcoming-features-1744104834195.md
  packages/manager/cypress/e2e/core/cloudpulse/alert-errors.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/alerts-listing-page.spec.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertConfirmationDialog.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertConfirmationDialog.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertInformationActionTable.tsx
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#11989 change: [M3-9733], [M3-9734] and [M3-9736] - Image service Gen2 - Copy updates
  packages/manager/.changeset/pr-11989-changed-1744126754414.md
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/routes/images/ImagesRoute.tsx
Labels: Approved, Image Service Gen2

#11984 feat: [UIE-8672, UIE-8625] - IAM RBAC: fix not displaying empty state when no roles or no entities assigned
  packages/manager/.changeset/pr-11984-upcoming-features-1744052007574.md
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Users/UserDetails/UserDetailsPanel.test.tsx
  packages/manager/src/features/IAM/Users/UserDetails/UserDetailsPanel.tsx
  packages/manager/src/features/IAM/Users/UserEntities/UserEntities.test.tsx
  packages/manager/src/features/IAM/Users/UserEntities/UserEntities.tsx
  packages/manager/src/features/IAM/Users/UserRoles/UserRoles.test.tsx
  packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
Labels: Approved, IAM (Identity & Access Management)

#11986 refactor: [M3-9170] - Move `betaUtils` and its associated factories to `utilities` package
  packages/manager/.changeset/pr-11986-removed-1744096851575.md
  packages/manager/cypress/e2e/core/account/smoke-enroll-beta.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/factories/index.ts
  packages/manager/src/features/Betas/BetasLanding.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.test.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/utilities/.changeset/pr-11986-added-1744096873342.md
  packages/utilities/src/factories/betas.ts
  packages/utilities/src/factories/index.ts
  packages/utilities/src/helpers/betaUtils.test.ts
  packages/utilities/src/helpers/betaUtils.ts
  packages/utilities/src/helpers/index.ts
Labels: Approved, Modularization

#11977 upcoming: [DI-24470] - Rename resources to entities in labels, placeholders and messages in cloudpulse alerting
  packages/manager/.changeset/pr-11977-upcoming-features-1744016876527.md
  packages/manager/cypress/e2e/core/cloudpulse/alert-show-details.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/edit-system-alert.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/edit-user-alert.spec.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertMaxSelectionText.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertMaxSelectionText.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResourcesNotice.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/constants.ts
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Resources/CloudPulseModifyAlertResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Resources/CloudPulseModifyAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertLanding.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResourcesConfirmationDialog.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/utils.test.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/utils.ts
Labels: Approved, Ready for Review, Cloud Pulse, Cloud Pulse - Alerting

#11973 fix: Update field restrictions for Create Firewall form
  packages/manager/.changeset/pr-11973-changed-1743783278795.md
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx
Labels: Approved, Restricted User Access

#11868 DI-23961 - Fix schema types and validations in cloudpulse alerting create and edit flow
  packages/api-v4/.changeset/pr-11868-upcoming-features-1744170177040.md
  packages/api-v4/src/cloudpulse/alerts.ts
  packages/manager/.changeset/pr-11868-upcoming-features-1742271706713.md
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/EngineOption.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/EngineOption.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/RegionSelect.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/RegionSelect.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/schemas.ts
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/types.ts
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/utilities.ts
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/schemas.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/utils.test.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/utils.ts
  packages/manager/src/features/CloudPulse/Alerts/constants.ts
  packages/validation/.changeset/pr-11868-upcoming-features-1742271743027.md
  packages/validation/src/cloudpulse.schema.ts
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#11996 test [M3-9559]: mock region for LKE test
  packages/manager/.changeset/pr-11996-tests-1744202889076.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
Labels: Add'tl Approval Needed

#12002 deps: [M3-9749] - Upgrade Cypress to 14.3.0
  package.json
  packages/manager/.changeset/pr-12002-tech-stories-1744219481332.md
  packages/manager/Dockerfile
  packages/manager/package.json
  pnpm-lock.yaml
Labels: Testing, Dependencies, Approved

#11985 upcoming: [M3-9714] - Update Linode Create UI for Linode Interfaces
  packages/manager/.changeset/pr-11985-upcoming-features-1744141507075.md
  packages/manager/src/components/SelectionCard/CardBase.styles.ts
  packages/manager/src/components/ShowMoreExpansion/ShowMoreExpansion.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceGeneration.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceGeneration.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceType.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/LinodeInterface.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/Networking.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPC.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPCAvailability.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPCRanges.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.test.ts
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.ts
  packages/ui/src/components/Button/Button.tsx
Labels: Approved, Linode Interfaces

#12007 change: [M3-9743] - Rename `Analytics` tab to `Metrics` tab on Linode details page
  packages/manager/.changeset/pr-12007-changed-1744290501828.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/utilities/src/helpers/arrayToList.test.ts
  packages/utilities/src/helpers/arrayToList.ts
Labels: Approved, ACLP Integration

#11995 upcoming: [M3-9731] - Check for Linode Interfaces Account Capability
  packages/api-v4/.changeset/pr-11995-added-1744149551930.md
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-11995-upcoming-features-1744149575402.md
  packages/manager/cypress/e2e/core/linodes/linode-network.spec.ts
  packages/manager/src/features/Account/DefaultFirewalls.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.test.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx
  packages/manager/src/utilities/linodes.test.ts
  packages/manager/src/utilities/linodes.ts
Labels: Approved, Linode Interfaces

#11976 upcoming: [M3-9537] - Fix some VPC related bugs for Linode Interfaces
  packages/api-v4/.changeset/pr-11976-changed-1744036917580.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-11976-upcoming-features-1744036859769.md
  packages/manager/cypress/e2e/core/linodes/linode-network.spec.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.test.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.test.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/hooks/useVPCConfigInterface.ts
  packages/manager/src/hooks/useVPCInterface.ts
  packages/queries/src/linodes/interfaces.ts
  packages/utilities/src/factories/linodes.ts
Labels: Approved, Linode Interfaces

#11932 change: [M3-8978] - Disable Autocomplete search on touch devices
  packages/manager/.changeset/pr-11932-changed-1743106946509.md
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/Help/Panels/AlgoliaSearchBar.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/ui/src/components/Autocomplete/Autocomplete.tsx
  packages/ui/src/components/DatePicker/TimeZoneSelect.tsx
  packages/ui/src/components/Select/Select.tsx
Labels: Approved

#12008 upcoming: [M3-9752] - Support more VPC features in the Add Interface Drawer
  packages/manager/.changeset/pr-12008-upcoming-features-1744651679398.md
  packages/manager/cypress/e2e/core/linodes/linode-network.spec.ts
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPC.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPCRanges.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/AddInterfaceForm.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VPC/VPCDetails.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VPC/VPCIPv4Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VPC/VPCIPv4Addresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VPC/VPCInterface.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VPC/VPCRanges.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/VPCPanel.tsx
  packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.tsx
  packages/manager/src/features/VPCs/components/VPCPublicIPLabel.tsx
  packages/manager/src/features/VPCs/components/VPCRangesDescription.tsx
  packages/manager/src/features/VPCs/constants.ts
Labels: Approved, Linode Interfaces

#11957 upcoming: [M3-9649] - Linode Interfaces - Edit Public Interface
  packages/manager/.changeset/pr-11957-upcoming-features-1744304365513.md
  packages/manager/src/components/ErrorMessage.tsx
  packages/manager/src/components/SupportLink/SupportLink.tsx
  packages/manager/src/components/SupportTicketGeneralError.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/AddInterfaceDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/EditInterfaceDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/EditInterfaceForm.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/PublicInterface/IPv4AddressRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/PublicInterface/IPv4Addresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/PublicInterface/IPv6RangeRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/PublicInterface/IPv6Ranges.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceDetailsDrawer/PublicInterfaceDetailsContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaces.tsx
  packages/queries/src/linodes/interfaces.ts
  packages/validation/src/linodes.schema.ts
Labels: Approved, Linode Interfaces

#12001 upcoming:[DI-24112] - Add grouping by tag for alerts
  packages/manager/.changeset/pr-12001-upcoming-features-1744284627613.md
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertActionMenu.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertsTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/GroupedAlertsTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertsActionMenu.ts
  packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/utilities/src/helpers/groupByTags.ts
  packages/utilities/src/types/ManagerPreferences.ts
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#12019 fix: [M3-9521] - Warning message in the images landing page for the restricted user
  packages/manager/.changeset/pr-12019-fixed-1744606971621.md
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
Labels: Approved, Restricted User Access

#11975 fix: [M3-9245] - CM Showing Wrong Permissions for Limited Access Key
  packages/manager/.changeset/pr-11975-fixed-1744233099304.md
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/ViewPermissionsDrawer.tsx
Labels: Bug, Object Storage

#12014 test [M3-9567]: Fix Cypress LKE update tests in DevCloud
  packages/manager/.changeset/pr-12014-tests-1744382864732.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
Labels: Approved

#12017 upcoming: [M3-9751] - Add Interface Settings Drawer for Linode Interfaces
  packages/manager/.changeset/pr-12017-upcoming-features-1744652118248.md
  packages/manager/src/components/SupportTicketGeneralError.tsx
  packages/manager/src/dev-tools/load.ts
  packages/manager/src/factories/userPermissions.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
  packages/manager/src/features/Help/Panels/AlgoliaSearchBar.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceSettingsForm.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaces.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/mocks/presets/crud/seeds/nodebalancers.ts
  packages/queries/src/linodes/interfaces.ts
  packages/queries/src/linodes/linodes.ts
  packages/ui/src/components/Autocomplete/Autocomplete.tsx
  packages/ui/src/components/DatePicker/TimeZoneSelect.tsx
  packages/ui/src/components/Select/Select.tsx
  packages/utilities/src/factories/linodes.ts
  packages/utilities/src/factories/nodebalancer.ts
  packages/utilities/src/helpers/groupByTags.ts
  packages/validation/src/linodes.schema.ts
Labels: Approved, Linode Interfaces

#11978 feat: [UIE-8601] - IAM RBAC: add new drawer for updating entities flow
  packages/api-v4/.changeset/pr-11978-upcoming-features-1744016884259.md
  packages/manager/.changeset/pr-11978-upcoming-features-1744016922823.md
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesActionMenu.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesActionMenu.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UpdateEntitiesDrawer.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UpdateEntitiesDrawer.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.test.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
  packages/manager/src/features/IAM/Shared/utilities.test.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserEntities/ChangeRoleForEntityDrawer.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignSingleRole.tsx
Labels: Approved, IAM (Identity & Access Management)

#12022 change: [UIE-8685] - Advanced Config: custom validation for wal_sender_timeout
  packages/api-v4/src/databases/types.ts
  packages/manager/src/factories/databases.ts
  packages/validation/.changeset/pr-12022-added-1744640788599.md
  packages/validation/src/databases.schema.ts
Labels: DBaaS, Approved

#12011 fix: [M3-9732] - ACL Flash of Content
  packages/manager/.changeset/pr-12011-fixed-1744319899786.md
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
Labels: Approved, Object Storage Gen2

#12030 test: [M3-9480] - Allow Linode delete Cypress tests to pass in non-Prod environments
  packages/manager/.changeset/pr-12030-tests-1744726914987.md
  packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
Labels: Ready for Review

#12018 refactor: [M3-9767] - Use simple Select in `RegionTypeFilter`
  packages/manager/.changeset/pr-12018-tech-stories-1744408988818.md
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/Linodes/LinodesLanding/RegionTypeFilter.tsx
  packages/manager/src/features/Linodes/index.tsx
Labels: Approved

#12025 refactor: [M3-9711] - Move `grants` and its associated factories to `utilities` package
  packages/manager/.changeset/pr-12025-removed-1744698392062.md
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/cypress/e2e/core/account/user-verification-banner.spec.ts
  packages/manager/cypress/e2e/core/account/users-landing-page.spec.ts
  packages/manager/cypress/e2e/core/billing/restricted-user-billing.spec.ts
  packages/manager/cypress/e2e/core/databases/create-database.spec.ts
  packages/manager/cypress/e2e/core/images/images-empty-landing-page.spec.ts
  packages/manager/cypress/e2e/core/images/images-non-empty-landing-page.spec.ts
  packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/cypress/e2e/core/parentChild/account-switching.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/cypress/support/constants/user-permissions.ts
  packages/manager/src/factories/index.ts
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.test.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddLinodeDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLandingEmptyState.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Addons/Backups.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Addons/PrivateIP.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Details/Details.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Region.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Security.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx
  packages/manager/src/features/Users/UserRow.test.tsx
  packages/manager/src/features/Users/UserRow.tsx
  packages/manager/src/features/Volumes/VolumesLandingEmptyState.test.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/utilities/.changeset/pr-12025-added-1744698420691.md
  packages/utilities/src/factories/grants.ts
  packages/utilities/src/factories/index.ts
  packages/utilities/src/helpers/grants.test.ts
  packages/utilities/src/helpers/grants.ts
  packages/utilities/src/helpers/index.ts
Labels: Approved, Ready for Review, Modularization

#12021 fix: [M3-9586] - Warning message in the Longview landing page for the restricted user
  packages/manager/.changeset/pr-12021-fixed-1744625544934.md
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
Labels: Approved, Restricted User Access

#11999 test: [M3-9565] - mock region for linode config test
  packages/manager/.changeset/pr-11999-tests-1744205582905.md
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
Labels: Testing, Approved

#11997 test: [M3-9489] - Use mock regions for region search
  packages/manager/.changeset/pr-11997-tests-1744203271879.md
  packages/manager/cypress/e2e/core/general/gdpr-agreement.spec.ts
Labels: Approved

#12032 fix: [UIE-8447] - autofill fix and clear errors on blur
  packages/manager/.changeset/pr-12032-fixed-1744732437757.md
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfigurationDrawer.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/utilities.ts
Labels: Add'tl Approval Needed, DBaaS

#12034 hotfix: [M3-9771] – Remove references to disk encryption for LKE
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/Encryption/constants.tsx
  packages/manager/src/features/Kubernetes/ClusterList/constants.ts
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
Labels: Add'tl Approval Needed, LKE, Hotfix, Linode Disk Encryption (LDE), LKE-Enterprise

#12047 Release v1.139.1 - `staging` → `master`
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/components/Encryption/constants.tsx
  packages/manager/src/features/Kubernetes/ClusterList/constants.ts
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
Labels: Release, Off-Cycle Release

#12040 test: [M3-9174] - Add Cypress tests for Firewall landing page improvements related to Linode Interfaces
  packages/manager/.changeset/pr-12040-tests-1744753693965.md
  packages/manager/cypress/e2e/core/firewalls/delete-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/firewall-landing-page.spec.ts
  packages/manager/cypress/e2e/core/firewalls/landing-page-empty-state.spec.ts
  packages/manager/cypress/support/intercepts/firewalls.ts
Labels: Approved, Linode Interfaces

#12023 test: [M3-9555] - Fix plan selection Cypress test against other environments
  packages/manager/.changeset/pr-12023-tests-1744653408368.md
  packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts
Labels: Approved

#12048 change: [OCA-1509] - Deprecate 4 Marketplace apps
  packages/manager/.changeset/pr-12048-changed-1744815132260.md
  packages/manager/public/assets/seatable.svg
  packages/manager/public/assets/utunnel.svg
  packages/manager/public/assets/victoriametricssingle.svg
  packages/manager/public/assets/warpspeed.svg
  packages/manager/public/assets/white/seatable.svg
  packages/manager/public/assets/white/utunnel.svg
  packages/manager/public/assets/white/victoriametricssingle.svg
  packages/manager/public/assets/white/warpspeed.svg
  packages/manager/src/features/OneClickApps/oneClickApps.ts
Labels: Marketplace, Approved

#12044 feat[UIE-8656] - IAM / RBAC useIsIAMEnabled hook to check user API access
  packages/manager/.changeset/pr-12044-upcoming-features-1744808175869.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
  packages/manager/src/features/IAM/hooks/useCalculateHiddenItems.ts
  packages/manager/src/features/IAM/hooks/useIsIAMEnabled.test.ts
  packages/manager/src/features/IAM/hooks/useIsIAMEnabled.ts
  packages/manager/src/queries/entities/entities.ts
  packages/manager/src/queries/iam/iam.ts
Labels: Approved, IAM (Identity & Access Management)

#12036 test: [M3-9169] - Add Cypress tests for Firewall create with template flows
  packages/manager/.changeset/pr-12036-tests-1744749094051.md
  packages/manager/cypress/e2e/core/firewalls/create-firewall-custom.spec.ts
  packages/manager/cypress/e2e/core/firewalls/create-firewall-with-template.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
  packages/manager/cypress/support/intercepts/firewalls.ts
  packages/manager/cypress/support/intercepts/general.ts
  packages/manager/eslint.config.js
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/OneClickApps/oneClickApps.ts
Labels: Approved, Linode Interfaces

#12033 fix: [M3-9770] - Fix incorrect max autoscaler limit validation for LKE-E
  packages/manager/.changeset/pr-12033-upcoming-features-1744745488820.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Kubernetes/constants.ts
  packages/validation/.changeset/pr-12033-removed-1744745547794.md
  packages/validation/src/kubernetes.schema.ts
Labels: Bug, Approved, LKE-Enterprise

#12038 feat: [UIE-8646] Update "Assign roles" drawer
  packages/manager/.changeset/pr-12038-changed-1744750503892.md
  packages/manager/src/features/IAM/Shared/Entities/Entities.test.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignSingleRole.tsx
  packages/ui/src/assets/icons/delete.svg
  packages/ui/src/assets/icons/index.ts
Labels: IAM (Identity & Access Management)

#12012 feat: [UIE-8142] - IAM RBAC - Implement Roles Table
  packages/api-v4/src/iam/types.ts
  packages/manager/.changeset/pr-12012-added-1744320839894.md
  packages/manager/.changeset/pr-12012-added-1744837242791.md
  packages/manager/package.json
  packages/manager/src/features/IAM/Roles/Roles.test.tsx
  packages/manager/src/features/IAM/Roles/Roles.tsx
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.test.tsx
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.tsx
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTableActionMenu.test.tsx
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTableActionMenu.tsx
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTableExpandedRow.test.tsx
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTableExpandedRow.tsx
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/utilities/src/helpers/capitalize.ts
  pnpm-lock.yaml
Labels: Approved, IAM (Identity & Access Management)

#12027 feat: [UIE-8603] - IAM RBAC: User Entities - Remove Assignment
  packages/api-v4/.changeset/pr-12027-upcoming-features-1744710990072.md
  packages/manager/.changeset/pr-12027-upcoming-features-1744711021887.md
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/RemoveAssignmentConfirmationDialog/RemoveAssignmentConfirmationDialog.test.tsx
  packages/manager/src/features/IAM/Shared/RemoveAssignmentConfirmationDialog/RemoveAssignmentConfirmationDialog.tsx
  packages/manager/src/features/IAM/Shared/utilities.test.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.test.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
Labels: Approved, IAM (Identity & Access Management)

#12026 upcoming: [M3-9758] - Create a feature flag for ACLP Integration
  packages/manager/.changeset/pr-12026-upcoming-features-1744709007966.md
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
Labels: Approved, ACLP Integration

#12031 change: [M3-9433] - Image Service Gen2 GA: Update copy about Image Pricing
  packages/manager/.changeset/pr-12031-changed-1744729225214.md
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.tsx
  packages/manager/src/routes/images/ImagesRoute.tsx
Labels: Approved, Image Service Gen2

#12029 test: [M3-9578] - Use mock regions for Linode Migrate integration tests
  packages/manager/.changeset/pr-12029-tests-1744725232756.md
  packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
  packages/manager/cypress/support/intercepts/regions.ts
Labels: Add'tl Approval Needed, Ready for Review

#12041 change: [M3-9773] - Add Premium plan notice for LKE
  packages/manager/.changeset/pr-12041-added-1744830071047.md
  packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/PremiumCPUPlanNotice.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
Labels: LKE, Approved, LKE-Enterprise

#12058 fix: Surface IPv4 Range errors for Linode Interfaces in SubnetAssignLinodesDrawer
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/PromptDialogContent.tsx
  packages/manager/src/features/VPCs/utils.test.ts
  packages/manager/src/features/VPCs/utils.ts
Labels: Bug, Linode Interfaces

#12051 test: [DI-24751] - Add Cypress test coverage for grouping of alerts by tags in CloudPulse Alerts Listing page
  packages/manager/.changeset/pr-12051-tests-1744882097150.md
  packages/manager/cypress/e2e/core/cloudpulse/groupby-tags.spec.ts
Labels: Approved, Cloud Pulse - Alerting

#11994 refactor: [M3-9723] - Managed Tanstack routing
  packages/api-v4/src/managed/managed.ts
  packages/manager/.changeset/pr-11994-tech-stories-1744294379683.md
  packages/manager/cypress/e2e/core/managed/managed-contacts.spec.ts
  packages/manager/cypress/e2e/core/managed/managed-credentials.spec.ts
  packages/manager/cypress/e2e/core/managed/managed-monitors.spec.ts
  packages/manager/cypress/e2e/core/managed/managed-ssh.spec.ts
  packages/manager/cypress/support/intercepts/managed.ts
  packages/manager/eslint.config.js
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/DeletionDialog/DeletionDialog.test.tsx
  packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
  packages/manager/src/factories/managed.ts
  packages/manager/src/features/Managed/Contacts/Contacts.test.ts
  packages/manager/src/features/Managed/Contacts/Contacts.tsx
  packages/manager/src/features/Managed/Contacts/ContactsActionMenu.tsx
  packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
  packages/manager/src/features/Managed/Contacts/ContactsRow.tsx
  packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx
  packages/manager/src/features/Managed/Contacts/common.ts
  packages/manager/src/features/Managed/Contacts/index.ts
  packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
  packages/manager/src/features/Managed/Credentials/CredentialActionMenu.tsx
  packages/manager/src/features/Managed/Credentials/CredentialList.tsx
  packages/manager/src/features/Managed/Credentials/CredentialRow.tsx
  packages/manager/src/features/Managed/Credentials/CredentialTableContent.tsx
  packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
  packages/manager/src/features/Managed/Credentials/index.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/MonitorTickets.tsx
  packages/manager/src/features/Managed/ManagedLanding.tsx
  packages/manager/src/features/Managed/MonitorDrawer.tsx
  packages/manager/src/features/Managed/Monitors/HistoryDrawer.tsx
  packages/manager/src/features/Managed/Monitors/MonitorActionMenu.test.tsx
  packages/manager/src/features/Managed/Monitors/MonitorActionMenu.tsx
  packages/manager/src/features/Managed/Monitors/MonitorRow.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTable.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTableContent.tsx
  packages/manager/src/features/Managed/Monitors/index.tsx
  packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccess.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.test.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessRow.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessTable.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessTableContent.tsx
  packages/manager/src/features/Managed/SSHAccess/index.ts
  packages/manager/src/features/Managed/SupportWidget.tsx
  packages/manager/src/features/Managed/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/managed/managed.ts
  packages/manager/src/routes/index.tsx
  packages/manager/src/routes/managed/index.ts
  packages/manager/src/routes/managed/managedLazyRoutes.ts
Labels: Approved, Routing Refactor

#12056 test: [M3-9171 & M3-9172] - Add Cypress tests for Linode Interfaces account settings additions
  packages/manager/.changeset/pr-12056-tests-1744906803100.md
  packages/manager/cypress/e2e/core/account/network-settings.spec.ts
  packages/manager/cypress/support/intercepts/account.ts
  packages/manager/cypress/support/intercepts/firewalls.ts
  packages/manager/cypress/support/util/errors.ts
Labels: Testing, Approved, Linode Interfaces

#12068 feat[UIE-8726]: IAM disable API check when feature flag is off
  packages/manager/src/features/IAM/hooks/useIsIAMEnabled.test.ts
  packages/manager/src/features/IAM/hooks/useIsIAMEnabled.ts
  packages/manager/src/queries/iam/iam.ts
Labels: Approved, IAM (Identity & Access Management), For Release

#12064 change: [M3-9655] - [Akamai Design System] Toast Component - Design Feedback
  packages/manager/src/components/Snackbar/Snackbar.tsx
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Add'tl Approval Needed, Design Tokens, For Release

#12042 test:[DI-24112] - Add UTs for new components
  packages/manager/.changeset/pr-12042-upcoming-features-1744796837347.md
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/GroupedAlertsTable.test.tsx
  packages/manager/src/features/CloudPulse/Utils/UserPreference.test.ts
  packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
Labels: Approved, Cloud Pulse - Alerting

#12013 change: [M3-9742] - Add dedicated `Alerts` tab on Linode details page
  packages/manager/.changeset/pr-12013-changed-1744375580329.md
  packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAlerts/LinodeAlerts.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettings.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
Labels: Approved, ACLP Integration

#12028 Fixed: [M3-9621], [M3-9628], [M2-9629], [M3-9648] - Bug fixes in Linode Create and Landing Pages
  packages/manager/.changeset/pr-12028-fixed-1744724101282.md
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Volumes/Drawers/VolumeDrawer/LinodeVolumeAddDrawer.tsx
Labels: Approved

#12046 fix: [M3-9769] - Enhanced number input for LKE and LKE-E
  packages/manager/.changeset/pr-12046-fixed-1744906900651.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
  packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.tsx
  packages/manager/src/factories/managed.ts
  packages/manager/src/features/Kubernetes/ClusterList/constants.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummaryItem.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/Kubernetes/constants.ts
  packages/manager/src/features/Managed/Credentials/CredentialList.tsx
  packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
  packages/manager/src/features/Managed/Monitors/MonitorActionMenu.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.tsx
Labels: Bug, LKE, Approved, LKE-Enterprise

#12049 upcoming: [M3-9590] - Update Linode Networking UI for Linode Interfaces
  packages/manager/src/components/ShowMore/ShowMore.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPC.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VPC/VPCDetails.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/VPCInterface/VPCIPv4Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/VPCInterface/VPCIPv4Addresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/VPCInterface/VPCIPv4Ranges.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceIPs.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceIPs.utils.test.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceIPs.utils.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceTableRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfacesTable.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfacesTableContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/queries/src/linodes/interfaces.ts
  packages/queries/src/linodes/networking.ts
Labels: Approved, Linode Interfaces

#12053 feat: [UIE-8671] - IAM RBAC: facade roles description
  packages/api-v4/.changeset/pr-12053-upcoming-features-1744891132478.md
  packages/api-v4/src/iam/types.ts
  packages/manager/.changeset/pr-12053-upcoming-features-1744891161989.md
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.test.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
  packages/manager/src/features/IAM/Shared/constants.ts
  packages/manager/src/features/IAM/Shared/utilities.test.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
Labels: IAM (Identity & Access Management)

#12067 fix: [M3-9779, M3-9787] - Improve validation and UX for ACL IP Address fields
  packages/manager/.changeset/pr-12067-upcoming-features-1745002359136.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx
Labels: Bug, Approved, LKE-Enterprise

#11988 upcoming: [M3-9739] - Create feature flag for `mtctt2025`
  packages/manager/.changeset/pr-11988-upcoming-features-1744118506514.md
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
Labels: Approved, mtc-tt-2025

#12037 fix: [M3-9584] - No warning message in the volume details page for the restricted users
  packages/manager/.changeset/pr-12037-fixed-1744750096750.md
  packages/manager/src/features/Account/utils.ts
  packages/manager/src/features/Volumes/VolumesLanding.tsx
Labels: Approved, Restricted User Access

#12043 fix: [M3-9522] - Recovery images table headers alignment with data column
  packages/manager/.changeset/pr-12043-tests-1744782995123.md
  packages/manager/cypress/e2e/core/images/images-non-empty-landing-page.spec.ts
  packages/manager/cypress/support/intercepts/images.ts
  packages/manager/src/factories/images.ts
Labels: Testing, Approved

#12050 upcoming: [M3-9740, M3-9280] - Add mocks and update `PlansPanel` to support `mtc-tt-2025` in selected regions
  packages/manager/.changeset/pr-12050-upcoming-features-1744882750715.md
  packages/manager/cypress/e2e/core/databases/create-database.spec.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/factories/types.ts
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTableActionMenu.tsx
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
  packages/manager/src/features/IAM/Shared/RemoveAssignmentConfirmationDialog/RemoveAssignmentConfirmationDialog.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/index.tsx
  packages/manager/src/features/components/PlansPanel/PlanContainer.tsx
  packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
  packages/manager/src/features/components/PlansPanel/constants.ts
  packages/manager/src/features/components/PlansPanel/types.ts
  packages/manager/src/features/components/PlansPanel/utils.test.ts
  packages/manager/src/features/components/PlansPanel/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/queries/src/linodes/networking.ts
  packages/utilities/src/helpers/planNotices.ts
Labels: LKE, Approved, Linodes, mtc-tt-2025

#12062 feat: [UIE-8672, UIE-8702, UIE-8703] - IAM RBAC: fix bugs
  packages/manager/.changeset/pr-12062-upcoming-features-1744990576571.md
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UpdateEntitiesDrawer.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.test.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
  packages/manager/src/features/IAM/Shared/Entities/utils.test.ts
  packages/manager/src/features/IAM/Shared/Entities/utils.ts
  packages/manager/src/features/IAM/Shared/types.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
  packages/manager/src/features/IAM/Users/UserEntities/UserEntities.tsx
  packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
  packages/manager/src/queries/entities/entities.ts
Labels: IAM (Identity & Access Management)

#12085 test [M3-9569]: Fix for OBJ multicluster delete test app crash in DevCloud
  packages/manager/.changeset/pr-12085-tests-1745337050128.md
  packages/manager/cypress/e2e/core/objectStorageMulticluster/bucket-delete-multicluster.spec.ts
Labels: Add'tl Approval Needed

#11942 upcoming: [M3-9513] – Update endpoints, types, and validation for VPC Linode instances
  packages/api-v4/.changeset/pr-11942-upcoming-features-1743626885050.md
  packages/api-v4/src/linodes/types.ts
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreate/schemas.ts
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/SuccessDialogContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/VPCInterface/VPCIPv4Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceDetailsDrawer/VPCInterfaceDetailsContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceIPs.utils.ts
  packages/manager/src/features/VPCs/utils.ts
  packages/manager/src/hooks/useVPCInterface.ts
  packages/utilities/src/factories/linodeConfigInterface.ts
  packages/utilities/src/helpers/getIsLegacyInterfaceArray.ts
  packages/validation/.changeset/pr-11942-upcoming-features-1743626985956.md
  packages/validation/src/linodes.schema.ts
  packages/validation/src/vpcs.schema.ts
Labels: Approved, VPC IPv6

#12076 fix: [M3-9781] - Sizing bug on LKE Tier selection
  packages/manager/.changeset/pr-12076-upcoming-features-1745347113083.md
  packages/manager/src/features/Kubernetes/CreateCluster/ClusterTierPanel.tsx
Labels: Bug, Approved, LKE-Enterprise

#12069 upcoming: [M3-9777] - Add label field when creating a firewall from a template in CreateFirewallDrawer
  packages/manager/.changeset/pr-12069-upcoming-features-1745004654779.md
  packages/manager/cypress/e2e/core/firewalls/create-firewall-custom.spec.ts
  packages/manager/cypress/e2e/core/firewalls/create-firewall-with-template.spec.ts
  packages/manager/src/components/GenerateFirewallDialog/useCreateFirewallFromTemplate.ts
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/TemplateFirewallFields.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/formUtilities.ts
Labels: Approved, Linode Interfaces, Firewalls

#12020 refactor: [M3-9748] - Akamai Design System: Checkbox component - `Sizes`
  packages/manager/.changeset/pr-12020-added-1744609645278.md
  packages/manager/.changeset/pr-12020-tech-stories-1745313505956.md
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/components/SelectableTableRow/SelectableTableRow.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/DisplayAlertResources.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.styles.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.tsx
  packages/manager/src/features/Linodes/CloneLanding/Disks.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Addons/Backups.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Addons/PrivateIP.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetail.tsx
  packages/ui/src/components/Checkbox/Checkbox.stories.tsx
  packages/ui/src/components/Checkbox/Checkbox.tsx
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Design Tokens, Requires UX Approval

#12074 deps: [M3-9804] - Upgrade Vite to 6.3.x
  package.json
  packages/manager/.changeset/pr-12074-tech-stories-1745370110655.md
  packages/manager/.changeset/pr-12074-tech-stories-1745370127666.md
  packages/manager/.changeset/pr-12074-tech-stories-1745370148515.md
  packages/manager/.changeset/pr-12074-tech-stories-1745370166288.md
  packages/manager/.changeset/pr-12074-tech-stories-1745370189196.md
  packages/manager/.changeset/pr-12074-tech-stories-1745370205456.md
  packages/manager/package.json
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsEngineTypeFilter.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/constants.ts
  packages/search/package.json
  pnpm-lock.yaml
Labels: Dependencies

#12075 fix: [M3-9805] - Revert Object Storage Size Conversions from Base10 to Base2
  packages/manager/.changeset/pr-12075-fixed-1745266693581.md
  packages/manager/src/components/Uploaders/FileUpload.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_BucketLanding.tsx
  packages/utilities/src/helpers/unitConversions.ts
Labels: Bug, Object Storage, Approved

#12077 fix: [M3-8289] - Properly encode URL and filenames of files
  packages/manager/src/components/Link.tsx
  packages/manager/src/components/Uploaders/ObjectUploader/ObjectUploader.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/utilities.test.ts
  packages/manager/src/features/ObjectStorage/utilities.ts
Labels: Bug, Approved

#12035 upcoming: [M3-9114] - Add support for Linode Interfaces in Firewalls AddLinodeDrawer
  packages/manager/.changeset/pr-12035-upcoming-features-1744816700425.md
  packages/manager/.changeset/pr-12035-upcoming-features-1745269110510.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddLinodeDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
  packages/manager/src/features/Linodes/LinodeCreate/schemas.ts
  packages/utilities/src/factories/linodeConfigInterface.ts
  packages/utilities/src/helpers/getIsLegacyInterfaceArray.ts
  packages/validation/src/firewalls.schema.ts
  packages/validation/src/vpcs.schema.ts
Labels: Approved, Linode Interfaces, Firewalls

#12024 refactor: [M3-9764] - Application Error Boundaries
  packages/manager/.changeset/pr-12024-changed-1745259666310.md
  packages/manager/eslint.config.js
  packages/manager/src/App.tsx
  packages/manager/src/MainContent.tsx
  packages/manager/src/Router.tsx
  packages/manager/src/assets/icons/zero-state.svg
  packages/manager/src/components/CodeBlock/CodeBlock.styles.ts
  packages/manager/src/features/ErrorBoundary/ErrorBoundaryFallback.test.tsx
  packages/manager/src/features/ErrorBoundary/ErrorBoundaryFallback.tsx
  packages/manager/src/features/ErrorBoundary/ErrorComponent.tsx
  packages/manager/src/features/TheApplicationIsOnFire.tsx
  packages/manager/src/routes/index.tsx
  packages/manager/src/routes/root.ts
Labels: Approved

#12060 refactor: [M3-8977] - Replace `Autocomplete`s with `Select`
  packages/manager/.changeset/pr-12060-tech-stories-1744927614310.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
  packages/manager/cypress/e2e/core/nodebalancers/nodebalancers-create-in-complex-form.spec.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleForm.tsx
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
Labels: Tech Debt

#12080 fix: [M3-9807] - Broken loading state on Linode Transfer Table
  packages/manager/.changeset/pr-12080-fixed-1745318841815.md
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
Labels: Bug, Approved

#12078 Upcoming: [DI-24748] - Show regions based on available resources and dependent filters in CloudPulse dashboards
  packages/manager/.changeset/pr-12078-upcoming-features-1745307427690.md
  packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-dashboard-errors.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/timerange-verification.spec.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
Labels: Cloud Pulse, Cloud Pulse - Dashboards

#12096 upcoming: [DI-24743] - Disabling ability to create based on account limits
  packages/manager/.changeset/pr-12096-upcoming-features-1745425235919.md
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/constants.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertListNoticeMessages.tsx
Labels: Cloud Pulse - Alerting

#12089 deps: [M3-9471] - Clean up unnecessary package resolutions
  package.json
  packages/manager/.changeset/pr-12089-tech-stories-1745429234215.md
  pnpm-lock.yaml
Labels: Dependencies, Approved

#12104 upcoming: [DI-24085] - Added info message for failed alerts
  packages/manager/.changeset/pr-12104-upcoming-features-1745508732060.md
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#12091 change: [DI-24087] - Added last modified by & create date in list & detail
  packages/manager/.changeset/pr-12091-added-1745403784215.md
  packages/manager/cypress/e2e/core/cloudpulse/alert-show-details.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/alerts-listing-page.spec.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetailOverview.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/constants.ts
Labels: Ready for Review, Cloud Pulse, Cloud Pulse - Alerting

#11910 upcoming: [M3-9424] - Review nodebalancers validation schemas
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/src/components/LineGraph/MetricsDisplay.styles.ts
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/utilities/ipUtils.ts
  packages/validation/.changeset/pr-11910-changed-1742903940647.md
  packages/validation/src/nodebalancers.schema.ts
  packages/validation/src/vpcs.schema.ts
Labels: Approved, NB-VPC

#12097 change: [M3-9613, M3-9795] - Replace accordions with papers in Account Settings and fix FirewallRow services column width on FirewallLanding
  packages/manager/.changeset/pr-12097-changed-1745441238928.md
  packages/manager/.changeset/pr-12097-fixed-1745441307930.md
  packages/manager/cypress/e2e/core/account/account-cancellation.spec.ts
  packages/manager/cypress/e2e/core/account/network-settings.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts
  packages/manager/src/components/TableSortCell/TableSortCell.tsx
  packages/manager/src/features/Account/AutoBackups.tsx
  packages/manager/src/features/Account/CloseAccountSetting.test.tsx
  packages/manager/src/features/Account/CloseAccountSetting.tsx
  packages/manager/src/features/Account/DefaultFirewalls.tsx
  packages/manager/src/features/Account/EnableManaged.tsx
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Account/NetworkHelper.tsx
  packages/manager/src/features/Account/NetworkInterfaceType.tsx
  packages/manager/src/features/Account/ObjectStorageSettings.tsx
  packages/manager/src/features/Backups/BackupDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
Labels: Approved, Linode Interfaces

#12082 upcoming: [M3-9772] - Update Linode Create CodeSnippets tool to account for Linode Interfaces
  packages/manager/.changeset/pr-12082-upcoming-features-1745342031960.md
  packages/manager/cypress/e2e/core/linodes/linode-network.spec.ts
  packages/manager/cypress/support/intercepts/linodes.ts
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/CurlTabPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/IntegrationsTabPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/LinodeCLIPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/SDKTabPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceFirewall.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.test.ts
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreate/resolvers.ts
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/AddInterfaceForm.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/utilities.ts
Labels: Linode Interfaces

#12088 test [M3-9574]: Fix for nodebalancer creation test
  packages/manager/.changeset/pr-12088-tests-1745436278227.md
  packages/manager/cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts
Labels: Approved

#12112 fix: [M3-0836] - Wrong history instance for bucket deep navigation
  packages/manager/.changeset/pr-12112-fixed-1745593237854.md
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketBreadcrumb.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketProperties.tsx
Labels: Routing Refactor

#12106 tech-story: [M3-9839] - Update `linode/shared` to not depend on TanStack Query and MUI directly
  packages/queries/.changeset/pr-12106-tech-stories-1745525156110.md
  packages/queries/src/index.ts
  packages/shared/.changeset/pr-12106-tech-stories-1745525093011.md
  packages/shared/package.json
  packages/shared/src/components/LinodeSelect/LinodeSelect.tsx
  packages/shared/src/utilities/wrap.tsx
  packages/ui/.changeset/pr-12106-tech-stories-1745525130129.md
  packages/ui/src/index.ts
  pnpm-lock.yaml
Labels: Dependencies, Modularization

#12072 fix: [M3-9642] - Hover state for Close Icon and replaced imports
  packages/manager/.changeset/pr-12072-fixed-1745232908003.md
  packages/manager/src/components/EditableEntityLabel/EditableInput.tsx
  packages/manager/src/components/MainContentBanner.tsx
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
  packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsListTable.tsx
  packages/manager/src/components/Tag/Tag.tsx
  packages/manager/src/components/TagsInput/TagsInput.tsx
  packages/manager/src/dev-tools/DevTools.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferCheckoutBar.styles.ts
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ImageRegionRow.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummaryItem.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/LabelsAndTaints/LabelTable.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/LabelsAndTaints/TaintTable.tsx
  packages/manager/src/features/Linodes/CloneLanding/Details.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPCRanges.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppDetailDrawer.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionList.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPCRanges.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerSelect.tsx
  packages/manager/src/features/Support/AttachFileListItem.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/VPCs/VPCCreate/SubnetNode.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/ui/src/components/Autocomplete/Autocomplete.stories.tsx
  packages/ui/src/components/DialogTitle/DialogTitle.tsx
  packages/ui/src/components/Drawer/Drawer.tsx
  packages/ui/src/components/EditableText/EditableText.tsx
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Bug, Approved

#12101 fix: [M3-9831] - Broken Payment Method `Default` Chip in the Make a Payment Drawer
  packages/manager/.changeset/pr-12101-fixed-1745467362526.md
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
Labels: Bug, Approved

#12110 upcoming:[DI-24467] - Update group_by type in widgets and metrics request
  packages/api-v4/.changeset/pr-12110-upcoming-features-1745583476204.md
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-12110-upcoming-features-1745583351428.md
  packages/manager/src/factories/dashboards.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Cloud Pulse - Dashboards

#12116 fix: [UIE-8684] - save button text fix, error message for Autocomplete, validation
  packages/manager/.changeset/pr-12116-fixed-1745838194419.md
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfigurationDrawer.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/utilities.ts
  packages/validation/.changeset/pr-12116-added-1745838363692.md
  packages/validation/src/databases.schema.ts
Labels: Add'tl Approval Needed, 🚨 Urgent, DBaaS, Approved

#12118 change: [M3-9852] - Deprecate DeletionDialog
  packages/manager/.changeset/pr-12118-changed-1745854078468.md
  packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
Labels: Ready for Review

#12083 test: [M3-9177] - Cypress test to confirm Linode config dialog changes for Linode interfaces
  packages/manager/.changeset/pr-12083-tests-1745333883299.md
  packages/manager/cypress/e2e/core/linodes/create-linode-with-vpc.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/cypress/support/intercepts/configs.ts
  packages/manager/cypress/support/util/linodes.ts
Labels: Approved, Ready for Review, Linode Interfaces

#12107 fix: [M3-9840] - Add `ThemeWrapper` to fix failing tests in shared package
  packages/shared/.changeset/pr-12107-fixed-1745525630718.md
  packages/shared/src/components/LinodeSelect/LinodeSelect.test.tsx
  packages/shared/src/components/LinodeSelect/LinodeSelect.tsx
  packages/shared/src/utilities/wrap.tsx
Labels: Ready for Review, Modularization

#12117 test: [M3-9179] - Add cypress tests for adding Linodes to firewalls
  packages/manager/.changeset/pr-12117-tests-1745841831406.md
  packages/manager/cypress/e2e/core/firewalls/add-device-to-firewall.spec.ts
  packages/manager/cypress/support/intercepts/firewalls.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddLinodeDrawer.tsx
Labels: Testing, Approved, Linode Interfaces

#12125 feat: [UIE-8143] - IAM RBAC - Merge form-selected roles into existing roles for backend PUT call
  packages/manager/.changeset/pr-12125-added-1745931455893.md
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.test.tsx
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesActionMenu.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesActionMenu.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UnassignRoleConfirmationDialog.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UnassignRoleConfirmationDialog.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UpdateEntitiesDrawer.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UpdateEntitiesDrawer.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/utils.test.ts
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/utils.ts
  packages/manager/src/features/IAM/Shared/types.ts
  packages/manager/src/features/IAM/Shared/utilities.test.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.test.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
  packages/manager/src/features/IAM/hooks/useCalculateHiddenItems.ts
Labels: 🚨 Urgent, Approved, IAM (Identity & Access Management)

#12126 change: [UIE-8841] - custom validation for net_buffer_length
  packages/validation/.changeset/pr-12126-added-1745937083422.md
  packages/validation/src/databases.schema.ts
Labels: 🚨 Urgent, DBaaS, Approved

#12098 change: [M3-9809] - Notice paper and list spacing
  packages/manager/.changeset/pr-12098-changed-1745515258326.md
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.stories.tsx
  packages/manager/src/components/Encryption/Encryption.tsx
  packages/manager/src/components/ErrorMessage.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeKubernetesVersionBanner.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Backups/BackupsWarning.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Clone/CloneWarning.tsx
  packages/manager/src/features/Linodes/LinodesDetail/VolumesUpgradeBanner.tsx
  packages/manager/src/features/Linodes/MigrateLinode/CautionNotice.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeActionNotice.tsx
  packages/ui/src/components/Notice/Notice.stories.tsx
  packages/ui/src/components/Notice/Notice.styles.ts
  packages/ui/src/components/Notice/Notice.test.tsx
  packages/ui/src/components/Notice/Notice.tsx
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Design Tokens, Requires UX Approval

#12100 tech-story: [M3-8667] - Add eslint rule to to prevent import of Cypress code in main application
  packages/manager/.changeset/pr-12100-tech-stories-1745464783439.md
  packages/manager/eslint.config.js
Labels: Testing, Approved

#12120 fix: [M3-9856] - Fix text layout for `Notice`s with multiple children
  packages/manager/.changeset/pr-12120-tech-stories-1745864893717.md
  packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
  packages/ui/.changeset/pr-12120-fixed-1745864924644.md
  packages/ui/src/components/Notice/Notice.tsx
Labels: Bug, Approved, Design Tokens

#12122 upcoming: [M3-9830, M3-9848] - Linode Interface touchups/fixes for UpgradeInterface dialog, useVPCConfigInterface, PublicIPAddressesTooltip and NetworkInterfaceType
  packages/manager/.changeset/pr-12122-fixed-1745938870454.md
  packages/manager/.changeset/pr-12122-upcoming-features-1745938720819.md
  packages/manager/.changeset/pr-12122-upcoming-features-1745938794724.md
  packages/manager/src/features/Account/NetworkInterfaceType.tsx
  packages/manager/src/features/Linodes/AccessTable.test.tsx
  packages/manager/src/features/Linodes/AccessTable.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/UpgradeInterfacesDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/useUpgradeToLinodeInterfaces.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetail.tsx
  packages/manager/src/features/Linodes/LinodesLanding/IPAddress.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/IPAddress.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/Linodes/PublicIPAddressesTooltip.tsx
  packages/manager/src/hooks/useVPCConfigInterface.ts
Labels: 🚨 Urgent, Approved, Linode Interfaces

#12079 Upcoming: [DI-24747] - Pass filters from widgets using dashboards API call
  packages/manager/.changeset/pr-12079-upcoming-features-1745312844211.md
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/src/factories/dashboards.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Ready for Review, Cloud Pulse, Cloud Pulse - Dashboards

#12073 change: [M3-9205] - Add Kubernetes CRUD support to MSW 2.0
  packages/manager/.changeset/pr-12073-tech-stories-1745358168782.md
  packages/manager/src/dev-tools/dev-tools.css
  packages/manager/src/dev-tools/load.ts
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/mocks/mockState.ts
  packages/manager/src/mocks/presets/baseline/crud.ts
  packages/manager/src/mocks/presets/crud/handlers/kubernetes.ts
  packages/manager/src/mocks/presets/crud/kubernetes.ts
  packages/manager/src/mocks/presets/crud/seeds/index.ts
  packages/manager/src/mocks/presets/crud/seeds/kubernetes.ts
  packages/manager/src/mocks/presets/crud/seeds/utils.ts
  packages/manager/src/mocks/types.ts
Labels: LKE, Approved

#12071 upcoming: [M3-9691] - Quotas for Object Storage
  packages/api-v4/src/quotas/types.ts
  packages/manager/src/factories/quotas.ts
  packages/manager/src/features/Account/Quotas/Quotas.test.tsx
  packages/manager/src/features/Account/Quotas/Quotas.tsx
  packages/manager/src/features/Account/Quotas/QuotasIncreaseForm.test.tsx
  packages/manager/src/features/Account/Quotas/QuotasIncreaseForm.tsx
  packages/manager/src/features/Account/Quotas/QuotasTable.test.tsx
  packages/manager/src/features/Account/Quotas/QuotasTable.tsx
  packages/manager/src/features/Account/Quotas/QuotasTableRow.tsx
  packages/manager/src/features/Account/Quotas/utils.test.tsx
  packages/manager/src/features/Account/Quotas/utils.ts
  packages/manager/src/mocks/presets/crud/handlers/quotas.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: 🚨 Urgent, Approved

#12129 upcoming: [M3-9868, M3-9850] - UX Refinements and Copy updates for Linode Interfaces on the Linode create flow
  packages/manager/.changeset/pr-12129-upcoming-features-1746039836052.md
  packages/manager/cypress/e2e/core/linodes/create-linode-with-vlan.spec.ts
  packages/manager/src/features/Linodes/LinodeCreate/Addons/PrivateIP.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceGeneration.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceType.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/LinodeInterface.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/LinodeInterface.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/Networking.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VLAN.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VLANAvailabilityNotice.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPC.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPCAvailabilityNotice.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPCRanges.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreate/VLAN/VLAN.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VLAN/VLAN.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VLAN/VLANAvailabilityNotice.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
Labels: 🚨 Urgent, Approved, Linode Interfaces

#12131 upcoming: [M3-9403] - Update copies for Linode Interfaces: Linode Details, Account Settings, Firewalls
  packages/manager/.changeset/pr-12131-upcoming-features-1746029056502.md
  packages/manager/cypress/e2e/core/firewalls/create-firewall-with-template.spec.ts
  packages/manager/src/features/Account/DefaultFirewalls.test.tsx
  packages/manager/src/features/Account/DefaultFirewalls.tsx
  packages/manager/src/features/Account/NetworkInterfaceType.test.tsx
  packages/manager/src/features/Account/NetworkInterfaceType.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddLinodeDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/PublicTemplateRules.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/TemplateFirewallFields.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/TemplateFirewallFields.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/VPCTemplateRules.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/constants.ts
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/ConfigSelectDialogContent.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/ConfigSelectDialogContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/ErrorDialogContent.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/ErrorDialogContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/PromptDialogContent.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/PromptDialogContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/SuccessDialogContent.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/SuccessDialogContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/UpgradeInterfacesDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/constants.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/AddInterfaceForm.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/EditInterfaceForm.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/PublicInterface/IPv6Ranges.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceDetailsDrawer/InterfaceDetailsDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceSettingsForm.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaces.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/ui/src/components/Dialog/Dialog.tsx
  packages/ui/src/components/DialogTitle/DialogTitle.tsx
Labels: 🚨 Urgent, Approved, Linode Interfaces
