Repository linode/manager, pull requests merged in 2025-02, with the labels that each got.

#11563 upcoming: [M3-9155] Add billing agreement checkbox for tax id
  packages/api-v4/.changeset/pr-11563-added-1737734348416.md
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-11563-upcoming-features-1737734387143.md
  packages/manager/cypress/e2e/core/billing/billing-contact.spec.ts
  packages/manager/cypress/e2e/core/general/gdpr-agreement.spec.ts
  packages/manager/cypress/support/intercepts/account.ts
  packages/manager/src/factories/accountAgreements.ts
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/Billing/constants.ts
Labels: e2e, Approved

#11578 refactor: [M3-9157] - TanStack Router Migration for Images Feature
  packages/manager/.changeset/pr-11578-tech-stories-1738275626195.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
  packages/manager/cypress/e2e/core/images/manage-image-regions.spec.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.test.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageCreateContainer.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesCreate/index.ts
  packages/manager/src/features/Images/ImagesLanding/EditImageDrawer.test.tsx
  packages/manager/src/features/Images/ImagesLanding/EditImageDrawer.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRow.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesActionMenu.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLandingEmptyState.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLandingEmptyState.tsx
  packages/manager/src/features/Images/ImagesLanding/RebuildImageDrawer.test.tsx
  packages/manager/src/features/Images/ImagesLanding/RebuildImageDrawer.tsx
  packages/manager/src/features/Images/constants.ts
  packages/manager/src/features/Images/index.tsx
  packages/manager/src/routes/images/imagesLazyRoutes.ts
  packages/manager/src/routes/images/index.ts
  packages/manager/src/routes/index.tsx
Labels: Approved, Routing Refactor

#11583 DI-23201 : Add scaffolding for new edit resource component for system alerts in CloudPulse alerting
  packages/api-v4/.changeset/pr-11583-upcoming-features-1738238193677.md
  packages/api-v4/src/cloudpulse/alerts.ts
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-11583-upcoming-features-1738238243389.md
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertActionMenu.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/DisplayAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertResourceUtils.test.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertResourceUtils.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertsActionMenu.ts
  packages/manager/src/queries/cloudpulse/alerts.ts
  packages/manager/src/queries/cloudpulse/resources.ts
Labels: Approved, Ready for Review, Cloud Pulse, Cloud Pulse - Alerting

#11590 feat: [UIE-8372] - database migration event notification
  packages/api-v4/.changeset/pr-11590-added-1738256458071.md
  packages/api-v4/src/account/types.ts
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-11590-added-1738256866553.md
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseStatusDisplay.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/features/Events/factories/database.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: DBaaS, Approved

#11589 feat: [M3-9197] - Collapsible Node Pool tables & filterable status
  packages/manager/.changeset/pr-11589-added-1738345796763.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.styles.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/ui/src/foundations/themes/light.ts
Labels: LKE, Approved, LKE-Enterprise

#11592 fix: [M3-9069] - Copy Token behavior on LKE details page
  packages/manager/.changeset/pr-11592-fixed-1738326763592.md
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
  packages/ui/src/components/CircleProgress/CircleProgress.tsx
Labels: Bug, LKE, Approved

#11593 refactor: [M3-8256] - Remove `ramda` from Managed
  packages/manager/.changeset/pr-11593-tech-stories-1738564796090.md
  packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
  packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx
  packages/manager/src/features/Managed/MonitorDrawer.tsx
Labels: Approved, Tech Debt

#11597 upcoming: [M3-9224] - Limits evolution: revise types, queries and mock data
  packages/api-v4/.changeset/pr-11597-upcoming-features-1738601486075.md
  packages/api-v4/src/quotas/quotas.ts
  packages/api-v4/src/quotas/types.ts
  packages/manager/.changeset/pr-11597-upcoming-features-1738601515225.md
  packages/manager/src/factories/quotas.ts
  packages/manager/src/mocks/presets/crud/handlers/quotas.ts
  packages/manager/src/queries/quotas/quotas.ts
Labels: Approved, Limits

#11595 feat: [UIE-8422] - database migration banner
  packages/manager/.changeset/pr-11595-added-1738590003764.md
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
  packages/manager/src/features/GlobalNotifications/DatabaseMigrationInfoBanner.tsx
Labels: DBaaS, Approved

#11599 fix: [M3-9235] - Longview Detail id param not found locally
  packages/manager/.changeset/pr-11599-fixed-1738615199594.md
  packages/manager/src/routes/longview/longviewLazyRoutes.tsx
Labels: Approved, Routing Refactor

#11585 test: [M3-9142] - Add Cypress test for Service Transfers empty state
  packages/manager/.changeset/pr-11585-tests-1738677917619.md
  packages/manager/cypress/e2e/core/account/service-transfer.spec.ts
Labels: Testing, Approved

#11612 test: [M3-9244] - Upgrade to Vitest 3.0.5
  package.json
  packages/manager/.changeset/pr-11612-tech-stories-1738701099324.md
  yarn.lock
Labels: Dependencies, Approved, Ready for Review

#11598 change: [M3-9232] - Clean up `disallowImageUploadToNonObjRegions` flag and add `ignoreAccountAvailability` prop to `RegionMultiSelect`
  packages/manager/.changeset/pr-11598-changed-1738606647435.md
  packages/manager/.changeset/pr-11598-tech-stories-1738606544178.md
  packages/manager/.changeset/pr-11598-tech-stories-1738606600844.md
  packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.tsx
Labels: Approved, Image Service Gen2

#11579 feat: [M3-9167] - Image Encryption Information
  packages/manager/.changeset/pr-11579-added-1738162685405.md
  packages/manager/.changeset/pr-11579-tech-stories-1738162742130.md
  packages/manager/src/assets/icons/unlock.svg
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.test.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRow.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRow.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.test.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/routes/images/ImagesRoute.tsx
Labels: Approved, Images

#11602 deps: [M3-9237] - Update `markdown-it` to v14
  packages/manager/.changeset/pr-11602-tech-stories-1738634748360.md
  packages/manager/package.json
  yarn.lock
Labels: Dependencies, Approved

#11617 fix: Disabled button in Collapsible Node Pool Accordion
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/components/ActionMenu/ActionMenu.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
Labels: Bug, LKE, Approved

#11566 upcoming: [M3-9090] - Update existing `v4/linodes/instances` endpoints and types for Linode Interfaces project
  packages/api-v4/.changeset/pr-11566-upcoming-features-1738092202608.md
  packages/api-v4/src/firewalls/types.ts
  packages/api-v4/src/linodes/configs.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-linodes-update.spec.ts
  packages/manager/src/__data__/linodes.ts
  packages/manager/src/factories/linodeConfigInterfaceFactory.ts
  packages/manager/src/factories/linodeInterface.ts
  packages/manager/src/factories/linodes.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
  packages/manager/src/features/Linodes/LinodeCreate/utilities.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
  packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx
  packages/manager/src/features/Linodes/LinodesLanding/ListView.tsx
  packages/manager/src/features/Linodes/LinodesLanding/utils.ts
  packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/utils.ts
  packages/manager/src/hooks/useVPCConfigInterface.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/utilities/codesnippets/generate-ansibleConfig.ts
  packages/manager/src/utilities/codesnippets/generate-pythonSDKSnippet.test.ts
  packages/manager/src/utilities/codesnippets/generate-pythonSDKSnippet.ts
  packages/manager/src/utilities/codesnippets/generate-terraformConfig.test.ts
  packages/manager/src/utilities/codesnippets/generate-terraformConfig.ts
  packages/manager/src/utilities/configs.test.ts
  packages/manager/src/utilities/configs.ts
  packages/validation/.changeset/pr-11566-upcoming-features-1738092236934.md
  packages/validation/src/linodes.schema.ts
Labels: Approved, Linode Interfaces

#11215 refactor: [M3-8843] - StackScript Landing page
  packages/manager/.changeset/pr-11215-changed-1738603808282.md
  packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/smoke-stackscripts-landing-page.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/update-stackscripts.spec.ts
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionList.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionRow.tsx
  packages/manager/src/features/StackScripts/CommonStackScript.styles.ts
  packages/manager/src/features/StackScripts/Partials/StackScriptSearchHelperText.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptsEmptyLandingPage.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptActionMenu.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptDeleteDialog.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptLandingTable.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptMakePublicDialog.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptRow.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptsLanding.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptActionMenu.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanelContent.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx
  packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptsSection.tsx
  packages/manager/src/features/StackScripts/StackScripts.tsx
  packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
  packages/manager/src/features/StackScripts/StackScriptsLanding.test.tsx
  packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
  packages/manager/src/features/StackScripts/stackScriptUtils.test.ts
  packages/manager/src/features/StackScripts/stackScriptUtils.ts
  packages/manager/src/features/StackScripts/types.ts
  packages/manager/src/queries/stackscripts.ts
  packages/manager/src/routes/stackscripts/index.tsx
Labels: Approved, Ready for Review, StackScripts

#11573 upcoming: [DI-23083] - Migrated CloudPulseTimeRangeSelect to DateTimeRangePicker
  packages/api-v4/.changeset/pr-11573-upcoming-features-1738066060175.md
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-11573-upcoming-features-1738066869988.md
  packages/manager/src/components/DatePicker/DateTimePicker.tsx
  packages/manager/src/components/DatePicker/DateTimeRangePicker.test.tsx
  packages/manager/src/components/DatePicker/DateTimeRangePicker.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.test.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/CloudPulseDateTimePickerUtils.ts
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.test.ts
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.test.ts
  packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.test.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidgetRenderer.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDateTimeRangePicker.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseMonitor/DatabaseMonitor.test.tsx
  packages/ui/.changeset/pr-11573-upcoming-features-1738670291812.md
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Cloud Pulse, Cloud Pulse - Dashboards

#11596 test: [DI-22613] - ACLP: Automate Resource Details and Notification Changes with enhanced test coverage
  packages/manager/.changeset/pr-11596-tests-1738650165686.md
  packages/manager/cypress/e2e/core/cloudpulse/alert-show-details.spec.ts
  packages/manager/cypress/support/intercepts/cloudpulse.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#11615 upcoming: [DI-22941] - Update dependency and order for tags
  packages/manager/.changeset/pr-11615-upcoming-features-1738754714037.md
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTagsFilter.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTagsFilter.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Add'tl Approval Needed, Cloud Pulse - Dashboards

#11594 test: [M3-8914] - POC: Centralized Locators for Linode Page in Cypress UI Automation Framework
  packages/manager/.changeset/pr-11594-tests-1738582940572.md
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/cypress/support/ui/locators/common-locators.ts
  packages/manager/cypress/support/ui/locators/linode-locators.ts
  packages/manager/cypress/support/ui/main-search.ts
Labels: Testing, Approved

#11605 feat: [UIE-8135] - IAM RBAC: add new assign panel component
  packages/manager/.changeset/pr-11605-upcoming-features-1738668460766.md
  packages/manager/src/factories/accountPermissions.ts
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.style.ts
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
  packages/manager/src/features/IAM/Shared/utilities.test.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx
  packages/manager/src/features/IAM/Users/UserRoles/UserRoles.test.tsx
  packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
Labels: IAM (Identity & Access Management)

#11611 refactor: [M3-9241] - Improve Syntax Highlighting
  packages/manager/.changeset/pr-11611-changed-1738687196459.md
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/cypress/e2e/core/notificationsAndEvents/events-fetching.spec.ts
  packages/manager/cypress/support/cypress-exports.ts
  packages/manager/cypress/support/stubs/sequential-stub.ts
  packages/manager/cypress/support/ui/common.ts
  packages/manager/cypress/support/util/paginate.ts
  packages/manager/cypress/support/util/request.ts
  packages/manager/cypress/support/util/response.ts
  packages/manager/cypress/tsconfig.json
  packages/manager/package.json
  packages/manager/src/assets/icons/download.svg
  packages/manager/src/components/CodeBlock/CodeBlock.stories.tsx
  packages/manager/src/components/CodeBlock/CodeBlock.styles.ts
  packages/manager/src/components/CodeBlock/CodeBlock.tsx
  packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.test.tsx
  packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.tsx
  packages/manager/src/components/HighlightedMarkdown/__snapshots__/HighlightedMarkdown.test.tsx.snap
  packages/manager/src/components/Markdown/Markdown.stories.tsx
  packages/manager/src/components/Markdown/Markdown.test.tsx
  packages/manager/src/components/Markdown/Markdown.tsx
  packages/manager/src/components/Markdown/__snapshots__/Markdown.test.tsx.snap
  packages/manager/src/components/ProductInformationBanner/ProductInformationBanner.tsx
  packages/manager/src/components/ScriptCode/ScriptCode.test.tsx
  packages/manager/src/components/ScriptCode/ScriptCode.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
  packages/manager/src/features/Betas/BetaSignup.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/CurlTabPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/IntegrationsTabPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/LinodeCLIPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/SDKTabPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptDetailsDialog.test.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/MarkdownReference.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/PreviewReply.tsx
  packages/manager/src/features/Support/TicketDetailText.tsx
  packages/manager/src/formatted-text.css
  packages/manager/src/index.css
  packages/manager/src/index.tsx
  packages/manager/src/utilities/codesnippets/generate-ansibleConfig.test.ts
  packages/manager/src/utilities/codesnippets/generate-ansibleConfig.ts
  packages/manager/src/utilities/codesnippets/generate-goSDKSnippet.test.ts
  packages/manager/src/utilities/codesnippets/generate-goSDKSnippet.ts
  packages/manager/src/utilities/codesnippets/generate-pythonSDKSnippet.test.ts
  packages/manager/src/utilities/codesnippets/generate-pythonSDKSnippet.ts
  packages/manager/src/utilities/codesnippets/generate-terraformConfig.test.ts
  packages/manager/src/utilities/codesnippets/generate-terraformConfig.ts
  packages/manager/src/utilities/markdown.ts
  packages/manager/src/utilities/sanitizeHTML.ts
  packages/manager/src/utilities/syntax-highlighter.ts
  packages/manager/src/utilities/testHelpers.tsx
  yarn.lock
Labels: Enhancement, Approved

#11616 change: [UIE-8440] - Allow more symbols to be used in Search v2
  packages/search/src/search.peggy
  packages/search/src/search.test.ts
Labels: Search, IAM (Identity & Access Management)

#11613 DI-23223: Update the EditAlertResources component to save the added / removed resources and Show only selected resources
  packages/api-v4/.changeset/pr-11613-upcoming-features-1738762902787.md
  packages/api-v4/src/cloudpulse/alerts.ts
  packages/manager/.changeset/pr-11613-upcoming-features-1738724859180.md
  packages/manager/src/factories/cloudpulse/alerts.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResourcesNotice.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/DisplayAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResourcesConfirmationDialog.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertResourceUtils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/alerts.ts
  packages/manager/src/queries/cloudpulse/queries.ts
Labels: Approved, Ready for Review, Cloud Pulse, Cloud Pulse - Alerting

#11580 test: [M3-8625] - Create linode in a core region with Gecko
  packages/manager/.changeset/pr-11580-tests-1738132129968.md
  packages/manager/cypress/e2e/core/linodes/create-linode-in-core-region.spec.ts
Labels: Testing, Approved

#11600 tech-story: [M3-9099] - Add MSW crud support for VPCs for Linode Interfaces project
  packages/manager/.changeset/pr-11600-tech-stories-1738787965596.md
  packages/manager/src/dev-tools/load.ts
  packages/manager/src/factories/vpcs.ts
  packages/manager/src/mocks/indexedDB.ts
  packages/manager/src/mocks/mockState.ts
  packages/manager/src/mocks/presets/baseline/crud.ts
  packages/manager/src/mocks/presets/crud/handlers/firewalls.ts
  packages/manager/src/mocks/presets/crud/handlers/vpcs.ts
  packages/manager/src/mocks/presets/crud/seeds/index.ts
  packages/manager/src/mocks/presets/crud/seeds/utils.ts
  packages/manager/src/mocks/presets/crud/seeds/vpcs.ts
  packages/manager/src/mocks/presets/crud/vpcs.ts
  packages/manager/src/mocks/types.ts
Labels: Approved, Linode Interfaces

#11588 feat: [UIE-8139] - IAM RBAC: add new assigned entities table component part 1
  packages/api-v4/.changeset/pr-11588-upcoming-features-1738244661751.md
  packages/api-v4/src/iam/types.ts
  packages/manager/.changeset/pr-11588-upcoming-features-1738244711758.md
  packages/manager/src/factories/userPermissions.ts
  packages/manager/src/features/IAM/Shared/AssignedEntitiesTable/AssignedEntitiesTable.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedEntitiesTable/AssignedEntitiesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserDetails/UserProfile.tsx
  packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
  packages/manager/src/features/IAM/Users/UserEntities/UserEntities.tsx
  packages/manager/src/features/IAM/Users/UsersTable/UsersActionMenu.test.tsx
  packages/manager/src/features/IAM/Users/UsersTable/UsersActionMenu.tsx
  packages/manager/src/queries/iam/iam.ts
Labels: Approved, IAM (Identity & Access Management)

#11404 feat: [M3-8792] - Improve Consistency of Notice Error States
  packages/manager/.changeset/pr-11404-tech-stories-1733950330771.md
  packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
  packages/manager/src/components/Dialog/Dialog.tsx
  packages/manager/src/features/Account/ObjectStorageSettings.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentBits/CreditCardDialog.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PromoDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsReviewUpdatesDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsUpgradeVersionDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
  packages/manager/src/features/Support/AttachFileForm.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/manager/src/features/Volumes/Dialogs/DeleteVolumeDialog.tsx
  packages/manager/src/features/Volumes/Dialogs/DetachVolumeDialog.tsx
Labels: Add'tl Approval Needed, Ready for Review

#11604 fix: [9144] - Remove duplicate options in support search
  packages/manager/.changeset/pr-11604-fixed-1738652958345.md
  packages/manager/src/features/Help/SearchHOC.tsx
Labels: Bug, Approved

#11622 docs: [NO-TICKET] - Update ReadMe: Getting Started OAuth Token Step
  docs/GETTING_STARTED.md
  packages/manager/.changeset/pr-11622-changed-1738868106892.md
Labels: Approved, Documentation

#11601 refactor: [M3-6902] - So long react-select 🎉
  packages/manager/.changeset/pr-11601-tech-stories-1738695641743.md
  packages/manager/cypress/e2e/core/billing/billing-contact.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-disk-encryption.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/placement-groups-linode-assignment.spec.ts
  packages/manager/cypress/support/ui/index.ts
  packages/manager/cypress/support/ui/select.ts
  packages/manager/package.json
  packages/manager/src/GoTo.tsx
  packages/manager/src/__data__/searchResults.ts
  packages/manager/src/components/Dialog/Dialog.tsx
  packages/manager/src/components/EnhancedSelect/EnhancedSelect.css
  packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.tsx
  packages/manager/src/components/EnhancedSelect/Select.styles.ts
  packages/manager/src/components/EnhancedSelect/Select.tsx
  packages/manager/src/components/EnhancedSelect/__mocks__/Select.tsx
  packages/manager/src/components/EnhancedSelect/components/DropdownIndicator.tsx
  packages/manager/src/components/EnhancedSelect/components/Guidance.tsx
  packages/manager/src/components/EnhancedSelect/components/Input.tsx
  packages/manager/src/components/EnhancedSelect/components/LoadingIndicator.tsx
  packages/manager/src/components/EnhancedSelect/components/MenuList.tsx
  packages/manager/src/components/EnhancedSelect/components/MultiValueLabel.tsx
  packages/manager/src/components/EnhancedSelect/components/MultiValueRemove.tsx
  packages/manager/src/components/EnhancedSelect/components/NoOptionsMessage.tsx
  packages/manager/src/components/EnhancedSelect/components/Option.tsx
  packages/manager/src/components/EnhancedSelect/components/SelectControl.tsx
  packages/manager/src/components/EnhancedSelect/components/SelectPlaceholder.tsx
  packages/manager/src/components/EnhancedSelect/components/SingleValue.tsx
  packages/manager/src/components/EnhancedSelect/index.tsx
  packages/manager/src/components/IPSelect/IPSelect.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.test.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.style.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/ScheduleSettings.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/Apache.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINX.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkLanding.tsx
  packages/manager/src/features/Longview/shared/TimeRangeSelect.tsx
  packages/manager/src/features/Managed/MonitorDrawer.tsx
  packages/manager/src/features/Search/ResultGroup.tsx
  packages/manager/src/features/Search/ResultRow.tsx
  packages/manager/src/features/Search/types.ts
  packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedMultiSelect.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.test.tsx
  packages/manager/src/features/Users/UserPermissions.styles.ts
  packages/manager/src/utilities/getSelectedOptionFromGroupedOptions.ts
  packages/manager/src/utilities/tagUtils.ts
  packages/ui/src/components/Select/Select.tsx
  yarn.lock
Labels: Approved, Tech Debt

#11628 fix: [UIE-8446] - restore backup date and time fix
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/features/GlobalNotifications/DatabaseMigrationInfoBanner.tsx
Labels: Bug, DBaaS, Approved

#11631 fix: [DI-23411] - Updated preference key for date time range picker
  packages/manager/.changeset/pr-11631-added-1738936959631.md
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/constants.ts
Labels: Approved

#11625 test: [M3-7112] - Add invoice generation tests for PdfGenerator.ts
  packages/manager/.changeset/pr-11625-tests-1738838917529.md
  packages/manager/package.json
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.test.ts
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.test.ts
  packages/manager/src/features/Billing/PdfGenerator/utils.ts
  yarn.lock
Labels: Dependencies, Approved, Unit tests

#11630 upcoming: [DI-23226] - Add engine type filter in the resources section of CloudPulse alerting for DBaaS
  packages/manager/.changeset/pr-11630-upcoming-features-1739192880293.md
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsEngineTypeFilter.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsEngineTypeFilter.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResourcesFilterRenderer.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResourcesFilterRenderer.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/DisplayAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/constants.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/types.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertResourceUtils.ts
  packages/manager/src/features/CloudPulse/Alerts/constants.ts
  packages/manager/src/queries/cloudpulse/resources.ts
Labels: Approved, Ready for Review, Cloud Pulse, Cloud Pulse - Alerting

#11642 upcoming: [DI-23225] - Add implicit type filter for dbaas resources fetch call in cloudpulse alerts resources section
  packages/api-v4/.changeset/pr-11642-upcoming-features-1739238905252.md
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-11642-upcoming-features-1739238872529.md
  packages/manager/src/factories/cloudpulse/alerts.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.tsx
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#11634 refactor: [M3-9130] - Replace `data-test-id` attributes with `data-testid` and add eslint rules
  packages/manager/.changeset/pr-11634-tech-stories-1739173865935.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/e2e/core/notificationsAndEvents/events.spec.ts
  packages/manager/cypress/e2e/core/notificationsAndEvents/notifications.spec.ts
  packages/manager/src/components/DeletionDialog/DeletionDialog.test.tsx
  packages/manager/src/features/Events/EventRow.tsx
  packages/manager/src/features/NotificationCenter/Notifications/NotificationCenterNotificationMessage.tsx
  packages/manager/src/features/NotificationCenter/Notifications/NotificationCenterNotifications.tsx
  packages/ui/.changeset/pr-11634-tech-stories-1739192088418.md
  packages/ui/.eslintrc.json
Labels: Approved

#11635 fix: [M3-9078] - Ensure document titles for all pages have appropriate keywords
  packages/manager/.changeset/pr-11635-fixed-1739187388251.md
  packages/manager/src/features/Account/AccountLogins.tsx
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Betas/BetasLanding.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Events/EventsLanding.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Firewalls/index.tsx
  packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLandingEmptyState.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLandingEmptyState.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
  packages/manager/src/routes/images/ImagesRoute.tsx
  packages/manager/src/routes/placementGroups/PlacementGroupsRoute.tsx
Labels: Approved, Ready for Review

#11620 Refactor: [M3-9249] - Convert Logout and OAuth to functional components
  packages/manager/.changeset/pr-11620-tech-stories-1738782536719.md
  packages/manager/src/layouts/Logout.tsx
  packages/manager/src/layouts/OAuth.test.tsx
  packages/manager/src/layouts/OAuth.tsx
Labels: Approved, Routing Refactor

#11636 feat: [M3-9019] - Improved NodeBalancer copy and helper text
  packages/manager/.changeset/pr-11636-added-1739206010427.md
  packages/manager/src/features/NodeBalancers/NodeBalancerActiveCheck.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerPassiveCheck.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerPassiveCheck.tsx
  packages/manager/src/features/NodeBalancers/constants.ts
  packages/manager/src/features/NodeBalancers/utils.ts
  packages/ui/src/components/Autocomplete/Autocomplete.tsx
Labels: Approved, NodeBalancers

#11640 upcoming: [M3-9104] - Implement Network Interfaces accordion in Account Settings
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-11640-upcoming-features-1739304484421.md
  packages/manager/src/factories/accountSettings.ts
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Account/NetworkInterfaceType.test.tsx
  packages/manager/src/features/Account/NetworkInterfaceType.tsx
  packages/manager/src/features/NodeBalancers/constants.ts
  packages/ui/src/components/Accordion/Accordion.tsx
Labels: Approved, Linode Interfaces

#11627 refactor: [M3-6675] - Remove span from button component
  packages/manager/.changeset/pr-11627-removed-1738841591644.md
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/cypress/support/ui/locators/linode-locators.ts
  packages/manager/src/features/Account/CloseAccountSetting.test.tsx
  packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
  packages/ui/src/components/Button/Button.tsx
Labels: Approved, Ready for Review

#11643 upcoming: [DI-21796] - Make node type filter dynamic based on cluster size
  packages/manager/.changeset/pr-11643-upcoming-features-1739246456461.md
  packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-dashboard-errors.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.test.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/Utils/constants.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseNodeTypeFilter.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseNodeTypeFilter.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Cloud Pulse - Dashboards

#11644 test: [M3-9251] - Add payment generation tests for PdfGenerator.ts
  packages/manager/.changeset/pr-11644-tests-1739256775104.md
  packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.test.ts
Labels: Approved, Unit tests

#11606 refactor: [M3-8250] - Remove ramda from Longview
  packages/manager/.changeset/pr-11606-removed-1738669494756.md
  packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-dashboard-errors.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/Longview/__mocks__/request.ts
  packages/manager/src/features/Longview/request.ts
  packages/manager/src/features/Longview/shared/TimeRangeSelect.tsx
  packages/manager/src/features/Longview/shared/formatters.test.ts
  packages/manager/src/features/Longview/shared/formatters.ts
Labels: Approved, Merge Conflicts

#11652 change: [OCA-1349] - Add backstage & deprecate apps
  packages/manager/.changeset/pr-11652-added-1739385288455.md
  packages/manager/.changeset/pr-11652-removed-1739401051825.md
  packages/manager/public/assets/backstage.svg
  packages/manager/public/assets/white/backstage.svg
  packages/manager/src/features/OneClickApps/oneClickApps.ts
Labels: Marketplace, Approved

#11648 change: [M3-9198] - Accessibility Issues with LKE Kubeconfig Buttons
  packages/manager/.changeset/pr-11648-changed-1739310281639.md
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
Labels: Approved

#11654 change: [M3-9162] - Bugs in Plans table for LKE
  packages/manager/.changeset/pr-11651-fixed-1739400469975.md
  packages/manager/src/assets/icons/LKEminusSign.svg
  packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
Labels: Bug, LKE, Approved

#11657 tests: [DI-23360] - Add Cypress tests for editing system alerts in the CloudPulse application
  packages/manager/.changeset/pr-11657-tests-1739428868479.md
  packages/manager/cypress/e2e/core/cloudpulse/edit-system-alert.spec.ts
  packages/manager/cypress/support/intercepts/cloudpulse.ts
Labels: Approved, Cloud Pulse - Alerting

#11649 upcoming: [DI-23436] - Integrating the Resources section in the create alert flow for Cloudpulse alerting
  packages/manager/.changeset/pr-11649-upcoming-features-1739352814480.md
  packages/manager/cypress/e2e/core/cloudpulse/edit-system-alert.spec.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResourcesNotice.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/MetricCriteria.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/MetricCriteria.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannels/AddChannelListing.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannels/AddChannelListing.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Resources/CloudPulseModifyAlertResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Resources/CloudPulseModifyAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/schemas.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/validation/.changeset/pr-11649-removed-1739489861125.md
  packages/validation/src/cloudpulse.schema.ts
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#11656 upcoming: [DI-23310] - Handle enable/disable action item for user created alerts
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-11656-upcoming-features-1739419988145.md
  packages/manager/src/factories/cloudpulse/alerts.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertActionMenu.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/constants.ts
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertsActionMenu.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/alerts.ts
Labels: Cloud Pulse - Alerting

#11658 fix: [DI-23469] - Fix low space between dashboard select & date time range picker
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
Labels: Cloud Pulse, Cloud Pulse - Dashboards

#11619 feat: [M3-9231] - Improve Node Pool Collapsing UX
  packages/manager/.changeset/pr-11619-added-1739207937605.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/hooks/useDefaultExpandedNodePools.test.ts
  packages/manager/src/hooks/useDefaultExpandedNodePools.ts
  packages/manager/src/utilities/storage.ts
Labels: UX/UI, LKE, Approved

#11667 hotfix: Uptime interface for LongView API response
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/factories/longviewDisks.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
  packages/manager/src/features/Longview/request.types.ts
Labels: Hotfix

#11682 fix: [M3-9343] - Fix validation with LKE Node Pool Labels creation
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/validation/CHANGELOG.md
  packages/validation/package.json
  packages/validation/src/kubernetes.schema.ts
Labels: Bug, Hotfix

#11671 test: [DI-23423] - E2E Cypress automation and validation for ACLP enable/disable
  packages/manager/.changeset/pr-11671-tests-1739858811779.md
  packages/manager/cypress/e2e/core/cloudpulse/alerts-listing-page.spec.ts
Labels: Approved, Cloud Pulse - Alerting

#11673 refactor: [M3-9264] - Migrate `Dialog`, `DialogTitle`, and associated util to `ui` package & some bug fixes
  packages/manager/.changeset/pr-11673-removed-1739872199022.md
  packages/manager/src/GoTo.tsx
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
  packages/manager/src/components/Drawer.tsx
  packages/manager/src/components/GenerateFirewallDialog/GenerateFirewallDialog.tsx
  packages/manager/src/components/TransferDisplay/TransferDisplayDialog.tsx
  packages/manager/src/dev-tools/components/ExtraPresetAccount.tsx
  packages/manager/src/dev-tools/components/ExtraPresetProfile.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.styles.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupsDialog.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/legacy/RestoreLegacyFromBackupDialog.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.styles.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferDetailsDialog.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUploadCLIDialog.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptDetailsDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/LinodeRebuildDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/StandardRescueDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/Profile/DisplaySettings/AvatarColorPickerDialog.tsx
  packages/manager/src/features/Profile/Settings/PreferenceEditor.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/manager/src/features/TheApplicationIsOnFire.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/utilities/stringUtils.ts
  packages/ui/.changeset/pr-11673-added-1739872267893.md
  packages/ui/src/assets/icons/chevron-down.svg
  packages/ui/src/assets/icons/index.ts
  packages/ui/src/assets/icons/visibilityHide.svg
  packages/ui/src/assets/icons/visibilityShow.svg
  packages/ui/src/components/Accordion/Accordion.tsx
  packages/ui/src/components/Dialog/Dialog.stories.tsx
  packages/ui/src/components/Dialog/Dialog.test.tsx
  packages/ui/src/components/Dialog/Dialog.tsx
  packages/ui/src/components/Dialog/index.ts
  packages/ui/src/components/DialogTitle/DialogTitle.test.tsx
  packages/ui/src/components/DialogTitle/DialogTitle.tsx
  packages/ui/src/components/DialogTitle/index.ts
  packages/ui/src/components/Notice/Notice.tsx
  packages/ui/src/components/VisibilityTooltip/VisibilityTooltip.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/utilities/index.ts
  packages/ui/src/utilities/stringUtils.ts
Labels: Approved, Modularization

#11679 Release v1.136.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/package.json
  packages/manager/src/factories/longviewDisks.ts
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
  packages/manager/src/features/Longview/request.types.ts
  packages/validation/CHANGELOG.md
  packages/validation/package.json
  packages/validation/src/kubernetes.schema.ts
Labels: Release, Hotfix

#11676 fix: [M3-9339] - Marketplace App Details Drawer overlap issues
  packages/manager/public/assets/postgresqlmarketplaceocc.svg
  packages/manager/public/assets/redissentinelmarketplaceocc.svg
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppDetailDrawer.tsx
  packages/manager/src/features/OneClickApps/oneClickApps.ts
Labels: Bug, Marketplace, Approved

#11680 fix: [M3-9252] - CDS pre-release fixes
  packages/manager/src/components/AreaChart/AreaChart.tsx
  packages/manager/src/components/DocsLink/DocsLink.tsx
  packages/manager/src/components/ImageSelect/ImageOption.tsx
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/components/LineGraph/MetricsDisplay.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNavToggle.tsx
  packages/manager/src/components/SelectionCard/CardBase.styles.ts
  packages/manager/src/components/SelectionCard/CardBase.tsx
  packages/manager/src/components/Tabs/Tab.test.tsx
  packages/manager/src/components/Tabs/Tab.tsx
  packages/manager/src/components/Tag/Tag.styles.ts
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx
  packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferCheckoutBar.styles.ts
  packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferCheckoutBar.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
  packages/manager/src/features/Longview/LongviewDetail/GraphCard.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/Search/ResultGroup.styles.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/testSetup.ts
  packages/ui/src/components/Box/Box.tsx
  packages/ui/src/components/Button/StyledTagButton.ts
  packages/ui/src/components/TooltipIcon/TooltipIcon.tsx
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved

#11689 test: [M3 8672] - use eslint to flag createLinode function
  packages/manager/.changeset/pr-11689-tests-1739986270581.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/support/util/linodes.ts
  packages/manager/package.json
  packages/ui/package.json
  yarn.lock
Labels: Approved

#11662 fix: [M3-9281] - Ensure document titles for Cloud Pulse pages have ap…
  packages/manager/.changeset/pr-11662-fixed-1739467765713.md
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
Labels: Approved, Cloud Pulse

#11677 refactor: [M3-9340] - Refactor CreateFirewallDrawer to use react-hook-form
  packages/api-v4/.changeset/pr-11677-changed-1739995208483.md
  packages/api-v4/src/firewalls/types.ts
  packages/manager/.changeset/pr-11677-tech-stories-1739897652667.md
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/constants.ts
  packages/validation/.changeset/pr-11677-changed-1739897615658.md
  packages/validation/src/firewalls.schema.ts
Labels: Approved, Firewalls

#11691 fix: [M3-9252] - Kill `MuiAccordionSummary-root` transition in primary nav
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
Labels: Approved

#11675 test: [M3-8070] - Part 2 of applying eslint to cypress files
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/e2e/core/account/account-cancellation.spec.ts
  packages/manager/cypress/e2e/core/account/display-settings.spec.ts
  packages/manager/cypress/e2e/core/account/email-bounce.spec.ts
  packages/manager/cypress/e2e/core/account/oauth-apps.spec.ts
  packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts
  packages/manager/cypress/e2e/core/account/security-questions.spec.ts
  packages/manager/cypress/e2e/core/account/service-transfer.spec.ts
  packages/manager/cypress/e2e/core/account/sms-verification.spec.ts
  packages/manager/cypress/e2e/core/account/ssh-keys.spec.ts
  packages/manager/cypress/e2e/core/account/user-profile.spec.ts
  packages/manager/cypress/e2e/core/account/users-landing-page.spec.ts
  packages/manager/cypress/e2e/core/billing/billing-contact.spec.ts
  packages/manager/cypress/e2e/core/billing/smoke-billing-activity.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/alerts-listing-page.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/edit-system-alert.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/cypress/e2e/core/databases/create-database.spec.ts
  packages/manager/cypress/e2e/core/databases/delete-database.spec.ts
  packages/manager/cypress/e2e/core/databases/resize-database.spec.ts
  packages/manager/cypress/e2e/core/databases/update-database.spec.ts
Labels: Add'tl Approval Needed, Ready for Review, Missing Changeset

#11697 test: [DI-23274] - Fix lint issue for `create-user-alert.spec.ts`
  packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
Labels: Add'tl Approval Needed

#11653 feat: [M3-9020] - LKE UI updates for checkout bar & Nodebalancer Details summary
  packages/api-v4/.changeset/pr-11653-changed-1739986135472.md
  packages/api-v4/src/nodebalancers/nodebalancers.ts
  packages/api-v4/src/nodebalancers/types.ts
  packages/manager/.changeset/pr-11653-added-1739985989958.md
  packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
  packages/manager/src/factories/account.ts
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/kubernetes.ts
  packages/manager/src/queries/nodebalancers.ts
  packages/manager/src/utilities/pricing/constants.ts
Labels: LKE, Approved, NodeBalancers, LKE-Enterprise

#11698 chore(deps): [M3-9356] - Update to Vite v6.1.1
  packages/manager/package.json
  yarn.lock
Labels: Dependencies

#11647 upcoming: [M3-9065] - Build new Quotas Controls
  packages/api-v4/src/quotas/types.ts
  packages/manager/.changeset/pr-11647-upcoming-features-1739465882408.md
  packages/manager/src/components/RegionSelect/RegionOption.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.styles.ts
  packages/manager/src/components/RegionSelect/RegionSelect.tsx
  packages/manager/src/components/RegionSelect/RegionSelect.types.ts
  packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
  packages/manager/src/components/RegionSelect/constants.ts
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/Quotas.tsx
  packages/manager/src/features/Account/Quotas/Quotas.test.tsx
  packages/manager/src/features/Account/Quotas/Quotas.tsx
  packages/manager/src/features/Account/Quotas/utils.test.tsx
  packages/manager/src/features/Account/Quotas/utils.ts
  packages/manager/src/mocks/presets/crud/handlers/quotas.ts
  packages/manager/src/mocks/utilities/response.ts
  packages/manager/src/utilities/formatRegion.ts
Labels: Limits

#11672 fix: [M3-9146] - Disable OBJ create flow for restricted user
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-11672-fixed-1739863532671.md
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
  packages/manager/src/factories/grants.ts
  packages/manager/src/features/Account/constants.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLandingEmptyState.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
Labels: Object Storage, Approved, Restricted User Access

#11674 fix: [M3-9148] - Added permission notice on create pages for restricted user
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-11674-fixed-1739881665819.md
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/src/factories/grants.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Linodes/LinodeCreate/index.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
Labels: Bug, Approved, Restricted User Access

#11692 upcoming: [DI-23317] - Filter regions by supported region ids
  packages/manager/.changeset/pr-11692-upcoming-features-1740111658194.md
  packages/manager/src/factories/cloudpulse/alerts.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertResourceUtils.test.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertResourceUtils.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Cloud Pulse

#11621 upcoming: [M3-9210] - Update Linode Interface types as specified
  packages/api-v4/.changeset/pr-11621-upcoming-features-1738790605953.md
  packages/api-v4/src/linodes/types.ts
  packages/api-v4/src/regions/types.ts
  packages/manager/src/factories/linodeInterface.ts
Labels: Approved, Linode Interfaces

#11699 fix: [M3-9360] - Collapsible Node Pool overflow bug
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
Labels: Bug, LKE, Approved

#11681 feat: [M3-9204] - Make Public checkbox default-checked in OAuth App Creation Form
  packages/manager/.changeset/pr-11681-changed-1739908630049.md
  packages/manager/cypress/e2e/core/account/oauth-apps.spec.ts
  packages/manager/src/features/Profile/OAuthClients/CreateOAuthClientDrawer.test.tsx
  packages/manager/src/features/Profile/OAuthClients/CreateOAuthClientDrawer.tsx
Labels: Approved

#11669 upcoming: [DI-23318] - Edit functionality for user alert
  packages/api-v4/.changeset/pr-11669-upcoming-features-1739899408035.md
  packages/api-v4/src/cloudpulse/alerts.ts
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-11669-upcoming-features-1739899370024.md
  packages/manager/cypress/e2e/core/cloudpulse/alert-show-details.spec.ts
  packages/manager/src/factories/cloudpulse/alerts.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/ServiceTypeSelect.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/ServiceTypeSelect.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Resources/CloudPulseModifyAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertLanding.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/schemas.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertsActionMenu.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/utils.test.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Add'tl Approval Needed, Cloud Pulse, Cloud Pulse - Alerting

#11703 fix: Update LKE Tiered Version endpoints
  packages/api-v4/CHANGELOG.md
  packages/api-v4/src/kubernetes/kubernetes.ts
  packages/manager/cypress/support/intercepts/lke.ts
Labels: Approved, LKE-Enterprise

#11701 fix: [M3-9061] - Node Pools CTA Buttons on Small Screens
  packages/manager/.changeset/pr-11701-fixed-1740128402516.md
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
Labels: Enhancement, Bug, LKE, Approved

#11708 fix: Update yarn-lock
  packages/utilities/package.json
  yarn.lock
Labels: Approved

#11706 test: [M3-9234]: config caddy to ignore test output
  docker-compose.yml
  packages/manager/.changeset/pr-11706-tests-1740406319898.md
Labels: Approved

#11713 fix: [M3-9401] - Account Billing page regression due to MUI v6
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
Labels: Bug, Approved

#11702 changed: [DI-23519] - updated icon colors to black
  packages/manager/src/assets/icons/refresh.svg
  packages/manager/src/assets/icons/zoomin.svg
  packages/manager/src/assets/icons/zoomout.svg
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx
Labels: Add'tl Approval Needed, Cloud Pulse

#11687 fix: [M3-9153] - LKE create page error for restricted user
  packages/manager/.changeset/pr-11687-fixed-1739979963091.md
  packages/manager/src/features/Kubernetes/CreateCluster/ClusterTypePanel.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
Labels: LKE, Approved, Restricted User Access

#11711 refactor: [M3-9397] - Migrate utilities to `(at)linode/utilities` package - Part 1
  packages/manager/.changeset/pr-11711-removed-1740406956736.md
  packages/manager/src/components/CopyableTextField/CopyableTextField.test.tsx
  packages/manager/src/components/DownloadTooltip.tsx
  packages/manager/src/components/SplashScreen.tsx
  packages/manager/src/constants.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryClusterConfigurationLegacy.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
  packages/manager/src/features/Domains/DownloadDNSZoneFileButton.test.tsx
  packages/manager/src/features/Domains/DownloadDNSZoneFileButton.tsx
  packages/manager/src/features/Events/factories/linode.tsx
  packages/manager/src/features/Kubernetes/ClusterList/ClusterActionMenu.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.tsx
  packages/manager/src/features/Linodes/LinodeCreate/shared/LinodeSelectTableRow.tsx
  packages/manager/src/features/Linodes/LinodeCreate/shared/SelectLinodeCard.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.tsx
  packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/utils.ts
  packages/manager/src/features/StackScripts/StackScriptEdit.tsx
  packages/manager/src/features/components/PlansPanel/utils.ts
  packages/manager/src/index.css
  packages/manager/src/initSentry.ts
  packages/manager/src/utilities/extendType.ts
  packages/manager/src/utilities/initWindows.ts
  packages/utilities/.changeset/pr-11711-added-1740406893414.md
  packages/utilities/src/helpers/accessibility.ts
  packages/utilities/src/helpers/areArraysEqual.test.ts
  packages/utilities/src/helpers/areArraysEqual.ts
  packages/utilities/src/helpers/arePropsEqual.test.ts
  packages/utilities/src/helpers/arePropsEqual.ts
  packages/utilities/src/helpers/arrayToList.test.ts
  packages/utilities/src/helpers/arrayToList.ts
  packages/utilities/src/helpers/breakpoints.ts
  packages/utilities/src/helpers/deepStringTransform.test.ts
  packages/utilities/src/helpers/deepStringTransform.ts
  packages/utilities/src/helpers/downloadFile.ts
  packages/utilities/src/helpers/env.ts
  packages/utilities/src/helpers/escapeRegExp.test.ts
  packages/utilities/src/helpers/escapeRegExp.ts
  packages/utilities/src/helpers/evenizeNumber.ts
  packages/utilities/src/helpers/formatStorageUnits.test.ts
  packages/utilities/src/helpers/formatStorageUnits.ts
  packages/utilities/src/helpers/groupByTags.test.ts
  packages/utilities/src/helpers/groupByTags.ts
  packages/utilities/src/helpers/index.ts
Labels: Approved, Modularization

#11715 fix: [M3-9400] - Selection Card UI regression caused by MUI v6
  packages/manager/src/components/SelectionCard/CardBase.styles.ts
Labels: Bug, Approved

#11693 upcoming: [DI-23224] - Add tag filter in the resources section of CloudPulse Alerts
  packages/manager/.changeset/pr-11693-upcoming-features-1740051990439.md
  packages/manager/cypress/e2e/core/cloudpulse/edit-system-alert.spec.ts
  packages/manager/src/factories/cloudpulse/alerts.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsRegionFilter.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResourcesFilterRenderer.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResourcesFilterRenderer.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsTagsFilter.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsTagsFilter.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/DisplayAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/TextWithExtraInfo.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/TextWithExtraInfo.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/constants.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/types.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertResourceUtils.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/queries/cloudpulse/resources.ts
  packages/ui/.changeset/pr-11693-added-1740060076770.md
  packages/ui/src/assets/icons/checkboxIndeterminate.svg
  packages/ui/src/assets/icons/index.ts
  packages/ui/src/components/Checkbox/Checkbox.tsx
Labels: Approved, Ready for Review, Cloud Pulse, Cloud Pulse - Alerting

#11709 poc: Use MUI's Button Loading State
  packages/manager/src/components/CheckoutBar/CheckoutBar.test.tsx
  packages/manager/src/components/DeletionDialog/DeletionDialog.test.tsx
  packages/ui/src/components/Button/Button.test.tsx
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/foundations/themes/light.ts
Labels: Proof of Concept, Approved

#11540 feat: [M3-9094] - DateRangePicker - v2
  packages/ui/.changeset/pr-11540-added-1738685506591.md
  packages/ui/src/components/DatePicker/Calendar/Calendar.styles.ts
  packages/ui/src/components/DatePicker/Calendar/Calendar.tsx
  packages/ui/src/components/DatePicker/DateRangePicker/DateRangePicker.stories.tsx
  packages/ui/src/components/DatePicker/DateRangePicker/DateRangePicker.test.tsx
  packages/ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
  packages/ui/src/components/DatePicker/DateRangePicker/Presets.tsx
  packages/ui/src/components/DatePicker/DateRangePicker/index.ts
  packages/ui/src/components/DatePicker/DateTimeField.tsx
  packages/ui/src/components/DatePicker/utils.ts
  packages/ui/src/components/index.ts
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/index.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Requires Changes, Date Range Picker

#11650 refactor: [M3-8711] - Read auth token from local storage
  packages/manager/cypress/e2e/core/parentChild/token-expiration.spec.ts
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.test.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.tsx
  packages/manager/src/features/Account/SwitchAccounts/useParentChildAuthentication.tsx
  packages/manager/src/features/Account/SwitchAccounts/utils.ts
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/hooks/useAuthentication.ts
  packages/manager/src/hooks/useInitialRequests.ts
  packages/manager/src/index.tsx
  packages/manager/src/layouts/LoginAsCustomerCallback.tsx
  packages/manager/src/layouts/Logout.test.tsx
  packages/manager/src/layouts/Logout.tsx
  packages/manager/src/layouts/OAuth.tsx
  packages/manager/src/layouts/OAuthCallback.test.tsx
  packages/manager/src/layouts/OAuthCallback.tsx
  packages/manager/src/request.test.tsx
  packages/manager/src/request.tsx
  packages/manager/src/session.ts
  packages/manager/src/store/authentication/authentication.actions.ts
  packages/manager/src/store/authentication/authentication.helpers.ts
  packages/manager/src/store/authentication/authentication.reducer.ts
  packages/manager/src/store/authentication/authentication.requests.ts
  packages/manager/src/store/authentication/authentication.test.ts
  packages/manager/src/store/authentication/index.ts
  packages/manager/src/store/index.ts
  packages/manager/src/utilities/authentication.ts
  packages/manager/src/utilities/storage.ts
  packages/manager/src/utilities/theme.ts
Labels: Approved

#11712 fix: [M3-9398] - Improve clarity for OBJ validation message
  packages/validation/.changeset/pr-11712-fixed-1740408470305.md
  packages/validation/src/buckets.schema.ts
Labels: Bug, Approved

#11714 fix: [M3-9344, M3-9336] - Fix LKE-E cluster filtering bug and non-LKE linode failed request bug
  packages/manager/.changeset/pr-11714-fixed-1740421546666.md
  packages/manager/.changeset/pr-11714-upcoming-features-1740421599114.md
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/queries/kubernetes.ts
Labels: Bug, LKE, Approved, LKE-Enterprise

#11725 fix: [M3-9410] - Unable to save non-US billing contact info without tax id
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
Labels: Hotfix

#11705 test: [M3-9150] - Cypress test for Image create page for restricted users
  packages/manager/.changeset/pr-11705-tests-1740407261971.md
  packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts
Labels: Approved

#11728 test: [M3-9417] - Fix CloudPulse test failures involving notice text assertions
  packages/manager/.changeset/pr-11728-tests-1740514341603.md
  packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/edit-system-alert.spec.ts
Labels: Ready for Review

#11685 upcoming: [DI-23548] - Added reusable component for alerts contextual view
  packages/api-v4/.changeset/pr-11685-upcoming-features-1739973458559.md
  packages/api-v4/src/cloudpulse/alerts.ts
  packages/manager/.changeset/pr-11685-upcoming-features-1739973428216.md
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertReusableComponent.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertReusableComponent.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/utils.test.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/alerts.ts
  packages/manager/src/queries/cloudpulse/queries.ts
  packages/manager/src/queries/cloudpulse/requests.ts
Labels: Ready for Review, Cloud Pulse, Cloud Pulse - Alerting

#11700 fix: [M3-9363] - Change error message for creating an Access key Drawer (restricted user)
  packages/manager/.changeset/pr-11700-fixed-1740116651657.md
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-access-keys-gen2.spec.ts
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
Labels: Object Storage, Approved, Ready for Review, Restricted User Access

#11362 test: [M3-8487] - Improve Cypress test VLAN handling
  packages/manager/.changeset/pr-11362-tests-1740410848045.md
  packages/manager/cypress/support/api/vlans.ts
  packages/manager/cypress/support/util/linodes.ts
Labels: Add'tl Approval Needed, Approved, Ready for Review

#10806 test: [M3-8137] - Add Cypress integration test to enable Linode Managed
  packages/manager/.changeset/pr-10806-tests-1725030349963.md
  packages/manager/cypress/e2e/core/account/account-linode-managed.spec.ts
  packages/manager/cypress/support/constants/account.ts
  packages/manager/cypress/support/intercepts/account.ts
  packages/manager/cypress/support/intercepts/linodes.ts
Labels: Approved

#11663 test: [M3-9149] - Cypress test for Linode create page for restricted users
  packages/manager/.changeset/pr-11663-tests-1740588226694.md
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
Labels: Add'tl Approval Needed, Missing Changeset

#11731 fix: [M3-9345] - RTX 6000 showing up in UI
  packages/manager/.changeset/pr-11731-fixed-1740521257689.md
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
  packages/manager/src/features/components/PlansPanel/utils.test.ts
  packages/manager/src/features/components/PlansPanel/utils.ts
Labels: LKE, Approved

#11678 upcoming: [M3-9115] - Create Firewalls from templates in CreateFirewallDrawer
  packages/manager/.changeset/pr-11678-upcoming-features-1739907724334.md
  packages/manager/src/components/GenerateFirewallDialog/useCreateFirewallFromTemplate.ts
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/PublicTemplateRules.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/TemplateFirewallFields.test.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/TemplateFirewallFields.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/VPCTemplateRules.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/constants.ts
  packages/manager/src/features/Firewalls/FirewallLanding/formUtilities.ts
  packages/manager/src/queries/firewalls.ts
Labels: Approved, Linode Interfaces

#11737 test: Remove Cypress test assertion involving login page content
  packages/manager/.changeset/pr-11737-tests-1740586626716.md
  packages/manager/cypress/e2e/core/general/account-login-redirect.spec.ts
Labels: Ready for Review

#11297 refactor: [M3-8632] - Use pnpm as our package manager
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/coverage_badge.yml
  .github/workflows/e2e_schedule_and_push.yml
  .gitignore
  .husky/pre-commit
  docker-compose.yml
  docs/CONTRIBUTING.md
  docs/GETTING_STARTED.md
  docs/development-guide/01-repository-structure.md
  docs/development-guide/04-component-library.md
  docs/development-guide/08-testing.md
  docs/development-guide/12-managing-dependencies.md
  package.json
  packages/api-v4/.changeset/README.md
  packages/api-v4/README.md
  packages/api-v4/package.json
  packages/manager/.changeset/README.md
  packages/manager/.storybook/main.ts
  packages/manager/Dockerfile
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
  packages/manager/cypress/support/cypress-exports.ts
  packages/manager/cypress/support/plugins/junit-report.ts
  packages/manager/cypress/support/plugins/split-run.ts
  packages/manager/cypress/support/util/accessibility.ts
  packages/manager/package.json
  packages/manager/src/components/AkamaiBanner/AkamaiBanner.test.tsx
  packages/manager/src/components/Breadcrumb/Crumbs.tsx
  packages/manager/src/components/Link.test.tsx
  packages/manager/src/components/MainContentBanner.test.tsx
  packages/manager/src/components/Prompt/Prompt.tsx
  packages/manager/src/components/TanstackLinks.tsx
  packages/manager/src/factories/databases.ts
  packages/manager/src/factories/entityTransfers.ts
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/factories/statusPage.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseSummarySection.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.test.tsx
  packages/manager/src/features/Help/StatusBanners.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/UserDefinedFields/UserDefinedFieldInput.tsx
  packages/manager/src/features/Managed/SSHAccess/LinodePubKey.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/Question.tsx
  packages/manager/src/session.ts
  packages/manager/src/utilities/testHelpers.tsx
  packages/search/package.json
  packages/ui/.changeset/README.md
  packages/ui/package.json
  packages/validation/.changeset/README.md
  packages/validation/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/junit-summary/util/cypress.ts
  scripts/package.json
  yarn.lock
Labels: Dependencies, Approved

#11742 fix: Add pnpm to `e2e_schedule_and_push.yml`
  .github/workflows/e2e_schedule_and_push.yml
Labels: github_actions

#11726 upcoming: [M3-9402] - Hide GPU plans tab for LKE-E
  packages/manager/.changeset/pr-11726-upcoming-features-1740510652938.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
Labels: Approved, LKE-Enterprise

#11655 upcoming: [M3-9095] - Add Linode Interfaces Table to Linode Details
  packages/api-v4/.changeset/pr-11655-changed-1740493497447.md
  packages/api-v4/src/linodes/index.ts
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-11655-upcoming-features-1739459039200.md
  packages/manager/cypress/e2e/core/linodes/linode-network.spec.ts
  packages/manager/src/components/Prompt/Prompt.tsx
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/UserDefinedFields/UserDefinedFieldInput.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls/LinodeFirewallsRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceFirewall.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceTableRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaces.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfacesTable.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfacesTableContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/utilities.test.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/utilities.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetwork.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/manager/src/queries/linodes/interfaces.ts
  packages/manager/src/queries/linodes/linodes.ts
  packages/manager/src/utilities/linodes.test.ts
  packages/manager/src/utilities/linodes.ts
  packages/manager/src/utilities/testHelpers.tsx
  packages/manager/vite.config.ts
Labels: Add'tl Approval Needed, Linode Interfaces

#11732 fix: [M3-9413] - Authentication Provider Selection Card UI Issue
  packages/manager/.changeset/pr-11732-fixed-1740533390539.md
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.styles.ts
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.test.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
Labels: Bug, UX/UI, Approved

#11724 chore: [M3-9440] - Improve Banner Spacing
  packages/manager/src/features/GlobalNotifications/TokensUpdateBanner.tsx
  packages/ui/.changeset/pr-11724-changed-1740590596984.md
  packages/ui/src/components/Notice/Notice.test.tsx
  packages/ui/src/components/Notice/Notice.tsx
Labels: UX/UI, Approved

#11664 upcoming: [M3-8844] - Add LKE-E final copy and update some existing LKE copy
  packages/manager/.changeset/pr-11664-changed-1739979366424.md
  packages/manager/.changeset/pr-11664-upcoming-features-1739979306430.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/components/SelectionCard/SelectionCard.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/ClusterTierPanel.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.styles.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/LabelsAndTaints/LabelAndTaintDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/RecycleNodeDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/RecycleClusterDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/RecycleNodePoolDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeClusterDialog.tsx
  packages/manager/src/features/Kubernetes/UpgradeVersionModal.tsx
  packages/manager/src/features/Kubernetes/constants.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/validation/.changeset/pr-11664-added-1740008383592.md
  packages/validation/src/kubernetes.schema.ts
Labels: LKE, Approved, LKE-Enterprise

#11749 deps: [M3-9442] - Update `@vitest/ui` in `utilities` package
  packages/utilities/.changeset/pr-11749-tech-stories-1740669995320.md
  packages/utilities/package.json
  pnpm-lock.yaml
Labels: Dependencies, Approved

#11752 chore: [M3-9443] - Upgrade Tanstack Router to latest
  packages/manager/package.json
  packages/manager/src/hooks/useDialogData.ts
  packages/manager/src/hooks/useOrderV2.ts
  packages/manager/src/hooks/usePaginationV2.ts
  packages/manager/src/routes/placementGroups/index.ts
  pnpm-lock.yaml
Labels: Add'tl Approval Needed, Routing Refactor

#11760 hotfix: Linode Creation in Distributed Regions
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/linodes/create-linode-with-disk-encryption.spec.ts
  packages/manager/package.json
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/Encryption/Encryption.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Security.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Security.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.tsx
  packages/manager/src/features/Linodes/LinodeCreate/TwoStepRegion.tsx
Labels: Hotfix

#11761 Release v1.137.2 - `staging` → `master`
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/linodes/create-linode-with-disk-encryption.spec.ts
  packages/manager/package.json
  packages/manager/src/components/AccessPanel/AccessPanel.tsx
  packages/manager/src/components/Encryption/Encryption.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Security.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Security.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.tsx
  packages/manager/src/features/Linodes/LinodeCreate/TwoStepRegion.tsx
Labels: Release, Hotfix

#11755 chore: [no-ticket] - Upgrade Vitest packages to 3.0.7
  package.json
  packages/manager/.changeset/pr-11755-changed-1740752072171.md
  packages/manager/.changeset/pr-11755-changed-1740752328523.md
  packages/manager/package.json
  packages/ui/.changeset/pr-11755-changed-1740752132853.md
  packages/ui/package.json
  packages/utilities/.changeset/pr-11755-changed-1740752199155.md
  packages/utilities/package.json
  pnpm-lock.yaml
Labels: Approved, Tech Debt

#11758 security: [M3-9447] - Update `react-vnc` for security updates
  packages/manager/.changeset/pr-11758-changed-1740751964030.md
  packages/manager/package.json
  packages/manager/src/features/Lish/Glish.tsx
  pnpm-lock.yaml
Labels: Security, Approved

#11736 upcoming: [M3-9110] - Add Interface type to Linode Entity Detail
  packages/manager/.changeset/pr-11736-added-1740581762216.md
  packages/manager/.changeset/pr-11736-upcoming-features-1740581729228.md
  packages/manager/cypress/e2e/core/linodes/linode-network.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
Labels: Approved, Linode Interfaces

#11750 fix: [M3-9439] - Search package using older Vite version
  packages/search/package.json
  pnpm-lock.yaml
Labels: Dependencies, Approved
