Repository linode/manager, pull requests merged in 2025-03, with the labels that each got.

#11716 upcoming: [M3-9396] - Quotas Table
  packages/manager/src/components/BarPercent/BarPercent.test.tsx
  packages/manager/src/components/BarPercent/BarPercent.tsx
  packages/manager/src/components/BarPercent/utils.test.ts
  packages/manager/src/components/BarPercent/utils.ts
  packages/manager/src/components/TableRowEmpty/TableRowEmpty.tsx
  packages/manager/src/components/TableRowLoading/TableRowLoading.tsx
  packages/manager/src/features/Account/Quotas/Quotas.test.tsx
  packages/manager/src/features/Account/Quotas/Quotas.tsx
  packages/manager/src/features/Account/Quotas/QuotasTable.test.tsx
  packages/manager/src/features/Account/Quotas/QuotasTable.tsx
  packages/manager/src/features/Account/Quotas/utils.test.tsx
  packages/manager/src/features/Account/Quotas/utils.ts
  packages/manager/src/mocks/presets/crud/handlers/quotas.ts
  packages/manager/src/mocks/presets/crud/quotas.ts
Labels: Limits

#11748 Upcoming:[DI-23319] - CloudPulse Alerting minor UX improvements
  packages/manager/.changeset/pr-11748-upcoming-features-1740653230064.md
  packages/manager/src/assets/icons/entityIcons/alertsresources.svg
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilter.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/TriggerConditions.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResourcesConfirmationDialog.tsx
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#11745 upcoming: [M3-9355] - Fix LKE-E provisioning placeholder when filtering by status
  packages/manager/.changeset/pr-11745-upcoming-features-1740672674751.md
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
Labels: Bug, Approved, LKE-Enterprise

#11730 test [M3-8070]: linting of images, kubernetes, linodes dirs
  packages/manager/.changeset/pr-11730-tests-1740520042307.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/e2e/core/images/create-image.spec.ts
  packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
  packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-delete.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-summary-page.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
  packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-mobile.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-add-ons.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-ssh-key.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-vlan.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-vpc.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/cypress/e2e/core/linodes/update-linode-labels.spec.ts
Labels: Approved

#11719 test: [DI-23514] - Add Automation for edit functionality of user defined alert.
  packages/manager/.changeset/pr-11719-tests-1740478883806.md
  packages/manager/cypress/e2e/core/cloudpulse/edit-user-alert.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/timerange-verification.spec.ts
  packages/manager/cypress/support/constants/cloudpulse.ts
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannels/AddChannelListing.tsx
Labels: Cloud Pulse - Alerting

#11771 fix: [M3-9253] - Incorrect helper text in `Add SSH Key` drawer
  packages/manager/.changeset/pr-11771-fixed-1740992423294.md
  packages/manager/src/features/Profile/SSHKeys/CreateSSHKeyDrawer.tsx
Labels: Approved

#11769 fix: [M3-9270] - Confusing wording on DBaaS suspend dialog
  packages/manager/.changeset/pr-11769-fixed-1740985683618.md
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
Labels: DBaaS, Approved

#11765 fix: [M3-9243] - Added show detail dailog for selected Stackscript
  packages/manager/.changeset/pr-11765-fixed-1740766037419.md
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionList.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionRow.tsx
Labels: Bug, Approved, StackScripts

#11753 chore: [M3-9445] - Improve pre-commit hook experience
  .husky/pre-commit
  package.json
  packages/api-v4/package.json
  packages/manager/package.json
  packages/ui/package.json
  packages/utilities/package.json
  packages/validation/package.json
  pnpm-lock.yaml
Labels: Enhancement, Approved, Tooling

#11768 deps: [M3-9457] - Update `jspdf` dependencies to resolve DOMPurify dependabot alert
  packages/manager/.changeset/pr-11768-tech-stories-1741017663608.md
  packages/manager/package.json
  pnpm-lock.yaml
Labels: Dependencies, Approved

#11777 change: [M3-9347] - Use self-hosted Pendo agent scripts
  docs/tooling/analytics.md
  packages/manager/.changeset/pr-11777-tech-stories-1741043684723.md
  packages/manager/public/pendo/pendo-staging.js
  packages/manager/public/pendo/pendo.js
  packages/manager/src/hooks/usePendo.ts
Labels: Approved, Analytics

#11641 upcoming: [M3-9120] - Linode Create Networking for Linode Interfaces
  packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-vlan.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode-with-vpc.spec.ts
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/src/components/VLANSelect.tsx
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Actions.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/Firewall.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceFirewall.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceGeneration.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceType.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/LinodeInterface.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/Networking.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VLAN.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.test.ts
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionList.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VLAN/VLAN.tsx
  packages/manager/src/features/Linodes/LinodeCreate/index.tsx
  packages/manager/src/features/Linodes/LinodeCreate/resolvers.ts
  packages/manager/src/features/Linodes/LinodeCreate/utilities.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
  packages/manager/src/utilities/linodes.test.ts
  packages/manager/src/utilities/linodes.ts
Labels: Approved, Linode Interfaces

#11775 change: [M3-9446] - Update LKE copy part 2 (Upgrade, Recycle, and Delete modals)
  packages/manager/.changeset/pr-11775-changed-1741032651842.md
  packages/manager/cypress/e2e/core/kubernetes/lke-landing-page.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/LocalStorageWarningNotice.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/DeleteNodePoolDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/RecycleNodeDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/RecycleClusterDialog.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/RecycleNodePoolDialog.tsx
  packages/manager/src/features/Kubernetes/UpgradeVersionModal.tsx
  packages/manager/src/features/Kubernetes/constants.ts
Labels: LKE, Approved, LKE-Enterprise

#11723 fix: [M3-9359] - Adjust mobile primary nav height
  packages/manager/.changeset/pr-11723-fixed-1740501014063.md
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
Labels: Bug, Approved, Ready for Review

#11767 fix: [M3-9449] - Filter out Linodes in distributed regions from Create flow Backups & Clone tab
  packages/manager/.changeset/pr-11767-fixed-1740775625877.md
  packages/manager/src/features/Linodes/LinodeCreate/shared/LinodeSelectTable.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/shared/LinodeSelectTable.tsx
  packages/manager/src/hooks/useOrder.ts
Labels: Bug, Approved, Linodes, Gecko LA

#11780 test [M3 8628]: Delete region test suite
  docs/development-guide/08-testing.md
  packages/manager/.changeset/pr-11780-tests-1741102827420.md
  packages/manager/cypress/e2e/region/images/create-machine-image-from-linode.spec.ts
  packages/manager/cypress/e2e/region/images/update-delete-machine-image.spec.ts
  packages/manager/cypress/e2e/region/images/upload-machine-image.spec.ts
  packages/manager/cypress/e2e/region/linodes/create-linode.spec.ts
  packages/manager/cypress/e2e/region/linodes/delete-linode.spec.ts
  packages/manager/cypress/e2e/region/linodes/update-linode.spec.ts
  packages/manager/cypress/support/plugins/configure-test-suite.ts
Labels: Approved

#11735 feat: [UIE-8514] - DBaaS : Initial Advanced Config Tab and Drawer Setup
  packages/api-v4/.changeset/pr-11735-upcoming-features-1740581707757.md
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-11735-upcoming-features-1740581501727.md
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/factories/databases.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfiguration.style.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfigurationDrawer.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationSelect.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
Labels: DBaaS, Approved

#11757 feat: [M3-9404] - 4.0.0 Design Tokens - New Spacing & Badge Tokens
  packages/manager/.changeset/pr-11757-tech-stories-1740683464911.md
  packages/manager/package.json
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/PrimaryNavToggle.tsx
  packages/manager/src/components/TypeToConfirm/TypeToConfirm.tsx
  packages/manager/src/features/Account/CloseAccountDialog.tsx
  packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
  packages/manager/src/features/TopMenu/InternalAdminBanner.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/features/TopMenu/TopMenuTooltip.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenuPopover.tsx
  packages/ui/.changeset/pr-11757-tech-stories-1740683477384.md
  packages/ui/package.json
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
  pnpm-lock.yaml
Labels: Ready for Review, Design Tokens

#11734 upcoming: [DI-23640] - Added table in alert contextual view
  packages/manager/.changeset/pr-11734-upcoming-features-1740564048829.md
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/constants.ts
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertInformationActionRow.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertInformationActionRow.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertInformationActionTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertInformationActionTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertReusableComponent.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertReusableComponent.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/MetricThreshold.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Ready for Review, Cloud Pulse, Cloud Pulse - Alerting

#11772 fix: [M3-9412] - Shiki Syntax Highlighting causing Webkit browsers to crash
  packages/manager/.changeset/pr-11772-tech-stories-1741017357763.md
  packages/manager/package.json
  pnpm-lock.yaml
Labels: Dependencies, Approved

#11779 fix: [M3-9415] - NodeBalancer Create Summary broken dividers and spacing
  packages/manager/.changeset/pr-11779-fixed-1741096736423.md
  packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
Labels: Bug, Approved

#11704 refactor: [M3-9354] - Reroute Firewalls Feature
  packages/manager/.changeset/pr-11704-tech-stories-1740340564875.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/component/features/firewalls/firewall-rule-table.spec.tsx
  packages/manager/cypress/support/component/setup.tsx
  packages/manager/cypress/support/util/components.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/Events/factories/firewall.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddLinodeDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddLinodeDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceTable.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/constants.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleActionMenu.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleActionMenu.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
  packages/manager/src/features/Firewalls/index.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls/AddFirewallForm.tsx
  packages/manager/src/hooks/useTabs.ts
  packages/manager/src/routes/firewalls/firewallLazyRoutes.ts
  packages/manager/src/routes/firewalls/index.ts
  packages/manager/src/routes/index.tsx
Labels: Routing Refactor

#11781 Revert "change: [M3-9347] - Use self-hosted Pendo agent scripts"
  docs/tooling/analytics.md
  packages/manager/.changeset/pr-11777-tech-stories-1741043684723.md
  packages/manager/public/pendo/pendo-staging.js
  packages/manager/public/pendo/pendo.js
  packages/manager/src/hooks/usePendo.ts
Labels: Approved, Analytics

#11783 refactor: [M3-9276] – Revise logic governing display of LDE in Cloud
  packages/api-v4/.changeset/pr-11783-changed-1741210351721.md
  packages/api-v4/src/regions/types.ts
  packages/manager/.changeset/pr-11783-tests-1741210181065.md
  packages/manager/.changeset/pr-11783-upcoming-features-1741210015259.md
  packages/manager/cypress/e2e/core/linodes/create-linode-with-disk-encryption.spec.ts
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Security.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/DiskEncryption.tsx
Labels: Approved, Linode Disk Encryption (LDE)

#11727 upcoming: [M3-9112] - Hide Networking section in Config table and dialog for new interfaces
  packages/api-v4/.changeset/pr-11727-upcoming-features-1740523371376.md
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-11727-upcoming-features-1740523339141.md
  packages/manager/cypress/support/intercepts/configs.ts
  packages/manager/src/factories/linodeConfigs.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/ConfigRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
  packages/manager/src/utilities/configs.ts
Labels: Approved, Linode Interfaces

#11799 fix: Update link import in FirewallCreate section
  packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx
Labels: Approved

#11770 refactor: [M3-9419] - Migrate hooks to `(at)linode/utilities` package
  packages/manager/.changeset/pr-11770-removed-1740989311904.md
  packages/manager/src/components/DocumentTitle/DocumentTitle.tsx
  packages/manager/src/components/OrderBy.tsx
  packages/manager/src/components/VLANSelect.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/StandardRescueDialog.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/hooks/useAdobeAnalytics.ts
  packages/manager/src/hooks/useNewRelic.ts
  packages/manager/src/hooks/usePendo.ts
  packages/utilities/.changeset/pr-11770-added-1740989355752.md
  packages/utilities/src/hooks/index.ts
  packages/utilities/src/hooks/useDebouncedValue.test.ts
  packages/utilities/src/hooks/useDebouncedValue.ts
  packages/utilities/src/hooks/useFormValidateOnChange.ts
  packages/utilities/src/hooks/usePrevious.ts
  packages/utilities/src/hooks/useScript.ts
  packages/utilities/src/hooks/useSet.test.ts
  packages/utilities/src/hooks/useSet.ts
Labels: Approved, Modularization

#11800 fix: [M3-9478] - `Add an SSH Key` button spacing
  packages/manager/.changeset/pr-11800-fixed-1741298651535.md
  packages/manager/src/features/Profile/SSHKeys/DeleteSSHKeyDialog.test.tsx
  packages/manager/src/features/Profile/SSHKeys/DeleteSSHKeyDialog.tsx
  packages/manager/src/features/Profile/SSHKeys/EditSSHKeyDrawer.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeyActionMenu.tsx
  packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
Labels: Bug, UX/UI, Approved

#11796 upcoming: [M3-9482] Enable Firewall query on LinodeEntityDetail only if Linode uses legacy interfaces and fix typo in Firewall Template feature
  packages/manager/.changeset/pr-11796-upcoming-features-1741277847530.md
  packages/manager/.changeset/pr-11796-upcoming-features-1741294621831.md
  packages/manager/src/features/Firewalls/FirewallLanding/VPCTemplateRules.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/queries/linodes/firewalls.ts
Labels: Approved, Linode Interfaces

#11773 upcoming: [DI-23235] - Alerting UI changes: validations, limits, Error Messages
  packages/manager/.changeset/pr-11773-upcoming-features-1741023864014.md
  packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilter.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilter.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilterField.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/MetricCriteria.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/MetricCriteria.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/TriggerConditions.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/TriggerConditions.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/ServiceTypeSelect.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannels/AddChannelListing.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannels/AddChannelListing.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannels/AddNotificationChannelDrawer.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertResourceUtils.ts
  packages/manager/src/features/CloudPulse/Alerts/constants.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/validation/.changeset/pr-11773-upcoming-features-1741023892137.md
  packages/validation/src/cloudpulse.schema.ts
Labels: Approved, Ready for Review, Cloud Pulse, Cloud Pulse - Alerting

#11766 test [M3 8070]: apply linting 7
  packages/manager/.changeset/pr-11766-tests-1741093015072.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/e2e/core/placementGroups/create-linode-with-placement-groups.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/create-placement-groups.spec.ts
  packages/manager/cypress/e2e/core/placementGroups/update-placement-group-label.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/update-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/clone-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.smoke.spec.ts
  packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/delete-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/resize-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/update-volume.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-create.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-linodes-update.spec.ts
Labels: Approved

#11782 upcoming: [M3-9116] - `Add Network Interface` Drawer and `Delete Interface` Dialog
  packages/manager/.changeset/pr-11782-upcoming-features-1741200646559.md
  packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/Actions.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/AddInterfaceDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/AddInterfaceForm.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/InterfaceFirewall.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/InterfaceType.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VLANInterface.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/utilities.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/DeleteInterfaceDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceTableRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaces.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfacesTable.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfacesTableContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/utilities.test.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/utilities.ts
  packages/manager/src/queries/linodes/interfaces.ts
  packages/validation/src/linodes.schema.ts
Labels: Approved, Linode Interfaces

#11805 fix: [M3-8812] - Hide VPC Section from Linode Create Clone Tab
  packages/manager/.changeset/pr-11805-fixed-1741362504398.md
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/index.tsx
Labels: Approved, Linodes

#11788 upcoming: [M3-9468] - Support Linode Interface Account Setting on Linode Create Flow
  packages/manager/.changeset/pr-11788-upcoming-features-1741212842371.md
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceFirewall.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceGeneration.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceGeneration.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreate/index.tsx
  packages/manager/src/features/Linodes/LinodeCreate/utilities.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
Labels: Approved, Linode Interfaces

#11798 fix: [M3-9414] - PaginationFooter page size select
  packages/manager/.changeset/pr-11798-fixed-1741288715604.md
  packages/manager/src/components/PaginationFooter/PaginationFooter.constants.ts
  packages/manager/src/components/PaginationFooter/PaginationFooter.test.tsx
  packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
  packages/manager/src/components/PaginationFooter/PaginationFooter.utils.test.ts
  packages/manager/src/components/PaginationFooter/PaginationFooter.utils.ts
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/hooks/usePagination.ts
  packages/manager/src/hooks/usePaginationV2.test.ts
  packages/manager/src/hooks/usePaginationV2.ts
  packages/ui/src/components/Select/Select.tsx
  packages/ui/src/components/TextField/TextField.tsx
Labels: Bug, Approved

#11818 upcoming: [M3-9496] - Beta Quota Endpoints
  packages/api-v4/.changeset/pr-11818-upcoming-features-1741627601695.md
  packages/api-v4/src/quotas/quotas.ts
  packages/manager/src/mocks/presets/crud/handlers/quotas.ts
Labels: Approved, Limits

#11815 upcoming: [DI-23817] - Added refetch interval in alerts query
  packages/manager/.changeset/pr-11815-upcoming-features-1741615995524.md
  packages/manager/src/queries/cloudpulse/alerts.ts
Labels: Cloud Pulse, Cloud Pulse - Alerting

#11824 fix: [M3-9520] - Fix Broken `ActionsPanel` Imports
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/Actions.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/DeleteInterfaceDialog.tsx
Labels: Bug, Approved

#11817 refactor: [M3-9493] – Streamline/simplify LDE logic
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/linodes/create-linode-with-disk-encryption.spec.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Security.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/DiskEncryption.tsx
Labels: Approved, Linode Disk Encryption (LDE)

#11820 change: [M3-9516] - Update body text color to use proper color token
  packages/manager/.changeset/pr-11820-changed-1741642386020.md
  packages/manager/src/components/Markdown/__snapshots__/Markdown.test.tsx.snap
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/ui/.changeset/pr-11820-changed-1741642411797.md
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Ready for Review, Design Tokens

#11793 test: [M3-9152] - Cypress test for LKE create page for restricted users
  packages/manager/.changeset/pr-11793-tests-1741276889132.md
  packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
Labels: Approved

#11822 test: [DI-23925] - Fix failing Edit User alert due to recent changes
  packages/manager/.changeset/pr-11822-tests-1741678822638.md
  packages/manager/cypress/e2e/core/cloudpulse/edit-user-alert.spec.ts
Labels: Bug, Approved, Cloud Pulse - Alerting

#11786 upcoming: [M3-9418] - Update warnings and actions for LKE-E VPCs
  packages/manager/.changeset/pr-11786-upcoming-features-1741281388516.md
  packages/manager/src/features/Kubernetes/constants.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCRow.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCRow.tsx
  packages/manager/src/features/VPCs/utils.ts
Labels: Approved, VPC, LKE-Enterprise

#11830 fix: [M3-9526] - Fix database cluster config MUIv6 regressions
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
Labels: Bug, Approved

#11785 upcoming: [DI-23778] - Added. confirmation dialog in alerts contextual view
  packages/api-v4/.changeset/pr-11785-upcoming-features-1741159921041.md
  packages/api-v4/src/cloudpulse/alerts.ts
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-11785-upcoming-features-1741159867178.md
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertConfirmationDialog.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertConfirmationDialog.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertInformationActionTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertInformationActionTable.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/alerts.ts
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#11803 upcoming: [DI-22920] - Add megamenu changes
  packages/manager/.changeset/pr-11803-upcoming-features-1741584341402.md
  packages/manager/cypress/e2e/core/cloudpulse/alert-show-details.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/alerts-listing-page.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-dashboard-errors.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-navigation.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/edit-system-alert.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/edit-user-alert.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/timerange-verification.spec.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertInformationActionRow.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertReusableComponent.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertReusableComponent.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.tsx
  packages/manager/src/features/CloudPulse/CloudPulseLanding.tsx
  packages/manager/src/features/CloudPulse/CloudPulseTabs.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.test.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
  packages/manager/src/routes/alerts/CloudPulseAlertsRoute.tsx
  packages/manager/src/routes/alerts/index.ts
  packages/manager/src/routes/cloudPulse/index.ts
  packages/manager/src/routes/index.tsx
  packages/manager/src/routes/metrics/CloudPulseMetricsRoute.tsx
  packages/manager/src/routes/metrics/index.ts
Labels: Approved, Cloud Pulse - Alerting

#11806 refactor: [M3-9484] - Reroute Stackscripts
  packages/manager/.changeset/pr-11806-tech-stories-1741373353918.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/e2e/core/stackscripts/delete-stackscripts.spec.ts
  packages/manager/cypress/e2e/core/stackscripts/update-stackscripts.spec.ts
  packages/manager/src/MainContent.tsx
  packages/manager/src/features/StackScripts/StackScriptBase/StackScriptsEmptyLandingPage.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.test.tsx
  packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
  packages/manager/src/features/StackScripts/StackScriptEdit.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptActionMenu.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptDeleteDialog.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptLandingTable.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptMakePublicDialog.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptsLanding.tsx
  packages/manager/src/features/StackScripts/StackScripts.tsx
  packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
  packages/manager/src/routes/index.tsx
  packages/manager/src/routes/stackscripts/index.ts
  packages/manager/src/routes/stackscripts/stackscriptsLazyRoutes.ts
Labels: Approved, Routing Refactor

#11792 upcoming: [M3-9462] - Request for Quota increase modal
  packages/manager/.changeset/pr-11792-upcoming-features-1741627662406.md
  packages/manager/src/components/RegionSelect/constants.ts
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Account/Quotas/QuotasIncreaseForm.test.tsx
  packages/manager/src/features/Account/Quotas/QuotasIncreaseForm.tsx
  packages/manager/src/features/Account/Quotas/QuotasTable.tsx
  packages/manager/src/features/Account/Quotas/QuotasTableRow.tsx
  packages/manager/src/features/Account/Quotas/utils.test.tsx
  packages/manager/src/features/Account/Quotas/utils.ts
  packages/manager/src/hooks/useIsAkamaiAccount.ts
  packages/manager/src/request.tsx
Labels: Approved, Limits

#11762 feat: [UIE-8138, UIE-8139] - IAM RBAC: add new assigned roles table component part 2
  packages/api-v4/.changeset/pr-11762-upcoming-features-1740743199251.md
  packages/api-v4/src/iam/types.ts
  packages/manager/.changeset/pr-11762-upcoming-features-1740739892540.md
  packages/manager/src/factories/accountResources.ts
  packages/manager/src/factories/userPermissions.ts
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.style.ts
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
  packages/manager/src/features/IAM/Shared/utilities.test.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.test.tsx
  packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
  packages/manager/src/features/IAM/Users/UserEntities/UserEntities.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.test.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
  packages/manager/src/features/IAM/Users/UserRoles/UserRoles.test.tsx
  packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
Labels: Approved, IAM (Identity & Access Management)

#11813 upcoming: [DI-23781] - Error handling while enabling/disabling alerts in Monitor
  packages/manager/.changeset/pr-11813-upcoming-features-1741767698345.md
  packages/manager/cypress/e2e/core/cloudpulse/alert-errors.spec.ts
  packages/manager/cypress/support/intercepts/cloudpulse.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
Labels: Approved

#11827 fix: [M3-9465] - Make LKE/LKE-E spacing tweaks
  packages/manager/.changeset/pr-11827-fixed-1741723772655.md
  packages/manager/src/features/Kubernetes/CreateCluster/ClusterTierPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/LabelsAndTaints/LabelAndTaintDrawer.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/LabelsAndTaints/LabelTable.styles.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.styles.ts
Labels: LKE, Approved, LKE-Enterprise

#11801 tech-story: [M3-9483] - Add rule to prevent direct imports of Link from `react-router-dom`
  packages/manager/.changeset/pr-11801-tech-stories-1741386433515.md
  packages/manager/.eslintrc.cjs
  packages/manager/cypress/e2e/core/cloudpulse/alert-errors.spec.ts
  packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
  packages/manager/src/components/AbuseTicketBanner/AbuseTicketBanner.tsx
  packages/manager/src/components/BackupStatus/BackupStatus.tsx
  packages/manager/src/components/Breadcrumb/Crumbs.tsx
  packages/manager/src/components/IconTextLink/IconTextLink.tsx
  packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx
  packages/manager/src/components/Link.tsx
  packages/manager/src/components/MaintenanceBanner/MaintenanceBanner.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PromotionalOfferCard/PromotionalOfferCard.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/components/SupportLink/SupportLink.tsx
  packages/manager/src/components/Tabs/TabLinkList.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
  packages/manager/src/features/Databases/DatabaseEngineVersion.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.styles.ts
  packages/manager/src/features/IAM/Users/UsersTable/UserRow.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeRow.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/Linodes/RenderIPs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/TopProcesses.styles.ts
  packages/manager/src/features/Managed/ManagedDashboardCard/MonitorStatus.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/MonitorTickets.tsx
  packages/manager/src/features/Managed/Monitors/IssueDay.styles.tsx
  packages/manager/src/features/Managed/Monitors/MonitorRow.styles.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerFirewallsRow.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx
  packages/manager/src/features/Profile/AuthenticationSettings/SMSMessaging.tsx
  packages/manager/src/features/Search/ResultRow.styles.ts
  packages/manager/src/features/Support/SupportTickets/TicketRow.tsx
  packages/manager/src/features/TopMenu/CreateMenu/ProductFamilyGroup.tsx
  packages/manager/src/features/TopMenu/Help.tsx
  packages/manager/src/features/TopMenu/TopMenu.tsx
Labels: Approved

#11837 refactor: [DI-23972] - Updated redirection for invalid url to metrics & alerts home page
  packages/manager/.changeset/pr-11837-added-1741874687278.md
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
Labels: Approved

#11835 fix: [M3-9533] Storybook crypto.randomUUID Error
  packages/manager/.changeset/pr-11835-fixed-1741797017641.md
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/factories/statusPage.ts
Labels: Approved

#11825 upcoming: [DI-23773] - Added the tooltip icon for Add buttons in disabled state
  packages/manager/.changeset/pr-11825-upcoming-features-1741714373810.md
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilter.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/MetricCriteria.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannels/AddChannelListing.tsx
Labels: Cloud Pulse, Cloud Pulse - Alerting

#11845 test: [M3-9508] - Disable Cypress recording for GitHub Actions runs
  .github/workflows/e2e_schedule_and_push.yml
Labels: Ready for Review, Missing Changeset

#11848 remove: [M3-9580] - Bucket rate limit table from Object Storage details drawer
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
Labels: Ready for Review, Hotfix

#11809 upcoming: [M3-9495] - Disable APL for LKE-E clusters
  packages/manager/.changeset/pr-11809-upcoming-features-1741383768710.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
Labels: Approved, LKE-Enterprise, APL

#11821 change: [M3-9434] - Update styles to CDS for create menu
  packages/manager/.changeset/pr-11821-changed-1741726538918.md
  packages/manager/.eslintrc.cjs
  packages/manager/src/features/TopMenu/CreateMenu/CreateMenu.styles.ts
  packages/manager/src/features/TopMenu/CreateMenu/ProductFamilyGroup.tsx
Labels: Approved, Ready for Review, Design Tokens

#11838 fix: [M3-9459] - show details button misalignment for selected stackscript
  packages/manager/.changeset/pr-11838-fixed-1741862453402.md
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionRow.tsx
Labels: Bug, Approved, StackScripts

#11811 upcoming: [M3-9422] -Update existing API endpoints and types for `/v4/nodebalancers`
  packages/api-v4/.changeset/pr-11811-upcoming-features-1741607872773.md
  packages/api-v4/src/nodebalancers/nodebalancer-config-nodes.ts
  packages/api-v4/src/nodebalancers/nodebalancer-configs.ts
  packages/api-v4/src/nodebalancers/nodebalancers.ts
  packages/api-v4/src/nodebalancers/types.ts
Labels: NB-VPC

#11849 feat: [M3-9581] - Implement Custom Spacing Function
  docs/development-guide/16-design-tokens.md
  packages/ui/src/foundations/themes/index.ts
  packages/ui/src/foundations/themes/light.ts
  packages/ui/src/foundations/utils.test.ts
  packages/ui/src/foundations/utils.ts
Labels: Ready for Review, Design Tokens

#11833 refactor: [M3-9532] – Account for "LA Disk Encryption" region capability in `regionSupportsDiskEncryption` checks
  packages/api-v4/CHANGELOG.md
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Security.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/DiskEncryption.tsx
  packages/ui/CHANGELOG.md
  packages/utilities/CHANGELOG.md
  packages/validation/CHANGELOG.md
Labels: Approved, Linode Disk Encryption (LDE)

#11864 deps: [M3-9553] - Update `@babel/helpers` and `@babel/runtime` to latest
  pnpm-lock.yaml
Labels: Dependencies, Approved

#11860 upcoming: [DI-23784] - Restrict actions in alerts action menu
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-11860-upcoming-features-1742209993496.md
  packages/manager/cypress/support/constants/alert.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/constants.ts
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertsActionMenu.ts
  packages/manager/src/features/CloudPulse/Alerts/constants.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: Cloud Pulse - Alerting

#11846 refactor: [M3-9528] - Move dependency-free utilities from `sort-by.ts` to utilities package
  packages/manager/.changeset/pr-11846-removed-1741893679762.md
  packages/manager/.changeset/pr-11846-tests-1741970544754.md
  packages/manager/cypress/support/util/lke.ts
  packages/manager/src/components/OrderBy.tsx
  packages/manager/src/components/RegionSelect/RegionMultiSelect.stories.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/AccessKeyRegions.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/utils.ts
  packages/manager/src/utilities/sortByUTFDate.test.ts
  packages/manager/src/utilities/sortByUTFDate.ts
  packages/utilities/.changeset/pr-11846-added-1741893654719.md
  packages/utilities/src/helpers/index.ts
  packages/utilities/src/helpers/sort-by.test.ts
  packages/utilities/src/helpers/sort-by.ts
Labels: Approved, Modularization

#11850 refactor: [M3-9543] - Migrate hooks to `@linode/utilities` package
  packages/manager/.changeset/pr-11850-removed-1741945476887.md
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
  packages/manager/src/features/Managed/Contacts/Contacts.tsx
  packages/manager/src/features/Managed/Credentials/CredentialList.tsx
  packages/manager/src/features/Managed/Monitors/MonitorTable.tsx
  packages/manager/src/features/Managed/SSHAccess/SSHAccessTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_BucketLanding.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/utilities/.changeset/pr-11850-added-1741945489673.md
  packages/utilities/src/hooks/index.ts
  packages/utilities/src/hooks/useDialog.ts
  packages/utilities/src/hooks/useEditableLabelState.ts
  packages/utilities/src/hooks/useErrors.ts
  packages/utilities/src/hooks/useOpenClose.test.ts
  packages/utilities/src/hooks/useOpenClose.ts
Labels: Do Not Merge, Approved, Modularization

#11869 Fix:[DI-24064] - Fix navigation for metrics and alerts under Monitor
  packages/manager/.changeset/pr-11869-fixed-1742283252552.md
  packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
Labels: Approved, Cloud Pulse - Alerting, Cloud Pulse - Dashboards

#11862 test: [M3-9476] - Use "chooseRegion" util when mocking VPCs so tests pass in other envs
  packages/manager/.changeset/pr-11862-tests-1742223400134.md
  packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
  packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
Labels: Ready for Review

#11863 test: [M3-9477] - Allow Google Pay test to pass when using Braintree sandbox
  packages/manager/.changeset/pr-11863-tests-1742223285423.md
  packages/manager/cypress/e2e/core/billing/google-pay.spec.ts
Labels: Ready for Review

#11840 feat: [UIE-8141] - IAM RBAC: add new drawer for changing role flow
  packages/api-v4/.changeset/pr-11840-upcoming-features-1741881740441.md
  packages/api-v4/src/iam/iam.ts
  packages/manager/.changeset/pr-11840-upcoming-features-1741881680603.md
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
  packages/manager/src/features/IAM/Shared/utilities.test.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/queries/iam/iam.ts
  packages/queries/.changeset/pr-11840-upcoming-features-1741881790593.md
Labels: Approved, IAM (Identity & Access Management)

#11866 deps: [M3-9470] - Update `tsx`, `tsup`, and `vite` to resolve `esbuild` dependabot alert
  packages/api-v4/.changeset/pr-11866-tech-stories-1742243490708.md
  packages/api-v4/package.json
  packages/manager/.changeset/pr-11866-tech-stories-1742243451994.md
  packages/manager/.changeset/pr-11866-tech-stories-1742243555812.md
  packages/manager/package.json
  packages/validation/.changeset/pr-11866-tech-stories-1742243516966.md
  packages/validation/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: Dependencies

#11873 fix: Incorrect Drawer import in IAM
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
Labels: 🚨 Urgent

#11843 refactor: [M3-9393] - Move Volumes queries
  packages/manager/.changeset/pr-11843-removed-1742193586933.md
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/ConfigRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/StandardRescueDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/UpgradeVolumesDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/VolumesUpgradeBanner.tsx
  packages/manager/src/features/Linodes/MigrateLinode/CautionNotice.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketProductSelectionFields.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/Volumes/Dialogs/DeleteVolumeDialog.tsx
  packages/manager/src/features/Volumes/Dialogs/DetachVolumeDialog.tsx
  packages/manager/src/features/Volumes/Dialogs/UpgradeVolumeDialog.tsx
  packages/manager/src/features/Volumes/Drawers/AttachVolumeDrawer.tsx
  packages/manager/src/features/Volumes/Drawers/CloneVolumeDrawer.tsx
  packages/manager/src/features/Volumes/Drawers/EditVolumeDrawer.tsx
  packages/manager/src/features/Volumes/Drawers/ManageTagsDrawer.tsx
  packages/manager/src/features/Volumes/Drawers/ResizeVolumeDrawer.tsx
  packages/manager/src/features/Volumes/Drawers/VolumeDrawer/LinodeVolumeAttachForm.tsx
  packages/manager/src/features/Volumes/Drawers/VolumeDrawer/LinodeVolumeCreateForm.tsx
  packages/manager/src/features/Volumes/Drawers/VolumeDrawer/PricePanel.tsx
  packages/manager/src/features/Volumes/Drawers/VolumeDrawer/SizeField.tsx
  packages/manager/src/features/Volumes/Drawers/VolumeDrawer/VolumeSelect.tsx
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/queries/cloudpulse/queries.ts
  packages/manager/src/queries/linodes/events.ts
  packages/manager/src/queries/volumes/events.ts
  packages/queries/.changeset/pr-11843-added-1742193613127.md
  packages/queries/src/index.ts
  packages/queries/src/volumes/index.ts
  packages/queries/src/volumes/requests.ts
  packages/queries/src/volumes/volumes.ts
Labels: Approved, Modularization, Merge Conflicts

#11808 upcoming: [M3-9111] - Add Upgrade Interfaces dialog
  packages/manager/.changeset/pr-11808-upcoming-features-1741709450795.md
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/BootConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/ConfigSelectDialogContent.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/ConfigSelectDialogContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/ErrorDialogContent.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/ErrorDialogContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/PromptDialogContent.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/PromptDialogContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/SuccessDialogContent.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/SuccessDialogContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/UpgradeInterfacesDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/constants.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/types.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/useUpgradeToLinodeInterfaces.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetail.tsx
  packages/manager/src/mocks/mockState.ts
  packages/manager/src/mocks/presets/crud/handlers/linodes.ts
  packages/manager/src/mocks/presets/crud/linodes.ts
  packages/manager/src/mocks/types.ts
  packages/queries/.changeset/pr-11808-upcoming-features-1741795929482.md
  packages/queries/src/linodes/interfaces.ts
  packages/ui/src/components/Button/Button.tsx
  packages/utilities/src/factories/linodeInterface.ts
Labels: Approved, Linode Interfaces

#11819 refactor: [M3-9510] - Clean up main search implementation
  packages/manager/.changeset/pr-11819-changed-1741629531708.md
  packages/manager/.changeset/pr-11819-tech-stories-1741629552993.md
  packages/manager/src/__data__/searchResults.ts
  packages/manager/src/components/Tag/Tag.tsx
  packages/manager/src/constants.ts
  packages/manager/src/env.d.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.test.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/features/Linodes/presentation.test.tsx
  packages/manager/src/features/Linodes/presentation.ts
  packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/LinodeOrIPSelect.tsx
  packages/manager/src/features/Search/ResultGroup.tsx
  packages/manager/src/features/Search/ResultRow.tsx
  packages/manager/src/features/Search/SearchLanding.styles.ts
  packages/manager/src/features/Search/SearchLanding.test.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/Search/refinedSearch.test.ts
  packages/manager/src/features/Search/refinedSearch.ts
  packages/manager/src/features/Search/search.interfaces.ts
  packages/manager/src/features/Search/searchLanding.css
  packages/manager/src/features/Search/types.ts
  packages/manager/src/features/Search/useAPISearch.ts
  packages/manager/src/features/Search/useAPISearch.tsx
  packages/manager/src/features/Search/useClientSideSearch.ts
  packages/manager/src/features/Search/useSearch.ts
  packages/manager/src/features/Search/utils.test.ts
  packages/manager/src/features/Search/utils.ts
  packages/manager/src/features/Search/withStoreSearch.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketProductSelectionFields.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.test.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.tsx
  packages/manager/src/features/TopMenu/SearchBar/utils.tsx
  packages/manager/src/queries/databases/databases.ts
  packages/manager/src/queries/domains.ts
  packages/manager/src/queries/images.ts
  packages/manager/src/queries/kubernetes.ts
  packages/manager/src/queries/object-storage/queries.ts
  packages/manager/src/queries/stackscripts.ts
  packages/manager/src/store/selectors/getSearchEntities.ts
  packages/queries/src/firewalls/firewalls.ts
  packages/queries/src/linodes/linodes.ts
  packages/queries/src/nodebalancers/nodebalancers.ts
  packages/queries/src/volumes/volumes.ts
Labels: Approved, Search

#11876 deps: [M3-9470] - Upgrade Storybook to `8.6.7`
  packages/manager/.changeset/pr-11876-tech-stories-1742316906909.md
  packages/manager/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: Dependencies, Approved

#11847 upcoming: [M3-9535] - Support VPC interfaces on updated Linode Create Networking flow
  packages/api-v4/src/linodes/types.ts
  packages/manager/.changeset/pr-11847-tech-stories-1742223197152.md
  packages/manager/.changeset/pr-11847-upcoming-features-1742223153659.md
  packages/manager/src/components/VLANSelect.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Addons/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreate/Networking/LinodeInterface.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/Networking.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VLAN.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPC.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.test.ts
  packages/manager/src/features/Linodes/LinodeCreate/Networking/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreate/index.tsx
  packages/manager/src/features/Linodes/LinodeCreate/resolvers.ts
  packages/manager/src/features/Linodes/LinodeCreate/schemas.ts
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/utilities.ts
  packages/validation/.changeset/pr-11847-changed-1742223102140.md
  packages/validation/src/linodes.schema.ts
Labels: Approved, Linode Interfaces

#11859 refactor: [M3-9542] - Migrate utilities to `(at)linode/utilities` package - Part 4
  packages/manager/.changeset/pr-11859-removed-1742206785924.md
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
  packages/manager/src/components/AreaChart/AreaChart.stories.tsx
  packages/manager/src/components/LineGraph/LineGraph.stories.tsx
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/components/LineGraph/MetricsDisplay.test.tsx
  packages/manager/src/components/LineGraph/MetricsDisplay.tsx
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.test.ts
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Utils/utils.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.test.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/features/Firewalls/shared.ts
  packages/manager/src/features/Images/ImagesCreate/ImageUploadCLIDialog.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/features/Linodes/LinodeCreate/utilities.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/LinodeRebuildForm.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/NetworkGraphs.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyActionMenu.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTableRow.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesList.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/ViewPermissionsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/ObjectStorage/hooks/useIsObjectStorageGen2Enabled.tsx
  packages/manager/src/features/ObjectStorage/hooks/useObjectStorageRegions.tsx
  packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
  packages/manager/src/features/Support/SupportTickets/ticketUtils.ts
  packages/manager/src/features/components/PlansPanel/PlansAvailabilityNotice.test.tsx
  packages/manager/src/features/components/PlansPanel/PlansAvailabilityNotice.tsx
  packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
  packages/manager/src/features/components/PlansPanel/utils.ts
  packages/manager/src/queries/object-storage/queries.ts
  packages/utilities/.changeset/pr-11859-added-1742206804089.md
  packages/utilities/src/helpers/accountCapabilities.test.ts
  packages/utilities/src/helpers/accountCapabilities.ts
  packages/utilities/src/helpers/index.ts
  packages/utilities/src/helpers/metadata.test.ts
  packages/utilities/src/helpers/metadata.ts
  packages/utilities/src/helpers/planNotices.ts
  packages/utilities/src/helpers/regions.test.ts
  packages/utilities/src/helpers/regions.ts
  packages/utilities/src/helpers/statMetrics.test.ts
  packages/utilities/src/helpers/statMetrics.tsx
  packages/utilities/src/helpers/stringUtils.test.ts
  packages/utilities/src/helpers/stringUtils.ts
Labels: Wait to Merge, Approved, Modularization

#11877 change: [M3-9601] - Replace Label with Bucket Name
  packages/manager/.changeset/pr-11877-changed-1742349834239.md
  packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
  packages/manager/cypress/e2e/core/objectStorage/object-storage.smoke.spec.ts
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
  packages/manager/cypress/e2e/core/objectStorageMulticluster/bucket-create-multicluster.spec.ts
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.test.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/validation/.changeset/pr-11877-changed-1742349805597.md
  packages/validation/src/buckets.schema.ts
Labels: Object Storage, Approved

#11867 refactor: [M3-9591] - Cleanup token organization and paths
  docs/development-guide/16-design-tokens.md
  packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.tsx
  packages/manager/src/components/IconTextLink/IconTextLink.tsx
  packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
  packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
  packages/manager/src/components/PrimaryNav/SideMenu.tsx
  packages/manager/src/components/RegionSelect/RegionOption.tsx
  packages/manager/src/components/SelectionCard/CardBase.styles.ts
  packages/manager/src/components/Tag/Tag.styles.ts
  packages/manager/src/components/TagCell/TagCell.tsx
  packages/manager/src/features/Account/CloseAccountDialog.tsx
  packages/manager/src/features/Account/Quotas/QuotasIncreaseForm.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResourcesNotice.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/AlertInformationActionRow.tsx
  packages/manager/src/features/CloudPulse/Alerts/ContextualView/MetricThreshold.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannels/AddNotificationChannelDrawer.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResourcesConfirmationDialog.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertsNoticeMessage.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/utils.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.style.ts
  packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/PublicTemplateRules.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/VPCTemplateRules.tsx
  packages/manager/src/features/Footer.tsx
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.style.ts
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/SuccessDialogContent.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.styles.ts
  packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx
  packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx
  packages/manager/src/features/TopMenu/CreateMenu/CreateMenu.styles.ts
  packages/manager/src/features/TopMenu/InternalAdminBanner.tsx
  packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.styles.ts
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.styles.ts
  packages/manager/src/features/TopMenu/TopMenuTooltip.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenuPopover.tsx
  packages/ui/src/components/Button/StyledTagButton.ts
  packages/ui/src/components/DatePicker/Calendar/Calendar.styles.ts
  packages/ui/src/components/DatePicker/DateRangePicker/Presets.tsx
  packages/ui/src/components/DatePicker/TimePicker.tsx
  packages/ui/src/foundations/breakpoints.ts
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/index.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Design Tokens

#11875 upcoming: [M3-9096] - Add factories and mocks for new API `/v4/linode/interfaces` endpoints
  packages/manager/.changeset/pr-11875-tech-stories-1742315053264.md
  packages/manager/src/mocks/presets/crud/handlers/linodes.ts
  packages/manager/src/mocks/presets/crud/handlers/vpcs.ts
  packages/manager/src/mocks/presets/crud/linodes.ts
  packages/manager/src/mocks/types.ts
  packages/utilities/src/factories/linodeInterface.ts
Labels: Approved, Linode Interfaces

#11880 upcoming: [M3-9517] - Update LKE-E flows to account for LDE being disabled at LA launch
  packages/manager/.changeset/pr-11880-upcoming-features-1742329364209.md
  packages/manager/src/features/Kubernetes/ClusterList/constants.ts
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
Labels: Approved, LKE-Enterprise

#11882 fix: [M3-9605] - Spacing for Add SSH Key Drawer
  packages/ui/src/components/Drawer/Drawer.tsx
Labels: Bug, Approved

#11856 upcoming: [M3-9519] - Allow LKE-E IP ACL addresses to be optional with an explicit acknowledgement
  packages/api-v4/src/kubernetes/kubernetes.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/components/ErrorMessage.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.test.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx
  packages/manager/src/features/Kubernetes/constants.ts
  packages/manager/src/queries/images.ts
  packages/manager/src/queries/kubernetes.ts
  packages/validation/src/kubernetes.schema.ts
Labels: Approved, LKE-Enterprise

#11852 upcoming: [M3-9511] - VPC IPv6 - Update endpoints and types for VPC Entity
  packages/api-v4/.changeset/pr-11852-upcoming-features-1742414634244.md
  packages/api-v4/src/vpcs/types.ts
  packages/validation/.changeset/pr-11852-upcoming-features-1742414737915.md
  packages/validation/src/vpcs.schema.ts
Labels: Add'tl Approval Needed, VPC

#11883 change: [DI-24111] - Updated hovering color for dashboard icons
  packages/manager/.changeset/pr-11883-changed-1742377578472.md
  packages/manager/src/assets/icons/refresh.svg
  packages/manager/src/assets/icons/zoomin.svg
  packages/manager/src/assets/icons/zoomout.svg
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx
Labels: Cloud Pulse

#11828 upcoming: [M3-9105] - Add Account Default Firewalls setting
  packages/api-v4/src/firewalls/types.ts
  packages/manager/.changeset/pr-11828-upcoming-features-1741811633687.md
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/AccountLogins.tsx
  packages/manager/src/features/Account/AccountLoginsTableRow.tsx
  packages/manager/src/features/Account/CloseAccountDialog.tsx
  packages/manager/src/features/Account/CloseAccountSetting.tsx
  packages/manager/src/features/Account/DefaultFirewalls.test.tsx
  packages/manager/src/features/Account/DefaultFirewalls.tsx
  packages/manager/src/features/Account/GlobalSettings.tsx
  packages/manager/src/features/Account/NetworkInterfaceType.tsx
  packages/manager/src/features/Account/ObjectStorageSettings.tsx
  packages/queries/.changeset/pr-11828-upcoming-features-1741811672300.md
  packages/queries/src/firewalls/firewalls.ts
  packages/validation/src/firewalls.schema.ts
Labels: Approved, Linode Interfaces

#11889 chore: [M3-9600] - ESLint warning for theme.spacing
  packages/manager/.changeset/pr-11889-tech-stories-1742437360421.md
  packages/manager/.eslintrc.cjs
  packages/manager/package.json
  packages/queries/package.json
  packages/ui/package.json
  packages/utilities/package.json
  pnpm-lock.yaml
Labels: Dependencies, Approved, Tooling

#11898 test: [M3-9618] - Temporarily skip Firewall end-to-end tests
  packages/manager/.changeset/pr-11898-tests-1742493507045.md
  packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/delete-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
Labels: Approved, Ready for Review

#11899 security: [M3-9620] Remove unused utils with security vulnerabilities
  packages/utilities/.changeset/pr-11899-removed-1742563209985.md
  packages/utilities/src/helpers/stringUtils.test.ts
  packages/utilities/src/helpers/stringUtils.ts
Labels: Security, Approved

#11841 refactor: [M3-9435] [Akamai Design System] Breadcrumb Component
  packages/manager/.changeset/pr-11841-changed-1741884096366.md
  packages/manager/src/components/Breadcrumb/Breadcrumb.stories.tsx
  packages/manager/src/components/Breadcrumb/Crumbs.styles.tsx
  packages/manager/src/components/Breadcrumb/Crumbs.tsx
  packages/manager/src/components/Breadcrumb/FinalCrumb.styles.tsx
  packages/manager/src/components/Breadcrumb/FinalCrumb.tsx
  packages/ui/src/components/EditableText/EditableText.tsx
Labels: Approved, Design Tokens

#11896 upcoming: [M3-9512] - Update types and validation for VPC subnet
  packages/api-v4/.changeset/pr-11896-upcoming-features-1742491246746.md
  packages/api-v4/src/vpcs/types.ts
  packages/api-v4/src/vpcs/vpcs.ts
  packages/manager/src/features/VPCs/VPCDetail/SubnetCreateDrawer.tsx
  packages/validation/.changeset/pr-11896-upcoming-features-1742491352504.md
  packages/validation/src/vpcs.schema.ts
Labels: Approved, VPC IPv6

#11911 fix: Fix styling for Linode Entity Details body and footer
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailFooter.tsx
Labels: Bug

#11878 refactor: [M3-9431] [Akamai Design System] Radio Button Component
  packages/manager/.changeset/pr-11878-changed-1742325899299.md
  packages/ui/src/assets/icons/radio.svg
  packages/ui/src/assets/icons/radioRadioed.svg
  packages/ui/src/components/Radio/Radio.test.tsx
  packages/ui/src/components/Radio/Radio.tsx
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Design Tokens

#11892 test: [M3-8668] - Disallow legacy regions from being selected via `chooseRegion`
  packages/manager/.changeset/pr-11892-tests-1742564481277.md
  packages/manager/cypress/support/util/regions.ts
Labels: Approved, Ready for Review

#11842 upcoming: [M3-9109] - Update Firewall devices Linode landing table to account for new interfaces
  packages/api-v4/src/firewalls/types.ts
  packages/manager/.changeset/pr-11842-upcoming-features-1742225152205.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.test.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceTable.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/constants.ts
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.test.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/mocks/types.ts
  packages/queries/src/firewalls/firewalls.ts
  packages/queries/src/linodes/linodes.ts
Labels: Approved, Linode Interfaces

#11894 fix: [M3-9607] - Tabs keyboard navigation on Tanstack rerouted features
  packages/manager/.changeset/pr-11894-fixed-1742495460894.md
  packages/manager/cypress/component/components/tabs.spec.tsx
  packages/manager/cypress/support/component/setup.tsx
  packages/manager/cypress/support/util/components.ts
  packages/manager/package.json
  packages/manager/src/components/Tabs/SafeTabPanel.test.tsx
  packages/manager/src/components/Tabs/Tab.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/IntegrationsTabPanel.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/SDKTabPanel.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/hooks/useTabs.ts
  pnpm-lock.yaml
Labels: Approved, Routing Refactor

#11905 refactor: [M3-9545] - Add `luxon` dependency and move related utils
  packages/manager/.changeset/pr-11905-removed-1742540403425.md
  packages/manager/src/features/Events/utils.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/ScheduleSettings.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/Apache.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINX.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
  packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
  packages/utilities/.changeset/pr-11905-added-1742540619261.md
  packages/utilities/package.json
  packages/utilities/src/helpers/formatDuration.test.ts
  packages/utilities/src/helpers/formatDuration.ts
  packages/utilities/src/helpers/formatUptime.test.ts
  packages/utilities/src/helpers/formatUptime.ts
  packages/utilities/src/helpers/index.ts
  packages/utilities/src/helpers/initWindows.test.ts
  packages/utilities/src/helpers/initWindows.ts
  packages/utilities/src/helpers/isToday.test.ts
  packages/utilities/src/helpers/isToday.ts
  pnpm-lock.yaml
Labels: Dependencies, Approved, Modularization

#11884 change: [M3-9437] - Akamai Design System: Profile Menu
  packages/manager/.changeset/pr-11884-changed-1742456199053.md
  packages/manager/src/assets/icons/swapSmall.svg
  packages/manager/src/features/Account/SwitchAccountButton.tsx
  packages/manager/src/features/TopMenu/UserMenu/UserMenuPopover.tsx
Labels: Approved, Design Tokens

#11832 upcoming: [M3-9421] - Add API endpoints and types for `/v4/nodebalancers`
  packages/api-v4/.changeset/pr-11832-upcoming-features-1741778030625.md
  packages/api-v4/src/nodebalancers/nodebalancer-configs.ts
  packages/api-v4/src/nodebalancers/nodebalancers.ts
  packages/api-v4/src/nodebalancers/types.ts
  packages/api-v4/src/nodebalancers/utils.ts
Labels: Approved, NB-VPC

#11871 change: [M3-9430] - Akamai Design System: Checkbox Component
  packages/ui/.changeset/pr-11871-changed-1742300523305.md
  packages/ui/src/components/Checkbox/Checkbox.stories.tsx
  packages/ui/src/components/Checkbox/Checkbox.tsx
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Design Tokens

#11834 feat: [UIE-8140] - IAM RBAC - Assign New Roles drawer update
  packages/manager/.changeset/pr-11834-upcoming-features-1741795011556.md
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignSingleRole.tsx
Labels: Approved, IAM (Identity & Access Management)

#11923 fix: [M3-9652] - Packages unable to publish
  .github/workflows/ci.yml
  packages/manager/.changeset/pr-11923-tech-stories-1742933716536.md
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.test.tsx
Labels: Bug, Approved

#11886 test: [M3-9486, M3-9487, M3-9557] - Allow Linode create tests to pass in alternative environments
  packages/manager/.changeset/pr-11886-tests-1742401040412.md
  packages/manager/.changeset/pr-11886-tests-1742401071717.md
  packages/manager/.changeset/pr-11886-tests-1742401097314.md
  packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
  packages/manager/cypress/support/util/tag.ts
Labels: Approved, Ready for Review

#11891 refactor: [M3-9617] - Move `doesRegionSupportFeature` to `utilities` package
  packages/manager/.changeset/pr-11891-removed-1742474181923.md
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VLAN/VLAN.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VLAN/VLANAvailabilityNotice.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/VPCPanel.tsx
  packages/manager/src/features/Volumes/Drawers/VolumeDrawer/LinodeVolumeCreateForm.tsx
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/utilities/.changeset/pr-11891-added-1742474194986.md
  packages/utilities/src/helpers/doesRegionSupportFeature.test.ts
  packages/utilities/src/helpers/doesRegionSupportFeature.ts
  packages/utilities/src/helpers/index.ts
Labels: Approved, Modularization

#11861 refactor: [M3-8247] - Remove ramda from Utilities
  packages/manager/.changeset/pr-11861-removed-1742218921343.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/utilities/createStringsFromDevices.ts
  packages/manager/src/utilities/creditCard.test.ts
  packages/manager/src/utilities/creditCard.ts
  packages/manager/src/utilities/formikErrorUtils.ts
  packages/manager/src/utilities/getSelectedOptionFromGroupedOptions.test.ts
  packages/manager/src/utilities/getSelectedOptionFromGroupedOptions.ts
  packages/manager/src/utilities/isNilOrEmpty.test.ts
  packages/manager/src/utilities/isNilOrEmpty.ts
  packages/manager/src/utilities/mergeDeepRight.test.ts
  packages/manager/src/utilities/mergeDeepRight.ts
  packages/manager/src/utilities/testHelpers.tsx
  packages/utilities/src/helpers/initWindows.ts
Labels: Approved, Tech Debt

#11893 feat: [UIE-8600] - IAM RBAC: add new drawer for unassigning role flow
  packages/manager/.changeset/pr-11893-upcoming-features-1742481856731.md
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesActionMenu.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesActionMenu.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UnassignRoleConfirmationDialog.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UnassignRoleConfirmationDialog.tsx
  packages/manager/src/features/IAM/Shared/utilities.test.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
Labels: IAM (Identity & Access Management)

#11812 upcoming: [UIE-8515] - DBaaS: Advanced Configuration - Drawer with existing configs
  packages/api-v4/.changeset/pr-11812-added-1741611699926.md
  packages/api-v4/src/databases/databases.ts
  packages/api-v4/src/databases/types.ts
  packages/manager/.changeset/pr-11812-upcoming-features-1741612097921.md
  packages/manager/src/factories/databases.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfiguration.style.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfiguration.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfigurationDrawer.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.style.ts
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationSelect.tsx
  packages/manager/src/features/Databases/utilities.test.ts
  packages/manager/src/features/Databases/utilities.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/databases/databases.ts
Labels: DBaaS, Approved

#11925 hotfix: Revert Authentication Changes
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/parentChild/token-expiration.spec.ts
  packages/manager/package.json
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.test.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.tsx
  packages/manager/src/features/Account/SwitchAccounts/useParentChildAuthentication.tsx
  packages/manager/src/features/Account/SwitchAccounts/utils.ts
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/hooks/useAuthentication.ts
  packages/manager/src/hooks/useInitialRequests.ts
  packages/manager/src/index.tsx
  packages/manager/src/layouts/LoginAsCustomerCallback.tsx
  packages/manager/src/layouts/Logout.test.tsx
  packages/manager/src/layouts/Logout.tsx
  packages/manager/src/layouts/OAuth.test.tsx
  packages/manager/src/layouts/OAuth.tsx
  packages/manager/src/layouts/OAuthCallback.tsx
  packages/manager/src/request.test.tsx
  packages/manager/src/request.tsx
  packages/manager/src/session.ts
  packages/manager/src/store/authentication/authentication.actions.ts
  packages/manager/src/store/authentication/authentication.helpers.ts
  packages/manager/src/store/authentication/authentication.reducer.ts
  packages/manager/src/store/authentication/authentication.requests.ts
  packages/manager/src/store/authentication/authentication.test.ts
  packages/manager/src/store/authentication/index.ts
  packages/manager/src/store/index.ts
  packages/manager/src/utilities/authentication.ts
  packages/manager/src/utilities/storage.ts
  packages/manager/src/utilities/theme.ts
Labels: Hotfix

#11908 DX: [M3-9254] - Dev Tools Tokens
  packages/manager/src/dev-tools/DesignTokensTool.tsx
  packages/manager/src/dev-tools/DevTools.tsx
  packages/manager/src/dev-tools/EnvironmentToggleTool.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/dev-tools/ServiceWorkerTool.tsx
  packages/manager/src/dev-tools/ThemeSelector.tsx
  packages/manager/src/dev-tools/components/DevToolSelect.tsx
  packages/manager/src/dev-tools/components/Draggable.tsx
  packages/manager/src/dev-tools/components/ExtraPresetAccount.tsx
  packages/manager/src/dev-tools/components/ExtraPresetOptionSelect.tsx
  packages/manager/src/dev-tools/components/ExtraPresetProfile.tsx
  packages/manager/src/dev-tools/components/Tokens/ColorSwatch.tsx
  packages/manager/src/dev-tools/components/Tokens/TokenCopy.tsx
  packages/manager/src/dev-tools/components/Tokens/TokenInfo.tsx
  packages/manager/src/dev-tools/components/Tokens/TokenSection.tsx
  packages/manager/src/dev-tools/components/Tokens/utils.ts
  packages/manager/src/dev-tools/dev-tools.css
Labels: Design Tokens

#11927 Release v1.138.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/parentChild/token-expiration.spec.ts
  packages/manager/package.json
  packages/manager/src/components/AccessPanel/UserSSHKeyPanel.test.tsx
  packages/manager/src/features/Account/SwitchAccountDrawer.tsx
  packages/manager/src/features/Account/SwitchAccounts/useParentChildAuthentication.tsx
  packages/manager/src/features/Account/SwitchAccounts/utils.ts
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.test.tsx
  packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
  packages/manager/src/features/TopMenu/TopMenu.tsx
  packages/manager/src/hooks/useAuthentication.ts
  packages/manager/src/hooks/useInitialRequests.ts
  packages/manager/src/index.tsx
  packages/manager/src/layouts/LoginAsCustomerCallback.tsx
  packages/manager/src/layouts/Logout.test.tsx
  packages/manager/src/layouts/Logout.tsx
  packages/manager/src/layouts/OAuth.test.tsx
  packages/manager/src/layouts/OAuth.tsx
  packages/manager/src/layouts/OAuthCallback.tsx
  packages/manager/src/request.test.tsx
  packages/manager/src/request.tsx
  packages/manager/src/session.ts
  packages/manager/src/store/authentication/authentication.actions.ts
  packages/manager/src/store/authentication/authentication.helpers.ts
  packages/manager/src/store/authentication/authentication.reducer.ts
  packages/manager/src/store/authentication/authentication.requests.ts
  packages/manager/src/store/authentication/authentication.test.ts
  packages/manager/src/store/authentication/index.ts
  packages/manager/src/store/index.ts
  packages/manager/src/utilities/authentication.ts
  packages/manager/src/utilities/storage.ts
  packages/manager/src/utilities/theme.ts
Labels: Release, Hotfix

#11913 refactor: [M3-9616] - Move `ramda` dependent utils
  packages/manager/.changeset/pr-11913-removed-1742847225104.md
  packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordDrawerUtils.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/StandardRescueDialog.tsx
  packages/manager/src/features/Volumes/Drawers/VolumeDrawer/LinodeVolumeCreateForm.tsx
  packages/manager/src/features/Volumes/VolumeCreate.tsx
  packages/manager/src/utilities/formikErrorUtils.ts
  packages/utilities/.changeset/pr-11913-added-1742915642212.md
  packages/utilities/src/helpers/createDevicesFromStrings.test.ts
  packages/utilities/src/helpers/createDevicesFromStrings.ts
  packages/utilities/src/helpers/createStringsFromDevices.test.ts
  packages/utilities/src/helpers/createStringsFromDevices.ts
  packages/utilities/src/helpers/index.ts
  packages/utilities/src/helpers/isNilOrEmpty.test.ts
  packages/utilities/src/helpers/isNilOrEmpty.ts
  packages/utilities/src/helpers/maybeCastToNumber.ts
Labels: Approved, Modularization

#11903 upcoming:[DI-24187] - Update success message for edit/create/enable/disable alert
  packages/manager/.changeset/pr-11903-upcoming-features-1742542218295.md
  packages/manager/cypress/e2e/core/cloudpulse/alerts-listing-page.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/edit-user-alert.spec.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/constants.ts
Labels: Approved, Cloud Pulse - Alerting

#11917 refactor: [DI-24193] - Update query cache on api success
  packages/manager/.changeset/pr-11917-added-1743002198888.md
  packages/manager/src/queries/cloudpulse/alerts.ts
Labels: Approved, Cloud Pulse, Cloud Pulse - Alerting

#11865 upcoming: [M3-9530] - Display interface type first in Linode Network IP Addresses table
  packages/manager/.changeset/pr-11865-changed-1742248570726.md
  packages/manager/cypress/e2e/core/linodes/linode-network.spec.ts
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/DeleteIPDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/DeleteRangeDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/ExplainerCopy.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.test.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/types.ts
Labels: Approved, Linode Interfaces

#11888 upcoming: [M3-9118] - Add the Interface Details drawer
  packages/manager/.changeset/pr-11888-upcoming-features-1742589295521.md
  packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/PublicTemplateRules.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/VPCTemplateRules.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/SuccessDialogContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceDetailsDrawer/InterfaceDetailsContent.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceDetailsDrawer/InterfaceDetailsContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceDetailsDrawer/InterfaceDetailsDrawer.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceDetailsDrawer/PublicInterfaceDetailsContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceDetailsDrawer/VPCInterfaceDetailsContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/InterfaceDetailsDrawer/VlanInterfaceDetailsContent.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaceActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/LinodeInterfaces.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
Labels: Approved, Linode Interfaces

#11901 upcoming: [M3-9588] - Add VPC & Firewall section to LKE-E create flow
  packages/manager/.changeset/pr-11901-upcoming-features-1742509729379.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/features/Kubernetes/CreateCluster/ClusterNetworkingPanel.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
Labels: Approved, LKE-Enterprise

#11930 fix: [M3-9669] – Adjust conditions for displaying encryption status on Linode Details page & encryption copy on LKE Create page
  packages/manager/.changeset/pr-11930-upcoming-features-1743025907787.md
  packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
Labels: Approved, Linode Disk Encryption (LDE)

#11922 refactor: [M3-9416] - Move feature flag code out of Kubernetes queries file
  packages/manager/.changeset/pr-11922-tech-stories-1742933251448.md
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
  packages/manager/src/features/Search/useClientSideSearch.ts
  packages/manager/src/features/Support/SupportTickets/SupportTicketProductSelectionFields.tsx
  packages/manager/src/queries/kubernetes.ts
Labels: Approved, Modularization, LKE-Enterprise, APL

#11929 change: [M3-9670] - Remove region selector from Edit VPC drawer
  packages/manager/.changeset/pr-11929-fixed-1743022527992.md
  packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.tsx
Labels: Approved, VPC

#11904 refactor: [M3-9389] - Move Support queries
  packages/manager/.changeset/pr-11904-removed-1742539061783.md
  packages/manager/src/features/Account/Quotas/QuotasIncreaseForm.tsx
  packages/manager/src/features/Support/SupportTicketDetail/CloseTicketLink.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
  packages/manager/src/features/Support/SupportTickets/TicketList.test.tsx
  packages/manager/src/features/Support/SupportTickets/TicketList.tsx
  packages/manager/src/queries/support.ts
  packages/queries/.changeset/pr-11904-added-1742539115195.md
  packages/queries/src/index.ts
  packages/queries/src/support/index.ts
  packages/queries/src/support/support.ts
Labels: Approved, Modularization

#11912 test: [M3-7510] - Cypress tests for Databases create page for restricted users
  packages/manager/.changeset/pr-11912-tests-1743006972477.md
  packages/manager/cypress/e2e/core/databases/create-database.spec.ts
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
Labels: Testing, Approved

#11897 refactor: [M3-9390] - Move Tags queries
  packages/manager/.changeset/pr-11897-removed-1742493750939.md
  packages/manager/src/components/TagCell/AddTag.tsx
  packages/manager/src/components/TagsInput/TagsInput.tsx
  packages/manager/src/factories/tags.ts
  packages/queries/.changeset/pr-11897-added-1742493818548.md
  packages/queries/src/index.ts
  packages/queries/src/tags/index.ts
  packages/queries/src/tags/tags.ts
Labels: Approved, Modularization
