Repository linode/manager, pull requests merged in 2025-10, with the labels that each got.

#12932 feat: [UIE-9248] - IAM RBAC: replace grants in Linodes
  packages/manager/.changeset/pr-12932-changed-1759233206741.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/StandardRescueDialog.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskActionMenu.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskActionMenu.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskRow.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDisks.tsx
Labels: Linodes, IAM (Identity & Access Management)

#12847 test: [M3-10506] - Fix flaky Object Storage Multicluster object upload test
  packages/manager/.changeset/pr-12847-tests-1757523022214.md
  packages/manager/cypress/e2e/core/objectStorageMulticluster/object-storage-objects-multicluster.spec.ts
Labels: Stale

#12939 feat: [UIE-9181] - DBaaS - Display hostname in summary tables based on VPC configuration and refactor connection details
  packages/manager/.changeset/pr-12939-added-1759348628476.md
  packages/manager/.changeset/pr-12939-changed-1759348579491.md
  packages/manager/src/features/Databases/DatabaseDetail/ConnectionDetailsHostRows.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/ConnectionDetailsHostRows.tsx
  packages/manager/src/features/Databases/DatabaseDetail/ConnectionDetailsRow.test.tsx
  packages/manager/src/features/Databases/DatabaseDetail/ConnectionDetailsRow.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseNetworking/DatabaseManageNetworking.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
  packages/manager/src/features/Databases/constants.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: 🚨 Urgent, DBaaS

#12947 fix: [M3-10659] - Update placeholder text color
  packages/manager/.changeset/pr-12947-fixed-1759415336915.md
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Bug

#12897 test: [DI-27320] - Add DBaaS widget tests with group-by feature
  packages/manager/.changeset/pr-12897-tests-1758514789710.md
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/nodebalancer-widget-verification.spec.ts
  packages/manager/cypress/support/constants/widgets.ts
  packages/manager/cypress/support/intercepts/cloudpulse.ts
  packages/manager/src/features/CloudPulse/GroupBy/CloudPulseGroupByDrawer.tsx
Labels: Approved, Cloud Pulse

#12934 fix: [UIE-9266], [UIE-9268], [UIE-9299] - IAM RBAC: Fix permission checks for subnet actions in VPC, fetch permissions only when drawer is open
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeActionMenu.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
Labels: VPC, IAM (Identity & Access Management)

#12944 upcoming: [DPS-34980] Fix Destination Name autocomplete in stream form not filtering correctly
  packages/manager/.changeset/pr-12944-upcoming-features-1759397682222.md
  packages/manager/src/features/Delivery/Streams/StreamForm/Delivery/StreamFormDelivery.tsx
  packages/manager/src/features/Delivery/Streams/StreamsLanding.tsx
Labels: Approved, Logs

#12940 refactor: [M3-10638] - VPC IPv4 and IPv6 address code clean up
  packages/manager/.changeset/pr-12940-tech-stories-1759341754178.md
  packages/manager/src/features/Linodes/LinodeCreate/Networking/VPC.tsx
  packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VPC/AddVPCIPv4Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VPC/AddVPCIPv6Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VPC/VPCIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VPC/VPCIPv4Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/VPC/VPCIPv6Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/VPCInterface/EditVPCIPv4Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/VPCInterface/EditVPCIPv6Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/VPCInterface/PublicAccess.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/VPCInterface/VPCIPAddresses.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/VPCInterface/VPCIPv4Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/VPCInterface/VPCIPv6Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/PublicIPv4Access.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/PublicIPv6Access.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/VPCIPv4Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/VPCIPv6Address.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/VPCPanel.tsx
  packages/manager/src/features/VPCs/components/VPCPublicIPLabel.tsx
Labels: Approved, Clean Up, VPC

#12958 feat: [UIE-9329] - IAM RBAC: refetch entities
  packages/manager/.changeset/pr-12958-fixed-1759747213086.md
  packages/manager/src/queries/entities/entities.ts
Labels: Add'tl Approval Needed, IAM (Identity & Access Management)

#12962 fix: [UIE-9340] - IAM: User Menu Beta badge fix
  packages/manager/src/features/TopMenu/UserMenu/UserMenuPopover.tsx
Labels: IAM (Identity & Access Management)

#12648 feat: Allow multi-cluster Marketplace deployments
  packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Summary/utilities.test.ts
  packages/manager/src/features/Linodes/LinodeCreate/Summary/utilities.ts
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/UserDefinedFields/UserDefinedFields.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/UserDefinedFields/utilities.test.ts
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/UserDefinedFields/utilities.ts
Labels: Marketplace, Approved

#12864 upcoming: [M3-10617, M3-10451] - Upgrade from MUI-x v7 to v8
  packages/manager/.changeset/pr-12864-tech-stories-1757970225518.md
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/nodebalancer-widget-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/timerange-verification.spec.ts
  packages/manager/cypress/support/constants/widgets.ts
  packages/manager/cypress/support/util/cloudpulse.ts
  packages/manager/package.json
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.test.ts
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/ui/.changeset/pr-12864-fixed-1757944761045.md
  packages/ui/package.json
  packages/ui/src/assets/icons/chevron-left.svg
  packages/ui/src/assets/icons/chevron-right.svg
  packages/ui/src/components/DatePicker/Calendar/Calendar.styles.ts
  packages/ui/src/components/DatePicker/Calendar/Calendar.tsx
  packages/ui/src/components/DatePicker/DateField.tsx
  packages/ui/src/components/DatePicker/DateRangePicker/DateRangePicker.test.tsx
  packages/ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
  packages/ui/src/components/DatePicker/DateRangePicker/Presets.tsx
  packages/ui/src/components/DatePicker/DateTimeField.tsx
  packages/ui/src/components/DatePicker/DateTimeRangePicker/DateTimeRangePicker.stories.tsx
  packages/ui/src/components/DatePicker/DateTimeRangePicker/DateTimeRangePicker.test.tsx
  packages/ui/src/components/DatePicker/DateTimeRangePicker/DateTimeRangePicker.tsx
  packages/ui/src/components/DatePicker/TimePicker.tsx
  packages/ui/src/components/DatePicker/utils.ts
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/index.ts
  packages/ui/src/foundations/themes/light.ts
  pnpm-lock.yaml
Labels: Approved, Ready for Review, Requires UX Approval
