Repository linode/manager, pull requests merged in 2025-05, with the labels that each got.

#12136 fix: [M3-9847] - PayPal button styles in dark mode
  packages/api-v4/src/account/payments.ts
  packages/manager/.changeset/pr-12136-fixed-1746028814998.md
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/index.ts
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
  packages/queries/.changeset/pr-12136-added-1746028890631.md
  packages/queries/src/account/payment.ts
Labels: Bug

#12133 upcoming: [DI-24840] - Disable create button when list api is loading
  packages/manager/.changeset/pr-12133-upcoming-features-1746014537173.md
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
Labels: Approved, Cloud Pulse - Alerting

#12144 fix: [M3-9891] - Actual fix for 'Improve validation and UX for ACL IP Address fields'
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
Labels: Bug, 🚨 Urgent, LKE, Approved

#12139 fix: [M3-9886] - Update how UpgradeVersionModal handles versioning to account for upgrades to versions older than the latest
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/kubernetes/lke-landing-page.spec.ts
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeKubernetesVersionBanner.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/Kubernetes/UpgradeVersionModal.tsx
Labels: 🚨 Urgent, LKE, Approved

#12151 upcoming: [M3-9490] – Add support for VPC IPv6 feature flag
  packages/manager/.changeset/pr-12151-upcoming-features-1746210671339.md
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
Labels: Approved, VPC IPv6

#12134 upcoming: [DI-24750] - Capability to delete an user alert
  packages/api-v4/.changeset/pr-12134-upcoming-features-1746018597838.md
  packages/api-v4/src/cloudpulse/alerts.ts
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/.changeset/pr-12134-upcoming-features-1746018527588.md
  packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertActionMenu.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertsTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/GroupedAlertsTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/GroupedAlertsTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/AlertsActionMenu.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/alerts.ts
Labels: Approved, Cloud Pulse - Alerting

#12149 test: [M3-9579] - Bugfix for Image Search test
  packages/manager/.changeset/pr-12149-tests-1746199265746.md
  packages/manager/cypress/e2e/core/images/search-images.spec.ts
Labels: Testing, Approved

#12146 fix: [M3-9883] - Fix Upgrade Interface issues: URL navigation and `Unable to find this Interfaces Firewall device` in Edit Interface Drawer
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/SuccessDialogContent.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRowFirewallsCell.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx
  packages/manager/src/hooks/useInterfaceDataForLinode.ts
  packages/queries/src/linodes/interfaces.ts
Labels: 🚨 Urgent, Approved, Linode Interfaces

#12099 upcoming: [M3-9423] – Update types based on changes to `v4/vpcs` endpoints
  packages/api-v4/.changeset/pr-12099-upcoming-features-1745522965929.md
  packages/api-v4/src/vpcs/types.ts
  packages/manager/src/factories/subnets.ts
  packages/manager/src/factories/vpcs.ts
Labels: Approved, NB-VPC

#12143 feat: [M3-9890] - Support Akamai Employee Banners on the Linode Create flow when using Linode Interfaces
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Linodes/LinodeCreate/Actions.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Firewall.tsx
  packages/manager/src/features/Linodes/LinodeCreate/FirewallAuthorization.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/Firewall.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceFirewall.tsx
  packages/manager/src/features/Linodes/LinodeCreate/index.tsx
  packages/manager/src/features/Linodes/LinodeCreate/resolvers.ts
Labels: 🚨 Urgent, Approved, Secure VMs

#11956 upcoming: [M3-9458] - LKE for Restricted users
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-11956-upcoming-features-1745238069164.md
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
  packages/manager/cypress/support/constants/user-permissions.ts
  packages/manager/src/features/Account/constants.ts
  packages/manager/src/features/Account/utils.ts
  packages/manager/src/features/Kubernetes/ClusterList/ClusterActionMenu.tsx
  packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
  packages/manager/src/features/Users/UserPermissions.tsx
  packages/manager/src/queries/kubernetes.ts
  packages/utilities/src/factories/grants.ts
Labels: Approved, Restricted User Access

#12158 test: [M3-9838] - Add test coverage for Adobe Launch and Cloud Manager
  packages/manager/.changeset/pr-12158-tests-1746552988253.md
  packages/manager/cypress/e2e/core/general/analytics.spec.ts
Labels: Approved, Analytics

#12127 test: [M3-9479] - Fix DBaaS Cypress test region mocks so tests pass in DevCloud
  packages/manager/.changeset/pr-12127-tests-1745948285700.md
  packages/manager/cypress/e2e/core/databases/create-database.spec.ts
  packages/manager/cypress/support/util/regions.ts
Labels: Approved

#12164 test: [M3-9915] - Improve Cypress OBJ bucket clean up stability
  packages/manager/.changeset/pr-12164-tests-1746553359993.md
  packages/manager/cypress/support/api/objectStorage.ts
Labels: Ready for Review

#12165 fix: [M3-8994] OBJ landing redirect
  packages/manager/.changeset/pr-12165-fixed-1746561971348.md
  packages/manager/src/routes/objectStorage/index.ts
Labels: Approved

#12168 upcoming: [M3-9909] - Update MTC plan check per updated design doc
  packages/manager/.changeset/pr-12168-upcoming-features-1746617724134.md
  packages/manager/src/features/components/PlansPanel/constants.ts
Labels: Approved, mtc-2025

#12172 test: [M3-9924] - Fix Cypress rebuild test by using Alpine Linux 3.20 Image following deprecation of 3.18
  packages/manager/.changeset/pr-12172-tests-1746640484987.md
  packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
Labels: Testing, Approved

#12167 feat: [UIE-8762, UIE-8621] - IAM RBAC: update text, fix sorting
  packages/manager/.changeset/pr-12167-upcoming-features-1746614302548.md
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UpdateEntitiesDrawer.test.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/UpdateEntitiesDrawer.tsx
  packages/manager/src/features/IAM/Shared/constants.ts
  packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
  packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.test.tsx
  packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
  packages/manager/src/features/IAM/Users/UserEntities/ChangeRoleForEntityDrawer.test.tsx
  packages/manager/src/features/IAM/Users/UserEntities/ChangeRoleForEntityDrawer.tsx
  packages/manager/src/features/IAM/Users/UserEntities/UserEntities.test.tsx
  packages/manager/src/features/IAM/Users/UserEntities/UserEntities.tsx
  packages/manager/src/features/IAM/Users/UserRoles/UserRoles.test.tsx
  packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
  packages/manager/src/features/IAM/Users/UsersTable/UsersActionMenu.test.tsx
  packages/manager/src/features/IAM/Users/UsersTable/UsersActionMenu.tsx
Labels: Approved, IAM (Identity & Access Management)

#12173 test: [M3-9479] - Remove mock regions for Database Cluster
  packages/manager/cypress/support/util/regions.ts
Labels: Approved

#12171 change: [M3-9925] - Add validation rules on changeset description
  docs/CONTRIBUTING.md
  scripts/changelog/changeset.mjs
Labels: Approved

#12005 refactor: [M3-9656] - [Akamai Design System] Label Component
  packages/shared/src/components/LinodeSelect/LinodeSelect.test.tsx
  packages/ui/src/components/TextField/TextField.stories.tsx
  packages/ui/src/components/TextField/TextField.tsx
  packages/ui/src/components/TooltipIcon/TooltipIcon.stories.tsx
  packages/ui/src/components/TooltipIcon/TooltipIcon.tsx
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved, Ready for Review, Design Tokens, Requires UX Approval

#12177 upcoming: [M3-9492] - Add queries for VPC IPs endpoints
  packages/queries/.changeset/pr-12177-upcoming-features-1746731515329.md
  packages/queries/src/vpcs/requests.ts
  packages/queries/src/vpcs/vpcs.ts
Labels: VPC IPv6

#12108 change: [M3-9433] - Update styles to match CDS for Entity Header, Notification sections and layout spacing
  packages/manager/.changeset/pr-11857-changed-1741982641599.md
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/AreaChart/utils.test.ts
  packages/manager/src/components/Breadcrumb/Breadcrumb.styles.tsx
  packages/manager/src/components/LandingHeader/LandingHeader.tsx
  packages/manager/src/components/Tabs/TabList.tsx
  packages/manager/src/components/Tabs/__snapshots__/TabList.test.tsx.snap
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
  packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
  packages/manager/src/features/Databases/DatabaseDetail/index.tsx
  packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
  packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
  packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.styles.ts
  packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.tsx
  packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
  packages/manager/src/features/IAM/IAMLanding.tsx
  packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageCreateContainer.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/Marketplace.tsx
  packages/manager/src/features/Linodes/LinodeCreate/index.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
  packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/Managed/ManagedLanding.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
  packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.tsx
  packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptLandingTable.tsx
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptsLanding.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/tsconfig.json
  packages/ui/src/components/EditableText/EditableText.tsx
  packages/ui/src/components/Notice/Notice.styles.ts
Labels: Requires UX Approval

#12178 hotfix: [M3-9944] - State issue with Object Storage access key drawer
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
Labels: Approved, Hotfix

#12166 fix: [M3-9917] - Internal Akamai Employee Firewall Policy banner logic
  packages/manager/.changeset/pr-12166-fixed-1746574391327.md
  packages/manager/src/features/Linodes/LinodeCreate/Actions.tsx
  packages/manager/src/features/Linodes/LinodeCreate/FirewallAuthorization.tsx
  packages/manager/src/features/Linodes/LinodeCreate/resolvers.ts
  packages/manager/src/features/Linodes/LinodeCreate/utilities.test.tsx
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
Labels: Bug, Approved, Secure VMs, Linode Interfaces

#12186 Release v1.141.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/package.json
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
Labels: Release, Hotfix

#12174 upcoming: [DI-24898] - Add view control for cloudpulse filters
  packages/manager/.changeset/pr-12174-upcoming-features-1746687422617.md
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.ts
  packages/manager/src/features/CloudPulse/Utils/models.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
Labels: Approved, Cloud Pulse - Dashboards

#12184 fix: [UIE-8679, UIE-8532] - Assigned Permissions Panel, Entities Table: Styling Issues
  packages/manager/.changeset/pr-12184-upcoming-features-1747047890188.md
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.style.ts
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
  packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignSingleRole.tsx
Labels: Approved, IAM (Identity & Access Management)

#12102 tech-story: [M3-9832] - Update `@paypal/react-paypal-js` to `^8.8.3`
  packages/manager/.changeset/pr-12102-tech-stories-1745500769863.md
  packages/manager/package.json
  packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.test.tsx
  packages/manager/src/features/Billing/BillingDetail.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.test.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
  packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.test.tsx
  pnpm-lock.yaml
Labels: Dependencies, Approved

#12196 Revert "refactor: [M3-9656] - [Akamai Design System] Label Component"
  packages/shared/src/components/LinodeSelect/LinodeSelect.test.tsx
  packages/ui/src/components/TextField/TextField.stories.tsx
  packages/ui/src/components/TextField/TextField.tsx
  packages/ui/src/components/TooltipIcon/TooltipIcon.stories.tsx
  packages/ui/src/components/TooltipIcon/TooltipIcon.tsx
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Approved

#12195 tech story: [M3-9964] - Delete root level `.eslintrc.js`
  .eslintrc.js
  packages/manager/.changeset/pr-12195-tech-stories-1747064399669.md
Labels: Clean Up, Tooling

#12159 fix: [M3-9894] - Use outlined warning icon in Firewall warning banner
  packages/manager/.changeset/pr-12159-fixed-1746488156627.md
  packages/manager/src/components/AkamaiBanner/AkamaiBanner.styles.ts
  packages/manager/src/components/AkamaiBanner/AkamaiBanner.tsx
Labels: Approved, Secure VMs

#12194 fix: [M3-9958] - StackScripts Landing description truncation
  packages/manager/.changeset/pr-12194-fixed-1747062971408.md
  packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptRow.tsx
Labels: Bug, UX/UI, Approved

#12188 fix: [M3-9957] - Add `/v4beta` endpoints for Node Pools and use POST `/v4beta` when adding a new LKE-E Node Pool
  packages/api-v4/.changeset/pr-12188-upcoming-features-1747068993421.md
  packages/api-v4/src/kubernetes/nodePools.ts
  packages/api-v4/src/kubernetes/types.ts
  packages/manager/.changeset/pr-12188-upcoming-features-1747069173199.md
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
  packages/manager/src/mocks/presets/crud/handlers/kubernetes.ts
  packages/manager/src/queries/kubernetes.ts
  packages/validation/.changeset/pr-12188-upcoming-features-1747069233094.md
  packages/validation/src/kubernetes.schema.ts
Labels: 🚨 Urgent, Approved, Ready for Review, LKE-Enterprise

#12175 upcoming: [DI-24826] - Added text box in create alert
  packages/manager/.changeset/pr-12175-upcoming-features-1746693256640.md
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilterField.tsx
  packages/manager/src/features/CloudPulse/Alerts/constants.ts
Labels: Ready for Review, Cloud Pulse, Cloud Pulse - Alerting

#12192 upcoming: [DI-24984] - Changes for removing tags filter from linode config in CloudPulse dashboards
  packages/manager/.changeset/pr-12192-upcoming-features-1747052321803.md
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.test.tsx
Labels: Approved, Cloud Pulse

#12197 change: [M3-9942-M3-9923-M3-9967] - Quotas UI updates for GA
  packages/manager/.changeset/pr-12197-changed-1747075597631.md
  packages/manager/src/features/Account/AccountLanding.tsx
  packages/manager/src/features/Account/Quotas/Quotas.tsx
  packages/manager/src/features/Account/Quotas/QuotasIncreaseForm.test.tsx
  packages/manager/src/features/Account/Quotas/QuotasIncreaseForm.tsx
  packages/manager/src/features/Account/Quotas/QuotasTable.tsx
  packages/manager/src/features/Account/Quotas/QuotasTableRow.tsx
  packages/manager/src/features/Account/Quotas/utils.test.tsx
  packages/manager/src/features/Account/Quotas/utils.ts
Labels: 🚨 Urgent, Approved, Limits

#12200 fix: [M3-9969] - Fix console warnings related to first-child pseudo class in LandingHeader component
  packages/manager/.changeset/pr-12200-fixed-1747084073178.md
  packages/manager/src/components/LandingHeader/LandingHeader.tsx
Labels: 🚨 Urgent, Approved

#12180 upcoming: [M3-9918] - Add Alerts legacy-beta preference toggle
  packages/manager/.changeset/pr-12180-upcoming-features-1746791691694.md
  packages/manager/src/features/Linodes/LinodesDetail/AclpPreferenceToggle.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/AclpPreferenceToggle.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAlerts/LinodeAlerts.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeMetrics/AclpMetricsPreferenceToggle.test.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeMetrics/AclpMetricsPreferenceToggle.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeMetrics/LinodeMetrics.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
  packages/utilities/src/types/ManagerPreferences.ts
Labels: Approved, Linodes, ACLP Integration

#12183 feat: [UIE-8618] - IAM RBAC: fix styles for the Assigned Roles Table
  packages/manager/.changeset/pr-12183-upcoming-features-1746799688079.md
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
  packages/manager/src/features/IAM/Shared/AssignedRolesTable/utils.ts
  packages/manager/src/features/IAM/Shared/types.ts
  packages/manager/src/features/IAM/Shared/utilities.test.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
  packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
  packages/manager/src/features/IAM/Users/UserEntities/utils.test.ts
  packages/manager/src/features/IAM/Users/UserEntities/utils.ts
  packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
Labels: Approved, IAM (Identity & Access Management)

#12216 fix: [M3-9957] - Remove the feature flag check so that beta customers can add Node Pools to existing LKE-E cluster
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
Labels: Approved, LKE-Enterprise

#12182 feat: [UIE-8734] - IAM RBAC - Assign Selected Roles drawer
  packages/manager/.changeset/pr-12182-added-1746798254647.md
  packages/manager/src/features/IAM/Roles/RolesTable/AssignSelectedRolesDrawer.tsx
  packages/manager/src/features/IAM/Roles/RolesTable/AssignSingleSelectedRole.tsx
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.tsx
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTableActionMenu.tsx
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.style.ts
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
  packages/manager/src/features/IAM/Shared/utilities.test.ts
  packages/manager/src/features/IAM/Shared/utilities.ts
Labels: 🚨 Urgent, Approved, IAM (Identity & Access Management)

#12155 upcoming: [DPS-33104] DataStream: routes, feature flag, tabs
  packages/manager/.changeset/pr-12155-upcoming-features-1746446424705.md
  packages/manager/eslint.config.js
  packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/DataStream/DataStreamLanding.tsx
  packages/manager/src/features/DataStream/Destinations/Destinations.tsx
  packages/manager/src/features/DataStream/Streams/Streams.tsx
  packages/manager/src/routes/datastream/DataStreamRoute.tsx
  packages/manager/src/routes/datastream/dataStreamLazyRoutes.ts
  packages/manager/src/routes/datastream/index.ts
  packages/manager/src/routes/index.tsx
Labels: Approved, Cloud Pulse - Logging

#12215 change: [M3-9947] - Remove Accordion wrapper from default Alerts tab on Linode details page
  packages/manager/.changeset/pr-12215-changed-1747223125401.md
  packages/manager/.changeset/pr-12215-fixed-1747230804629.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
  packages/ui/src/components/Paper/Paper.tsx
Labels: Approved, Linodes, ACLP Integration

#12218 test: [M3-9619] - Un-skip Cypress Firewall E2E tests
  packages/manager/.changeset/pr-12218-tests-1747241849916.md
  packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/delete-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
  packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
  packages/manager/cypress/support/util/linodes.ts
Labels: Ready for Review

#12226 test: [M3-9985] - Exclude distributed regions from `chooseRegion` output by default
  packages/manager/.changeset/pr-12226-tests-1747314916451.md
  packages/manager/cypress/support/util/regions.ts
Labels: Approved

#12210 fix: [M3-9920] - Do not set ACL Revision ID to empty string on LKE clusters
  packages/manager/.changeset/pr-12210-fixed-1747239552927.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx
Labels: Bug, LKE, Approved, LKE-Enterprise

#12205 refactor: [M3-9375] - Move Images queries
  packages/manager/.changeset/pr-12205-tech-stories-1747256053421.md
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
  packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
  packages/manager/src/features/Images/ImagesLanding/EditImageDrawer.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Images.tsx
  packages/manager/src/features/Linodes/LinodeCreate/UserData/UserData.tsx
  packages/manager/src/features/Linodes/LinodeCreate/shared/LinodeSelectTableRow.tsx
  packages/manager/src/features/Linodes/LinodeCreate/shared/SelectLinodeCard.tsx
  packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
  packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/UserData.tsx
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  packages/manager/src/features/Search/useAPISearch.ts
  packages/manager/src/features/Search/useClientSideSearch.ts
  packages/manager/src/hooks/useEventHandlers.ts
  packages/queries/.changeset/pr-12205-added-1747256092908.md
  packages/queries/src/images/images.ts
  packages/queries/src/images/index.ts
  packages/queries/src/index.ts
Labels: Approved

#12207 fix: [M3-9668, M3-9538] - Fixed Formatting of the `volume status` and broken spacing in `MultipleIPInput` component
  packages/manager/.changeset/pr-12207-fixed-1747120917933.md
  packages/manager/cypress/e2e/core/volumes/clone-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/resize-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/update-volume.spec.ts
  packages/manager/cypress/e2e/core/volumes/upgrade-volume.spec.ts
  packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
  packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
  packages/manager/src/features/Images/ImagesLanding/ImageStatus.tsx
  packages/manager/src/features/Linodes/LinodeCreate/shared/LinodeSelectTableRow.tsx
  packages/manager/src/features/Linodes/LinodeCreate/shared/SelectLinodeCard.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/Linodes/transitions.ts
  packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodesTableRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/Volumes/VolumeTableRow.tsx
  packages/manager/src/mocks/serverHandlers.ts
  packages/utilities/src/helpers/formatStatus.test.ts
  packages/utilities/src/helpers/formatStatus.ts
  packages/utilities/src/helpers/index.ts
Labels: Bug, Approved

#12219 chore: [M3-8716] - Upgrade sentry to v9
  packages/manager/.changeset/pr-12219-tech-stories-1747251063145.md
  packages/manager/package.json
  packages/manager/src/exceptionReporting.ts
  packages/manager/src/features/ErrorBoundary/ErrorBoundaryFallback.tsx
  packages/manager/src/features/ErrorBoundary/ErrorComponent.tsx
  packages/manager/src/initSentry.ts
  packages/manager/src/queries/cloudpulse/services.ts
  pnpm-lock.yaml
Labels: Tech Debt

#12208 fix: [M3-9968] - Input placholder opacity
  packages/ui/.changeset/pr-12208-fixed-1747157830376.md
  packages/ui/src/foundations/themes/light.ts
Labels: Approved

#12223 chore: Remove `useAccountManagement` hook and fix some restricted user UI
  packages/api-v4/.changeset/pr-12223-removed-1747346374792.md
  packages/api-v4/src/account/types.ts
  packages/manager/.changeset/pr-12223-fixed-1747346453830.md
  packages/manager/.changeset/pr-12223-tech-stories-1747346603680.md
  packages/manager/cypress/e2e/core/account/account-cancellation.spec.ts
  packages/manager/cypress/e2e/core/account/account-linode-managed.spec.ts
  packages/manager/cypress/e2e/core/account/account-login-history.spec.ts
  packages/manager/cypress/e2e/core/account/display-settings.spec.ts
  packages/manager/cypress/e2e/core/account/restricted-user-details-pages.spec.ts
  packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-access-keys-gen2.spec.ts
  packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
  packages/manager/cypress/e2e/core/parentChild/token-scopes.spec.ts
  packages/manager/src/GoTo.tsx
  packages/manager/src/components/StackScript/StackScript.tsx
  packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
  packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyActionMenu.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTable.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTableRow.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
  packages/manager/src/features/ObjectStorage/AccessKeyLanding/ViewPermissionsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketLandingEmptyState.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
  packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
  packages/manager/src/features/ObjectStorage/hooks/useIsObjectStorageGen2Enabled.tsx
  packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
  packages/manager/src/features/Support/SupportTickets/ticketUtils.ts
  packages/manager/src/features/TopMenu/UserMenu/UserMenuPopover.tsx
  packages/manager/src/features/Volumes/VolumesLanding.tsx
  packages/manager/src/hooks/useAccountManagement.ts
  packages/utilities/src/factories/grants.ts
Labels: Approved, Clean Up, Restricted User Access

#12217 fix: [M3-9737] - NodeBalancer queries
  packages/api-v4/.changeset/pr-12217-changed-1747239928776.md
  packages/api-v4/src/nodebalancers/types.ts
  packages/manager/.changeset/pr-12217-fixed-1747241027159.md
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
  packages/queries/.changeset/pr-12217-removed-1747241598724.md
  packages/queries/src/nodebalancers/index.ts
  packages/queries/src/nodebalancers/keys.ts
  packages/queries/src/nodebalancers/nodebalancers.ts
  packages/queries/src/nodebalancers/requests.ts
  packages/utilities/src/factories/nodebalancer.ts
Labels: React Query, Approved

#12181 upcoming: [M3-9783] - Add VPC Section in the Nodebalancer create flow
  packages/api-v4/src/nodebalancers/nodebalancers.ts
  packages/api-v4/src/nodebalancers/types.ts
  packages/manager/.changeset/pr-12181-upcoming-features-1746797606970.md
  packages/manager/cypress/e2e/core/nodebalancers/nodebalancer-create-with-vpc.spec.ts
  packages/manager/cypress/support/intercepts/nodebalancers.ts
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
  packages/manager/src/features/NodeBalancers/VPCPanel.test.tsx
  packages/manager/src/features/NodeBalancers/VPCPanel.tsx
  packages/manager/src/features/VPCs/constants.ts
  packages/queries/src/nodebalancers/nodebalancers.ts
  packages/validation/.changeset/pr-12181-fixed-1746797740109.md
  packages/validation/src/nodebalancers.schema.ts
Labels: Ready for Review, NB-VPC

#12162 upcoming: [M3-9784] - Show VPC details in the Nodebalancer summary page
  packages/manager/.changeset/pr-12162-upcoming-features-1746512536804.md
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.test.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
  packages/queries/src/nodebalancers/keys.ts
  packages/queries/src/nodebalancers/nodebalancers.ts
  packages/utilities/src/factories/nodebalancer.ts
Labels: Approved, NB-VPC

#12236 upcoming: [M3-9989, M3-9919] - Add beta ACLP contextual alerts to Alerts tab on Linode details page
  packages/manager/.changeset/pr-12236-upcoming-features-1747395107850.md
  packages/manager/src/features/Linodes/LinodesDetail/LinodeAlerts/LinodeAlerts.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
Labels: Add'tl Approval Needed, Linodes, ACLP Integration

#12237 test: [M3-9595] - Firewall create page for restricted users
  packages/manager/.changeset/pr-12237-tests-1747403119751.md
  packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts
Labels: Approved

#12255 Release v1.142.1 - staging → master
  packages/manager/CHANGELOG.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/package.json
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeClusterSpecs.tsx
Labels: Release, Hotfix

#12052 refactor: [M3-9647] - Reduce api requests made for every keystroke in Volume attach drawer
  packages/manager/.changeset/pr-12052-tech-stories-1744889150021.md
  packages/manager/src/features/Volumes/Drawers/VolumeDrawer/LinodeVolumeAttachForm.tsx
  packages/manager/src/features/Volumes/Drawers/VolumeDrawer/VolumeSelect.tsx
Labels: Bug, Approved

#12252 fix: [M3-9900] - Simplify `linode_resize` started event
  packages/manager/.changeset/pr-12252-fixed-1747765254237.md
  packages/manager/src/features/Events/factories/linode.tsx
Labels: Approved

#12243 upcoming: [M3-9999] - Event message tweaks for Linode Interfaces
  packages/manager/.changeset/pr-12243-upcoming-features-1747670800164.md
  packages/manager/src/components/Snackbar/ToastNotifications.stories.tsx
  packages/manager/src/features/Events/factories/interface.tsx
  packages/manager/src/features/Events/utils.test.tsx
  packages/manager/src/features/Events/utils.tsx
  packages/manager/src/hooks/useEventHandlers.ts
  packages/manager/src/queries/linodes/events.ts
Labels: Linode Interfaces

#12244 chore: [M3-9606] - Use `unstable_createBreakpoints` to define our MUI breakpoints
  packages/manager/.changeset/pr-12244-tech-stories-1747680484622.md
  packages/ui/src/foundations/breakpoints.ts
Labels: Approved, Tech Debt

#12221 refactor: [M3-9384] - Move Quotas queries
  packages/manager/.changeset/pr-12221-tech-stories-1747257942556.md
  packages/manager/src/features/Account/Quotas/QuotasTable.test.tsx
  packages/manager/src/features/Account/Quotas/QuotasTable.tsx
  packages/queries/.changeset/pr-12221-added-1747257990334.md
  packages/queries/src/index.ts
  packages/queries/src/quotas/index.ts
  packages/queries/src/quotas/keys.ts
  packages/queries/src/quotas/quotas.ts
  packages/queries/src/quotas/requests.ts
Labels: Approved, Modularization

#12227 feat: [UIE-8140, UIE-8662, UIE-8769] - IAM RBAC: fix bugs for the drawer
  packages/manager/.changeset/pr-12227-upcoming-features-1747318764898.md
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTableExpandedRow.test.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.test.tsx
  packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.style.ts
  packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx
  packages/manager/src/features/IAM/Users/UserRoles/AssignSingleRole.tsx
Labels: Approved, IAM (Identity & Access Management)

#12224 refactor: [M3-9656] - [Akamai Design System] Label Component
  packages/ui/.changeset/pr-12224-changed-1747294477261.md
  packages/ui/src/components/TextField/TextField.stories.tsx
  packages/ui/src/components/TextField/TextField.tsx
  packages/ui/src/components/TooltipIcon/TooltipIcon.stories.tsx
  packages/ui/src/components/TooltipIcon/TooltipIcon.tsx
  packages/ui/src/foundations/themes/dark.ts
  packages/ui/src/foundations/themes/light.ts
Labels: Add'tl Approval Needed, Ready for Review, Design Tokens

#12258 tech-story: [M3-10017] - Reroute /search
  packages/manager/.changeset/pr-12258-tech-stories-1747847887739.md
  packages/manager/eslint.config.js
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/Tag/Tag.tsx
  packages/manager/src/features/Search/SearchLanding.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
  packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.tsx
  packages/manager/src/routes/index.tsx
  packages/manager/src/routes/search/index.ts
  packages/manager/src/routes/search/searchLazyRoutes.ts
Labels: Approved, Routing Refactor

#12251 change: [M3-9997] - Update estimated time for LKE-E node pool pending creation message
  packages/manager/.changeset/pr-12251-upcoming-features-1747763494658.md
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
Labels: Approved, LKE-Enterprise

#12246 fix: [M3-9940] - Fix newest LKE-E kubernetes version not being selected by default in create flow
  packages/manager/.changeset/pr-12246-upcoming-features-1747750319787.md
  packages/manager/src/factories/kubernetesCluster.ts
  packages/manager/src/features/Kubernetes/kubeUtils.test.ts
  packages/manager/src/features/Kubernetes/kubeUtils.ts
  packages/manager/src/mocks/presets/crud/handlers/kubernetes.ts
  packages/utilities/src/helpers/sort-by.ts
Labels: Bug, Approved, LKE-Enterprise

#12265 fix: [M3-10008] - Fix erroneous Sentry error condition in Adobe Analytics hook
  packages/manager/.changeset/pr-12265-tech-stories-1747931205927.md
  packages/manager/src/constants.ts
  packages/manager/src/hooks/useAdobeAnalytics.ts
Labels: Approved, Analytics

#12266 fix: [M3-10011] - Disable the Kubernetes Dashboard request for LKE-E clusters
  packages/manager/.changeset/pr-12266-upcoming-features-1747938663753.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
  packages/manager/src/queries/kubernetes.ts
Labels: Bug, Approved, LKE-Enterprise

#12267 chore: [M3-10036] - Re-add `eslint-plugin-react-refresh` eslint plugin
  package.json
  packages/manager/.changeset/pr-12267-tech-stories-1747942707347.md
  packages/manager/eslint.config.js
  packages/manager/src/components/Avatar/Avatar.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDisks.tsx
  packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx
  packages/manager/src/features/Linodes/LinodesDetail/utilities.ts
  packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
  pnpm-lock.yaml
Labels: Tooling

#12272 fix: [M3-100041] - Make `quota_id` type a string
  packages/api-v4/.changeset/pr-12272-fixed-1748009649223.md
  packages/api-v4/src/quotas/quotas.ts
  packages/api-v4/src/quotas/types.ts
  packages/manager/.changeset/pr-12272-fixed-1748009662401.md
  packages/manager/src/factories/quotas.ts
  packages/manager/src/mocks/presets/crud/handlers/quotas.ts
  packages/queries/src/quotas/keys.ts
  packages/queries/src/quotas/quotas.ts
Labels: 🚨 Urgent, Approved

#12254 chore: [M3-10007] - Shared TypeScript configuration for packages
  packages/api-v4/package.json
  packages/api-v4/tsconfig.json
  packages/manager/package.json
  packages/manager/tsconfig.json
  packages/queries/package.json
  packages/queries/tsconfig.json
  packages/search/package.json
  packages/search/tsconfig.json
  packages/shared/package.json
  packages/shared/tsconfig.json
  packages/tsconfig/package.json
  packages/tsconfig/tsconfig.emit-types.json
  packages/tsconfig/tsconfig.non-strict.json
  packages/tsconfig/tsconfig.package.json
  packages/tsconfig/tsconfig.react.json
  packages/ui/package.json
  packages/ui/tsconfig.json
  packages/utilities/package.json
  packages/utilities/tsconfig.json
  packages/validation/package.json
  packages/validation/tsconfig.json
  pnpm-lock.yaml
Labels: Approved, Tooling

#12242 tech-story: [M3-9983] - Reroute Support/Help
  packages/manager/.changeset/pr-12242-tech-stories-1747759885067.md
  packages/manager/cypress/e2e/core/account/account-linode-managed.spec.ts
  packages/manager/cypress/support/ui/constants.ts
  packages/manager/eslint.config.js
  packages/manager/src/MainContent.tsx
  packages/manager/src/components/AccountActivation/AccountActivationLanding.test.tsx
  packages/manager/src/components/AccountActivation/AccountActivationLanding.tsx
  packages/manager/src/components/MaintenanceBanner/MaintenanceBanner.tsx
  packages/manager/src/components/SupportLink/SupportLink.tsx
  packages/manager/src/env.d.ts
  packages/manager/src/features/Events/FormattedEventMessage.test.tsx
  packages/manager/src/features/Help/HelpLanding.test.tsx
  packages/manager/src/features/Help/Panels/AlgoliaSearchBar.tsx
  packages/manager/src/features/Help/SupportSearchLanding/HelpResources.tsx
  packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.test.tsx
  packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.tsx
  packages/manager/src/features/Help/index.tsx
  packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
  packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
  packages/manager/src/features/Linodes/SMTPRestrictionText.test.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
  packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
  packages/manager/src/features/Managed/ManagedDashboardCard/MonitorTickets.tsx
  packages/manager/src/features/NotificationCenter/useFormattedNotifications.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.test.tsx
  packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.test.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.test.tsx
  packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
  packages/manager/src/features/Support/SupportTickets/TicketList.test.tsx
  packages/manager/src/features/Support/SupportTickets/TicketList.tsx
  packages/manager/src/features/Support/SupportTickets/index.tsx
  packages/manager/src/hooks/useOrderV2.ts
  packages/manager/src/routes/account/index.ts
  packages/manager/src/routes/images/index.ts
  packages/manager/src/routes/index.tsx
  packages/manager/src/routes/longview/index.ts
  packages/manager/src/routes/support/index.ts
  packages/manager/src/routes/support/supportLazyRoutes.tsx
  packages/manager/src/utilities/logic-query-parser.d.ts
  packages/manager/src/utilities/search-string.d.ts
Labels: Approved, Routing Refactor

#12269 fix: [M3-9990] - Image Select overflows off screen on mobile viewports
  packages/manager/.changeset/pr-12269-fixed-1747981241068.md
  packages/manager/src/components/ImageSelect/ImageSelect.tsx
  packages/manager/src/features/Linodes/LinodeCreate/Tabs/Images.tsx
Labels: Bug, Approved

#12268 change: [M3-9687] - Prepare LKE APL for GA
  packages/manager/.changeset/pr-12268-changed-1747968191432.md
  packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
  packages/manager/src/dev-tools/FeatureFlagTool.tsx
  packages/manager/src/featureFlags.ts
  packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
  packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
  packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
  packages/manager/src/features/Kubernetes/kubeUtils.ts
Labels: 🚨 Urgent, APL

#12256 upcoming: M3-9792 - Add VPC column to the Nodebalancer Landing table
  packages/manager/.changeset/pr-12256-upcoming-features-1747817841341.md
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerVPC.tsx
  packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
Labels: 🚨 Urgent, Approved, NB-VPC

#12249 feat: [UIE-8766] - IAM RBAC: fix bugs for the assigned roles table
  packages/manager/.changeset/pr-12249-upcoming-features-1747752128426.md
  packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.style.ts
  packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx
  packages/manager/src/queries/iam/iam.ts
Labels: Approved, IAM (Identity & Access Management)

#12232 upcoming: [M3-9785, M3-9788, M3-10040] - Added NodeBalacer Table and replace Linodes with Resources and remove "Label" text from Subnet and Linode Column
  packages/manager/.changeset/pr-12232-upcoming-features-1747645656510.md
  packages/manager/src/factories/subnets.ts
  packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetNodebalancerRow.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/SubnetNodebalancerRow.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx
  packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCRow.test.tsx
  packages/manager/src/features/VPCs/VPCLanding/VPCRow.tsx
  packages/manager/src/features/VPCs/utils.test.ts
  packages/manager/src/features/VPCs/utils.ts
Labels: Do Not Merge, Ready for Review, NB-VPC

#12259 test: [M3-9176] - Add integration test for Upgrade to new Linode Interface flow
  packages/manager/.changeset/pr-12259-tests-1747849345030.md
  packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
  packages/manager/cypress/e2e/core/linodes/upgrade-linode-interface.spec.ts
  packages/manager/cypress/support/constants/linode-interfaces.ts
  packages/manager/cypress/support/intercepts/linodes.ts
  packages/manager/cypress/support/util/linodes.ts
  packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/ConfigSelectDialogContent.tsx
  packages/utilities/src/factories/linodeInterface.ts
Labels: Testing, Linode Interfaces

#12264 feat: [UIE-8792] - add pagination to Roles table
  packages/manager/.changeset/pr-12264-upcoming-features-1747926067938.md
  packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.tsx
  packages/manager/src/features/IAM/Shared/constants.ts
Labels: Approved, IAM (Identity & Access Management)

#12278 upcoming: [DPS-33114] Add General Information and Data Set forms
  packages/manager/.changeset/pr-12278-upcoming-features-1748242133984.md
  packages/manager/src/features/DataStream/Streams/StreamCreate/EventTypeDetails.tsx
  packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreate.styles.ts
  packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreate.tsx
  packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreateDataSet.test.tsx
  packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreateDataSet.tsx
  packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreateDataSetData.ts
  packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreateGeneralInfo.test.tsx
  packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreateGeneralInfo.tsx
  packages/manager/src/features/DataStream/Streams/StreamCreate/types.ts
Labels: Approved

#12271 test: [M3-9967] - Add tests for Quotas tab endpoint selection
  packages/manager/.changeset/pr-12271-tests-1748369901745.md
  packages/manager/cypress/e2e/core/account/quotas.spec.ts
  packages/manager/cypress/support/intercepts/object-storage.ts
  packages/manager/src/features/Account/Quotas/QuotasTable.tsx
Labels: Testing, Approved, Limits

#12300 change: [M3-10061] - Update copy for LKE premium CPU notice
  packages/manager/CHANGELOG.md
  packages/manager/src/features/Kubernetes/CreateCluster/PremiumCPUPlanNotice.tsx
Labels: 🚨 Urgent, LKE, Approved, LKE-Enterprise
